// filepath: pcc/pcc_long_term_care_ext102/pcc_long_term_care_ext102_engine.js
module.exports.version='v3.69.69.0';
module.exports.module='pcc_long_term_care_ext102';
module.exports.functions={};
module.exports.functions['LTCGenExt']=function(input){const score=Math.round((0.18 + Number(input.ltGen||1)*0.2 + Number(input.ltGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.69.69.0',module:'pcc_long_term_care_ext102',function:'LTCGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LTCAdmitExt']=function(input){const score=Math.round((0.18 + Number(input.ltAdm||1)*0.2 + Number(input.ltAdmType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.69.69.0',module:'pcc_long_term_care_ext102',function:'LTCAdmitExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LTCCarePlanExt']=function(input){const score=Math.round((0.18 + Number(input.ltCP||1)*0.2 + Number(input.ltCPScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.69.69.0',module:'pcc_long_term_care_ext102',function:'LTCCarePlanExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LTCMedExt']=function(input){const score=Math.round((0.18 + Number(input.ltMed||1)*0.2 + Number(input.ltMedNum||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.69.69.0',module:'pcc_long_term_care_ext102',function:'LTCMedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LTCActivityExt']=function(input){const score=Math.round((0.18 + Number(input.ltAct||1)*0.2 + Number(input.ltActScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.69.69.0',module:'pcc_long_term_care_ext102',function:'LTCActivityExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LTCNutrExt']=function(input){const score=Math.round((0.18 + Number(input.ltNut||1)*0.2 + Number(input.ltNutScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.69.69.0',module:'pcc_long_term_care_ext102',function:'LTCNutrExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LTCDementiaExt']=function(input){const score=Math.round((0.18 + Number(input.ltDem||1)*0.2 + Number(input.ltDemScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.69.69.0',module:'pcc_long_term_care_ext102',function:'LTCDementiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LTCWoundExt']=function(input){const score=Math.round((0.18 + Number(input.ltWnd||1)*0.2 + Number(input.ltWndStage||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.69.69.0',module:'pcc_long_term_care_ext102',function:'LTCWoundExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LTCInfecExt']=function(input){const score=Math.round((0.18 + Number(input.ltInf||1)*0.2 + Number(input.ltInfType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.69.69.0',module:'pcc_long_term_care_ext102',function:'LTCInfecExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LTCDischExt']=function(input){const score=Math.round((0.18 + Number(input.ltDis||1)*0.2 + Number(input.ltDisType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.69.69.0',module:'pcc_long_term_care_ext102',function:'LTCDischExt',input,score,ts:new Date().toISOString()}};

// TS: v3.69.69.0
