// Auto-generated by gen_p3master.py -- PCC 3.205.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.205.0';

function EXT6AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.ext6) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_rheum_ext6', function: 'EXT6AssessmentExt', input, score, ts: TS };
}

function EXT6ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.ext6) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_rheum_ext6', function: 'EXT6ScoreExt', input, score, ts: TS };
}

function EXT6StageExt(input) {
  const score = Math.round((0.3 + (Number(input.ext6) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_rheum_ext6', function: 'EXT6StageExt', input, score, ts: TS };
}

function EXT6PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.ext6) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_rheum_ext6', function: 'EXT6PlanExt', input, score, ts: TS };
}

function EXT6RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.ext6) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_rheum_ext6', function: 'EXT6RiskExt', input, score, ts: TS };
}

function EXT6DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.ext6) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_rheum_ext6', function: 'EXT6DoseExt', input, score, ts: TS };
}

function EXT6FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.ext6) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_rheum_ext6', function: 'EXT6FrequencyExt', input, score, ts: TS };
}

function EXT6DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.ext6) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_rheum_ext6', function: 'EXT6DurationExt', input, score, ts: TS };
}

function EXT6FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.ext6) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_rheum_ext6', function: 'EXT6FollowupExt', input, score, ts: TS };
}

function EXT6OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.ext6) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_rheum_ext6', function: 'EXT6OutcomeExt', input, score, ts: TS };
}

module.exports = {
  EXT6AssessmentExt,
  EXT6ScoreExt,
  EXT6StageExt,
  EXT6PlanExt,
  EXT6RiskExt,
  EXT6DoseExt,
  EXT6FrequencyExt,
  EXT6DurationExt,
  EXT6FollowupExt,
  EXT6OutcomeExt,
};