// filepath: pcc/pcc_pediatric_neuro_ext155/pcc_pediatric_neuro_ext155_engine.js
module.exports.version='v3.265.0';
module.exports.module='pcc_pediatric_neuro_ext155';
module.exports.functions={};
module.exports.functions['PediatricTetheredExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.tethered||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.265.0',module:'pcc_pediatric_neuro_ext155',function:'PediatricTetheredExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricScoliNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.scoliNeuro||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.265.0',module:'pcc_pediatric_neuro_ext155',function:'PediatricScoliNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDiscitisExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.discitis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.265.0',module:'pcc_pediatric_neuro_ext155',function:'PediatricDiscitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEpiduralAbsExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pEpiduralAbs||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.265.0',module:'pcc_pediatric_neuro_ext155',function:'PediatricEpiduralAbsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTransverseMylExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTM||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.265.0',module:'pcc_pediatric_neuro_ext155',function:'PediatricTransverseMylExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCordTumorExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.cordTumor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.265.0',module:'pcc_pediatric_neuro_ext155',function:'PediatricCordTumorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSyringomyeliaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.syrinx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.265.0',module:'pcc_pediatric_neuro_ext155',function:'PediatricSyringomyeliaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChiarimalExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.chiariMal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.265.0',module:'pcc_pediatric_neuro_ext155',function:'PediatricChiarimalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinalTraumaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pSpinalTrauma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.265.0',module:'pcc_pediatric_neuro_ext155',function:'PediatricSpinalTraumaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinaBifidaExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.spinaBifida||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.265.0',module:'pcc_pediatric_neuro_ext155',function:'PediatricSpinaBifidaExt',input,score,ts:new Date().toISOString()}};

// TS: v3.265.0
