// filepath: pcc/pcc_pediatric_surg_ext177/pcc_pediatric_surg_ext177_engine.js
module.exports.version='v3.17.17.0';
module.exports.module='pcc_pediatric_surg_ext177';
module.exports.functions={};
module.exports.functions['PediatricMoveDrugTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.moveDrugTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_pediatric_surg_ext177',function:'PediatricMoveDrugTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBotulinumTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.botoxTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_pediatric_surg_ext177',function:'PediatricBotulinumTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDBSSurgExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pDBSSurg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_pediatric_surg_ext177',function:'PediatricDBSSurgExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricITBSurgExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pITBSurg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_pediatric_surg_ext177',function:'PediatricITBSurgExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDystoniaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pDystoniaSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_pediatric_surg_ext177',function:'PediatricDystoniaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChoreaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pChoreaSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_pediatric_surg_ext177',function:'PediatricChoreaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTicCBTExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTicCBT||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_pediatric_surg_ext177',function:'PediatricTicCBTExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAtaxiaRehabExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAtaxiaRehab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_pediatric_surg_ext177',function:'PediatricAtaxiaRehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMyoTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pMyoTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_pediatric_surg_ext177',function:'PediatricMyoTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTremorTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTremorTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_pediatric_surg_ext177',function:'PediatricTremorTxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.17.17.0
