// filepath: pcc/pcc_rad_ext179/pcc_rad_ext179_engine.js
module.exports.version='v3.15.15.0';
module.exports.module='pcc_rad_ext179';
module.exports.functions={};
module.exports.functions['RadDiabetesAdultExt']=function(input){const score=Math.round((0.18 + Number(input.radDM||1)*0.2 + Number(input.dmImaging||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_rad_ext179',function:'RadDiabetesAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadCardiacAdultExt']=function(input){const score=Math.round((0.18 + Number(input.radCardiac||1)*0.2 + Number(input.ejectionFrac||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_rad_ext179',function:'RadCardiacAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadRenalAdultExt']=function(input){const score=Math.round((0.18 + Number(input.radRenal||1)*0.2 + Number(input.renalCystic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_rad_ext179',function:'RadRenalAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadLiverAdultExt']=function(input){const score=Math.round((0.18 + Number(input.radLiver||1)*0.2 + Number(input.liverFat||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_rad_ext179',function:'RadLiverAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadVascularAdultExt']=function(input){const score=Math.round((0.18 + Number(input.radVasc||1)*0.2 + Number(input.stenosis||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_rad_ext179',function:'RadVascularAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadPulmAdultExt']=function(input){const score=Math.round((0.18 + Number(input.radPulm||1)*0.2 + Number(input.pulmFinding||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_rad_ext179',function:'RadPulmAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadMusculoskeletalAdultExt']=function(input){const score=Math.round((0.18 + Number(input.radMSK||1)*0.2 + Number(input.fracture||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_rad_ext179',function:'RadMusculoskeletalAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadInfectAdultExt']=function(input){const score=Math.round((0.18 + Number(input.radInf||1)*0.2 + Number(input.infectLoc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_rad_ext179',function:'RadInfectAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadOBAdultExt']=function(input){const score=Math.round((0.18 + Number(input.radOB||1)*0.2 + Number(input.gestAge||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_rad_ext179',function:'RadOBAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadGUAdultExt']=function(input){const score=Math.round((0.18 + Number(input.radGU||1)*0.2 + Number(input.guFinding||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_rad_ext179',function:'RadGUAdultExt',input,score,ts:new Date().toISOString()}};

// TS: v3.15.15.0
