// filepath: pcc/pcc_pediatric_surg_ext142/pcc_pediatric_surg_ext142_engine.js
module.exports.version='v3.252.0';
module.exports.module='pcc_pediatric_surg_ext142';
module.exports.functions={};
module.exports.functions['PediatricNeuroSarcRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_surg_ext142',function:'PediatricNeuroSarcRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBehcetRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.colchicine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_surg_ext142',function:'PediatricBehcetRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeuroLupusRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pSLERx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_surg_ext142',function:'PediatricNeuroLupusRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVasculitisRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.cyclophos||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_surg_ext142',function:'PediatricVasculitisRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricADEMsteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ademSteroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_surg_ext142',function:'PediatricADEMsteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMSDiseaseModExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.dmt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_surg_ext142',function:'PediatricMSDiseaseModExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNMOeculizumabExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.eculizumab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_surg_ext142',function:'PediatricNMOeculizumabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMOGIVIGExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.mogIVIG||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_surg_ext142',function:'PediatricMOGIVIGExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAESteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.aeSteroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_surg_ext142',function:'PediatricAESteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFIRESketogenicExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.keto||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_surg_ext142',function:'PediatricFIRESketogenicExt',input,score,ts:new Date().toISOString()}};

// TS: v3.252.0
