// filepath: pcc/pcc_pediatric_surg_ext138/pcc_pediatric_surg_ext138_engine.js
module.exports.version='v3.248.0';
module.exports.module='pcc_pediatric_surg_ext138';
module.exports.functions={};
module.exports.functions['PediatricNF1MgmtExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.mgmt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_surg_ext138',function:'PediatricNF1MgmtExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTSCSurgeryExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_surg_ext138',function:'PediatricTSCSurgeryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSturgeLaserExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.laser||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_surg_ext138',function:'PediatricSturgeLaserExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricATMgmtExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.atMgmt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_surg_ext138',function:'PediatricATMgmtExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVHLScreenExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.vhlScreen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_surg_ext138',function:'PediatricVHLScreenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMitoSuppExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.mitoSupp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_surg_ext138',function:'PediatricMitoSuppExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDravetRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.stiripentol||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_surg_ext138',function:'PediatricDravetRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDravetCannabExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cbd||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_surg_ext138',function:'PediatricDravetCannabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWestSteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.acth||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_surg_ext138',function:'PediatricWestSteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVigabatrinExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.vigabatrin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_surg_ext138',function:'PediatricVigabatrinExt',input,score,ts:new Date().toISOString()}};

// TS: v3.248.0
