// filepath: pcc/pcc_pediatric_neuro_ext86/pcc_pediatric_neuro_ext86_engine.js
// pcc_pediatric_neuro_ext86 engine (deterministic)
module.exports.version='v3.196.0';
module.exports.module='pcc_pediatric_neuro_ext86';
module.exports.functions={};
module.exports.functions['PediatricHeadacheClinicExt']=function(input){const score=Math.round((0.15 + Number(input.freq||5)*0.04 + Number(input.disability||30)*0.01 + Number(input.schoolDays||3)*0.1)*100)/100;return{version:'v3.196.0',module:'pcc_pediatric_neuro_ext86',function:'PediatricHeadacheClinicExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricMigraineProphyExt']=function(input){const score=Math.round((0.2 + Number(input.freq||4)*0.05 + Number(input.med||1)*0.15 + Number(input.response||1)*0.2)*100)/100;return{version:'v3.196.0',module:'pcc_pediatric_neuro_ext86',function:'PediatricMigraineProphyExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricChronicMigraineMgmExt']=function(input){const score=Math.round((0.18 + Number(input.days||15)*0.01 + Number(input.cbt||1)*0.2 + Number(input.med||1)*0.15)*100)/100;return{version:'v3.196.0',module:'pcc_pediatric_neuro_ext86',function:'PediatricChronicMigraineMgmExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCGRPForMigraineExt']=function(input){const score=Math.round((0.15 + Number(input.drug||1)*0.2 + Number(input.response||1)*0.2 + Number(input.weight||40)*0.005)*100)/100;return{version:'v3.196.0',module:'pcc_pediatric_neuro_ext86',function:'PediatricCGRPForMigraineExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricClusterHeadacheExt']=function(input){const score=Math.round((0.15 + Number(input.freq||2)*0.1 + Number(input.oxygen||1)*0.2 + Number(input.age||12)*0.02)*100)/100;return{version:'v3.196.0',module:'pcc_pediatric_neuro_ext86',function:'PediatricClusterHeadacheExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricTensionHeadacheExt']=function(input){const score=Math.round((0.15 + Number(input.stress||5)*0.05 + Number(input.relax||1)*0.2 + Number(input.responder||1)*0.2)*100)/100;return{version:'v3.196.0',module:'pcc_pediatric_neuro_ext86',function:'PediatricTensionHeadacheExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricConcussionHeadacheExt']=function(input){const score=Math.round((0.18 + Number(input.days||7)*0.05 + Number(input.symptoms||3)*0.05 + Number(input.sport||1)*0.2)*100)/100;return{version:'v3.196.0',module:'pcc_pediatric_neuro_ext86',function:'PediatricConcussionHeadacheExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricPseudotumorExt']=function(input){const score=Math.round((0.18 + Number(input.opening||25)*0.01 + Number(input.diamox||1)*0.2 + Number(input.papilledema||1)*0.2)*100)/100;return{version:'v3.196.0',module:'pcc_pediatric_neuro_ext86',function:'PediatricPseudotumorExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricMigraineMimicsExt']=function(input){const score=Math.round((0.15 + Number(input.localizing||1)*0.2 + Number(input.redFlags||1)*0.2 + Number(input.imaging||1)*0.15)*100)/100;return{version:'v3.196.0',module:'pcc_pediatric_neuro_ext86',function:'PediatricMigraineMimicsExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricIdiopathicStuporExt']=function(input){const score=Math.round((0.15 + Number(input.duration||2)*0.15 + Number(input.eeg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.196.0',module:'pcc_pediatric_neuro_ext86',function:'PediatricIdiopathicStuporExt',input,score,ts:new Date().toISOString()};};

// TS: v3.196.0
