// filepath: pcc/pcc_neuro_ext186/pcc_neuro_ext186_engine.js
module.exports.version='v3.15.15.0';
module.exports.module='pcc_neuro_ext186';
module.exports.functions={};
module.exports.functions['CSFdisorderExt']=function(input){const score=Math.round((0.18 + Number(input.csfDisorder||1)*0.2 + Number(input.pressure||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_neuro_ext186',function:'CSFdisorderExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CSFleakSpontaneousExt']=function(input){const score=Math.round((0.18 + Number(input.csfLeak||1)*0.2 + Number(input.orthostatic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_neuro_ext186',function:'CSFleakSpontaneousExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CSFleakSpinalExt']=function(input){const score=Math.round((0.18 + Number(input.csfSpinalLeak||1)*0.2 + Number(input.epidural||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_neuro_ext186',function:'CSFleakSpinalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ChiariMalformationExt']=function(input){const score=Math.round((0.18 + Number(input.chiariMal||1)*0.2 + Number(input.tonsillar||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_neuro_ext186',function:'ChiariMalformationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SyringomyeliaExt']=function(input){const score=Math.round((0.18 + Number(input.syringo||1)*0.2 + Number(input.cordCyst||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_neuro_ext186',function:'SyringomyeliaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TetheredCordExt']=function(input){const score=Math.round((0.18 + Number(input.tethered||1)*0.2 + Number(input.filum||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_neuro_ext186',function:'TetheredCordExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ChiariDecompressionExt']=function(input){const score=Math.round((0.18 + Number(input.chiariDecomp||1)*0.2 + Number(input.decompression||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_neuro_ext186',function:'ChiariDecompressionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SpinaBifidaOccultaExt']=function(input){const score=Math.round((0.18 + Number(input.sbOcculta||1)*0.2 + Number(input.spinaBifida||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_neuro_ext186',function:'SpinaBifidaOccultaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HydrocephalusExt']=function(input){const score=Math.round((0.18 + Number(input.hydro||1)*0.2 + Number(input.evans||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_neuro_ext186',function:'HydrocephalusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PseudotumorExt']=function(input){const score=Math.round((0.18 + Number(input.pseudotumor||1)*0.2 + Number(input.iih||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_neuro_ext186',function:'PseudotumorExt',input,score,ts:new Date().toISOString()}};

// TS: v3.15.15.0
