// filepath: pcc/pcc_midwifery_nurse_ext102/pcc_midwifery_nurse_ext102_engine.js
module.exports.version='v3.73.73.0';
module.exports.module='pcc_midwifery_nurse_ext102';
module.exports.functions={};
module.exports.functions['MWNurseGenExt']=function(input){const score=Math.round((0.18 + Number(input.mnGen||1)*0.2 + Number(input.mnGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_midwifery_nurse_ext102',function:'MWNurseGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MWNurseAntenExt']=function(input){const score=Math.round((0.18 + Number(input.mnAnt||1)*0.2 + Number(input.mnAntWeek||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_midwifery_nurse_ext102',function:'MWNurseAntenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MWNurseIntrapartExt']=function(input){const score=Math.round((0.18 + Number(input.mnIntra||1)*0.2 + Number(input.mnIntraStage||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_midwifery_nurse_ext102',function:'MWNurseIntrapartExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MWNursePostExt']=function(input){const score=Math.round((0.18 + Number(input.mnPost||1)*0.2 + Number(input.mnPostDay||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_midwifery_nurse_ext102',function:'MWNursePostExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MWNurseNewbornExt']=function(input){const score=Math.round((0.18 + Number(input.mnNB||1)*0.2 + Number(input.mnNBDay||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_midwifery_nurse_ext102',function:'MWNurseNewbornExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MWNurseBFext']=function(input){const score=Math.round((0.18 + Number(input.mnBF||1)*0.2 + Number(input.mnBFscore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_midwifery_nurse_ext102',function:'MWNurseBFext',input,score,ts:new Date().toISOString()}};
module.exports.functions['MWNurseGYNExt']=function(input){const score=Math.round((0.18 + Number(input.mnGyn||1)*0.2 + Number(input.mnGynType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_midwifery_nurse_ext102',function:'MWNurseGYNExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MWNurseScreenExt']=function(input){const score=Math.round((0.18 + Number(input.mnScr||1)*0.2 + Number(input.mnScrType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_midwifery_nurse_ext102',function:'MWNurseScreenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MWNurseCommExt']=function(input){const score=Math.round((0.18 + Number(input.mnCom||1)*0.2 + Number(input.mnComType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_midwifery_nurse_ext102',function:'MWNurseCommExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MWNurseOutreachExt']=function(input){const score=Math.round((0.18 + Number(input.mnOut||1)*0.2 + Number(input.mnOutType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_midwifery_nurse_ext102',function:'MWNurseOutreachExt',input,score,ts:new Date().toISOString()}};

// TS: v3.73.73.0
