// Auto-generated by gen_p3master.py -- PCC 3.309.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.309.0';

function X351AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x351) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_351', function: 'X351AssessmentExt', input, score, ts: TS };
}

function X351ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x351) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_351', function: 'X351ScoreExt', input, score, ts: TS };
}

function X351StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x351) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_351', function: 'X351StageExt', input, score, ts: TS };
}

function X351PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x351) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_351', function: 'X351PlanExt', input, score, ts: TS };
}

function X351RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x351) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_351', function: 'X351RiskExt', input, score, ts: TS };
}

function X351DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x351) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_351', function: 'X351DoseExt', input, score, ts: TS };
}

function X351FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x351) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_351', function: 'X351FrequencyExt', input, score, ts: TS };
}

function X351DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x351) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_351', function: 'X351DurationExt', input, score, ts: TS };
}

function X351FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x351) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_351', function: 'X351FollowupExt', input, score, ts: TS };
}

function X351OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x351) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_351', function: 'X351OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X351AssessmentExt,
  X351ScoreExt,
  X351StageExt,
  X351PlanExt,
  X351RiskExt,
  X351DoseExt,
  X351FrequencyExt,
  X351DurationExt,
  X351FollowupExt,
  X351OutcomeExt,
};