// Auto_generated by gen_p3hb.py -- PCC v3.170.0
"use strict";
const TS = '2026-07-28T12:30:00Z';

function PediatricAEImmunotherapySurgExt(input) { const score = Math.round((0.4+Number(input.cycle_count||3)*0.08)*100)/100; return { version:'3.170.0', module:'pcc_pediatric_surg_ext60', function:"PediatricAEImmunotherapySurgExt", input, score, ts: TS }; }

function PediatricRituximabSurgExt(input) { const score = Math.round((0.4+Number(input.cdb19_count||50)*0.005)*100)/100; return { version:'3.170.0', module:'pcc_pediatric_surg_ext60', function:"PediatricRituximabSurgExt", input, score, ts: TS }; }

function PediatricCyclophosphamideExt(input) { const score = Math.round((0.4+Number(input.dose_g||1)*0.1)*100)/100; return { version:'3.170.0', module:'pcc_pediatric_surg_ext60', function:"PediatricCyclophosphamideExt", input, score, ts: TS }; }

function PediatricPlasmaExchangeSurgExt(input) { const score = Math.round((0.4+Number(input.exchanges||5)*0.05)*100)/100; return { version:'3.170.0', module:'pcc_pediatric_surg_ext60', function:"PediatricPlasmaExchangeSurgExt", input, score, ts: TS }; }

function PediatricIVIGAdminExt(input) { const score = Math.round((0.3+Number(input.dose_gkg||1)*0.15)*100)/100; return { version:'3.170.0', module:'pcc_pediatric_surg_ext60', function:"PediatricIVIGAdminExt", input, score, ts: TS }; }

function PediatricSteroidPulseSurgExt(input) { const score = Math.round((0.35+Number(input.pulse_count||3)*0.1)*100)/100; return { version:'3.170.0', module:'pcc_pediatric_surg_ext60', function:"PediatricSteroidPulseSurgExt", input, score, ts: TS }; }

function PediatricImmunosuppressantExt(input) { const score = Math.round((0.35+Number(input.drug_count||2)*0.1)*100)/100; return { version:'3.170.0', module:'pcc_pediatric_surg_ext60', function:"PediatricImmunosuppressantExt", input, score, ts: TS }; }

function PediatricBiologicInfusionExt(input) { const score = Math.round((0.4+Number(input.infusions||6)*0.05)*100)/100; return { version:'3.170.0', module:'pcc_pediatric_surg_ext60', function:"PediatricBiologicInfusionExt", input, score, ts: TS }; }

function PediatricTocilizumabExt(input) { const score = Math.round((0.4+Number(input.dose_mg||400)*0.0008)*100)/100; return { version:'3.170.0', module:'pcc_pediatric_surg_ext60', function:"PediatricTocilizumabExt", input, score, ts: TS }; }

function PediatricBortezomibExt(input) { const score = Math.round((0.5+Number(input.cycles||4)*0.05)*100)/100; return { version:'3.170.0', module:'pcc_pediatric_surg_ext60', function:"PediatricBortezomibExt", input, score, ts: TS }; }

module.exports = {
  PediatricAEImmunotherapySurgExt,
  PediatricRituximabSurgExt,
  PediatricCyclophosphamideExt,
  PediatricPlasmaExchangeSurgExt,
  PediatricIVIGAdminExt,
  PediatricSteroidPulseSurgExt,
  PediatricImmunosuppressantExt,
  PediatricBiologicInfusionExt,
  PediatricTocilizumabExt,
  PediatricBortezomibExt,
};