// Auto-generated by gen_p3master.py -- PCC 3.187.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.187.0';

function HTAAssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.htaa) || 0) * 0.2) * 100) / 100;
  return { version: VER, module: 'pcc_hypertension_advanced', function: 'HTAAssessmentExt', input, score, ts: TS };
}

function HTAScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.htas) || 0) * 0.31) * 100) / 100;
  return { version: VER, module: 'pcc_hypertension_advanced', function: 'HTAScoreExt', input, score, ts: TS };
}

function HTAStageExt(input) {
  const score = Math.round((0.3 + (Number(input.htas) || 0) * 0.32) * 100) / 100;
  return { version: VER, module: 'pcc_hypertension_advanced', function: 'HTAStageExt', input, score, ts: TS };
}

function HTAPlanExt(input) {
  const score = Math.round((0.3 + (Number(input.htap) || 0) * 0.28) * 100) / 100;
  return { version: VER, module: 'pcc_hypertension_advanced', function: 'HTAPlanExt', input, score, ts: TS };
}

function HTARiskExt(input) {
  const score = Math.round((0.3 + (Number(input.htar) || 0) * 0.29) * 100) / 100;
  return { version: VER, module: 'pcc_hypertension_advanced', function: 'HTARiskExt', input, score, ts: TS };
}

function HTADoseExt(input) {
  const score = Math.round((0.3 + (Number(input.htad) || 0) * 0.3) * 100) / 100;
  return { version: VER, module: 'pcc_hypertension_advanced', function: 'HTADoseExt', input, score, ts: TS };
}

function HTAFrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.htaf) || 0) * 0.21) * 100) / 100;
  return { version: VER, module: 'pcc_hypertension_advanced', function: 'HTAFrequencyExt', input, score, ts: TS };
}

function HTADurationExt(input) {
  const score = Math.round((0.3 + (Number(input.htad) || 0) * 0.17) * 100) / 100;
  return { version: VER, module: 'pcc_hypertension_advanced', function: 'HTADurationExt', input, score, ts: TS };
}

function HTAFollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.htaf) || 0) * 0.18) * 100) / 100;
  return { version: VER, module: 'pcc_hypertension_advanced', function: 'HTAFollowupExt', input, score, ts: TS };
}

function HTAOutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.htao) || 0) * 0.49) * 100) / 100;
  return { version: VER, module: 'pcc_hypertension_advanced', function: 'HTAOutcomeExt', input, score, ts: TS };
}

module.exports = {
  HTAAssessmentExt,
  HTAScoreExt,
  HTAStageExt,
  HTAPlanExt,
  HTARiskExt,
  HTADoseExt,
  HTAFrequencyExt,
  HTADurationExt,
  HTAFollowupExt,
  HTAOutcomeExt,
};