// Auto_generated by gen_p3hb.py -- PCC v3.170.0
"use strict";
const TS = '2026-07-28T12:30:00Z';

function AutoimmuneEncephalitisExt(input) { const score = Math.round((0.4+Number(input.antibodies||1)*0.15)*100)/100; return { version:'3.170.0', module:'pcc_neuro_ext71', function:"AutoimmuneEncephalitisExt", input, score, ts: TS }; }

function ParaneoplasticSyndromeExt(input) { const score = Math.round((0.45+Number(input.antibody_count||1)*0.1)*100)/100; return { version:'3.170.0', module:'pcc_neuro_ext71', function:"ParaneoplasticSyndromeExt", input, score, ts: TS }; }

function CerebralVasculitisExt(input) { const score = Math.round((0.4+Number(input.vessel_count||2)*0.08)*100)/100; return { version:'3.170.0', module:'pcc_neuro_ext71', function:"CerebralVasculitisExt", input, score, ts: TS }; }

function CNSLupusExt(input) { const score = Math.round((0.4+Number(input.sledai_score||10)*0.04)*100)/100; return { version:'3.170.0', module:'pcc_neuro_ext71', function:"CNSLupusExt", input, score, ts: TS }; }

function NeuroBehcetExt(input) { const score = Math.round((0.4+Number(input.ulcer_count||2)*0.1)*100)/100; return { version:'3.170.0', module:'pcc_neuro_ext71', function:"NeuroBehcetExt", input, score, ts: TS }; }

function SarcoidNeuroExt(input) { const score = Math.round((0.35+Number(input.cns_lesions||3)*0.08)*100)/100; return { version:'3.170.0', module:'pcc_neuro_ext71', function:"SarcoidNeuroExt", input, score, ts: TS }; }

function NeuroIgG4Ext(input) { const score = Math.round((0.4+Number(input.organs_involved||2)*0.1)*100)/100; return { version:'3.170.0', module:'pcc_neuro_ext71', function:"NeuroIgG4Ext", input, score, ts: TS }; }

function CLIPPERSOrNeuroBehcetExt(input) { const score = Math.round((0.45+Number(input.enhancing_lesions||3)*0.08)*100)/100; return { version:'3.170.0', module:'pcc_neuro_ext71', function:"CLIPPERSOrNeuroBehcetExt", input, score, ts: TS }; }

function LymphomaCNSRelapseExt(input) { const score = Math.round((0.5+Number(input.lesion_volume||5)*0.05)*100)/100; return { version:'3.170.0', module:'pcc_neuro_ext71', function:"LymphomaCNSRelapseExt", input, score, ts: TS }; }

function GADAntibodyExt(input) { const score = Math.round((0.4+Number(input.gad_titer||0)*0.02)*100)/100; return { version:'3.170.0', module:'pcc_neuro_ext71', function:"GADAntibodyExt", input, score, ts: TS }; }

module.exports = {
  AutoimmuneEncephalitisExt,
  ParaneoplasticSyndromeExt,
  CerebralVasculitisExt,
  CNSLupusExt,
  NeuroBehcetExt,
  SarcoidNeuroExt,
  NeuroIgG4Ext,
  CLIPPERSOrNeuroBehcetExt,
  LymphomaCNSRelapseExt,
  GADAntibodyExt,
};