// filepath: pcc/pcc_pediatric_neuro_ext81/pcc_pediatric_neuro_ext81_engine.js
// pcc_pediatric_neuro_ext81 engine (deterministic)
module.exports.version='v3.191.0';
module.exports.module='pcc_pediatric_neuro_ext81';
module.exports.functions={};
module.exports.functions['PediatricStrokeExt']=function(input){const score=Math.round((0.2 + Number(input.age||5)*0.04 + Number(input.presentation||1)*0.2 + Number(input.imaging||1)*0.2)*100)/100;return{version:'v3.191.0',module:'pcc_pediatric_neuro_ext81',function:'PediatricStrokeExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricArteriopathyExt']=function(input){const score=Math.round((0.18 + Number(input.type||2)*0.1 + Number(input.recurrent||1)*0.15 + Number(input.collaterals||3)*0.08)*100)/100;return{version:'v3.191.0',module:'pcc_pediatric_neuro_ext81',function:'PediatricArteriopathyExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStrokeAnticoagExt']=function(input){const score=Math.round((0.18 + Number(input.heparin||1)*0.2 + Number(input.warfarin||1)*0.2 + Number(input.lab||2)*0.05)*100)/100;return{version:'v3.191.0',module:'pcc_pediatric_neuro_ext81',function:'PediatricStrokeAnticoagExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSickleCellStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.transfusion||1)*0.2 + Number(input.hydroxyurea||1)*0.2 + Number(input.tcd||1)*0.1)*100)/100;return{version:'v3.191.0',module:'pcc_pediatric_neuro_ext81',function:'PediatricSickleCellStrokeExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStrokeRehabExt']=function(input){const score=Math.round((0.15 + Number(input.intensity||3)*0.1 + Number(input.weeks||12)*0.04 + Number(input.gain||10)*0.04)*100)/100;return{version:'v3.191.0',module:'pcc_pediatric_neuro_ext81',function:'PediatricStrokeRehabExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStrokeRecoveryExt']=function(input){const score=Math.round((0.2 + Number(input.mrs||2)*0.1 + Number(input.followMonths||12)*0.02 + Number(input.therapy||3)*0.05)*100)/100;return{version:'v3.191.0',module:'pcc_pediatric_neuro_ext81',function:'PediatricStrokeRecoveryExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStrokeGeneticExt']=function(input){const score=Math.round((0.15 + Number(input.mutations||2)*0.1 + Number(input.syndromic||1)*0.15 + Number(input.familyHist||1)*0.1)*100)/100;return{version:'v3.191.0',module:'pcc_pediatric_neuro_ext81',function:'PediatricStrokeGeneticExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricNICHExt']=function(input){const score=Math.round((0.18 + Number(input.delivery||1)*0.2 + Number(input.asphyxia||1)*0.1 + Number(input.hypothermia||1)*0.2)*100)/100;return{version:'v3.191.0',module:'pcc_pediatric_neuro_ext81',function:'PediatricNICHExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCVSTExt']=function(input){const score=Math.round((0.15 + Number(input.clot||1)*0.2 + Number(input.collaterals||3)*0.08 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.191.0',module:'pcc_pediatric_neuro_ext81',function:'PediatricCVSTExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricNeuroprotectionExt']=function(input){const score=Math.round((0.18 + Number(input.hypothermia||1)*0.2 + Number(input.duration||72)*0.005 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.191.0',module:'pcc_pediatric_neuro_ext81',function:'PediatricNeuroprotectionExt',input,score,ts:new Date().toISOString()};};

// TS: v3.191.0
