-- coe_103 reverse
BEGIN;
DROP TABLE IF EXISTS coe_103_results CASCADE;
DROP TABLE IF EXISTS coe_103_orders  CASCADE;
DROP TABLE IF EXISTS coe_103_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_COE_103_up';
COMMIT;
