-- icu_103 reverse
BEGIN;
DROP TABLE IF EXISTS icu_103_results CASCADE;
DROP TABLE IF EXISTS icu_103_orders  CASCADE;
DROP TABLE IF EXISTS icu_103_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ICU_103_up';
COMMIT;
