// filepath: pcc/pcc_pediatric_neuro_ext110/pcc_pediatric_neuro_ext110_engine.js
module.exports.version='v3.220.0';
module.exports.module='pcc_pediatric_neuro_ext110';
module.exports.functions={};
module.exports.functions['PediatricGBMext']=function(input){const score=Math.round((0.15 + Number(input.age||8)*0.04 + Number(input.gbm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_neuro_ext110',function:'PediatricGBMext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAAext']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.grade||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_neuro_ext110',function:'PediatricAAext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOligoExt']=function(input){const score=Math.round((0.15 + Number(input.age||10)*0.04 + Number(input["1p19q"]||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_neuro_ext110',function:'PediatricOligoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGliomatosisExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.diffuse||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_neuro_ext110',function:'PediatricGliomatosisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDIPGext']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.h3k27m||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_neuro_ext110',function:'PediatricDIPGext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPilocyticExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.braf||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_neuro_ext110',function:'PediatricPilocyticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSEGAext']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.tsc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_neuro_ext110',function:'PediatricSEGAext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPXAext']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.braf||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_neuro_ext110',function:'PediatricPXAext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPMAext']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.grade||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_neuro_ext110',function:'PediatricPMAext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGliosarcomaExt']=function(input){const score=Math.round((0.15 + Number(input.age||8)*0.04 + Number(input.gbm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_neuro_ext110',function:'PediatricGliosarcomaExt',input,score,ts:new Date().toISOString()}};

// TS: v3.220.0
