// filepath: pcc/pcc_neuro_ext184/pcc_neuro_ext184_engine.js
module.exports.version='v3.13.13.0';
module.exports.module='pcc_neuro_ext184';
module.exports.functions={};
module.exports.functions['NeuroEndocrineAdvancedExt']=function(input){const score=Math.round((0.18 + Number(input.netAdv||1)*0.2 + Number(input.serotonin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_neuro_ext184',function:'NeuroEndocrineAdvancedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PituitaryApoplexyExt']=function(input){const score=Math.round((0.18 + Number(input.apoplexy||1)*0.2 + Number(input.headache||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_neuro_ext184',function:'PituitaryApoplexyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EmptySellaExt']=function(input){const score=Math.round((0.18 + Number(input.emptySella||1)*0.2 + Number(input.herniation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_neuro_ext184',function:'EmptySellaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LymphocyticHypophysitisExt']=function(input){const score=Math.round((0.18 + Number(input.lymphHypo||1)*0.2 + Number(input.autoimmune||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_neuro_ext184',function:'LymphocyticHypophysitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['DiabetesInsipidusPregExt']=function(input){const score=Math.round((0.18 + Number(input.diPreg||1)*0.2 + Number(input.pregnancyDI||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_neuro_ext184',function:'DiabetesInsipidusPregExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HypopituitarismExt']=function(input){const score=Math.round((0.18 + Number(input.hypopit||1)*0.2 + Number(input.deficiency||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_neuro_ext184',function:'HypopituitarismExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PituitaryPostopExt']=function(input){const score=Math.round((0.18 + Number(input.pitPostop||1)*0.2 + Number(input.transsphen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_neuro_ext184',function:'PituitaryPostopExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SIADHCancerExt']=function(input){const score=Math.round((0.18 + Number(input.siadhCancer||1)*0.2 + Number(input.smallCell||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_neuro_ext184',function:'SIADHCancerExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AdrenalInsufficiencyCritExt']=function(input){const score=Math.round((0.18 + Number(input.adrenalCrit||1)*0.2 + Number(input.shock||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_neuro_ext184',function:'AdrenalInsufficiencyCritExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PituitaryApoplexyCritExt']=function(input){const score=Math.round((0.18 + Number(input.pitApoplexyCrit||1)*0.2 + Number(input.visual||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_neuro_ext184',function:'PituitaryApoplexyCritExt',input,score,ts:new Date().toISOString()}};

// TS: v3.13.13.0
