// filepath: pcc/pcc_pediatric_surg_ext127/pcc_pediatric_surg_ext127_engine.js
module.exports.version='v3.237.0';
module.exports.module='pcc_pediatric_surg_ext127';
module.exports.functions={};
module.exports.functions['PediatricSCDHUext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.hydroxyurea||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.237.0',module:'pcc_pediatric_surg_ext127',function:'PediatricSCDHUext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCDPainMgmtExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.morphine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.237.0',module:'pcc_pediatric_surg_ext127',function:'PediatricSCDPainMgmtExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCDExchangeExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.exchange||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.237.0',module:'pcc_pediatric_surg_ext127',function:'PediatricSCDExchangeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCDAcuteChestSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.antibiotic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.237.0',module:'pcc_pediatric_surg_ext127',function:'PediatricSCDAcuteChestSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCDPriapismAspExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.aspiration||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.237.0',module:'pcc_pediatric_surg_ext127',function:'PediatricSCDPriapismAspExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCDRenalSupportExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.acei||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.237.0',module:'pcc_pediatric_surg_ext127',function:'PediatricSCDRenalSupportExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCDRetinaLaserExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.laser||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.237.0',module:'pcc_pediatric_surg_ext127',function:'PediatricSCDRetinaLaserExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCDAvNSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.hipReplacement||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.237.0',module:'pcc_pediatric_surg_ext127',function:'PediatricSCDAvNSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCDUlcerCareExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.woundCare||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.237.0',module:'pcc_pediatric_surg_ext127',function:'PediatricSCDUlcerCareExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCDTransplantExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.transplant||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.237.0',module:'pcc_pediatric_surg_ext127',function:'PediatricSCDTransplantExt',input,score,ts:new Date().toISOString()}};

// TS: v3.237.0
