// Auto_generated by gen_p3if.py -- PCC v3.186.0
"use strict";
const TS = '2026-07-28T15:10:00Z';

function PediatricWadaTestExt(input) { const score = Math.round((0.4+Number(input.right_score||50)*0.01)*100)/100; return { version:'3.186.0', module:'pcc_pediatric_surg_ext76', function:"PediatricWadaTestExt", input, score, ts: TS }; }

function PediatricMEGSourceImagingExt(input) { const score = Math.round((0.4+Number(input.sources||50)*0.01)*100)/100; return { version:'3.186.0', module:'pcc_pediatric_surg_ext76', function:"PediatricMEGSourceImagingExt", input, score, ts: TS }; }

function PediatricFunctionalMRSurgeryExt(input) { const score = Math.round((0.4+Number(input.tumor_score||50)*0.01)*100)/100; return { version:'3.186.0', module:'pcc_pediatric_surg_ext76', function:"PediatricFunctionalMRSurgeryExt", input, score, ts: TS }; }

function PediatricLanguageMappingSurgExt(input) { const score = Math.round((0.4+Number(input.broca||1)*0.15)*100)/100; return { version:'3.186.0', module:'pcc_pediatric_surg_ext76', function:"PediatricLanguageMappingSurgExt", input, score, ts: TS }; }

function PediatricMemoryMappingExt(input) { const score = Math.round((0.4+Number(input.hippocampal||1)*0.15)*100)/100; return { version:'3.186.0', module:'pcc_pediatric_surg_ext76', function:"PediatricMemoryMappingExt", input, score, ts: TS }; }

function PediatricAwakeCraniotomyExt(input) { const score = Math.round((0.5+Number(input.age||16)*0.01)*100)/100; return { version:'3.186.0', module:'pcc_pediatric_surg_ext76', function:"PediatricAwakeCraniotomyExt", input, score, ts: TS }; }

function PediatricEpilepsySurgeryEvalExt(input) { const score = Math.round((0.4+Number(input.focal_score||1)*0.15)*100)/100; return { version:'3.186.0', module:'pcc_pediatric_surg_ext76', function:"PediatricEpilepsySurgeryEvalExt", input, score, ts: TS }; }

function PediatricSurgicalResectionCognExt(input) { const score = Math.round((0.4+Number(input.preserve_score||1)*0.15)*100)/100; return { version:'3.186.0', module:'pcc_pediatric_surg_ext76', function:"PediatricSurgicalResectionCognExt", input, score, ts: TS }; }

function PediatricCogRehabPostExt(input) { const score = Math.round((0.3+Number(input.weeks||8)*0.05)*100)/100; return { version:'3.186.0', module:'pcc_pediatric_surg_ext76', function:"PediatricCogRehabPostExt", input, score, ts: TS }; }

function PediatricCognitiveScreeningExt(input) { const score = Math.round((0.3+Number(input.tests||5)*0.06)*100)/100; return { version:'3.186.0', module:'pcc_pediatric_surg_ext76', function:"PediatricCognitiveScreeningExt", input, score, ts: TS }; }

module.exports = {
  PediatricWadaTestExt,
  PediatricMEGSourceImagingExt,
  PediatricFunctionalMRSurgeryExt,
  PediatricLanguageMappingSurgExt,
  PediatricMemoryMappingExt,
  PediatricAwakeCraniotomyExt,
  PediatricEpilepsySurgeryEvalExt,
  PediatricSurgicalResectionCognExt,
  PediatricCogRehabPostExt,
  PediatricCognitiveScreeningExt,
};