// filepath: pcc/pcc_pediatric_surg_ext107/pcc_pediatric_surg_ext107_engine.js
module.exports.version='v3.217.0';
module.exports.module='pcc_pediatric_surg_ext107';
module.exports.functions={};
module.exports.functions['PediatricBellSteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_surg_ext107',function:'PediatricBellSteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRHAciclovirExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.aciclovir||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_surg_ext107',function:'PediatricRHAciclovirExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTNCarbamazepineExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.carbamazepine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_surg_ext107',function:'PediatricTNCarbamazepineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGPNBaclofenExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.baclofen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_surg_ext107',function:'PediatricGPNBaclofenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVagusSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_surg_ext107',function:'PediatricVagusSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRLNSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.thyroidectomy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_surg_ext107',function:'PediatricRLNSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSLNSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_surg_ext107',function:'PediatricSLNSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPhrenicSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.plication||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_surg_ext107',function:'PediatricPhrenicSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLTSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_surg_ext107',function:'PediatricLTSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSANSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_surg_ext107',function:'PediatricSANSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.217.0
