// filepath: pcc/pcc_neuro_ext188/pcc_neuro_ext188_engine.js
module.exports.version='v3.17.17.0';
module.exports.module='pcc_neuro_ext188';
module.exports.functions={};
module.exports.functions['MovementDisorderDrugExt']=function(input){const score=Math.round((0.18 + Number(input.mdDrug||1)*0.2 + Number(input.dopa||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_neuro_ext188',function:'MovementDisorderDrugExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['DBSprogrammingExt']=function(input){const score=Math.round((0.18 + Number(input.dbsProg||1)*0.2 + Number(input.programming||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_neuro_ext188',function:'DBSprogrammingExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LevodopaChallengeExt']=function(input){const score=Math.round((0.18 + Number(input.levodopaChallenge||1)*0.2 + Number(input.response||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_neuro_ext188',function:'LevodopaChallengeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ApomorphineExt']=function(input){const score=Math.round((0.18 + Number(input.apo||1)*0.2 + Number(input.infusion||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_neuro_ext188',function:'ApomorphineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LCIGext']=function(input){const score=Math.round((0.18 + Number(input.lcig||1)*0.2 + Number(input.dopaInfusion||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_neuro_ext188',function:'LCIGext',input,score,ts:new Date().toISOString()}};
module.exports.functions['BotulinumMovementExt']=function(input){const score=Math.round((0.18 + Number(input.botoxMove||1)*0.2 + Number(input.dystoniaBotox||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_neuro_ext188',function:'BotulinumMovementExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ParkFreezingExt']=function(input){const score=Math.round((0.18 + Number(input.freezing||1)*0.2 + Number(input.gaitFreezing||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_neuro_ext188',function:'ParkFreezingExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ParkFallsExt']=function(input){const score=Math.round((0.18 + Number(input.parkFalls||1)*0.2 + Number(input.balance||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_neuro_ext188',function:'ParkFallsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ParkDementiaExt']=function(input){const score=Math.round((0.18 + Number(input.parkDem||1)*0.2 + Number(input.cognitive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_neuro_ext188',function:'ParkDementiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ParkPsychosisExt']=function(input){const score=Math.round((0.18 + Number(input.parkPsy||1)*0.2 + Number(input.hallucinations||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.17.17.0',module:'pcc_neuro_ext188',function:'ParkPsychosisExt',input,score,ts:new Date().toISOString()}};

// TS: v3.17.17.0
