// filepath: pcc/pcc_pediatric_neuro_ext92/pcc_pediatric_neuro_ext92_engine.js
// pcc_pediatric_neuro_ext92 engine (deterministic)
module.exports.version='v3.202.0';
module.exports.module='pcc_pediatric_neuro_ext92';
module.exports.functions={};
module.exports.functions['PediatricTetheredCordExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.lesion||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.202.0',module:'pcc_pediatric_neuro_ext92',function:'PediatricTetheredCordExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricChiariExt']=function(input){const score=Math.round((0.18 + Number(input.tonsils||3)*0.05 + Number(input.syrinx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.202.0',module:'pcc_pediatric_neuro_ext92',function:'PediatricChiariExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSpinalTumorExt']=function(input){const score=Math.round((0.15 + Number(input.histology||1)*0.2 + Number(input.location||2)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.202.0',module:'pcc_pediatric_neuro_ext92',function:'PediatricSpinalTumorExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSpinalCordInjuryExt']=function(input){const score=Math.round((0.15 + Number(input.ais||2)*0.15 + Number(input.recovery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.202.0',module:'pcc_pediatric_neuro_ext92',function:'PediatricSpinalCordInjuryExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSpinalMuscAtrophyExt']=function(input){const score=Math.round((0.15 + Number(input.smaType||1)*0.2 + Number(input.therapy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.202.0',module:'pcc_pediatric_neuro_ext92',function:'PediatricSpinalMuscAtrophyExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSpinalDystrophyExt']=function(input){const score=Math.round((0.15 + Number(input.kyphosis||30)*0.01 + Number(input.scoliosis||25)*0.01 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.202.0',module:'pcc_pediatric_neuro_ext92',function:'PediatricSpinalDystrophyExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSkeletalDysplasiaSpineExt']=function(input){const score=Math.round((0.15 + Number(input.dysplasia||1)*0.2 + Number(input.kyphosis||45)*0.005 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.202.0',module:'pcc_pediatric_neuro_ext92',function:'PediatricSkeletalDysplasiaSpineExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSpinalCordTumorSurgMgmExt']=function(input){const score=Math.round((0.15 + Number(input.extent||1)*0.2 + Number(input.biopsy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.202.0',module:'pcc_pediatric_neuro_ext92',function:'PediatricSpinalCordTumorSurgMgmExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricNeurogenicBowelBladExt']=function(input){const score=Math.round((0.15 + Number(input.lesionLevel||1)*0.2 + Number(input.training||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.202.0',module:'pcc_pediatric_neuro_ext92',function:'PediatricNeurogenicBowelBladExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricToneMgmForSpineExt']=function(input){const score=Math.round((0.15 + Number(input.baclofen||1)*0.2 + Number(input.rhizotomy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.202.0',module:'pcc_pediatric_neuro_ext92',function:'PediatricToneMgmForSpineExt',input,score,ts:new Date().toISOString()};};

// TS: v3.202.0
