// filepath: pcc/pcc_pediatric_surg_ext93/pcc_pediatric_surg_ext93_engine.js
// pcc_pediatric_surg_ext93 engine (deterministic)
module.exports.version='v3.203.0';
module.exports.module='pcc_pediatric_surg_ext93';
module.exports.functions={};
module.exports.functions['PediatricCarotidReimplantExt']=function(input){const score=Math.round((0.15 + Number(input.age||10)*0.04 + Number(input.stenosis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_surg_ext93',function:'PediatricCarotidReimplantExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricECICExt']=function(input){const score=Math.round((0.15 + Number(input.age||6)*0.04 + Number(input.bypass||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_surg_ext93',function:'PediatricECICExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricMoyaMoyaBypassExt']=function(input){const score=Math.round((0.15 + Number(input.age||7)*0.04 + Number(input.stages||2)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_surg_ext93',function:'PediatricMoyaMoyaBypassExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricPosteriorFossaRevascExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.vessel||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_surg_ext93',function:'PediatricPosteriorFossaRevascExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricArteriopathyAnticoagSurgExt']=function(input){const score=Math.round((0.15 + Number(input.age||7)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_surg_ext93',function:'PediatricArteriopathyAnticoagSurgExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCVSTThrombolysisExt']=function(input){const score=Math.round((0.15 + Number(input.age||6)*0.04 + Number(input.thrombolysis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_surg_ext93',function:'PediatricCVSTThrombolysisExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricDecompressiveStrokeSurgExt']=function(input){const score=Math.round((0.15 + Number(input.age||7)*0.04 + Number(input.diam||10)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_surg_ext93',function:'PediatricDecompressiveStrokeSurgExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStentingICAExt']=function(input){const score=Math.round((0.15 + Number(input.age||12)*0.02 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_surg_ext93',function:'PediatricStentingICAExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCollateralAugmentationExt']=function(input){const score=Math.round((0.15 + Number(input.age||6)*0.04 + Number(input.collat||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_surg_ext93',function:'PediatricCollateralAugmentationExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricRevascPostOpCareExt']=function(input){const score=Math.round((0.15 + Number(input.age||6)*0.04 + Number(input.icu||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_surg_ext93',function:'PediatricRevascPostOpCareExt',input,score,ts:new Date().toISOString()};};

// TS: v3.203.0
