// Auto-generated by gen_p3master.py -- PCC 3.296.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.296.0';

function X312AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x312) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_312', function: 'X312AssessmentExt', input, score, ts: TS };
}

function X312ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x312) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_312', function: 'X312ScoreExt', input, score, ts: TS };
}

function X312StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x312) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_312', function: 'X312StageExt', input, score, ts: TS };
}

function X312PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x312) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_312', function: 'X312PlanExt', input, score, ts: TS };
}

function X312RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x312) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_312', function: 'X312RiskExt', input, score, ts: TS };
}

function X312DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x312) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_312', function: 'X312DoseExt', input, score, ts: TS };
}

function X312FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x312) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_312', function: 'X312FrequencyExt', input, score, ts: TS };
}

function X312DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x312) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_312', function: 'X312DurationExt', input, score, ts: TS };
}

function X312FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x312) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_312', function: 'X312FollowupExt', input, score, ts: TS };
}

function X312OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x312) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_312', function: 'X312OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X312AssessmentExt,
  X312ScoreExt,
  X312StageExt,
  X312PlanExt,
  X312RiskExt,
  X312DoseExt,
  X312FrequencyExt,
  X312DurationExt,
  X312FollowupExt,
  X312OutcomeExt,
};