// filepath: pcc/pcc_pediatric_neuro_ext113/pcc_pediatric_neuro_ext113_engine.js
module.exports.version='v3.223.0';
module.exports.module='pcc_pediatric_neuro_ext113';
module.exports.functions={};
module.exports.functions['PediatricCNSLymphomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.lymphoma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_neuro_ext113',function:'PediatricCNSLymphomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSecondaryCNSLymphomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.systemic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_neuro_ext113',function:'PediatricSecondaryCNSLymphomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDLBCLExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.dlbcl||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_neuro_ext113',function:'PediatricDLBCLExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBurkittExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.burkitt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_neuro_ext113',function:'PediatricBurkittExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIntravascularExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.intravascular||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_neuro_ext113',function:'PediatricIntravascularExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLymphomatoidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ebv||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_neuro_ext113',function:'PediatricLymphomatoidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeurolymphomatosisExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.nerve||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_neuro_ext113',function:'PediatricNeurolymphomatosisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLeptomeningealCarcExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cancer||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_neuro_ext113',function:'PediatricLeptomeningealCarcExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainMetastasesExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.metastases||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_neuro_ext113',function:'PediatricBrainMetastasesExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricParaneoplasticExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.antiHu||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_neuro_ext113',function:'PediatricParaneoplasticExt',input,score,ts:new Date().toISOString()}};

// TS: v3.223.0
