// filepath: pcc/pcc_pediatric_surg_ext119/pcc_pediatric_surg_ext119_engine.js
module.exports.version='v3.229.0';
module.exports.module='pcc_pediatric_surg_ext119';
module.exports.functions={};
module.exports.functions['PediatricNeuroSarcoidImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.229.0',module:'pcc_pediatric_surg_ext119',function:'PediatricNeuroSarcoidImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBehcetImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.colchicine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.229.0',module:'pcc_pediatric_surg_ext119',function:'PediatricBehcetImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSLEimmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.229.0',module:'pcc_pediatric_surg_ext119',function:'PediatricSLEimmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBehcetExtendedImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.immuno||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.229.0',module:'pcc_pediatric_surg_ext119',function:'PediatricBehcetExtendedImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVasculitisImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.229.0',module:'pcc_pediatric_surg_ext119',function:'PediatricVasculitisImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeuroLupusImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.229.0',module:'pcc_pediatric_surg_ext119',function:'PediatricNeuroLupusImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSjogrenImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.229.0',module:'pcc_pediatric_surg_ext119',function:'PediatricSjogrenImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCeliacDietExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.glutenFree||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.229.0',module:'pcc_pediatric_surg_ext119',function:'PediatricCeliacDietExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWhippleAbxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ceftriaxone||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.229.0',module:'pcc_pediatric_surg_ext119',function:'PediatricWhippleAbxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIgG4SteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.229.0',module:'pcc_pediatric_surg_ext119',function:'PediatricIgG4SteroidExt',input,score,ts:new Date().toISOString()}};

// TS: v3.229.0
