// Auto-generated by gen_p3master.py -- PCC 3.278.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.278.0';

function X258AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x258) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_258', function: 'X258AssessmentExt', input, score, ts: TS };
}

function X258ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x258) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_258', function: 'X258ScoreExt', input, score, ts: TS };
}

function X258StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x258) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_258', function: 'X258StageExt', input, score, ts: TS };
}

function X258PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x258) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_258', function: 'X258PlanExt', input, score, ts: TS };
}

function X258RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x258) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_258', function: 'X258RiskExt', input, score, ts: TS };
}

function X258DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x258) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_258', function: 'X258DoseExt', input, score, ts: TS };
}

function X258FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x258) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_258', function: 'X258FrequencyExt', input, score, ts: TS };
}

function X258DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x258) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_258', function: 'X258DurationExt', input, score, ts: TS };
}

function X258FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x258) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_258', function: 'X258FollowupExt', input, score, ts: TS };
}

function X258OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x258) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_258', function: 'X258OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X258AssessmentExt,
  X258ScoreExt,
  X258StageExt,
  X258PlanExt,
  X258RiskExt,
  X258DoseExt,
  X258FrequencyExt,
  X258DurationExt,
  X258FollowupExt,
  X258OutcomeExt,
};