-- card_106 reverse
BEGIN;
DROP TABLE IF EXISTS card_106_results CASCADE;
DROP TABLE IF EXISTS card_106_orders  CASCADE;
DROP TABLE IF EXISTS card_106_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_CARD_106_up';
COMMIT;
