// Auto_generated by gen_p3hi.py -- PCC v3.177.0
"use strict";
const TS = '2026-07-28T13:40:00Z';

function PediatricToneMgmtExt(input) { const score = Math.round((0.4+Number(input.spasticity_score||3)*0.08)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_surg_ext67', function:"PediatricToneMgmtExt", input, score, ts: TS }; }

function PediatricIntrathecalPumpExt(input) { const score = Math.round((0.4+Number(input.dose_mg||5)*0.05)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_surg_ext67', function:"PediatricIntrathecalPumpExt", input, score, ts: TS }; }

function PediatricSDRExt(input) { const score = Math.round((0.45+Number(input.rootlets||5)*0.05)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_surg_ext67', function:"PediatricSDRExt", input, score, ts: TS }; }

function PediatricBotulinumSurgExt(input) { const score = Math.round((0.3+Number(input.muscles||4)*0.06)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_surg_ext67', function:"PediatricBotulinumSurgExt", input, score, ts: TS }; }

function PediatricConstraintTherapyExt(input) { const score = Math.round((0.3+Number(input.weeks||8)*0.05)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_surg_ext67', function:"PediatricConstraintTherapyExt", input, score, ts: TS }; }

function PediatricGaitTrainingExt(input) { const score = Math.round((0.3+Number(input.sessions||20)*0.025)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_surg_ext67', function:"PediatricGaitTrainingExt", input, score, ts: TS }; }

function PediatricPROExt(input) { const score = Math.round((0.3+Number(input.devices||1)*0.15)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_surg_ext67', function:"PediatricPROExt", input, score, ts: TS }; }

function PediatricOrthoticCastingExt(input) { const score = Math.round((0.3+Number(input.casts||3)*0.08)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_surg_ext67', function:"PediatricOrthoticCastingExt", input, score, ts: TS }; }

function PediatricOrthoScoliosisMgmtExt(input) { const score = Math.round((0.4+Number(input.cobb||30)*0.01)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_surg_ext67', function:"PediatricOrthoScoliosisMgmtExt", input, score, ts: TS }; }

function PediatricOrthosisGaitExt(input) { const score = Math.round((0.3+Number(input.devices||2)*0.1)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_surg_ext67', function:"PediatricOrthosisGaitExt", input, score, ts: TS }; }

module.exports = {
  PediatricToneMgmtExt,
  PediatricIntrathecalPumpExt,
  PediatricSDRExt,
  PediatricBotulinumSurgExt,
  PediatricConstraintTherapyExt,
  PediatricGaitTrainingExt,
  PediatricPROExt,
  PediatricOrthoticCastingExt,
  PediatricOrthoScoliosisMgmtExt,
  PediatricOrthosisGaitExt,
};