// filepath: pcc/pcc_pediatric_surg_ext140/pcc_pediatric_surg_ext140_engine.js
module.exports.version='v3.250.0';
module.exports.module='pcc_pediatric_surg_ext140';
module.exports.functions={};
module.exports.functions['PediatricMGCriSupportExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.support||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.250.0',module:'pcc_pediatric_surg_ext140',function:'PediatricMGCriSupportExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGBSTherapyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.250.0',module:'pcc_pediatric_surg_ext140',function:'PediatricGBSTherapyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBotulismSupportExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.supportBot||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.250.0',module:'pcc_pediatric_surg_ext140',function:'PediatricBotulismSupportExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricJDMsteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.250.0',module:'pcc_pediatric_surg_ext140',function:'PediatricJDMsteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDMDsteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.prednisone||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.250.0',module:'pcc_pediatric_surg_ext140',function:'PediatricDMDsteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBMDSteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.bmdSteroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.250.0',module:'pcc_pediatric_surg_ext140',function:'PediatricBMDSteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSMA1geneTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.zolgensma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.250.0',module:'pcc_pediatric_surg_ext140',function:'PediatricSMA1geneTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSMA2nusinersenExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.nusinersen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.250.0',module:'pcc_pediatric_surg_ext140',function:'PediatricSMA2nusinersenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCMTPTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.250.0',module:'pcc_pediatric_surg_ext140',function:'PediatricCMTPTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMGPsupportExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pyridostigmine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.250.0',module:'pcc_pediatric_surg_ext140',function:'PediatricMGPsupportExt',input,score,ts:new Date().toISOString()}};

// TS: v3.250.0
