// Auto-generated by gen_p3master.py -- PCC 3.192.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.192.0';

function SMAAssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.smaa) || 0) * 0.2) * 100) / 100;
  return { version: VER, module: 'pcc_sleep_medicine_advanced', function: 'SMAAssessmentExt', input, score, ts: TS };
}

function SMAScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.smas) || 0) * 0.31) * 100) / 100;
  return { version: VER, module: 'pcc_sleep_medicine_advanced', function: 'SMAScoreExt', input, score, ts: TS };
}

function SMAStageExt(input) {
  const score = Math.round((0.3 + (Number(input.smas) || 0) * 0.32) * 100) / 100;
  return { version: VER, module: 'pcc_sleep_medicine_advanced', function: 'SMAStageExt', input, score, ts: TS };
}

function SMAPlanExt(input) {
  const score = Math.round((0.3 + (Number(input.smap) || 0) * 0.28) * 100) / 100;
  return { version: VER, module: 'pcc_sleep_medicine_advanced', function: 'SMAPlanExt', input, score, ts: TS };
}

function SMARiskExt(input) {
  const score = Math.round((0.3 + (Number(input.smar) || 0) * 0.29) * 100) / 100;
  return { version: VER, module: 'pcc_sleep_medicine_advanced', function: 'SMARiskExt', input, score, ts: TS };
}

function SMADoseExt(input) {
  const score = Math.round((0.3 + (Number(input.smad) || 0) * 0.3) * 100) / 100;
  return { version: VER, module: 'pcc_sleep_medicine_advanced', function: 'SMADoseExt', input, score, ts: TS };
}

function SMAFrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.smaf) || 0) * 0.21) * 100) / 100;
  return { version: VER, module: 'pcc_sleep_medicine_advanced', function: 'SMAFrequencyExt', input, score, ts: TS };
}

function SMADurationExt(input) {
  const score = Math.round((0.3 + (Number(input.smad) || 0) * 0.17) * 100) / 100;
  return { version: VER, module: 'pcc_sleep_medicine_advanced', function: 'SMADurationExt', input, score, ts: TS };
}

function SMAFollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.smaf) || 0) * 0.18) * 100) / 100;
  return { version: VER, module: 'pcc_sleep_medicine_advanced', function: 'SMAFollowupExt', input, score, ts: TS };
}

function SMAOutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.smao) || 0) * 0.49) * 100) / 100;
  return { version: VER, module: 'pcc_sleep_medicine_advanced', function: 'SMAOutcomeExt', input, score, ts: TS };
}

module.exports = {
  SMAAssessmentExt,
  SMAScoreExt,
  SMAStageExt,
  SMAPlanExt,
  SMARiskExt,
  SMADoseExt,
  SMAFrequencyExt,
  SMADurationExt,
  SMAFollowupExt,
  SMAOutcomeExt,
};