// filepath: pcc/pcc_pediatric_neuro_ext156/pcc_pediatric_neuro_ext156_engine.js
module.exports.version='v3.12.8.0';
module.exports.module='pcc_pediatric_neuro_ext156';
module.exports.functions={};
module.exports.functions['PediatricPituitaryAdExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pPitAd||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_neuro_ext156',function:'PediatricPituitaryAdExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAcromegalyExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pAcro||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_neuro_ext156',function:'PediatricAcromegalyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCushingExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pCushing||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_neuro_ext156',function:'PediatricCushingExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDIExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pDI||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_neuro_ext156',function:'PediatricDIExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSIADHExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSIADH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_neuro_ext156',function:'PediatricSIADHExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHypothyroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pHypo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_neuro_ext156',function:'PediatricHypothyroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCongHypothyroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pCongHypo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_neuro_ext156',function:'PediatricCongHypothyroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHyperthyroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pHyper||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_neuro_ext156',function:'PediatricHyperthyroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAdrenalInsufficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAdren||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_neuro_ext156',function:'PediatricAdrenalInsufficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPheochromExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pPheo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_neuro_ext156',function:'PediatricPheochromExt',input,score,ts:new Date().toISOString()}};

// TS: v3.12.8.0
