-- peds_108 reverse
BEGIN;
DROP TABLE IF EXISTS peds_108_results CASCADE;
DROP TABLE IF EXISTS peds_108_orders  CASCADE;
DROP TABLE IF EXISTS peds_108_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_PEDS_108_up';
COMMIT;
