// filepath: pcc/pcc_pediatric_neuro_ext117/pcc_pediatric_neuro_ext117_engine.js
module.exports.version='v3.227.0';
module.exports.module='pcc_pediatric_neuro_ext117';
module.exports.functions={};
module.exports.functions['PediatricAISExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ischemic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.227.0',module:'pcc_pediatric_neuro_ext117',function:'PediatricAISExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSmallVesselExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.small||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.227.0',module:'pcc_pediatric_neuro_ext117',function:'PediatricSmallVesselExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLargeArteryExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.large||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.227.0',module:'pcc_pediatric_neuro_ext117',function:'PediatricLargeArteryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCardioembolicExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.heart||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.227.0',module:'pcc_pediatric_neuro_ext117',function:'PediatricCardioembolicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCryptogenicExt2']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.unknown||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.227.0',module:'pcc_pediatric_neuro_ext117',function:'PediatricCryptogenicExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricESUSext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.embolic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.227.0',module:'pcc_pediatric_neuro_ext117',function:'PediatricESUSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVertebrobasilarExt2']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.posterior||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.227.0',module:'pcc_pediatric_neuro_ext117',function:'PediatricVertebrobasilarExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWatershedExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.227.0',module:'pcc_pediatric_neuro_ext117',function:'PediatricWatershedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLacunarExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.lacune||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.227.0',module:'pcc_pediatric_neuro_ext117',function:'PediatricLacunarExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHTExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ht||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.227.0',module:'pcc_pediatric_neuro_ext117',function:'PediatricHTExt',input,score,ts:new Date().toISOString()}};

// TS: v3.227.0
