// filepath: pcc/pcc_pediatric_surg_ext150/pcc_pediatric_surg_ext150_engine.js
module.exports.version='v3.260.0';
module.exports.module='pcc_pediatric_surg_ext150';
module.exports.functions={};
module.exports.functions['PediatricAtaxiaRehabExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ataxiaRehab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_surg_ext150',function:'PediatricAtaxiaRehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChoreaRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.choreaRx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_surg_ext150',function:'PediatricChoreaRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDystoniaDBSext']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.dystoniaDBS||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_surg_ext150',function:'PediatricDystoniaDBSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTicCBText']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.ticCBT||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_surg_ext150',function:'PediatricTicCBText',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMyoclonusRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.myoRx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_surg_ext150',function:'PediatricMyoclonusRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTremorPropranololExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.tremorProp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_surg_ext150',function:'PediatricTremorPropranololExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOpsoclonusIVIGext']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.opsoIVIG||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_surg_ext150',function:'PediatricOpsoclonusIVIGext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSydenhamPenExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.sydenhamPen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_surg_ext150',function:'PediatricSydenhamPenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPANDASabxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pandasAbx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_surg_ext150',function:'PediatricPANDASabxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBenignPalsyObsExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.bpObs||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_surg_ext150',function:'PediatricBenignPalsyObsExt',input,score,ts:new Date().toISOString()}};

// TS: v3.260.0
