// filepath: pcc/pcc_pediatric_surg_ext88/pcc_pediatric_surg_ext88_engine.js
// pcc_pediatric_surg_ext88 engine (deterministic)
module.exports.version='v3.198.0';
module.exports.module='pcc_pediatric_surg_ext88';
module.exports.functions={};
module.exports.functions['PediatricSDRExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.spasticity||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.198.0',module:'pcc_pediatric_surg_ext88',function:'PediatricSDRExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricITBPumpImplExt']=function(input){const score=Math.round((0.15 + Number(input.pump||1)*0.2 + Number(input.catheter||1)*0.15 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.198.0',module:'pcc_pediatric_surg_ext88',function:'PediatricITBPumpImplExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricITBPumpRefillExt']=function(input){const score=Math.round((0.15 + Number(input.refill||1)*0.2 + Number(input.screening||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.198.0',module:'pcc_pediatric_surg_ext88',function:'PediatricITBPumpRefillExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricITBPumpReplaceExt']=function(input){const score=Math.round((0.15 + Number(input.endOfLife||1)*0.2 + Number(input.battery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.198.0',module:'pcc_pediatric_surg_ext88',function:'PediatricITBPumpReplaceExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricRectusFemorisTransferExt']=function(input){const score=Math.round((0.15 + Number(input.age||7)*0.04 + Number(input.gait||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.198.0',module:'pcc_pediatric_surg_ext88',function:'PediatricRectusFemorisTransferExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricFemoralOsteoExt']=function(input){const score=Math.round((0.15 + Number(input.age||8)*0.04 + Number(input.aim||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.198.0',module:'pcc_pediatric_surg_ext88',function:'PediatricFemoralOsteoExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricTibialTendonTransferExt']=function(input){const score=Math.round((0.15 + Number(input.age||7)*0.04 + Number(input.gait||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.198.0',module:'pcc_pediatric_surg_ext88',function:'PediatricTibialTendonTransferExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSpinalFusionForCPExt']=function(input){const score=Math.round((0.15 + Number(input.scoliosis||30)*0.01 + Number(input.age||12)*0.02 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.198.0',module:'pcc_pediatric_surg_ext88',function:'PediatricSpinalFusionForCPExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricHipSurveillanceForCPExt']=function(input){const score=Math.round((0.15 + Number(input.xray||3)*0.1 + Number(input.reimers||30)*0.01 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.198.0',module:'pcc_pediatric_surg_ext88',function:'PediatricHipSurveillanceForCPExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricReconstructHipSurgExt']=function(input){const score=Math.round((0.15 + Number(input.age||8)*0.04 + Number(input.displacement||50)*0.005 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.198.0',module:'pcc_pediatric_surg_ext88',function:'PediatricReconstructHipSurgExt',input,score,ts:new Date().toISOString()};};

// TS: v3.198.0
