// filepath: pcc/pcc_pediatric_neuro_ext149/pcc_pediatric_neuro_ext149_engine.js
module.exports.version='v3.259.0';
module.exports.module='pcc_pediatric_neuro_ext149';
module.exports.functions={};
module.exports.functions['PediatricMedulloExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pMedullo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_neuro_ext149',function:'PediatricMedulloExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPilocyticExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.piloAstro||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_neuro_ext149',function:'PediatricPilocyticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEpendymomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ependymomaP||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_neuro_ext149',function:'PediatricEpendymomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainstemExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.dipg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_neuro_ext149',function:'PediatricBrainstemExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricATRText']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.atrt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_neuro_ext149',function:'PediatricATRText',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCraniopharyngiomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.craniophar||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_neuro_ext149',function:'PediatricCraniopharyngiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPituitaryExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pPit||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_neuro_ext149',function:'PediatricPituitaryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChoroidPlexusExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.chPlex||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_neuro_ext149',function:'PediatricChoroidPlexusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinalTumorExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pSpinal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_neuro_ext149',function:'PediatricSpinalTumorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeurofibromatosisTumorExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.nfTumor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_neuro_ext149',function:'PediatricNeurofibromatosisTumorExt',input,score,ts:new Date().toISOString()}};

// TS: v3.259.0
