// Auto-generated by gen_p3master.py -- PCC 3.288.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.288.0';

function X287AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x287) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_287', function: 'X287AssessmentExt', input, score, ts: TS };
}

function X287ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x287) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_287', function: 'X287ScoreExt', input, score, ts: TS };
}

function X287StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x287) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_287', function: 'X287StageExt', input, score, ts: TS };
}

function X287PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x287) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_287', function: 'X287PlanExt', input, score, ts: TS };
}

function X287RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x287) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_287', function: 'X287RiskExt', input, score, ts: TS };
}

function X287DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x287) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_287', function: 'X287DoseExt', input, score, ts: TS };
}

function X287FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x287) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_287', function: 'X287FrequencyExt', input, score, ts: TS };
}

function X287DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x287) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_287', function: 'X287DurationExt', input, score, ts: TS };
}

function X287FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x287) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_287', function: 'X287FollowupExt', input, score, ts: TS };
}

function X287OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x287) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_287', function: 'X287OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X287AssessmentExt,
  X287ScoreExt,
  X287StageExt,
  X287PlanExt,
  X287RiskExt,
  X287DoseExt,
  X287FrequencyExt,
  X287DurationExt,
  X287FollowupExt,
  X287OutcomeExt,
};