-- gi_101 reverse
BEGIN;
DROP TABLE IF EXISTS gi_101_results CASCADE;
DROP TABLE IF EXISTS gi_101_orders  CASCADE;
DROP TABLE IF EXISTS gi_101_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_GI_101_up';
COMMIT;
