// filepath: pcc/pcc_proteomics_ext102/pcc_proteomics_ext102_engine.js
module.exports.version='v3.38.38.0';
module.exports.module='pcc_proteomics_ext102';
module.exports.functions={};
module.exports.functions['ProMassSpecExt']=function(input){const score=Math.round((0.18 + Number(input.prMS||1)*0.2 + Number(input.prMsType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.38.38.0',module:'pcc_proteomics_ext102',function:'ProMassSpecExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ProELISAExt']=function(input){const score=Math.round((0.18 + Number(input.prELISA||1)*0.2 + Number(input.prElisaTarget||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.38.38.0',module:'pcc_proteomics_ext102',function:'ProELISAExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ProWBext']=function(input){const score=Math.round((0.18 + Number(input.prWB||1)*0.2 + Number(input.prWbAb||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.38.38.0',module:'pcc_proteomics_ext102',function:'ProWBext',input,score,ts:new Date().toISOString()}};
module.exports.functions['ProFlowExt']=function(input){const score=Math.round((0.18 + Number(input.prFlow||1)*0.2 + Number(input.prFlowMarker||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.38.38.0',module:'pcc_proteomics_ext102',function:'ProFlowExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ProIHCext']=function(input){const score=Math.round((0.18 + Number(input.prIHC||1)*0.2 + Number(input.prIhcMarker||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.38.38.0',module:'pcc_proteomics_ext102',function:'ProIHCext',input,score,ts:new Date().toISOString()}};
module.exports.functions['ProBiomarkerExt']=function(input){const score=Math.round((0.18 + Number(input.prBiomarker||1)*0.2 + Number(input.prBiomarkerLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.38.38.0',module:'pcc_proteomics_ext102',function:'ProBiomarkerExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ProPhosphoExt']=function(input){const score=Math.round((0.18 + Number(input.prPhos||1)*0.2 + Number(input.prPhosSite||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.38.38.0',module:'pcc_proteomics_ext102',function:'ProPhosphoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ProInteractomeExt']=function(input){const score=Math.round((0.18 + Number(input.prInt||1)*0.2 + Number(input.prIntType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.38.38.0',module:'pcc_proteomics_ext102',function:'ProInteractomeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ProStructExt']=function(input){const score=Math.round((0.18 + Number(input.prStruct||1)*0.2 + Number(input.prStructType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.38.38.0',module:'pcc_proteomics_ext102',function:'ProStructExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ProClinExt']=function(input){const score=Math.round((0.18 + Number(input.prClin||1)*0.2 + Number(input.prClinInd||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.38.38.0',module:'pcc_proteomics_ext102',function:'ProClinExt',input,score,ts:new Date().toISOString()}};

// TS: v3.38.38.0
