// filepath: pcc/pcc_pediatric_surg_ext159/pcc_pediatric_surg_ext159_engine.js
module.exports.version='v3.12.11.0';
module.exports.module='pcc_pediatric_surg_ext159';
module.exports.functions={};
module.exports.functions['PediatricNF2geneticExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.nf2GenTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_surg_ext159',function:'PediatricNF2geneticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTSCgeneticExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.tscGenTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_surg_ext159',function:'PediatricTSCgeneticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVHLgeneticExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.vhlGenTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_surg_ext159',function:'PediatricVHLgeneticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLFSScreenExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.lfsScreen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_surg_ext159',function:'PediatricLFSScreenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCowdenTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.cowdenTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_surg_ext159',function:'PediatricCowdenTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGorlinTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.gorlinTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_surg_ext159',function:'PediatricGorlinTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricATsupportExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.atSupport||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_surg_ext159',function:'PediatricATsupportExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHDjuvenileTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.hdJuvTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_surg_ext159',function:'PediatricHDjuvenileTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFRDAidebenoneExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.idebenone||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_surg_ext159',function:'PediatricFRDAidebenoneExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricKennedySupportExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.kennedySup||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_surg_ext159',function:'PediatricKennedySupportExt',input,score,ts:new Date().toISOString()}};

// TS: v3.12.11.0
