// filepath: pcc/pcc_pediatric_neuro_ext186/pcc_pediatric_neuro_ext186_engine.js
module.exports.version='v3.26.26.0';
module.exports.module='pcc_pediatric_neuro_ext186';
module.exports.functions={};
module.exports.functions['PediatricCerebellarExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pCerebellar||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_pediatric_neuro_ext186',function:'PediatricCerebellarExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAText']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pAT||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_pediatric_neuro_ext186',function:'PediatricAText',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFAext']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pFA||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_pediatric_neuro_ext186',function:'PediatricFAext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHDExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pHD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_pediatric_neuro_ext186',function:'PediatricHDExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChoreaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pChoreaSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_pediatric_neuro_ext186',function:'PediatricChoreaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSydenhamExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pSydenham||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_pediatric_neuro_ext186',function:'PediatricSydenhamExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTicExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_pediatric_neuro_ext186',function:'PediatricTicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTouretteExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTourette||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_pediatric_neuro_ext186',function:'PediatricTouretteExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDystoniaExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pDystonia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_pediatric_neuro_ext186',function:'PediatricDystoniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAtaxiaTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAtaxiaTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_pediatric_neuro_ext186',function:'PediatricAtaxiaTxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.26.26.0
