// Auto_generated by gen_p3gx.py -- PCC v3.166.0
"use strict";
const TS = '2026-07-28T11:50:00Z';

function StrokeRecoveryAssessmentExt(input) { const score = Math.round((0.3+Number(input.days_post||30)*0.005)*100)/100; return { version:'3.166.0', module:'pcc_neuro_ext67', function:"StrokeRecoveryAssessmentExt", input, score, ts: TS }; }

function AphasiaAssessmentExt(input) { const score = Math.round((0.4+Number(input.wab_score||50)*0.005)*100)/100; return { version:'3.166.0', module:'pcc_neuro_ext67', function:"AphasiaAssessmentExt", input, score, ts: TS }; }

function DysphagiaManagementExt(input) { const score = Math.round((0.35+Number(input.gugging_score||10)*0.04)*100)/100; return { version:'3.166.0', module:'pcc_neuro_ext67', function:"DysphagiaManagementExt", input, score, ts: TS }; }

function SpasticityTreatmentExt(input) { const score = Math.round((0.4+Number(input.mas_score||2)*0.1)*100)/100; return { version:'3.166.0', module:'pcc_neuro_ext67', function:"SpasticityTreatmentExt", input, score, ts: TS }; }

function NeurogenicBladderExt(input) { const score = Math.round((0.3+Number(input.residual_ml||100)*0.003)*100)/100; return { version:'3.166.0', module:'pcc_neuro_ext67', function:"NeurogenicBladderExt", input, score, ts: TS }; }

function PoststrokeDepressionExt(input) { const score = Math.round((0.4+Number(input.phq9_score||10)*0.04)*100)/100; return { version:'3.166.0', module:'pcc_neuro_ext67', function:"PoststrokeDepressionExt", input, score, ts: TS }; }

function PoststrokeSeizureExt(input) { const score = Math.round((0.4+Number(input.seizure_freq||1)*0.15)*100)/100; return { version:'3.166.0', module:'pcc_neuro_ext67', function:"PoststrokeSeizureExt", input, score, ts: TS }; }

function MotorRecoveryTrackingExt(input) { const score = Math.round((0.3+Number(input.fugl_meyer||50)*0.008)*100)/100; return { version:'3.166.0', module:'pcc_neuro_ext67', function:"MotorRecoveryTrackingExt", input, score, ts: TS }; }

function CognitiveRehabExt(input) { const score = Math.round((0.35+Number(input.mmse_score||24)*0.02)*100)/100; return { version:'3.166.0', module:'pcc_neuro_ext67', function:"CognitiveRehabExt", input, score, ts: TS }; }

function VocationalRehabExt(input) { const score = Math.round((0.3+Number(input.work_hours||4)*0.05)*100)/100; return { version:'3.166.0', module:'pcc_neuro_ext67', function:"VocationalRehabExt", input, score, ts: TS }; }

module.exports = {
  StrokeRecoveryAssessmentExt,
  AphasiaAssessmentExt,
  DysphagiaManagementExt,
  SpasticityTreatmentExt,
  NeurogenicBladderExt,
  PoststrokeDepressionExt,
  PoststrokeSeizureExt,
  MotorRecoveryTrackingExt,
  CognitiveRehabExt,
  VocationalRehabExt,
};