// filepath: pcc/pcc_nutrition_ext100/pcc_nutrition_ext100_engine.js
module.exports.version='v3.20.20.0';
module.exports.module='pcc_nutrition_ext100';
module.exports.functions={};
module.exports.functions['NutrAssessmentExt']=function(input){const score=Math.round((0.18 + Number(input.nutrAssess||1)*0.2 + Number(input.alb||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_nutrition_ext100',function:'NutrAssessmentExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrMalnutritionExt']=function(input){const score=Math.round((0.18 + Number(input.nutrMaln||1)*0.2 + Number(input.weightLoss||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_nutrition_ext100',function:'NutrMalnutritionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrObesityExt']=function(input){const score=Math.round((0.18 + Number(input.nutrOb||1)*0.2 + Number(input.bmiNutr||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_nutrition_ext100',function:'NutrObesityExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrTPNext']=function(input){const score=Math.round((0.18 + Number(input.nutrTPN||1)*0.2 + Number(input.tpnDuration||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_nutrition_ext100',function:'NutrTPNext',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrEnteralExt']=function(input){const score=Math.round((0.18 + Number(input.nutrEnt||1)*0.2 + Number(input.feedingType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_nutrition_ext100',function:'NutrEnteralExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrDiabeticExt']=function(input){const score=Math.round((0.18 + Number(input.nutrDM||1)*0.2 + Number(input.carbs||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_nutrition_ext100',function:'NutrDiabeticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrRenalExt']=function(input){const score=Math.round((0.18 + Number(input.nutrRenal||1)*0.2 + Number(input.renalDiet||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_nutrition_ext100',function:'NutrRenalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrCardiacExt']=function(input){const score=Math.round((0.18 + Number(input.nutrCard||1)*0.2 + Number(input.sodium||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_nutrition_ext100',function:'NutrCardiacExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrPediatricExt']=function(input){const score=Math.round((0.18 + Number(input.nutrPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_nutrition_ext100',function:'NutrPediatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrGeriatricExt']=function(input){const score=Math.round((0.18 + Number(input.nutrGer||1)*0.2 + Number(input.gerAge||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_nutrition_ext100',function:'NutrGeriatricExt',input,score,ts:new Date().toISOString()}};

// TS: v3.20.20.0
