// filepath: pcc/pcc_neuro_ext158/pcc_neuro_ext158_engine.js
module.exports.version='v3.257.0';
module.exports.module='pcc_neuro_ext158';
module.exports.functions={};
module.exports.functions['AcuteIschemicStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.lvo||1)*0.2 + Number(input.nihss||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.257.0',module:'pcc_neuro_ext158',function:'AcuteIschemicStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntracerebralHemorrhageExt']=function(input){const score=Math.round((0.18 + Number(input.ich||1)*0.2 + Number(input.hematoma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.257.0',module:'pcc_neuro_ext158',function:'IntracerebralHemorrhageExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SubarachnoidHemorrhageExt']=function(input){const score=Math.round((0.18 + Number(input.sah||1)*0.2 + Number(input.huntHess||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.257.0',module:'pcc_neuro_ext158',function:'SubarachnoidHemorrhageExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TIAext']=function(input){const score=Math.round((0.18 + Number(input.tia||1)*0.2 + Number(input.abcd2||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.257.0',module:'pcc_neuro_ext158',function:'TIAext',input,score,ts:new Date().toISOString()}};
module.exports.functions['StrokeSecondaryPreventionExt']=function(input){const score=Math.round((0.18 + Number(input.secondary||1)*0.2 + Number(input.strokePrev||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.257.0',module:'pcc_neuro_ext158',function:'StrokeSecondaryPreventionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CryptogenicStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.crypto||1)*0.2 + Number(input.pfo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.257.0',module:'pcc_neuro_ext158',function:'CryptogenicStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CarotidStenosisExt']=function(input){const score=Math.round((0.18 + Number(input.carotid||1)*0.2 + Number(input.stenosis||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.257.0',module:'pcc_neuro_ext158',function:'CarotidStenosisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VertebrobasilarExt']=function(input){const score=Math.round((0.18 + Number(input.vb||1)*0.2 + Number(input.posterior||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.257.0',module:'pcc_neuro_ext158',function:'VertebrobasilarExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LacunarStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.lacunar||1)*0.2 + Number(input.smallVesselStroke||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.257.0',module:'pcc_neuro_ext158',function:'LacunarStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['StrokeInYoungExt']=function(input){const score=Math.round((0.18 + Number(input.youngStroke||1)*0.2 + Number(input.pfo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.257.0',module:'pcc_neuro_ext158',function:'StrokeInYoungExt',input,score,ts:new Date().toISOString()}};

// TS: v3.257.0
