// filepath: pcc/pcc_perioperative_ext102/pcc_perioperative_ext102_engine.js
module.exports.version='v3.71.71.0';
module.exports.module='pcc_perioperative_ext102';
module.exports.functions={};
module.exports.functions['POGenExt']=function(input){const score=Math.round((0.18 + Number(input.poGen||1)*0.2 + Number(input.poGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_perioperative_ext102',function:'POGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['POPreopExt']=function(input){const score=Math.round((0.18 + Number(input.poPre||1)*0.2 + Number(input.poPreScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_perioperative_ext102',function:'POPreopExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['POIntropExt']=function(input){const score=Math.round((0.18 + Number(input.poItr||1)*0.2 + Number(input.poItrType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_perioperative_ext102',function:'POIntropExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['POTimeOutExt']=function(input){const score=Math.round((0.18 + Number(input.poTm||1)*0.2 + Number(input.poTmScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_perioperative_ext102',function:'POTimeOutExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['POHandoffExt']=function(input){const score=Math.round((0.18 + Number(input.poH||1)*0.2 + Number(input.poHScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_perioperative_ext102',function:'POHandoffExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PODischargeExt']=function(input){const score=Math.round((0.18 + Number(input.poDis||1)*0.2 + Number(input.poDisType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_perioperative_ext102',function:'PODischargeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['POComplicExt']=function(input){const score=Math.round((0.18 + Number(input.poCom||1)*0.2 + Number(input.poComType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_perioperative_ext102',function:'POComplicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['POEnhancedExt']=function(input){const score=Math.round((0.18 + Number(input.poERAS||1)*0.2 + Number(input.poERASScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_perioperative_ext102',function:'POEnhancedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['POFollowExt']=function(input){const score=Math.round((0.18 + Number(input.poFol||1)*0.2 + Number(input.poFolType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_perioperative_ext102',function:'POFollowExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['POQualityExt']=function(input){const score=Math.round((0.18 + Number(input.poQ||1)*0.2 + Number(input.poQScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_perioperative_ext102',function:'POQualityExt',input,score,ts:new Date().toISOString()}};

// TS: v3.71.71.0
