// filepath: pcc/pcc_pediatric_neuro_ext109/pcc_pediatric_neuro_ext109_engine.js
module.exports.version='v3.219.0';
module.exports.module='pcc_pediatric_neuro_ext109';
module.exports.functions={};
module.exports.functions['PediatricPinealExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.tumor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_neuro_ext109',function:'PediatricPinealExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPituitaryExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.adenoma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_neuro_ext109',function:'PediatricPituitaryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCraniopharyngiomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.tumor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_neuro_ext109',function:'PediatricCraniopharyngiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOpticGliomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.nf1||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_neuro_ext109',function:'PediatricOpticGliomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainstemGliomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.diffuse||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_neuro_ext109',function:'PediatricBrainstemGliomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCerebellarAstrocytomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cystic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_neuro_ext109',function:'PediatricCerebellarAstrocytomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMedulloblastomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.metastasis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_neuro_ext109',function:'PediatricMedulloblastomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEpendymomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.grade||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_neuro_ext109',function:'PediatricEpendymomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCPTExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.tumor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_neuro_ext109',function:'PediatricCPTExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGCText']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.marker||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_neuro_ext109',function:'PediatricGCText',input,score,ts:new Date().toISOString()}};

// TS: v3.219.0
