// Auto_generated by gen_p3gt.py - PCC v3.162.0
"use strict";
const TS = '2026-07-28T11:14:00Z';

function IntracranialAtherosclerosisDiseaseExt(input) {
  return { version:'3.162.0', module:'pcc_neuro_ext63', function:"IntracranialAtherosclerosisDiseaseExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function CerebralMicrobleedsSyndromeExt(input) {
  return { version:'3.162.0', module:'pcc_neuro_ext63', function:"CerebralMicrobleedsSyndromeExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function SuperficialSiderosisExt(input) {
  return { version:'3.162.0', module:'pcc_neuro_ext63', function:"SuperficialSiderosisExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function RadiationVasculopathyExt(input) {
  return { version:'3.162.0', module:'pcc_neuro_ext63', function:"RadiationVasculopathyExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function PosteriorCorticalAtrophyExt(input) {
  return { version:'3.162.0', module:'pcc_neuro_ext63', function:"PosteriorCorticalAtrophyExt", input, score: Math.round((0.4+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function PrimaryProgressiveAphasiaExt(input) {
  return { version:'3.162.0', module:'pcc_neuro_ext63', function:"PrimaryProgressiveAphasiaExt", input, score: Math.round((0.4+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function CorticobasalDegenerationExt(input) {
  return { version:'3.162.0', module:'pcc_neuro_ext63', function:"CorticobasalDegenerationExt", input, score: Math.round((0.45+Number(input.value||3)*0.04)*100)/100, ts: TS };
}

function ProgressiveSupranuclearPalsyExt(input) {
  return { version:'3.162.0', module:'pcc_neuro_ext63', function:"ProgressiveSupranuclearPalsyExt", input, score: Math.round((0.45+Number(input.value||3)*0.04)*100)/100, ts: TS };
}

function MultipleSystemAtrophyExt(input) {
  return { version:'3.162.0', module:'pcc_neuro_ext63', function:"MultipleSystemAtrophyExt", input, score: Math.round((0.4+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function LewyBodyDementiaExt(input) {
  return { version:'3.162.0', module:'pcc_neuro_ext63', function:"LewyBodyDementiaExt", input, score: Math.round((0.45+Number(input.value||3)*0.04)*100)/100, ts: TS };
}

function PediatricIntracranialAtherosclerosisExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_neuro_ext52', function:"PediatricIntracranialAtherosclerosisExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function PediatricCerebralMicrobleedsExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_neuro_ext52', function:"PediatricCerebralMicrobleedsExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function PediatricSuperficialSiderosisExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_neuro_ext52', function:"PediatricSuperficialSiderosisExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function PediatricRadiationVasculopathyExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_neuro_ext52', function:"PediatricRadiationVasculopathyExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function PediatricPosteriorCorticalAtrophyExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_neuro_ext52', function:"PediatricPosteriorCorticalAtrophyExt", input, score: Math.round((0.4+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function PediatricProgressiveAphasiaExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_neuro_ext52', function:"PediatricProgressiveAphasiaExt", input, score: Math.round((0.4+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function PediatricCorticobasalDegenerationExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_neuro_ext52', function:"PediatricCorticobasalDegenerationExt", input, score: Math.round((0.45+Number(input.value||3)*0.04)*100)/100, ts: TS };
}

function PediatricProgressiveSupranuclearPalsyExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_neuro_ext52', function:"PediatricProgressiveSupranuclearPalsyExt", input, score: Math.round((0.45+Number(input.value||3)*0.04)*100)/100, ts: TS };
}

function PediatricMultipleSystemAtrophyExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_neuro_ext52', function:"PediatricMultipleSystemAtrophyExt", input, score: Math.round((0.4+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function PediatricLewyBodyDementiaExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_neuro_ext52', function:"PediatricLewyBodyDementiaExt", input, score: Math.round((0.45+Number(input.value||3)*0.04)*100)/100, ts: TS };
}

function PediatricNeuroAtherosclerosisSurgeryExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_surg_ext52', function:"PediatricNeuroAtherosclerosisSurgeryExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function PediatricBypassProcedureExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_surg_ext52', function:"PediatricBypassProcedureExt", input, score: Math.round((0.3+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function PediatricECICProcedureExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_surg_ext52', function:"PediatricECICProcedureExt", input, score: Math.round((0.3+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function PediatricMicrobleedsResectionExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_surg_ext52', function:"PediatricMicrobleedsResectionExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function PediatricSiderosisCavityExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_surg_ext52', function:"PediatricSiderosisCavityExt", input, score: Math.round((0.1+(Number(input.value||5))/50)*100)/100, ts: TS };
}

function PediatricRadiationNecrosisResectionExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_surg_ext52', function:"PediatricRadiationNecrosisResectionExt", input, score: Math.round((0.3+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function PediatricPCAOccipitalStimulatorExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_surg_ext52', function:"PediatricPCAOccipitalStimulatorExt", input, score: Math.round((0.3+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function PediatricPPAVagusNerveStimExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_surg_ext52', function:"PediatricPPAVagusNerveStimExt", input, score: Math.round((0.3+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function PediatricCBDPallidotomyExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_surg_ext52', function:"PediatricCBDPallidotomyExt", input, score: Math.round((0.3+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

function PediatricPSPDeepBrainStimExt(input) {
  return { version:'3.162.0', module:'pcc_pediatric_surg_ext52', function:"PediatricPSPDeepBrainStimExt", input, score: Math.round((0.3+Number(input.value||3)*0.05)*100)/100, ts: TS };
}

module.exports = {
  IntracranialAtherosclerosisDiseaseExt,
  CerebralMicrobleedsSyndromeExt,
  SuperficialSiderosisExt,
  RadiationVasculopathyExt,
  PosteriorCorticalAtrophyExt,
  PrimaryProgressiveAphasiaExt,
  CorticobasalDegenerationExt,
  ProgressiveSupranuclearPalsyExt,
  MultipleSystemAtrophyExt,
  LewyBodyDementiaExt,
  PediatricIntracranialAtherosclerosisExt,
  PediatricCerebralMicrobleedsExt,
  PediatricSuperficialSiderosisExt,
  PediatricRadiationVasculopathyExt,
  PediatricPosteriorCorticalAtrophyExt,
  PediatricProgressiveAphasiaExt,
  PediatricCorticobasalDegenerationExt,
  PediatricProgressiveSupranuclearPalsyExt,
  PediatricMultipleSystemAtrophyExt,
  PediatricLewyBodyDementiaExt,
  PediatricNeuroAtherosclerosisSurgeryExt,
  PediatricBypassProcedureExt,
  PediatricECICProcedureExt,
  PediatricMicrobleedsResectionExt,
  PediatricSiderosisCavityExt,
  PediatricRadiationNecrosisResectionExt,
  PediatricPCAOccipitalStimulatorExt,
  PediatricPPAVagusNerveStimExt,
  PediatricCBDPallidotomyExt,
  PediatricPSPDeepBrainStimExt,
};