-- card_102 reverse
BEGIN;
DROP TABLE IF EXISTS card_102_results CASCADE;
DROP TABLE IF EXISTS card_102_orders  CASCADE;
DROP TABLE IF EXISTS card_102_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_CARD_102_up';
COMMIT;
