// Auto-generated by gen_p3master.py -- PCC 3.289.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.289.0';

function X289AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x289) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_289', function: 'X289AssessmentExt', input, score, ts: TS };
}

function X289ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x289) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_289', function: 'X289ScoreExt', input, score, ts: TS };
}

function X289StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x289) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_289', function: 'X289StageExt', input, score, ts: TS };
}

function X289PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x289) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_289', function: 'X289PlanExt', input, score, ts: TS };
}

function X289RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x289) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_289', function: 'X289RiskExt', input, score, ts: TS };
}

function X289DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x289) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_289', function: 'X289DoseExt', input, score, ts: TS };
}

function X289FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x289) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_289', function: 'X289FrequencyExt', input, score, ts: TS };
}

function X289DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x289) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_289', function: 'X289DurationExt', input, score, ts: TS };
}

function X289FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x289) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_289', function: 'X289FollowupExt', input, score, ts: TS };
}

function X289OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x289) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_289', function: 'X289OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X289AssessmentExt,
  X289ScoreExt,
  X289StageExt,
  X289PlanExt,
  X289RiskExt,
  X289DoseExt,
  X289FrequencyExt,
  X289DurationExt,
  X289FollowupExt,
  X289OutcomeExt,
};