// filepath: pcc/pcc_pediatric_surg_ext149/pcc_pediatric_surg_ext149_engine.js
module.exports.version='v3.259.0';
module.exports.module='pcc_pediatric_surg_ext149';
module.exports.functions={};
module.exports.functions['PediatricMedulloResectExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.medResect||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_surg_ext149',function:'PediatricMedulloResectExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPiloResectExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.piloResect||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_surg_ext149',function:'PediatricPiloResectExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEpendymomaResectExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.epenResect||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_surg_ext149',function:'PediatricEpendymomaResectExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDIPGBxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.dipgBx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_surg_ext149',function:'PediatricDIPGBxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricATRTSurgExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.atrtSurg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_surg_ext149',function:'PediatricATRTSurgExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCraniopharResectExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.cranioResect||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_surg_ext149',function:'PediatricCraniopharResectExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPitTransExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pitTrans||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_surg_ext149',function:'PediatricPitTransExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChoroidPlexSurgExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.chPlexSurg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_surg_ext149',function:'PediatricChoroidPlexSurgExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinalTumorSurgExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pSpinalSurg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_surg_ext149',function:'PediatricSpinalTumorSurgExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNFTumorSurgExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.nfTumorSurg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_pediatric_surg_ext149',function:'PediatricNFTumorSurgExt',input,score,ts:new Date().toISOString()}};

// TS: v3.259.0
