// Auto-generated by gen_p3master.py -- PCC 3.277.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.277.0';

function X253AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x253) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_253', function: 'X253AssessmentExt', input, score, ts: TS };
}

function X253ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x253) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_253', function: 'X253ScoreExt', input, score, ts: TS };
}

function X253StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x253) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_253', function: 'X253StageExt', input, score, ts: TS };
}

function X253PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x253) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_253', function: 'X253PlanExt', input, score, ts: TS };
}

function X253RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x253) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_253', function: 'X253RiskExt', input, score, ts: TS };
}

function X253DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x253) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_253', function: 'X253DoseExt', input, score, ts: TS };
}

function X253FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x253) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_253', function: 'X253FrequencyExt', input, score, ts: TS };
}

function X253DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x253) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_253', function: 'X253DurationExt', input, score, ts: TS };
}

function X253FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x253) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_253', function: 'X253FollowupExt', input, score, ts: TS };
}

function X253OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x253) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_253', function: 'X253OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X253AssessmentExt,
  X253ScoreExt,
  X253StageExt,
  X253PlanExt,
  X253RiskExt,
  X253DoseExt,
  X253FrequencyExt,
  X253DurationExt,
  X253FollowupExt,
  X253OutcomeExt,
};