-- icu_101 reverse
BEGIN;
DROP TABLE IF EXISTS icu_101_results CASCADE;
DROP TABLE IF EXISTS icu_101_orders  CASCADE;
DROP TABLE IF EXISTS icu_101_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ICU_101_up';
COMMIT;
