// Auto-generated by gen_p3master.py -- PCC 3.190.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.190.0';

function CMRIAssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.cmri) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_mri', function: 'CMRIAssessmentExt', input, score, ts: TS };
}

function CMRIScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.cmri) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_mri', function: 'CMRIScoreExt', input, score, ts: TS };
}

function CMRIStageExt(input) {
  const score = Math.round((0.3 + (Number(input.cmri) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_mri', function: 'CMRIStageExt', input, score, ts: TS };
}

function CMRIPlanExt(input) {
  const score = Math.round((0.3 + (Number(input.cmri) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_mri', function: 'CMRIPlanExt', input, score, ts: TS };
}

function CMRIRiskExt(input) {
  const score = Math.round((0.3 + (Number(input.cmri) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_mri', function: 'CMRIRiskExt', input, score, ts: TS };
}

function CMRIDoseExt(input) {
  const score = Math.round((0.3 + (Number(input.cmri) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_mri', function: 'CMRIDoseExt', input, score, ts: TS };
}

function CMRIFrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.cmri) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_mri', function: 'CMRIFrequencyExt', input, score, ts: TS };
}

function CMRIDurationExt(input) {
  const score = Math.round((0.3 + (Number(input.cmri) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_mri', function: 'CMRIDurationExt', input, score, ts: TS };
}

function CMRIFollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.cmri) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_mri', function: 'CMRIFollowupExt', input, score, ts: TS };
}

function CMRIOutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.cmri) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_mri', function: 'CMRIOutcomeExt', input, score, ts: TS };
}

module.exports = {
  CMRIAssessmentExt,
  CMRIScoreExt,
  CMRIStageExt,
  CMRIPlanExt,
  CMRIRiskExt,
  CMRIDoseExt,
  CMRIFrequencyExt,
  CMRIDurationExt,
  CMRIFollowupExt,
  CMRIOutcomeExt,
};