// Auto_generated by gen_p3gv.py -- PCC v3.164.0
"use strict";
const TS = '2026-07-28T11:30:00Z';

function PediatricNeurodegenerativeExt(input) { const score = Math.round((0.4+Number(input.progression||1)*0.04)*100)/100; return { version:'3.164.0', module:'pcc_pediatric_neuro_ext54', function:"PediatricNeurodegenerativeExt", input, score, ts: TS }; }

function PediatricMovementDisorderExt(input) { const score = Math.round((0.3+Number(input.udrs_score||10)*0.02)*100)/100; return { version:'3.164.0', module:'pcc_pediatric_neuro_ext54', function:"PediatricMovementDisorderExt", input, score, ts: TS }; }

function PediatricDystoniaClassificationExt(input) { const score = Math.round((0.35+Number(input.twist_score||3)*0.04)*100)/100; return { version:'3.164.0', module:'pcc_pediatric_neuro_ext54', function:"PediatricDystoniaClassificationExt", input, score, ts: TS }; }

function PediatricAtaxiaDiagnosticExt(input) { const score = Math.round((0.3+Number(input.icars_score||8)*0.02)*100)/100; return { version:'3.164.0', module:'pcc_pediatric_neuro_ext54', function:"PediatricAtaxiaDiagnosticExt", input, score, ts: TS }; }

function PediatricChoreaDisorderExt(input) { const score = Math.round((0.4+Number(input.uhdrs||3)*0.04)*100)/100; return { version:'3.164.0', module:'pcc_pediatric_neuro_ext54', function:"PediatricChoreaDisorderExt", input, score, ts: TS }; }

function PediatricTremorPhenotypeExt(input) { const score = Math.round((0.25+Number(input.frequency||3)*0.05)*100)/100; return { version:'3.164.0', module:'pcc_pediatric_neuro_ext54', function:"PediatricTremorPhenotypeExt", input, score, ts: TS }; }

function PediatricTicDisorderExt(input) { const score = Math.round((0.3+Number(input.ygtts_score||8)*0.03)*100)/100; return { version:'3.164.0', module:'pcc_pediatric_neuro_ext54', function:"PediatricTicDisorderExt", input, score, ts: TS }; }

function PediatricMyoclonusExt(input) { const score = Math.round((0.35+Number(input.frequency||3)*0.04)*100)/100; return { version:'3.164.0', module:'pcc_pediatric_neuro_ext54', function:"PediatricMyoclonusExt", input, score, ts: TS }; }

function PediatricParkinsonismExt(input) { const score = Math.round((0.4+Number(input.atp||2)*0.05)*100)/100; return { version:'3.164.0', module:'pcc_pediatric_neuro_ext54', function:"PediatricParkinsonismExt", input, score, ts: TS }; }

function PediatricNeuroacanthocytosisExt(input) { const score = Math.round((0.45+Number(input.hb||11)*0.03)*100)/100; return { version:'3.164.0', module:'pcc_pediatric_neuro_ext54', function:"PediatricNeuroacanthocytosisExt", input, score, ts: TS }; }

module.exports = {
  PediatricNeurodegenerativeExt,
  PediatricMovementDisorderExt,
  PediatricDystoniaClassificationExt,
  PediatricAtaxiaDiagnosticExt,
  PediatricChoreaDisorderExt,
  PediatricTremorPhenotypeExt,
  PediatricTicDisorderExt,
  PediatricMyoclonusExt,
  PediatricParkinsonismExt,
  PediatricNeuroacanthocytosisExt,
};