// filepath: pcc/pcc_pediatric_neuro_ext103/pcc_pediatric_neuro_ext103_engine.js
module.exports.version='v3.213.0';
module.exports.module='pcc_pediatric_neuro_ext103';
module.exports.functions={};
module.exports.functions['PediatricSMARtext']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.smaType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_neuro_ext103',function:'PediatricSMARtext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSMA1Ext']=function(input){const score=Math.round((0.18 + Number(input.age||0.5)*0.05 + Number(input.weakness||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_neuro_ext103',function:'PediatricSMA1Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSMA2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||2)*0.04 + Number(input.sit||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_neuro_ext103',function:'PediatricSMA2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSMA3Ext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.walk||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_neuro_ext103',function:'PediatricSMA3Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDuchenneExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.gower||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_neuro_ext103',function:'PediatricDuchenneExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBeckerExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.dystrophin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_neuro_ext103',function:'PediatricBeckerExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMyotonicExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.myotonia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_neuro_ext103',function:'PediatricMyotonicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPompeExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.gaa||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_neuro_ext103',function:'PediatricPompeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDermatomyositisExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.rash||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_neuro_ext103',function:'PediatricDermatomyositisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCongenitalMyopathyExt']=function(input){const score=Math.round((0.18 + Number(input.age||2)*0.04 + Number(input.hypotonia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_neuro_ext103',function:'PediatricCongenitalMyopathyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.213.0
