// filepath: pcc/pcc_pediatric_surg_ext180/pcc_pediatric_surg_ext180_engine.js
module.exports.version='v3.20.20.0';
module.exports.module='pcc_pediatric_surg_ext180';
module.exports.functions={};
module.exports.functions['PediatricStrokeSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_surg_ext180',function:'PediatricStrokeSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricArtSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pArtSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_surg_ext180',function:'PediatricArtSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSinusSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pSinusSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_surg_ext180',function:'PediatricSinusSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPeriSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pPeriSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_surg_ext180',function:'PediatricPeriSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSickleSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSickleSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_surg_ext180',function:'PediatricSickleSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMoyaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pMoyaSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_surg_ext180',function:'PediatricMoyaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCADSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pCADSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_surg_ext180',function:'PediatricCADSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeRehabTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeRehabTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_surg_ext180',function:'PediatricStrokeRehabTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeFollowTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeFollowTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_surg_ext180',function:'PediatricStrokeFollowTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTIATxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTIATx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_surg_ext180',function:'PediatricTIATxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.20.20.0
