// Auto-generated by gen_p3hc.py -- PCC v3.171.0
"use strict";
const TS = '2026-07-28T12:40:00Z';

function CNSInfectionExt(input) { const score = Math.round((0.4+Number(input.csf_cells||100)*0.001)*100)/100; return { version:'3.171.0', module:'pcc_neuro_ext72', function:'CNSInfectionExt', input, score, ts: TS }; }

function EncephalitisManagementExt(input) { const score = Math.round((0.4+Number(input.acid||0)*0.15)*100)/100; return { version:'3.171.0', module:'pcc_neuro_ext72', function:'EncephalitisManagementExt', input, score, ts: TS }; }

function MeningitisAssessmentExt(input) { const score = Math.round((0.35+Number(input.csf_wbc||500)*0.0004)*100)/100; return { version:'3.171.0', module:'pcc_neuro_ext72', function:'MeningitisAssessmentExt', input, score, ts: TS }; }

function BrainAbscessExt(input) { const score = Math.round((0.4+Number(input.abscess_volume||5)*0.05)*100)/100; return { version:'3.171.0', module:'pcc_neuro_ext72', function:'BrainAbscessExt', input, score, ts: TS }; }

function SpinalEpiduralAbscessExt(input) { const score = Math.round((0.45+Number(input.abscess_length||5)*0.05)*100)/100; return { version:'3.171.0', module:'pcc_neuro_ext72', function:'SpinalEpiduralAbscessExt', input, score, ts: TS }; }

function CerebritisExt(input) { const score = Math.round((0.4+Number(input.fever||1)*0.08)*100)/100; return { version:'3.171.0', module:'pcc_neuro_ext72', function:'CerebritisExt', input, score, ts: TS }; }

function PostInfectiousEncephalitisExt(input) { const score = Math.round((0.45+Number(input.antibody||0)*0.1)*100)/100; return { version:'3.171.0', module:'pcc_neuro_ext72', function:'PostInfectiousEncephalitisExt', input, score, ts: TS }; }

function RASMeningitisExt(input) { const score = Math.round((0.45+Number(input.csf_pressure||30)*0.01)*100)/100; return { version:'3.171.0', module:'pcc_neuro_ext72', function:'RASMeningitisExt', input, score, ts: TS }; }

function TuberculousMeningitisExt(input) { const score = Math.round((0.45+Number(input.csf_glucose||40)*0.005)*100)/100; return { version:'3.171.0', module:'pcc_neuro_ext72', function:'TuberculousMeningitisExt', input, score, ts: TS }; }

function FungalMeningitisExt(input) { const score = Math.round((0.45+Number(input.csf_protein||100)*0.002)*100)/100; return { version:'3.171.0', module:'pcc_neuro_ext72', function:'FungalMeningitisExt', input, score, ts: TS }; }

module.exports = {
  CNSInfectionExt,
  EncephalitisManagementExt,
  MeningitisAssessmentExt,
  BrainAbscessExt,
  SpinalEpiduralAbscessExt,
  CerebritisExt,
  PostInfectiousEncephalitisExt,
  RASMeningitisExt,
  TuberculousMeningitisExt,
  FungalMeningitisExt,
};