// Auto-generated by gen_p3master.py -- PCC 3.305.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.305.0';

function X338AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x338) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_338', function: 'X338AssessmentExt', input, score, ts: TS };
}

function X338ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x338) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_338', function: 'X338ScoreExt', input, score, ts: TS };
}

function X338StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x338) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_338', function: 'X338StageExt', input, score, ts: TS };
}

function X338PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x338) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_338', function: 'X338PlanExt', input, score, ts: TS };
}

function X338RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x338) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_338', function: 'X338RiskExt', input, score, ts: TS };
}

function X338DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x338) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_338', function: 'X338DoseExt', input, score, ts: TS };
}

function X338FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x338) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_338', function: 'X338FrequencyExt', input, score, ts: TS };
}

function X338DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x338) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_338', function: 'X338DurationExt', input, score, ts: TS };
}

function X338FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x338) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_338', function: 'X338FollowupExt', input, score, ts: TS };
}

function X338OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x338) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_338', function: 'X338OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X338AssessmentExt,
  X338ScoreExt,
  X338StageExt,
  X338PlanExt,
  X338RiskExt,
  X338DoseExt,
  X338FrequencyExt,
  X338DurationExt,
  X338FollowupExt,
  X338OutcomeExt,
};