const { getDb } = require('./database.js');
const db = getDb();

// Create table
db.exec(`CREATE TABLE IF NOT EXISTS medical_services (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  specialty TEXT NOT NULL,
  name_en TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  default_price REAL DEFAULT 0,
  category TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)`);

const stmt = db.prepare('INSERT INTO medical_services (specialty, name_en, name_ar, default_price, category) VALUES (?, ?, ?, ?, ?)');
let count = 0;

const services = [
    // ===== DENTAL / طب الأسنان =====
    ['Dental', 'Dental Consultation', 'استشارة أسنان', 100, 'Consultation'],
    ['Dental', 'Dental X-Ray (Periapical)', 'أشعة سنية (ذروية)', 80, 'Diagnostic'],
    ['Dental', 'Panoramic X-Ray (OPG)', 'أشعة بانوراما', 150, 'Diagnostic'],
    ['Dental', 'Cephalometric X-Ray', 'أشعة جانبية للرأس', 120, 'Diagnostic'],
    ['Dental', 'CBCT Scan', 'أشعة مقطعية مخروطية', 350, 'Diagnostic'],
    ['Dental', 'Dental Cleaning / Scaling', 'تنظيف الأسنان', 200, 'Preventive'],
    ['Dental', 'Polishing', 'تلميع الأسنان', 100, 'Preventive'],
    ['Dental', 'Fluoride Treatment', 'علاج الفلورايد', 80, 'Preventive'],
    ['Dental', 'Dental Sealant (per tooth)', 'حشوة وقائية (للسن)', 60, 'Preventive'],
    ['Dental', 'Composite Filling (Anterior)', 'حشوة تجميلية أمامية', 250, 'Restorative'],
    ['Dental', 'Composite Filling (Posterior)', 'حشوة تجميلية خلفية', 300, 'Restorative'],
    ['Dental', 'Amalgam Filling', 'حشوة أملغم', 150, 'Restorative'],
    ['Dental', 'Glass Ionomer Filling', 'حشوة أيونومر زجاجي', 200, 'Restorative'],
    ['Dental', 'Temporary Filling', 'حشوة مؤقتة', 100, 'Restorative'],
    ['Dental', 'Root Canal Treatment (Anterior)', 'علاج عصب أمامي', 800, 'Endodontics'],
    ['Dental', 'Root Canal Treatment (Premolar)', 'علاج عصب ضاحك', 1000, 'Endodontics'],
    ['Dental', 'Root Canal Treatment (Molar)', 'علاج عصب طاحن', 1500, 'Endodontics'],
    ['Dental', 'Root Canal Retreatment', 'إعادة علاج عصب', 1800, 'Endodontics'],
    ['Dental', 'Pulp Capping (Direct)', 'تغطية لب مباشرة', 300, 'Endodontics'],
    ['Dental', 'Pulp Capping (Indirect)', 'تغطية لب غير مباشرة', 250, 'Endodontics'],
    ['Dental', 'Pulpotomy', 'بتر لب', 400, 'Endodontics'],
    ['Dental', 'Post & Core', 'وتد وقلب', 500, 'Endodontics'],
    ['Dental', 'Simple Extraction', 'قلع بسيط', 300, 'Surgery'],
    ['Dental', 'Surgical Extraction', 'قلع جراحي', 600, 'Surgery'],
    ['Dental', 'Wisdom Tooth Extraction (Simple)', 'قلع ضرس عقل بسيط', 500, 'Surgery'],
    ['Dental', 'Wisdom Tooth Extraction (Surgical)', 'قلع ضرس عقل جراحي', 1200, 'Surgery'],
    ['Dental', 'Incision & Drainage (Abscess)', 'شق وتصريف خراج', 400, 'Surgery'],
    ['Dental', 'Frenectomy', 'قص اللجام', 500, 'Surgery'],
    ['Dental', 'Alveoloplasty', 'تعديل العظم السنخي', 600, 'Surgery'],
    ['Dental', 'Apicoectomy', 'استئصال قمة الجذر', 1000, 'Surgery'],
    ['Dental', 'Bone Graft', 'ترقيع عظمي', 2000, 'Surgery'],
    ['Dental', 'Sinus Lift', 'رفع الجيب الأنفي', 3000, 'Surgery'],
    ['Dental', 'PFM Crown', 'تاج خزف معدني', 1200, 'Prosthodontics'],
    ['Dental', 'Zirconia Crown', 'تاج زركونيا', 1800, 'Prosthodontics'],
    ['Dental', 'E-Max Crown', 'تاج إي ماكس', 2000, 'Prosthodontics'],
    ['Dental', 'Temporary Crown', 'تاج مؤقت', 300, 'Prosthodontics'],
    ['Dental', 'Veneer (Porcelain)', 'قشرة خزفية', 2000, 'Prosthodontics'],
    ['Dental', 'Veneer (Composite)', 'قشرة كمبوزت', 800, 'Prosthodontics'],
    ['Dental', 'Dental Bridge (PFM per unit)', 'جسر خزف معدني (للوحدة)', 1200, 'Prosthodontics'],
    ['Dental', 'Dental Bridge (Zirconia per unit)', 'جسر زركونيا (للوحدة)', 1800, 'Prosthodontics'],
    ['Dental', 'Complete Denture (Upper or Lower)', 'طقم أسنان كامل', 3000, 'Prosthodontics'],
    ['Dental', 'Partial Denture (Acrylic)', 'طقم جزئي أكريليك', 2000, 'Prosthodontics'],
    ['Dental', 'Partial Denture (Metal Frame)', 'طقم جزئي معدني', 3500, 'Prosthodontics'],
    ['Dental', 'Denture Repair', 'تصليح طقم أسنان', 300, 'Prosthodontics'],
    ['Dental', 'Denture Relining', 'إعادة تبطين طقم', 500, 'Prosthodontics'],
    ['Dental', 'Dental Implant (Standard)', 'زراعة أسنان عادية', 4000, 'Implantology'],
    ['Dental', 'Dental Implant (Premium/Swiss)', 'زراعة سويسرية', 6000, 'Implantology'],
    ['Dental', 'Implant Abutment', 'دعامة زراعة', 1000, 'Implantology'],
    ['Dental', 'Implant Crown', 'تاج على زراعة', 2000, 'Implantology'],
    ['Dental', 'Mini Implant', 'زراعة مصغرة', 2000, 'Implantology'],
    ['Dental', 'All-on-4 Implants', 'زراعة الكل على 4', 40000, 'Implantology'],
    ['Dental', 'All-on-6 Implants', 'زراعة الكل على 6', 55000, 'Implantology'],
    ['Dental', 'Metal Braces (Full)', 'تقويم معدني كامل', 8000, 'Orthodontics'],
    ['Dental', 'Ceramic Braces (Full)', 'تقويم خزفي كامل', 10000, 'Orthodontics'],
    ['Dental', 'Clear Aligners (Invisalign)', 'تقويم شفاف', 15000, 'Orthodontics'],
    ['Dental', 'Retainer (Fixed)', 'مثبت ثابت', 500, 'Orthodontics'],
    ['Dental', 'Retainer (Removable)', 'مثبت متحرك', 800, 'Orthodontics'],
    ['Dental', 'Space Maintainer', 'حافظ مسافة', 400, 'Orthodontics'],
    ['Dental', 'Orthodontic Consultation', 'استشارة تقويم', 150, 'Orthodontics'],
    ['Dental', 'Braces Adjustment Visit', 'زيارة تعديل تقويم', 200, 'Orthodontics'],
    ['Dental', 'In-Office Teeth Whitening', 'تبييض أسنان بالعيادة', 1500, 'Cosmetic'],
    ['Dental', 'Laser Teeth Whitening', 'تبييض بالليزر', 2000, 'Cosmetic'],
    ['Dental', 'Home Whitening Kit', 'طقم تبييض منزلي', 800, 'Cosmetic'],
    ['Dental', 'Smile Design / Hollywood Smile', 'تصميم ابتسامة هوليوود', 20000, 'Cosmetic'],
    ['Dental', 'Gum Contouring (Laser)', 'تجميل اللثة بالليزر', 1500, 'Cosmetic'],
    ['Dental', 'Tooth Jewel', 'حلية سن', 200, 'Cosmetic'],
    ['Dental', 'Gum Depigmentation', 'إزالة تصبغات اللثة', 1000, 'Cosmetic'],
    ['Dental', 'Deep Scaling & Root Planing', 'تنظيف عميق وكشط جذور', 500, 'Periodontics'],
    ['Dental', 'Gingivectomy', 'استئصال لثة', 800, 'Periodontics'],
    ['Dental', 'Gum Graft', 'ترقيع لثوي', 1500, 'Periodontics'],
    ['Dental', 'Flap Surgery', 'جراحة شريحة لثوية', 2000, 'Periodontics'],
    ['Dental', 'Splinting', 'تثبيت الأسنان المتخلخلة', 400, 'Periodontics'],
    ['Dental', 'Stainless Steel Crown (Pediatric)', 'تاج فولاذي للأطفال', 400, 'Pediatric'],
    ['Dental', 'Pulpotomy (Pediatric)', 'بتر لب أطفال', 350, 'Pediatric'],
    ['Dental', 'Space Maintainer (Pediatric)', 'حافظ مسافة للأطفال', 400, 'Pediatric'],
    ['Dental', 'Nitrous Oxide Sedation', 'تخدير بأكسيد النيتروز', 300, 'Sedation'],
    ['Dental', 'IV Sedation', 'تخدير وريدي', 1500, 'Sedation'],
    ['Dental', 'TMJ Treatment', 'علاج مفصل الفك', 800, 'TMJ'],
    ['Dental', 'Night Guard / Bite Splint', 'واقي ليلي للأسنان', 600, 'TMJ'],
    ['Dental', 'Mouth Guard (Sports)', 'واقي رياضي للفم', 400, 'TMJ'],

    // ===== DERMATOLOGY / الجلدية =====
    ['Dermatology', 'Dermatology Consultation', 'استشارة جلدية', 150, 'Consultation'],
    ['Dermatology', 'Follow-up Visit', 'زيارة متابعة', 100, 'Consultation'],
    ['Dermatology', 'Skin Biopsy', 'خزعة جلدية', 500, 'Diagnostic'],
    ['Dermatology', 'Dermoscopy', 'فحص الجلد بالديرموسكوب', 200, 'Diagnostic'],
    ['Dermatology', 'Wood Lamp Examination', 'فحص بمصباح وود', 100, 'Diagnostic'],
    ['Dermatology', 'Patch Testing (Allergy)', 'اختبار اللصقات للحساسية', 400, 'Diagnostic'],
    ['Dermatology', 'KOH Test (Fungal)', 'فحص فطريات', 80, 'Diagnostic'],
    ['Dermatology', 'Botox (Per Area)', 'بوتوكس (للمنطقة)', 1200, 'Cosmetic Injection'],
    ['Dermatology', 'Botox Full Face', 'بوتوكس كامل الوجه', 3000, 'Cosmetic Injection'],
    ['Dermatology', 'Botox Hyperhidrosis (Underarm)', 'بوتوكس لفرط التعرق', 2500, 'Cosmetic Injection'],
    ['Dermatology', 'Dermal Filler (1ml)', 'فيلر جلدي 1مل', 1500, 'Cosmetic Injection'],
    ['Dermatology', 'Lip Filler', 'فيلر شفايف', 1500, 'Cosmetic Injection'],
    ['Dermatology', 'Cheek Filler', 'فيلر خدود', 2000, 'Cosmetic Injection'],
    ['Dermatology', 'Chin Filler', 'فيلر ذقن', 1500, 'Cosmetic Injection'],
    ['Dermatology', 'Under-Eye Filler', 'فيلر تحت العين', 2000, 'Cosmetic Injection'],
    ['Dermatology', 'Jawline Filler', 'فيلر خط الفك', 2500, 'Cosmetic Injection'],
    ['Dermatology', 'Nose Filler (Non-Surgical Rhinoplasty)', 'فيلر أنف', 2000, 'Cosmetic Injection'],
    ['Dermatology', 'Mesotherapy (Face)', 'ميزوثيرابي للوجه', 800, 'Cosmetic Injection'],
    ['Dermatology', 'Mesotherapy (Hair)', 'ميزوثيرابي للشعر', 800, 'Cosmetic Injection'],
    ['Dermatology', 'PRP (Face)', 'بلازما للوجه', 1000, 'Regenerative'],
    ['Dermatology', 'PRP (Hair / Scalp)', 'بلازما للشعر', 1000, 'Regenerative'],
    ['Dermatology', 'PRP (Joint)', 'بلازما للمفاصل', 1500, 'Regenerative'],
    ['Dermatology', 'Stem Cell Therapy (Face)', 'علاج الخلايا الجذعية للوجه', 3000, 'Regenerative'],
    ['Dermatology', 'Laser Hair Removal (Full Body - Session)', 'إزالة شعر بالليزر كامل الجسم', 1500, 'Laser'],
    ['Dermatology', 'Laser Hair Removal (Face)', 'إزالة شعر الوجه بالليزر', 400, 'Laser'],
    ['Dermatology', 'Laser Hair Removal (Underarm)', 'إزالة شعر الإبط بالليزر', 300, 'Laser'],
    ['Dermatology', 'Laser Hair Removal (Bikini)', 'إزالة شعر البيكيني بالليزر', 500, 'Laser'],
    ['Dermatology', 'Laser Hair Removal (Legs)', 'إزالة شعر الساقين بالليزر', 800, 'Laser'],
    ['Dermatology', 'Laser Hair Removal (Arms)', 'إزالة شعر الذراعين بالليزر', 500, 'Laser'],
    ['Dermatology', 'Laser Hair Removal (Back - Men)', 'إزالة شعر الظهر بالليزر', 800, 'Laser'],
    ['Dermatology', 'Laser Hair Removal (Beard - Men)', 'إزالة شعر اللحية بالليزر', 600, 'Laser'],
    ['Dermatology', 'Fractional CO2 Laser', 'ليزر فراكشنال CO2', 2000, 'Laser'],
    ['Dermatology', 'Nd:YAG Laser (Vascular)', 'ليزر الأوعية الدموية', 1000, 'Laser'],
    ['Dermatology', 'Q-Switch Laser (Pigmentation)', 'ليزر كيوسويتش للتصبغات', 800, 'Laser'],
    ['Dermatology', 'Laser Tattoo Removal (Session)', 'إزالة وشم بالليزر', 1000, 'Laser'],
    ['Dermatology', 'Laser Skin Resurfacing', 'تجديد البشرة بالليزر', 2500, 'Laser'],
    ['Dermatology', 'IPL (Intense Pulsed Light)', 'ضوء نبضي مكثف', 800, 'Laser'],
    ['Dermatology', 'Laser Scar Treatment', 'علاج الندبات بالليزر', 1500, 'Laser'],
    ['Dermatology', 'Chemical Peel (Superficial)', 'تقشير كيميائي سطحي', 500, 'Peels'],
    ['Dermatology', 'Chemical Peel (Medium)', 'تقشير كيميائي متوسط', 800, 'Peels'],
    ['Dermatology', 'Chemical Peel (Deep/TCA)', 'تقشير كيميائي عميق', 1500, 'Peels'],
    ['Dermatology', 'Glycolic Acid Peel', 'تقشير حمض الجليكوليك', 400, 'Peels'],
    ['Dermatology', 'Dermapen / Microneedling', 'ديرمابن / إبر مجهرية', 800, 'Skin Rejuvenation'],
    ['Dermatology', 'HydraFacial', 'هيدرافيشل', 600, 'Skin Rejuvenation'],
    ['Dermatology', 'Carbon Laser Facial', 'كربون ليزر فيشل', 500, 'Skin Rejuvenation'],
    ['Dermatology', 'Oxygen Facial', 'أكسجين فيشل', 400, 'Skin Rejuvenation'],
    ['Dermatology', 'LED Light Therapy', 'علاج ضوئي LED', 300, 'Skin Rejuvenation'],
    ['Dermatology', 'Radiofrequency Skin Tightening', 'شد البشرة بالترددات الراديوية', 1500, 'Skin Rejuvenation'],
    ['Dermatology', 'HIFU (High Intensity Focused Ultrasound)', 'هايفو لشد الوجه', 3000, 'Skin Rejuvenation'],
    ['Dermatology', 'Thread Lift (PDO Threads)', 'خيوط شد الوجه', 4000, 'Skin Rejuvenation'],
    ['Dermatology', 'Cryotherapy (Wart/Lesion)', 'علاج بالتبريد', 300, 'Procedures'],
    ['Dermatology', 'Electrocautery (Skin Tag/Mole)', 'كي كهربائي', 400, 'Procedures'],
    ['Dermatology', 'Mole Removal', 'إزالة شامة', 600, 'Procedures'],
    ['Dermatology', 'Wart Removal', 'إزالة ثآليل', 300, 'Procedures'],
    ['Dermatology', 'Corn/Callus Removal', 'إزالة مسامير القدم', 200, 'Procedures'],
    ['Dermatology', 'Acne Treatment (Session)', 'علاج حب الشباب (جلسة)', 400, 'Acne'],
    ['Dermatology', 'Acne Scar Treatment (Session)', 'علاج آثار حب الشباب', 800, 'Acne'],
    ['Dermatology', 'Comedone Extraction', 'استخراج رؤوس سوداء', 200, 'Acne'],
    ['Dermatology', 'Cortisone Injection (Keloid/Acne)', 'حقن كورتيزون', 300, 'Procedures'],
    ['Dermatology', 'Vitiligo Treatment (Session)', 'علاج البهاق (جلسة)', 500, 'Procedures'],
    ['Dermatology', 'Psoriasis Phototherapy', 'علاج ضوئي للصدفية', 400, 'Procedures'],
    ['Dermatology', 'Hair Transplant (per Graft)', 'زراعة شعر (للبصيلة)', 8, 'Hair'],
    ['Dermatology', 'Scalp Micropigmentation', 'مايكروبيجمنتيشن فروة الرأس', 3000, 'Hair'],
    ['Dermatology', 'Alopecia Treatment', 'علاج الثعلبة', 500, 'Hair'],
    ['Dermatology', 'IV Glutathione (Skin Brightening)', 'جلوتاثيون وريدي للتفتيح', 500, 'IV Therapy'],
    ['Dermatology', 'IV Vitamin C', 'فيتامين سي وريدي', 400, 'IV Therapy'],

    // ===== GENERAL PRACTICE / طب عام =====
    ['General Practice', 'General Consultation', 'استشارة طب عام', 100, 'Consultation'],
    ['General Practice', 'Follow-up Visit', 'زيارة متابعة', 80, 'Consultation'],
    ['General Practice', 'Home Visit', 'زيارة منزلية', 300, 'Consultation'],
    ['General Practice', 'Telemedicine Consultation', 'استشارة عن بعد', 80, 'Consultation'],
    ['General Practice', 'Medical Report / Fitness Certificate', 'تقرير طبي / شهادة لياقة', 100, 'Administrative'],
    ['General Practice', 'Sick Leave Certificate', 'إجازة مرضية', 50, 'Administrative'],
    ['General Practice', 'Pre-Employment Medical Exam', 'فحص ما قبل التوظيف', 200, 'Administrative'],
    ['General Practice', 'Blood Pressure Check', 'قياس ضغط الدم', 30, 'Vitals'],
    ['General Practice', 'Blood Glucose Check', 'قياس السكر', 30, 'Vitals'],
    ['General Practice', 'BMI Assessment', 'تقييم مؤشر كتلة الجسم', 50, 'Vitals'],
    ['General Practice', 'Wound Cleaning & Dressing', 'تنظيف وتضميد جرح', 150, 'Procedures'],
    ['General Practice', 'Suturing (Simple)', 'خياطة بسيطة', 300, 'Procedures'],
    ['General Practice', 'Suturing (Complex)', 'خياطة معقدة', 600, 'Procedures'],
    ['General Practice', 'Suture Removal', 'فك غرز', 100, 'Procedures'],
    ['General Practice', 'Abscess Incision & Drainage', 'شق وتصريف خراج', 400, 'Procedures'],
    ['General Practice', 'Foreign Body Removal', 'إزالة جسم غريب', 300, 'Procedures'],
    ['General Practice', 'Ear Wax Removal / Irrigation', 'إزالة شمع الأذن', 150, 'Procedures'],
    ['General Practice', 'Nasal Packing', 'حشو أنفي', 200, 'Procedures'],
    ['General Practice', 'IM Injection', 'حقنة عضلية', 30, 'Injections'],
    ['General Practice', 'IV Injection', 'حقنة وريدية', 50, 'Injections'],
    ['General Practice', 'SC Injection', 'حقنة تحت الجلد', 30, 'Injections'],
    ['General Practice', 'IV Cannulation', 'تركيب كانيولا', 80, 'Injections'],
    ['General Practice', 'IV Fluid Administration', 'محاليل وريدية', 150, 'Injections'],
    ['General Practice', 'Nebulizer Session', 'جلسة بخار', 80, 'Respiratory'],
    ['General Practice', 'Oxygen Therapy', 'علاج بالأكسجين', 100, 'Respiratory'],
    ['General Practice', 'ECG (Electrocardiogram)', 'تخطيط القلب', 100, 'Cardiac'],
    ['General Practice', 'Vaccination (Adult)', 'تطعيم بالغين', 100, 'Vaccination'],
    ['General Practice', 'Flu Vaccination', 'تطعيم الانفلونزا', 100, 'Vaccination'],
    ['General Practice', 'Hepatitis B Vaccination', 'تطعيم التهاب الكبد ب', 150, 'Vaccination'],
    ['General Practice', 'Tetanus Vaccination', 'تطعيم الكزاز', 80, 'Vaccination'],
    ['General Practice', 'Child Vaccination', 'تطعيم أطفال', 100, 'Vaccination'],
    ['General Practice', 'Urinary Catheter Insertion', 'تركيب قسطرة بولية', 200, 'Procedures'],
    ['General Practice', 'NG Tube Insertion', 'تركيب أنبوب أنفي معدي', 200, 'Procedures'],
    ['General Practice', 'Splinting (Fracture)', 'تجبير كسر', 300, 'Orthopedic'],
    ['General Practice', 'Cast Application', 'تركيب جبس', 400, 'Orthopedic'],
    ['General Practice', 'Cast Removal', 'إزالة جبس', 150, 'Orthopedic'],
    ['General Practice', 'Burn Dressing (Minor)', 'تضميد حروق بسيطة', 200, 'Procedures'],
    ['General Practice', 'Eye Irrigation', 'غسيل عين', 100, 'Procedures'],
    ['General Practice', 'Pap Smear', 'مسحة عنق الرحم', 200, 'Screening'],
    ['General Practice', 'Annual Health Checkup', 'فحص سنوي شامل', 500, 'Screening'],

    // ===== ORTHOPEDICS / العظام =====
    ['Orthopedics', 'Orthopedic Consultation', 'استشارة عظام', 150, 'Consultation'],
    ['Orthopedics', 'Joint Injection (Cortisone)', 'حقن مفصل كورتيزون', 500, 'Injections'],
    ['Orthopedics', 'Joint Injection (Hyaluronic Acid)', 'حقن مفصل هيالورونيك', 800, 'Injections'],
    ['Orthopedics', 'PRP Joint Injection', 'حقن بلازما للمفصل', 1200, 'Injections'],
    ['Orthopedics', 'Trigger Point Injection', 'حقن نقاط الزناد', 300, 'Injections'],
    ['Orthopedics', 'Carpal Tunnel Injection', 'حقن نفق الرسغ', 400, 'Injections'],
    ['Orthopedics', 'Closed Reduction (Fracture)', 'رد مغلق لكسر', 1000, 'Procedures'],
    ['Orthopedics', 'Cast Application', 'تركيب جبس', 400, 'Procedures'],
    ['Orthopedics', 'Cast Removal', 'إزالة جبس', 150, 'Procedures'],
    ['Orthopedics', 'Splinting', 'تجبير', 300, 'Procedures'],
    ['Orthopedics', 'Joint Aspiration', 'سحب سائل مفصلي', 400, 'Procedures'],
    ['Orthopedics', 'Physical Therapy Session', 'جلسة علاج طبيعي', 200, 'Rehab'],
    ['Orthopedics', 'Shoulder Dislocation Reduction', 'رد خلع كتف', 800, 'Procedures'],
    ['Orthopedics', 'Knee Arthroscopy', 'منظار ركبة', 8000, 'Surgery'],
    ['Orthopedics', 'ACL Reconstruction', 'إعادة بناء رباط صليبي', 20000, 'Surgery'],
    ['Orthopedics', 'Meniscus Repair', 'إصلاح غضروف هلالي', 12000, 'Surgery'],
    ['Orthopedics', 'Total Knee Replacement', 'تبديل ركبة كامل', 35000, 'Surgery'],
    ['Orthopedics', 'Total Hip Replacement', 'تبديل ورك كامل', 40000, 'Surgery'],
    ['Orthopedics', 'Rotator Cuff Repair', 'إصلاح الكفة المدورة', 15000, 'Surgery'],
    ['Orthopedics', 'Spine Surgery (Discectomy)', 'جراحة عمود فقري', 25000, 'Surgery'],
    ['Orthopedics', 'Fracture Fixation (ORIF)', 'تثبيت كسر جراحي', 15000, 'Surgery'],

    // ===== ENT / أنف أذن حنجرة =====
    ['ENT', 'ENT Consultation', 'استشارة أنف أذن حنجرة', 150, 'Consultation'],
    ['ENT', 'Audiometry (Hearing Test)', 'فحص سمع', 200, 'Diagnostic'],
    ['ENT', 'Tympanometry', 'قياس طبلة الأذن', 150, 'Diagnostic'],
    ['ENT', 'Nasal Endoscopy', 'منظار أنفي', 300, 'Diagnostic'],
    ['ENT', 'Laryngoscopy', 'منظار حنجري', 400, 'Diagnostic'],
    ['ENT', 'Ear Wax Removal', 'إزالة شمع الأذن', 150, 'Procedures'],
    ['ENT', 'Ear Syringing', 'غسيل أذن', 100, 'Procedures'],
    ['ENT', 'Nasal Cauterization', 'كي الأنف', 300, 'Procedures'],
    ['ENT', 'Foreign Body Removal (Ear/Nose)', 'إزالة جسم غريب', 300, 'Procedures'],
    ['ENT', 'Tonsillectomy', 'استئصال اللوزتين', 5000, 'Surgery'],
    ['ENT', 'Adenoidectomy', 'استئصال اللحمية', 4000, 'Surgery'],
    ['ENT', 'Septoplasty', 'تعديل الحاجز الأنفي', 8000, 'Surgery'],
    ['ENT', 'Rhinoplasty', 'تجميل الأنف', 15000, 'Surgery'],
    ['ENT', 'Myringotomy with Tubes', 'أنابيب الأذن', 3000, 'Surgery'],
    ['ENT', 'Turbinate Reduction', 'تصغير قرنيات الأنف', 4000, 'Surgery'],
    ['ENT', 'FESS (Sinus Surgery)', 'جراحة الجيوب الأنفية', 10000, 'Surgery'],
    ['ENT', 'Thyroidectomy', 'استئصال الغدة الدرقية', 15000, 'Surgery'],
    ['ENT', 'Sleep Study (Polysomnography)', 'دراسة النوم', 2000, 'Diagnostic'],

    // ===== OPHTHALMOLOGY / العيون =====
    ['Ophthalmology', 'Eye Consultation', 'استشارة عيون', 150, 'Consultation'],
    ['Ophthalmology', 'Visual Acuity Test', 'فحص حدة البصر', 50, 'Diagnostic'],
    ['Ophthalmology', 'Refraction Test', 'فحص انكسار', 100, 'Diagnostic'],
    ['Ophthalmology', 'Fundoscopy', 'فحص قاع العين', 150, 'Diagnostic'],
    ['Ophthalmology', 'Tonometry (IOP)', 'قياس ضغط العين', 100, 'Diagnostic'],
    ['Ophthalmology', 'OCT Scan', 'تصوير مقطعي للعين', 300, 'Diagnostic'],
    ['Ophthalmology', 'Visual Field Test', 'فحص ساحة الإبصار', 200, 'Diagnostic'],
    ['Ophthalmology', 'LASIK Surgery', 'عملية ليزك', 5000, 'Surgery'],
    ['Ophthalmology', 'PRK Surgery', 'عملية PRK', 4000, 'Surgery'],
    ['Ophthalmology', 'SMILE Surgery', 'عملية سمايل', 6000, 'Surgery'],
    ['Ophthalmology', 'Cataract Surgery (Phaco)', 'عملية ماء أبيض', 8000, 'Surgery'],
    ['Ophthalmology', 'Glaucoma Surgery', 'جراحة المياه الزرقاء', 10000, 'Surgery'],
    ['Ophthalmology', 'Retinal Laser', 'ليزر شبكية', 2000, 'Laser'],
    ['Ophthalmology', 'YAG Laser Capsulotomy', 'ليزر ياج', 1500, 'Laser'],
    ['Ophthalmology', 'Intravitreal Injection', 'حقن داخل العين', 2000, 'Injections'],
    ['Ophthalmology', 'Chalazion Removal', 'إزالة كيس دهني', 800, 'Procedures'],
    ['Ophthalmology', 'Pterygium Surgery', 'إزالة ظفرة', 3000, 'Surgery'],
    ['Ophthalmology', 'Strabismus Surgery', 'جراحة حول', 8000, 'Surgery'],
    ['Ophthalmology', 'Contact Lens Fitting', 'تركيب عدسات لاصقة', 200, 'Optical'],
    ['Ophthalmology', 'Glasses Prescription', 'وصفة نظارات', 100, 'Optical'],

    // ===== INTERNAL MEDICINE / الباطنية =====
    ['Internal Medicine', 'Internal Medicine Consultation', 'استشارة باطنية', 150, 'Consultation'],
    ['Internal Medicine', 'Diabetes Management', 'إدارة السكري', 200, 'Chronic'],
    ['Internal Medicine', 'Hypertension Management', 'إدارة ارتفاع الضغط', 200, 'Chronic'],
    ['Internal Medicine', 'Asthma Management', 'إدارة الربو', 200, 'Chronic'],
    ['Internal Medicine', 'Thyroid Disorder Management', 'إدارة اضطرابات الغدة الدرقية', 200, 'Chronic'],
    ['Internal Medicine', 'Liver Disease Management', 'إدارة أمراض الكبد', 250, 'Chronic'],
    ['Internal Medicine', 'Kidney Disease Management', 'إدارة أمراض الكلى', 250, 'Chronic'],
    ['Internal Medicine', 'Joint Aspiration', 'سحب سائل مفصلي', 400, 'Procedures'],
    ['Internal Medicine', 'Paracentesis', 'بزل بطني', 800, 'Procedures'],
    ['Internal Medicine', 'Thoracentesis', 'بزل صدري', 1000, 'Procedures'],
    ['Internal Medicine', 'Bone Marrow Biopsy', 'خزعة نخاع عظم', 1500, 'Procedures'],

    // ===== PEDIATRICS / الأطفال =====
    ['Pediatrics', 'Pediatric Consultation', 'استشارة أطفال', 120, 'Consultation'],
    ['Pediatrics', 'Well-Baby Check', 'فحص طفل سليم', 100, 'Screening'],
    ['Pediatrics', 'Growth & Development Assessment', 'تقييم نمو وتطور', 150, 'Screening'],
    ['Pediatrics', 'Newborn Exam', 'فحص مولود', 200, 'Screening'],
    ['Pediatrics', 'Childhood Vaccination', 'تطعيمات أطفال', 100, 'Vaccination'],
    ['Pediatrics', 'Nebulizer Session (Pediatric)', 'جلسة بخار أطفال', 80, 'Respiratory'],
    ['Pediatrics', 'Circumcision', 'ختان', 1500, 'Surgery'],
    ['Pediatrics', 'Tongue Tie Release', 'قص لجام اللسان', 500, 'Surgery'],
    ['Pediatrics', 'Ear Piercing (Medical)', 'تثقيب الأذن طبي', 150, 'Procedures'],

    // ===== OB/GYN / نساء وولادة =====
    ['OB/GYN', 'OB/GYN Consultation', 'استشارة نساء وولادة', 150, 'Consultation'],
    ['OB/GYN', 'Prenatal Visit', 'زيارة متابعة حمل', 120, 'Obstetric'],
    ['OB/GYN', 'Obstetric Ultrasound', 'أشعة صوتية للحامل', 200, 'Obstetric'],
    ['OB/GYN', '3D/4D Ultrasound', 'أشعة ثلاثية/رباعية الأبعاد', 400, 'Obstetric'],
    ['OB/GYN', 'Non-Stress Test (NST)', 'فحص عدم الإجهاد', 200, 'Obstetric'],
    ['OB/GYN', 'Pap Smear', 'مسحة عنق رحم', 200, 'Screening'],
    ['OB/GYN', 'Colposcopy', 'تنظير عنق الرحم', 500, 'Diagnostic'],
    ['OB/GYN', 'IUD Insertion', 'تركيب لولب', 500, 'Procedures'],
    ['OB/GYN', 'IUD Removal', 'إزالة لولب', 300, 'Procedures'],
    ['OB/GYN', 'Contraceptive Implant', 'تركيب شريحة منع حمل', 800, 'Procedures'],
    ['OB/GYN', 'Cesarean Section', 'ولادة قيصرية', 15000, 'Surgery'],
    ['OB/GYN', 'Normal Delivery', 'ولادة طبيعية', 8000, 'Obstetric'],
    ['OB/GYN', 'Hysteroscopy', 'منظار رحمي', 5000, 'Surgery'],
    ['OB/GYN', 'Laparoscopy (Diagnostic)', 'منظار بطني تشخيصي', 8000, 'Surgery'],
    ['OB/GYN', 'Myomectomy', 'استئصال أورام ليفية', 12000, 'Surgery'],
    ['OB/GYN', 'Hysterectomy', 'استئصال رحم', 20000, 'Surgery'],

    // ===== UROLOGY / المسالك البولية =====
    ['Urology', 'Urology Consultation', 'استشارة مسالك بولية', 150, 'Consultation'],
    ['Urology', 'Cystoscopy', 'منظار مثانة', 3000, 'Diagnostic'],
    ['Urology', 'Urodynamic Study', 'دراسة ديناميكية البول', 1500, 'Diagnostic'],
    ['Urology', 'Circumcision (Adult)', 'ختان بالغين', 2000, 'Surgery'],
    ['Urology', 'ESWL (Kidney Stone)', 'تفتيت حصوات بالموجات', 5000, 'Surgery'],
    ['Urology', 'Ureteroscopy', 'منظار حالب', 8000, 'Surgery'],
    ['Urology', 'TURP (Prostate)', 'استئصال بروستاتا عبر الإحليل', 12000, 'Surgery'],
    ['Urology', 'Vasectomy', 'قطع القناة الدافقة', 3000, 'Surgery'],
    ['Urology', 'Varicocelectomy', 'استئصال دوالي الخصية', 6000, 'Surgery'],
    ['Urology', 'Hydrocelectomy', 'استئصال قيلة مائية', 4000, 'Surgery'],

    // ===== CARDIOLOGY / القلب =====
    ['Cardiology', 'Cardiology Consultation', 'استشارة قلب', 200, 'Consultation'],
    ['Cardiology', 'ECG', 'تخطيط القلب', 100, 'Diagnostic'],
    ['Cardiology', 'Echocardiogram', 'إيكو القلب', 500, 'Diagnostic'],
    ['Cardiology', 'Stress Test (Treadmill)', 'اختبار جهد', 800, 'Diagnostic'],
    ['Cardiology', 'Holter Monitor (24hrs)', 'هولتر مراقبة 24 ساعة', 600, 'Diagnostic'],
    ['Cardiology', 'Cardiac Catheterization', 'قسطرة قلبية', 15000, 'Surgery'],
    ['Cardiology', 'Coronary Angioplasty / Stent', 'توسيع شريان ودعامة', 25000, 'Surgery'],
    ['Cardiology', 'Pacemaker Implantation', 'تركيب منظم ضربات القلب', 30000, 'Surgery'],

    // ===== PSYCHIATRY / الطب النفسي =====
    ['Psychiatry', 'Psychiatric Consultation', 'استشارة نفسية', 200, 'Consultation'],
    ['Psychiatry', 'Psychotherapy Session', 'جلسة علاج نفسي', 200, 'Therapy'],
    ['Psychiatry', 'CBT Session', 'جلسة علاج سلوكي معرفي', 250, 'Therapy'],
    ['Psychiatry', 'Family Therapy Session', 'جلسة علاج أسري', 300, 'Therapy'],
    ['Psychiatry', 'Psychological Assessment', 'تقييم نفسي', 500, 'Diagnostic'],
    ['Psychiatry', 'ADHD Assessment', 'تقييم فرط الحركة', 400, 'Diagnostic'],
    ['Psychiatry', 'Addiction Counseling', 'استشارات إدمان', 200, 'Therapy'],
];

db.transaction(() => {
    for (const s of services) {
        try {
            stmt.run(s[0], s[1], s[2], s[3], s[4]);
            count++;
        } catch (e) { }
    }
})();

console.log(`Inserted ${count} medical services across all specialties.`);
