// Insert tier14-17 mounts into the real server.js
const fs = require('fs');
const c = fs.readFileSync('server.js.full', 'utf8');
const idx = c.lastIndexOf('startServer();');
if (idx < 0) { console.error('startServer not found'); process.exit(1); }
const mounts = `
try { app.use('/api/pharm_order', require('./tier14_pharm_ext_101_order_router')); } catch(e) { console.error('pharm_order mount failed', e.message); }
try { app.use('/api/pharm_compounding', require('./tier14_pharm_ext_102_compounding_router')); } catch(e) { console.error('pharm_compounding mount failed', e.message); }
try { app.use('/api/pharm_interaction', require('./tier14_pharm_ext_103_interaction_router')); } catch(e) { console.error('pharm_interaction mount failed', e.message); }
try { app.use('/api/pharm_formulary', require('./tier14_pharm_ext_104_formulary_router')); } catch(e) { console.error('pharm_formulary mount failed', e.message); }
try { app.use('/api/pharm_inventory', require('./tier14_pharm_ext_105_inventory_router')); } catch(e) { console.error('pharm_inventory mount failed', e.message); }
try { app.use('/api/pharm_stewardship', require('./tier14_pharm_ext_106_stewardship_router')); } catch(e) { console.error('pharm_stewardship mount failed', e.message); }
try { app.use('/api/icu_vitals', require('./tier15_icu_ext_107_vitals_router')); } catch(e) { console.error('icu_vitals mount failed', e.message); }
try { app.use('/api/icu_hemodynamics', require('./tier15_icu_ext_108_hemodynamics_router')); } catch(e) { console.error('icu_hemodynamics mount failed', e.message); }
try { app.use('/api/icu_renal', require('./tier15_icu_ext_109_renal_router')); } catch(e) { console.error('icu_renal mount failed', e.message); }
try { app.use('/api/icu_nutrition', require('./tier15_icu_ext_110_nutrition_router')); } catch(e) { console.error('icu_nutrition mount failed', e.message); }
try { app.use('/api/icu_admin', require('./tier15_icu_ext_111_icu_admin_router')); } catch(e) { console.error('icu_admin mount failed', e.message); }
try { app.use('/api/or_preop', require('./tier16_or_ext_112_preop_router')); } catch(e) { console.error('or_preop mount failed', e.message); }
try { app.use('/api/or_intraop', require('./tier16_or_ext_113_intraop_router')); } catch(e) { console.error('or_intraop mount failed', e.message); }
try { app.use('/api/or_postop', require('./tier16_or_ext_114_postop_router')); } catch(e) { console.error('or_postop mount failed', e.message); }
try { app.use('/api/or_scheduling', require('./tier16_or_ext_115_scheduling_router')); } catch(e) { console.error('or_scheduling mount failed', e.message); }
try { app.use('/api/or_surgical', require('./tier16_or_ext_116_surgical_router')); } catch(e) { console.error('or_surgical mount failed', e.message); }
try { app.use('/api/portal_auth', require('./tier17_portal_ext_117_auth_router')); } catch(e) { console.error('portal_auth mount failed', e.message); }
try { app.use('/api/portal_records', require('./tier17_portal_ext_118_records_router')); } catch(e) { console.error('portal_records mount failed', e.message); }
try { app.use('/api/portal_appointments', require('./tier17_portal_ext_119_appointments_router')); } catch(e) { console.error('portal_appointments mount failed', e.message); }
try { app.use('/api/portal_billing', require('./tier17_portal_ext_120_billing_router')); } catch(e) { console.error('portal_billing mount failed', e.message); }
try { app.use('/api/portal_messaging', require('./tier17_portal_ext_121_messaging_router')); } catch(e) { console.error('portal_messaging mount failed', e.message); }
try { app.use('/api/infx_outbreak', require('./tier18_infx_ext_122_outbreak_router')); } catch(e) { console.error('infx_outbreak mount failed', e.message); }
try { app.use('/api/infx_isolation', require('./tier18_infx_ext_123_isolation_router')); } catch(e) { console.error('infx_isolation mount failed', e.message); }
try { app.use('/api/infx_mdro', require('./tier18_infx_ext_124_mdro_router')); } catch(e) { console.error('infx_mdro mount failed', e.message); }
try { app.use('/api/infx_surveillance', require('./tier18_infx_ext_125_surveillance_router')); } catch(e) { console.error('infx_surveillance mount failed', e.message); }
try { app.use('/api/infx_employee', require('./tier18_infx_ext_126_employee_router')); } catch(e) { console.error('infx_employee mount failed', e.message); }
try { app.use('/api/him_coding', require('./tier19_him_ext_127_coding_router')); } catch(e) { console.error('him_coding mount failed', e.message); }
try { app.use('/api/him_roi', require('./tier19_him_ext_128_roi_router')); } catch(e) { console.error('him_roi mount failed', e.message); }
try { app.use('/api/him_deficiency', require('./tier19_him_ext_129_deficiency_router')); } catch(e) { console.error('him_deficiency mount failed', e.message); }
try { app.use('/api/him_audit', require('./tier19_him_ext_130_audit_router')); } catch(e) { console.error('him_audit mount failed', e.message); }
try { app.use('/api/him_release', require('./tier19_him_ext_131_release_router')); } catch(e) { console.error('him_release mount failed', e.message); }
try { app.use('/api/research_trial', require('./tier20_research_ext_132_trial_router')); } catch(e) { console.error('research_trial mount failed', e.message); }
try { app.use('/api/research_consent', require('./tier20_research_ext_133_consent_router')); } catch(e) { console.error('research_consent mount failed', e.message); }
try { app.use('/api/research_irb', require('./tier20_research_ext_134_irb_router')); } catch(e) { console.error('research_irb mount failed', e.message); }
try { app.use('/api/research_recruitment', require('./tier20_research_ext_135_recruitment_router')); } catch(e) { console.error('research_recruitment mount failed', e.message); }
try { app.use('/api/research_biobank', require('./tier20_research_ext_136_biobank_router')); } catch(e) { console.error('research_biobank mount failed', e.message); }
try { app.use('/api/sched_provider', require('./tier21_sched_ext_137_provider_router')); } catch(e) { console.error('sched_provider mount failed', e.message); }
try { app.use('/api/sched_call', require('./tier21_sched_ext_138_call_router')); } catch(e) { console.error('sched_call mount failed', e.message); }
try { app.use('/api/sched_template', require('./tier21_sched_ext_139_template_router')); } catch(e) { console.error('sched_template mount failed', e.message); }
try { app.use('/api/sched_waitlist', require('./tier21_sched_ext_140_waitlist_router')); } catch(e) { console.error('sched_waitlist mount failed', e.message); }
try { app.use('/api/sched_appointment', require('./tier21_sched_ext_141_appointment_router')); } catch(e) { console.error('sched_appointment mount failed', e.message); }
try { app.use('/api/sched_staff', require('./tier21_sched_ext_142_staff_router')); } catch(e) { console.error('sched_staff mount failed', e.message); }
try { app.use('/api/wound_assessment', require('./tier22_wound_ext_143_assessment_router')); } catch(e) { console.error('wound_assessment mount failed', e.message); }
try { app.use('/api/wound_dressing', require('./tier22_wound_ext_144_dressing_router')); } catch(e) { console.error('wound_dressing mount failed', e.message); }
try { app.use('/api/wound_healing', require('./tier22_wound_ext_145_healing_router')); } catch(e) { console.error('wound_healing mount failed', e.message); }
try { app.use('/api/wound_measurement', require('./tier22_wound_ext_146_measurement_router')); } catch(e) { console.error('wound_measurement mount failed', e.message); }
try { app.use('/api/wound_staging', require('./tier22_wound_ext_147_staging_router')); } catch(e) { console.error('wound_staging mount failed', e.message); }
try { app.use('/api/dialysis_access', require('./tier23_dialysis_ext_148_access_router')); } catch(e) { console.error('dialysis_access mount failed', e.message); }
try { app.use('/api/dialysis_adequacy', require('./tier23_dialysis_ext_149_adequacy_router')); } catch(e) { console.error('dialysis_adequacy mount failed', e.message); }
try { app.use('/api/dialysis_complication', require('./tier23_dialysis_ext_150_complication_router')); } catch(e) { console.error('dialysis_complication mount failed', e.message); }
try { app.use('/api/dialysis_peritoneal', require('./tier23_dialysis_ext_151_peritoneal_router')); } catch(e) { console.error('dialysis_peritoneal mount failed', e.message); }
try { app.use('/api/dialysis_dialyzer', require('./tier23_dialysis_ext_152_dialyzer_router')); } catch(e) { console.error('dialysis_dialyzer mount failed', e.message); }
try { app.use('/api/tx_candidate', require('./tier24_transplant_ext_153_candidate_router')); } catch(e) { console.error('tx_candidate mount failed', e.message); }
try { app.use('/api/tx_donor', require('./tier24_transplant_ext_154_donor_router')); } catch(e) { console.error('tx_donor mount failed', e.message); }
try { app.use('/api/tx_immuno', require('./tier24_transplant_ext_155_immuno_router')); } catch(e) { console.error('tx_immuno mount failed', e.message); }
try { app.use('/api/tx_outcome', require('./tier24_transplant_ext_156_outcome_router')); } catch(e) { console.error('tx_outcome mount failed', e.message); }
try { app.use('/api/tx_followup', require('./tier24_transplant_ext_157_followup_router')); } catch(e) { console.error('tx_followup mount failed', e.message); }
try { app.use('/api/rehab_function', require('./tier25_rehab_ext_158_function_router')); } catch(e) { console.error('rehab_function mount failed', e.message); }
try { app.use('/api/rehab_therapy', require('./tier25_rehab_ext_159_therapy_router')); } catch(e) { console.error('rehab_therapy mount failed', e.message); }
try { app.use('/api/rehab_prosthetic', require('./tier25_rehab_ext_160_prosthetic_router')); } catch(e) { console.error('rehab_prosthetic mount failed', e.message); }
try { app.use('/api/rehab_neuro', require('./tier25_rehab_ext_161_neuro_router')); } catch(e) { console.error('rehab_neuro mount failed', e.message); }
try { app.use('/api/rehab_pediatric', require('./tier25_rehab_ext_162_pediatric_router')); } catch(e) { console.error('rehab_pediatric mount failed', e.message); }
try { app.use('/api/oncology_tumor', require('./tier26_oncology_ext_163_tumor_router')); } catch(e) { console.error('oncology_tumor mount failed', e.message); }
try { app.use('/api/oncology_chemo', require('./tier26_oncology_ext_164_chemo_router')); } catch(e) { console.error('oncology_chemo mount failed', e.message); }
try { app.use('/api/oncology_radiation', require('./tier26_oncology_ext_165_radiation_router')); } catch(e) { console.error('oncology_radiation mount failed', e.message); }
try { app.use('/api/oncology_palliative', require('./tier26_oncology_ext_166_palliative_router')); } catch(e) { console.error('oncology_palliative mount failed', e.message); }
try { app.use('/api/oncology_survivor', require('./tier26_oncology_ext_167_survivor_router')); } catch(e) { console.error('oncology_survivor mount failed', e.message); }
try { app.use('/api/ed_triage', require('./tier27_emergency_ext_168_triage_router')); } catch(e) { console.error('ed_triage mount failed', e.message); }
try { app.use('/api/ed_resus', require('./tier27_emergency_ext_169_resuscitation_router')); } catch(e) { console.error('ed_resus mount failed', e.message); }
try { app.use('/api/ed_trauma', require('./tier27_emergency_ext_170_trauma_router')); } catch(e) { console.error('ed_trauma mount failed', e.message); }
try { app.use('/api/ed_tox', require('./tier27_emergency_ext_171_toxicology_router')); } catch(e) { console.error('ed_tox mount failed', e.message); }
try { app.use('/api/ed_ems', require('./tier27_emergency_ext_172_ems_router')); } catch(e) { console.error('ed_ems mount failed', e.message); }
try { app.use('/api/ob_prenatal', require('./tier28_obstetrics_ext_173_prenatal_router')); } catch(e) { console.error('ob_prenatal mount failed', e.message); }
try { app.use('/api/ob_labor', require('./tier28_obstetrics_ext_174_labor_router')); } catch(e) { console.error('ob_labor mount failed', e.message); }
try { app.use('/api/ob_gynecology', require('./tier28_obstetrics_ext_175_gynecology_router')); } catch(e) { console.error('ob_gynecology mount failed', e.message); }
try { app.use('/api/ob_neonatal', require('./tier28_obstetrics_ext_176_neonatal_router')); } catch(e) { console.error('ob_neonatal mount failed', e.message); }
try { app.use('/api/ob_reproduction', require('./tier28_obstetrics_ext_177_reproduction_router')); } catch(e) { console.error('ob_reproduction mount failed', e.message); }
try { app.use('/api/cardio_stress', require('./tier29_cardiology_ext_178_stress_router')); } catch(e) { console.error('cardio_stress mount failed', e.message); }
try { app.use('/api/cardio_echo', require('./tier29_cardiology_ext_179_echo_router')); } catch(e) { console.error('cardio_echo mount failed', e.message); }
try { app.use('/api/cardio_cath', require('./tier29_cardiology_ext_180_cath_router')); } catch(e) { console.error('cardio_cath mount failed', e.message); }
try { app.use('/api/cardio_ep', require('./tier29_cardiology_ext_181_ep_router')); } catch(e) { console.error('cardio_ep mount failed', e.message); }
try { app.use('/api/cardio_hf', require('./tier29_cardiology_ext_182_hf_router')); } catch(e) { console.error('cardio_hf mount failed', e.message); }
try { app.use('/api/hem_transfusion', require('./tier30_hematology_ext_183_transfusion_router')); } catch(e) { console.error('hem_transfusion mount failed', e.message); }
try { app.use('/api/hem_apheresis', require('./tier30_hematology_ext_184_apheresis_router')); } catch(e) { console.error('hem_apheresis mount failed', e.message); }
try { app.use('/api/hem_stem_cell', require('./tier30_hematology_ext_185_stem_cell_router')); } catch(e) { console.error('hem_stem_cell mount failed', e.message); }
try { app.use('/api/hem_cell_therapy', require('./tier30_hematology_ext_186_cell_therapy_router')); } catch(e) { console.error('hem_cell_therapy mount failed', e.message); }
try { app.use('/api/hem_coag_ext', require('./tier30_hematology_ext_187_coag_ext_router')); } catch(e) { console.error('hem_coag_ext mount failed', e.message); }
try { app.use('/api/nephro_ckd', require('./tier31_nephrology_ext_188_ckd_router')); } catch(e) { console.error('nephro_ckd mount failed', e.message); }
try { app.use('/api/nephro_da', require('./tier31_nephrology_ext_189_dialysis_access_router')); } catch(e) { console.error('nephro_da mount failed', e.message); }
try { app.use('/api/nephro_immuno', require('./tier31_nephrology_ext_190_transplant_immuno_router')); } catch(e) { console.error('nephro_immuno mount failed', e.message); }
try { app.use('/api/nephro_ext', require('./tier31_nephrology_ext_191_nephro_ext_router')); } catch(e) { console.error('nephro_ext mount failed', e.message); }
try { app.use('/api/nephro_nutrition', require('./tier31_nephrology_ext_192_renal_nutrition_router')); } catch(e) { console.error('nephro_nutrition mount failed', e.message); }
try { app.use('/api/pulm_copd', require('./tier32_pulmonology_ext_193_copd_router')); } catch(e) { console.error('pulm_copd mount failed', e.message); }
try { app.use('/api/pulm_asthma', require('./tier32_pulmonology_ext_194_asthma_router')); } catch(e) { console.error('pulm_asthma mount failed', e.message); }
try { app.use('/api/pulm_sleep', require('./tier32_pulmonology_ext_195_sleep_router')); } catch(e) { console.error('pulm_sleep mount failed', e.message); }
try { app.use('/api/pulm_ild', require('./tier32_pulmonology_ext_196_ild_router')); } catch(e) { console.error('pulm_ild mount failed', e.message); }
try { app.use('/api/pulm_pc', require('./tier32_pulmonology_ext_197_pulm_critical_router')); } catch(e) { console.error('pulm_pc mount failed', e.message); }
try { app.use('/api/endo_diabetes', require('./tier33_endocrinology_ext_198_diabetes_router')); } catch(e) { console.error('endo_diabetes mount failed', e.message); }
try { app.use('/api/endo_thyroid', require('./tier33_endocrinology_ext_199_thyroid_router')); } catch(e) { console.error('endo_thyroid mount failed', e.message); }
try { app.use('/api/endo_adrenal', require('./tier33_endocrinology_ext_200_adrenal_router')); } catch(e) { console.error('endo_adrenal mount failed', e.message); }
try { app.use('/api/endo_pituitary', require('./tier33_endocrinology_ext_201_pituitary_router')); } catch(e) { console.error('endo_pituitary mount failed', e.message); }
try { app.use('/api/endo_metabolic', require('./tier33_endocrinology_ext_202_metabolic_router')); } catch(e) { console.error('endo_metabolic mount failed', e.message); }
try { app.use('/api/gi_ibd', require('./tier34_gastroenterology_ext_203_ibd_router')); } catch(e) { console.error('gi_ibd mount failed', e.message); }
try { app.use('/api/gi_hepa', require('./tier34_gastroenterology_ext_204_hepatology_router')); } catch(e) { console.error('gi_hepa mount failed', e.message); }
try { app.use('/api/gi_end', require('./tier34_gastroenterology_ext_205_endoscopy_router')); } catch(e) { console.error('gi_end mount failed', e.message); }
try { app.use('/api/gi_onco', require('./tier34_gastroenterology_ext_206_gi_oncology_router')); } catch(e) { console.error('gi_onco mount failed', e.message); }
try { app.use('/api/gi_nut', require('./tier34_gastroenterology_ext_207_gi_nutrition_router')); } catch(e) { console.error('gi_nut mount failed', e.message); }
try { app.use('/api/rheum_ra', require('./tier35_rheumatology_ext_208_ra_router')); } catch(e) { console.error('rheum_ra mount failed', e.message); }
try { app.use('/api/rheum_lupus', require('./tier35_rheumatology_ext_209_lupus_router')); } catch(e) { console.error('rheum_lupus mount failed', e.message); }
try { app.use('/api/rheum_vasculitis', require('./tier35_rheumatology_ext_210_vasculitis_router')); } catch(e) { console.error('rheum_vasculitis mount failed', e.message); }
try { app.use('/api/rheum_myo', require('./tier35_rheumatology_ext_211_myositis_router')); } catch(e) { console.error('rheum_myo mount failed', e.message); }
try { app.use('/api/rheum_spine', require('./tier35_rheumatology_ext_212_spine_router')); } catch(e) { console.error('rheum_spine mount failed', e.message); }
try { app.use('/api/infx_hiv', require('./tier36_infectious_disease_ext_213_hiv_router')); } catch(e) { console.error('infx_hiv mount failed', e.message); }
try { app.use('/api/infx_tb', require('./tier36_infectious_disease_ext_214_tb_router')); } catch(e) { console.error('infx_tb mount failed', e.message); }
try { app.use('/api/infx_hepa', require('./tier36_infectious_disease_ext_215_hepatitis_router')); } catch(e) { console.error('infx_hepa mount failed', e.message); }
try { app.use('/api/infx_trop', require('./tier36_infectious_disease_ext_216_tropical_router')); } catch(e) { console.error('infx_trop mount failed', e.message); }
try { app.use('/api/infx_stew', require('./tier36_infectious_disease_ext_217_stewardship_router')); } catch(e) { console.error('infx_stew mount failed', e.message); }
try { app.use('/api/neuro_stroke', require('./tier37_neurology_ext_218_stroke_router')); } catch(e) { console.error('neuro_stroke mount failed', e.message); }
try { app.use('/api/neuro_epi', require('./tier37_neurology_ext_219_epilepsy_router')); } catch(e) { console.error('neuro_epi mount failed', e.message); }
try { app.use('/api/neuro_ms', require('./tier37_neurology_ext_220_ms_router')); } catch(e) { console.error('neuro_ms mount failed', e.message); }
try { app.use('/api/neuro_mov', require('./tier37_neurology_ext_221_movement_router')); } catch(e) { console.error('neuro_mov mount failed', e.message); }
try { app.use('/api/neuro_nm', require('./tier37_neurology_ext_222_neuro_musc_router')); } catch(e) { console.error('neuro_nm mount failed', e.message); }
try { app.use('/api/derm_psor', require('./tier38_dermatology_ext_223_psoriasis_router')); } catch(e) { console.error('derm_psor mount failed', e.message); }
try { app.use('/api/derm_ecz', require('./tier38_dermatology_ext_224_eczema_router')); } catch(e) { console.error('derm_ecz mount failed', e.message); }
try { app.use('/api/derm_skin', require('./tier38_dermatology_ext_225_skin_cancer_router')); } catch(e) { console.error('derm_skin mount failed', e.message); }
try { app.use('/api/derm_acne', require('./tier38_dermatology_ext_226_acne_router')); } catch(e) { console.error('derm_acne mount failed', e.message); }
try { app.use('/api/derm_hair', require('./tier38_dermatology_ext_227_hair_nails_router')); } catch(e) { console.error('derm_hair mount failed', e.message); }
try { app.use('/api/ent_oto', require('./tier39_ent_ext_228_otology_router')); } catch(e) { console.error('ent_oto mount failed', e.message); }
try { app.use('/api/ent_rhino', require('./tier39_ent_ext_229_rhinology_router')); } catch(e) { console.error('ent_rhino mount failed', e.message); }
try { app.use('/api/ent_laryn', require('./tier39_ent_ext_230_laryngology_router')); } catch(e) { console.error('ent_laryn mount failed', e.message); }
try { app.use('/api/ent_hn', require('./tier39_ent_ext_231_head_neck_router')); } catch(e) { console.error('ent_hn mount failed', e.message); }
try { app.use('/api/ent_ped', require('./tier39_ent_ext_232_ped_ent_router')); } catch(e) { console.error('ent_ped mount failed', e.message); }
try { app.use('/api/ophth_glaucoma', require('./tier40_ophthalmology_ext_233_glaucoma_router')); } catch(e) { console.error('ophth_glaucoma mount failed', e.message); }
try { app.use('/api/ophth_retina', require('./tier40_ophthalmology_ext_234_retina_router')); } catch(e) { console.error('ophth_retina mount failed', e.message); }
try { app.use('/api/ophth_cornea', require('./tier40_ophthalmology_ext_235_cornea_router')); } catch(e) { console.error('ophth_cornea mount failed', e.message); }
try { app.use('/api/ophth_plas', require('./tier40_ophthalmology_ext_236_oculoplast_router')); } catch(e) { console.error('ophth_plas mount failed', e.message); }
try { app.use('/api/ophth_no', require('./tier40_ophthalmology_ext_237_neuro_ophth_router')); } catch(e) { console.error('ophth_no mount failed', e.message); }
try { app.use('/api/ob_high_risk', require('./tier41_obstetrics_ext_238_high_risk_router')); } catch(e) { console.error('ob_high_risk mount failed', e.message); }
try { app.use('/api/ob_fetal', require('./tier41_obstetrics_ext_239_fetal_mon_router')); } catch(e) { console.error('ob_fetal mount failed', e.message); }
try { app.use('/api/ob_procedures', require('./tier41_obstetrics_ext_240_ob_procedures_router')); } catch(e) { console.error('ob_procedures mount failed', e.message); }
try { app.use('/api/ob_postpartum', require('./tier41_obstetrics_ext_241_postpartum_router')); } catch(e) { console.error('ob_postpartum mount failed', e.message); }
try { app.use('/api/ob_lactation', require('./tier41_obstetrics_ext_242_lactation_router')); } catch(e) { console.error('ob_lactation mount failed', e.message); }
try { app.use('/api/psych_mood', require('./tier42_psychiatry_ext_243_mood_anx_router')); } catch(e) { console.error('psych_mood mount failed', e.message); }
try { app.use('/api/psych_psychotic', require('./tier42_psychiatry_ext_244_psychotic_router')); } catch(e) { console.error('psych_psychotic mount failed', e.message); }
try { app.use('/api/psych_trauma', require('./tier42_psychiatry_ext_245_trauma_router')); } catch(e) { console.error('psych_trauma mount failed', e.message); }
try { app.use('/api/psych_substance', require('./tier42_psychiatry_ext_246_substance_router')); } catch(e) { console.error('psych_substance mount failed', e.message); }
try { app.use('/api/psych_neurodev', require('./tier42_psychiatry_ext_247_neurodev_router')); } catch(e) { console.error('psych_neurodev mount failed', e.message); }
try { app.use('/api/surg_gi', require('./tier43_surgery_ext_248_gi_surg_router')); } catch(e) { console.error('surg_gi mount failed', e.message); }
try { app.use('/api/surg_ortho', require('./tier43_surgery_ext_249_ortho_surg_router')); } catch(e) { console.error('surg_ortho mount failed', e.message); }
try { app.use('/api/surg_vasc', require('./tier43_surgery_ext_250_vascular_router')); } catch(e) { console.error('surg_vasc mount failed', e.message); }
try { app.use('/api/surg_trauma', require('./tier43_surgery_ext_251_trauma_router')); } catch(e) { console.error('surg_trauma mount failed', e.message); }
try { app.use('/api/surg_transplant', require('./tier43_surgery_ext_252_transplant_router')); } catch(e) { console.error('surg_transplant mount failed', e.message); }
try { app.use('/api/ped_resp', require('./tier44_pediatrics_ext_253_ped_resp_router')); } catch(e) { console.error('ped_resp mount failed', e.message); }
try { app.use('/api/ped_neonat', require('./tier44_pediatrics_ext_254_ped_neonat_router')); } catch(e) { console.error('ped_neonat mount failed', e.message); }
try { app.use('/api/ped_gastro', require('./tier44_pediatrics_ext_255_ped_gastro_router')); } catch(e) { console.error('ped_gastro mount failed', e.message); }
try { app.use('/api/ped_endo', require('./tier44_pediatrics_ext_256_ped_endo_router')); } catch(e) { console.error('ped_endo mount failed', e.message); }
try { app.use('/api/ped_immuno', require('./tier44_pediatrics_ext_257_ped_immuno_router')); } catch(e) { console.error('ped_immuno mount failed', e.message); }
try { app.use('/api/icu_vent', require('./tier45_icu_ext_258_icu_vent_router')); } catch(e) { console.error('icu_vent mount failed', e.message); }
try { app.use('/api/icu_sepsis', require('./tier45_icu_ext_259_icu_sepsis_router')); } catch(e) { console.error('icu_sepsis mount failed', e.message); }
try { app.use('/api/icu_hemodyn', require('./tier45_icu_ext_260_icu_hemodyn_router')); } catch(e) { console.error('icu_hemodyn mount failed', e.message); }
try { app.use('/api/icu_neuro', require('./tier45_icu_ext_261_icu_neuro_router')); } catch(e) { console.error('icu_neuro mount failed', e.message); }
try { app.use('/api/icu_renal', require('./tier45_icu_ext_262_icu_renal_router')); } catch(e) { console.error('icu_renal mount failed', e.message); }
try { app.use('/api/pharm_onco', require('./tier46_pharmacy_ext_263_pharm_onco_router')); } catch(e) { console.error('pharm_onco mount failed', e.message); }
try { app.use('/api/pharm_antinf', require('./tier46_pharmacy_ext_264_pharm_antinf_router')); } catch(e) { console.error('pharm_antinf mount failed', e.message); }
try { app.use('/api/pharm_chronic', require('./tier46_pharmacy_ext_265_pharm_chronic_router')); } catch(e) { console.error('pharm_chronic mount failed', e.message); }
try { app.use('/api/pharm_pain', require('./tier46_pharmacy_ext_266_pharm_pain_router')); } catch(e) { console.error('pharm_pain mount failed', e.message); }
try { app.use('/api/pharm_special', require('./tier46_pharmacy_ext_267_pharm_special_router')); } catch(e) { console.error('pharm_special mount failed', e.message); }
try { app.use('/api/rad_body', require('./tier47_radiology_ext_268_rad_body_router')); } catch(e) { console.error('rad_body mount failed', e.message); }
try { app.use('/api/rad_neuro', require('./tier47_radiology_ext_269_rad_neuro_router')); } catch(e) { console.error('rad_neuro mount failed', e.message); }
try { app.use('/api/rad_cardio', require('./tier47_radiology_ext_270_rad_cardio_router')); } catch(e) { console.error('rad_cardio mount failed', e.message); }
try { app.use('/api/rad_gu_gi', require('./tier47_radiology_ext_271_rad_gu_gi_router')); } catch(e) { console.error('rad_gu_gi mount failed', e.message); }
try { app.use('/api/rad_interv', require('./tier47_radiology_ext_272_rad_interv_router')); } catch(e) { console.error('rad_interv mount failed', e.message); }
try { app.use('/api/lab_heme', require('./tier48_laboratory_ext_273_lab_heme_router')); } catch(e) { console.error('lab_heme mount failed', e.message); }
try { app.use('/api/lab_chem', require('./tier48_laboratory_ext_274_lab_chem_router')); } catch(e) { console.error('lab_chem mount failed', e.message); }
try { app.use('/api/lab_micro', require('./tier48_laboratory_ext_275_lab_micro_router')); } catch(e) { console.error('lab_micro mount failed', e.message); }
try { app.use('/api/lab_immuno', require('./tier48_laboratory_ext_276_lab_immuno_router')); } catch(e) { console.error('lab_immuno mount failed', e.message); }
try { app.use('/api/lab_mol', require('./tier48_laboratory_ext_277_lab_mol_router')); } catch(e) { console.error('lab_mol mount failed', e.message); }
try { app.use('/api/nurs_assess', require('./tier49_nursing_ext_278_nurs_assess_router')); } catch(e) { console.error('nurs_assess mount failed', e.message); }
try { app.use('/api/nurs_med', require('./tier49_nursing_ext_279_nurs_med_router')); } catch(e) { console.error('nurs_med mount failed', e.message); }
try { app.use('/api/nurs_wound', require('./tier49_nursing_ext_280_nurs_wound_router')); } catch(e) { console.error('nurs_wound mount failed', e.message); }
try { app.use('/api/nurs_resp', require('./tier49_nursing_ext_281_nurs_resp_router')); } catch(e) { console.error('nurs_resp mount failed', e.message); }
try { app.use('/api/nurs_safety', require('./tier49_nursing_ext_282_nurs_safety_router')); } catch(e) { console.error('nurs_safety mount failed', e.message); }
try { app.use('/api/card_failure', require('./tier50_cardiology_ext_283_card_failure_router')); } catch(e) { console.error('card_failure mount failed', e.message); }
try { app.use('/api/card_arr', require('./tier50_cardiology_ext_284_card_arr_router')); } catch(e) { console.error('card_arr mount failed', e.message); }
try { app.use('/api/card_valve', require('./tier50_cardiology_ext_285_card_valve_router')); } catch(e) { console.error('card_valve mount failed', e.message); }
try { app.use('/api/card_ischemic', require('./tier50_cardiology_ext_286_card_ischemic_router')); } catch(e) { console.error('card_ischemic mount failed', e.message); }
try { app.use('/api/card_cong', require('./tier50_cardiology_ext_287_card_cong_router')); } catch(e) { console.error('card_cong mount failed', e.message); }
try { app.use('/api/derm_infla', require('./tier51_dermatology_ext_288_derm_infla_router')); } catch(e) { console.error('derm_infla mount failed', e.message); }
try { app.use('/api/derm_inf', require('./tier51_dermatology_ext_289_derm_inf_router')); } catch(e) { console.error('derm_inf mount failed', e.message); }
try { app.use('/api/derm_neo', require('./tier51_dermatology_ext_290_derm_neo_router')); } catch(e) { console.error('derm_neo mount failed', e.message); }
try { app.use('/api/derm_pig', require('./tier51_dermatology_ext_291_derm_pig_router')); } catch(e) { console.error('derm_pig mount failed', e.message); }
try { app.use('/api/derm_proced', require('./tier51_dermatology_ext_292_derm_proced_router')); } catch(e) { console.error('derm_proced mount failed', e.message); }
try { app.use('/api/rehab_pt', require('./tier52_rehabilitation_ext_293_rehab_pt_router')); } catch(e) { console.error('rehab_pt mount failed', e.message); }
try { app.use('/api/rehab_ot', require('./tier52_rehabilitation_ext_294_rehab_ot_router')); } catch(e) { console.error('rehab_ot mount failed', e.message); }
try { app.use('/api/rehab_slp', require('./tier52_rehabilitation_ext_295_rehab_slp_router')); } catch(e) { console.error('rehab_slp mount failed', e.message); }
try { app.use('/api/rehab_prosth', require('./tier52_rehabilitation_ext_296_rehab_prosth_router')); } catch(e) { console.error('rehab_prosth mount failed', e.message); }
try { app.use('/api/rehab_pain', require('./tier52_rehabilitation_ext_297_rehab_pain_router')); } catch(e) { console.error('rehab_pain mount failed', e.message); }
try { app.use('/api/onc_breast', require('./tier53_oncology_ext_298_onc_breast_router')); } catch(e) { console.error('onc_breast mount failed', e.message); }
try { app.use('/api/onc_lung', require('./tier53_oncology_ext_299_onc_lung_router')); } catch(e) { console.error('onc_lung mount failed', e.message); }
try { app.use('/api/onc_gi', require('./tier53_oncology_ext_300_onc_gi_router')); } catch(e) { console.error('onc_gi mount failed', e.message); }
try { app.use('/api/onc_gu', require('./tier53_oncology_ext_301_onc_gu_router')); } catch(e) { console.error('onc_gu mount failed', e.message); }
try { app.use('/api/onc_heme', require('./tier53_oncology_ext_302_onc_heme_router')); } catch(e) { console.error('onc_heme mount failed', e.message); }
try { app.use('/api/er_trauma', require('./tier54_emergency_ext_303_er_trauma_router')); } catch(e) { console.error('er_trauma mount failed', e.message); }
try { app.use('/api/er_cardio', require('./tier54_emergency_ext_304_er_cardio_router')); } catch(e) { console.error('er_cardio mount failed', e.message); }
try { app.use('/api/er_neuro', require('./tier54_emergency_ext_305_er_neuro_router')); } catch(e) { console.error('er_neuro mount failed', e.message); }
try { app.use('/api/er_resp', require('./tier54_emergency_ext_306_er_resp_router')); } catch(e) { console.error('er_resp mount failed', e.message); }
try { app.use('/api/er_gi_gi', require('./tier54_emergency_ext_307_er_gi_gi_router')); } catch(e) { console.error('er_gi_gi mount failed', e.message); }
try { app.use('/api/triage_acu', require('./tier55_triage_ext_308_triage_acu_router')); } catch(e) { console.error('triage_acu mount failed', e.message); }
try { app.use('/api/triage_intake', require('./tier55_triage_ext_309_triage_intake_router')); } catch(e) { console.error('triage_intake mount failed', e.message); }
try { app.use('/api/triage_screen', require('./tier55_triage_ext_310_triage_screen_router')); } catch(e) { console.error('triage_screen mount failed', e.message); }
try { app.use('/api/triage_ped', require('./tier55_triage_ext_311_triage_ped_router')); } catch(e) { console.error('triage_ped mount failed', e.message); }
try { app.use('/api/triage_disp', require('./tier55_triage_ext_312_triage_disp_router')); } catch(e) { console.error('triage_disp mount failed', e.message); }
try { app.use('/api/surg_neuro', require('./tier56_surgical_specialties_313_surg_neuro_router')); } catch(e) { console.error('surg_neuro mount failed', e.message); }
try { app.use('/api/surg_plastic', require('./tier56_surgical_specialties_314_surg_plastic_router')); } catch(e) { console.error('surg_plastic mount failed', e.message); }
try { app.use('/api/surg_urology', require('./tier56_surgical_specialties_315_surg_urology_router')); } catch(e) { console.error('surg_urology mount failed', e.message); }
try { app.use('/api/surg_ent_surg', require('./tier56_surgical_specialties_316_surg_ent_surg_router')); } catch(e) { console.error('surg_ent_surg mount failed', e.message); }
try { app.use('/api/surg_thoracic', require('./tier56_surgical_specialties_317_surg_thoracic_router')); } catch(e) { console.error('surg_thoracic mount failed', e.message); }
try { app.use('/api/img_advanced', require('./tier57_imaging_ext_318_img_advanced_router')); } catch(e) { console.error('img_advanced mount failed', e.message); }
try { app.use('/api/img_us_ext', require('./tier57_imaging_ext_319_img_us_ext_router')); } catch(e) { console.error('img_us_ext mount failed', e.message); }
try { app.use('/api/img_breast', require('./tier57_imaging_ext_320_img_breast_router')); } catch(e) { console.error('img_breast mount failed', e.message); }
try { app.use('/api/img_msk', require('./tier57_imaging_ext_321_img_msk_router')); } catch(e) { console.error('img_msk mount failed', e.message); }
try { app.use('/api/img_emergent', require('./tier57_imaging_ext_322_img_emergent_router')); } catch(e) { console.error('img_emergent mount failed', e.message); }
try { app.use('/api/res_trial', require('./tier58_research_ext_323_res_trial_router')); } catch(e) { console.error('res_trial mount failed', e.message); }
try { app.use('/api/res_pub', require('./tier58_research_ext_324_res_pub_router')); } catch(e) { console.error('res_pub mount failed', e.message); }
try { app.use('/api/res_grant', require('./tier58_research_ext_325_res_grant_router')); } catch(e) { console.error('res_grant mount failed', e.message); }
try { app.use('/api/res_data', require('./tier58_research_ext_326_res_data_router')); } catch(e) { console.error('res_data mount failed', e.message); }
try { app.use('/api/res_ethics', require('./tier58_research_ext_327_res_ethics_router')); } catch(e) { console.error('res_ethics mount failed', e.message); }
try { app.use('/api/tele_visit', require('./tier59_telemedicine_328_tele_visit_router')); } catch(e) { console.error('tele_visit mount failed', e.message); }
try { app.use('/api/tele_monitor', require('./tier59_telemedicine_329_tele_monitor_router')); } catch(e) { console.error('tele_monitor mount failed', e.message); }
try { app.use('/api/tele_surg', require('./tier59_telemedicine_330_tele_surg_router')); } catch(e) { console.error('tele_surg mount failed', e.message); }
try { app.use('/api/tele_psy', require('./tier59_telemedicine_331_tele_psy_router')); } catch(e) { console.error('tele_psy mount failed', e.message); }
try { app.use('/api/tele_admin', require('./tier59_telemedicine_332_tele_admin_router')); } catch(e) { console.error('tele_admin mount failed', e.message); }
try { app.use('/api/ai_clin_dec', require('./tier60_ai_brain_ext_333_ai_clin_dec_router')); } catch(e) { console.error('ai_clin_dec mount failed', e.message); }
try { app.use('/api/ai_diag_img', require('./tier60_ai_brain_ext_334_ai_diag_img_router')); } catch(e) { console.error('ai_diag_img mount failed', e.message); }
try { app.use('/api/ai_nlp_doc', require('./tier60_ai_brain_ext_335_ai_nlp_doc_router')); } catch(e) { console.error('ai_nlp_doc mount failed', e.message); }
try { app.use('/api/ai_forecast', require('./tier60_ai_brain_ext_336_ai_forecast_router')); } catch(e) { console.error('ai_forecast mount failed', e.message); }
try { app.use('/api/ai_chatbot', require('./tier60_ai_brain_ext_337_ai_chatbot_router')); } catch(e) { console.error('ai_chatbot mount failed', e.message); }
try { app.use('/api/ops_facility', require('./tier61_ops_ext_338_ops_facility_router')); } catch(e) { console.error('ops_facility mount failed', e.message); }
try { app.use('/api/ops_assets', require('./tier61_ops_ext_339_ops_assets_router')); } catch(e) { console.error('ops_assets mount failed', e.message); }
try { app.use('/api/ops_vendor', require('./tier61_ops_ext_340_ops_vendor_router')); } catch(e) { console.error('ops_vendor mount failed', e.message); }
try { app.use('/api/ops_legal', require('./tier61_ops_ext_341_ops_legal_router')); } catch(e) { console.error('ops_legal mount failed', e.message); }
try { app.use('/api/ops_quality', require('./tier61_ops_ext_342_ops_quality_router')); } catch(e) { console.error('ops_quality mount failed', e.message); }
try { app.use('/api/sp_geri', require('./tier62_spec_care_ext_343_sp_geri_router')); } catch(e) { console.error('sp_geri mount failed', e.message); }
try { app.use('/api/sp_pall', require('./tier62_spec_care_ext_344_sp_pall_router')); } catch(e) { console.error('sp_pall mount failed', e.message); }
try { app.use('/api/sp_home', require('./tier62_spec_care_ext_345_sp_home_router')); } catch(e) { console.error('sp_home mount failed', e.message); }
try { app.use('/api/sp_rehab', require('./tier62_spec_care_ext_346_sp_rehab_router')); } catch(e) { console.error('sp_rehab mount failed', e.message); }
try { app.use('/api/sp_mat', require('./tier62_spec_care_ext_347_sp_mat_router')); } catch(e) { console.error('sp_mat mount failed', e.message); }
try { app.use('/api/px_satis', require('./tier63_px_348_px_satis_router')); } catch(e) { console.error('px_satis mount failed', e.message); }
try { app.use('/api/px_engage', require('./tier63_px_349_px_engage_router')); } catch(e) { console.error('px_engage mount failed', e.message); }
try { app.use('/api/px_access', require('./tier63_px_350_px_access_router')); } catch(e) { console.error('px_access mount failed', e.message); }
try { app.use('/api/px_feedback', require('./tier63_px_351_px_feedback_router')); } catch(e) { console.error('px_feedback mount failed', e.message); }
try { app.use('/api/px_journey', require('./tier63_px_352_px_journey_router')); } catch(e) { console.error('px_journey mount failed', e.message); }
try { app.use('/api/pop_registries', require('./tier64_pop_health_348_pop_registries_router')); } catch(e) { console.error('pop_registries mount failed', e.message); }
try { app.use('/api/pop_screen', require('./tier64_pop_health_349_pop_screen_router')); } catch(e) { console.error('pop_screen mount failed', e.message); }
try { app.use('/api/pop_cohort', require('./tier64_pop_health_350_pop_cohort_router')); } catch(e) { console.error('pop_cohort mount failed', e.message); }
try { app.use('/api/pop_outreach', require('./tier64_pop_health_351_pop_outreach_router')); } catch(e) { console.error('pop_outreach mount failed', e.message); }
try { app.use('/api/pop_metrics', require('./tier64_pop_health_352_pop_metrics_router')); } catch(e) { console.error('pop_metrics mount failed', e.message); }
try { app.use('/api/rev_charge', require('./tier65_rev_cycle_353_rev_charge_router')); } catch(e) { console.error('rev_charge mount failed', e.message); }
try { app.use('/api/rev_claim', require('./tier65_rev_cycle_354_rev_claim_router')); } catch(e) { console.error('rev_claim mount failed', e.message); }
try { app.use('/api/rev_payment', require('./tier65_rev_cycle_355_rev_payment_router')); } catch(e) { console.error('rev_payment mount failed', e.message); }
try { app.use('/api/rev_audit', require('./tier65_rev_cycle_356_rev_audit_router')); } catch(e) { console.error('rev_audit mount failed', e.message); }
try { app.use('/api/rev_contract', require('./tier65_rev_cycle_357_rev_contract_router')); } catch(e) { console.error('rev_contract mount failed', e.message); }
try { app.use('/api/lab_specimen', require('./tier66_lab_diag_358_lab_specimen_router')); } catch(e) { console.error('lab_specimen mount failed', e.message); }
try { app.use('/api/lab_result', require('./tier66_lab_diag_359_lab_result_router')); } catch(e) { console.error('lab_result mount failed', e.message); }
try { app.use('/api/lab_micro', require('./tier66_lab_diag_360_lab_micro_router')); } catch(e) { console.error('lab_micro mount failed', e.message); }
try { app.use('/api/lab_path', require('./tier66_lab_diag_361_lab_path_router')); } catch(e) { console.error('lab_path mount failed', e.message); }
try { app.use('/api/lab_qc', require('./tier66_lab_diag_362_lab_qc_router')); } catch(e) { console.error('lab_qc mount failed', e.message); }
try { app.use('/api/surg_pre_admit', require('./tier67_surg_periop_363_surg_pre_admit_router')); } catch(e) { console.error('surg_pre_admit mount failed', e.message); }
try { app.use('/api/surg_intraop', require('./tier67_surg_periop_364_surg_intraop_router')); } catch(e) { console.error('surg_intraop mount failed', e.message); }
try { app.use('/api/surg_postop', require('./tier67_surg_periop_365_surg_postop_router')); } catch(e) { console.error('surg_postop mount failed', e.message); }
try { app.use('/api/surg_complications', require('./tier67_surg_periop_366_surg_complications_router')); } catch(e) { console.error('surg_complications mount failed', e.message); }
try { app.use('/api/surg_quality', require('./tier67_surg_periop_367_surg_quality_router')); } catch(e) { console.error('surg_quality mount failed', e.message); }
try { app.use('/api/rx_clinical', require('./tier68_rx_368_rx_clinical_router')); } catch(e) { console.error('rx_clinical mount failed', e.message); }
try { app.use('/api/rx_oncology', require('./tier68_rx_369_rx_oncology_router')); } catch(e) { console.error('rx_oncology mount failed', e.message); }
try { app.use('/api/rx_specialty', require('./tier68_rx_370_rx_specialty_router')); } catch(e) { console.error('rx_specialty mount failed', e.message); }
try { app.use('/api/rx_clinical_pharm', require('./tier68_rx_371_rx_clinical_pharm_router')); } catch(e) { console.error('rx_clinical_pharm mount failed', e.message); }
try { app.use('/api/rx_informatics', require('./tier68_rx_372_rx_informatics_router')); } catch(e) { console.error('rx_informatics mount failed', e.message); }
try { app.use('/api/mh_assess', require('./tier69_mh_373_mh_assess_router')); } catch(e) { console.error('mh_assess mount failed', e.message); }
try { app.use('/api/mh_therapy', require('./tier69_mh_374_mh_therapy_router')); } catch(e) { console.error('mh_therapy mount failed', e.message); }
try { app.use('/api/mh_psychopharm', require('./tier69_mh_375_mh_psychopharm_router')); } catch(e) { console.error('mh_psychopharm mount failed', e.message); }
try { app.use('/api/mh_addiction', require('./tier69_mh_376_mh_addiction_router')); } catch(e) { console.error('mh_addiction mount failed', e.message); }
try { app.use('/api/mh_community', require('./tier69_mh_377_mh_community_router')); } catch(e) { console.error('mh_community mount failed', e.message); }
try { app.use('/api/img_proc', require('./tier70_img_diag_378_img_proc_router')); } catch(e) { console.error('img_proc mount failed', e.message); }
try { app.use('/api/img_interp', require('./tier70_img_diag_379_img_interp_router')); } catch(e) { console.error('img_interp mount failed', e.message); }
try { app.use('/api/img_admin', require('./tier70_img_diag_380_img_admin_router')); } catch(e) { console.error('img_admin mount failed', e.message); }
try { app.use('/api/img_specialty', require('./tier70_img_diag_381_img_specialty_router')); } catch(e) { console.error('img_specialty mount failed', e.message); }
try { app.use('/api/img_safety', require('./tier70_img_diag_382_img_safety_router')); } catch(e) { console.error('img_safety mount failed', e.message); }
try { app.use('/api/nut_assess', require('./tier71_nut_383_nut_assess_router')); } catch(e) { console.error('nut_assess mount failed', e.message); }
try { app.use('/api/nut_intervention', require('./tier71_nut_384_nut_intervention_router')); } catch(e) { console.error('nut_intervention mount failed', e.message); }
try { app.use('/api/nut_clinical', require('./tier71_nut_385_nut_clinical_router')); } catch(e) { console.error('nut_clinical mount failed', e.message); }
try { app.use('/api/nut_pediatric', require('./tier71_nut_386_nut_pediatric_router')); } catch(e) { console.error('nut_pediatric mount failed', e.message); }
try { app.use('/api/nut_admin', require('./tier71_nut_387_nut_admin_router')); } catch(e) { console.error('nut_admin mount failed', e.message); }
try { app.use('/api/er_triage', require('./tier72_er_388_er_triage_router')); } catch(e) { console.error('er_triage mount failed', e.message); }
try { app.use('/api/er_resus', require('./tier72_er_389_er_resus_router')); } catch(e) { console.error('er_resus mount failed', e.message); }
try { app.use('/api/er_medic', require('./tier72_er_390_er_medic_router')); } catch(e) { console.error('er_medic mount failed', e.message); }
try { app.use('/api/er_trauma', require('./tier72_er_391_er_trauma_router')); } catch(e) { console.error('er_trauma mount failed', e.message); }
try { app.use('/api/er_dispos', require('./tier72_er_392_er_dispos_router')); } catch(e) { console.error('er_dispos mount failed', e.message); }
try { app.use('/api/cardio_ext_ep', require('./tier73_cardio_ext_383_cardio_ep_router')); } catch(e) { console.error('cardio_ext_ep mount failed', e.message); }
try { app.use('/api/cardio_ext_imaging', require('./tier73_cardio_ext_384_cardio_imaging_router')); } catch(e) { console.error('cardio_ext_imaging mount failed', e.message); }
try { app.use('/api/cardio_ext_chf', require('./tier73_cardio_ext_385_cardio_chf_router')); } catch(e) { console.error('cardio_ext_chf mount failed', e.message); }
try { app.use('/api/cardio_ext_rehab', require('./tier73_cardio_ext_386_cardio_rehab_router')); } catch(e) { console.error('cardio_ext_rehab mount failed', e.message); }
try { app.use('/api/cardio_ext_prevention', require('./tier73_cardio_ext_387_cardio_prevention_router')); } catch(e) { console.error('cardio_ext_prevention mount failed', e.message); }
try { app.use('/api/onc_ext_treat', require('./tier74_onc_ext_393_onc_ext_treat_router')); } catch(e) { console.error('onc_ext_treat mount failed', e.message); }
try { app.use('/api/onc_ext_followup', require('./tier74_onc_ext_394_onc_ext_followup_router')); } catch(e) { console.error('onc_ext_followup mount failed', e.message); }
try { app.use('/api/onc_ext_special', require('./tier74_onc_ext_395_onc_ext_special_router')); } catch(e) { console.error('onc_ext_special mount failed', e.message); }
try { app.use('/api/onc_ext_symptom', require('./tier74_onc_ext_396_onc_ext_symptom_router')); } catch(e) { console.error('onc_ext_symptom mount failed', e.message); }
try { app.use('/api/onc_ext_support', require('./tier74_onc_ext_397_onc_ext_support_router')); } catch(e) { console.error('onc_ext_support mount failed', e.message); }
try { app.use('/api/pulm_assess', require('./tier75_pulm_ext_398_pulm_assess_router')); } catch(e) { console.error('pulm_assess mount failed', e.message); }
try { app.use('/api/pulm_disease', require('./tier75_pulm_ext_399_pulm_disease_router')); } catch(e) { console.error('pulm_disease mount failed', e.message); }
try { app.use('/api/pulm_proc', require('./tier75_pulm_ext_400_pulm_proc_router')); } catch(e) { console.error('pulm_proc mount failed', e.message); }
try { app.use('/api/pulm_special', require('./tier75_pulm_ext_401_pulm_special_router')); } catch(e) { console.error('pulm_special mount failed', e.message); }
try { app.use('/api/pulm_icu', require('./tier75_pulm_ext_402_pulm_icu_router')); } catch(e) { console.error('pulm_icu mount failed', e.message); }
try { app.use('/api/endo_diabetes_v2', require('./tier76_endo_ext_403_endo_diabetes_router')); } catch(e) { console.error('endo_diabetes_v2 mount failed', e.message); }
try { app.use('/api/endo_thyroid_v2', require('./tier76_endo_ext_404_endo_thyroid_router')); } catch(e) { console.error('endo_thyroid_v2 mount failed', e.message); }
try { app.use('/api/endo_adrenal_v2', require('./tier76_endo_ext_405_endo_adrenal_router')); } catch(e) { console.error('endo_adrenal_v2 mount failed', e.message); }
try { app.use('/api/endo_pituitary_v2', require('./tier76_endo_ext_406_endo_pituitary_router')); } catch(e) { console.error('endo_pituitary_v2 mount failed', e.message); }
try { app.use('/api/endo_special_v2', require('./tier76_endo_ext_407_endo_special_router')); } catch(e) { console.error('endo_special_v2 mount failed', e.message); }
try { app.use('/api/neuro_stroke_v2', require('./tier77_neuro_ext_408_neuro_stroke_router')); } catch(e) { console.error('neuro_stroke_v2 mount failed', e.message); }
try { app.use('/api/neuro_epilepsy_v2', require('./tier77_neuro_ext_409_neuro_epilepsy_router')); } catch(e) { console.error('neuro_epilepsy_v2 mount failed', e.message); }
try { app.use('/api/neuro_movement_v2', require('./tier77_neuro_ext_410_neuro_movement_router')); } catch(e) { console.error('neuro_movement_v2 mount failed', e.message); }
try { app.use('/api/neuro_neuromuscular_v2', require('./tier77_neuro_ext_411_neuro_neuromuscular_router')); } catch(e) { console.error('neuro_neuromuscular_v2 mount failed', e.message); }
try { app.use('/api/neuro_headache_v2', require('./tier77_neuro_ext_412_neuro_headache_router')); } catch(e) { console.error('neuro_headache_v2 mount failed', e.message); }
try { app.use('/api/ortho_trauma_v2', require('./tier78_ortho_ext_413_ortho_trauma_router')); } catch(e) { console.error('ortho_trauma_v2 mount failed', e.message); }
try { app.use('/api/ortho_joint_v2', require('./tier78_ortho_ext_414_ortho_joint_router')); } catch(e) { console.error('ortho_joint_v2 mount failed', e.message); }
try { app.use('/api/ortho_spine_v2', require('./tier78_ortho_ext_415_ortho_spine_router')); } catch(e) { console.error('ortho_spine_v2 mount failed', e.message); }
try { app.use('/api/ortho_sports_v2', require('./tier78_ortho_ext_416_ortho_sports_router')); } catch(e) { console.error('ortho_sports_v2 mount failed', e.message); }
try { app.use('/api/ortho_pediatric_v2', require('./tier78_ortho_ext_417_ortho_pediatric_router')); } catch(e) { console.error('ortho_pediatric_v2 mount failed', e.message); }
try { app.use('/api/ophth_general_v2', require('./tier79_ophth_ext_418_ophth_general_router')); } catch(e) { console.error('ophth_general_v2 mount failed', e.message); }
try { app.use('/api/ophth_retina_v2', require('./tier79_ophth_ext_419_ophth_retina_router')); } catch(e) { console.error('ophth_retina_v2 mount failed', e.message); }
try { app.use('/api/ophth_cataract_v2', require('./tier79_ophth_ext_420_ophth_cataract_router')); } catch(e) { console.error('ophth_cataract_v2 mount failed', e.message); }
try { app.use('/api/ophth_glaucoma_v2', require('./tier79_ophth_ext_421_ophth_glaucoma_router')); } catch(e) { console.error('ophth_glaucoma_v2 mount failed', e.message); }
try { app.use('/api/ophth_pediatric_v2', require('./tier79_ophth_ext_422_ophth_pediatric_router')); } catch(e) { console.error('ophth_pediatric_v2 mount failed', e.message); }
try { app.use('/api/ent_general_v2', require('./tier80_ent_ext_423_ent_general_router')); } catch(e) { console.error('ent_general_v2 mount failed', e.message); }
try { app.use('/api/ent_sinus_v2', require('./tier80_ent_ext_424_ent_sinus_router')); } catch(e) { console.error('ent_sinus_v2 mount failed', e.message); }
try { app.use('/api/ent_throat_v2', require('./tier80_ent_ext_425_ent_throat_router')); } catch(e) { console.error('ent_throat_v2 mount failed', e.message); }
try { app.use('/api/ent_head_neck_v2', require('./tier80_ent_ext_426_ent_head_neck_router')); } catch(e) { console.error('ent_head_neck_v2 mount failed', e.message); }
try { app.use('/api/ent_pediatric_v2', require('./tier80_ent_ext_427_ent_pediatric_router')); } catch(e) { console.error('ent_pediatric_v2 mount failed', e.message); }
try { app.use('/api/uro_general_v2', require('./tier81_uro_ext_428_uro_general_router')); } catch(e) { console.error('uro_general_v2 mount failed', e.message); }
try { app.use('/api/uro_renal_v2', require('./tier81_uro_ext_429_uro_renal_router')); } catch(e) { console.error('uro_renal_v2 mount failed', e.message); }
try { app.use('/api/uro_onco_v2', require('./tier81_uro_ext_430_uro_onco_router')); } catch(e) { console.error('uro_onco_v2 mount failed', e.message); }
try { app.use('/api/uro_peds_v2', require('./tier81_uro_ext_431_uro_peds_router')); } catch(e) { console.error('uro_peds_v2 mount failed', e.message); }
try { app.use('/api/uro_andrology_v2', require('./tier81_uro_ext_432_uro_andrology_router')); } catch(e) { console.error('uro_andrology_v2 mount failed', e.message); }
try { app.use('/api/obgyn_antenatal_v2', require('./tier82_obgyn_ext_433_obgyn_antenatal_router')); } catch(e) { console.error('obgyn_antenatal_v2 mount failed', e.message); }
try { app.use('/api/obgyn_gyne_v2', require('./tier82_obgyn_ext_434_obgyn_gyne_router')); } catch(e) { console.error('obgyn_gyne_v2 mount failed', e.message); }
try { app.use('/api/obgyn_onc_v2', require('./tier82_obgyn_ext_435_obgyn_onc_router')); } catch(e) { console.error('obgyn_onc_v2 mount failed', e.message); }
try { app.use('/api/obgyn_labor_v2', require('./tier82_obgyn_ext_436_obgyn_labor_router')); } catch(e) { console.error('obgyn_labor_v2 mount failed', e.message); }
try { app.use('/api/obgyn_repro_v2', require('./tier82_obgyn_ext_437_obgyn_repro_router')); } catch(e) { console.error('obgyn_repro_v2 mount failed', e.message); }
try { app.use('/api/derm_general_v2', require('./tier83_derm_ext_438_derm_general_router')); } catch(e) { console.error('derm_general_v2 mount failed', e.message); }
try { app.use('/api/derm_onc_v2', require('./tier83_derm_ext_439_derm_onc_router')); } catch(e) { console.error('derm_onc_v2 mount failed', e.message); }
try { app.use('/api/derm_immuno_v2', require('./tier83_derm_ext_440_derm_immuno_router')); } catch(e) { console.error('derm_immuno_v2 mount failed', e.message); }
try { app.use('/api/derm_cosmetic_v2', require('./tier83_derm_ext_441_derm_cosmetic_router')); } catch(e) { console.error('derm_cosmetic_v2 mount failed', e.message); }
try { app.use('/api/derm_peds_v2', require('./tier83_derm_ext_442_derm_peds_router')); } catch(e) { console.error('derm_peds_v2 mount failed', e.message); }
try { app.use('/api/psych_general_v2', require('./tier84_psych_ext_443_psych_general_router')); } catch(e) { console.error('psych_general_v2 mount failed', e.message); }
try { app.use('/api/psych_anxiety_v2', require('./tier84_psych_ext_444_psych_anxiety_router')); } catch(e) { console.error('psych_anxiety_v2 mount failed', e.message); }
try { app.use('/api/psych_mood_v2', require('./tier84_psych_ext_445_psych_mood_router')); } catch(e) { console.error('psych_mood_v2 mount failed', e.message); }
try { app.use('/api/psych_sud_v2', require('./tier84_psych_ext_446_psych_sud_router')); } catch(e) { console.error('psych_sud_v2 mount failed', e.message); }
try { app.use('/api/psych_emerg_v2', require('./tier84_psych_ext_447_psych_emerg_router')); } catch(e) { console.error('psych_emerg_v2 mount failed', e.message); }
try { app.use('/api/pain_acute_v2', require('./tier85_pain_ext_448_pain_acute_router')); } catch(e) { console.error('pain_acute_v2 mount failed', e.message); }
try { app.use('/api/pain_chronic_v2', require('./tier85_pain_ext_449_pain_chronic_router')); } catch(e) { console.error('pain_chronic_v2 mount failed', e.message); }
try { app.use('/api/pain_procedures_v2', require('./tier85_pain_ext_450_pain_procedures_router')); } catch(e) { console.error('pain_procedures_v2 mount failed', e.message); }
try { app.use('/api/pain_rehab_v2', require('./tier85_pain_ext_451_pain_rehab_router')); } catch(e) { console.error('pain_rehab_v2 mount failed', e.message); }
try { app.use('/api/pain_specialty_v2', require('./tier85_pain_ext_452_pain_specialty_router')); } catch(e) { console.error('pain_specialty_v2 mount failed', e.message); }
try { app.use('/api/card_heart_failure_v2', require('./tier86_card_ext_453_card_heart_failure_router')); } catch(e) { console.error('card_heart_failure_v2 mount failed', e.message); }
try { app.use('/api/card_intervention_v2', require('./tier86_card_ext_454_card_intervention_router')); } catch(e) { console.error('card_intervention_v2 mount failed', e.message); }
try { app.use('/api/card_imaging_v2', require('./tier86_card_ext_455_card_imaging_router')); } catch(e) { console.error('card_imaging_v2 mount failed', e.message); }
try { app.use('/api/card_rehab_v2', require('./tier86_card_ext_456_card_rehab_router')); } catch(e) { console.error('card_rehab_v2 mount failed', e.message); }
try { app.use('/api/card_arrhythmia_v2', require('./tier86_card_ext_457_card_arrhythmia_router')); } catch(e) { console.error('card_arrhythmia_v2 mount failed', e.message); }
try { app.use('/api/neph_general_v2', require('./tier87_neph_ext_458_neph_general_router')); } catch(e) { console.error('neph_general_v2 mount failed', e.message); }
try { app.use('/api/neph_dialysis_v2', require('./tier87_neph_ext_459_neph_dialysis_router')); } catch(e) { console.error('neph_dialysis_v2 mount failed', e.message); }
try { app.use('/api/neph_nephrology_v2', require('./tier87_neph_ext_460_neph_nephrology_router')); } catch(e) { console.error('neph_nephrology_v2 mount failed', e.message); }
try { app.use('/api/neph_geri_v2', require('./tier87_neph_ext_461_neph_geri_router')); } catch(e) { console.error('neph_geri_v2 mount failed', e.message); }
try { app.use('/api/neph_advanced_v2', require('./tier87_neph_ext_462_neph_advanced_router')); } catch(e) { console.error('neph_advanced_v2 mount failed', e.message); }
try { app.use('/api/id_general_v2', require('./tier88_id_general_463_router')); } catch(e) { console.error('id_general_v2 mount failed', e.message); }
try { app.use('/api/id_syndromes_v2', require('./tier88_id_syndromes_464_router')); } catch(e) { console.error('id_syndromes_v2 mount failed', e.message); }
try { app.use('/api/gi_luminal_v2', require('./tier88_gi_luminal_465_router')); } catch(e) { console.error('gi_luminal_v2 mount failed', e.message); }
try { app.use('/api/gi_liver_v2', require('./tier88_gi_liver_466_router')); } catch(e) { console.error('gi_liver_v2 mount failed', e.message); }
try { app.use('/api/id_specialty_v2', require('./tier88_id_specialty_467_router')); } catch(e) { console.error('id_specialty_v2 mount failed', e.message); }
try { app.use('/api/oncology_chemo_v2', require('./tier89_oncology_chemo_468_router')); } catch(e) { console.error('oncology_chemo_v2 mount failed', e.message); }
try { app.use('/api/oncology_radiation_v2', require('./tier89_oncology_radiation_469_router')); } catch(e) { console.error('oncology_radiation_v2 mount failed', e.message); }
try { app.use('/api/hematology_benign_v2', require('./tier89_hematology_benign_470_router')); } catch(e) { console.error('hematology_benign_v2 mount failed', e.message); }
try { app.use('/api/oncology_support_v2', require('./tier89_oncology_support_471_router')); } catch(e) { console.error('oncology_support_v2 mount failed', e.message); }
try { app.use('/api/oncology_survivorship_v2', require('./tier89_oncology_survivorship_472_router')); } catch(e) { console.error('oncology_survivorship_v2 mount failed', e.message); }
try { app.use('/api/genetics_cancer_v2', require('./tier90_genetics_cancer_473_router')); } catch(e) { console.error('genetics_cancer_v2 mount failed', e.message); }
try { app.use('/api/genetics_rare_v2', require('./tier90_genetics_rare_474_router')); } catch(e) { console.error('genetics_rare_v2 mount failed', e.message); }
try { app.use('/api/genetics_adult_v2', require('./tier90_genetics_adult_475_router')); } catch(e) { console.error('genetics_adult_v2 mount failed', e.message); }
try { app.use('/api/genetics_counseling_v2', require('./tier90_genetics_counseling_476_router')); } catch(e) { console.error('genetics_counseling_v2 mount failed', e.message); }
try { app.use('/api/genetics_lab_v2', require('./tier90_genetics_lab_477_router')); } catch(e) { console.error('genetics_lab_v2 mount failed', e.message); }
try { app.use('/api/geriatric_assessment_v2', require('./tier91_geriatric_assessment_478_router')); } catch(e) { console.error('geriatric_assessment_v2 mount failed', e.message); }
try { app.use('/api/geriatric_falls_v2', require('./tier91_geriatric_falls_479_router')); } catch(e) { console.error('geriatric_falls_v2 mount failed', e.message); }
try { app.use('/api/geriatric_polypharmacy_v2', require('./tier91_geriatric_polypharmacy_480_router')); } catch(e) { console.error('geriatric_polypharmacy_v2 mount failed', e.message); }
try { app.use('/api/geriatric_dementia_v2', require('./tier91_geriatric_dementia_481_router')); } catch(e) { console.error('geriatric_dementia_v2 mount failed', e.message); }
try { app.use('/api/geriatric_palliative_v2', require('./tier91_geriatric_palliative_482_router')); } catch(e) { console.error('geriatric_palliative_v2 mount failed', e.message); }
try { app.use('/api/immunodeficiency_v2', require('./tier92_immunodeficiency_483_router')); } catch(e) { console.error('immunodeficiency_v2 mount failed', e.message); }
try { app.use('/api/allergy_clinical_v2', require('./tier92_allergy_clinical_484_router')); } catch(e) { console.error('allergy_clinical_v2 mount failed', e.message); }
try { app.use('/api/immunology_lab_v2', require('./tier92_immunology_lab_485_router')); } catch(e) { console.error('immunology_lab_v2 mount failed', e.message); }
try { app.use('/api/immunotherapy_v2', require('./tier92_immunotherapy_486_router')); } catch(e) { console.error('immunotherapy_v2 mount failed', e.message); }
try { app.use('/api/autoimmune_v2', require('./tier92_autoimmune_487_router')); } catch(e) { console.error('autoimmune_v2 mount failed', e.message); }
try { app.use('/api/rheumatoid_v2', require('./tier93_rheumatoid_488_router')); } catch(e) { console.error('rheumatoid_v2 mount failed', e.message); }
try { app.use('/api/spondyloarthropathy_v2', require('./tier93_spondyloarthropathy_489_router')); } catch(e) { console.error('spondyloarthropathy_v2 mount failed', e.message); }
try { app.use('/api/crystal_arthritis_v2', require('./tier93_crystal_arthritis_490_router')); } catch(e) { console.error('crystal_arthritis_v2 mount failed', e.message); }
try { app.use('/api/connective_tissue_v2', require('./tier93_connective_tissue_491_router')); } catch(e) { console.error('connective_tissue_v2 mount failed', e.message); }
try { app.use('/api/vasculitis_v2', require('./tier93_vasculitis_492_router')); } catch(e) { console.error('vasculitis_v2 mount failed', e.message); }
try { app.use('/api/pulm_function_v2', require('./tier94_pulm_function_493_router')); } catch(e) { console.error('pulm_function_v2 mount failed', e.message); }
try { app.use('/api/pulm_sleep_v2', require('./tier94_pulm_sleep_494_router')); } catch(e) { console.error('pulm_sleep_v2 mount failed', e.message); }
try { app.use('/api/pulm_interstitial_v2', require('./tier94_pulm_interstitial_495_router')); } catch(e) { console.error('pulm_interstitial_v2 mount failed', e.message); }
try { app.use('/api/pulm_vascular_v2', require('./tier94_pulm_vascular_496_router')); } catch(e) { console.error('pulm_vascular_v2 mount failed', e.message); }
try { app.use('/api/pulm_pleural_v2', require('./tier94_pulm_pleural_497_router')); } catch(e) { console.error('pulm_pleural_v2 mount failed', e.message); }
try { app.use('/api/hepatology_viral_v2', require('./tier95_hepatology_viral_498_router')); } catch(e) { console.error('hepatology_viral_v2 mount failed', e.message); }
try { app.use('/api/hepatology_cirrhosis_v2', require('./tier95_hepatology_cirrhosis_499_router')); } catch(e) { console.error('hepatology_cirrhosis_v2 mount failed', e.message); }
try { app.use('/api/hepatology_liver_failure_v2', require('./tier95_hepatology_liver_failure_500_router')); } catch(e) { console.error('hepatology_liver_failure_v2 mount failed', e.message); }
try { app.use('/api/hepatology_pediatric_v2', require('./tier95_hepatology_pediatric_501_router')); } catch(e) { console.error('hepatology_pediatric_v2 mount failed', e.message); }
try { app.use('/api/hepatology_metabolic_v2', require('./tier95_hepatology_metabolic_502_router')); } catch(e) { console.error('hepatology_metabolic_v2 mount failed', e.message); }
try { app.use('/api/diabetes_t1dm_v2', require('./tier96_diabetes_t1dm_503_router')); } catch(e) { console.error('diabetes_t1dm_v2 mount failed', e.message); }
try { app.use('/api/diabetes_t2dm_v2', require('./tier96_diabetes_t2dm_504_router')); } catch(e) { console.error('diabetes_t2dm_v2 mount failed', e.message); }
try { app.use('/api/thyroid_extended_v2', require('./tier96_thyroid_extended_505_router')); } catch(e) { console.error('thyroid_extended_v2 mount failed', e.message); }
try { app.use('/api/adrenal_pituitary_v2', require('./tier96_adrenal_pituitary_506_router')); } catch(e) { console.error('adrenal_pituitary_v2 mount failed', e.message); }
try { app.use('/api/bone_metabolic_v2', require('./tier96_bone_metabolic_507_router')); } catch(e) { console.error('bone_metabolic_v2 mount failed', e.message); }
try { app.use('/api/neph_acute_v2', require('./tier97_neph_acute_508_router')); } catch(e) { console.error('neph_acute_v2 mount failed', e.message); }
try { app.use('/api/neph_glomerular_v2', require('./tier97_neph_glomerular_509_router')); } catch(e) { console.error('neph_glomerular_v2 mount failed', e.message); }
try { app.use('/api/neph_vascular_v2', require('./tier97_neph_vascular_510_router')); } catch(e) { console.error('neph_vascular_v2 mount failed', e.message); }
try { app.use('/api/neph_dialysis_v2', require('./tier97_neph_dialysis_511_router')); } catch(e) { console.error('neph_dialysis_v2 mount failed', e.message); }
try { app.use('/api/neph_imaging_v2', require('./tier97_neph_imaging_512_router')); } catch(e) { console.error('neph_imaging_v2 mount failed', e.message); }
try { app.use('/api/cardio_acute_v2', require('./tier98_cardio_acute_513_router')); } catch(e) { console.error('cardio_acute_v2 mount failed', e.message); }
try { app.use('/api/cardio_imaging_v2', require('./tier98_cardio_imaging_514_router')); } catch(e) { console.error('cardio_imaging_v2 mount failed', e.message); }
try { app.use('/api/cardio_intervention_v2', require('./tier98_cardio_intervention_515_router')); } catch(e) { console.error('cardio_intervention_v2 mount failed', e.message); }
try { app.use('/api/cardio_ep_v2', require('./tier98_cardio_electrophysiology_516_router')); } catch(e) { console.error('cardio_ep_v2 mount failed', e.message); }
try { app.use('/api/cardio_valve_v2', require('./tier98_cardio_valve_517_router')); } catch(e) { console.error('cardio_valve_v2 mount failed', e.message); }
try { app.use('/api/icu_extended_v2', require('./tier99_icu_extended_518_router')); } catch(e) { console.error('icu_extended_v2 mount failed', e.message); }
try { app.use('/api/ed_extended_v2', require('./tier99_ed_extended_519_router')); } catch(e) { console.error('ed_extended_v2 mount failed', e.message); }
try { app.use('/api/perioperative_v2', require('./tier99_perioperative_520_router')); } catch(e) { console.error('perioperative_v2 mount failed', e.message); }
try { app.use('/api/rehab_v2', require('./tier99_rehab_521_router')); } catch(e) { console.error('rehab_v2 mount failed', e.message); }
try { app.use('/api/oncology_extended_v2', require('./tier99_oncology_extended_522_router')); } catch(e) { console.error('oncology_extended_v2 mount failed', e.message); }
try { app.use('/api/obgyn_mfm_v2', require('./tier100_obgyn_mfm_523_router')); } catch(e) { console.error('obgyn_mfm_v2 mount failed', e.message); }
try { app.use('/api/obgyn_gyn_onc_v2', require('./tier100_obgyn_gyn_onc_524_router')); } catch(e) { console.error('obgyn_gyn_onc_v2 mount failed', e.message); }
try { app.use('/api/obgyn_rei_v2', require('./tier100_obgyn_rei_525_router')); } catch(e) { console.error('obgyn_rei_v2 mount failed', e.message); }
try { app.use('/api/obgyn_menopause_v2', require('./tier100_obgyn_menopause_526_router')); } catch(e) { console.error('obgyn_menopause_v2 mount failed', e.message); }
try { app.use('/api/obgyn_reproductive_v2', require('./tier100_obgyn_reproductive_527_router')); } catch(e) { console.error('obgyn_reproductive_v2 mount failed', e.message); }
`;
const newC = c.slice(0, idx) + mounts + '\n' + c.slice(idx);
fs.writeFileSync('server.js', newC);
console.log('Inserted', mounts.split('\n').length, 'mounts. New file size:', newC.length);
