#!/bin/bash
HOST="http://127.0.0.1:3000"
PASS=0; FAIL=0
run() {
  local url="$1"; local body="$2"; local name="$3"
  local code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$HOST$url" -H 'Content-Type: application/json' -d "$body")
  if [ "$code" = "200" ]; then echo "  PASS $name ($code)"; PASS=$((PASS+1));
  else echo "  FAIL $name ($code)"; FAIL=$((FAIL+1)); fi
}
echo "=== 101 ECG ==="
run "/api/car_ecg/rhy" '{"heart_rate":75,"regular":true,"p_wave":true,"pr_interval":160,"qrs_follows":true,"pvc_present":false,"pac_present":false}' "rhy"
run "/api/car_ecg/int" '{"pr_interval":160,"qrs_duration":90,"qtc_interval":400,"rr_interval":"normal","p_axis":50,"qrs_axis":60,"t_axis":40}' "int"
run "/api/car_ecg/st" '{"lead":"v2","st_elevation_mm":0,"st_depression_mm":0,"t_inversion":false,"symmetrical_t":false,"reciprocal_changes":false}' "st"
run "/api/car_ecg/q" '{"q_duration":0.02,"q_depth":1,"pathological":false,"reciprocal_q":false,"leads_involved":"none"}' "q"
run "/api/car_ecg/ax" '{"p_axis":50,"qrs_axis":60,"t_axis":40,"left_axia_dev":false,"right_axis_dev":false,"indeterminate":false}' "ax"
run "/api/car_ecg/bbb" '{"rabbit_ears":false,"wide_qrs":false,"lead_with_pattern":"none","lbbb_criteria":false,"rbbb_criteria":false,"fascicular_block":false}' "bbb"
echo "=== 102 STRESS ==="
run "/api/car_stress/ind" '{"indication":"chest_pain","likely_to_change":true,"baseline_ecg_normal":true,"can_exercise":true}' "ind"
run "/api/car_stress/con" '{"acute_mi":false,"unstable_angina":false,"severe_aortic_stenosis":false,"uncontrolled_htn":false,"decompensated_hf":false,"recent_pe":false}' "con"
run "/api/car_stress/pro" '{"protocol":"bruce","max_hr_achieved":true,"target_hr":150,"achieved_hr":145,"test_adequate":true}' "pro"
run "/api/car_stress/res" '{"st_changes":false,"st_depression_max":0,"chest_pain":false,"ekg_changes":false,"hypotension":false,"arrhythmia":false}' "res"
run "/api/car_stress/rec" '{"recovery_minutes":5,"symptoms_resolved":true,"ekg_normalized":true,"hr_normalized":true,"bp_stable":true}' "rec"
run "/api/car_stress/comp" '{"shock":false,"lvf":false,"heart_block":false,"afib_onset":false,"cardiac_arrest":false}' "comp"
echo "=== 103 ECHO ==="
run "/api/car_echo/ind" '{"indication":"hf","application_appropriate":true,"alternative_imaging":false}' "ind"
run "/api/car_echo/tte" '{"lvef":55,"lvesd":35,"lvedd":50,"pasp":25,"regional_wma":false,"mild_valvular":true,"severe_valvular":false}' "tte"
run "/api/car_echo/tee" '{"laa_clot":false,"valvular_vegetation":false,"aortic_dissection":false,"endocarditis":false,"laa_closure":false,"fasting_status":true}' "tee"
run "/api/car_echo/fn" '{"lvef":55,"mapse":12,"tdi_septal":9,"tdi_lateral":11,"global_hypokinesis":false,"regional_wma":false}' "fn"
run "/api/car_echo/val" '{"av_area":2.5,"mv_area":3.0,"severe_as":false,"severe_mr":false,"severe_ar":false,"severe_tr":false}' "val"
run "/api/car_echo/peri" '{"effusion_size":5,"tamponade":false,"constriction":false,"right_dysfunction":false,"respiratory_variation":false,"ivc_plethora":false}' "peri"
echo "=== 104 HF ==="
run "/api/car_hf/dx" '{"dyspnea":true,"fatigue":true,"elevated_jvp":true,"rales":true,"s3_gallop":false,"edema":false,"echo_confirmed":true,"ntprobnp_elevated":true}' "dx"
run "/api/car_hf/ph" '{"lvef":40,"phenotype":"hfmidrange","echocardiographic_documented":true,"cardiac_mri":false,"amyloid_screened":false}' "ph"
run "/api/car_hf/gd" '{"acei_or_arni":true,"beta_blocker":true,"mra":true,"sglt2i":true,"dose_optimized":true,"documented":true}' "gd"
run "/api/car_hf/de" '{"dyspnea_increase":true,"weight_gain":true,"weight_change_lb":6,"edema_increase":true,"orthopnea":false,"pnd":false}' "de"
run "/api/car_hf/adv" '{"lvad_evaluated":false,"heart_transplant_evaluated":false,"crt_indicated":false,"advanced_referred":false,"palliative_consult":true}' "adv"
run "/api/car_hf/mon" '{"daily_weights":true,"diet_sodium_compliant":true,"fluid_intake_compliant":true,"medication_adherence":true,"symptom_recognition":true,"zone_protocol":true}' "mon"
echo "=== 105 ACS ==="
run "/api/car_acs/pres" '{"chest_pain_score":8,"troponin":0.06,"st_elevation":false,"st_depression":true,"t_inversion":true,"diaphoresis":true,"dyspnea":true}' "pres"
run "/api/car_acs/fm" '{"mona":true,"oxygen":true,"nitrates":true,"aspirin":true,"iv_access":true,"time_to_ecg":8}' "fm"
run "/api/car_acs/act" '{"cath_team_activated":true,"angiography_planned":true,"door_to_balloon":65,"fibrinolysis":false,"icu_team_informed":true}' "act"
run "/api/car_acs/pci" '{"dapt_initiated":true,"statin_initiated":true,"beta_blocker":true,"acei_initiated":true,"revascularization_complete":true}' "pci"
run "/api/car_acs/comp" '{"cardiogenic_shock":false,"heart_block":false,"vfib":false,"free_wall_rupture":false,"reinfarction":false}' "comp"
run "/api/car_acs/rehab" '{"rehab_referred":true,"rehab_education":true,"lifestyle_counseling":true,"medication_adherence":true,"smoking_cessation":true}' "rehab"
echo "=== 106 ARR ==="
run "/api/car_arr/af" '{"heart_rate":125,"irregular":true,"symptomatic":false,"cha2ds2_vasc":3,"has_bled":1,"anticoagulation_initiated":true}' "af"
run "/api/car_arr/afl" '{"cavotricuspid_dependent":true,"left_atrial":false,"ablation_planned":true,"anticoagulated":true,"rate_controlled":true}' "afl"
run "/api/car_arr/svt" '{"type":"avnrt","hemodynamic_stable":true,"vagal_maneuver_tried":true,"adenosine_given":true,"ablation_planned":false}' "svt"
run "/api/car_arr/vt" '{"vt_known":true,"stable":true,"shock_able":true,"ablation_done":false,"icd_placed":true,"amiodarone_used":true}' "vt"
run "/api/car_arr/bra" '{"type":"sinus","symptomatic":false,"atropine_given":false,"pacing_needed":false,"medications_reversed":true}' "bra"
run "/api/car_arr/abl" '{"ep_consulted":true,"pre_procedure_imaging":true,"anticoagulation_status":true,"consent_obtained":true,"success_outcome":true}' "abl"
echo ""
echo "PASS=$PASS FAIL=$FAIL"