#!/bin/bash
HOST="http://127.0.0.1:3000"
PASS=0; FAIL=0
run() {
  local url="$1"; local body="$2"; local name="$3"
  local code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$HOST$url" -H 'Content-Type: application/json' -d "$body")
  if [ "$code" = "200" ]; then echo "  PASS $name ($code)"; PASS=$((PASS+1));
  else echo "  FAIL $name ($code) :: $body"; FAIL=$((FAIL+1)); fi
}
echo "=== 101 GEN ==="
run "/api/dr_gn/les" '{"type":"nevus","abcde":"benign","biopsy_needed":false,"patient_concern":false}' "les"
run "/api/dr_gn/rash" '{"morphology":"macular","distribution":true,"acute":true,"systemic":false,"mucosal":false}' "rash"
run "/api/dr_gn/prur" '{"generalized":true,"localized":false,"night_bothers":false,"skin_changes":false,"workup":true,"treatment":true}' "prur"
run "/api/dr_gn/alg" '{"contact":true,"urticaria":false,"anaphylaxis":false,"testing":true,"avoidance":true,"immunotherapy":false}' "alg"
run "/api/dr_gn/psor" '{"bsa":5,"severity":true,"topical":true,"phototherapy":false,"systemic":false,"biological":false}' "psor"
run "/api/dr_gn/ai" '{"type":"pemphigus","skin_biopsy":true,"immunofluorescence":true,"serology":true,"systemic":true,"steroid_started":true}' "ai"
echo "=== 102 INF ==="
run "/api/dr_inf/cell" '{"severity":"moderate","systemic":false,"borders":true,"marks":false,"antibiotics":true,"culture":true}' "cell"
run "/api/dr_inf/abs" '{"fluctuant":true,"drainage":true,"culture":true,"antibiotics":true,"systemic":false,"recurrent":false}' "abs"
run "/api/dr_inf/fun" '{"type":"tinea_pedis","koh":true,"culture":false,"topical":true,"oral":false,"response":true}' "fun"
run "/api/dr_inf/vir" '{"type":"zoster","diagnosed":true,"acyclovir":true,"pain_management":true,"referral":false,"eye_involvement":false}' "vir"
run "/api/dr_inf/par" '{"type":"scabies","diagnosed":true,"contacts":true,"treatment":true,"environment":true,"followup":true}' "par"
run "/api/dr_inf/wou" '{"type":"surgical","clean":true,"documented":true,"improving":true,"infection":false,"healing":true}' "wou"
echo "=== 103 ACNE ==="
run "/api/dr_ac/cls" '{"type":"papular","severity":false,"count":10,"scarring":false,"face_trunk":true}' "cls"
run "/api/dr_ac/top" '{"retinoid":true,"benzoyl":true,"antibiotic":true,"salicylic":false,"combination":true,"irritation":false}' "top"
run "/api/dr_ac/sys" '{"type":"oral_antibiotic","contraindicated":false,"ipledge":false,"birth_control":true,"labs":true,"responded":true}' "sys"
run "/api/dr_ac/scar" '{"type":"rolling","laser":false,"subcision":false,"fillers":false,"tca_cross":false}' "scar"
run "/api/dr_ac/ros" '{"type":"papulopustular","triggers_identified":true,"antibiotic":false,"ivermectin":true,"brimonidine":false}' "ros"
run "/api/dr_ac/mon" '{"improvement":true,"adverse":false,"adherent":true,"mood":true,"photos":true,"followup":true}' "mon"
echo "=== 104 ECZEMA ==="
run "/api/dr_ec/cls" '{"type":"atopic","bsa":10,"severity":"moderate","skin_type":true}' "cls"
run "/api/dr_ec/top" '{"moisturizer":true,"cream":true,"steroid":true,"tci":false,"crisaborole":false,"responded":true}' "top"
run "/api/dr_ec/sys" '{"phototherapy":false,"methotrexate":false,"cyclosporine":false,"azathioprine":false,"dupilumab":false,"responded":true}' "sys"
run "/api/dr_ec/trig" '{"identified":true,"allergen_test":true,"avoidance":true,"documented":true,"diary":false}' "trig"
run "/api/dr_ec/inf" '{"type":"bacterial","culture":true,"antibiotics":true,"hospitalized":false,"improvement":true}' "inf"
run "/api/dr_ec/ped" '{"age_months":24,"food_allergy":false,"elimination":false,"counseling":true,"caregiver_burden":false,"sleep":true}' "ped"
echo "=== 105 MELANOMA ==="
run "/api/dr_ml/biop" '{"method":"excisional","full_thickness":true,"margin":true,"lesion_oriented":true,"sent_to_path":true}' "biop"
run "/api/dr_ml/path" '{"type":"thin","breslow":0.5,"clark":2,"mitoses":1,"ulceration":false,"regression":false}' "path"
run "/api/dr_ml/st" '{"t":"t1a","n":"n0","m":"m0","sln_done":true,"imaging":true}' "st"
run "/api/dr_ml/surg" '{"wle_margin":1.0,"sln_done":true,"sln_positive":false,"completion":false,"complications":false,"flap":false}' "surg"
run "/api/dr_ml/sys" '{"adjuvant":false,"drug":"none","braf_tested":true,"adverse":false,"responded":true}' "sys"
run "/api/dr_ml/fu" '{"months":6,"recurrence":false,"skin_exam":true,"imaging":true,"lymph_nodes":true,"family_screening":true}' "fu"
echo "=== 106 COSM ==="
run "/api/dr_cs/bot" '{"area":"glabellar","units":20,"allergies_reviewed":true,"consent":true,"photograph":true}' "bot"
run "/api/dr_cs/fill" '{"product":"ha","area":"lip","test_patch":true,"consent":true,"symmetrical":true}' "fill"
run "/api/dr_cs/las" '{"type":"non_ablative","skin_type_assessed":true,"test_spot":true,"eye_protection":true,"complications":false}' "las"
run "/api/dr_cs/pe" '{"type":"glycolic","skin_type":true,"patch_test":true,"sunscreen":true,"discomfort":false}' "pe"
run "/api/dr_cs/comp" '{"bruising":false,"swelling":false,"asymmetry":false,"vascular_occlusion":false,"skin_necrosis":false,"managed":true}' "comp"
run "/api/dr_cs/fu" '{"satisfaction":true,"followup_scheduled":true,"maintenance":true,"photos":true,"next_session":true}' "fu"
echo ""
echo "PASS=$PASS FAIL=$FAIL"