#!/bin/bash
HOST="http://127.0.0.1:3000"
PASS=0; FAIL=0
run() {
  local url="$1"; local body="$2"; local name="$3"
  local code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$HOST$url" -H 'Content-Type: application/json' -d "$body")
  if [ "$code" = "200" ]; then echo "  PASS $name ($code)"; PASS=$((PASS+1));
  else echo "  FAIL $name ($code) :: $body"; FAIL=$((FAIL+1)); fi
}
echo "=== 101 RHINO ==="
run "/api/en_rh/sin" '{"type":"acute_bact","duration_days":5,"imaging":false,"intranasal_meds":false,"antibiotics":false}' "sin"
run "/api/en_rh/alg" '{"seasonal":true,"perennial":false,"medication":false,"food":false,"testing_done":false,"immunotherapy":false}' "alg"
run "/api/en_rh/obst" '{"cause":"septal_deviation","imaging":true,"medical_therapy":false,"surgery_planned":false}' "obst"
run "/api/en_rh/pol" '{"stage":"2","symptomatic":true,"steroid_treated":true,"surgery_planned":false,"respond_to_steroid":true}' "pol"
run "/api/en_rh/epi" '{"severity":"mild","anterior_source":true,"posterior_source":false,"coagulopathy":false,"controlled":true,"packing":false}' "epi"
run "/api/en_rh/fn" '{"smell_loss":false,"sniffin_score":30,"taste_loss":false,"workup":false,"recovery":true,"smell_training":false}' "fn"
echo "=== 102 LARYN ==="
run "/api/en_la/dys" '{"duration_days":14,"type":"functional","stroboscopy":false,"therapy":false,"improvement":false}' "dys"
run "/api/en_la/par" '{"side":"left","cause":"surgical","imaging":false,"speech_therapy":false,"surgery_planned":false}' "par"
run "/api/en_la/nod" '{"singer":true,"teacher":false,"reflux_treated":false,"voice_therapy":false,"surgery_planned":false}' "nod"
run "/api/en_la/ref" '{"typical":true,"atypical":false,"ppi_trial":true,"impedance":false,"responded":true,"egj_dysfunction":false}' "ref"
run "/api/en_la/ca" '{"site":"glottic","stage":"i","mdt_reviewed":true,"consent":true,"treatment_started":true}' "ca"
run "/api/en_la/sten" '{"location":"subglottic","grade":1,"cause":"intubation","dilation":false,"tracheostomy":false}' "sten"
echo "=== 103 OTOLOGY ==="
run "/api/en_ot/ha" '{"pta_od":35,"pta_os":35,"ear":"both","candidate":true,"fitted":true,"benefit":true}' "ha"
run "/api/en_ot/om" '{"type":"acute","bilateral":false,"tubes_needed":false,"antibiotics":true,"fluid_persistent":false}' "om"
run "/api/en_ot/oe" '{"type":"bacterial","immunocompromised":false,"culture":true,"drops_started":true,"imaging":false}' "oe"
run "/api/en_ot/chol" '{"suspected":false,"otoscopy_done":true,"ears_present":false,"ct_done":false,"surgery_planned":false,"fu_scheduled":false}' "chol"
run "/api/en_ot/tin" '{"type":"subjective","workup":true,"cause_found":false,"therapy_offered":true,"distressing":false}' "tin"
run "/api/en_ot/coc" '{"candidate":true,"workup":true,"imaging_done":true,"surgery_done":true,"activated":true,"rehab":true}' "coc"
echo "=== 104 TONSIL ==="
run "/api/en_tn/strep" '{"criteria":"centor_1","strep_test":false,"antibiotics":false,"complications":false}' "strep"
run "/api/en_tn/hyp" '{"events_per_year":3,"ahi":2,"sleep_apnea":false,"weight_issue":false,"surgery_planned":false}' "hyp"
run "/api/en_tn/adn" '{"age_months":48,"nasal_obstruction":true,"serous_otitis":false,"sleep_apnea":false,"surgery_planned":false}' "adn"
run "/api/en_tn/quins" '{"suspected":false,"imaging":false,"iv_antibiotics":false,"drainage":false,"airway_compromised":false}' "quins"
run "/api/en_tn/osa" '{"ahi":15,"symptomatic":true,"cpap_attempted":true,"surgery_planned":false,"weight_loss":false,"position_therapy":false}' "osa"
run "/api/en_tn/po" '{"postop_days":7,"bleeding":false,"controlled":true,"diet":true,"hydration":true,"followup":true}' "po"
echo "=== 105 HEADNECK ==="
run "/api/en_hn/mass" '{"size_cm":2,"location":"thyroid","imaging":true,"fna_done":true,"documented":true}' "mass"
run "/api/en_hn/st" '{"t":"t2","n":"n1","m":"m0","imaging_done":true,"mdt":true}' "st"
run "/api/en_hn/surg" '{"type":"primary","clear_margins":true,"complications":false,"floss":true,"path":true}' "surg"
run "/api/en_hn/rc" '{"indicated":false,"regimen":"none","mucositis":false,"neutropenia":false,"weight_loss":false}' "rc"
run "/api/en_hn/thy" '{"cytology":"bethesda_4","lobectomy_planned":false,"total_planned":false,"calcium":true,"voice":true}' "thy"
run "/api/en_hn/fu" '{"months":6,"recurrence":false,"imaging_planned":true,"qol":true,"swallowing":true,"speech":true}' "fu"
echo "=== 106 SALIV ==="
run "/api/en_sl/sal" '{"condition":"sialolith","imaging":true,"fna_done":false,"surgery_planned":false}' "sal"
run "/api/en_sl/tra" '{"fx_present":false,"location":"none","airway":true,"hemorrhage":false,"imaging":false,"surgery_planned":false}' "tra"
run "/api/en_sl/ner" '{"branch":"frontal","grade":"i","complete":false,"imaging":false,"recovery":true,"followup":true}' "ner"
run "/api/en_sl/sm" '{"anosmia":false,"duration_days":14,"workup":false,"smell_training":false,"improvement":false,"followup":false}' "sm"
run "/api/en_sl/tin" '{"type":"subjective","workup":true,"imaging":false,"cause_found":false,"therapy":false}' "tin"
run "/api/en_sl/oc" '{"condition":"leukoplakia","biopsy":true,"dysplasia":false,"referral":false,"followup":true}' "oc"
echo ""
echo "PASS=$PASS FAIL=$FAIL"