#!/bin/bash
HOST="http://127.0.0.1:3000"
PASS=0; FAIL=0
run() {
  local url="$1"; local body="$2"; local name="$3"
  local code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$HOST$url" -H 'Content-Type: application/json' -d "$body")
  if [ "$code" = "200" ]; then echo "  PASS $name ($code)"; PASS=$((PASS+1));
  else echo "  FAIL $name ($code) :: $body"; FAIL=$((FAIL+1)); fi
}
echo "=== 101 PRE ==="
run "/api/lb_pre/ord" '{"type":"cbc","appropriate":true,"consent":true,"duplicates_checked":true}' "ord"
run "/api/lb_pre/spec" '{"type":"serum","tube":"red","labeled":true,"adequate_volume":true,"hemolyzed":false,"lipemic":false}' "spec"
run "/api/lb_pre/trans" '{"condition":"room","time_to_lab_minutes":30,"timely":true,"cold_chain":true}' "trans"
run "/api/lb_pre/acc" '{"received":true,"centrifuged":true,"aliquoted":true,"stored":true,"critical_value_notified":true}' "acc"
run "/api/lb_pre/rej" '{"reason":"none","redrawn":false,"reordered":false,"notified":true}' "rej"
run "/api/lb_pre/track" '{"tat_minutes":45,"within_tat":true,"escalated":false,"barcode":true,"audit":true}' "track"
echo "=== 102 CHEM ==="
run "/api/lb_ch/an" '{"analyzer":"roche_cobas","throughput_per_hour":300,"calibrated":true,"qc_passed":true}' "an"
run "/api/lb_ch/qc" '{"two_levels":true,"sd_level1":1.0,"sd_level2":1.2,"within_range":true,"trend_reviewed":true,"corrective":false}' "qc"
run "/api/lb_ch/cal" '{"calibrated":true,"last_cal_days":30,"calibration_validators":true,"outcome_match":true,"scheduled":true}' "cal"
run "/api/lb_ch/crit" '{"critical_value":200,"verified":true,"notified":true,"readback":true,"time_to_notify":15,"documented":true}' "crit"
run "/api/lb_ch/delta" '{"previous":100,"current":120,"delta_pct":20,"flag":false,"investigated":false,"explained":true}' "delta"
run "/api/lb_ch/ref" '{"low":3.5,"high":5.0,"age_appropriate":true,"sex_appropriate":true,"flag_outliers":true,"documented":true}' "ref"
echo "=== 103 HEMA ==="
run "/api/lb_he/cbc" '{"hgb":14,"wbc":7,"plt":250,"analyzed":true,"flagged":false,"reviewed":true}' "cbc"
run "/api/lb_he/sm" '{"smear_reviewed":true,"differential_done":true,"abnormal_cells":false,"pathologist_review":false,"released":true}' "sm"
run "/api/lb_he/co" '{"pt":12,"inr":1.0,"ptt":30,"fibrinogen":300,"dvt_workup":false,"anticoag_monitored":true}' "co"
run "/api/lb_he/es" '{"esr_value":15,"unit":"mm_hr","crp_correlated":true,"clinical_relevant":true,"documented":true}' "es"
run "/api/lb_he/bb" '{"type":"crossmatch","ab_id_complete":true,"two_technologists":true,"computer_crossmatch":true,"unit_released":true}' "bb"
run "/api/lb_he/q" '{"calibrated":true,"qc_passed":true,"three_levels":true,"proficiency":true,"documented":true}' "q"
echo "=== 104 MICRO ==="
run "/api/lb_mb/cul" '{"source":"urine","gram_done":true,"incubation_hours":24,"preliminary":true,"final":true}' "cul"
run "/api/lb_mb/id" '{"method":"maldi_tof","id_complete":true,"confidence_high":true,"verified":true}' "id"
run "/api/lb_mb/ast" '{"method":"vitek2","ast_complete":true,"mecA_done":true,"carbapenem_resist":false,"documented":true}' "ast"
run "/api/lb_mb/bc" '{"set_done":true,"set_count":2,"aerobic_bottle":true,"anaerobic_bottle":true,"first_drawn":true,"monitored":true}' "bc"
run "/api/lb_mb/st" '{"gram":true,"acid_fast":false,"fungal":false,"interpretation_done":true,"clinical_correlation":true}' "st"
run "/api/lb_mb/rep" '{"critical_value_called":true,"communicated":true,"interpretive_comment":true,"saved":true,"sent_to_ehr":true}' "rep"
echo "=== 105 MOL ==="
run "/api/lb_ml/pcr" '{"target":"covid","internal_control":true,"amplification":true,"valid_run":true,"reported":true}' "pcr"
run "/api/lb_ml/ngs" '{"platform":"illumina","depth":100,"coverage":95,"qc_passed":true,"aligned":true,"variants_called":true}' "ngs"
run "/api/lb_ml/fish" '{"target":"her2","signal_count":40,"cells_counted":200,"interpreted":true,"documented":true}' "fish"
run "/api/lb_ml/cyto" '{"band_resolution":400,"metaphases_count":20,"karyotyped":true,"abnormalities":false,"documented":true}' "cyto"
run "/api/lb_ml/rep" '{"interp":true,"interpretive":true,"clinically_significant":true,"actionable":true,"tat":true,"documented":true}' "rep"
run "/api/lb_ml/qc" '{"no_template":true,"positive_control":true,"negative_control":true,"amplicon_size":true,"contamination_assay":true}' "qc"
echo "=== 106 PATH ==="
run "/api/lb_pa/gross" '{"specimen":"biopsy","dimensions":3,"photographed":true,"sectioned":true,"cassettes_count":3}' "gross"
run "/api/lb_pa/proc" '{"fixed":true,"processed":true,"embedded":true,"sectioned":true,"stained":true,"coverslipped":true}' "proc"
run "/api/lb_pa/dx" '{"microscopy_done":true,"diagnosis_category":"benign","special_stains":false,"ihc_done":false,"report_signed":true}' "dx"
run "/api/lb_pa/froz" '{"requested":false,"performed":false,"margin_assessed":false,"diagnosed":false,"communicated":false,"concordance":false}' "froz"
run "/api/lb_pa/ihc" '{"stain":"er","positive":true,"negative_control":true,"positive_control":true,"documented":true}' "ihc"
run "/api/lb_pa/q" '{"tat_days":3,"within_tat":true,"proficiency":true,"qc_reviewed":true,"documented":true}' "q"
echo ""
echo "PASS=$PASS FAIL=$FAIL"