#!/bin/bash
HOST="http://127.0.0.1:3000"
PASS=0; FAIL=0
run() {
  local url="$1"; local body="$2"; local name="$3"
  local code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$HOST$url" -H 'Content-Type: application/json' -d "$body")
  if [ "$code" = "200" ]; then echo "  PASS $name ($code)"; PASS=$((PASS+1));
  else echo "  FAIL $name ($code)"; FAIL=$((FAIL+1)); fi
}
echo "=== 101 CKD ==="
run "/api/nep_ckd/st" '{"gfr":45,"kidney_damage":true,"albuminuria":100,"stage":"g3a","dialysis_initiated":false}' "st"
run "/api/nep_ckd/alb" '{"alb_creat_ratio":50,"category":"a2","urine_collected":true,"confirmed":true,"first_morning":true}' "alb"
run "/api/nep_ckd/prog" '{"gfr_slope":-3,"baseline_gfr":60,"current_gfr":45,"rapid_decline":false,"referral_needed":true}' "prog"
run "/api/nep_ckd/bp" '{"sbp":135,"dbp":85,"ace_inhibitor":true,"ARB":false,"diuretic":true,"target_met":true}' "bp"
run "/api/nep_ckd/met" '{"bicarb":22,"potassium":4.5,"phosphate":1.2,"pth":80,"alkali_therapy":false,"phosphate_binder":false}' "met"
run "/api/nep_ckd/an" '{"hgb":10.5,"tsat":25,"esa_initiated":true,"iron_repletion":true,"target_hgb_met":true}' "an"
echo "=== 102 DIALYSIS ==="
run "/api/nep_dial/adq" '{"modality":"hd","urr":72,"kt_v":1.4,"adequate":true,"review_needed":false}' "adq"
run "/api/nep_dial/acc" '{"type":"avf","working":true,"infection_signs":false,"fistula_murmur":true,"dysfunction":false}' "acc"
run "/api/nep_dial/comp" '{"hypotension":false,"cramps":false,"headache":false,"nausea":false,"air_embolism":false,"dialyzer_reaction":false}' "comp"
run "/api/nep_dial/dw" '{"sbp":120,"edema":1,"dry_weight":70,"at_goal":true,"cramping_dialysis":false,"hypotension_dialysis":false}' "dw"
run "/api/nep_dial/peri" '{"cloudy_effluent":false,"abdominal_pain":false,"fever":false,"wbc_effluent":50,"culture_collected":true,"empiric_antibiotics":true}' "peri"
run "/api/nep_dial/pres" '{"duration_hours":4,"frequency_per_week":3,"dialysate_prescription":2,"individualized":true,"reviewed":true}' "pres"
echo "=== 103 AKI ==="
run "/api/nep_aki/st" '{"creatinine":2.5,"baseline_creatinine":1.0,"urine_output_ml_kg_hr":0.5,"stage":"injury","contrast_exposure":false}' "st"
run "/api/nep_aki/et" '{"type":"prerenal","ultrasound_done":false,"fen_ratio":true,"workup_complete":false}' "et"
run "/api/nep_aki/fl" '{"intake_ml":1500,"output_ml":1200,"balance_24h":300,"fluid_overload":false,"responsive":true}' "fl"
run "/api/nep_aki/neph" '{"aminoglycoside":false,"vancomycin":false,"nsaid":false,"contrast":true,"dose_adjusted":true}' "neph"
run "/api/nep_aki/rrt" '{"urgent_indications":false,"refractory_acidosis":false,"refractory_hyperkalemia":false,"fluid_overload_refractory":false,"uremic_complications":false}' "rrt"
run "/api/nep_aki/rec" '{"last_creatinine":1.4,"dialysis_dependent":false,"recovery_started":true,"followup_planned":true}' "rec"
echo "=== 104 GN ==="
run "/api/nep_gn/pres" '{"syndrome":"nephritic","hematuria":true,"dysmorphic_rbc":true,"rbc_casts":true,"proteinuria_24h":1500}' "pres"
run "/api/nep_gn/biop" '{"indication_clear":true,"coagulopathy":false,"uncontrolled_htn":false,"single_kidney":false,"consent":true,"adequate_sample":true}' "biop"
run "/api/nep_gn/immu" '{"induction":"steroids","dose_appropriate":true,"monitoring":true,"side_effects":false,"prophylaxis":true}' "immu"
run "/api/nep_gn/supp" '{"raas_blockade":true,"diuretic":true,"anti_platelet":false,"anti_coag":false,"lipid_control":true,"bp_controlled":true}' "supp"
run "/api/nep_gn/mon" '{"creatinine":1.2,"proteinuria":500,"remission":true,"relapse":false,"followup_scheduled":true}' "mon"
run "/api/nep_gn/tx" '{"referred":true,"workup_complete":false,"live_donor_evaluation":false,"listed":false,"scheduled":false}' "tx"
echo "=== 105 HTN ==="
run "/api/nep_htn/class" '{"sbp":135,"dbp":85,"stage":"stage_1","renovascular_suspected":false}' "class"
run "/api/nep_htn/sec" '{"renal_artery_stenosis":false,"primary_aldosteronism":false,"cushing":false,"pheo":false,"workup_initiated":false}' "sec"
run "/api/nep_htn/tx" '{"lifestyle":true,"ace_inhibitor":true,"ARB":false,"ccb":true,"diuretic":true,"target_met":true}' "tx"
run "/api/nep_htn/elec" '{"sodium":140,"potassium":4.0,"chloride":100,"bicarb":24,"magnesium":2.0,"corrected":true}' "elec"
run "/api/nep_htn/ab" '{"ph":7.4,"pco2":40,"bicarb":24,"anion_gap":12,"disorder":"none"}' "ab"
run "/api/nep_htn/stones" '{"type":"calcium_oxalate","hydration":true,"diet_modified":true,"workup_complete":true,"recurrent":false}' "stones"
echo "=== 106 PED ==="
run "/api/nep_ped/uti" '{"type":"cystitis","febrile":false,"imaging_done":false,"prophylaxis":false,"age_months":36}' "uti"
run "/api/nep_ped/vur" '{"grade":"ii","bilateral":false,"prophylaxis":true,"surgical_referral":false,"followup":true}' "vur"
run "/api/nep_ped/ns" '{"steroid_responsive":true,"steroid_dependent":false,"steroid_resistant":false,"frequent_relapser":false,"biopsy_needed":false,"albumin_infused":false}' "ns"
run "/api/nep_ped/hus" '{"microangiopathic_anemia":false,"schistocytes":false,"thrombocytopenia":false,"renal_impairment":false,"dialysis_needed":false,"plasmapheresis_needed":false}' "hus"
run "/api/nep_ped/gr" '{"height_z":-1.5,"weight_z":-1.0,"growth_failure":false,"nutritional_support":true,"gh_therapy":false}' "gr"
run "/api/nep_ped/tx" '{"referred":false,"workup_complete":false,"live_donor_evaluation":false,"listed":false,"scheduled":false}' "tx"
echo ""
echo "PASS=$PASS FAIL=$FAIL"