#!/bin/bash
HOST="http://127.0.0.1:3000"
PASS=0; FAIL=0
run() {
  local url="$1"; local body="$2"; local name="$3"
  local code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$HOST$url" -H 'Content-Type: application/json' -d "$body")
  if [ "$code" = "200" ]; then echo "  PASS $name ($code)"; PASS=$((PASS+1));
  else echo "  FAIL $name ($code) :: $body"; FAIL=$((FAIL+1)); fi
}
echo "=== 101 REFR ==="
run "/api/op_refr/va" '{"va_od":0.8,"va_os":0.9,"distance":"far","with_correction":true,"pinhole_improvement":false}' "va"
run "/api/op_refr/ref" '{"sphere_od":-2.5,"cylinder_od":-1.0,"axis_od":180,"sphere_os":-3.0,"cylinder_os":-0.5,"axis_os":170,"bva_improved":true}' "ref"
run "/api/op_refr/pre" '{"type":"progressive","work_appropriate":true,"driving_appropriate":true,"cosmetic_acceptable":true}' "pre"
run "/api/op_refr/lv" '{"va_20_200":false,"field_loss":false,"work_impact":false,"adl_impact":false,"aid_referred":false}' "lv"
run "/api/op_refr/ped" '{"age_months":36,"amblyopia_risk":false,"strabismus":false,"fixation_test":true,"referred":false}' "ped"
run "/api/op_refr/ct" '{"first_time":true,"training":true,"complications":false,"followup":true,"tolerating":true}' "ct"
echo "=== 102 RETINA ==="
run "/api/op_ret/amd" '{"type":"wet","drusen":false,"cst":350,"fluid":true,"treatment_eligible":true}' "amd"
run "/api/op_ret/dr" '{"hba1c":8,"severity":"moderate","fluid":false,"laser_done":false,"anti_vegf":false}' "dr"
run "/api/op_ret/rd" '{"symptomatic":true,"type":"rhegmatogenous","macula_on":true,"urgent":true,"surgery_planned":true}' "rd"
run "/api/op_ret/av" '{"drug":"aflibercept","injections_count":5,"successful":true,"interval_extended":true,"complications":false}' "av"
run "/api/op_ret/laser" '{"type":"prp","successful":true,"complications":false,"followup":true}' "laser"
run "/api/op_ret/ppv" '{"indication":true,"type":"25g","successful":true,"complications":false,"position":true}' "ppv"
echo "=== 103 GLAU ==="
run "/api/op_gl/iop" '{"iop":18,"eye":"ou","pachymetry":540,"target_iop":18,"above_target":false}' "iop"
run "/api/op_gl/disc" '{"cdr":0.6,"notching":false,"hemorrhage":false,"rnf_loss":false,"progression":false}' "disc"
run "/api/op_gl/vf" '{"md":-2.5,"psd":1.5,"reliable":true,"progression":false,"oct_correlated":true}' "vf"
run "/api/op_gl/med" '{"prostaglandin":true,"beta_blocker":false,"alpha_agonist":false,"carbonic_anhydrase":false,"compliance":true,"target_met":true}' "med"
run "/api/op_gl/laser" '{"type":"slt","successful":true,"complications":false,"iop_reduced":true}' "laser"
run "/api/op_gl/surg" '{"type":"trabeculectomy","target_pressure":true,"success":true,"complications":false}' "surg"
echo "=== 104 CORNEA ==="
run "/api/op_cor/dx" '{"condition":"keratoconus","clinical":true,"imaging_done":true,"cultures_done":false}' "dx"
run "/api/op_cor/ker" '{"type":"bacterial","contact_user":false,"culture_done":true,"antibiotics_started":true,"followup_scheduled":true}' "ker"
run "/api/op_cor/kera" '{"k_max":52,"thinnest_pach":450,"progression":true,"crosslinking":false,"contact_lens_fitted":false,"transplant_needed":false}' "kera"
run "/api/op_cor/dry" '{"schirmer":10,"tbut":5,"severity":"moderate","artificial_tears":true,"anti_inflammatory":false,"responded":true}' "dry"
run "/api/op_cor/tx" '{"type":"dsaek","successful":true,"rejection":false,"immunosuppression":true,"followup":true}' "tx"
run "/api/op_cor/ref" '{"type":"lasik","screening_done":true,"candidate":true,"successful":true,"complications":false}' "ref"
echo "=== 105 PEDI ==="
run "/api/op_pd/scr" '{"age_months":12,"test":"red_reflex","pass":true,"followup":true,"referred":false}' "scr"
run "/api/op_pd/amb" '{"unilateral":true,"va_difference":3,"patching_compliance":true,"improvement":true,"treatment_success":true,"recurrence":false}' "amb"
run "/api/op_pd/stra" '{"type":"esotropia","prism_diopters":15,"binocular":false,"surgery_needed":true,"surgery_planned":false}' "stra"
run "/api/op_pd/rb" '{"leukocoria":false,"strabismus":false,"family_hx":false,"bilateral":false,"referred":false,"exam_under_anesthesia":false}' "rb"
run "/api/op_pd/cat" '{"diagnosed":false,"bilateral":false,"surgery_planned":false,"timeline":false,"ioL_planned":false,"amblyopia_risk":false}' "cat"
run "/api/op_pd/fu" '{"compliance":true,"glasses_worn":true,"attendance":true,"outcome":true,"followup_scheduled":true}' "fu"
echo "=== 106 OCULO ==="
run "/api/op_oc/lid" '{"condition":"ptosis","visual_axis":false,"surgery_planned":false,"documented":true}' "lid"
run "/api/op_oc/orb" '{"condition":"proptosis","imaging":true,"urgent":false,"consulted":true,"compressive":false}' "orb"
run "/api/op_oc/lac" '{"condition":"nasolacrimal_obstruction","acute_infection":false,"probing_planned":false,"dcr_planned":false,"resolved":false}' "lac"
run "/api/op_oc/pup" '{"defect":"aniscoria","mri_planned":false,"mra_planned":false,"documented":true,"referred":false}' "pup"
run "/api/op_oc/on" '{"painful":true,"va":0.5,"color_vision":true,"mri_done":true,"steroid_given":true,"followup":true}' "on"
run "/api/op_oc/pe" '{"opening_pressure":25,"lp_done":true,"imaging_done":true,"mrv_done":true,"referred":true}' "pe"
echo ""
echo "PASS=$PASS FAIL=$FAIL"