#!/bin/bash
HOST="http://127.0.0.1:3000"
PASS=0; FAIL=0
run() {
  local url="$1"; local body="$2"; local name="$3"
  local code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$HOST$url" -H 'Content-Type: application/json' -d "$body")
  if [ "$code" = "200" ]; then echo "  PASS $name ($code)"; PASS=$((PASS+1));
  else echo "  FAIL $name ($code) :: $body"; FAIL=$((FAIL+1)); fi
}
echo "=== 101 RECON ==="
run "/api/ph_recon/in" '{"med_count":5,"completed":true,"otc_captured":true,"herbal_captured":true,"verified":true}' "in"
run "/api/ph_recon/dis" '{"discrepancy_count":1,"intentional":true,"unintentional":false,"duplicate":false,"interaction":false,"resolved":true}' "dis"
run "/api/ph_recon/tx" '{"method":"electronic","read_back":true,"complete":true,"timed_acknowledged":true}' "tx"
run "/api/ph_recon/trans" '{"transition":"admission","list_updated":true,"patient_education":true,"community_provider":true}' "trans"
run "/api/ph_recon/hr" '{"anticoag":true,"antiplatelet":false,"insulin":false,"opioid":false,"immunosuppressant":false,"chemo":false,"bridging":true}' "hr"
run "/api/ph_recon/fu" '{"scheduled":true,"pharmacist_called":true,"adherence_check":true,"adverse_check":true,"lab_review":true}' "fu"
echo "=== 102 STEWARD ==="
run "/api/ph_stw/ind" '{"drug":"vancomycin","indication":"cellulitis","documented":true,"evidence_based":true,"approved":true}' "ind"
run "/api/ph_stw/cul" '{"cultures_collected":true,"before_antibiotics":true,"results_reviewed":true,"narrowed":true,"escalated":false}' "cul"
run "/api/ph_stw/dose" '{"daily_dose":1000,"dose_adjusted":true,"renal_adjusted":true,"level_drawn":true,"level_in_range":true}' "dose"
run "/api/ph_stw/route" '{"route":"iv","switch_to_po":true,"tolerating_po":true,"eligible":true}' "route"
run "/api/ph_stw/dur" '{"days":5,"evidence_based_duration":true,"reviewed_daily":true,"stop_planned":true,"stopped":true}' "dur"
run "/api/ph_stw/mdr" '{"mdro":false,"organism":"none","contact_precautions":false,"cohort":false,"monitoring":true}' "mdr"
echo "=== 103 INTERACT ==="
run "/api/ph_int/cls" '{"severity":"major","likelihood":true,"evidence":"established","reviewed":true}' "cls"
run "/api/ph_int/pk" '{"affected":"warfarin","type":"metabolism_inhibitor","level_monitoring":true,"dose_adjustment":true}' "pk"
run "/api/ph_int/pd" '{"type":"additive","adversed_documented":false,"synergy_utilized":false,"antagonism_avoided":true}' "pd"
run "/api/ph_int/qt" '{"qt_prolonging_count":1,"ecg_planned":true,"k_replaced":true,"mag_replaced":true,"monitoring_done":true}' "qt"
run "/api/ph_int/alg" '{"allergen":"penicillin","previous_reaction":true,"cross_reactive":true,"substituted":true,"documented":true}' "alg"
run "/api/ph_int/rh" '{"crcl":45,"alt":25,"renal_dose":true,"hepatic_dose":true,"contraindicated":false}' "rh"
echo "=== 104 TOX ==="
run "/api/ph_tox/syn" '{"syndrome":"opiate","vital_signs_reviewed":true,"mental_status":true,"pupils":true,"skin":true}' "syn"
run "/api/ph_tox/exp" '{"route":"oral","time_since":2,"amount":50,"intent":"unintentional","contamination_risk":false}' "exp"
run "/api/ph_tox/anti" '{"antidote_needed":true,"antidote":"naloxone","dosed":true,"response":true}' "anti"
run "/api/ph_tox/lab" '{"cbc":true,"bmp":true,"osmolar_gap":true,"anion_gap":true,"salicylate_level":true,"ethanol_level":true,"drug_screen":true}' "lab"
run "/api/ph_tox/elim" '{"dialysis_consulted":false,"hemodialysis":false,"crrt":false,"continuous":false,"urine_alkalinization":false,"activated_charcoal":true}' "elim"
run "/api/ph_tox/mon" '{"hr":80,"bp":120,"temp":37,"mental_watch":true,"disposition":true,"followup":true}' "mon"
echo "=== 105 PEDS ==="
run "/api/ph_pd/wt" '{"weight_kg":15,"age_months":36,"dose_mg_kg":10,"total_dose":150,"double_checked":true,"clamped":true}' "wt"
run "/api/ph_pd/dev" '{"stage":"school","liver_mature":true,"kidney_mature":true,"gi_motility":true,"gi_absorption":true}' "dev"
run "/api/ph_pd/form" '{"form":"syrup","palatable":true,"administrable":true,"measured_correctly":true,"caregiver_educated":true}' "form"
run "/api/ph_pd/bm" '{"contraindicated":false,"safe":true,"discussed":true,"timing_optimized":true,"monitoring":true}' "bm"
run "/api/ph_pd/neo" '{"postnatal_age":5,"gestational_age":38,"neonatal_dose":true,"excretion_considered":true,"level_drawn":false}' "neo"
run "/api/ph_pd/ol" '{"fda_approved":true,"evidence":true,"consent":true,"safety_reasonable":true,"specialist_input":true}' "ol"
echo "=== 106 ONC ==="
run "/api/ph_onc/em" '{"risk":"moderate","premeds_given":true,"breakthrough":false,"rescue_plan":true,"monitoring":true}' "em"
run "/api/ph_onc/dose" '{"bsa":1.8,"dose_mg":100,"dose_reduced":false,"reduction_documented":true,"consent":true}' "dose"
run "/api/ph_onc/ext" '{"vesicant":"none","iv_assessed":true,"warm_cold":true,"dexrazoxane":false,"extravasation_protocol":true}' "ext"
run "/api/ph_onc/sup" '{"growth_factor":true,"g_csf_appropriate":true,"antiemetic":true,"mouth_care":true,"diet":true}' "sup"
run "/api/ph_onc/tox" '{"neutropenia":false,"febrile_neutropenia":false,"mucositis":false,"hand_foot":false,"neuropathy":false,"managed":true}' "tox"
run "/api/ph_onc/adh" '{"taking":true,"barriers":false,"oral_counseling":true,"call_education":true,"refills_planned":true}' "adh"
echo ""
echo "PASS=$PASS FAIL=$FAIL"