#!/bin/bash
HOST="http://127.0.0.1:3000"
PASS=0; FAIL=0
run() {
  local url="$1"; local body="$2"; local name="$3"
  local code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$HOST$url" -H 'Content-Type: application/json' -d "$body")
  if [ "$code" = "200" ]; then echo "  PASS $name ($code)"; PASS=$((PASS+1));
  else echo "  FAIL $name ($code) :: $body"; FAIL=$((FAIL+1)); fi
}
echo "=== 101 ACUTE ==="
run "/api/pr_ac/assess" '{"pain_score":8,"type":"nociceptive","location":"abdomen","duration_hours":6,"vital_signs":true,"function":true}' "assess"
run "/api/pr_ac/nono" '{"acetaminophen":true,"nsaid":true,"iv_acetaminophen":false,"gabapentin":false,"contraindicated":false,"effective":true}' "nono"
run "/api/pr_ac/op" '{"indicated":true,"daily_mme":30,"short_acting":true,"nausea_meds":true,"bowel_regimen":true,"pain_improved":true,"function_improved":true,"respiratory_depression":false,"sedation":false}' "op"
run "/api/pr_ac/reg" '{"type":"epidural","catheter":true,"sensory_block":true,"motor_block":false,"complications":false,"monitoring":true}' "reg"
run "/api/pr_ac/pca" '{"load":true,"basal":true,"bolus":true,"max_dose":15,"responded":true,"adverse":false}' "pca"
run "/api/pr_ac/trans" '{"po_intolerance":false,"converted":true,"equianalgesic":true,"breakthrough":true,"tolerating":true}' "trans"
echo "=== 102 CHRONIC ==="
run "/api/pr_ch/assess" '{"diagnosis":"back_pain","duration_months":6,"pain_score":6,"biomedical":true,"psychological":true,"social":true}' "assess"
run "/api/pr_ch/nono" '{"nsaid":true,"tylenol":true,"antidepressant":false,"anticonvulsant":true,"topical":true,"effective":true}' "nono"
run "/api/pr_ch/op" '{"daily_mme":40,"pmp_checked":true,"udt_done":true,"function_improved":true,"dependence":false,"consent":true,"agreement":true,"benefit":true,"behavior":false}' "op"
run "/api/pr_ch/np" '{"physical_therapy":true,"psychological_therapy":true,"mindfulness":true,"acupuncture":false,"exercise":true,"responded":true}' "np"
run "/api/pr_ch/risk" '{"ort_tool":true,"risk":"moderate","overdose_education":true,"naloxone_prescribed":true,"monitoring":true,"benefit_risk_assessed":true}' "risk"
run "/api/pr_ch/tap" '{"reduction_pct":10,"comfortable":true,"adjuncts":true,"monitoring":true,"complete":false,"function_improved":true}' "tap"
echo "=== 103 NEUROP ==="
run "/api/pr_np/assess" '{"diagnosis":"diabetic_peripheral","pain_score":6,"allodynia":true,"hyperalgesia":true,"qol_impact":true}' "assess"
run "/api/pr_np/first" '{"gabapentin":true,"pregabalin":false,"duloxetine":false,"tca":false,"responded":true,"side_effects":false}' "first"
run "/api/pr_np/op" '{"indicated":false,"daily_mme":20,"reasonable":true,"function_improved":true,"pain_improved":true,"dependence_risk":false,"consent":true,"pmp_checked":true,"udt_done":true}' "op"
run "/api/pr_np/top" '{"lidocaine":true,"capsaicin":false,"diclofenac":false,"compound":false,"responded":true}' "top"
run "/api/pr_np/proc" '{"nerve_block":false,"sympathetic_block":false,"radiofrequency":false,"spinal_cord_stim":false,"successful":true,"documented":true}' "proc"
run "/api/pr_np/mon" '{"pain_score":5,"function":true,"mood":true,"sleep":true,"adverse":false,"followup":true}' "mon"
echo "=== 104 OT ==="
run "/api/pr_ot/assess" '{"indication":"post_stroke","fim_score":80,"cognitive":true,"motor":true,"sensory":true}' "assess"
run "/api/pr_ot/adl" '{"dressing":true,"bathing":true,"eating":true,"toileting":true,"transfer":true,"independence_improved":true}' "adl"
run "/api/pr_ot/spl" '{"type":"resting","fabricated":true,"fitting":true,"worn":true,"skin_intact":true}' "spl"
run "/api/pr_ot/whl" '{"evaluated":true,"sized":true,"posture":true,"pressure_relief":true,"training":true,"followup":true}' "whl"
run "/api/pr_ot/home" '{"assessed":true,"recommended":true,"installed":true,"accessible":true,"caregiver_educated":true}' "home"
run "/api/pr_ot/prog" '{"sessions":10,"independence":true,"function_improved":true,"satisfaction":true,"discharge_planning":true}' "prog"
echo "=== 105 PT ==="
run "/api/pr_pt/ev" '{"indication":"post_surgical","range_motion":120,"strength":4,"balance":4,"gait":true,"function":true}' "ev"
run "/api/pr_pt/ex" '{"type":"strengthening","frequency":3,"duration":30,"adherent":true,"progressing":true}' "ex"
run "/api/pr_pt/mn" '{"type":"mobilization","indicated":true,"effective":true,"safe":true,"complications":false}' "mn"
run "/api/pr_pt/mod" '{"heat":false,"cold":true,"ultrasound":false,"tens":true,"laser":false,"responded":true}' "mod"
run "/api/pr_pt/home" '{"documented":true,"demonstrated":true,"written":true,"video":false,"followup":true,"adherent":true}' "home"
run "/api/pr_pt/prog" '{"sessions":12,"function_improved":true,"pain_improved":true,"rom_improved":true,"strength_improved":true,"continue_pt":true}' "prog"
echo "=== 106 PED ==="
run "/api/pr_pd/assess" '{"age_months":84,"scale":"faces","score":6,"type":"acute","parent_present":true}' "assess"
run "/api/pr_pd/fam" '{"education":true,"presence":true,"preparation":true,"coping":true,"anxiety_addressed":true}' "fam"
run "/api/pr_pd/non" '{"distraction":true,"imagery":true,"music":true,"cold":false,"heat":false,"massage":false,"responded":true}' "non"
run "/api/pr_pd/ac" '{"sweet_sucrose":false,"swaddling":false,"breastfeeding":false,"analgesic":true,"dose_correct":true,"response":true}' "ac"
run "/api/pr_pd/chr" '{"condition":"juvenile_arthritis","function":true,"school_attendance":true,"multidisciplinary":true,"biopsychosocial":true}' "chr"
run "/api/pr_pd/sch" '{"attendance":true,"peer_support":true,"activity":true,"individualized_plan":true,"staff_education":true,"medication_at_school":false}' "sch"
echo ""
echo "PASS=$PASS FAIL=$FAIL"