'use strict';
const express = require('express');
const router = express.Router();
const { requireAuth, requireTenantScope, requireRole } = require('./mw');
const engine = require('./tier3_int_102_dm_engine');
router.get('/health', (req, res) => res.json({ ok: true, module: 'tier3-int-dm' }));
router.post('/diagnosis', requireAuth, requireTenantScope, requireRole('doctor'), (req, res) => res.json({ ok: true, result: engine.diabetesDiagnosisAndClassification(req.body) }));
router.post('/a1c-target', requireAuth, requireTenantScope, requireRole('doctor'), (req, res) => res.json({ ok: true, result: engine.a1cTargetIndividualization(req.body) }));
router.post('/non-insulin', requireAuth, requireTenantScope, requireRole('doctor'), (req, res) => res.json({ ok: true, result: engine.nonInsulinTherapy(req.body) }));
router.post('/insulin', requireAuth, requireTenantScope, requireRole('doctor'), (req, res) => res.json({ ok: true, result: engine.basalBolusInsulin(req.body) }));
router.post('/hypo', requireAuth, requireTenantScope, requireRole('doctor'), (req, res) => res.json({ ok: true, result: engine.hypoglycemiaManagement(req.body) }));
module.exports = router;