'use strict';
const express = require('express');
const router = express.Router();
const { requireAuth, requireTenantScope, requireRole } = require('./mw');
const engine = require('./tier4_coe_108_peds_engine');
router.get('/health', (req, res) => res.json({ ok: true, module: 'tier4-coe-peds' }));
router.post('/certification', requireAuth, requireTenantScope, requireRole('doctor'), (req, res) => res.json({ ok: true, result: engine.pediatricCOECertification(req.body) }));
router.post('/age-specific', requireAuth, requireTenantScope, requireRole('doctor'), (req, res) => res.json({ ok: true, result: engine.pediatricAgeSpecificCare(req.body) }));
router.post('/medication', requireAuth, requireTenantScope, requireRole('doctor'), (req, res) => res.json({ ok: true, result: engine.pediatricMedicationDosing(req.body) }));
router.post('/family-rounds', requireAuth, requireTenantScope, requireRole('doctor'), (req, res) => res.json({ ok: true, result: engine.familyCenteredRounds(req.body) }));
router.post('/transition', requireAuth, requireTenantScope, requireRole('doctor'), (req, res) => res.json({ ok: true, result: engine.pediatricToAdultTransition(req.body) }));
module.exports = router;