// Auto_generated by gen_p3gw.py -- PCC v3.165.0
"use strict";
const TS = '2026-07-28T11:40:00Z';

function PediatricBrainTumorStagingExt(input) { const score = Math.round((0.4+Number(input.grade||2)*0.1)*100)/100; return { version:'3.165.0', module:'pcc_pediatric_neuro_ext55', function:"PediatricBrainTumorStagingExt", input, score, ts: TS }; }

function PediatricGliomaMolecularExt(input) { const score = Math.round((0.3+Number(input.braf_v600e||0)*0.3)*100)/100; return { version:'3.165.0', module:'pcc_pediatric_neuro_ext55', function:"PediatricGliomaMolecularExt", input, score, ts: TS }; }

function PediatricMedulloblastomaExt(input) { const score = Math.round((0.45+Number(input.subtype_risk||1)*0.15)*100)/100; return { version:'3.165.0', module:'pcc_pediatric_neuro_ext55', function:"PediatricMedulloblastomaExt", input, score, ts: TS }; }

function PediatricEpendymomaExt(input) { const score = Math.round((0.4+Number(input.location_score||2)*0.1)*100)/100; return { version:'3.165.0', module:'pcc_pediatric_neuro_ext55', function:"PediatricEpendymomaExt", input, score, ts: TS }; }

function PediatricATRTClassificationExt(input) { const score = Math.round((0.5+Number(input.age_months||12)*0.01)*100)/100; return { version:'3.165.0', module:'pcc_pediatric_neuro_ext55', function:"PediatricATRTClassificationExt", input, score, ts: TS }; }

function PediatricDNETExt(input) { const score = Math.round((0.3+Number(input.seizure_freq||5)*0.05)*100)/100; return { version:'3.165.0', module:'pcc_pediatric_neuro_ext55', function:"PediatricDNETExt", input, score, ts: TS }; }

function PediatricCraniopharyngiomaExt(input) { const score = Math.round((0.4+Number(input.cyst_volume||10)*0.03)*100)/100; return { version:'3.165.0', module:'pcc_pediatric_neuro_ext55', function:"PediatricCraniopharyngiomaExt", input, score, ts: TS }; }

function PediatricPinealtumorExt(input) { const score = Math.round((0.45+Number(input.parinaud||0)*0.15)*100)/100; return { version:'3.165.0', module:'pcc_pediatric_neuro_ext55', function:"PediatricPinealtumorExt", input, score, ts: TS }; }

function PediatricBrainstemGliomaExt(input) { const score = Math.round((0.5+Number(input.dipg||0)*0.2)*100)/100; return { version:'3.165.0', module:'pcc_pediatric_neuro_ext55', function:"PediatricBrainstemGliomaExt", input, score, ts: TS }; }

function PediatricNeuroOncFollowupExt(input) { const score = Math.round((0.3+Number(input.months_since_dx||12)*0.02)*100)/100; return { version:'3.165.0', module:'pcc_pediatric_neuro_ext55', function:"PediatricNeuroOncFollowupExt", input, score, ts: TS }; }

module.exports = {
  PediatricBrainTumorStagingExt,
  PediatricGliomaMolecularExt,
  PediatricMedulloblastomaExt,
  PediatricEpendymomaExt,
  PediatricATRTClassificationExt,
  PediatricDNETExt,
  PediatricCraniopharyngiomaExt,
  PediatricPinealtumorExt,
  PediatricBrainstemGliomaExt,
  PediatricNeuroOncFollowupExt,
};