// filepath: pcc/pcc_neuro_ext134/pcc_neuro_ext134_engine.js
module.exports.version='v3.233.0';
module.exports.module='pcc_neuro_ext134';
module.exports.functions={};
module.exports.functions['AbuliaExt']=function(input){const score=Math.round((0.18 + Number(input.motivation||1)*0.2 + Number(input.frontal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_neuro_ext134',function:'AbuliaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CatatoniaExt']=function(input){const score=Math.round((0.18 + Number(input.stupor||1)*0.2 + Number(input.mutism||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_neuro_ext134',function:'CatatoniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AkineticMutismExt']=function(input){const score=Math.round((0.18 + Number(input.mutism||1)*0.2 + Number(input.akinesia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_neuro_ext134',function:'AkineticMutismExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LockedInSyndromeExt']=function(input){const score=Math.round((0.18 + Number(input.pontine||1)*0.2 + Number(input.aware||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_neuro_ext134',function:'LockedInSyndromeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VegetativeStateExt']=function(input){const score=Math.round((0.18 + Number(input.unresponsive||1)*0.2 + Number(input.cycle||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_neuro_ext134',function:'VegetativeStateExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MinimallyConsciousStateExt']=function(input){const score=Math.round((0.18 + Number(input.command||1)*0.2 + Number(input.inconsistent||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_neuro_ext134',function:'MinimallyConsciousStateExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BrainDeathExt']=function(input){const score=Math.round((0.18 + Number(input.coma||1)*0.2 + Number(input.apnea||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_neuro_ext134',function:'BrainDeathExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PersistentVegetativeStateExt']=function(input){const score=Math.round((0.18 + Number(input.months||6)*0.04 + Number(input.unresponsive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_neuro_ext134',function:'PersistentVegetativeStateExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ConsciousnessDisordersExt']=function(input){const score=Math.round((0.18 + Number(input.disorder||1)*0.2 + Number(input.awareness||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_neuro_ext134',function:'ConsciousnessDisordersExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['StuporExt']=function(input){const score=Math.round((0.18 + Number(input.stupor||1)*0.2 + Number(input.unresponsive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_neuro_ext134',function:'StuporExt',input,score,ts:new Date().toISOString()}};

// TS: v3.233.0
