// Auto-generated by gen_p3master.py -- PCC 3.303.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.303.0';

function X333AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x333) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_333', function: 'X333AssessmentExt', input, score, ts: TS };
}

function X333ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x333) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_333', function: 'X333ScoreExt', input, score, ts: TS };
}

function X333StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x333) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_333', function: 'X333StageExt', input, score, ts: TS };
}

function X333PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x333) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_333', function: 'X333PlanExt', input, score, ts: TS };
}

function X333RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x333) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_333', function: 'X333RiskExt', input, score, ts: TS };
}

function X333DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x333) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_333', function: 'X333DoseExt', input, score, ts: TS };
}

function X333FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x333) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_333', function: 'X333FrequencyExt', input, score, ts: TS };
}

function X333DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x333) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_333', function: 'X333DurationExt', input, score, ts: TS };
}

function X333FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x333) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_333', function: 'X333FollowupExt', input, score, ts: TS };
}

function X333OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x333) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_333', function: 'X333OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X333AssessmentExt,
  X333ScoreExt,
  X333StageExt,
  X333PlanExt,
  X333RiskExt,
  X333DoseExt,
  X333FrequencyExt,
  X333DurationExt,
  X333FollowupExt,
  X333OutcomeExt,
};