// filepath: pcc/pcc_pediatric_neuro_ext96/pcc_pediatric_neuro_ext96_engine.js
// pcc_pediatric_neuro_ext96 engine (deterministic)
module.exports.version='v3.206.0';
module.exports.module='pcc_pediatric_neuro_ext96';
module.exports.functions={};
module.exports.functions['PediatricAneurysmExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.aneurysm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_neuro_ext96',function:'PediatricAneurysmExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSAHExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.huntHess||2)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_neuro_ext96',function:'PediatricSAHExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricAVMExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.spetzler||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_neuro_ext96',function:'PediatricAVMExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCavernomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.cavernoma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_neuro_ext96',function:'PediatricCavernomaExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCVMExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.05 + Number(input.malformation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_neuro_ext96',function:'PediatricCVMExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricDuralAVFistulaExt']=function(input){const score=Math.round((0.18 + Number(input.age||6)*0.04 + Number(input.cognard||2)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_neuro_ext96',function:'PediatricDuralAVFistulaExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCCFistulaExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.fistula||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_neuro_ext96',function:'PediatricCCFistulaExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricPICAneurysmExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.aneurysm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_neuro_ext96',function:'PediatricPICAneurysmExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricBasilarExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.aneurysm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_neuro_ext96',function:'PediatricBasilarExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricGiantAneurysmExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.02 + Number(input.aneurysm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_neuro_ext96',function:'PediatricGiantAneurysmExt',input,score,ts:new Date().toISOString()};};

// TS: v3.206.0
