// Auto-generated by gen_p3master.py -- PCC 3.305.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.305.0';

function X337AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x337) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_337', function: 'X337AssessmentExt', input, score, ts: TS };
}

function X337ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x337) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_337', function: 'X337ScoreExt', input, score, ts: TS };
}

function X337StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x337) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_337', function: 'X337StageExt', input, score, ts: TS };
}

function X337PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x337) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_337', function: 'X337PlanExt', input, score, ts: TS };
}

function X337RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x337) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_337', function: 'X337RiskExt', input, score, ts: TS };
}

function X337DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x337) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_337', function: 'X337DoseExt', input, score, ts: TS };
}

function X337FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x337) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_337', function: 'X337FrequencyExt', input, score, ts: TS };
}

function X337DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x337) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_337', function: 'X337DurationExt', input, score, ts: TS };
}

function X337FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x337) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_337', function: 'X337FollowupExt', input, score, ts: TS };
}

function X337OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x337) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_337', function: 'X337OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X337AssessmentExt,
  X337ScoreExt,
  X337StageExt,
  X337PlanExt,
  X337RiskExt,
  X337DoseExt,
  X337FrequencyExt,
  X337DurationExt,
  X337FollowupExt,
  X337OutcomeExt,
};