// filepath: pcc/pcc_rad_ext178/pcc_rad_ext178_engine.js
module.exports.version='v3.14.14.0';
module.exports.module='pcc_rad_ext178';
module.exports.functions={};
module.exports.functions['RadTumorStagingExt']=function(input){const score=Math.round((0.18 + Number(input.radStaging||1)*0.2 + Number(input.tnm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_rad_ext178',function:'RadTumorStagingExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadPETAdultExt']=function(input){const score=Math.round((0.18 + Number(input.petAdult||1)*0.2 + Number(input.suvMax||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_rad_ext178',function:'RadPETAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadCTchestAdultExt']=function(input){const score=Math.round((0.18 + Number(input.ctChest||1)*0.2 + Number(input.recist||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_rad_ext178',function:'RadCTchestAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadMRIadultExt']=function(input){const score=Math.round((0.18 + Number(input.mriTumor||1)*0.2 + Number(input.recistMri||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_rad_ext178',function:'RadMRIadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadBoneScanAdultExt']=function(input){const score=Math.round((0.18 + Number(input.boneScan||1)*0.2 + Number(input.mets||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_rad_ext178',function:'RadBoneScanAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadMammoAdultExt']=function(input){const score=Math.round((0.18 + Number(input.mammoAdult||1)*0.2 + Number(input.biRads||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_rad_ext178',function:'RadMammoAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadColonoscopyAdultExt']=function(input){const score=Math.round((0.18 + Number(input.coloAdult||1)*0.2 + Number(input.coloFinding||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_rad_ext178',function:'RadColonoscopyAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadBronchoscopyAdultExt']=function(input){const score=Math.round((0.18 + Number(input.bronchAdult||1)*0.2 + Number(input.bronchFinding||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_rad_ext178',function:'RadBronchoscopyAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadEndoscopyAdultExt']=function(input){const score=Math.round((0.18 + Number(input.endoAdult||1)*0.2 + Number(input.endoFinding||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_rad_ext178',function:'RadEndoscopyAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RadRecistAdultExt']=function(input){const score=Math.round((0.18 + Number(input.recistAdult||1)*0.2 + Number(input.response||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_rad_ext178',function:'RadRecistAdultExt',input,score,ts:new Date().toISOString()}};

// TS: v3.14.14.0
