// Auto-generated by gen_p3he.py -- PCC v3.173.0
"use strict";
const TS = '2026-07-28T13:00:00Z';

function PediatricPeripheralNeuropathyExt(input) { const score = Math.round((0.3+Number(input.ncs_amp||2)*0.06)*100)/100; return { version:'3.173.0', module:'pcc_pediatric_neuro_ext63', function:'PediatricPeripheralNeuropathyExt', input, score, ts: TS }; }

function PediatricCIDPExt(input) { const score = Math.round((0.4+Number(input.efns_score||3)*0.06)*100)/100; return { version:'3.173.0', module:'pcc_pediatric_neuro_ext63', function:'PediatricCIDPExt', input, score, ts: TS }; }

function PediatricGuillainBarreExt(input) { const score = Math.round((0.45+Number(input.egs_score||3)*0.08)*100)/100; return { version:'3.173.0', module:'pcc_pediatric_neuro_ext63', function:'PediatricGuillainBarreExt', input, score, ts: TS }; }

function PediatricCIDPVariantExt(input) { const score = Math.round((0.4+Number(input.mfs||0)*0.15)*100)/100; return { version:'3.173.0', module:'pcc_pediatric_neuro_ext63', function:'PediatricCIDPVariantExt', input, score, ts: TS }; }

function PediatricDiabeticNeuropathyExt(input) { const score = Math.round((0.3+Number(input.duration||5)*0.05)*100)/100; return { version:'3.173.0', module:'pcc_pediatric_neuro_ext63', function:'PediatricDiabeticNeuropathyExt', input, score, ts: TS }; }

function PediatricCMTExt(input) { const score = Math.round((0.4+Number(input.cmt_score||2)*0.08)*100)/100; return { version:'3.173.0', module:'pcc_pediatric_neuro_ext63', function:'PediatricCMTExt', input, score, ts: TS }; }

function PediatricSmallFiberExt(input) { const score = Math.round((0.35+Number(input.sfn_score||3)*0.08)*100)/100; return { version:'3.173.0', module:'pcc_pediatric_neuro_ext63', function:'PediatricSmallFiberExt', input, score, ts: TS }; }

function PediatricAutonomicNeuropathyExt(input) { const score = Math.round((0.4+Number(input.comp_score||2)*0.1)*100)/100; return { version:'3.173.0', module:'pcc_pediatric_neuro_ext63', function:'PediatricAutonomicNeuropathyExt', input, score, ts: TS }; }

function PediatricHereditaryNeuropathyExt(input) { const score = Math.round((0.35+Number(input.gene||1)*0.12)*100)/100; return { version:'3.173.0', module:'pcc_pediatric_neuro_ext63', function:'PediatricHereditaryNeuropathyExt', input, score, ts: TS }; }

function PediatricVasculiticNeuropathyExt(input) { const score = Math.round((0.4+Number(input.vessel_count||2)*0.1)*100)/100; return { version:'3.173.0', module:'pcc_pediatric_neuro_ext63', function:'PediatricVasculiticNeuropathyExt', input, score, ts: TS }; }

module.exports = {
  PediatricPeripheralNeuropathyExt,
  PediatricCIDPExt,
  PediatricGuillainBarreExt,
  PediatricCIDPVariantExt,
  PediatricDiabeticNeuropathyExt,
  PediatricCMTExt,
  PediatricSmallFiberExt,
  PediatricAutonomicNeuropathyExt,
  PediatricHereditaryNeuropathyExt,
  PediatricVasculiticNeuropathyExt,
};