// filepath: pcc/pcc_pediatric_neuro_ext159/pcc_pediatric_neuro_ext159_engine.js
module.exports.version='v3.12.11.0';
module.exports.module='pcc_pediatric_neuro_ext159';
module.exports.functions={};
module.exports.functions['PediatricNF2childExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pNF2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_neuro_ext159',function:'PediatricNF2childExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTSCgeneticExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pTSCgenetic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_neuro_ext159',function:'PediatricTSCgeneticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVHLgeneticExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pVHLgenetic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_neuro_ext159',function:'PediatricVHLgeneticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLFSext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pLFS||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_neuro_ext159',function:'PediatricLFSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCowdenExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pCowden||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_neuro_ext159',function:'PediatricCowdenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGorlinExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pGorlin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_neuro_ext159',function:'PediatricGorlinExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricATgeneticExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pATgenetic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_neuro_ext159',function:'PediatricATgeneticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHDjuvenileExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pHDjuvenile||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_neuro_ext159',function:'PediatricHDjuvenileExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFRDAext']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pFRDA||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_neuro_ext159',function:'PediatricFRDAext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricKennedyExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pKennedy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.11.0',module:'pcc_pediatric_neuro_ext159',function:'PediatricKennedyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.12.11.0
