// Auto-generated by gen_p3ie.py -- PCC v3.185.0
"use strict";
const TS = '2026-07-28T15:00:00Z';

function PediatricSialorrheaExt(input) { const score = Math.round((0.3+Number(input.drool_score||3)*0.1)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_neuro_ext75', function:'PediatricSialorrheaExt', input, score, ts: TS }; }

function PediatricSpasticityOralExt(input) { const score = Math.round((0.3+Number(input.tone_score||2)*0.15)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_neuro_ext75', function:'PediatricSpasticityOralExt', input, score, ts: TS }; }

function PediatricDysarthriaExt(input) { const score = Math.round((0.3+Number(input.intell_score||50)*0.01)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_neuro_ext75', function:'PediatricDysarthriaExt', input, score, ts: TS }; }

function PediatricDysphagiaExt(input) { const score = Math.round((0.3+Number(input.aspiration_risk||20)*0.018)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_neuro_ext75', function:'PediatricDysphagiaExt', input, score, ts: TS }; }

function PediatricPEGExt(input) { const score = Math.round((0.35+Number(input.weight_loss_pct||5)*0.06)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_neuro_ext75', function:'PediatricPEGExt', input, score, ts: TS }; }

function PediatricTracheostomyDecannExt(input) { const score = Math.round((0.4+Number(input.vent_days||20)*0.01)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_neuro_ext75', function:'PediatricTracheostomyDecannExt', input, score, ts: TS }; }

function PediatricRespAssessmentExt(input) { const score = Math.round((0.3+Number(input.fev1_pct||60)*0.01)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_neuro_ext75', function:'PediatricRespAssessmentExt', input, score, ts: TS }; }

function PediatricVentMgmtExt(input) { const score = Math.round((0.4+Number(input.vent_hours||10)*0.03)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_neuro_ext75', function:'PediatricVentMgmtExt', input, score, ts: TS }; }

function PediatricSleepApneaExt(input) { const score = Math.round((0.4+Number(input.ahi||5)*0.04)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_neuro_ext75', function:'PediatricSleepApneaExt', input, score, ts: TS }; }

function PediatricGIAssessmentExt(input) { const score = Math.round((0.3+Number(input.feeding_score||30)*0.02)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_neuro_ext75', function:'PediatricGIAssessmentExt', input, score, ts: TS }; }

module.exports = {
  PediatricSialorrheaExt,
  PediatricSpasticityOralExt,
  PediatricDysarthriaExt,
  PediatricDysphagiaExt,
  PediatricPEGExt,
  PediatricTracheostomyDecannExt,
  PediatricRespAssessmentExt,
  PediatricVentMgmtExt,
  PediatricSleepApneaExt,
  PediatricGIAssessmentExt,
};