// filepath: pcc/pcc_pediatric_surg_ext173/pcc_pediatric_surg_ext173_engine.js
module.exports.version='v3.13.13.0';
module.exports.module='pcc_pediatric_surg_ext173';
module.exports.functions={};
module.exports.functions['PediatricPitApoplexyTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pPitApoplexyTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_surg_ext173',function:'PediatricPitApoplexyTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEmptySellaTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pEmptySellaTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_surg_ext173',function:'PediatricEmptySellaTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLymphHypoTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pLymphHypoTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_surg_ext173',function:'PediatricLymphHypoTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDIneonatalTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pDIneonatalTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_surg_ext173',function:'PediatricDIneonatalTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSIADHpostOpTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSIADHpostOpTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_surg_ext173',function:'PediatricSIADHpostOpTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHypopitSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pHypopitSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_surg_ext173',function:'PediatricHypopitSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPituitaryPostopSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pPitPostopSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_surg_ext173',function:'PediatricPituitaryPostopSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCraniopharyngiomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pCraniopharyngiomaSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_surg_ext173',function:'PediatricCraniopharyngiomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHypopitHormoneExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pHypopitHormone||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_surg_ext173',function:'PediatricHypopitHormoneExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPitApoplexyCritTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pPitApoplexyCritTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_surg_ext173',function:'PediatricPitApoplexyCritTxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.13.13.0
