// Auto-generated by gen_p3master.py -- PCC 3.268.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.268.0';

function EXT4AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.ext4) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_pharm_ext4', function: 'EXT4AssessmentExt', input, score, ts: TS };
}

function EXT4ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.ext4) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_pharm_ext4', function: 'EXT4ScoreExt', input, score, ts: TS };
}

function EXT4StageExt(input) {
  const score = Math.round((0.3 + (Number(input.ext4) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_pharm_ext4', function: 'EXT4StageExt', input, score, ts: TS };
}

function EXT4PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.ext4) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_pharm_ext4', function: 'EXT4PlanExt', input, score, ts: TS };
}

function EXT4RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.ext4) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_pharm_ext4', function: 'EXT4RiskExt', input, score, ts: TS };
}

function EXT4DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.ext4) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_pharm_ext4', function: 'EXT4DoseExt', input, score, ts: TS };
}

function EXT4FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.ext4) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_pharm_ext4', function: 'EXT4FrequencyExt', input, score, ts: TS };
}

function EXT4DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.ext4) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_pharm_ext4', function: 'EXT4DurationExt', input, score, ts: TS };
}

function EXT4FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.ext4) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_pharm_ext4', function: 'EXT4FollowupExt', input, score, ts: TS };
}

function EXT4OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.ext4) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_pharm_ext4', function: 'EXT4OutcomeExt', input, score, ts: TS };
}

module.exports = {
  EXT4AssessmentExt,
  EXT4ScoreExt,
  EXT4StageExt,
  EXT4PlanExt,
  EXT4RiskExt,
  EXT4DoseExt,
  EXT4FrequencyExt,
  EXT4DurationExt,
  EXT4FollowupExt,
  EXT4OutcomeExt,
};