// filepath: pcc/pcc_anesth_ext100/pcc_anesth_ext100_engine.js
module.exports.version='v3.27.27.0';
module.exports.module='pcc_anesth_ext100';
module.exports.functions={};
module.exports.functions['AnesthGeneralExt']=function(input){const score=Math.round((0.18 + Number(input.anGeneral||1)*0.2 + Number(input.asaClassAN||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.27.27.0',module:'pcc_anesth_ext100',function:'AnesthGeneralExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthRegionalExt']=function(input){const score=Math.round((0.18 + Number(input.anRegional||1)*0.2 + Number(input.blockType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.27.27.0',module:'pcc_anesth_ext100',function:'AnesthRegionalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthLocalExt']=function(input){const score=Math.round((0.18 + Number(input.anLocal||1)*0.2 + Number(input.localType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.27.27.0',module:'pcc_anesth_ext100',function:'AnesthLocalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthSpinalExt']=function(input){const score=Math.round((0.18 + Number(input.anSpinal||1)*0.2 + Number(input.spinalLevel||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.27.27.0',module:'pcc_anesth_ext100',function:'AnesthSpinalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthEpiduralExt']=function(input){const score=Math.round((0.18 + Number(input.anEpidural||1)*0.2 + Number(input.epidLevel||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.27.27.0',module:'pcc_anesth_ext100',function:'AnesthEpiduralExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthSedationExt']=function(input){const score=Math.round((0.18 + Number(input.anSedation||1)*0.2 + Number(input.ramsayScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.27.27.0',module:'pcc_anesth_ext100',function:'AnesthSedationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthPediatricExt']=function(input){const score=Math.round((0.18 + Number(input.anPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.27.27.0',module:'pcc_anesth_ext100',function:'AnesthPediatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthObstetricExt']=function(input){const score=Math.round((0.18 + Number(input.anObstetric||1)*0.2 + Number(input.gestAge||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.27.27.0',module:'pcc_anesth_ext100',function:'AnesthObstetricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthCardiacExt']=function(input){const score=Math.round((0.18 + Number(input.anCardiac||1)*0.2 + Number(input.anCardiacType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.27.27.0',module:'pcc_anesth_ext100',function:'AnesthCardiacExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthTraumaExt']=function(input){const score=Math.round((0.18 + Number(input.anTrauma||1)*0.2 + Number(input.traumaSev||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.27.27.0',module:'pcc_anesth_ext100',function:'AnesthTraumaExt',input,score,ts:new Date().toISOString()}};

// TS: v3.27.27.0
