// Auto-generated by gen_p3master.py -- PCC 3.190.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.190.0';

function CCTAssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.ccta) || 0) * 0.2) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_ct', function: 'CCTAssessmentExt', input, score, ts: TS };
}

function CCTScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.ccts) || 0) * 0.31) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_ct', function: 'CCTScoreExt', input, score, ts: TS };
}

function CCTStageExt(input) {
  const score = Math.round((0.3 + (Number(input.ccts) || 0) * 0.32) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_ct', function: 'CCTStageExt', input, score, ts: TS };
}

function CCTPlanExt(input) {
  const score = Math.round((0.3 + (Number(input.cctp) || 0) * 0.28) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_ct', function: 'CCTPlanExt', input, score, ts: TS };
}

function CCTRiskExt(input) {
  const score = Math.round((0.3 + (Number(input.cctr) || 0) * 0.29) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_ct', function: 'CCTRiskExt', input, score, ts: TS };
}

function CCTDoseExt(input) {
  const score = Math.round((0.3 + (Number(input.cctd) || 0) * 0.3) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_ct', function: 'CCTDoseExt', input, score, ts: TS };
}

function CCTFrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.cctf) || 0) * 0.21) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_ct', function: 'CCTFrequencyExt', input, score, ts: TS };
}

function CCTDurationExt(input) {
  const score = Math.round((0.3 + (Number(input.cctd) || 0) * 0.17) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_ct', function: 'CCTDurationExt', input, score, ts: TS };
}

function CCTFollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.cctf) || 0) * 0.18) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_ct', function: 'CCTFollowupExt', input, score, ts: TS };
}

function CCTOutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.ccto) || 0) * 0.49) * 100) / 100;
  return { version: VER, module: 'pcc_cardiac_ct', function: 'CCTOutcomeExt', input, score, ts: TS };
}

module.exports = {
  CCTAssessmentExt,
  CCTScoreExt,
  CCTStageExt,
  CCTPlanExt,
  CCTRiskExt,
  CCTDoseExt,
  CCTFrequencyExt,
  CCTDurationExt,
  CCTFollowupExt,
  CCTOutcomeExt,
};