// Auto-generated by gen_p3master.py -- PCC 3.288.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.288.0';

function X286AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x286) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_286', function: 'X286AssessmentExt', input, score, ts: TS };
}

function X286ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x286) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_286', function: 'X286ScoreExt', input, score, ts: TS };
}

function X286StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x286) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_286', function: 'X286StageExt', input, score, ts: TS };
}

function X286PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x286) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_286', function: 'X286PlanExt', input, score, ts: TS };
}

function X286RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x286) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_286', function: 'X286RiskExt', input, score, ts: TS };
}

function X286DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x286) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_286', function: 'X286DoseExt', input, score, ts: TS };
}

function X286FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x286) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_286', function: 'X286FrequencyExt', input, score, ts: TS };
}

function X286DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x286) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_286', function: 'X286DurationExt', input, score, ts: TS };
}

function X286FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x286) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_286', function: 'X286FollowupExt', input, score, ts: TS };
}

function X286OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x286) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_286', function: 'X286OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X286AssessmentExt,
  X286ScoreExt,
  X286StageExt,
  X286PlanExt,
  X286RiskExt,
  X286DoseExt,
  X286FrequencyExt,
  X286DurationExt,
  X286FollowupExt,
  X286OutcomeExt,
};