// filepath: pcc/pcc_endocrine_ext100/pcc_endocrine_ext100_engine.js
module.exports.version='v3.20.20.0';
module.exports.module='pcc_endocrine_ext100';
module.exports.functions={};
module.exports.functions['EndoDiabetesExt']=function(input){const score=Math.round((0.18 + Number(input.endoDM||1)*0.2 + Number(input.hba1c||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_endocrine_ext100',function:'EndoDiabetesExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EndoThyroidExt']=function(input){const score=Math.round((0.18 + Number(input.endoThyroid||1)*0.2 + Number(input.tsh||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_endocrine_ext100',function:'EndoThyroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EndoAdrenalExt']=function(input){const score=Math.round((0.18 + Number(input.endoAdrenal||1)*0.2 + Number(input.cortisol||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_endocrine_ext100',function:'EndoAdrenalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EndoPituitaryExt']=function(input){const score=Math.round((0.18 + Number(input.endoPit||1)*0.2 + Number(input.igf1||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_endocrine_ext100',function:'EndoPituitaryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EndoParathyroidExt']=function(input){const score=Math.round((0.18 + Number(input.endoPTH||1)*0.2 + Number(input.calcium||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_endocrine_ext100',function:'EndoParathyroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EndoGonadExt']=function(input){const score=Math.round((0.18 + Number(input.endoGonad||1)*0.2 + Number(input.testosterone||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_endocrine_ext100',function:'EndoGonadExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EndoPCOSext']=function(input){const score=Math.round((0.18 + Number(input.endoPCOS||1)*0.2 + Number(input.amhPCOS||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_endocrine_ext100',function:'EndoPCOSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['EndoObesityExt']=function(input){const score=Math.round((0.18 + Number(input.endoObesity||1)*0.2 + Number(input.bmiOb||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_endocrine_ext100',function:'EndoObesityExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EndoLipidExt']=function(input){const score=Math.round((0.18 + Number(input.endoLipid||1)*0.2 + Number(input.ldlEndo||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_endocrine_ext100',function:'EndoLipidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EndoBoneExt']=function(input){const score=Math.round((0.18 + Number(input.endoBone||1)*0.2 + Number(input.boneDex||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_endocrine_ext100',function:'EndoBoneExt',input,score,ts:new Date().toISOString()}};

// TS: v3.20.20.0
