// Auto-generated by gen_p3master.py -- PCC 3.292.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.292.0';

function X299AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x299) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_299', function: 'X299AssessmentExt', input, score, ts: TS };
}

function X299ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x299) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_299', function: 'X299ScoreExt', input, score, ts: TS };
}

function X299StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x299) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_299', function: 'X299StageExt', input, score, ts: TS };
}

function X299PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x299) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_299', function: 'X299PlanExt', input, score, ts: TS };
}

function X299RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x299) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_299', function: 'X299RiskExt', input, score, ts: TS };
}

function X299DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x299) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_299', function: 'X299DoseExt', input, score, ts: TS };
}

function X299FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x299) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_299', function: 'X299FrequencyExt', input, score, ts: TS };
}

function X299DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x299) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_299', function: 'X299DurationExt', input, score, ts: TS };
}

function X299FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x299) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_299', function: 'X299FollowupExt', input, score, ts: TS };
}

function X299OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x299) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_299', function: 'X299OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X299AssessmentExt,
  X299ScoreExt,
  X299StageExt,
  X299PlanExt,
  X299RiskExt,
  X299DoseExt,
  X299FrequencyExt,
  X299DurationExt,
  X299FollowupExt,
  X299OutcomeExt,
};