// Auto_generated by gen_p3hk.py -- PCC v3.179.0
"use strict";
const TS = '2026-07-28T14:00:00Z';

function PediatricOpticNerveSheathFenestrationExt(input) { const score = Math.round((0.45+Number(input.thickness||5)*0.05)*100)/100; return { version:'3.179.0', module:'pcc_pediatric_surg_ext69', function:"PediatricOpticNerveSheathFenestrationExt", input, score, ts: TS }; }

function PediatricThymectomyImmExt(input) { const score = Math.round((0.4+Number(input.thymus_size||3)*0.08)*100)/100; return { version:'3.179.0', module:'pcc_pediatric_surg_ext69', function:"PediatricThymectomyImmExt", input, score, ts: TS }; }

function PediatricITBSurgExt(input) { const score = Math.round((0.4+Number(input.dose_mg||5)*0.05)*100)/100; return { version:'3.179.0', module:'pcc_pediatric_surg_ext69', function:"PediatricITBSurgExt", input, score, ts: TS }; }

function PediatricVNSImmExt(input) { const score = Math.round((0.35+Number(input.output_mA||1)*0.1)*100)/100; return { version:'3.179.0', module:'pcc_pediatric_surg_ext69', function:"PediatricVNSImmExt", input, score, ts: TS }; }

function PediatricAlemtuzumabExt(input) { const score = Math.round((0.5+Number(input.dose_mg||12)*0.05)*100)/100; return { version:'3.179.0', module:'pcc_pediatric_surg_ext69', function:"PediatricAlemtuzumabExt", input, score, ts: TS }; }

function PediatricRituximabSurgExt(input) { const score = Math.round((0.4+Number(input.dose_mg||375)*0.0006)*100)/100; return { version:'3.179.0', module:'pcc_pediatric_surg_ext69', function:"PediatricRituximabSurgExt", input, score, ts: TS }; }

function PediatricIVIGExt(input) { const score = Math.round((0.3+Number(input.dose_gkg||1)*0.15)*100)/100; return { version:'3.179.0', module:'pcc_pediatric_surg_ext69', function:"PediatricIVIGExt", input, score, ts: TS }; }

function PediatricMitoxantroneExt(input) { const score = Math.round((0.5+Number(input.dose_mg||20)*0.01)*100)/100; return { version:'3.179.0', module:'pcc_pediatric_surg_ext69', function:"PediatricMitoxantroneExt", input, score, ts: TS }; }

function PediatricNatalizumabExt(input) { const score = Math.round((0.4+Number(input.doses||12)*0.03)*100)/100; return { version:'3.179.0', module:'pcc_pediatric_surg_ext69', function:"PediatricNatalizumabExt", input, score, ts: TS }; }

function PediatricFingolimodExt(input) { const score = Math.round((0.4+Number(input.dose_mg||0.5)*0.4)*100)/100; return { version:'3.179.0', module:'pcc_pediatric_surg_ext69', function:"PediatricFingolimodExt", input, score, ts: TS }; }

module.exports = {
  PediatricOpticNerveSheathFenestrationExt,
  PediatricThymectomyImmExt,
  PediatricITBSurgExt,
  PediatricVNSImmExt,
  PediatricAlemtuzumabExt,
  PediatricRituximabSurgExt,
  PediatricIVIGExt,
  PediatricMitoxantroneExt,
  PediatricNatalizumabExt,
  PediatricFingolimodExt,
};