// Auto-generated by gen_p3master.py -- PCC 3.316.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.316.0';

function X372AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x372) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_372', function: 'X372AssessmentExt', input, score, ts: TS };
}

function X372ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x372) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_372', function: 'X372ScoreExt', input, score, ts: TS };
}

function X372StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x372) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_372', function: 'X372StageExt', input, score, ts: TS };
}

function X372PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x372) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_372', function: 'X372PlanExt', input, score, ts: TS };
}

function X372RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x372) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_372', function: 'X372RiskExt', input, score, ts: TS };
}

function X372DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x372) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_372', function: 'X372DoseExt', input, score, ts: TS };
}

function X372FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x372) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_372', function: 'X372FrequencyExt', input, score, ts: TS };
}

function X372DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x372) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_372', function: 'X372DurationExt', input, score, ts: TS };
}

function X372FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x372) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_372', function: 'X372FollowupExt', input, score, ts: TS };
}

function X372OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x372) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_372', function: 'X372OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X372AssessmentExt,
  X372ScoreExt,
  X372StageExt,
  X372PlanExt,
  X372RiskExt,
  X372DoseExt,
  X372FrequencyExt,
  X372DurationExt,
  X372FollowupExt,
  X372OutcomeExt,
};