// Auto-generated by gen_p3ic.py -- PCC v3.183.0
"use strict";
const TS = '2026-07-28T14:40:00Z';

function PediatricDementiaScreeningExt(input) { const score = Math.round((0.3+Number(input.cog_score||80)*0.005)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_neuro_ext73', function:'PediatricDementiaScreeningExt', input, score, ts: TS }; }

function PediatricNiemannPickExt(input) { const score = Math.round((0.4+Number(input.splenomegaly||0)*0.2)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_neuro_ext73', function:'PediatricNiemannPickExt', input, score, ts: TS }; }

function PediatricTaySachsExt(input) { const score = Math.round((0.4+Number(input.hex_a||0)*0.2)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_neuro_ext73', function:'PediatricTaySachsExt', input, score, ts: TS }; }

function PediatricBattenDiseaseExt(input) { const score = Math.round((0.4+Number(input.cln3||0)*0.2)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_neuro_ext73', function:'PediatricBattenDiseaseExt', input, score, ts: TS }; }

function PediatricLeukodystrophyExt(input) { const score = Math.round((0.4+Number(input.mri_charcot||1)*0.15)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_neuro_ext73', function:'PediatricLeukodystrophyExt', input, score, ts: TS }; }

function PediatricALDGenExt(input) { const score = Math.round((0.4+Number(input.abc||0)*0.2)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_neuro_ext73', function:'PediatricALDGenExt', input, score, ts: TS }; }

function PediatricPKUExt(input) { const score = Math.round((0.4+Number(input.phe_level||2)*0.2)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_neuro_ext73', function:'PediatricPKUExt', input, score, ts: TS }; }

function PediatricMLDExt(input) { const score = Math.round((0.4+Number(input.substrate||0)*0.2)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_neuro_ext73', function:'PediatricMLDExt', input, score, ts: TS }; }

function PediatricMitochondrialExt(input) { const score = Math.round((0.4+Number(input.mtdna||0)*0.15)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_neuro_ext73', function:'PediatricMitochondrialExt', input, score, ts: TS }; }

function PediatricScreenDevelopmentalExt(input) { const score = Math.round((0.3+Number(input.developmental_age||0)*0.05)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_neuro_ext73', function:'PediatricScreenDevelopmentalExt', input, score, ts: TS }; }

module.exports = {
  PediatricDementiaScreeningExt,
  PediatricNiemannPickExt,
  PediatricTaySachsExt,
  PediatricBattenDiseaseExt,
  PediatricLeukodystrophyExt,
  PediatricALDGenExt,
  PediatricPKUExt,
  PediatricMLDExt,
  PediatricMitochondrialExt,
  PediatricScreenDevelopmentalExt,
};