// filepath: pcc/pcc_pediatric_surg_ext131/pcc_pediatric_surg_ext131_engine.js
module.exports.version='v3.241.0';
module.exports.module='pcc_pediatric_surg_ext131';
module.exports.functions={};
module.exports.functions['PediatricB12ReplExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.b12Replace||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_surg_ext131',function:'PediatricB12ReplExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFolateReplExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.folateReplace||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_surg_ext131',function:'PediatricFolateReplExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricThiamineReplExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.thiamineReplace||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_surg_ext131',function:'PediatricThiamineReplExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNiacinReplExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.niacinReplace||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_surg_ext131',function:'PediatricNiacinReplExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricB6ReplExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.b6Replace||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_surg_ext131',function:'PediatricB6ReplExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVitDReplExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.vitDReplace||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_surg_ext131',function:'PediatricVitDReplExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVitEReplExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.vitEReplace||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_surg_ext131',function:'PediatricVitEReplExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCopperReplExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.copperReplace||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_surg_ext131',function:'PediatricCopperReplExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricZincReplExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.zincReplace||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_surg_ext131',function:'PediatricZincReplExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSeleniumReplExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.seleniumReplace||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_surg_ext131',function:'PediatricSeleniumReplExt',input,score,ts:new Date().toISOString()}};

// TS: v3.241.0
