// filepath: pcc/pcc_palliative_ext102/pcc_palliative_ext102_engine.js
module.exports.version='v3.52.52.0';
module.exports.module='pcc_palliative_ext102';
module.exports.functions={};
module.exports.functions['PalGenExt']=function(input){const score=Math.round((0.18 + Number(input.plGen||1)*0.2 + Number(input.plGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_palliative_ext102',function:'PalGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PalSymptomExt']=function(input){const score=Math.round((0.18 + Number(input.plSym||1)*0.2 + Number(input.plSymScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_palliative_ext102',function:'PalSymptomExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PalPainExt']=function(input){const score=Math.round((0.18 + Number(input.plPain||1)*0.2 + Number(input.plPainScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_palliative_ext102',function:'PalPainExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PalDyspneaExt']=function(input){const score=Math.round((0.18 + Number(input.plDys||1)*0.2 + Number(input.plDysScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_palliative_ext102',function:'PalDyspneaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PalNauseaExt']=function(input){const score=Math.round((0.18 + Number(input.plNau||1)*0.2 + Number(input.plNauScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_palliative_ext102',function:'PalNauseaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PalConstipationExt']=function(input){const score=Math.round((0.18 + Number(input.plCon||1)*0.2 + Number(input.plConScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_palliative_ext102',function:'PalConstipationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PalDeliriumExt']=function(input){const score=Math.round((0.18 + Number(input.plDel||1)*0.2 + Number(input.plDelScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_palliative_ext102',function:'PalDeliriumExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PalAnorexiaExt']=function(input){const score=Math.round((0.18 + Number(input.plAno||1)*0.2 + Number(input.plAnoScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_palliative_ext102',function:'PalAnorexiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PalPsychExt']=function(input){const score=Math.round((0.18 + Number(input.plPsy||1)*0.2 + Number(input.plPsyScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_palliative_ext102',function:'PalPsychExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PalFamilyExt']=function(input){const score=Math.round((0.18 + Number(input.plFam||1)*0.2 + Number(input.plFamScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_palliative_ext102',function:'PalFamilyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.52.52.0
