// filepath: pcc/pcc_pediatric_neuro_ext143/pcc_pediatric_neuro_ext143_engine.js
module.exports.version='v3.253.0';
module.exports.module='pcc_pediatric_neuro_ext143';
module.exports.functions={};
module.exports.functions['PediatricBellPalsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pBell||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.253.0',module:'pcc_pediatric_neuro_ext143',function:'PediatricBellPalsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRamsayExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pRamsay||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.253.0',module:'pcc_pediatric_neuro_ext143',function:'PediatricRamsayExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFacialPalsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.facialPalsy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.253.0',module:'pcc_pediatric_neuro_ext143',function:'PediatricFacialPalsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMobiusExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.mobius||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.253.0',module:'pcc_pediatric_neuro_ext143',function:'PediatricMobiusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTrigeminalExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pTrigeminal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.253.0',module:'pcc_pediatric_neuro_ext143',function:'PediatricTrigeminalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHFSext']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pHFS||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.253.0',module:'pcc_pediatric_neuro_ext143',function:'PediatricHFSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCongenitalFacialExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.congFacial||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.253.0',module:'pcc_pediatric_neuro_ext143',function:'PediatricCongenitalFacialExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFacialDiplegiaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.facialDiplegia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.253.0',module:'pcc_pediatric_neuro_ext143',function:'PediatricFacialDiplegiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGBSfacialExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.gbsFacial||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.253.0',module:'pcc_pediatric_neuro_ext143',function:'PediatricGBSfacialExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLymeFacialExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.lymeFacial||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.253.0',module:'pcc_pediatric_neuro_ext143',function:'PediatricLymeFacialExt',input,score,ts:new Date().toISOString()}};

// TS: v3.253.0
