// filepath: pcc/pcc_neuro_ext165/pcc_neuro_ext165_engine.js
module.exports.version='v3.264.0';
module.exports.module='pcc_neuro_ext165';
module.exports.functions={};
module.exports.functions['VertigoBPPVext']=function(input){const score=Math.round((0.18 + Number(input.bppv||1)*0.2 + Number(input.dixHallpike||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_neuro_ext165',function:'VertigoBPPVext',input,score,ts:new Date().toISOString()}};
module.exports.functions['VestibularNeuritisExt']=function(input){const score=Math.round((0.18 + Number(input.vestNeur||1)*0.2 + Number(input.acuteVertigo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_neuro_ext165',function:'VestibularNeuritisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MeniereDiseaseExt']=function(input){const score=Math.round((0.18 + Number(input.meniere||1)*0.2 + Number(input.endolymph||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_neuro_ext165',function:'MeniereDiseaseExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LabyrinthitisExt']=function(input){const score=Math.round((0.18 + Number(input.labyrinth||1)*0.2 + Number(input.hearingLoss||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_neuro_ext165',function:'LabyrinthitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SuperiorCanalDehiscenceExt']=function(input){const score=Math.round((0.18 + Number(input.scd||1)*0.2 + Number(input.bonyDefect||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_neuro_ext165',function:'SuperiorCanalDehiscenceExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BilateralVestibulopathyExt']=function(input){const score=Math.round((0.18 + Number(input.bvp||1)*0.2 + Number(input.oscillopsia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_neuro_ext165',function:'BilateralVestibulopathyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VestibularMigraineExt']=function(input){const score=Math.round((0.18 + Number(input.vestMig||1)*0.2 + Number(input.headache||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_neuro_ext165',function:'VestibularMigraineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MalDeDebarquementExt']=function(input){const score=Math.round((0.18 + Number(input.mdd||1)*0.2 + Number(input.rocking||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_neuro_ext165',function:'MalDeDebarquementExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PersistentPosturalExt']=function(input){const score=Math.round((0.18 + Number(input.pppd||1)*0.2 + Number(input.postural||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_neuro_ext165',function:'PersistentPosturalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CervicogenicVertigoExt']=function(input){const score=Math.round((0.18 + Number(input.cervVertigo||1)*0.2 + Number(input.cervical||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_neuro_ext165',function:'CervicogenicVertigoExt',input,score,ts:new Date().toISOString()}};

// TS: v3.264.0
