-- sup_104 reverse
BEGIN;
DROP TABLE IF EXISTS sup_104_results CASCADE;
DROP TABLE IF EXISTS sup_104_orders  CASCADE;
DROP TABLE IF EXISTS sup_104_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_SUP_104_up';
COMMIT;
