// Auto-generated by gen_p3id.py -- PCC v3.184.0
"use strict";
const TS = '2026-07-28T14:50:00Z';

function PediatricSleepDisorderExt(input) { const score = Math.round((0.3+Number(input.osahs||3)*0.07)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_neuro_ext74', function:'PediatricSleepDisorderExt', input, score, ts: TS }; }

function PediatricOSAExt(input) { const score = Math.round((0.35+Number(input.ahi||3)*0.07)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_neuro_ext74', function:'PediatricOSAExt', input, score, ts: TS }; }

function PediatricCSAExt(input) { const score = Math.round((0.4+Number(input.cahi||3)*0.1)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_neuro_ext74', function:'PediatricCSAExt', input, score, ts: TS }; }

function PediatricNarcolepsyExt(input) { const score = Math.round((0.35+Number(input.ess||12)*0.04)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_neuro_ext74', function:'PediatricNarcolepsyExt', input, score, ts: TS }; }

function PediatricRLSExt(input) { const score = Math.round((0.3+Number(input.irls||15)*0.03)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_neuro_ext74', function:'PediatricRLSExt', input, score, ts: TS }; }

function PediatricRBDExt(input) { const score = Math.round((0.4+Number(input.rbd||5)*0.06)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_neuro_ext74', function:'PediatricRBDExt', input, score, ts: TS }; }

function PediatricCircadianExt(input) { const score = Math.round((0.3+Number(input.sleep_offset||4)*0.1)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_neuro_ext74', function:'PediatricCircadianExt', input, score, ts: TS }; }

function PediatricCPAPExt(input) { const score = Math.round((0.3+Number(input.cpap||5)*0.06)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_neuro_ext74', function:'PediatricCPAPExt', input, score, ts: TS }; }

function PediatricAdenotonsillectomyExt(input) { const score = Math.round((0.4+Number(input.tonsil_size||3)*0.08)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_neuro_ext74', function:'PediatricAdenotonsillectomyExt', input, score, ts: TS }; }

function PediatricSleepApneaSynExt(input) { const score = Math.round((0.3+Number(input.ahi||5)*0.04)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_neuro_ext74', function:'PediatricSleepApneaSynExt', input, score, ts: TS }; }

module.exports = {
  PediatricSleepDisorderExt,
  PediatricOSAExt,
  PediatricCSAExt,
  PediatricNarcolepsyExt,
  PediatricRLSExt,
  PediatricRBDExt,
  PediatricCircadianExt,
  PediatricCPAPExt,
  PediatricAdenotonsillectomyExt,
  PediatricSleepApneaSynExt,
};