// Auto-generated by gen_p3master.py -- PCC 3.297.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.297.0';

function X314AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x314) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_314', function: 'X314AssessmentExt', input, score, ts: TS };
}

function X314ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x314) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_314', function: 'X314ScoreExt', input, score, ts: TS };
}

function X314StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x314) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_314', function: 'X314StageExt', input, score, ts: TS };
}

function X314PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x314) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_314', function: 'X314PlanExt', input, score, ts: TS };
}

function X314RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x314) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_314', function: 'X314RiskExt', input, score, ts: TS };
}

function X314DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x314) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_314', function: 'X314DoseExt', input, score, ts: TS };
}

function X314FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x314) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_314', function: 'X314FrequencyExt', input, score, ts: TS };
}

function X314DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x314) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_314', function: 'X314DurationExt', input, score, ts: TS };
}

function X314FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x314) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_314', function: 'X314FollowupExt', input, score, ts: TS };
}

function X314OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x314) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_314', function: 'X314OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X314AssessmentExt,
  X314ScoreExt,
  X314StageExt,
  X314PlanExt,
  X314RiskExt,
  X314DoseExt,
  X314FrequencyExt,
  X314DurationExt,
  X314FollowupExt,
  X314OutcomeExt,
};