// filepath: pcc/pcc_pediatric_surg_ext163/pcc_pediatric_surg_ext163_engine.js
module.exports.version='v3.1.3.0';
module.exports.module='pcc_pediatric_surg_ext163';
module.exports.functions={};
module.exports.functions['PediatricEpiGeneTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.epiGeneTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.3.0',module:'pcc_pediatric_surg_ext163',function:'PediatricEpiGeneTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCN1ATxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.scn1aTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.3.0',module:'pcc_pediatric_surg_ext163',function:'PediatricSCN1ATxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGLUT1ketoExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.glut1Keto||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.3.0',module:'pcc_pediatric_surg_ext163',function:'PediatricGLUT1ketoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricB6DepRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.b6DepRx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.3.0',module:'pcc_pediatric_surg_ext163',function:'PediatricB6DepRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPLPdeRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.plpDepRx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.3.0',module:'pcc_pediatric_surg_ext163',function:'PediatricPLPdeRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFolinicDepRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.folinicRx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.3.0',module:'pcc_pediatric_surg_ext163',function:'PediatricFolinicDepRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricKCNQ2RxExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.kcnq2Rx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.3.0',module:'pcc_pediatric_surg_ext163',function:'PediatricKCNQ2RxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSTXBP1TxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.stxbp1Tx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.3.0',module:'pcc_pediatric_surg_ext163',function:'PediatricSTXBP1TxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCDKL5TxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.cdkl5Tx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.3.0',module:'pcc_pediatric_surg_ext163',function:'PediatricCDKL5TxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPCDH19CBText']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pcdh19CBT||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.3.0',module:'pcc_pediatric_surg_ext163',function:'PediatricPCDH19CBText',input,score,ts:new Date().toISOString()}};

// TS: v3.1.3.0
