// filepath: pcc/pcc_pediatric_neuro_ext128/pcc_pediatric_neuro_ext128_engine.js
module.exports.version='v3.238.0';
module.exports.module='pcc_pediatric_neuro_ext128';
module.exports.functions={};
module.exports.functions['PediatricHemophiliaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.hemophilia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_neuro_ext128',function:'PediatricHemophiliaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVWDExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.vwd||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_neuro_ext128',function:'PediatricVWDExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricITPExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.itp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_neuro_ext128',function:'PediatricITPExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAcquiredHemoExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.acquiredHemo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_neuro_ext128',function:'PediatricAcquiredHemoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDICExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.dic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_neuro_ext128',function:'PediatricDICExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTMAext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.tma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_neuro_ext128',function:'PediatricTMAext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHypercoagExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.hypercoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_neuro_ext128',function:'PediatricHypercoagExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAPASext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.aps||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_neuro_ext128',function:'PediatricAPASext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricThrombophiliaExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.thrombophilia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_neuro_ext128',function:'PediatricThrombophiliaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAnticoagulationExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anticoagulation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_neuro_ext128',function:'PediatricAnticoagulationExt',input,score,ts:new Date().toISOString()}};

// TS: v3.238.0
