// Auto_generated by gen_p3gz.py -- PCC v3.168.0
"use strict";
const TS = '2026-07-28T12:10:00Z';

function PediatricTrigeminalSurgeryExt(input) { const score = Math.round((0.4+Number(input.vessel_contact||0)*0.15)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_surg_ext58', function:"PediatricTrigeminalSurgeryExt", input, score, ts: TS }; }

function PediatricMVDExt(input) { const score = Math.round((0.5+Number(input.vein_size||3)*0.05)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_surg_ext58', function:"PediatricMVDExt", input, score, ts: TS }; }

function PediatricGammaKnifeHeadacheExt(input) { const score = Math.round((0.4+Number(input.dose_g||70)*0.005)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_surg_ext58', function:"PediatricGammaKnifeHeadacheExt", input, score, ts: TS }; }

function PediatricClusterSurgeryExt(input) { const score = Math.round((0.5+Number(input.spheno_palatine||0)*0.15)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_surg_ext58', function:"PediatricClusterSurgeryExt", input, score, ts: TS }; }

function PediatricMigraineSurgeryExt(input) { const score = Math.round((0.3+Number(input.trigger_sites||2)*0.08)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_surg_ext58', function:"PediatricMigraineSurgeryExt", input, score, ts: TS }; }

function PediatricOccipitalStimExt(input) { const score = Math.round((0.35+Number(input.leads||2)*0.06)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_surg_ext58', function:"PediatricOccipitalStimExt", input, score, ts: TS }; }

function PediatricVCNSSurgeryExt(input) { const score = Math.round((0.4+Number(input.intensity||2)*0.08)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_surg_ext58', function:"PediatricVCNSSurgeryExt", input, score, ts: TS }; }

function PediatricBotoxInjectionExt(input) { const score = Math.round((0.3+Number(input.sites||5)*0.04)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_surg_ext58', function:"PediatricBotoxInjectionExt", input, score, ts: TS }; }

function PediatricHeadacheBlockExt(input) { const score = Math.round((0.25+Number(input.nerves||3)*0.05)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_surg_ext58', function:"PediatricHeadacheBlockExt", input, score, ts: TS }; }

function PediatricPNSMigraineExt(input) { const score = Math.round((0.3+Number(input.leads||4)*0.04)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_surg_ext58', function:"PediatricPNSMigraineExt", input, score, ts: TS }; }

module.exports = {
  PediatricTrigeminalSurgeryExt,
  PediatricMVDExt,
  PediatricGammaKnifeHeadacheExt,
  PediatricClusterSurgeryExt,
  PediatricMigraineSurgeryExt,
  PediatricOccipitalStimExt,
  PediatricVCNSSurgeryExt,
  PediatricBotoxInjectionExt,
  PediatricHeadacheBlockExt,
  PediatricPNSMigraineExt,
};