// filepath: pcc/pcc_pediatric_surg_ext115/pcc_pediatric_surg_ext115_engine.js
module.exports.version='v3.225.0';
module.exports.module='pcc_pediatric_surg_ext115';
module.exports.functions={};
module.exports.functions['PediatricMoyaMoyaSxExt2']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.bypass||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.225.0',module:'pcc_pediatric_surg_ext115',function:'PediatricMoyaMoyaSxExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMoyaMoyaChildSxExt2']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.225.0',module:'pcc_pediatric_surg_ext115',function:'PediatricMoyaMoyaChildSxExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDirectRevascSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.225.0',module:'pcc_pediatric_surg_ext115',function:'PediatricDirectRevascSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIndirectRevascSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.225.0',module:'pcc_pediatric_surg_ext115',function:'PediatricIndirectRevascSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCombinedSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.225.0',module:'pcc_pediatric_surg_ext115',function:'PediatricCombinedSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricICABypassSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.225.0',module:'pcc_pediatric_surg_ext115',function:'PediatricICABypassSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHighFlowBypassSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.225.0',module:'pcc_pediatric_surg_ext115',function:'PediatricHighFlowBypassSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSTAMCASxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.225.0',module:'pcc_pediatric_surg_ext115',function:'PediatricSTAMCASxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOABypassSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.225.0',module:'pcc_pediatric_surg_ext115',function:'PediatricOABypassSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMultipleBypassSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.225.0',module:'pcc_pediatric_surg_ext115',function:'PediatricMultipleBypassSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.225.0
