// filepath: pcc/pcc_pediatric_surg_ext167/pcc_pediatric_surg_ext167_engine.js
module.exports.version='v3.1.7.0';
module.exports.module='pcc_pediatric_surg_ext167';
module.exports.functions={};
module.exports.functions['PediatricChronicPainTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.chronicPainTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_surg_ext167',function:'PediatricChronicPainTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCRPSTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.crpsTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_surg_ext167',function:'PediatricCRPSTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMigraineChronicTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.migChronicTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_surg_ext167',function:'PediatricMigraineChronicTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFibromyalgiaTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.fibroTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_surg_ext167',function:'PediatricFibromyalgiaTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAbdPainTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.abdPainTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_surg_ext167',function:'PediatricAbdPainTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHeadChronicTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.headChronicTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_surg_ext167',function:'PediatricHeadChronicTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricComplexPainTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.complexPainTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_surg_ext167',function:'PediatricComplexPainTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeuropathicTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.neuropathicTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_surg_ext167',function:'PediatricNeuropathicTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSicklePainTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.sicklePainTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_surg_ext167',function:'PediatricSicklePainTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCancerPainTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cancerPainTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_surg_ext167',function:'PediatricCancerPainTxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.7.0
