// filepath: pcc/pcc_pediatric_surg_ext103/pcc_pediatric_surg_ext103_engine.js
module.exports.version='v3.213.0';
module.exports.module='pcc_pediatric_surg_ext103';
module.exports.functions={};
module.exports.functions['PediatricSMANusinersenExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.nusinersen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_surg_ext103',function:'PediatricSMANusinersenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSMA1SxExt']=function(input){const score=Math.round((0.18 + Number(input.age||0.5)*0.05 + Number(input.geneTherapy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_surg_ext103',function:'PediatricSMA1SxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSMA2SxExt']=function(input){const score=Math.round((0.18 + Number(input.age||2)*0.04 + Number(input.nusinersen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_surg_ext103',function:'PediatricSMA2SxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSMA3SxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.nusinersen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_surg_ext103',function:'PediatricSMA3SxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDuchenneSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_surg_ext103',function:'PediatricDuchenneSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBeckerSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_surg_ext103',function:'PediatricBeckerSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMyotonicSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.cardiac||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_surg_ext103',function:'PediatricMyotonicSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPompeSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.ert||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_surg_ext103',function:'PediatricPompeSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDermatomyositisImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_surg_ext103',function:'PediatricDermatomyositisImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCongenitalMyoSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||2)*0.04 + Number(input.supportive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.213.0',module:'pcc_pediatric_surg_ext103',function:'PediatricCongenitalMyoSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.213.0
