// Auto-generated by gen_p3master.py -- PCC 3.295.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.295.0';

function X307AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x307) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_307', function: 'X307AssessmentExt', input, score, ts: TS };
}

function X307ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x307) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_307', function: 'X307ScoreExt', input, score, ts: TS };
}

function X307StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x307) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_307', function: 'X307StageExt', input, score, ts: TS };
}

function X307PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x307) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_307', function: 'X307PlanExt', input, score, ts: TS };
}

function X307RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x307) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_307', function: 'X307RiskExt', input, score, ts: TS };
}

function X307DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x307) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_307', function: 'X307DoseExt', input, score, ts: TS };
}

function X307FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x307) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_307', function: 'X307FrequencyExt', input, score, ts: TS };
}

function X307DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x307) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_307', function: 'X307DurationExt', input, score, ts: TS };
}

function X307FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x307) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_307', function: 'X307FollowupExt', input, score, ts: TS };
}

function X307OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x307) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_307', function: 'X307OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X307AssessmentExt,
  X307ScoreExt,
  X307StageExt,
  X307PlanExt,
  X307RiskExt,
  X307DoseExt,
  X307FrequencyExt,
  X307DurationExt,
  X307FollowupExt,
  X307OutcomeExt,
};