// Auto-generated by gen_p3master.py -- PCC 3.307.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.307.0';

function X344AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x344) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_344', function: 'X344AssessmentExt', input, score, ts: TS };
}

function X344ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x344) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_344', function: 'X344ScoreExt', input, score, ts: TS };
}

function X344StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x344) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_344', function: 'X344StageExt', input, score, ts: TS };
}

function X344PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x344) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_344', function: 'X344PlanExt', input, score, ts: TS };
}

function X344RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x344) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_344', function: 'X344RiskExt', input, score, ts: TS };
}

function X344DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x344) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_344', function: 'X344DoseExt', input, score, ts: TS };
}

function X344FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x344) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_344', function: 'X344FrequencyExt', input, score, ts: TS };
}

function X344DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x344) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_344', function: 'X344DurationExt', input, score, ts: TS };
}

function X344FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x344) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_344', function: 'X344FollowupExt', input, score, ts: TS };
}

function X344OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x344) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_344', function: 'X344OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X344AssessmentExt,
  X344ScoreExt,
  X344StageExt,
  X344PlanExt,
  X344RiskExt,
  X344DoseExt,
  X344FrequencyExt,
  X344DurationExt,
  X344FollowupExt,
  X344OutcomeExt,
};