// Auto-generated by gen_p3master.py -- PCC 3.294.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.294.0';

function X305AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x305) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_305', function: 'X305AssessmentExt', input, score, ts: TS };
}

function X305ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x305) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_305', function: 'X305ScoreExt', input, score, ts: TS };
}

function X305StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x305) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_305', function: 'X305StageExt', input, score, ts: TS };
}

function X305PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x305) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_305', function: 'X305PlanExt', input, score, ts: TS };
}

function X305RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x305) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_305', function: 'X305RiskExt', input, score, ts: TS };
}

function X305DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x305) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_305', function: 'X305DoseExt', input, score, ts: TS };
}

function X305FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x305) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_305', function: 'X305FrequencyExt', input, score, ts: TS };
}

function X305DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x305) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_305', function: 'X305DurationExt', input, score, ts: TS };
}

function X305FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x305) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_305', function: 'X305FollowupExt', input, score, ts: TS };
}

function X305OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x305) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_305', function: 'X305OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X305AssessmentExt,
  X305ScoreExt,
  X305StageExt,
  X305PlanExt,
  X305RiskExt,
  X305DoseExt,
  X305FrequencyExt,
  X305DurationExt,
  X305FollowupExt,
  X305OutcomeExt,
};