// filepath: pcc/pcc_neuro_ext167/pcc_neuro_ext167_engine.js
module.exports.version='v3.12.8.0';
module.exports.module='pcc_neuro_ext167';
module.exports.functions={};
module.exports.functions['NeuroendocrineTumorExt']=function(input){const score=Math.round((0.18 + Number(input.net||1)*0.2 + Number(input.carcinoid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_neuro_ext167',function:'NeuroendocrineTumorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PituitaryAdenomaExt']=function(input){const score=Math.round((0.18 + Number(input.pituitaryAd||1)*0.2 + Number(input.prolactin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_neuro_ext167',function:'PituitaryAdenomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AcromegalyExt']=function(input){const score=Math.round((0.18 + Number(input.acromegaly||1)*0.2 + Number(input.gh||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_neuro_ext167',function:'AcromegalyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CushingDiseaseExt']=function(input){const score=Math.round((0.18 + Number(input.cushing||1)*0.2 + Number(input.cortisol||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_neuro_ext167',function:'CushingDiseaseExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['DiabetesInsipidusExt']=function(input){const score=Math.round((0.18 + Number(input.di||1)*0.2 + Number(input.adh||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_neuro_ext167',function:'DiabetesInsipidusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SIADHext']=function(input){const score=Math.round((0.18 + Number(input.siadh||1)*0.2 + Number(input.hyponatremia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_neuro_ext167',function:'SIADHext',input,score,ts:new Date().toISOString()}};
module.exports.functions['HypothyroidNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.hypothyroid||1)*0.2 + Number(input.tsh||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_neuro_ext167',function:'HypothyroidNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HyperthyroidNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.hyperthyroid||1)*0.2 + Number(input.t4||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_neuro_ext167',function:'HyperthyroidNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HashimotoEnceph3Ext']=function(input){const score=Math.round((0.18 + Number(input.hashimoto3||1)*0.2 + Number(input.tpo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_neuro_ext167',function:'HashimotoEnceph3Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['AdrenalInsufficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.addison||1)*0.2 + Number(input.cortisolLow||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_neuro_ext167',function:'AdrenalInsufficiencyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.12.8.0
