// filepath: pcc/pcc_orphan_drugs_ext102/pcc_orphan_drugs_ext102_engine.js
module.exports.version='v3.40.40.0';
module.exports.module='pcc_orphan_drugs_ext102';
module.exports.functions={};
module.exports.functions['OrphanDesignationExt']=function(input){const score=Math.round((0.18 + Number(input.orDesig||1)*0.2 + Number(input.orDesigStatus||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_orphan_drugs_ext102',function:'OrphanDesignationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrphanAccessExt']=function(input){const score=Math.round((0.18 + Number(input.orAccess||1)*0.2 + Number(input.orAccessType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_orphan_drugs_ext102',function:'OrphanAccessExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrphanCostExt']=function(input){const score=Math.round((0.18 + Number(input.orCost||1)*0.2 + Number(input.orCostCover||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_orphan_drugs_ext102',function:'OrphanCostExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrphanTrialExt']=function(input){const score=Math.round((0.18 + Number(input.orTrial||1)*0.2 + Number(input.orTrialPhase||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_orphan_drugs_ext102',function:'OrphanTrialExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrphanSurrogateExt']=function(input){const score=Math.round((0.18 + Number(input.orSurrogate||1)*0.2 + Number(input.orSurrogateType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_orphan_drugs_ext102',function:'OrphanSurrogateExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrphanCompassionateExt']=function(input){const score=Math.round((0.18 + Number(input.orComp||1)*0.2 + Number(input.orCompType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_orphan_drugs_ext102',function:'OrphanCompassionateExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrphanRegistryExt']=function(input){const score=Math.round((0.18 + Number(input.orReg||1)*0.2 + Number(input.orRegSize||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_orphan_drugs_ext102',function:'OrphanRegistryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrphanPediatricExt']=function(input){const score=Math.round((0.18 + Number(input.orPed||1)*0.2 + Number(input.orPedAge||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_orphan_drugs_ext102',function:'OrphanPediatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrphanGeneticExt']=function(input){const score=Math.round((0.18 + Number(input.orGen||1)*0.2 + Number(input.orGenDisorder||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_orphan_drugs_ext102',function:'OrphanGeneticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrphanApprovalExt']=function(input){const score=Math.round((0.18 + Number(input.orAppr||1)*0.2 + Number(input.orApprPath||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_orphan_drugs_ext102',function:'OrphanApprovalExt',input,score,ts:new Date().toISOString()}};

// TS: v3.40.40.0
