// filepath: pcc/pcc_pediatric_surg_ext112/pcc_pediatric_surg_ext112_engine.js
module.exports.version='v3.222.0';
module.exports.module='pcc_pediatric_surg_ext112';
module.exports.functions={};
module.exports.functions['PediatricSchwannomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.222.0',module:'pcc_pediatric_surg_ext112',function:'PediatricSchwannomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVestibularSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.222.0',module:'pcc_pediatric_surg_ext112',function:'PediatricVestibularSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTrigeminalSchwannomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.222.0',module:'pcc_pediatric_surg_ext112',function:'PediatricTrigeminalSchwannomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNF2SxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.bevacizumab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.222.0',module:'pcc_pediatric_surg_ext112',function:'PediatricNF2SxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNF2vestibularSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.hearingPreserve||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.222.0',module:'pcc_pediatric_surg_ext112',function:'PediatricNF2vestibularSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeurofibromaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.222.0',module:'pcc_pediatric_surg_ext112',function:'PediatricNeurofibromaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMPNSTSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.222.0',module:'pcc_pediatric_surg_ext112',function:'PediatricMPNSTSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGlomusSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.preopEmbol||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.222.0',module:'pcc_pediatric_surg_ext112',function:'PediatricGlomusSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHemangioblastomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.222.0',module:'pcc_pediatric_surg_ext112',function:'PediatricHemangioblastomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChordomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.proton||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.222.0',module:'pcc_pediatric_surg_ext112',function:'PediatricChordomaSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.222.0
