// filepath: pcc/pcc_pediatric_neuro_ext116/pcc_pediatric_neuro_ext116_engine.js
module.exports.version='v3.226.0';
module.exports.module='pcc_pediatric_neuro_ext116';
module.exports.functions={};
module.exports.functions['PediatricCCMext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.familial||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.226.0',module:'pcc_pediatric_neuro_ext116',function:'PediatricCCMext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinalCCMext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.spinal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.226.0',module:'pcc_pediatric_neuro_ext116',function:'PediatricSpinalCCMext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAVMext2']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.spetzler||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.226.0',module:'pcc_pediatric_neuro_ext116',function:'PediatricAVMext2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinalAVMext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.spinal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.226.0',module:'pcc_pediatric_neuro_ext116',function:'PediatricSpinalAVMext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDuralFistulaExt2']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.dural||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.226.0',module:'pcc_pediatric_neuro_ext116',function:'PediatricDuralFistulaExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCCFistulaExt2']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ccf||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.226.0',module:'pcc_pediatric_neuro_ext116',function:'PediatricCCFistulaExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDVAext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.dva||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.226.0',module:'pcc_pediatric_neuro_ext116',function:'PediatricDVAext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCapillaryTelExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.tel||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.226.0',module:'pcc_pediatric_neuro_ext116',function:'PediatricCapillaryTelExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMixedMalExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.combined||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.226.0',module:'pcc_pediatric_neuro_ext116',function:'PediatricMixedMalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHHText']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.hht||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.226.0',module:'pcc_pediatric_neuro_ext116',function:'PediatricHHText',input,score,ts:new Date().toISOString()}};

// TS: v3.226.0
