// Auto_generated by gen_p3gv.py -- PCC v3.164.0
"use strict";
const TS = '2026-07-28T11:30:00Z';

function NeurodegenerativeDiseaseExt(input) { const score = Math.round((0.4+Number(input.progression||2)*0.04)*100)/100; return { version:'3.164.0', module:'pcc_neuro_ext65', function:"NeurodegenerativeDiseaseExt", input, score, ts: TS }; }

function MovementDisorderAssessmentExt(input) { const score = Math.round((0.3+Number(input.udrs_score||15)*0.02)*100)/100; return { version:'3.164.0', module:'pcc_neuro_ext65', function:"MovementDisorderAssessmentExt", input, score, ts: TS }; }

function DystoniaClassificationExt(input) { const score = Math.round((0.35+Number(input.twist_score||5)*0.04)*100)/100; return { version:'3.164.0', module:'pcc_neuro_ext65', function:"DystoniaClassificationExt", input, score, ts: TS }; }

function AtaxiaDiagnosticExt(input) { const score = Math.round((0.3+Number(input.icars_score||10)*0.02)*100)/100; return { version:'3.164.0', module:'pcc_neuro_ext65', function:"AtaxiaDiagnosticExt", input, score, ts: TS }; }

function ChoreaDisorderExt(input) { const score = Math.round((0.4+Number(input.uhdrs||5)*0.04)*100)/100; return { version:'3.164.0', module:'pcc_neuro_ext65', function:"ChoreaDisorderExt", input, score, ts: TS }; }

function TremorPhenotypeExt(input) { const score = Math.round((0.25+Number(input.frequency||4)*0.05)*100)/100; return { version:'3.164.0', module:'pcc_neuro_ext65', function:"TremorPhenotypeExt", input, score, ts: TS }; }

function TicDisorderAssessmentExt(input) { const score = Math.round((0.3+Number(input.ygtts_score||10)*0.03)*100)/100; return { version:'3.164.0', module:'pcc_neuro_ext65', function:"TicDisorderAssessmentExt", input, score, ts: TS }; }

function MyoclonusClassificationExt(input) { const score = Math.round((0.35+Number(input.frequency||5)*0.04)*100)/100; return { version:'3.164.0', module:'pcc_neuro_ext65', function:"MyoclonusClassificationExt", input, score, ts: TS }; }

function ParkinsonismAtypicalExt(input) { const score = Math.round((0.4+Number(input.atp||3)*0.05)*100)/100; return { version:'3.164.0', module:'pcc_neuro_ext65', function:"ParkinsonismAtypicalExt", input, score, ts: TS }; }

function NeuroacanthocytosisExt(input) { const score = Math.round((0.45+Number(input.hb||12)*0.03)*100)/100; return { version:'3.164.0', module:'pcc_neuro_ext65', function:"NeuroacanthocytosisExt", input, score, ts: TS }; }

module.exports = {
  NeurodegenerativeDiseaseExt,
  MovementDisorderAssessmentExt,
  DystoniaClassificationExt,
  AtaxiaDiagnosticExt,
  ChoreaDisorderExt,
  TremorPhenotypeExt,
  TicDisorderAssessmentExt,
  MyoclonusClassificationExt,
  ParkinsonismAtypicalExt,
  NeuroacanthocytosisExt,
};