// Auto_generated by gen_p3hg.py -- PCC v3.175.0
"use strict";
const TS = '2026-07-28T13:20:00Z';

function PediatricVestibularSurgeryExt(input) { const score = Math.round((0.4+Number(input.procedure_count||1)*0.1)*100)/100; return { version:'3.175.0', module:'pcc_pediatric_surg_ext65', function:"PediatricVestibularSurgeryExt", input, score, ts: TS }; }

function PediatricLabyrinthectomyExt(input) { const score = Math.round((0.5+Number(input.hearing_loss||30)*0.01)*100)/100; return { version:'3.175.0', module:'pcc_pediatric_surg_ext65', function:"PediatricLabyrinthectomyExt", input, score, ts: TS }; }

function PediatricEndolymphaticShuntExt(input) { const score = Math.round((0.4+Number(input.crises_freq||3)*0.08)*100)/100; return { version:'3.175.0', module:'pcc_pediatric_surg_ext65', function:"PediatricEndolymphaticShuntExt", input, score, ts: TS }; }

function PediatricAcousticNeuromaResectExt(input) { const score = Math.round((0.5+Number(input.size_mm||15)*0.02)*100)/100; return { version:'3.175.0', module:'pcc_pediatric_surg_ext65', function:"PediatricAcousticNeuromaResectExt", input, score, ts: TS }; }

function PediatricRetrosigmoidApproachExt(input) { const score = Math.round((0.4+Number(input.deficits||1)*0.15)*100)/100; return { version:'3.175.0', module:'pcc_pediatric_surg_ext65', function:"PediatricRetrosigmoidApproachExt", input, score, ts: TS }; }

function PediatricMiddleFossaApproachExt(input) { const score = Math.round((0.4+Number(input.hearing_preserved||0)*0.2)*100)/100; return { version:'3.175.0', module:'pcc_pediatric_surg_ext65', function:"PediatricMiddleFossaApproachExt", input, score, ts: TS }; }

function PediatricVestibularNerveSectionExt(input) { const score = Math.round((0.5+Number(input.crises||3)*0.1)*100)/100; return { version:'3.175.0', module:'pcc_pediatric_surg_ext65', function:"PediatricVestibularNerveSectionExt", input, score, ts: TS }; }

function PediatricHearingRehabExt(input) { const score = Math.round((0.3+Number(input.device_count||1)*0.15)*100)/100; return { version:'3.175.0', module:'pcc_pediatric_surg_ext65', function:"PediatricHearingRehabExt", input, score, ts: TS }; }

function PediatricBalanceTherapyExt(input) { const score = Math.round((0.3+Number(input.sessions||10)*0.04)*100)/100; return { version:'3.175.0', module:'pcc_pediatric_surg_ext65', function:"PediatricBalanceTherapyExt", input, score, ts: TS }; }

function PediatricPositionalTrainingExt(input) { const score = Math.round((0.3+Number(input.sessions||5)*0.08)*100)/100; return { version:'3.175.0', module:'pcc_pediatric_surg_ext65', function:"PediatricPositionalTrainingExt", input, score, ts: TS }; }

module.exports = {
  PediatricVestibularSurgeryExt,
  PediatricLabyrinthectomyExt,
  PediatricEndolymphaticShuntExt,
  PediatricAcousticNeuromaResectExt,
  PediatricRetrosigmoidApproachExt,
  PediatricMiddleFossaApproachExt,
  PediatricVestibularNerveSectionExt,
  PediatricHearingRehabExt,
  PediatricBalanceTherapyExt,
  PediatricPositionalTrainingExt,
};