// filepath: pcc/pcc_pediatric_neuro_ext105/pcc_pediatric_neuro_ext105_engine.js
module.exports.version='v3.215.0';
module.exports.module='pcc_pediatric_neuro_ext105';
module.exports.functions={};
module.exports.functions['PediatricSCISext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ais||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_neuro_ext105',function:'PediatricSCISext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTetraExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.c1||1)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_neuro_ext105',function:'PediatricTetraExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricParaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.t1||1)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_neuro_ext105',function:'PediatricParaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBSext']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.hemisection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_neuro_ext105',function:'PediatricBSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAnteriorExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.anterior||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_neuro_ext105',function:'PediatricAnteriorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCentralExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.central||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_neuro_ext105',function:'PediatricCentralExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCaudaEquinaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.lumbar||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_neuro_ext105',function:'PediatricCaudaEquinaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricConusExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.t12||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_neuro_ext105',function:'PediatricConusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinalShockExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.areflexia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_neuro_ext105',function:'PediatricSpinalShockExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricADRext']=function(input){const score=Math.round((0.15 + Number(input.age||8)*0.04 + Number(input.bp||180)*0.002 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_neuro_ext105',function:'PediatricADRext',input,score,ts:new Date().toISOString()}};

// TS: v3.215.0
