// filepath: pcc/pcc_infectious_ext100/pcc_infectious_ext100_engine.js
module.exports.version='v3.21.21.0';
module.exports.module='pcc_infectious_ext100';
module.exports.functions={};
module.exports.functions['InfSepsisExt']=function(input){const score=Math.round((0.18 + Number(input.infSepsis||1)*0.2 + Number(input.lactateInf||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_infectious_ext100',function:'InfSepsisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['InfMeningitisExt']=function(input){const score=Math.round((0.18 + Number(input.infMeningitis||1)*0.2 + Number(input.csfCell||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_infectious_ext100',function:'InfMeningitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['InfEncephalitisExt']=function(input){const score=Math.round((0.18 + Number(input.infEnceph||1)*0.2 + Number(input.csfEnceph||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_infectious_ext100',function:'InfEncephalitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['InfPneumoniaExt']=function(input){const score=Math.round((0.18 + Number(input.infPneumonia||1)*0.2 + Number(input.curb65||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_infectious_ext100',function:'InfPneumoniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['InfUTIext']=function(input){const score=Math.round((0.18 + Number(input.infUTI||1)*0.2 + Number(input.urineCulture||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_infectious_ext100',function:'InfUTIext',input,score,ts:new Date().toISOString()}};
module.exports.functions['InfCellulitisExt']=function(input){const score=Math.round((0.18 + Number(input.infCell||1)*0.2 + Number(input.cellExtent||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_infectious_ext100',function:'InfCellulitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['InfHIVadultExt']=function(input){const score=Math.round((0.18 + Number(input.infHIVa||1)*0.2 + Number(input.cd4Count||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_infectious_ext100',function:'InfHIVadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['InfTBadultExt']=function(input){const score=Math.round((0.18 + Number(input.infTBa||1)*0.2 + Number(input.tbSputum||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_infectious_ext100',function:'InfTBadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['InfHepBext']=function(input){const score=Math.round((0.18 + Number(input.infHepB||1)*0.2 + Number(input.hbvLoad||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_infectious_ext100',function:'InfHepBext',input,score,ts:new Date().toISOString()}};
module.exports.functions['InfHepCext']=function(input){const score=Math.round((0.18 + Number(input.infHepC||1)*0.2 + Number(input.hcvLoad||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_infectious_ext100',function:'InfHepCext',input,score,ts:new Date().toISOString()}};

// TS: v3.21.21.0
