// Auto-generated by gen_p3master.py -- PCC 3.280.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.280.0';

function X264AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x264) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_264', function: 'X264AssessmentExt', input, score, ts: TS };
}

function X264ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x264) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_264', function: 'X264ScoreExt', input, score, ts: TS };
}

function X264StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x264) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_264', function: 'X264StageExt', input, score, ts: TS };
}

function X264PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x264) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_264', function: 'X264PlanExt', input, score, ts: TS };
}

function X264RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x264) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_264', function: 'X264RiskExt', input, score, ts: TS };
}

function X264DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x264) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_264', function: 'X264DoseExt', input, score, ts: TS };
}

function X264FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x264) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_264', function: 'X264FrequencyExt', input, score, ts: TS };
}

function X264DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x264) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_264', function: 'X264DurationExt', input, score, ts: TS };
}

function X264FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x264) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_264', function: 'X264FollowupExt', input, score, ts: TS };
}

function X264OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x264) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_264', function: 'X264OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X264AssessmentExt,
  X264ScoreExt,
  X264StageExt,
  X264PlanExt,
  X264RiskExt,
  X264DoseExt,
  X264FrequencyExt,
  X264DurationExt,
  X264FollowupExt,
  X264OutcomeExt,
};