// filepath: pcc/pcc_pediatric_neuro_ext178/pcc_pediatric_neuro_ext178_engine.js
module.exports.version='v3.18.18.0';
module.exports.module='pcc_pediatric_neuro_ext178';
module.exports.functions={};
module.exports.functions['PediatricSCIext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSCI||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.18.18.0',module:'pcc_pediatric_neuro_ext178',function:'PediatricSCIext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinaBifidaNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pSBNeuro||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.18.18.0',module:'pcc_pediatric_neuro_ext178',function:'PediatricSpinaBifidaNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeuroBladderExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pNeuroBladder||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.18.18.0',module:'pcc_pediatric_neuro_ext178',function:'PediatricNeuroBladderExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeuroBowelExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pNeuroBowel||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.18.18.0',module:'pcc_pediatric_neuro_ext178',function:'PediatricNeuroBowelExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCIrehabExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSCIrehab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.18.18.0',module:'pcc_pediatric_neuro_ext178',function:'PediatricSCIrehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricADpedExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pADped||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.18.18.0',module:'pcc_pediatric_neuro_ext178',function:'PediatricADpedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPressureUlcerExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pPU||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.18.18.0',module:'pcc_pediatric_neuro_ext178',function:'PediatricPressureUlcerExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCIpsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pSCIpsy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.18.18.0',module:'pcc_pediatric_neuro_ext178',function:'PediatricSCIpsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCItransExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pSCItrans||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.18.18.0',module:'pcc_pediatric_neuro_ext178',function:'PediatricSCItransExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCIfollowExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSCIfollow||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.18.18.0',module:'pcc_pediatric_neuro_ext178',function:'PediatricSCIfollowExt',input,score,ts:new Date().toISOString()}};

// TS: v3.18.18.0
