-- coe_104 reverse
BEGIN;
DROP TABLE IF EXISTS coe_104_results CASCADE;
DROP TABLE IF EXISTS coe_104_orders  CASCADE;
DROP TABLE IF EXISTS coe_104_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_COE_104_up';
COMMIT;
