-- surg_103 reverse
BEGIN;
DROP TABLE IF EXISTS surg_103_results CASCADE;
DROP TABLE IF EXISTS surg_103_orders  CASCADE;
DROP TABLE IF EXISTS surg_103_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_SURG_103_up';
COMMIT;
