-- obg_101 reverse
BEGIN;
DROP TABLE IF EXISTS obg_101_results CASCADE;
DROP TABLE IF EXISTS obg_101_orders  CASCADE;
DROP TABLE IF EXISTS obg_101_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_OBG_101_up';
COMMIT;
