// filepath: pcc/pcc_hyperbaric_ext102/pcc_hyperbaric_ext102_engine.js
module.exports.version='v3.42.42.0';
module.exports.module='pcc_hyperbaric_ext102';
module.exports.functions={};
module.exports.functions['HBOTMainExt']=function(input){const score=Math.round((0.18 + Number(input.hbMain||1)*0.2 + Number(input.hbPressure||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.42.42.0',module:'pcc_hyperbaric_ext102',function:'HBOTMainExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HBOTWoundExt']=function(input){const score=Math.round((0.18 + Number(input.hbWound||1)*0.2 + Number(input.hbWoundStage||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.42.42.0',module:'pcc_hyperbaric_ext102',function:'HBOTWoundExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HBOTDCIext']=function(input){const score=Math.round((0.18 + Number(input.hbDCI||1)*0.2 + Number(input.hbDciSev||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.42.42.0',module:'pcc_hyperbaric_ext102',function:'HBOTDCIext',input,score,ts:new Date().toISOString()}};
module.exports.functions['HBOTCOext']=function(input){const score=Math.round((0.18 + Number(input.hbCO||1)*0.2 + Number(input.hbCoLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.42.42.0',module:'pcc_hyperbaric_ext102',function:'HBOTCOext',input,score,ts:new Date().toISOString()}};
module.exports.functions['HBOTArterialExt']=function(input){const score=Math.round((0.18 + Number(input.hbArt||1)*0.2 + Number(input.hbArtGas||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.42.42.0',module:'pcc_hyperbaric_ext102',function:'HBOTArterialExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HBOTRadiationExt']=function(input){const score=Math.round((0.18 + Number(input.hbRad||1)*0.2 + Number(input.hbRadDose||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.42.42.0',module:'pcc_hyperbaric_ext102',function:'HBOTRadiationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HBOTInfectionExt']=function(input){const score=Math.round((0.18 + Number(input.hbInf||1)*0.2 + Number(input.hbInfType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.42.42.0',module:'pcc_hyperbaric_ext102',function:'HBOTInfectionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HBOTBurnExt']=function(input){const score=Math.round((0.18 + Number(input.hbBurn||1)*0.2 + Number(input.hbBurnTBSA||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.42.42.0',module:'pcc_hyperbaric_ext102',function:'HBOTBurnExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HBOTSafetyExt']=function(input){const score=Math.round((0.18 + Number(input.hbSafe||1)*0.2 + Number(input.hbSafeCheck||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.42.42.0',module:'pcc_hyperbaric_ext102',function:'HBOTSafetyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HBOTChamberExt']=function(input){const score=Math.round((0.18 + Number(input.hbChamber||1)*0.2 + Number(input.hbChamberType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.42.42.0',module:'pcc_hyperbaric_ext102',function:'HBOTChamberExt',input,score,ts:new Date().toISOString()}};

// TS: v3.42.42.0
