-- anes_103 reverse
BEGIN;
DROP TABLE IF EXISTS anes_103_results CASCADE;
DROP TABLE IF EXISTS anes_103_orders  CASCADE;
DROP TABLE IF EXISTS anes_103_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ANES_103_up';
COMMIT;
