// filepath: pcc/pcc_pediatric_neuro_ext153/pcc_pediatric_neuro_ext153_engine.js
module.exports.version='v3.263.0';
module.exports.module='pcc_pediatric_neuro_ext153';
module.exports.functions={};
module.exports.functions['PediatricMigraineExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pMigraine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_pediatric_neuro_ext153',function:'PediatricMigraineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTTHext']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTTH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_pediatric_neuro_ext153',function:'PediatricTTHext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricClusterExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pCluster||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_pediatric_neuro_ext153',function:'PediatricClusterExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMOHext']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pMOH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_pediatric_neuro_ext153',function:'PediatricMOHext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChronicDailyExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pCDH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_pediatric_neuro_ext153',function:'PediatricChronicDailyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIIHext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pIIH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_pediatric_neuro_ext153',function:'PediatricIIHext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCSFleakExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pCSFleak||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_pediatric_neuro_ext153',function:'PediatricCSFleakExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPostTraumaticExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pPostTraumaHead||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_pediatric_neuro_ext153',function:'PediatricPostTraumaticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChiariExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pChiari||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_pediatric_neuro_ext153',function:'PediatricChiariExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainTumorHeadExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pTumorHead||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_pediatric_neuro_ext153',function:'PediatricBrainTumorHeadExt',input,score,ts:new Date().toISOString()}};

// TS: v3.263.0
