// filepath: pcc/pcc_pediatric_surg_ext181/pcc_pediatric_surg_ext181_engine.js
module.exports.version='v3.21.21.0';
module.exports.module='pcc_pediatric_surg_ext181';
module.exports.functions={};
module.exports.functions['PediatricMSSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMSSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_pediatric_surg_ext181',function:'PediatricMSSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMSRelapseTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMSRelapseTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_pediatric_surg_ext181',function:'PediatricMSRelapseTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricADEMTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pADEMTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_pediatric_surg_ext181',function:'PediatricADEMTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMOGTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pMOGTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_pediatric_surg_ext181',function:'PediatricMOGTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNMOSDTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pNMOSDTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_pediatric_surg_ext181',function:'PediatricNMOSDTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMSOpticTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMSOpticTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_pediatric_surg_ext181',function:'PediatricMSOpticTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMSSpinalTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMSSpinalTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_pediatric_surg_ext181',function:'PediatricMSSpinalTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMSBrainstemTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMSBrainstemTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_pediatric_surg_ext181',function:'PediatricMSBrainstemTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMSRehabTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMSRehabTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_pediatric_surg_ext181',function:'PediatricMSRehabTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMSCognitiveTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMSCognitiveTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_pediatric_surg_ext181',function:'PediatricMSCognitiveTxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.21.21.0
