// filepath: pcc/pcc_neuro_ext190/pcc_neuro_ext190_engine.js
module.exports.version='v3.19.19.0';
module.exports.module='pcc_neuro_ext190';
module.exports.functions={};
module.exports.functions['BrainTumorAdultGliomaExt']=function(input){const score=Math.round((0.18 + Number(input.gliomaAdult||1)*0.2 + Number(input.whoGrade||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.19.19.0',module:'pcc_neuro_ext190',function:'BrainTumorAdultGliomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MeningiomaAdultExt']=function(input){const score=Math.round((0.18 + Number(input.meningiomaAdult||1)*0.2 + Number(input.whoGrade||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.19.19.0',module:'pcc_neuro_ext190',function:'MeningiomaAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PituitaryAdenomaAdultExt']=function(input){const score=Math.round((0.18 + Number(input.pitAd||1)*0.2 + Number(input.horomone||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.19.19.0',module:'pcc_neuro_ext190',function:'PituitaryAdenomaAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AcousticNeuromaAdultExt']=function(input){const score=Math.round((0.18 + Number(input.acousticAdult||1)*0.2 + Number(input.hearingLoss||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.19.19.0',module:'pcc_neuro_ext190',function:'AcousticNeuromaAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CraniopharyngiomaAdultExt']=function(input){const score=Math.round((0.18 + Number(input.craniophAdult||1)*0.2 + Number(input.visual||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.19.19.0',module:'pcc_neuro_ext190',function:'CraniopharyngiomaAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GBMAdultExt']=function(input){const score=Math.round((0.18 + Number(input.gbmAdult||1)*0.2 + Number(input.mgmt||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.19.19.0',module:'pcc_neuro_ext190',function:'GBMAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BrainMetastasisAdultExt']=function(input){const score=Math.round((0.18 + Number(input.metsAdult||1)*0.2 + Number(input.primaryCancer||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.19.19.0',module:'pcc_neuro_ext190',function:'BrainMetastasisAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CNSLymphomaAdultExt']=function(input){const score=Math.round((0.18 + Number(input.cnsLymphomaAdult||1)*0.2 + Number(input.hivStatus||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.19.19.0',module:'pcc_neuro_ext190',function:'CNSLymphomaAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MedulloblastomaAdultExt']=function(input){const score=Math.round((0.18 + Number(input.medulloAdult||1)*0.2 + Number(input.molecular||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.19.19.0',module:'pcc_neuro_ext190',function:'MedulloblastomaAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EpendymomaAdultExt']=function(input){const score=Math.round((0.18 + Number(input.ependAdult||1)*0.2 + Number(input.location||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.19.19.0',module:'pcc_neuro_ext190',function:'EpendymomaAdultExt',input,score,ts:new Date().toISOString()}};

// TS: v3.19.19.0
