// filepath: pcc/pcc_pediatric_surg_ext133/pcc_pediatric_surg_ext133_engine.js
module.exports.version='v3.243.0';
module.exports.module='pcc_pediatric_surg_ext133';
module.exports.functions={};
module.exports.functions['PediatricPubertyBlockExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.gnrh||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.243.0',module:'pcc_pediatric_surg_ext133',function:'PediatricPubertyBlockExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHormoneRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.estrogen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.243.0',module:'pcc_pediatric_surg_ext133',function:'PediatricHormoneRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHypogonadismRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.testosterone||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.243.0',module:'pcc_pediatric_surg_ext133',function:'PediatricHypogonadismRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTurnerHRTtextExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.hrt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.243.0',module:'pcc_pediatric_surg_ext133',function:'PediatricTurnerHRTtextExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricKlinefelterHRTextExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.testosterone||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.243.0',module:'pcc_pediatric_surg_ext133',function:'PediatricKlinefelterHRTextExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPrecociousBlockerExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.gnrh||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.243.0',module:'pcc_pediatric_surg_ext133',function:'PediatricPrecociousBlockerExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDelayedHormonesExt']=function(input){const score=Math.round((0.18 + Number(input.age||15)*0.04 + Number(input.hormones||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.243.0',module:'pcc_pediatric_surg_ext133',function:'PediatricDelayedHormonesExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDSDsxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.243.0',module:'pcc_pediatric_surg_ext133',function:'PediatricDSDsxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGenderCounselingExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.counseling||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.243.0',module:'pcc_pediatric_surg_ext133',function:'PediatricGenderCounselingExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPubertyMonitorExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.monitor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.243.0',module:'pcc_pediatric_surg_ext133',function:'PediatricPubertyMonitorExt',input,score,ts:new Date().toISOString()}};

// TS: v3.243.0
