// filepath: pcc/pcc_neuro_ext196/pcc_neuro_ext196_engine.js
module.exports.version='v3.25.25.0';
module.exports.module='pcc_neuro_ext196';
module.exports.functions={};
module.exports.functions['DementiaAlzheimerAdultExt']=function(input){const score=Math.round((0.18 + Number(input.adAdult||1)*0.2 + Number(input.mmse||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_neuro_ext196',function:'DementiaAlzheimerAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VascularDementiaAdultExt']=function(input){const score=Math.round((0.18 + Number(input.vadAdult||1)*0.2 + Number(input.vascRisk||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_neuro_ext196',function:'VascularDementiaAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LewyBodyAdultExt']=function(input){const score=Math.round((0.18 + Number(input.lbdAdult||1)*0.2 + Number(input.fluctuations||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_neuro_ext196',function:'LewyBodyAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['FTDadultExt']=function(input){const score=Math.round((0.18 + Number(input.ftdAdult||1)*0.2 + Number(input.behaviorVariant||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_neuro_ext196',function:'FTDadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MCIadultExt']=function(input){const score=Math.round((0.18 + Number(input.mciAdult||1)*0.2 + Number(input.mciStage||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_neuro_ext196',function:'MCIadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PosteriorCorticalAdultExt']=function(input){const score=Math.round((0.18 + Number(input.pcaAdult||1)*0.2 + Number(input.visual||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_neuro_ext196',function:'PosteriorCorticalAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NPHadultExt']=function(input){const score=Math.round((0.18 + Number(input.nphAdult||1)*0.2 + Number(input.tapTest||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_neuro_ext196',function:'NPHadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AutoimmuneEncephalitisExt']=function(input){const score=Math.round((0.18 + Number(input.aeAdult||1)*0.2 + Number(input.abType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_neuro_ext196',function:'AutoimmuneEncephalitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CJDadultExt']=function(input){const score=Math.round((0.18 + Number(input.cjdAdult||1)*0.2 + Number(input.mriDwi||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_neuro_ext196',function:'CJDadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['DeliriumAdultExt']=function(input){const score=Math.round((0.18 + Number(input.deliriumAdult||1)*0.2 + Number(input.cam||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_neuro_ext196',function:'DeliriumAdultExt',input,score,ts:new Date().toISOString()}};

// TS: v3.25.25.0
