// filepath: pcc/pcc_pediatric_surg_ext166/pcc_pediatric_surg_ext166_engine.js
module.exports.version='v3.1.6.0';
module.exports.module='pcc_pediatric_surg_ext166';
module.exports.functions={};
module.exports.functions['PediatricThrombectomyTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pThrombectomyTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_surg_ext166',function:'PediatricThrombectomyTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeUnitTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeUnitTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_surg_ext166',function:'PediatricStrokeUnitTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeRehab2TxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeRehab2Tx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_surg_ext166',function:'PediatricStrokeRehab2TxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAntiplateletTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAntiplateletTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_surg_ext166',function:'PediatricAntiplateletTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAnticoagTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAnticoagTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_surg_ext166',function:'PediatricAnticoagTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLipidTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pLipidTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_surg_ext166',function:'PediatricLipidTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBPTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pBPTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_surg_ext166',function:'PediatricBPTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDMTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pDMTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_surg_ext166',function:'PediatricDMTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeLSTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pStrokeLSTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_surg_ext166',function:'PediatricStrokeLSTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeFUTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeFUTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_surg_ext166',function:'PediatricStrokeFUTxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.6.0
