// Auto-generated by gen_p3master.py -- PCC 3.296.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.296.0';

function X311AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x311) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_311', function: 'X311AssessmentExt', input, score, ts: TS };
}

function X311ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x311) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_311', function: 'X311ScoreExt', input, score, ts: TS };
}

function X311StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x311) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_311', function: 'X311StageExt', input, score, ts: TS };
}

function X311PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x311) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_311', function: 'X311PlanExt', input, score, ts: TS };
}

function X311RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x311) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_311', function: 'X311RiskExt', input, score, ts: TS };
}

function X311DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x311) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_311', function: 'X311DoseExt', input, score, ts: TS };
}

function X311FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x311) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_311', function: 'X311FrequencyExt', input, score, ts: TS };
}

function X311DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x311) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_311', function: 'X311DurationExt', input, score, ts: TS };
}

function X311FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x311) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_311', function: 'X311FollowupExt', input, score, ts: TS };
}

function X311OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x311) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_311', function: 'X311OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X311AssessmentExt,
  X311ScoreExt,
  X311StageExt,
  X311PlanExt,
  X311RiskExt,
  X311DoseExt,
  X311FrequencyExt,
  X311DurationExt,
  X311FollowupExt,
  X311OutcomeExt,
};