-- ============================================================
-- p1_11_wave20_force_rls_60_empty_down.sql
-- Wave 20 - Reverse: drop RLS + policy from 60 empty tables.
-- ============================================================
BEGIN;

DO $$
BEGIN
DROP POLICY IF EXISTS rls_cardiology_cath_reports_tenant_isolation ON cardiology_cath_reports;
ALTER TABLE cardiology_cath_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE cardiology_cath_reports NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_clinical_incidents_tenant_isolation ON clinical_incidents;
ALTER TABLE clinical_incidents DISABLE ROW LEVEL SECURITY;
ALTER TABLE clinical_incidents NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_cosmetic_cases_tenant_isolation ON cosmetic_cases;
ALTER TABLE cosmetic_cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE cosmetic_cases NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_cosmetic_consents_tenant_isolation ON cosmetic_consents;
ALTER TABLE cosmetic_consents DISABLE ROW LEVEL SECURITY;
ALTER TABLE cosmetic_consents NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_cosmetic_followups_tenant_isolation ON cosmetic_followups;
ALTER TABLE cosmetic_followups DISABLE ROW LEVEL SECURITY;
ALTER TABLE cosmetic_followups NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_cosmetic_photos_tenant_isolation ON cosmetic_photos;
ALTER TABLE cosmetic_photos DISABLE ROW LEVEL SECURITY;
ALTER TABLE cosmetic_photos NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_dental_images_tenant_isolation ON dental_images;
ALTER TABLE dental_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE dental_images NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_dental_periodontal_exams_tenant_isolation ON dental_periodontal_exams;
ALTER TABLE dental_periodontal_exams DISABLE ROW LEVEL SECURITY;
ALTER TABLE dental_periodontal_exams NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_doctor_inventory_request_items_tenant_isolation ON doctor_inventory_request_items;
ALTER TABLE doctor_inventory_request_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE doctor_inventory_request_items NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_doctor_inventory_requests_tenant_isolation ON doctor_inventory_requests;
ALTER TABLE doctor_inventory_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE doctor_inventory_requests NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_emar_administrations_tenant_isolation ON emar_administrations;
ALTER TABLE emar_administrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE emar_administrations NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_emar_orders_tenant_isolation ON emar_orders;
ALTER TABLE emar_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE emar_orders NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_employee_exposures_tenant_isolation ON employee_exposures;
ALTER TABLE employee_exposures DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_exposures NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_finance_report_snapshots_tenant_isolation ON finance_report_snapshots;
ALTER TABLE finance_report_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_report_snapshots NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_finance_tax_declarations_tenant_isolation ON finance_tax_declarations;
ALTER TABLE finance_tax_declarations DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_tax_declarations NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_hand_hygiene_audits_tenant_isolation ON hand_hygiene_audits;
ALTER TABLE hand_hygiene_audits DISABLE ROW LEVEL SECURITY;
ALTER TABLE hand_hygiene_audits NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_hr_advances_tenant_isolation ON hr_advances;
ALTER TABLE hr_advances DISABLE ROW LEVEL SECURITY;
ALTER TABLE hr_advances NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_hr_attendance_tenant_isolation ON hr_attendance;
ALTER TABLE hr_attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE hr_attendance NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_hr_credentialing_tenant_isolation ON hr_credentialing;
ALTER TABLE hr_credentialing DISABLE ROW LEVEL SECURITY;
ALTER TABLE hr_credentialing NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_hr_employee_custody_tenant_isolation ON hr_employee_custody;
ALTER TABLE hr_employee_custody DISABLE ROW LEVEL SECURITY;
ALTER TABLE hr_employee_custody NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_hr_employee_documents_tenant_isolation ON hr_employee_documents;
ALTER TABLE hr_employee_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE hr_employee_documents NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_hr_leaves_tenant_isolation ON hr_leaves;
ALTER TABLE hr_leaves DISABLE ROW LEVEL SECURITY;
ALTER TABLE hr_leaves NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_hr_nitaqat_records_tenant_isolation ON hr_nitaqat_records;
ALTER TABLE hr_nitaqat_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE hr_nitaqat_records NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_icu_daily_goals_tenant_isolation ON icu_daily_goals;
ALTER TABLE icu_daily_goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE icu_daily_goals NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_incident_reports_tenant_isolation ON incident_reports;
ALTER TABLE incident_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE incident_reports NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_infection_outbreaks_tenant_isolation ON infection_outbreaks;
ALTER TABLE infection_outbreaks DISABLE ROW LEVEL SECURITY;
ALTER TABLE infection_outbreaks NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_infection_surveillance_tenant_isolation ON infection_surveillance;
ALTER TABLE infection_surveillance DISABLE ROW LEVEL SECURITY;
ALTER TABLE infection_surveillance NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_inventory_tenant_isolation ON inventory;
ALTER TABLE inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_inventory_dept_request_items_tenant_isolation ON inventory_dept_request_items;
ALTER TABLE inventory_dept_request_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_dept_request_items NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_inventory_dept_requests_tenant_isolation ON inventory_dept_requests;
ALTER TABLE inventory_dept_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_dept_requests NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_inventory_issue_items_tenant_isolation ON inventory_issue_items;
ALTER TABLE inventory_issue_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_issue_items NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_inventory_issue_to_dept_tenant_isolation ON inventory_issue_to_dept;
ALTER TABLE inventory_issue_to_dept DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_issue_to_dept NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_inventory_opening_balances_tenant_isolation ON inventory_opening_balances;
ALTER TABLE inventory_opening_balances DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_opening_balances NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_inventory_purchase_items_tenant_isolation ON inventory_purchase_items;
ALTER TABLE inventory_purchase_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_purchase_items NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_inventory_purchases_tenant_isolation ON inventory_purchases;
ALTER TABLE inventory_purchases DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_purchases NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_inventory_stock_count_tenant_isolation ON inventory_stock_count;
ALTER TABLE inventory_stock_count DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_stock_count NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_lab_loinc_codes_tenant_isolation ON lab_loinc_codes;
ALTER TABLE lab_loinc_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE lab_loinc_codes NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_lab_microbiology_tenant_isolation ON lab_microbiology;
ALTER TABLE lab_microbiology DISABLE ROW LEVEL SECURITY;
ALTER TABLE lab_microbiology NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_maintenance_equipment_tenant_isolation ON maintenance_equipment;
ALTER TABLE maintenance_equipment DISABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_equipment NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_maintenance_pm_schedules_tenant_isolation ON maintenance_pm_schedules;
ALTER TABLE maintenance_pm_schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_pm_schedules NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_maintenance_work_orders_tenant_isolation ON maintenance_work_orders;
ALTER TABLE maintenance_work_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_work_orders NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_medical_certificates_tenant_isolation ON medical_certificates;
ALTER TABLE medical_certificates DISABLE ROW LEVEL SECURITY;
ALTER TABLE medical_certificates NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_medication_reconciliations_tenant_isolation ON medication_reconciliations;
ALTER TABLE medication_reconciliations DISABLE ROW LEVEL SECURITY;
ALTER TABLE medication_reconciliations NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_mortuary_cases_tenant_isolation ON mortuary_cases;
ALTER TABLE mortuary_cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE mortuary_cases NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_nphies_claim_status_inquiry_tenant_isolation ON nphies_claim_status_inquiry;
ALTER TABLE nphies_claim_status_inquiry DISABLE ROW LEVEL SECURITY;
ALTER TABLE nphies_claim_status_inquiry NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_nphies_remittance_advice_tenant_isolation ON nphies_remittance_advice;
ALTER TABLE nphies_remittance_advice DISABLE ROW LEVEL SECURITY;
ALTER TABLE nphies_remittance_advice NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_pediatric_immunizations_tenant_isolation ON pediatric_immunizations;
ALTER TABLE pediatric_immunizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE pediatric_immunizations NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_pharmacy_opening_balances_tenant_isolation ON pharmacy_opening_balances;
ALTER TABLE pharmacy_opening_balances DISABLE ROW LEVEL SECURITY;
ALTER TABLE pharmacy_opening_balances NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_pharmacy_purchase_items_tenant_isolation ON pharmacy_purchase_items;
ALTER TABLE pharmacy_purchase_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE pharmacy_purchase_items NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_pharmacy_purchase_orders_tenant_isolation ON pharmacy_purchase_orders;
ALTER TABLE pharmacy_purchase_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE pharmacy_purchase_orders NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_pharmacy_suppliers_tenant_isolation ON pharmacy_suppliers;
ALTER TABLE pharmacy_suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE pharmacy_suppliers NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_quality_incidents_tenant_isolation ON quality_incidents;
ALTER TABLE quality_incidents DISABLE ROW LEVEL SECURITY;
ALTER TABLE quality_incidents NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_quality_kpis_tenant_isolation ON quality_kpis;
ALTER TABLE quality_kpis DISABLE ROW LEVEL SECURITY;
ALTER TABLE quality_kpis NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_quality_patient_satisfaction_tenant_isolation ON quality_patient_satisfaction;
ALTER TABLE quality_patient_satisfaction DISABLE ROW LEVEL SECURITY;
ALTER TABLE quality_patient_satisfaction NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_queue_advertisements_tenant_isolation ON queue_advertisements;
ALTER TABLE queue_advertisements DISABLE ROW LEVEL SECURITY;
ALTER TABLE queue_advertisements NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_social_work_cases_tenant_isolation ON social_work_cases;
ALTER TABLE social_work_cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE social_work_cases NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_tenant_settings_tenant_isolation ON tenant_settings;
ALTER TABLE tenant_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_settings NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_transport_requests_tenant_isolation ON transport_requests;
ALTER TABLE transport_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_requests NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_vendors_tenant_isolation ON vendors;
ALTER TABLE vendors DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendors NO FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_zatca_credit_notes_tenant_isolation ON zatca_credit_notes;
ALTER TABLE zatca_credit_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE zatca_credit_notes NO FORCE ROW LEVEL SECURITY;
END $$;

COMMIT;
