-- icu_104 reverse
BEGIN;
DROP TABLE IF EXISTS icu_104_results CASCADE;
DROP TABLE IF EXISTS icu_104_orders  CASCADE;
DROP TABLE IF EXISTS icu_104_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ICU_104_up';
COMMIT;
