// filepath: pcc/pcc_neuro_ext192/pcc_neuro_ext192_engine.js
module.exports.version='v3.21.21.0';
module.exports.module='pcc_neuro_ext192';
module.exports.functions={};
module.exports.functions['MultipleSclerosisAdultExt']=function(input){const score=Math.round((0.18 + Number(input.msAdult||1)*0.2 + Number(input.edss||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_neuro_ext192',function:'MultipleSclerosisAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MSRelapseAdultExt']=function(input){const score=Math.round((0.18 + Number(input.msRelapse||1)*0.2 + Number(input.relapse||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_neuro_ext192',function:'MSRelapseAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MSProgressiveAdultExt']=function(input){const score=Math.round((0.18 + Number(input.msProg||1)*0.2 + Number(input.progression||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_neuro_ext192',function:'MSProgressiveAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PPMSadultExt']=function(input){const score=Math.round((0.18 + Number(input.ppmsAdult||1)*0.2 + Number(input.primaryProg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_neuro_ext192',function:'PPMSadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SPMSadultExt']=function(input){const score=Math.round((0.18 + Number(input.spmsAdult||1)*0.2 + Number(input.secondaryProg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_neuro_ext192',function:'SPMSadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MSOpticNeuritisExt']=function(input){const score=Math.round((0.18 + Number(input.msOptic||1)*0.2 + Number(input.visualAc||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_neuro_ext192',function:'MSOpticNeuritisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MSPregnancyExt']=function(input){const score=Math.round((0.18 + Number(input.msPreg||1)*0.2 + Number(input.gestAge||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_neuro_ext192',function:'MSPregnancyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MSFamilyPlanningExt']=function(input){const score=Math.round((0.18 + Number(input.msFP||1)*0.2 + Number(input.dmtType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_neuro_ext192',function:'MSFamilyPlanningExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MSRehabAdultExt']=function(input){const score=Math.round((0.18 + Number(input.msRehabAdult||1)*0.2 + Number(input.fatigue||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_neuro_ext192',function:'MSRehabAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MSCognitiveAdultExt']=function(input){const score=Math.round((0.18 + Number(input.msCogAdult||1)*0.2 + Number(input.cognitive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_neuro_ext192',function:'MSCognitiveAdultExt',input,score,ts:new Date().toISOString()}};

// TS: v3.21.21.0
