// filepath: pcc/pcc_ophth_ext100/pcc_ophth_ext100_engine.js
module.exports.version='v3.23.23.0';
module.exports.module='pcc_ophth_ext100';
module.exports.functions={};
module.exports.functions['OphthCataractExt']=function(input){const score=Math.round((0.18 + Number(input.ophCataract||1)*0.2 + Number(input.ophGrade||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_ophth_ext100',function:'OphthCataractExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphthGlaucomaExt']=function(input){const score=Math.round((0.18 + Number(input.ophGlaucoma||1)*0.2 + Number(input.iopLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_ophth_ext100',function:'OphthGlaucomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphthRetinaExt']=function(input){const score=Math.round((0.18 + Number(input.ophRetina||1)*0.2 + Number(input.retinalThick||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_ophth_ext100',function:'OphthRetinaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphthDiabeticExt']=function(input){const score=Math.round((0.18 + Number(input.ophDiabetic||1)*0.2 + Number(input.drGrade||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_ophth_ext100',function:'OphthDiabeticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphthAMDext']=function(input){const score=Math.round((0.18 + Number(input.ophAMD||1)*0.2 + Number(input.amdType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_ophth_ext100',function:'OphthAMDext',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphthUveitisExt']=function(input){const score=Math.round((0.18 + Number(input.ophUveitis||1)*0.2 + Number(input.uveitisLoc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_ophth_ext100',function:'OphthUveitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphthCorneaExt']=function(input){const score=Math.round((0.18 + Number(input.ophCornea||1)*0.2 + Number(input.corneaThick||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_ophth_ext100',function:'OphthCorneaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphthPediatricExt']=function(input){const score=Math.round((0.18 + Number(input.ophPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_ophth_ext100',function:'OphthPediatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphthTraumaExt']=function(input){const score=Math.round((0.18 + Number(input.ophTrauma||1)*0.2 + Number(input.traumaZone||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_ophth_ext100',function:'OphthTraumaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphthNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.ophNeuro||1)*0.2 + Number(input.opticNerve||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_ophth_ext100',function:'OphthNeuroExt',input,score,ts:new Date().toISOString()}};

// TS: v3.23.23.0
