-- pcc_neuro_ext62 v3.161.0 migration up
CREATE TABLE IF NOT EXISTS pcc_neuro_ext62 (
  id BIGINT IDENTITY PRIMARY KEY,
  tenant_id NVARCHAR(64) NOT NULL,
  fn NVARCHAR(128),
  payload NVARCHAR(MAX),
  ts DATETIME2 DEFAULT SYSUTCDATETIME()
);
