// filepath: pcc/pcc_pediatric_surg_ext125/pcc_pediatric_surg_ext125_engine.js
module.exports.version='v3.235.0';
module.exports.module='pcc_pediatric_surg_ext125';
module.exports.functions={};
module.exports.functions['PediatricCVSTAnticoagExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.heparin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_surg_ext125',function:'PediatricCVSTAnticoagExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSagittalThrombAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.heparin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_surg_ext125',function:'PediatricSagittalThrombAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTransverseThrombAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.heparin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_surg_ext125',function:'PediatricTransverseThrombAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSigmoidThrombAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.heparin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_surg_ext125',function:'PediatricSigmoidThrombAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCavernousThrombAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.heparin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_surg_ext125',function:'PediatricCavernousThrombAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDeepVenousThrombAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.heparin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_surg_ext125',function:'PediatricDeepVenousThrombAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCorticalVeinAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.heparin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_surg_ext125',function:'PediatricCorticalVeinAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSepticThrombAbsExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.abx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_surg_ext125',function:'PediatricSepticThrombAbsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAsepticThrombAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.heparin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_surg_ext125',function:'PediatricAsepticThrombAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPregnancyThrombAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||15)*0.04 + Number(input.lmwh||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_surg_ext125',function:'PediatricPregnancyThrombAntiExt',input,score,ts:new Date().toISOString()}};

// TS: v3.235.0
