// Auto_generated by gen_p3hh.py -- PCC v3.176.0
"use strict";
const TS = '2026-07-28T13:30:00Z';

function SpinalMuscularAtrophyExt(input) { const score = Math.round((0.4+Number(input.motor_score||10)*0.04)*100)/100; return { version:'3.176.0', module:'pcc_neuro_ext77', function:"SpinalMuscularAtrophyExt", input, score, ts: TS }; }

function SBMAExt(input) { const score = Math.round((0.4+Number(input.repeats||40)*0.008)*100)/100; return { version:'3.176.0', module:'pcc_neuro_ext77', function:"SBMAExt", input, score, ts: TS }; }

function FSHDExt(input) { const score = Math.round((0.35+Number(input.fshd_score||3)*0.08)*100)/100; return { version:'3.176.0', module:'pcc_neuro_ext77', function:"FSHDExt", input, score, ts: TS }; }

function MyotonicDystrophyExt(input) { const score = Math.round((0.4+Number(input.repeats||50)*0.005)*100)/100; return { version:'3.176.0', module:'pcc_neuro_ext77', function:"MyotonicDystrophyExt", input, score, ts: TS }; }

function LimbGirdleMuscularDystrophyExt(input) { const score = Math.round((0.4+Number(input.lgmd_score||3)*0.08)*100)/100; return { version:'3.176.0', module:'pcc_neuro_ext77', function:"LimbGirdleMuscularDystrophyExt", input, score, ts: TS }; }

function FacioscapulohumeralExt(input) { const score = Math.round((0.35+Number(input.fsh_score||3)*0.08)*100)/100; return { version:'3.176.0', module:'pcc_neuro_ext77', function:"FacioscapulohumeralExt", input, score, ts: TS }; }

function InclusionBodyMyositisExt(input) { const score = Math.round((0.4+Number(input.weak_score||3)*0.1)*100)/100; return { version:'3.176.0', module:'pcc_neuro_ext77', function:"InclusionBodyMyositisExt", input, score, ts: TS }; }

function DermatomyositisExt(input) { const score = Math.round((0.4+Number(input.skin_score||3)*0.1)*100)/100; return { version:'3.176.0', module:'pcc_neuro_ext77', function:"DermatomyositisExt", input, score, ts: TS }; }

function PolymyositisExt(input) { const score = Math.round((0.4+Number(input.cpk_level||500)*0.0005)*100)/100; return { version:'3.176.0', module:'pcc_neuro_ext77', function:"PolymyositisExt", input, score, ts: TS }; }

function MyastheniaGravisMyopathyExt(input) { const score = Math.round((0.4+Number(input.achr_pct||0)*0.01)*100)/100; return { version:'3.176.0', module:'pcc_neuro_ext77', function:"MyastheniaGravisMyopathyExt", input, score, ts: TS }; }

module.exports = {
  SpinalMuscularAtrophyExt,
  SBMAExt,
  FSHDExt,
  MyotonicDystrophyExt,
  LimbGirdleMuscularDystrophyExt,
  FacioscapulohumeralExt,
  InclusionBodyMyositisExt,
  DermatomyositisExt,
  PolymyositisExt,
  MyastheniaGravisMyopathyExt,
};