// Auto-generated by gen_p3he.py -- PCC v3.173.0
"use strict";
const TS = '2026-07-28T13:00:00Z';

function PeripheralNeuropathyExt(input) { const score = Math.round((0.3+Number(input.ncs_amp||3)*0.06)*100)/100; return { version:'3.173.0', module:'pcc_neuro_ext74', function:'PeripheralNeuropathyExt', input, score, ts: TS }; }

function CIDPExt(input) { const score = Math.round((0.4+Number(input.efns_score||4)*0.06)*100)/100; return { version:'3.173.0', module:'pcc_neuro_ext74', function:'CIDPExt', input, score, ts: TS }; }

function GuillainBarreExt(input) { const score = Math.round((0.45+Number(input.egs_score||3)*0.08)*100)/100; return { version:'3.173.0', module:'pcc_neuro_ext74', function:'GuillainBarreExt', input, score, ts: TS }; }

function CIDPVariantExt(input) { const score = Math.round((0.4+Number(input.mfs||0)*0.15)*100)/100; return { version:'3.173.0', module:'pcc_neuro_ext74', function:'CIDPVariantExt', input, score, ts: TS }; }

function DiabeticNeuropathyExt(input) { const score = Math.round((0.3+Number(input.duration||10)*0.04)*100)/100; return { version:'3.173.0', module:'pcc_neuro_ext74', function:'DiabeticNeuropathyExt', input, score, ts: TS }; }

function CharcotMarieToothExt(input) { const score = Math.round((0.4+Number(input.cmt_score||2)*0.08)*100)/100; return { version:'3.173.0', module:'pcc_neuro_ext74', function:'CharcotMarieToothExt', input, score, ts: TS }; }

function SmallFiberNeuropathyExt(input) { const score = Math.round((0.35+Number(input.sfn_score||5)*0.06)*100)/100; return { version:'3.173.0', module:'pcc_neuro_ext74', function:'SmallFiberNeuropathyExt', input, score, ts: TS }; }

function AutonomicNeuropathyExt(input) { const score = Math.round((0.4+Number(input.comp_score||3)*0.08)*100)/100; return { version:'3.173.0', module:'pcc_neuro_ext74', function:'AutonomicNeuropathyExt', input, score, ts: TS }; }

function HereditaryNeuropathyExt(input) { const score = Math.round((0.35+Number(input.gene||1)*0.1)*100)/100; return { version:'3.173.0', module:'pcc_neuro_ext74', function:'HereditaryNeuropathyExt', input, score, ts: TS }; }

function VasculiticNeuropathyExt(input) { const score = Math.round((0.4+Number(input.vessel_count||2)*0.1)*100)/100; return { version:'3.173.0', module:'pcc_neuro_ext74', function:'VasculiticNeuropathyExt', input, score, ts: TS }; }

module.exports = {
  PeripheralNeuropathyExt,
  CIDPExt,
  GuillainBarreExt,
  CIDPVariantExt,
  DiabeticNeuropathyExt,
  CharcotMarieToothExt,
  SmallFiberNeuropathyExt,
  AutonomicNeuropathyExt,
  HereditaryNeuropathyExt,
  VasculiticNeuropathyExt,
};