// filepath: pcc/pcc_pediatric_neuro_ext160/pcc_pediatric_neuro_ext160_engine.js
module.exports.version='v3.12.12.0';
module.exports.module='pcc_pediatric_neuro_ext160';
module.exports.functions={};
module.exports.functions['PediatricDMDchildExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pDMD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_neuro_ext160',function:'PediatricDMDchildExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBMDchildExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pBMD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_neuro_ext160',function:'PediatricBMDchildExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLGMDchildExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pLGMD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_neuro_ext160',function:'PediatricLGMDchildExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFSHDchildExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pFSHD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_neuro_ext160',function:'PediatricFSHDchildExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOPMDchildExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pOPMD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_neuro_ext160',function:'PediatricOPMDchildExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEDMDchildExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pEDMD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_neuro_ext160',function:'PediatricEDMDchildExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDM1childExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pDM1||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_neuro_ext160',function:'PediatricDM1childExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCongMyopExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pCongMyop||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_neuro_ext160',function:'PediatricCongMyopExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMitoMyopExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pMitoMyop||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_neuro_ext160',function:'PediatricMitoMyopExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPompeExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pPompe||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_neuro_ext160',function:'PediatricPompeExt',input,score,ts:new Date().toISOString()}};

// TS: v3.12.12.0
