// filepath: pcc/pcc_pediatric_neuro_ext168/pcc_pediatric_neuro_ext168_engine.js
module.exports.version='v3.1.8.0';
module.exports.module='pcc_pediatric_neuro_ext168';
module.exports.functions={};
module.exports.functions['PediatricCIMText']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pCIMT||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.8.0',module:'pcc_pediatric_neuro_ext168',function:'PediatricCIMText',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCPRehabExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pCPRehab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.8.0',module:'pcc_pediatric_neuro_ext168',function:'PediatricCPRehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeurorehabExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pNeurorehab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.8.0',module:'pcc_pediatric_neuro_ext168',function:'PediatricNeurorehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRobotRehabExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pRobotRehab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.8.0',module:'pcc_pediatric_neuro_ext168',function:'PediatricRobotRehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVRrehabExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pVR||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.8.0',module:'pcc_pediatric_neuro_ext168',function:'PediatricVRrehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTelerehabExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTelerehab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.8.0',module:'pcc_pediatric_neuro_ext168',function:'PediatricTelerehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpasticityMgtExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pSpast||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.8.0',module:'pcc_pediatric_neuro_ext168',function:'PediatricSpasticityMgtExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDysphagiaMgtExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pDysph||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.8.0',module:'pcc_pediatric_neuro_ext168',function:'PediatricDysphagiaMgtExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricConstraintExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pConstraint||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.8.0',module:'pcc_pediatric_neuro_ext168',function:'PediatricConstraintExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHandTherapyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pHandTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.8.0',module:'pcc_pediatric_neuro_ext168',function:'PediatricHandTherapyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.8.0
