// Auto-generated by gen_p3master.py -- PCC 3.316.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.316.0';

function X370AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x370) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_370', function: 'X370AssessmentExt', input, score, ts: TS };
}

function X370ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x370) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_370', function: 'X370ScoreExt', input, score, ts: TS };
}

function X370StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x370) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_370', function: 'X370StageExt', input, score, ts: TS };
}

function X370PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x370) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_370', function: 'X370PlanExt', input, score, ts: TS };
}

function X370RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x370) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_370', function: 'X370RiskExt', input, score, ts: TS };
}

function X370DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x370) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_370', function: 'X370DoseExt', input, score, ts: TS };
}

function X370FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x370) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_370', function: 'X370FrequencyExt', input, score, ts: TS };
}

function X370DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x370) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_370', function: 'X370DurationExt', input, score, ts: TS };
}

function X370FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x370) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_370', function: 'X370FollowupExt', input, score, ts: TS };
}

function X370OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x370) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_370', function: 'X370OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X370AssessmentExt,
  X370ScoreExt,
  X370StageExt,
  X370PlanExt,
  X370RiskExt,
  X370DoseExt,
  X370FrequencyExt,
  X370DurationExt,
  X370FollowupExt,
  X370OutcomeExt,
};