// filepath: pcc/pcc_end_of_life_ext102/pcc_end_of_life_ext102_engine.js
module.exports.version='v3.52.52.0';
module.exports.module='pcc_end_of_life_ext102';
module.exports.functions={};
module.exports.functions['EOLCareExt']=function(input){const score=Math.round((0.18 + Number(input.elCar||1)*0.2 + Number(input.elCarType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_end_of_life_ext102',function:'EOLCareExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EOLDNRExt']=function(input){const score=Math.round((0.18 + Number(input.elDNR||1)*0.2 + Number(input.elDNRtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_end_of_life_ext102',function:'EOLDNRExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EOLAdvanceExt']=function(input){const score=Math.round((0.18 + Number(input.elAdv||1)*0.2 + Number(input.elAdvType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_end_of_life_ext102',function:'EOLAdvanceExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EOLGoalsExt']=function(input){const score=Math.round((0.18 + Number(input.elGoal||1)*0.2 + Number(input.elGoalType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_end_of_life_ext102',function:'EOLGoalsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EOLComfortExt']=function(input){const score=Math.round((0.18 + Number(input.elCom||1)*0.2 + Number(input.elComScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_end_of_life_ext102',function:'EOLComfortExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EOLWithdrawalExt']=function(input){const score=Math.round((0.18 + Number(input.elWdr||1)*0.2 + Number(input.elWdrType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_end_of_life_ext102',function:'EOLWithdrawalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EOLFamilyMeetExt']=function(input){const score=Math.round((0.18 + Number(input.elFam||1)*0.2 + Number(input.elFamScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_end_of_life_ext102',function:'EOLFamilyMeetExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EOLSpiritualExt']=function(input){const score=Math.round((0.18 + Number(input.elSpi||1)*0.2 + Number(input.elSpiScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_end_of_life_ext102',function:'EOLSpiritualExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EOLGriefExt']=function(input){const score=Math.round((0.18 + Number(input.elGrief||1)*0.2 + Number(input.elGriefScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_end_of_life_ext102',function:'EOLGriefExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EOLDeathExt']=function(input){const score=Math.round((0.18 + Number(input.elDeath||1)*0.2 + Number(input.elDeathType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.52.52.0',module:'pcc_end_of_life_ext102',function:'EOLDeathExt',input,score,ts:new Date().toISOString()}};

// TS: v3.52.52.0
