// filepath: pcc/pcc_pediatric_surg_ext126/pcc_pediatric_surg_ext126_engine.js
module.exports.version='v3.236.0';
module.exports.module='pcc_pediatric_surg_ext126';
module.exports.functions={};
module.exports.functions['PediatricAngiitisImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_surg_ext126',function:'PediatricAngiitisImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPACNSImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cyclophosphamide||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_surg_ext126',function:'PediatricPACNSImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCNSVImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_surg_ext126',function:'PediatricCNSVImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRCVSnimoExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.nimodipine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_surg_ext126',function:'PediatricRCVSnimoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCallFlemingNimoExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.nimodipine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_surg_ext126',function:'PediatricCallFlemingNimoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSusacImmunoExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_surg_ext126',function:'PediatricSusacImmunoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCADASILsupportExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.antiplatelet||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_surg_ext126',function:'PediatricCADASILsupportExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHITargatrobanExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.argatroban||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_surg_ext126',function:'PediatricHITargatrobanExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDICtransfusionExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.transfusion||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_surg_ext126',function:'PediatricDICtransfusionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTTPplasmaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.plasmaExchange||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_surg_ext126',function:'PediatricTTPplasmaExt',input,score,ts:new Date().toISOString()}};

// TS: v3.236.0
