-- sup_107 reverse
BEGIN;
DROP TABLE IF EXISTS sup_107_results CASCADE;
DROP TABLE IF EXISTS sup_107_orders  CASCADE;
DROP TABLE IF EXISTS sup_107_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_SUP_107_up';
COMMIT;
