// filepath: pcc/pcc_spine_surgery_ext102/pcc_spine_surgery_ext102_engine.js
module.exports.version='v3.61.61.0';
module.exports.module='pcc_spine_surgery_ext102';
module.exports.functions={};
module.exports.functions['SSxGenExt']=function(input){const score=Math.round((0.18 + Number(input.spGen||1)*0.2 + Number(input.spGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_spine_surgery_ext102',function:'SSxGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SSxDiscExt']=function(input){const score=Math.round((0.18 + Number(input.spDisc||1)*0.2 + Number(input.spDiscLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_spine_surgery_ext102',function:'SSxDiscExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SSxStenExt']=function(input){const score=Math.round((0.18 + Number(input.spSten||1)*0.2 + Number(input.spStenScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_spine_surgery_ext102',function:'SSxStenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SSxSpondExt']=function(input){const score=Math.round((0.18 + Number(input.spSpon||1)*0.2 + Number(input.spSponGrade||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_spine_surgery_ext102',function:'SSxSpondExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SSxFracExt']=function(input){const score=Math.round((0.18 + Number(input.spFrac||1)*0.2 + Number(input.spFracTLICS||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_spine_surgery_ext102',function:'SSxFracExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SSxTumorExt']=function(input){const score=Math.round((0.18 + Number(input.spTum||1)*0.2 + Number(input.spTumType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_spine_surgery_ext102',function:'SSxTumorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SSxDeformExt']=function(input){const score=Math.round((0.18 + Number(input.spDef||1)*0.2 + Number(input.spDefType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_spine_surgery_ext102',function:'SSxDeformExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SSxFusionExt']=function(input){const score=Math.round((0.18 + Number(input.spFus||1)*0.2 + Number(input.spFusLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_spine_surgery_ext102',function:'SSxFusionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SSxMinimExt']=function(input){const score=Math.round((0.18 + Number(input.spMin||1)*0.2 + Number(input.spMinType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_spine_surgery_ext102',function:'SSxMinimExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SSxPostExt']=function(input){const score=Math.round((0.18 + Number(input.spPost||1)*0.2 + Number(input.spPostDay||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_spine_surgery_ext102',function:'SSxPostExt',input,score,ts:new Date().toISOString()}};

// TS: v3.61.61.0
