// filepath: pcc/pcc_neuro_ext145/pcc_neuro_ext145_engine.js
module.exports.version='v3.244.0';
module.exports.module='pcc_neuro_ext145';
module.exports.functions={};
module.exports.functions['PregestationalDiabeticExt']=function(input){const score=Math.round((0.18 + Number(input.diabetesType1||1)*0.2 + Number(input.control||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_neuro_ext145',function:'PregestationalDiabeticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GestationalDiabeticExt']=function(input){const score=Math.round((0.18 + Number(input.gestational||1)*0.2 + Number(input.week||20)*0.01 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_neuro_ext145',function:'GestationalDiabeticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HypertensiveDisorderPregExt']=function(input){const score=Math.round((0.18 + Number(input.preeclampsia||1)*0.2 + Number(input.severe||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_neuro_ext145',function:'HypertensiveDisorderPregExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EclampsiaExt']=function(input){const score=Math.round((0.18 + Number(input.seizure||1)*0.2 + Number(input.preeclampsia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_neuro_ext145',function:'EclampsiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HELLPext']=function(input){const score=Math.round((0.18 + Number(input.hemolysis||1)*0.2 + Number(input.elevatedLiver||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_neuro_ext145',function:'HELLPext',input,score,ts:new Date().toISOString()}};
module.exports.functions['AcuteFattyLiverPregExt']=function(input){const score=Math.round((0.18 + Number(input.afl||1)*0.2 + Number(input.week||30)*0.005 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_neuro_ext145',function:'AcuteFattyLiverPregExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HyperemesisGravidarumExt']=function(input){const score=Math.round((0.18 + Number(input.hg||1)*0.2 + Number(input.week||10)*0.01 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_neuro_ext145',function:'HyperemesisGravidarumExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CholestasisPregExt']=function(input){const score=Math.round((0.18 + Number(input.cholestasis||1)*0.2 + Number(input.bileAcids||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_neuro_ext145',function:'CholestasisPregExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PlacentaAccretaExt']=function(input){const score=Math.round((0.18 + Number(input.accreta||1)*0.2 + Number(input.priorCS||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_neuro_ext145',function:'PlacentaAccretaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PeripartumCardiomyoExt']=function(input){const score=Math.round((0.18 + Number(input.pcm||1)*0.2 + Number(input.pp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_neuro_ext145',function:'PeripartumCardiomyoExt',input,score,ts:new Date().toISOString()}};

// TS: v3.244.0
