// filepath: pcc/pcc_pediatric_surg_ext102/pcc_pediatric_surg_ext102_engine.js
module.exports.version='v3.212.0';
module.exports.module='pcc_pediatric_surg_ext102';
module.exports.functions={};
module.exports.functions['PediatricDementiaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.diet||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_surg_ext102',function:'PediatricDementiaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNCLsxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.supportive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_surg_ext102',function:'PediatricNCLsxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTaySachsSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||2)*0.04 + Number(input.supportive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_surg_ext102',function:'PediatricTaySachsSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNiemannPickSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.substrateReduct||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_surg_ext102',function:'PediatricNiemannPickSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGauchersSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ert||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_surg_ext102',function:'PediatricGauchersSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricKrabbeSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.hsct||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_surg_ext102',function:'PediatricKrabbeSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMLDSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||2)*0.04 + Number(input.hsct||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_surg_ext102',function:'PediatricMLDSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricALDSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.lorenzoOil||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_surg_ext102',function:'PediatricALDSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPKUSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.diet||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_surg_ext102',function:'PediatricPKUSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHomocystSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.b6||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_surg_ext102',function:'PediatricHomocystSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.212.0
