// filepath: pcc/pcc_pediatric_surg_ext171/pcc_pediatric_surg_ext171_engine.js
module.exports.version='v3.1.11.0';
module.exports.module='pcc_pediatric_surg_ext171';
module.exports.functions={};
module.exports.functions['PediatricHDjuvenileTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.hdJuvTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.11.0',module:'pcc_pediatric_surg_ext171',function:'PediatricHDjuvenileTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSCAchildTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.scaChildTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.11.0',module:'pcc_pediatric_surg_ext171',function:'PediatricSCAchildTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFRDAchildTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.frdaChildTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.11.0',module:'pcc_pediatric_surg_ext171',function:'PediatricFRDAchildTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDM1child2TxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.dm1Child2Tx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.11.0',module:'pcc_pediatric_surg_ext171',function:'PediatricDM1child2TxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOPMDchild2TxExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.opmdChild2Tx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.11.0',module:'pcc_pediatric_surg_ext171',function:'PediatricOPMDchild2TxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFSHDchild2TxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.fshdChild2Tx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.11.0',module:'pcc_pediatric_surg_ext171',function:'PediatricFSHDchild2TxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricKennedychild2TxExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.kennedyChild2Tx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.11.0',module:'pcc_pediatric_surg_ext171',function:'PediatricKennedychild2TxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFXTASchildTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.fxtasChildTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.11.0',module:'pcc_pediatric_surg_ext171',function:'PediatricFXTASchildTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLeighchildTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.leighChildTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.11.0',module:'pcc_pediatric_surg_ext171',function:'PediatricLeighchildTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMELASchildTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.melasChildTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.11.0',module:'pcc_pediatric_surg_ext171',function:'PediatricMELASchildTxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.11.0
