// filepath: pcc/pcc_pediatric_surg_ext111/pcc_pediatric_surg_ext111_engine.js
module.exports.version='v3.221.0';
module.exports.module='pcc_pediatric_surg_ext111';
module.exports.functions={};
module.exports.functions['PediatricMeningiomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_surg_ext111',function:'PediatricMeningiomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWHO1SxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_surg_ext111',function:'PediatricWHO1SxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWHO2SxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_surg_ext111',function:'PediatricWHO2SxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWHO3SxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_surg_ext111',function:'PediatricWHO3SxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCavernousSinusSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.radiosurgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_surg_ext111',function:'PediatricCavernousSinusSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOlfactorySxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.craniotomy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_surg_ext111',function:'PediatricOlfactorySxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricParasagittalSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_surg_ext111',function:'PediatricParasagittalSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricConvexitySxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_surg_ext111',function:'PediatricConvexitySxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSphenoidSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.radiosurgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_surg_ext111',function:'PediatricSphenoidSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPosteriorFossaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_surg_ext111',function:'PediatricPosteriorFossaSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.221.0
