// Auto-generated by gen_p3master.py -- PCC 3.314.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.314.0';

function X366AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x366) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_366', function: 'X366AssessmentExt', input, score, ts: TS };
}

function X366ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x366) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_366', function: 'X366ScoreExt', input, score, ts: TS };
}

function X366StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x366) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_366', function: 'X366StageExt', input, score, ts: TS };
}

function X366PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x366) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_366', function: 'X366PlanExt', input, score, ts: TS };
}

function X366RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x366) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_366', function: 'X366RiskExt', input, score, ts: TS };
}

function X366DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x366) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_366', function: 'X366DoseExt', input, score, ts: TS };
}

function X366FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x366) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_366', function: 'X366FrequencyExt', input, score, ts: TS };
}

function X366DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x366) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_366', function: 'X366DurationExt', input, score, ts: TS };
}

function X366FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x366) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_366', function: 'X366FollowupExt', input, score, ts: TS };
}

function X366OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x366) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_366', function: 'X366OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X366AssessmentExt,
  X366ScoreExt,
  X366StageExt,
  X366PlanExt,
  X366RiskExt,
  X366DoseExt,
  X366FrequencyExt,
  X366DurationExt,
  X366FollowupExt,
  X366OutcomeExt,
};