// filepath: pcc/pcc_neuro_ext172/pcc_neuro_ext172_engine.js
module.exports.version='v3.1.1.0';
module.exports.module='pcc_neuro_ext172';
module.exports.functions={};
module.exports.functions['NeuroOncEmergencyExt']=function(input){const score=Math.round((0.18 + Number(input.oncEmerg||1)*0.2 + Number(input.tumorType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_neuro_ext172',function:'NeuroOncEmergencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SpineOncExt']=function(input){const score=Math.round((0.18 + Number(input.spineOnc||1)*0.2 + Number(input.cordComp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_neuro_ext172',function:'SpineOncExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BrainMetsSolidExt']=function(input){const score=Math.round((0.18 + Number(input.brainMetsSolid||1)*0.2 + Number(input.primaryCa||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_neuro_ext172',function:'BrainMetsSolidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ParaneoplasticNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.paraneo||1)*0.2 + Number(input.antibody||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_neuro_ext172',function:'ParaneoplasticNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LambertEatonOncExt']=function(input){const score=Math.round((0.18 + Number(input.lemsOnc||1)*0.2 + Number(input.sclc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_neuro_ext172',function:'LambertEatonOncExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LimbicEncephalitisExt']=function(input){const score=Math.round((0.18 + Number(input.limbicE||1)*0.2 + Number(input.antiMa||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_neuro_ext172',function:'LimbicEncephalitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CerebellarDegenerationExt']=function(input){const score=Math.round((0.18 + Number(input.cerebDeg||1)*0.2 + Number(input.antiYo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_neuro_ext172',function:'CerebellarDegenerationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OpsoclonusMyoclonusExt']=function(input){const score=Math.round((0.18 + Number(input.opsomyoc||1)*0.2 + Number(input.antiRi||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_neuro_ext172',function:'OpsoclonusMyoclonusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['StiffPersonExt']=function(input){const score=Math.round((0.18 + Number(input.stiffPerson||1)*0.2 + Number(input.antiGAD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_neuro_ext172',function:'StiffPersonExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NeurolymphomatosisExt']=function(input){const score=Math.round((0.18 + Number(input.neurolymph||1)*0.2 + Number(input.nerveInfil||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_neuro_ext172',function:'NeurolymphomatosisExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.1.0
