// filepath: pcc/pcc_pediatric_neuro_ext126/pcc_pediatric_neuro_ext126_engine.js
module.exports.version='v3.236.0';
module.exports.module='pcc_pediatric_neuro_ext126';
module.exports.functions={};
module.exports.functions['PediatricAngiitisExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.angiitis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_neuro_ext126',function:'PediatricAngiitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPACNSExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pacns||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_neuro_ext126',function:'PediatricPACNSExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCNSVExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cnsv||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_neuro_ext126',function:'PediatricCNSVExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRCVSext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.rcvs||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_neuro_ext126',function:'PediatricRCVSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCallFlemingExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.call||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_neuro_ext126',function:'PediatricCallFlemingExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSusacExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.susac||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_neuro_ext126',function:'PediatricSusacExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCADASILExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.cadasil||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_neuro_ext126',function:'PediatricCADASILExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHIText']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.hit||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_neuro_ext126',function:'PediatricHIText',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDICext']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.dic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_neuro_ext126',function:'PediatricDICext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTTPext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ttp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.236.0',module:'pcc_pediatric_neuro_ext126',function:'PediatricTTPext',input,score,ts:new Date().toISOString()}};

// TS: v3.236.0
