// filepath: pcc/pcc_neuro_ext160/pcc_neuro_ext160_engine.js
module.exports.version='v3.259.0';
module.exports.module='pcc_neuro_ext160';
module.exports.functions={};
module.exports.functions['BrainTumorGliomaExt']=function(input){const score=Math.round((0.18 + Number(input.glioma||1)*0.2 + Number(input.whoGrade||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_neuro_ext160',function:'BrainTumorGliomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BrainTumorMeningiomaExt']=function(input){const score=Math.round((0.18 + Number(input.meningioma||1)*0.2 + Number(input.location||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_neuro_ext160',function:'BrainTumorMeningiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BrainTumorPituitaryExt']=function(input){const score=Math.round((0.18 + Number(input.pituitary||1)*0.2 + Number(input.hormone||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_neuro_ext160',function:'BrainTumorPituitaryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BrainMetastasisExt']=function(input){const score=Math.round((0.18 + Number(input.brainMet||1)*0.2 + Number(input.primary||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_neuro_ext160',function:'BrainMetastasisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SpineTumorExt']=function(input){const score=Math.round((0.18 + Number(input.spinetumor||1)*0.2 + Number(input.cordComp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_neuro_ext160',function:'SpineTumorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BrainLymphomaExt']=function(input){const score=Math.round((0.18 + Number(input.cnsLymphoma||1)*0.2 + Number(input.immuno||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_neuro_ext160',function:'BrainLymphomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MedulloblastomaExt']=function(input){const score=Math.round((0.18 + Number(input.medullo||1)*0.2 + Number(input.pediatricTumor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_neuro_ext160',function:'MedulloblastomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AcousticNeuromaExt']=function(input){const score=Math.round((0.18 + Number(input.schwannoma||1)*0.2 + Number(input.hearing||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_neuro_ext160',function:'AcousticNeuromaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PinealTumorExt']=function(input){const score=Math.round((0.18 + Number(input.pineal||1)*0.2 + Number(input.parinaud||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_neuro_ext160',function:'PinealTumorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SkullBaseTumorExt']=function(input){const score=Math.round((0.18 + Number(input.skullBase||1)*0.2 + Number(input.cranialNerve||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.259.0',module:'pcc_neuro_ext160',function:'SkullBaseTumorExt',input,score,ts:new Date().toISOString()}};

// TS: v3.259.0
