// filepath: pcc/pcc_respiratory_ext102/pcc_respiratory_ext102_engine.js
module.exports.version='v3.55.55.0';
module.exports.module='pcc_respiratory_ext102';
module.exports.functions={};
module.exports.functions['RespGenExt']=function(input){const score=Math.round((0.18 + Number(input.rsGen||1)*0.2 + Number(input.rsGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_respiratory_ext102',function:'RespGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RespVentExt']=function(input){const score=Math.round((0.18 + Number(input.rsVent||1)*0.2 + Number(input.rsVentMode||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_respiratory_ext102',function:'RespVentExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RespOxygenExt']=function(input){const score=Math.round((0.18 + Number(input.rsO2||1)*0.2 + Number(input.rsO2FiO2||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_respiratory_ext102',function:'RespOxygenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RespWeaningExt']=function(input){const score=Math.round((0.18 + Number(input.rsWean||1)*0.2 + Number(input.rsWeanScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_respiratory_ext102',function:'RespWeaningExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RespTrachExt']=function(input){const score=Math.round((0.18 + Number(input.rsTrach||1)*0.2 + Number(input.rsTrachType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_respiratory_ext102',function:'RespTrachExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RespPFText']=function(input){const score=Math.round((0.18 + Number(input.rsPFT||1)*0.2 + Number(input.rsPFTScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_respiratory_ext102',function:'RespPFText',input,score,ts:new Date().toISOString()}};
module.exports.functions['RespABGext']=function(input){const score=Math.round((0.18 + Number(input.rsABG||1)*0.2 + Number(input.rsABGtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_respiratory_ext102',function:'RespABGext',input,score,ts:new Date().toISOString()}};
module.exports.functions['RespRehabExt']=function(input){const score=Math.round((0.18 + Number(input.rsReh||1)*0.2 + Number(input.rsRehScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_respiratory_ext102',function:'RespRehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RespHomeExt']=function(input){const score=Math.round((0.18 + Number(input.rsHome||1)*0.2 + Number(input.rsHomeType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_respiratory_ext102',function:'RespHomeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RespFailureExt']=function(input){const score=Math.round((0.18 + Number(input.rsFail||1)*0.2 + Number(input.rsFailScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_respiratory_ext102',function:'RespFailureExt',input,score,ts:new Date().toISOString()}};

// TS: v3.55.55.0
