-- adm_101 reverse
BEGIN;
DROP TABLE IF EXISTS adm_101_results CASCADE;
DROP TABLE IF EXISTS adm_101_orders  CASCADE;
DROP TABLE IF EXISTS adm_101_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ADM_101_up';
COMMIT;
