-- card_103 reverse
BEGIN;
DROP TABLE IF EXISTS card_103_results CASCADE;
DROP TABLE IF EXISTS card_103_orders  CASCADE;
DROP TABLE IF EXISTS card_103_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_CARD_103_up';
COMMIT;
