// filepath: pcc/pcc_ophthalmology_ext102/pcc_ophthalmology_ext102_engine.js
module.exports.version='v3.63.63.0';
module.exports.module='pcc_ophthalmology_ext102';
module.exports.functions={};
module.exports.functions['OphGenExt']=function(input){const score=Math.round((0.18 + Number(input.opGen||1)*0.2 + Number(input.opGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.63.63.0',module:'pcc_ophthalmology_ext102',function:'OphGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphRefracExt']=function(input){const score=Math.round((0.18 + Number(input.opRe||1)*0.2 + Number(input.opReType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.63.63.0',module:'pcc_ophthalmology_ext102',function:'OphRefracExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphGlaucomaExt']=function(input){const score=Math.round((0.18 + Number(input.opGl||1)*0.2 + Number(input.opGlIOP||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.63.63.0',module:'pcc_ophthalmology_ext102',function:'OphGlaucomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphCataractExt']=function(input){const score=Math.round((0.18 + Number(input.opCat||1)*0.2 + Number(input.opCatGrade||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.63.63.0',module:'pcc_ophthalmology_ext102',function:'OphCataractExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphRetinaExt']=function(input){const score=Math.round((0.18 + Number(input.opRet||1)*0.2 + Number(input.opRetType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.63.63.0',module:'pcc_ophthalmology_ext102',function:'OphRetinaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphMacDegExt']=function(input){const score=Math.round((0.18 + Number(input.opMD||1)*0.2 + Number(input.opMDtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.63.63.0',module:'pcc_ophthalmology_ext102',function:'OphMacDegExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphDiabeticExt']=function(input){const score=Math.round((0.18 + Number(input.opDR||1)*0.2 + Number(input.opDRgrade||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.63.63.0',module:'pcc_ophthalmology_ext102',function:'OphDiabeticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphPediatricExt']=function(input){const score=Math.round((0.18 + Number(input.opPed||1)*0.2 + Number(input.opPedType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.63.63.0',module:'pcc_ophthalmology_ext102',function:'OphPediatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphTraumaExt']=function(input){const score=Math.round((0.18 + Number(input.opTr||1)*0.2 + Number(input.opTrScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.63.63.0',module:'pcc_ophthalmology_ext102',function:'OphTraumaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OphOncologyExt']=function(input){const score=Math.round((0.18 + Number(input.opOn||1)*0.2 + Number(input.opOnType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.63.63.0',module:'pcc_ophthalmology_ext102',function:'OphOncologyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.63.63.0
