// filepath: pcc/pcc_pediatric_neuro_ext166/pcc_pediatric_neuro_ext166_engine.js
module.exports.version='v3.1.6.0';
module.exports.module='pcc_pediatric_neuro_ext166';
module.exports.functions={};
module.exports.functions['PediatricThrombectomyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pThrombectomy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_neuro_ext166',function:'PediatricThrombectomyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeUnitExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeUnit||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_neuro_ext166',function:'PediatricStrokeUnitExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeRehab2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeRehab2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_neuro_ext166',function:'PediatricStrokeRehab2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAntiplateletExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAntiplatelet||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_neuro_ext166',function:'PediatricAntiplateletExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAnticoagExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAnticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_neuro_ext166',function:'PediatricAnticoagExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLipidMgtExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pLipid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_neuro_ext166',function:'PediatricLipidMgtExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBPmgtExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pBPmgt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_neuro_ext166',function:'PediatricBPmgtExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDiabetesMgtExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pDMmgt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_neuro_ext166',function:'PediatricDiabetesMgtExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeLifestyleExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pStrokeLS||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_neuro_ext166',function:'PediatricStrokeLifestyleExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeFollowupExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeFU||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.6.0',module:'pcc_pediatric_neuro_ext166',function:'PediatricStrokeFollowupExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.6.0
