// filepath: pcc/pcc_pediatric_neuro_ext169/pcc_pediatric_neuro_ext169_engine.js
module.exports.version='v3.1.9.0';
module.exports.module='pcc_pediatric_neuro_ext169';
module.exports.functions={};
module.exports.functions['PediatricNeuroICUExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pNeuroICU||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_neuro_ext169',function:'PediatricNeuroICUExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHerniationExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pHerniation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_neuro_ext169',function:'PediatricHerniationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricICPmonitorExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pICP||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_neuro_ext169',function:'PediatricICPmonitorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStatusEpiICUExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pSEicu||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_neuro_ext169',function:'PediatricStatusEpiICUExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMeningitisExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pMeningitis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_neuro_ext169',function:'PediatricMeningitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEncephExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pEnceph||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_neuro_ext169',function:'PediatricEncephExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainAbscessExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAbscess||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_neuro_ext169',function:'PediatricBrainAbscessExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVentNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pVentNeuro||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_neuro_ext169',function:'PediatricVentNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVasospasmExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pVasospasm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_neuro_ext169',function:'PediatricVasospasmExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainDeathExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pBrainDeath||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_neuro_ext169',function:'PediatricBrainDeathExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.9.0
