// filepath: pcc/pcc_pediatric_neuro_ext134/pcc_pediatric_neuro_ext134_engine.js
module.exports.version='v3.244.0';
module.exports.module='pcc_pediatric_neuro_ext134';
module.exports.functions={};
module.exports.functions['PediatricPregCompExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pregComp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_pediatric_neuro_ext134',function:'PediatricPregCompExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeonatalStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.age||0.1)*0.04 + Number(input.neonatalStroke||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_pediatric_neuro_ext134',function:'PediatricNeonatalStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHIEext']=function(input){const score=Math.round((0.18 + Number(input.age||0.1)*0.04 + Number(input.hie||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_pediatric_neuro_ext134',function:'PediatricHIEext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIVHext']=function(input){const score=Math.round((0.18 + Number(input.age||0.1)*0.04 + Number(input.ivh||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_pediatric_neuro_ext134',function:'PediatricIVHext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPVLext']=function(input){const score=Math.round((0.18 + Number(input.age||0.1)*0.04 + Number(input.pvl||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_pediatric_neuro_ext134',function:'PediatricPVLext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHMDext']=function(input){const score=Math.round((0.18 + Number(input.age||0.1)*0.04 + Number(input.hmd||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_pediatric_neuro_ext134',function:'PediatricHMDext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNECext']=function(input){const score=Math.round((0.18 + Number(input.age||0.5)*0.04 + Number(input.nec||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_pediatric_neuro_ext134',function:'PediatricNECext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricROPext']=function(input){const score=Math.round((0.18 + Number(input.age||0.5)*0.04 + Number(input.rop||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_pediatric_neuro_ext134',function:'PediatricROPext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBPDext']=function(input){const score=Math.round((0.18 + Number(input.age||0.5)*0.04 + Number(input.bpd||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_pediatric_neuro_ext134',function:'PediatricBPDext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCPext']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.cp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.244.0',module:'pcc_pediatric_neuro_ext134',function:'PediatricCPext',input,score,ts:new Date().toISOString()}};

// TS: v3.244.0
