// filepath: pcc/pcc_geriatric_ext101/pcc_geriatric_ext101_engine.js
module.exports.version='v3.35.35.0';
module.exports.module='pcc_geriatric_ext101';
module.exports.functions={};
module.exports.functions['GerFrailtyExt']=function(input){const score=Math.round((0.18 + Number(input.grFrail||1)*0.2 + Number(input.frailScale||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.35.35.0',module:'pcc_geriatric_ext101',function:'GerFrailtyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GerFallsExt']=function(input){const score=Math.round((0.18 + Number(input.grFalls||1)*0.2 + Number(input.fallRiskScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.35.35.0',module:'pcc_geriatric_ext101',function:'GerFallsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GerDeliriumExt']=function(input){const score=Math.round((0.18 + Number(input.grDelirium||1)*0.2 + Number(input.camGer||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.35.35.0',module:'pcc_geriatric_ext101',function:'GerDeliriumExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GerPolypharmExt']=function(input){const score=Math.round((0.18 + Number(input.grPoly||1)*0.2 + Number(input.medCount||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.35.35.0',module:'pcc_geriatric_ext101',function:'GerPolypharmExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GerCognitiveExt']=function(input){const score=Math.round((0.18 + Number(input.grCog||1)*0.2 + Number(input.mmseGer||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.35.35.0',module:'pcc_geriatric_ext101',function:'GerCognitiveExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GerUrinaryExt']=function(input){const score=Math.round((0.18 + Number(input.grUri||1)*0.2 + Number(input.uiSeverity||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.35.35.0',module:'pcc_geriatric_ext101',function:'GerUrinaryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GerNutritionExt']=function(input){const score=Math.round((0.18 + Number(input.grNutr||1)*0.2 + Number(input.albGer||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.35.35.0',module:'pcc_geriatric_ext101',function:'GerNutritionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GerPressureUlcerExt']=function(input){const score=Math.round((0.18 + Number(input.grPU||1)*0.2 + Number(input.bradenScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.35.35.0',module:'pcc_geriatric_ext101',function:'GerPressureUlcerExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GerEndOfLifeExt']=function(input){const score=Math.round((0.18 + Number(input.grEOL||1)*0.2 + Number(input.eolDecisions||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.35.35.0',module:'pcc_geriatric_ext101',function:'GerEndOfLifeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GerFunctionalExt']=function(input){const score=Math.round((0.18 + Number(input.grFunc||1)*0.2 + Number(input.adlScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.35.35.0',module:'pcc_geriatric_ext101',function:'GerFunctionalExt',input,score,ts:new Date().toISOString()}};

// TS: v3.35.35.0
