// filepath: pcc/pcc_ortho_ext100/pcc_ortho_ext100_engine.js
module.exports.version='v3.24.24.0';
module.exports.module='pcc_ortho_ext100';
module.exports.functions={};
module.exports.functions['OrthoFractureExt']=function(input){const score=Math.round((0.18 + Number(input.ortFracture||1)*0.2 + Number(input.fractType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_ortho_ext100',function:'OrthoFractureExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrthoSpineExt']=function(input){const score=Math.round((0.18 + Number(input.ortSpine||1)*0.2 + Number(input.spineLevel||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_ortho_ext100',function:'OrthoSpineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrthoJointExt']=function(input){const score=Math.round((0.18 + Number(input.ortJoint||1)*0.2 + Number(input.jointScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_ortho_ext100',function:'OrthoJointExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrthoSportExt']=function(input){const score=Math.round((0.18 + Number(input.ortSport||1)*0.2 + Number(input.sportType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_ortho_ext100',function:'OrthoSportExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrthoHandExt']=function(input){const score=Math.round((0.18 + Number(input.ortHand||1)*0.2 + Number(input.handGrip||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_ortho_ext100',function:'OrthoHandExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrthoFootExt']=function(input){const score=Math.round((0.18 + Number(input.ortFoot||1)*0.2 + Number(input.footArch||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_ortho_ext100',function:'OrthoFootExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrthoTumorExt']=function(input){const score=Math.round((0.18 + Number(input.ortTumor||1)*0.2 + Number(input.boneTumorType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_ortho_ext100',function:'OrthoTumorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrthoInfectionExt']=function(input){const score=Math.round((0.18 + Number(input.ortInf||1)*0.2 + Number(input.ortInfType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_ortho_ext100',function:'OrthoInfectionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrthoPediatricExt']=function(input){const score=Math.round((0.18 + Number(input.ortPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_ortho_ext100',function:'OrthoPediatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrthoReconExt']=function(input){const score=Math.round((0.18 + Number(input.ortRecon||1)*0.2 + Number(input.orthoReconType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_ortho_ext100',function:'OrthoReconExt',input,score,ts:new Date().toISOString()}};

// TS: v3.24.24.0
