// filepath: pcc/pcc_neuro_ext185/pcc_neuro_ext185_engine.js
module.exports.version='v3.14.14.0';
module.exports.module='pcc_neuro_ext185';
module.exports.functions={};
module.exports.functions['OphthalmoplegiaChronicExt']=function(input){const score=Math.round((0.18 + Number(input.chronicOph||1)*0.2 + Number(input.eyeMuscle||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_neuro_ext185',function:'OphthalmoplegiaChronicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['INOExt']=function(input){const score=Math.round((0.18 + Number(input.ino||1)*0.2 + Number(input.medialRectus||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_neuro_ext185',function:'INOExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['WEBINOExt']=function(input){const score=Math.round((0.18 + Number(input.webino||1)*0.2 + Number(input.bilateralIno||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_neuro_ext185',function:'WEBINOExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OpsoclonusExt']=function(input){const score=Math.round((0.18 + Number(input.opsoclonus2||1)*0.2 + Number(input.ocularShudder||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_neuro_ext185',function:'OpsoclonusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NystagmusCongenitalExt']=function(input){const score=Math.round((0.18 + Number(input.nystagmusCong||1)*0.2 + Number(input.sensoryDef||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_neuro_ext185',function:'NystagmusCongenitalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NystagmusAcquiredExt']=function(input){const score=Math.round((0.18 + Number(input.acquiredNyst||1)*0.2 + Number(input.acuteVert||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_neuro_ext185',function:'NystagmusAcquiredExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SaccadicPursuitExt']=function(input){const score=Math.round((0.18 + Number(input.saccadic||1)*0.2 + Number(input.pursuit||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_neuro_ext185',function:'SaccadicPursuitExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SupranuclearPalsyExt']=function(input){const score=Math.round((0.18 + Number(input.snPalsy||1)*0.2 + Number(input.verticalGaze||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_neuro_ext185',function:'SupranuclearPalsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ThirdNervePalsyExt']=function(input){const score=Math.round((0.18 + Number(input.iiiNerve||1)*0.2 + Number(input.ptosis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_neuro_ext185',function:'ThirdNervePalsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SixthNervePalsyExt']=function(input){const score=Math.round((0.18 + Number(input.viNerve||1)*0.2 + Number(input.lateralGaze||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_neuro_ext185',function:'SixthNervePalsyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.14.14.0
