// filepath: pcc/pcc_neuro_ext194/pcc_neuro_ext194_engine.js
module.exports.version='v3.23.23.0';
module.exports.module='pcc_neuro_ext194';
module.exports.functions={};
module.exports.functions['HeadacheMigraineAdultExt']=function(input){const score=Math.round((0.18 + Number(input.migraineAdult||1)*0.2 + Number(input.frequency||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_neuro_ext194',function:'HeadacheMigraineAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HeadacheClusterAdultExt']=function(input){const score=Math.round((0.18 + Number(input.clusterAdult||1)*0.2 + Number(input.attackFreq||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_neuro_ext194',function:'HeadacheClusterAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HeadacheTensionAdultExt']=function(input){const score=Math.round((0.18 + Number(input.tthAdult||1)*0.2 + Number(input.stress||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_neuro_ext194',function:'HeadacheTensionAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HeadacheMedicationOveruseExt']=function(input){const score=Math.round((0.18 + Number(input.moh||1)*0.2 + Number(input.meds||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_neuro_ext194',function:'HeadacheMedicationOveruseExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HeadachePregnancyExt']=function(input){const score=Math.round((0.18 + Number(input.hPreg||1)*0.2 + Number(input.gestAge||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_neuro_ext194',function:'HeadachePregnancyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HeadacheThunderclapExt']=function(input){const score=Math.round((0.18 + Number(input.thunderclap||1)*0.2 + Number(input.sahRisk||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_neuro_ext194',function:'HeadacheThunderclapExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HeadacheIdiopathicIntracranialExt']=function(input){const score=Math.round((0.18 + Number(input.iih||1)*0.2 + Number(input.opening||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_neuro_ext194',function:'HeadacheIdiopathicIntracranialExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HeadacheLowCSFExt']=function(input){const score=Math.round((0.18 + Number(input.lowCSF||1)*0.2 + Number(input.csfLeak||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_neuro_ext194',function:'HeadacheLowCSFExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HeadacheTrigeminalExt']=function(input){const score=Math.round((0.18 + Number(input.tgn||1)*0.2 + Number(input.attackSeverity||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_neuro_ext194',function:'HeadacheTrigeminalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HeadacheCervicogenicExt']=function(input){const score=Math.round((0.18 + Number(input.cervH||1)*0.2 + Number(input.cervSpine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_neuro_ext194',function:'HeadacheCervicogenicExt',input,score,ts:new Date().toISOString()}};

// TS: v3.23.23.0
