// Auto-generated by gen_p3master.py -- PCC 3.294.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.294.0';

function X306AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x306) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_306', function: 'X306AssessmentExt', input, score, ts: TS };
}

function X306ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x306) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_306', function: 'X306ScoreExt', input, score, ts: TS };
}

function X306StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x306) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_306', function: 'X306StageExt', input, score, ts: TS };
}

function X306PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x306) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_306', function: 'X306PlanExt', input, score, ts: TS };
}

function X306RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x306) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_306', function: 'X306RiskExt', input, score, ts: TS };
}

function X306DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x306) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_306', function: 'X306DoseExt', input, score, ts: TS };
}

function X306FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x306) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_306', function: 'X306FrequencyExt', input, score, ts: TS };
}

function X306DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x306) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_306', function: 'X306DurationExt', input, score, ts: TS };
}

function X306FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x306) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_306', function: 'X306FollowupExt', input, score, ts: TS };
}

function X306OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x306) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_306', function: 'X306OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X306AssessmentExt,
  X306ScoreExt,
  X306StageExt,
  X306PlanExt,
  X306RiskExt,
  X306DoseExt,
  X306FrequencyExt,
  X306DurationExt,
  X306FollowupExt,
  X306OutcomeExt,
};