// filepath: pcc/pcc_metabolomics_ext102/pcc_metabolomics_ext102_engine.js
module.exports.version='v3.39.39.0';
module.exports.module='pcc_metabolomics_ext102';
module.exports.functions={};
module.exports.functions['MetMetaboliteExt']=function(input){const score=Math.round((0.18 + Number(input.metMet||1)*0.2 + Number(input.metMetClass||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_metabolomics_ext102',function:'MetMetaboliteExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MetLipidomicExt']=function(input){const score=Math.round((0.18 + Number(input.metLipid||1)*0.2 + Number(input.metLipidClass||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_metabolomics_ext102',function:'MetLipidomicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MetGlycomicsExt']=function(input){const score=Math.round((0.18 + Number(input.metGlyco||1)*0.2 + Number(input.metGlycoType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_metabolomics_ext102',function:'MetGlycomicsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MetAminoAcidExt']=function(input){const score=Math.round((0.18 + Number(input.metAA||1)*0.2 + Number(input.metAaType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_metabolomics_ext102',function:'MetAminoAcidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MetHormoneExt']=function(input){const score=Math.round((0.18 + Number(input.metHorm||1)*0.2 + Number(input.metHormLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_metabolomics_ext102',function:'MetHormoneExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MetVitaminExt']=function(input){const score=Math.round((0.18 + Number(input.metVit||1)*0.2 + Number(input.metVitLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_metabolomics_ext102',function:'MetVitaminExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MetToxicExt']=function(input){const score=Math.round((0.18 + Number(input.metTox||1)*0.2 + Number(input.metToxLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_metabolomics_ext102',function:'MetToxicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MetDrugMetExt']=function(input){const score=Math.round((0.18 + Number(input.metDrug||1)*0.2 + Number(input.metDrugType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_metabolomics_ext102',function:'MetDrugMetExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MetFluxExt']=function(input){const score=Math.round((0.18 + Number(input.metFlux||1)*0.2 + Number(input.metFluxPath||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_metabolomics_ext102',function:'MetFluxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MetBiomarkerExt']=function(input){const score=Math.round((0.18 + Number(input.metBio||1)*0.2 + Number(input.metBioClass||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_metabolomics_ext102',function:'MetBiomarkerExt',input,score,ts:new Date().toISOString()}};

// TS: v3.39.39.0
