-- sup_101 reverse
BEGIN;
DROP TABLE IF EXISTS sup_101_results CASCADE;
DROP TABLE IF EXISTS sup_101_orders  CASCADE;
DROP TABLE IF EXISTS sup_101_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_SUP_101_up';
COMMIT;
