// filepath: pcc/pcc_pediatric_surg_ext106/pcc_pediatric_surg_ext106_engine.js
module.exports.version='v3.216.0';
module.exports.module='pcc_pediatric_surg_ext106';
module.exports.functions={};
module.exports.functions['PediatricGBSivigExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.216.0',module:'pcc_pediatric_surg_ext106',function:'PediatricGBSivigExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMFivigExt']=function(input){const score=Math.round((0.18 + Number(input.age||6)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.216.0',module:'pcc_pediatric_surg_ext106',function:'PediatricMFivigExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBSivigExt']=function(input){const score=Math.round((0.18 + Number(input.age||6)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.216.0',module:'pcc_pediatric_surg_ext106',function:'PediatricBSivigExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCIDPivigExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.216.0',module:'pcc_pediatric_surg_ext106',function:'PediatricCIDPivigExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMMNivigExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.216.0',module:'pcc_pediatric_surg_ext106',function:'PediatricMMNivigExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAntiMAGivigExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.rituximab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.216.0',module:'pcc_pediatric_surg_ext106',function:'PediatricAntiMAGivigExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPOEMSivigExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.216.0',module:'pcc_pediatric_surg_ext106',function:'PediatricPOEMSivigExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAMANivigExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.216.0',module:'pcc_pediatric_surg_ext106',function:'PediatricAMANivigExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAMSANivigExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.216.0',module:'pcc_pediatric_surg_ext106',function:'PediatricAMSANivigExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGBSvariantsivigExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.216.0',module:'pcc_pediatric_surg_ext106',function:'PediatricGBSvariantsivigExt',input,score,ts:new Date().toISOString()}};

// TS: v3.216.0
