// filepath: pcc/pcc_pediatric_surg_ext110/pcc_pediatric_surg_ext110_engine.js
module.exports.version='v3.220.0';
module.exports.module='pcc_pediatric_surg_ext110';
module.exports.functions={};
module.exports.functions['PediatricGBMSxExt']=function(input){const score=Math.round((0.15 + Number(input.age||8)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_surg_ext110',function:'PediatricGBMSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAASxExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_surg_ext110',function:'PediatricAASxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOligoSxExt']=function(input){const score=Math.round((0.15 + Number(input.age||10)*0.04 + Number(input.chemo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_surg_ext110',function:'PediatricOligoSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGliomatosisSxExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.biopsy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_surg_ext110',function:'PediatricGliomatosisSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDIPGsxExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.radiation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_surg_ext110',function:'PediatricDIPGsxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPilocyticSxExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_surg_ext110',function:'PediatricPilocyticSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSEGASxExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.mtor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_surg_ext110',function:'PediatricSEGASxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPXASxExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_surg_ext110',function:'PediatricPXASxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPMASxExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_surg_ext110',function:'PediatricPMASxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGliosarcomaSxExt']=function(input){const score=Math.round((0.15 + Number(input.age||8)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.220.0',module:'pcc_pediatric_surg_ext110',function:'PediatricGliosarcomaSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.220.0
