// filepath: pcc/pcc_neuro_ext148/pcc_neuro_ext148_engine.js
module.exports.version='v3.247.0';
module.exports.module='pcc_neuro_ext148';
module.exports.functions={};
module.exports.functions['ToxicEncephalopathyExt']=function(input){const score=Math.round((0.18 + Number(input.toxin||1)*0.2 + Number(input.encephalopathy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_neuro_ext148',function:'ToxicEncephalopathyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['WernickeEncephalopathyExt']=function(input){const score=Math.round((0.18 + Number(input.thiamine||1)*0.2 + Number(input.wehicke||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_neuro_ext148',function:'WernickeEncephalopathyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['KorsakoffExt']=function(input){const score=Math.round((0.18 + Number(input.alcohol||1)*0.2 + Number(input.memory||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_neuro_ext148',function:'KorsakoffExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AlcoholWithdrawalExt']=function(input){const score=Math.round((0.18 + Number(input.alcohol||1)*0.2 + Number(input.withdrawal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_neuro_ext148',function:'AlcoholWithdrawalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AlcoholSeizureExt']=function(input){const score=Math.round((0.18 + Number(input.alcohol||1)*0.2 + Number(input.seizure||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_neuro_ext148',function:'AlcoholSeizureExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OpioidOverdoseExt']=function(input){const score=Math.round((0.18 + Number(input.opioid||1)*0.2 + Number(input.overdose||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_neuro_ext148',function:'OpioidOverdoseExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OpioidWithdrawalExt']=function(input){const score=Math.round((0.18 + Number(input.opioid||1)*0.2 + Number(input.withdrawal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_neuro_ext148',function:'OpioidWithdrawalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BenzodiazepineSedationExt']=function(input){const score=Math.round((0.18 + Number(input.benzo||1)*0.2 + Number(input.sedation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_neuro_ext148',function:'BenzodiazepineSedationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['StimulantToxicExt']=function(input){const score=Math.round((0.18 + Number(input.stimulant||1)*0.2 + Number(input.toxicity||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_neuro_ext148',function:'StimulantToxicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CocaineCerebroExt']=function(input){const score=Math.round((0.18 + Number(input.cocaine||1)*0.2 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_neuro_ext148',function:'CocaineCerebroExt',input,score,ts:new Date().toISOString()}};

// TS: v3.247.0
