// filepath: pcc/pcc_pediatric_surg_ext96/pcc_pediatric_surg_ext96_engine.js
// pcc_pediatric_surg_ext96 engine (deterministic)
module.exports.version='v3.206.0';
module.exports.module='pcc_pediatric_surg_ext96';
module.exports.functions={};
module.exports.functions['PediatricAneurysmClippingExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.clip||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_surg_ext96',function:'PediatricAneurysmClippingExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSAHClippingExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.huntHess||2)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_surg_ext96',function:'PediatricSAHClippingExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricAVMResectionExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.spetzler||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_surg_ext96',function:'PediatricAVMResectionExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCavernomaResectExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.resect||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_surg_ext96',function:'PediatricCavernomaResectExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCVMResectExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.05 + Number(input.resect||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_surg_ext96',function:'PediatricCVMResectExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricDuralAVFistulaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||6)*0.04 + Number(input.embol||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_surg_ext96',function:'PediatricDuralAVFistulaSxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCCFistulaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.embol||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_surg_ext96',function:'PediatricCCFistulaSxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricPICAneurysmSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.coil||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_surg_ext96',function:'PediatricPICAneurysmSxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricBasilarSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.flowDiv||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_surg_ext96',function:'PediatricBasilarSxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricGiantAneurysmSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.02 + Number(input.bypass||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.206.0',module:'pcc_pediatric_surg_ext96',function:'PediatricGiantAneurysmSxExt',input,score,ts:new Date().toISOString()};};

// TS: v3.206.0
