// filepath: pcc/pcc_neuro_ext164/pcc_neuro_ext164_engine.js
module.exports.version='v3.263.0';
module.exports.module='pcc_neuro_ext164';
module.exports.functions={};
module.exports.functions['HeadacheMigraineExt']=function(input){const score=Math.round((0.18 + Number(input.migraine||1)*0.2 + Number(input.frequency||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_neuro_ext164',function:'HeadacheMigraineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TensionHeadacheExt']=function(input){const score=Math.round((0.18 + Number(input.tth||1)*0.2 + Number(input.pericranial||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_neuro_ext164',function:'TensionHeadacheExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ClusterHeadacheExt']=function(input){const score=Math.round((0.18 + Number(input.cluster||1)*0.2 + Number(input.horner||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_neuro_ext164',function:'ClusterHeadacheExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MedicationOveruseExt']=function(input){const score=Math.round((0.18 + Number(input.moh||1)*0.2 + Number(input.analgesic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_neuro_ext164',function:'MedicationOveruseExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TrigeminalAutonomicExt']=function(input){const score=Math.round((0.18 + Number(input.tac||1)*0.2 + Number(input.autonomic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_neuro_ext164',function:'TrigeminalAutonomicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ThunderclapHeadacheExt']=function(input){const score=Math.round((0.18 + Number(input.thunderclap||1)*0.2 + Number(input.worst||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_neuro_ext164',function:'ThunderclapHeadacheExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SexualHeadacheExt']=function(input){const score=Math.round((0.18 + Number(input.orgasmHeadache||1)*0.2 + Number(input.exertional||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_neuro_ext164',function:'SexualHeadacheExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CoughHeadacheExt']=function(input){const score=Math.round((0.18 + Number(input.coughHeadache||1)*0.2 + Number(input.valsalva||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_neuro_ext164',function:'CoughHeadacheExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HypnicHeadacheExt']=function(input){const score=Math.round((0.18 + Number(input.hypnic||1)*0.2 + Number(input.nightly||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_neuro_ext164',function:'HypnicHeadacheExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['IdiopathicIntracranialExt']=function(input){const score=Math.round((0.18 + Number(input.iih||1)*0.2 + Number(input.papilledema||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.263.0',module:'pcc_neuro_ext164',function:'IdiopathicIntracranialExt',input,score,ts:new Date().toISOString()}};

// TS: v3.263.0
