// filepath: pcc/pcc_neuro_ext168/pcc_neuro_ext168_engine.js
module.exports.version='v3.12.9.0';
module.exports.module='pcc_neuro_ext168';
module.exports.functions={};
module.exports.functions['OpticNeuritis2Ext']=function(input){const score=Math.round((0.18 + Number(input.optNeur2||1)*0.2 + Number(input.rapd||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.9.0',module:'pcc_neuro_ext168',function:'OpticNeuritis2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['IschemicOpticNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.ion||1)*0.2 + Number(input.naion||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.9.0',module:'pcc_neuro_ext168',function:'IschemicOpticNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PapilledemaExt']=function(input){const score=Math.round((0.18 + Number(input.papilledema2||1)*0.2 + Number(input.iih2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.9.0',module:'pcc_neuro_ext168',function:'PapilledemaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MacularDegenerationExt']=function(input){const score=Math.round((0.18 + Number(input.amd||1)*0.2 + Number(input.drusen||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.9.0',module:'pcc_neuro_ext168',function:'MacularDegenerationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RetinalDetachmentExt']=function(input){const score=Math.round((0.18 + Number(input.rd||1)*0.2 + Number(input.shadows||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.9.0',module:'pcc_neuro_ext168',function:'RetinalDetachmentExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RetinalVeinOcclusionExt']=function(input){const score=Math.round((0.18 + Number(input.rvo||1)*0.2 + Number(input.crv||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.9.0',module:'pcc_neuro_ext168',function:'RetinalVeinOcclusionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RetinalArteryOcclusionExt']=function(input){const score=Math.round((0.18 + Number(input.rac||1)*0.2 + Number(input.crao||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.9.0',module:'pcc_neuro_ext168',function:'RetinalArteryOcclusionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['DiabeticRetinopathyExt']=function(input){const score=Math.round((0.18 + Number(input.dr||1)*0.2 + Number(input.hba1c||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.9.0',module:'pcc_neuro_ext168',function:'DiabeticRetinopathyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GlaucomaNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.glaucoma||1)*0.2 + Number(input.iop||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.9.0',module:'pcc_neuro_ext168',function:'GlaucomaNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OrbitalCellulitisExt']=function(input){const score=Math.round((0.18 + Number(input.orbitalCell||1)*0.2 + Number(input.proptosis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.9.0',module:'pcc_neuro_ext168',function:'OrbitalCellulitisExt',input,score,ts:new Date().toISOString()}};

// TS: v3.12.9.0
