// filepath: pcc/pcc_reproductive_endocrinology_ext102/pcc_reproductive_endocrinology_ext102_engine.js
module.exports.version='v3.50.50.0';
module.exports.module='pcc_reproductive_endocrinology_ext102';
module.exports.functions={};
module.exports.functions['RepEndoCycleExt']=function(input){const score=Math.round((0.18 + Number(input.reCyc||1)*0.2 + Number(input.reCycDay||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.50.50.0',module:'pcc_reproductive_endocrinology_ext102',function:'RepEndoCycleExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RepEndoHormoneExt']=function(input){const score=Math.round((0.18 + Number(input.reHor||1)*0.2 + Number(input.reHorType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.50.50.0',module:'pcc_reproductive_endocrinology_ext102',function:'RepEndoHormoneExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RepEndoPCOSext']=function(input){const score=Math.round((0.18 + Number(input.rePCOS||1)*0.2 + Number(input.rePCOSscore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.50.50.0',module:'pcc_reproductive_endocrinology_ext102',function:'RepEndoPCOSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['RepEndoEndoExt']=function(input){const score=Math.round((0.18 + Number(input.reEndo||1)*0.2 + Number(input.reEndoScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.50.50.0',module:'pcc_reproductive_endocrinology_ext102',function:'RepEndoEndoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RepEndoPubertyExt']=function(input){const score=Math.round((0.18 + Number(input.rePub||1)*0.2 + Number(input.rePubType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.50.50.0',module:'pcc_reproductive_endocrinology_ext102',function:'RepEndoPubertyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RepEndoMenopauseExt']=function(input){const score=Math.round((0.18 + Number(input.reMen||1)*0.2 + Number(input.reMenScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.50.50.0',module:'pcc_reproductive_endocrinology_ext102',function:'RepEndoMenopauseExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RepEndoAndroExt']=function(input){const score=Math.round((0.18 + Number(input.reAnd||1)*0.2 + Number(input.reAndLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.50.50.0',module:'pcc_reproductive_endocrinology_ext102',function:'RepEndoAndroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RepEndoThyroidExt']=function(input){const score=Math.round((0.18 + Number(input.reThy||1)*0.2 + Number(input.reThyTSH||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.50.50.0',module:'pcc_reproductive_endocrinology_ext102',function:'RepEndoThyroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RepEndoContracepExt']=function(input){const score=Math.round((0.18 + Number(input.reCon||1)*0.2 + Number(input.reConType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.50.50.0',module:'pcc_reproductive_endocrinology_ext102',function:'RepEndoContracepExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RepEndoFertilityExt']=function(input){const score=Math.round((0.18 + Number(input.reFert||1)*0.2 + Number(input.reFertScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.50.50.0',module:'pcc_reproductive_endocrinology_ext102',function:'RepEndoFertilityExt',input,score,ts:new Date().toISOString()}};

// TS: v3.50.50.0
