// Auto-generated by gen_p3master.py -- PCC 3.283.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.283.0';

function X273AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x273) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_273', function: 'X273AssessmentExt', input, score, ts: TS };
}

function X273ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x273) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_273', function: 'X273ScoreExt', input, score, ts: TS };
}

function X273StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x273) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_273', function: 'X273StageExt', input, score, ts: TS };
}

function X273PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x273) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_273', function: 'X273PlanExt', input, score, ts: TS };
}

function X273RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x273) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_273', function: 'X273RiskExt', input, score, ts: TS };
}

function X273DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x273) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_273', function: 'X273DoseExt', input, score, ts: TS };
}

function X273FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x273) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_273', function: 'X273FrequencyExt', input, score, ts: TS };
}

function X273DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x273) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_273', function: 'X273DurationExt', input, score, ts: TS };
}

function X273FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x273) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_273', function: 'X273FollowupExt', input, score, ts: TS };
}

function X273OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x273) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_273', function: 'X273OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X273AssessmentExt,
  X273ScoreExt,
  X273StageExt,
  X273PlanExt,
  X273RiskExt,
  X273DoseExt,
  X273FrequencyExt,
  X273DurationExt,
  X273FollowupExt,
  X273OutcomeExt,
};