// Auto-generated by gen_p3master.py -- PCC 3.313.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.313.0';

function X362AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x362) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_362', function: 'X362AssessmentExt', input, score, ts: TS };
}

function X362ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x362) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_362', function: 'X362ScoreExt', input, score, ts: TS };
}

function X362StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x362) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_362', function: 'X362StageExt', input, score, ts: TS };
}

function X362PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x362) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_362', function: 'X362PlanExt', input, score, ts: TS };
}

function X362RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x362) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_362', function: 'X362RiskExt', input, score, ts: TS };
}

function X362DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x362) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_362', function: 'X362DoseExt', input, score, ts: TS };
}

function X362FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x362) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_362', function: 'X362FrequencyExt', input, score, ts: TS };
}

function X362DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x362) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_362', function: 'X362DurationExt', input, score, ts: TS };
}

function X362FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x362) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_362', function: 'X362FollowupExt', input, score, ts: TS };
}

function X362OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x362) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_362', function: 'X362OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X362AssessmentExt,
  X362ScoreExt,
  X362StageExt,
  X362PlanExt,
  X362RiskExt,
  X362DoseExt,
  X362FrequencyExt,
  X362DurationExt,
  X362FollowupExt,
  X362OutcomeExt,
};