-- gi_102 reverse
BEGIN;
DROP TABLE IF EXISTS gi_102_results CASCADE;
DROP TABLE IF EXISTS gi_102_orders  CASCADE;
DROP TABLE IF EXISTS gi_102_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_GI_102_up';
COMMIT;
