// Auto_generated by gen_p3hl.py -- PCC v3.180.0
"use strict";
const TS = '2026-07-28T14:10:00Z';

function PediatricParkinsonExt(input) { const score = Math.round((0.3+Number(input.parkinson_score||2)*0.1)*100)/100; return { version:'3.180.0', module:'pcc_pediatric_neuro_ext70', function:"PediatricParkinsonExt", input, score, ts: TS }; }

function PediatricJPExt(input) { const score = Math.round((0.4+Number(input.gene||0)*0.15)*100)/100; return { version:'3.180.0', module:'pcc_pediatric_neuro_ext70', function:"PediatricJPExt", input, score, ts: TS }; }

function PediatricDystoniaExt(input) { const score = Math.round((0.35+Number(input.dystonia_score||3)*0.08)*100)/100; return { version:'3.180.0', module:'pcc_pediatric_neuro_ext70', function:"PediatricDystoniaExt", input, score, ts: TS }; }

function PediatricHuntingtonExt(input) { const score = Math.round((0.4+Number(input.repeats||40)*0.005)*100)/100; return { version:'3.180.0', module:'pcc_pediatric_neuro_ext70', function:"PediatricHuntingtonExt", input, score, ts: TS }; }

function PediatricWilsonExt(input) { const score = Math.round((0.4+Number(input.copper_urine||100)*0.003)*100)/100; return { version:'3.180.0', module:'pcc_pediatric_neuro_ext70', function:"PediatricWilsonExt", input, score, ts: TS }; }

function PediatricLeschNyhanExt(input) { const score = Math.round((0.4+Number(input.uric_acid||5)*0.07)*100)/100; return { version:'3.180.0', module:'pcc_pediatric_neuro_ext70', function:"PediatricLeschNyhanExt", input, score, ts: TS }; }

function PediatricNeurotransmitterExt(input) { const score = Math.round((0.4+Number(input.csf_neuro||0)*0.1)*100)/100; return { version:'3.180.0', module:'pcc_pediatric_neuro_ext70', function:"PediatricNeurotransmitterExt", input, score, ts: TS }; }

function PediatricAicardiExt(input) { const score = Math.round((0.4+Number(input.cysts_count||8)*0.04)*100)/100; return { version:'3.180.0', module:'pcc_pediatric_neuro_ext70', function:"PediatricAicardiExt", input, score, ts: TS }; }

function PediatricRettSyndromeExt(input) { const score = Math.round((0.4+Number(input.mecp2||0)*0.2)*100)/100; return { version:'3.180.0', module:'pcc_pediatric_neuro_ext70', function:"PediatricRettSyndromeExt", input, score, ts: TS }; }

function PediatricTouretteExt(input) { const score = Math.round((0.3+Number(input.ygtts||10)*0.04)*100)/100; return { version:'3.180.0', module:'pcc_pediatric_neuro_ext70', function:"PediatricTouretteExt", input, score, ts: TS }; }

module.exports = {
  PediatricParkinsonExt,
  PediatricJPExt,
  PediatricDystoniaExt,
  PediatricHuntingtonExt,
  PediatricWilsonExt,
  PediatricLeschNyhanExt,
  PediatricNeurotransmitterExt,
  PediatricAicardiExt,
  PediatricRettSyndromeExt,
  PediatricTouretteExt,
};