// filepath: pcc/pcc_pediatric_surg_ext165/pcc_pediatric_surg_ext165_engine.js
module.exports.version='v3.1.5.0';
module.exports.module='pcc_pediatric_surg_ext165';
module.exports.functions={};
module.exports.functions['PediatricHemispherSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pHemispherSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.5.0',module:'pcc_pediatric_surg_ext165',function:'PediatricHemispherSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVNSpedSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pVNSpedSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.5.0',module:'pcc_pediatric_surg_ext165',function:'PediatricVNSpedSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDBSpedSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pDBSpedSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.5.0',module:'pcc_pediatric_surg_ext165',function:'PediatricDBSpedSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCallosoSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pCallosoSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.5.0',module:'pcc_pediatric_surg_ext165',function:'PediatricCallosoSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLesionSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pLesionSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.5.0',module:'pcc_pediatric_surg_ext165',function:'PediatricLesionSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLaserAblSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pLaserAblSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.5.0',module:'pcc_pediatric_surg_ext165',function:'PediatricLaserAblSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRFablationSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pRFablSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.5.0',module:'pcc_pediatric_surg_ext165',function:'PediatricRFablationSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLITTSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pLITTSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.5.0',module:'pcc_pediatric_surg_ext165',function:'PediatricLITTSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStereoSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStereoSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.5.0',module:'pcc_pediatric_surg_ext165',function:'PediatricStereoSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricECOGguidedSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pECOGSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.5.0',module:'pcc_pediatric_surg_ext165',function:'PediatricECOGguidedSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.5.0
