// Auto-generated by gen_p3master.py -- PCC 3.277.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.277.0';

function X254AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x254) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_254', function: 'X254AssessmentExt', input, score, ts: TS };
}

function X254ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x254) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_254', function: 'X254ScoreExt', input, score, ts: TS };
}

function X254StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x254) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_254', function: 'X254StageExt', input, score, ts: TS };
}

function X254PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x254) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_254', function: 'X254PlanExt', input, score, ts: TS };
}

function X254RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x254) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_254', function: 'X254RiskExt', input, score, ts: TS };
}

function X254DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x254) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_254', function: 'X254DoseExt', input, score, ts: TS };
}

function X254FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x254) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_254', function: 'X254FrequencyExt', input, score, ts: TS };
}

function X254DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x254) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_254', function: 'X254DurationExt', input, score, ts: TS };
}

function X254FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x254) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_254', function: 'X254FollowupExt', input, score, ts: TS };
}

function X254OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x254) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_254', function: 'X254OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X254AssessmentExt,
  X254ScoreExt,
  X254StageExt,
  X254PlanExt,
  X254RiskExt,
  X254DoseExt,
  X254FrequencyExt,
  X254DurationExt,
  X254FollowupExt,
  X254OutcomeExt,
};