// Auto-generated by gen_p3master.py -- PCC 3.306.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.306.0';

function X341AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x341) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_341', function: 'X341AssessmentExt', input, score, ts: TS };
}

function X341ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x341) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_341', function: 'X341ScoreExt', input, score, ts: TS };
}

function X341StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x341) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_341', function: 'X341StageExt', input, score, ts: TS };
}

function X341PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x341) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_341', function: 'X341PlanExt', input, score, ts: TS };
}

function X341RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x341) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_341', function: 'X341RiskExt', input, score, ts: TS };
}

function X341DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x341) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_341', function: 'X341DoseExt', input, score, ts: TS };
}

function X341FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x341) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_341', function: 'X341FrequencyExt', input, score, ts: TS };
}

function X341DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x341) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_341', function: 'X341DurationExt', input, score, ts: TS };
}

function X341FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x341) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_341', function: 'X341FollowupExt', input, score, ts: TS };
}

function X341OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x341) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_341', function: 'X341OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X341AssessmentExt,
  X341ScoreExt,
  X341StageExt,
  X341PlanExt,
  X341RiskExt,
  X341DoseExt,
  X341FrequencyExt,
  X341DurationExt,
  X341FollowupExt,
  X341OutcomeExt,
};