// filepath: pcc/pcc_neuro_ext125/pcc_neuro_ext125_engine.js
module.exports.version='v3.224.0';
module.exports.module='pcc_neuro_ext125';
module.exports.functions={};
module.exports.functions['TrigeminalNeuralgiaExt2']=function(input){const score=Math.round((0.18 + Number(input.v2||1)*0.2 + Number(input.v3||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_neuro_ext125',function:'TrigeminalNeuralgiaExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthesiaDoloroExt']=function(input){const score=Math.round((0.18 + Number(input.v1||1)*0.2 + Number(input.burning||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_neuro_ext125',function:'AnesthesiaDoloroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PostherpeticNeuralgiaExt']=function(input){const score=Math.round((0.18 + Number(input.hzv||1)*0.2 + Number(input.duration||30)*0.01 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_neuro_ext125',function:'PostherpeticNeuralgiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OccipitalNeuralgiaExt2']=function(input){const score=Math.round((0.18 + Number(input.greater||1)*0.2 + Number(input.lesser||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_neuro_ext125',function:'OccipitalNeuralgiaExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['GlossopharyngealNeuralgiaExt']=function(input){const score=Math.round((0.18 + Number(input.pharynx||1)*0.2 + Number(input.swallow||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_neuro_ext125',function:'GlossopharyngealNeuralgiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NervusIntermediusExt']=function(input){const score=Math.round((0.18 + Number(input.ear||1)*0.2 + Number(input.taste||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_neuro_ext125',function:'NervusIntermediusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ClusterHeadacheExt2']=function(input){const score=Math.round((0.18 + Number(input.attack||3)*0.1 + Number(input.autonomic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_neuro_ext125',function:'ClusterHeadacheExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['SUNCTExt']=function(input){const score=Math.round((0.18 + Number(input.short||1)*0.2 + Number(input.unilateral||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_neuro_ext125',function:'SUNCTExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SUNAExt']=function(input){const score=Math.round((0.18 + Number(input.attack||1)*0.2 + Number(input.face||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_neuro_ext125',function:'SUNAExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ParoxysmalHemicraniaExt']=function(input){const score=Math.round((0.18 + Number(input.abs||1)*0.2 + Number(input.attack||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_neuro_ext125',function:'ParoxysmalHemicraniaExt',input,score,ts:new Date().toISOString()}};

// TS: v3.224.0
