// Auto-generated by gen_p3master.py -- PCC 3.301.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.301.0';

function X325AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x325) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_325', function: 'X325AssessmentExt', input, score, ts: TS };
}

function X325ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x325) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_325', function: 'X325ScoreExt', input, score, ts: TS };
}

function X325StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x325) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_325', function: 'X325StageExt', input, score, ts: TS };
}

function X325PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x325) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_325', function: 'X325PlanExt', input, score, ts: TS };
}

function X325RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x325) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_325', function: 'X325RiskExt', input, score, ts: TS };
}

function X325DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x325) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_325', function: 'X325DoseExt', input, score, ts: TS };
}

function X325FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x325) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_325', function: 'X325FrequencyExt', input, score, ts: TS };
}

function X325DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x325) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_325', function: 'X325DurationExt', input, score, ts: TS };
}

function X325FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x325) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_325', function: 'X325FollowupExt', input, score, ts: TS };
}

function X325OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x325) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_325', function: 'X325OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X325AssessmentExt,
  X325ScoreExt,
  X325StageExt,
  X325PlanExt,
  X325RiskExt,
  X325DoseExt,
  X325FrequencyExt,
  X325DurationExt,
  X325FollowupExt,
  X325OutcomeExt,
};