// filepath: pcc/pcc_pediatric_surg_ext100/pcc_pediatric_surg_ext100_engine.js
// pcc_pediatric_surg_ext100 engine (deterministic)
module.exports.version='v3.210.0';
module.exports.module='pcc_pediatric_surg_ext100';
module.exports.functions={};
module.exports.functions['PediatricEpilepsySxResectExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_surg_ext100',function:'PediatricEpilepsySxResectExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricFocalSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_surg_ext100',function:'PediatricFocalSxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricGeneralizedSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.vns||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_surg_ext100',function:'PediatricGeneralizedSxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStatusSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anesthesia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_surg_ext100',function:'PediatricStatusSxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricRefractorySxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.vns||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_surg_ext100',function:'PediatricRefractorySxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricEpilepsyVnsExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.vns||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_surg_ext100',function:'PediatricEpilepsyVnsExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricTemporalSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_surg_ext100',function:'PediatricTemporalSxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricFrontalSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_surg_ext100',function:'PediatricFrontalSxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricMyoclonicSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.vns||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_surg_ext100',function:'PediatricMyoclonicSxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricAbsenceSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||6)*0.04 + Number(input.aed||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_surg_ext100',function:'PediatricAbsenceSxExt',input,score,ts:new Date().toISOString()};};

// TS: v3.210.0
