// Auto-generated by gen_p3master.py -- PCC 3.313.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.313.0';

function X361AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x361) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_361', function: 'X361AssessmentExt', input, score, ts: TS };
}

function X361ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x361) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_361', function: 'X361ScoreExt', input, score, ts: TS };
}

function X361StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x361) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_361', function: 'X361StageExt', input, score, ts: TS };
}

function X361PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x361) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_361', function: 'X361PlanExt', input, score, ts: TS };
}

function X361RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x361) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_361', function: 'X361RiskExt', input, score, ts: TS };
}

function X361DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x361) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_361', function: 'X361DoseExt', input, score, ts: TS };
}

function X361FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x361) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_361', function: 'X361FrequencyExt', input, score, ts: TS };
}

function X361DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x361) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_361', function: 'X361DurationExt', input, score, ts: TS };
}

function X361FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x361) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_361', function: 'X361FollowupExt', input, score, ts: TS };
}

function X361OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x361) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_361', function: 'X361OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X361AssessmentExt,
  X361ScoreExt,
  X361StageExt,
  X361PlanExt,
  X361RiskExt,
  X361DoseExt,
  X361FrequencyExt,
  X361DurationExt,
  X361FollowupExt,
  X361OutcomeExt,
};