// filepath: pcc/pcc_sports_ext100/pcc_sports_ext100_engine.js
module.exports.version='v3.24.24.0';
module.exports.module='pcc_sports_ext100';
module.exports.functions={};
module.exports.functions['SportInjuryExt']=function(input){const score=Math.round((0.18 + Number(input.spInjury||1)*0.2 + Number(input.injuryType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_sports_ext100',function:'SportInjuryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SportConcussionExt']=function(input){const score=Math.round((0.18 + Number(input.spConcuss||1)*0.2 + Number(input.scatScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_sports_ext100',function:'SportConcussionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SportCardiacExt']=function(input){const score=Math.round((0.18 + Number(input.spCardiac||1)*0.2 + Number(input.athleteEF||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_sports_ext100',function:'SportCardiacExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SportNutritionExt']=function(input){const score=Math.round((0.18 + Number(input.spNutr||1)*0.2 + Number(input.athleteBmi||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_sports_ext100',function:'SportNutritionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SportRehabExt']=function(input){const score=Math.round((0.18 + Number(input.spRehab||1)*0.2 + Number(input.rtp||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_sports_ext100',function:'SportRehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SportDopingExt']=function(input){const score=Math.round((0.18 + Number(input.spDoping||1)*0.2 + Number(input.bannedSub||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_sports_ext100',function:'SportDopingExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SportPediatricExt']=function(input){const score=Math.round((0.18 + Number(input.spPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_sports_ext100',function:'SportPediatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SportFemaleExt']=function(input){const score=Math.round((0.18 + Number(input.spFemale||1)*0.2 + Number(input.femaleAthleteTriad||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_sports_ext100',function:'SportFemaleExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SportEnduranceExt']=function(input){const score=Math.round((0.18 + Number(input.spEndur||1)*0.2 + Number(input.vo2max||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_sports_ext100',function:'SportEnduranceExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SportExtremeExt']=function(input){const score=Math.round((0.18 + Number(input.spExtreme||1)*0.2 + Number(input.altitude||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.24.24.0',module:'pcc_sports_ext100',function:'SportExtremeExt',input,score,ts:new Date().toISOString()}};

// TS: v3.24.24.0
