// Auto-generated by gen_p3id.py -- PCC v3.184.0
"use strict";
const TS = '2026-07-28T14:50:00Z';

function PediatricTonsillectomyExt(input) { const score = Math.round((0.4+Number(input.tonsil_grade||3)*0.08)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_surg_ext74', function:'PediatricTonsillectomyExt', input, score, ts: TS }; }

function PediatricAdenoidectomyExt(input) { const score = Math.round((0.4+Number(input.adenoid_size||3)*0.08)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_surg_ext74', function:'PediatricAdenoidectomyExt', input, score, ts: TS }; }

function PediatricUvulopalatoplastyExt(input) { const score = Math.round((0.4+Number(input.snore_score||3)*0.1)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_surg_ext74', function:'PediatricUvulopalatoplastyExt', input, score, ts: TS }; }

function PediatricCPAPInitExt(input) { const score = Math.round((0.3+Number(input.tolerance||3)*0.1)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_surg_ext74', function:'PediatricCPAPInitExt', input, score, ts: TS }; }

function PediatricBiPAPInitExt(input) { const score = Math.round((0.3+Number(input.bipap||3)*0.1)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_surg_ext74', function:'PediatricBiPAPInitExt', input, score, ts: TS }; }

function PediatricCPAPFollowExt(input) { const score = Math.round((0.3+Number(input.hours||5)*0.05)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_surg_ext74', function:'PediatricCPAPFollowExt', input, score, ts: TS }; }

function PediatricCranialRemodelingExt(input) { const score = Math.round((0.4+Number(input.age||6)*0.04)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_surg_ext74', function:'PediatricCranialRemodelingExt', input, score, ts: TS }; }

function PediatricPharyngoplastyExt(input) { const score = Math.round((0.4+Number(input.airway_score||3)*0.1)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_surg_ext74', function:'PediatricPharyngoplastyExt', input, score, ts: TS }; }

function PediatricMaxillaryMandibularExt(input) { const score = Math.round((0.5+Number(input.occlusion||3)*0.1)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_surg_ext74', function:'PediatricMaxillaryMandibularExt', input, score, ts: TS }; }

function PediatricTracheostomyExt(input) { const score = Math.round((0.5+Number(input.airway_score||1)*0.2)*100)/100; return { version:'3.184.0', module:'pcc_pediatric_surg_ext74', function:'PediatricTracheostomyExt', input, score, ts: TS }; }

module.exports = {
  PediatricTonsillectomyExt,
  PediatricAdenoidectomyExt,
  PediatricUvulopalatoplastyExt,
  PediatricCPAPInitExt,
  PediatricBiPAPInitExt,
  PediatricCPAPFollowExt,
  PediatricCranialRemodelingExt,
  PediatricPharyngoplastyExt,
  PediatricMaxillaryMandibularExt,
  PediatricTracheostomyExt,
};