// filepath: pcc/pcc_pediatric_surg_ext109/pcc_pediatric_surg_ext109_engine.js
module.exports.version='v3.219.0';
module.exports.module='pcc_pediatric_surg_ext109';
module.exports.functions={};
module.exports.functions['PediatricPinealSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_surg_ext109',function:'PediatricPinealSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPituitarySxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.transsphenoidal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_surg_ext109',function:'PediatricPituitarySxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCranioSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_surg_ext109',function:'PediatricCranioSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOpticGliomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.chemo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_surg_ext109',function:'PediatricOpticGliomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainstemGliomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.radiation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_surg_ext109',function:'PediatricBrainstemGliomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCerebellarAstroSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_surg_ext109',function:'PediatricCerebellarAstroSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMedulloblastomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_surg_ext109',function:'PediatricMedulloblastomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEpendymomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_surg_ext109',function:'PediatricEpendymomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCPTSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_surg_ext109',function:'PediatricCPTSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGCTSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.radiation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.219.0',module:'pcc_pediatric_surg_ext109',function:'PediatricGCTSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.219.0
