// filepath: pcc/pcc_pediatric_neuro_ext162/pcc_pediatric_neuro_ext162_engine.js
module.exports.version='v3.1.2.0';
module.exports.module='pcc_pediatric_neuro_ext162';
module.exports.functions={};
module.exports.functions['PediatricStroke2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStroke2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_pediatric_neuro_ext162',function:'PediatricStroke2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSAH2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pSAH2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_pediatric_neuro_ext162',function:'PediatricSAH2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricICH2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pICH2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_pediatric_neuro_ext162',function:'PediatricICH2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeonatalStroke2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pNeoStroke2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_pediatric_neuro_ext162',function:'PediatricNeonatalStroke2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPFOstrokeExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pPFO||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_pediatric_neuro_ext162',function:'PediatricPFOstrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSickleStroke2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.sickleStroke2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_pediatric_neuro_ext162',function:'PediatricSickleStroke2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSinusThromb2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSinus2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_pediatric_neuro_ext162',function:'PediatricSinusThromb2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeRecoveryExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeRecov||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_pediatric_neuro_ext162',function:'PediatricStrokeRecoveryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPostStrokeEpilepsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pPostSzEpi||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_pediatric_neuro_ext162',function:'PediatricPostStrokeEpilepsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVasculitisStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pVasculitisStroke||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_pediatric_neuro_ext162',function:'PediatricVasculitisStrokeExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.2.0
