// filepath: pcc/pcc_pediatric_surg_ext105/pcc_pediatric_surg_ext105_engine.js
module.exports.version='v3.215.0';
module.exports.module='pcc_pediatric_surg_ext105';
module.exports.functions={};
module.exports.functions['PediatricSCISxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_surg_ext105',function:'PediatricSCISxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTetraSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ventilator||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_surg_ext105',function:'PediatricTetraSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricParaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.rehab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_surg_ext105',function:'PediatricParaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBSSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_surg_ext105',function:'PediatricBSSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAnteriorSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.decompression||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_surg_ext105',function:'PediatricAnteriorSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCentralSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_surg_ext105',function:'PediatricCentralSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCaudaEquinaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.decompression||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_surg_ext105',function:'PediatricCaudaEquinaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricConusSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_surg_ext105',function:'PediatricConusSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinalShockSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.supportive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_surg_ext105',function:'PediatricSpinalShockSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricADRsxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.sympathectomy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.215.0',module:'pcc_pediatric_surg_ext105',function:'PediatricADRsxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.215.0
