// Auto-generated by gen_p3master.py -- PCC 3.291.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.291.0';

function X295AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x295) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_295', function: 'X295AssessmentExt', input, score, ts: TS };
}

function X295ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x295) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_295', function: 'X295ScoreExt', input, score, ts: TS };
}

function X295StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x295) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_295', function: 'X295StageExt', input, score, ts: TS };
}

function X295PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x295) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_295', function: 'X295PlanExt', input, score, ts: TS };
}

function X295RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x295) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_295', function: 'X295RiskExt', input, score, ts: TS };
}

function X295DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x295) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_295', function: 'X295DoseExt', input, score, ts: TS };
}

function X295FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x295) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_295', function: 'X295FrequencyExt', input, score, ts: TS };
}

function X295DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x295) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_295', function: 'X295DurationExt', input, score, ts: TS };
}

function X295FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x295) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_295', function: 'X295FollowupExt', input, score, ts: TS };
}

function X295OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x295) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_295', function: 'X295OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X295AssessmentExt,
  X295ScoreExt,
  X295StageExt,
  X295PlanExt,
  X295RiskExt,
  X295DoseExt,
  X295FrequencyExt,
  X295DurationExt,
  X295FollowupExt,
  X295OutcomeExt,
};