// Auto_generated by gen_p3ha.py -- PCC v3.169.0
"use strict";
const TS = '2026-07-28T12:20:00Z';

function PediatricMSExt(input) { const score = Math.round((0.3+Number(input.edss||3)*0.05)*100)/100; return { version:'3.169.0', module:'pcc_pediatric_neuro_ext59', function:"PediatricMSExt", input, score, ts: TS }; }

function PediatricMSRelapseExt(input) { const score = Math.round((0.4+Number(input.relapse_count||1)*0.1)*100)/100; return { version:'3.169.0', module:'pcc_pediatric_neuro_ext59', function:"PediatricMSRelapseExt", input, score, ts: TS }; }

function PediatricMSProgressionExt(input) { const score = Math.round((0.35+Number(input.brain_volume_change||3)*0.04)*100)/100; return { version:'3.169.0', module:'pcc_pediatric_neuro_ext59', function:"PediatricMSProgressionExt", input, score, ts: TS }; }

function PediatricDMTManagementExt(input) { const score = Math.round((0.3+Number(input.dmt_index||1)*0.05)*100)/100; return { version:'3.169.0', module:'pcc_pediatric_neuro_ext59', function:"PediatricDMTManagementExt", input, score, ts: TS }; }

function PediatricNMOSDExt(input) { const score = Math.round((0.4+Number(input.aquaporin||0)*0.15)*100)/100; return { version:'3.169.0', module:'pcc_pediatric_neuro_ext59', function:"PediatricNMOSDExt", input, score, ts: TS }; }

function PediatricMOGAntibodyExt(input) { const score = Math.round((0.4+Number(input.mog_titer||0)*0.04)*100)/100; return { version:'3.169.0', module:'pcc_pediatric_neuro_ext59', function:"PediatricMOGAntibodyExt", input, score, ts: TS }; }

function PediatricADEMExt(input) { const score = Math.round((0.45+Number(input.lesion_count||10)*0.025)*100)/100; return { version:'3.169.0', module:'pcc_pediatric_neuro_ext59', function:"PediatricADEMExt", input, score, ts: TS }; }

function PediatricOpticNeuritisExt(input) { const score = Math.round((0.35+Number(input.visual_loss_pct||50)*0.01)*100)/100; return { version:'3.169.0', module:'pcc_pediatric_neuro_ext59', function:"PediatricOpticNeuritisExt", input, score, ts: TS }; }

function PediatricTransverseMyelitisExt(input) { const score = Math.round((0.4+Number(input.lesion_length||5)*0.05)*100)/100; return { version:'3.169.0', module:'pcc_pediatric_neuro_ext59', function:"PediatricTransverseMyelitisExt", input, score, ts: TS }; }

function PediatricMSRehabExt(input) { const score = Math.round((0.3+Number(input.cog_score||10)*0.04)*100)/100; return { version:'3.169.0', module:'pcc_pediatric_neuro_ext59', function:"PediatricMSRehabExt", input, score, ts: TS }; }

module.exports = {
  PediatricMSExt,
  PediatricMSRelapseExt,
  PediatricMSProgressionExt,
  PediatricDMTManagementExt,
  PediatricNMOSDExt,
  PediatricMOGAntibodyExt,
  PediatricADEMExt,
  PediatricOpticNeuritisExt,
  PediatricTransverseMyelitisExt,
  PediatricMSRehabExt,
};