// filepath: pcc/pcc_neurosciences_ext102/pcc_neurosciences_ext102_engine.js
module.exports.version='v3.61.61.0';
module.exports.module='pcc_neurosciences_ext102';
module.exports.functions={};
module.exports.functions['NScGenExt']=function(input){const score=Math.round((0.18 + Number(input.nxGen||1)*0.2 + Number(input.nxGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_neurosciences_ext102',function:'NScGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NScStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.nxStr||1)*0.2 + Number(input.nxStrNIHSS||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_neurosciences_ext102',function:'NScStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NScSeizureExt']=function(input){const score=Math.round((0.18 + Number(input.nxSei||1)*0.2 + Number(input.nxSeiType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_neurosciences_ext102',function:'NScSeizureExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NScHeadacheExt']=function(input){const score=Math.round((0.18 + Number(input.nxHA||1)*0.2 + Number(input.nxHAScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_neurosciences_ext102',function:'NScHeadacheExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NScMovementExt']=function(input){const score=Math.round((0.18 + Number(input.nxMov||1)*0.2 + Number(input.nxMovType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_neurosciences_ext102',function:'NScMovementExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NScDementiaExt']=function(input){const score=Math.round((0.18 + Number(input.nxDem||1)*0.2 + Number(input.nxDemMMSE||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_neurosciences_ext102',function:'NScDementiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NScMSext']=function(input){const score=Math.round((0.18 + Number(input.nxMS||1)*0.2 + Number(input.nxMSEDSS||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_neurosciences_ext102',function:'NScMSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['NScNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.nxNeu||1)*0.2 + Number(input.nxNeuType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_neurosciences_ext102',function:'NScNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NScEMGext']=function(input){const score=Math.round((0.18 + Number(input.nxEMG||1)*0.2 + Number(input.nxEMGtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_neurosciences_ext102',function:'NScEMGext',input,score,ts:new Date().toISOString()}};
module.exports.functions['NScEEGext']=function(input){const score=Math.round((0.18 + Number(input.nxEEG||1)*0.2 + Number(input.nxEEGtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.61.61.0',module:'pcc_neurosciences_ext102',function:'NScEEGext',input,score,ts:new Date().toISOString()}};

// TS: v3.61.61.0
