// filepath: pcc/pcc_pediatric_surg_ext118/pcc_pediatric_surg_ext118_engine.js
module.exports.version='v3.228.0';
module.exports.module='pcc_pediatric_surg_ext118';
module.exports.functions={};
module.exports.functions['PediatricCADAntiExt2']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.228.0',module:'pcc_pediatric_surg_ext118',function:'PediatricCADAntiExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVADAntiExt2']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.228.0',module:'pcc_pediatric_surg_ext118',function:'PediatricVADAntiExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCDissectAntiExt2']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.228.0',module:'pcc_pediatric_surg_ext118',function:'PediatricCDissectAntiExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIADStentExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.228.0',module:'pcc_pediatric_surg_ext118',function:'PediatricIADStentExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPPDissectAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.228.0',module:'pcc_pediatric_surg_ext118',function:'PediatricPPDissectAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTraumaticDissectSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.228.0',module:'pcc_pediatric_surg_ext118',function:'PediatricTraumaticDissectSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpontDissectAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.228.0',module:'pcc_pediatric_surg_ext118',function:'PediatricSpontDissectAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRecDissectAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.228.0',module:'pcc_pediatric_surg_ext118',function:'PediatricRecDissectAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBilatDissectAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.228.0',module:'pcc_pediatric_surg_ext118',function:'PediatricBilatDissectAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPseudoCoilExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.coil||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.228.0',module:'pcc_pediatric_surg_ext118',function:'PediatricPseudoCoilExt',input,score,ts:new Date().toISOString()}};

// TS: v3.228.0
