// Auto-generated by gen_p3master.py -- PCC 3.296.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.296.0';

function X310AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x310) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_310', function: 'X310AssessmentExt', input, score, ts: TS };
}

function X310ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x310) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_310', function: 'X310ScoreExt', input, score, ts: TS };
}

function X310StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x310) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_310', function: 'X310StageExt', input, score, ts: TS };
}

function X310PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x310) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_310', function: 'X310PlanExt', input, score, ts: TS };
}

function X310RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x310) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_310', function: 'X310RiskExt', input, score, ts: TS };
}

function X310DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x310) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_310', function: 'X310DoseExt', input, score, ts: TS };
}

function X310FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x310) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_310', function: 'X310FrequencyExt', input, score, ts: TS };
}

function X310DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x310) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_310', function: 'X310DurationExt', input, score, ts: TS };
}

function X310FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x310) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_310', function: 'X310FollowupExt', input, score, ts: TS };
}

function X310OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x310) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_310', function: 'X310OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X310AssessmentExt,
  X310ScoreExt,
  X310StageExt,
  X310PlanExt,
  X310RiskExt,
  X310DoseExt,
  X310FrequencyExt,
  X310DurationExt,
  X310FollowupExt,
  X310OutcomeExt,
};