import os
MODULES=['pcc_lab_ext166','pcc_path_ext177','pcc_rad_ext177']
FUNCS={
'pcc_lab_ext166':[('LabImmunoAdultExt','0.18 + Number(input.labImmuno||1)*0.2 + Number(input.antibody||1)*0.2 + Number(input.outcome||1)*0.2'),('LabRheumatoidAdultExt','0.18 + Number(input.rf||1)*0.2 + Number(input.ccp||1)*0.2 + Number(input.outcome||1)*0.2'),('LabANCAadultExt','0.18 + Number(input.ancaAdult||1)*0.2 + Number(input.pr3||1)*0.2 + Number(input.outcome||1)*0.2'),('LabLupusAdultExt','0.18 + Number(input.lupusAdult||1)*0.2 + Number(input.dsDNA||1)*0.2 + Number(input.outcome||1)*0.2'),('LabCeliacAdultExt','0.18 + Number(input.celiacAdult||1)*0.2 + Number(input.tTG||1)*0.2 + Number(input.outcome||1)*0.2'),('LabHIVAdultExt','0.18 + Number(input.hivAdult||1)*0.2 + Number(input.cd4||1)*0.04 + Number(input.outcome||1)*0.2'),('LabHepBAdultExt','0.18 + Number(input.hepBAdult||1)*0.2 + Number(input.hbsAg||1)*0.2 + Number(input.outcome||1)*0.2'),('LabHepCAdultExt','0.18 + Number(input.hepCAdult||1)*0.2 + Number(input.hcvRNA||1)*0.2 + Number(input.outcome||1)*0.2'),('LabSyphilisAdultExt','0.18 + Number(input.syphilisAdult||1)*0.2 + Number(input.rpr||1)*0.2 + Number(input.outcome||1)*0.2'),('LabB12AdultExt','0.18 + Number(input.b12Adult||1)*0.2 + Number(input.b12Level||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_path_ext177':[('PathImmunoExt','0.18 + Number(input.pathImmuno||1)*0.2 + Number(input.biopsyType||1)*0.2 + Number(input.outcome||1)*0.2'),('PathRheumatoidExt','0.18 + Number(input.pathRF||1)*0.2 + Number(input.synovialPath||1)*0.2 + Number(input.outcome||1)*0.2'),('PathVasculitisExt','0.18 + Number(input.pathVasculitis||1)*0.2 + Number(input.vesselSize||1)*0.2 + Number(input.outcome||1)*0.2'),('PathLupusExt','0.18 + Number(input.pathLupus||1)*0.2 + Number(input.classCriteria||1)*0.2 + Number(input.outcome||1)*0.2'),('PathSclerodermaExt','0.18 + Number(input.pathSclero||1)*0.2 + Number(input.skinBiopsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PathMyositisExt','0.18 + Number(input.pathMyo||1)*0.2 + Number(input.muscleBiopsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PathSarcoidosisExt','0.18 + Number(input.pathSarco||1)*0.2 + Number(input.nonCaseating||1)*0.2 + Number(input.outcome||1)*0.2'),('PathIBDext','0.18 + Number(input.pathIBD||1)*0.2 + Number(input.crohnVsUC||1)*0.2 + Number(input.outcome||1)*0.2'),('PathCeliacExt','0.18 + Number(input.pathCeliac||1)*0.2 + Number(input.marshScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PathAmyloidExt','0.18 + Number(input.pathAmyloid||1)*0.2 + Number(input.congoRed||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_rad_ext177':[('RadImmunoAdultExt','0.18 + Number(input.radImmuno||1)*0.2 + Number(input.imagingModality||1)*0.2 + Number(input.outcome||1)*0.2'),('RadRheumatoidAdultExt','0.18 + Number(input.radRA||1)*0.2 + Number(input.erosionScore||1)*0.04 + Number(input.outcome||1)*0.2'),('RadVasculitisAdultExt','0.18 + Number(input.radVasculitis||1)*0.2 + Number(input.mra||1)*0.2 + Number(input.outcome||1)*0.2'),('RadSLEadultExt','0.18 + Number(input.radSLE||1)*0.2 + Number(input.sleImaging||1)*0.2 + Number(input.outcome||1)*0.2'),('RadSScadultExt','0.18 + Number(input.radSSC||1)*0.2 + Number(input.sscImaging||1)*0.2 + Number(input.outcome||1)*0.2'),('RadMyositisAdultExt','0.18 + Number(input.radMyositis||1)*0.2 + Number(input.mriMuscle||1)*0.2 + Number(input.outcome||1)*0.2'),('RadSarcoidAdultExt','0.18 + Number(input.radSarcoid||1)*0.2 + Number(input.sarcoidStage||1)*0.04 + Number(input.outcome||1)*0.2'),('RadIBDadultExt','0.18 + Number(input.radIBD||1)*0.2 + Number(input.mre||1)*0.2 + Number(input.outcome||1)*0.2'),('RadCeliacAdultExt','0.18 + Number(input.radCeliac||1)*0.2 + Number(input.capsuleEndoscopy||1)*0.2 + Number(input.outcome||1)*0.2'),('RadAmyloidAdultExt','0.18 + Number(input.radAmyloid||1)*0.2 + Number(input.dpdScan||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.13.13.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.13.13.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.13.13.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.13.13.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LM v3.13.13.0 done')