import os
MODULES=['pcc_preventive_medicine_ext102','pcc_lifestyle_medicine_ext102','pcc_wellness_ext102']
FUNCS={
'pcc_preventive_medicine_ext102':[('PrevPrimExt','0.18 + Number(input.pmPrim||1)*0.2 + Number(input.pmPrimType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevSecExt','0.18 + Number(input.pmSec||1)*0.2 + Number(input.pmSecType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevTertExt','0.18 + Number(input.pmTert||1)*0.2 + Number(input.pmTertType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevVaccExt','0.18 + Number(input.pmVacc||1)*0.2 + Number(input.pmVaccType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevScreenExt','0.18 + Number(input.pmScreen||1)*0.2 + Number(input.pmScreenType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevCounselExt','0.18 + Number(input.pmCounsel||1)*0.2 + Number(input.pmCounselType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevRiskRedExt','0.18 + Number(input.pmRisk||1)*0.2 + Number(input.pmRiskLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('PrevChemoprophExt','0.18 + Number(input.pmChem||1)*0.2 + Number(input.pmChemType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevHealthPromExt','0.18 + Number(input.pmPromo||1)*0.2 + Number(input.pmPromoType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevAdherenceExt','0.18 + Number(input.pmAdh||1)*0.2 + Number(input.pmAdhRate||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_lifestyle_medicine_ext102':[('LifeExerciseExt','0.18 + Number(input.lmEx||1)*0.2 + Number(input.lmExMin||1)*0.04 + Number(input.outcome||1)*0.2'),('LifeDietExt','0.18 + Number(input.lmDiet||1)*0.2 + Number(input.lmDietType||1)*0.2 + Number(input.outcome||1)*0.2'),('LifeSleepExt','0.18 + Number(input.lmSleep||1)*0.2 + Number(input.lmSleepHr||1)*0.04 + Number(input.outcome||1)*0.2'),('LifeStressExt','0.18 + Number(input.lmStress||1)*0.2 + Number(input.lmStressScore||1)*0.04 + Number(input.outcome||1)*0.2'),('LifeSmokeExt','0.18 + Number(input.lmSmoke||1)*0.2 + Number(input.lmSmokePack||1)*0.04 + Number(input.outcome||1)*0.2'),('LifeAlcoholExt','0.18 + Number(input.lmAlc||1)*0.2 + Number(input.lmAlcDrinks||1)*0.04 + Number(input.outcome||1)*0.2'),('LifeWeightExt','0.18 + Number(input.lmWt||1)*0.2 + Number(input.lmWtBMI||1)*0.04 + Number(input.outcome||1)*0.2'),('LifeMindfulExt','0.18 + Number(input.lmMind||1)*0.2 + Number(input.lmMindType||1)*0.2 + Number(input.outcome||1)*0.2'),('LifeSocialExt','0.18 + Number(input.lmSoc||1)*0.2 + Number(input.lmSocScore||1)*0.04 + Number(input.outcome||1)*0.2'),('LifeGoalsExt','0.18 + Number(input.lmGoal||1)*0.2 + Number(input.lmGoalType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_wellness_ext102':[('WellIntegralExt','0.18 + Number(input.wlInt||1)*0.2 + Number(input.wlIntScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellNutritionExt','0.18 + Number(input.wlNut||1)*0.2 + Number(input.wlNutScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellFitnessExt','0.18 + Number(input.wlFit||1)*0.2 + Number(input.wlFitScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellMindfulnessExt','0.18 + Number(input.wlMind||1)*0.2 + Number(input.wlMindScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellResilienceExt','0.18 + Number(input.wlRes||1)*0.2 + Number(input.wlResScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellConnectionExt','0.18 + Number(input.wlConn||1)*0.2 + Number(input.wlConnScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellPurposeExt','0.18 + Number(input.wlPurp||1)*0.2 + Number(input.wlPurpScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellEnergyExt','0.18 + Number(input.wlEn||1)*0.2 + Number(input.wlEnScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellRecoveryExt','0.18 + Number(input.wlRec||1)*0.2 + Number(input.wlRecScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellCheckExt','0.18 + Number(input.wlChk||1)*0.2 + Number(input.wlChkScore||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.47.47.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.47.47.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.47.47.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.47.47.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MU v3.47.47.0 done')