import os
MODULES=['pcc_neuro_ext125','pcc_pediatric_neuro_ext114','pcc_pediatric_surg_ext114']
FUNCS={
'pcc_neuro_ext125':[('TrigeminalNeuralgiaExt2','0.18 + Number(input.v2||1)*0.2 + Number(input.v3||1)*0.2 + Number(input.outcome||1)*0.2'),('AnesthesiaDoloroExt','0.18 + Number(input.v1||1)*0.2 + Number(input.burning||1)*0.2 + Number(input.outcome||1)*0.2'),('PostherpeticNeuralgiaExt','0.18 + Number(input.hzv||1)*0.2 + Number(input.duration||30)*0.01 + Number(input.outcome||1)*0.2'),('OccipitalNeuralgiaExt2','0.18 + Number(input.greater||1)*0.2 + Number(input.lesser||1)*0.2 + Number(input.outcome||1)*0.2'),('GlossopharyngealNeuralgiaExt','0.18 + Number(input.pharynx||1)*0.2 + Number(input.swallow||1)*0.2 + Number(input.outcome||1)*0.2'),('NervusIntermediusExt','0.18 + Number(input.ear||1)*0.2 + Number(input.taste||1)*0.2 + Number(input.outcome||1)*0.2'),('ClusterHeadacheExt2','0.18 + Number(input.attack||3)*0.1 + Number(input.autonomic||1)*0.2 + Number(input.outcome||1)*0.2'),('SUNCTExt','0.18 + Number(input.short||1)*0.2 + Number(input.unilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('SUNAExt','0.18 + Number(input.attack||1)*0.2 + Number(input.face||1)*0.2 + Number(input.outcome||1)*0.2'),('ParoxysmalHemicraniaExt','0.18 + Number(input.abs||1)*0.2 + Number(input.attack||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext114':[('PediatricTNExt2','0.18 + Number(input.age||10)*0.04 + Number(input.tn||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAnesthesiaDoloroExt','0.18 + Number(input.age||10)*0.04 + Number(input.v1||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPHNext','0.18 + Number(input.age||10)*0.04 + Number(input.hzv||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricONext2','0.18 + Number(input.age||8)*0.04 + Number(input.occipital||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGPNExt2','0.18 + Number(input.age||10)*0.04 + Number(input.pharynx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNIext','0.18 + Number(input.age||10)*0.04 + Number(input.ear||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricClusterExt2','0.18 + Number(input.age||12)*0.02 + Number(input.attack||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSUNCExt','0.18 + Number(input.age||10)*0.04 + Number(input.short||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSUNAExt','0.18 + Number(input.age||10)*0.04 + Number(input.face||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPHExt','0.18 + Number(input.age||10)*0.04 + Number(input.abs||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext114':[('PediatricTNMVDext','0.18 + Number(input.age||10)*0.04 + Number(input.mvd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAnesthesiaDoloroSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.mvd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPHNsxExt','0.18 + Number(input.age||10)*0.04 + Number(input.dorsalRoot||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricONsxExt','0.18 + Number(input.age||8)*0.04 + Number(input.nerveBlock||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGPNsxExt','0.18 + Number(input.age||10)*0.04 + Number(input.mvd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNIsxExt','0.18 + Number(input.age||10)*0.04 + Number(input.mvd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricClusterStimExt','0.18 + Number(input.age||12)*0.02 + Number(input.dbs||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSUNCTsxExt','0.18 + Number(input.age||10)*0.04 + Number(input.lamotrigine||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSUNAsxExt','0.18 + Number(input.age||10)*0.04 + Number(input.lamotrigine||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPHsxExt','0.18 + Number(input.age||10)*0.04 + Number(input.indomethacin||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.224.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.224.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.224.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.224.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-JR v3.224.0 done')
