import os
MODULES=['pcc_infectious_disease_ext102','pcc_tropical_medicine_ext102','pcc_stds_ext102']
FUNCS={
'pcc_infectious_disease_ext102':[('InfGenExt','0.18 + Number(input.idGen||1)*0.2 + Number(input.idGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('InfSepsisExt','0.18 + Number(input.idSep||1)*0.2 + Number(input.idSepScore||1)*0.04 + Number(input.outcome||1)*0.2'),('InfMeningExt','0.18 + Number(input.idMen||1)*0.2 + Number(input.idMenType||1)*0.2 + Number(input.outcome||1)*0.2'),('InfEndoExt','0.18 + Number(input.idEndo||1)*0.2 + Number(input.idEndoType||1)*0.2 + Number(input.outcome||1)*0.2'),('InfCellulitisExt','0.18 + Number(input.idCel||1)*0.2 + Number(input.idCelScore||1)*0.04 + Number(input.outcome||1)*0.2'),('InfUTIext','0.18 + Number(input.idUTI||1)*0.2 + Number(input.idUTItype||1)*0.2 + Number(input.outcome||1)*0.2'),('InfPneumExt','0.18 + Number(input.idPneu||1)*0.2 + Number(input.idPneuType||1)*0.2 + Number(input.outcome||1)*0.2'),('InfDiarrheaExt','0.18 + Number(input.idDiar||1)*0.2 + Number(input.idDiarType||1)*0.2 + Number(input.outcome||1)*0.2'),('InfTBext','0.18 + Number(input.idTB||1)*0.2 + Number(input.idTBType||1)*0.2 + Number(input.outcome||1)*0.2'),('InfHIVext','0.18 + Number(input.idHIV||1)*0.2 + Number(input.idHIVCD4||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_tropical_medicine_ext102':[('TrpGenExt','0.18 + Number(input.tpGen||1)*0.2 + Number(input.tpGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('TrpMalariaExt','0.18 + Number(input.tpMal||1)*0.2 + Number(input.tpMalType||1)*0.2 + Number(input.outcome||1)*0.2'),('TrpDengueExt','0.18 + Number(input.tpDen||1)*0.2 + Number(input.tpDenType||1)*0.2 + Number(input.outcome||1)*0.2'),('TrpCholeraExt','0.18 + Number(input.tpCho||1)*0.2 + Number(input.tpChoType||1)*0.2 + Number(input.outcome||1)*0.2'),('TrpTyphoidExt','0.18 + Number(input.tpTyp||1)*0.2 + Number(input.tpTypType||1)*0.2 + Number(input.outcome||1)*0.2'),('TrpHepAext','0.18 + Number(input.tpHA||1)*0.2 + Number(input.tpHAtype||1)*0.2 + Number(input.outcome||1)*0.2'),('TrpHepBext','0.18 + Number(input.tpHB||1)*0.2 + Number(input.tpHBtype||1)*0.2 + Number(input.outcome||1)*0.2'),('TrpSchistoExt','0.18 + Number(input.tpSch||1)*0.2 + Number(input.tpSchType||1)*0.2 + Number(input.outcome||1)*0.2'),('TrpLeishExt','0.18 + Number(input.tpLei||1)*0.2 + Number(input.tpLeiType||1)*0.2 + Number(input.outcome||1)*0.2'),('TrpTravelExt','0.18 + Number(input.tpTrv||1)*0.2 + Number(input.tpTrvType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_stds_ext102':[('StdGenExt','0.18 + Number(input.stGen||1)*0.2 + Number(input.stGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('StdHIVext','0.18 + Number(input.stHIV||1)*0.2 + Number(input.stHIVCD4||1)*0.04 + Number(input.outcome||1)*0.2'),('StdSyphilisExt','0.18 + Number(input.stSyp||1)*0.2 + Number(input.stSypStage||1)*0.04 + Number(input.outcome||1)*0.2'),('StdGonorrheaExt','0.18 + Number(input.stGon||1)*0.2 + Number(input.stGonType||1)*0.2 + Number(input.outcome||1)*0.2'),('StdChlamydiaExt','0.18 + Number(input.stChl||1)*0.2 + Number(input.stChlType||1)*0.2 + Number(input.outcome||1)*0.2'),('StdHepBext','0.18 + Number(input.stHB||1)*0.2 + Number(input.stHBtype||1)*0.2 + Number(input.outcome||1)*0.2'),('StdHPVext','0.18 + Number(input.stHPV||1)*0.2 + Number(input.stHPVType||1)*0.2 + Number(input.outcome||1)*0.2'),('StdHSVext','0.18 + Number(input.stHSV||1)*0.2 + Number(input.stHSVtype||1)*0.2 + Number(input.outcome||1)*0.2'),('StdPIDext','0.18 + Number(input.stPID||1)*0.2 + Number(input.stPIDscore||1)*0.04 + Number(input.outcome||1)*0.2'),('StdPreventExt','0.18 + Number(input.stPrev||1)*0.2 + Number(input.stPrevType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.59.59.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.59.59.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.59.59.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.59.59.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NG v3.59.59.0 done')