import os
MODULES=['pcc_pathology_ext100','pcc_cytology_ext100','pcc_molecular_ext100']
FUNCS={
'pcc_pathology_ext100':[('PathGeneralExt','0.18 + Number(input.pathGen||1)*0.2 + Number(input.pathGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('PathSurgicalExt','0.18 + Number(input.pathSurg||1)*0.2 + Number(input.surgPathType||1)*0.2 + Number(input.outcome||1)*0.2'),('PathFrozenExt','0.18 + Number(input.pathFrozen||1)*0.2 + Number(input.frozenTurnaround||1)*0.04 + Number(input.outcome||1)*0.2'),('PathAutopsyExt','0.18 + Number(input.pathAutopsy||1)*0.2 + Number(input.autopsyType||1)*0.2 + Number(input.outcome||1)*0.2'),('PathIHCext','0.18 + Number(input.pathIHC||1)*0.2 + Number(input.ihcMarker||1)*0.2 + Number(input.outcome||1)*0.2'),('PathSpecialStainExt','0.18 + Number(input.pathSpecial||1)*0.2 + Number(input.specialStainType||1)*0.2 + Number(input.outcome||1)*0.2'),('PathEMExt','0.18 + Number(input.pathEM||1)*0.2 + Number(input.emFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('PathFlowExt','0.18 + Number(input.pathFlow||1)*0.2 + Number(input.flowMarkers||1)*0.2 + Number(input.outcome||1)*0.2'),('PathCytogeneticsExt','0.18 + Number(input.pathCyto||1)*0.2 + Number(input.cytoAbn||1)*0.2 + Number(input.outcome||1)*0.2'),('PathFISHext','0.18 + Number(input.pathFISH||1)*0.2 + Number(input.fishProbe||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_cytology_ext100':[('CytoGynExt','0.18 + Number(input.cytoGyn||1)*0.2 + Number(input.bethesdaScore||1)*0.04 + Number(input.outcome||1)*0.2'),('CytoNonGynExt','0.18 + Number(input.cytoNonGyn||1)*0.2 + Number(input.nonGynSource||1)*0.2 + Number(input.outcome||1)*0.2'),('CytoFNAext','0.18 + Number(input.cytoFNA||1)*0.2 + Number(input.fnaSite||1)*0.2 + Number(input.outcome||1)*0.2'),('CytoFluidExt','0.18 + Number(input.cytoFluid||1)*0.2 + Number(input.fluidType||1)*0.2 + Number(input.outcome||1)*0.2'),('CytoUrineExt','0.18 + Number(input.cytoUrine||1)*0.2 + Number(input.urineCytology||1)*0.2 + Number(input.outcome||1)*0.2'),('CytoSputumExt','0.18 + Number(input.cytoSputum||1)*0.2 + Number(input.sputumFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('CytoCSFext','0.18 + Number(input.cytoCSF||1)*0.2 + Number(input.csfCellType||1)*0.2 + Number(input.outcome||1)*0.2'),('CytoBreastExt','0.18 + Number(input.cytoBreast||1)*0.2 + Number(input.breastFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('CytoThyroidExt','0.18 + Number(input.cytoThyroid||1)*0.2 + Number(input.thyroCyto||1)*0.2 + Number(input.outcome||1)*0.2'),('CytoLymphExt','0.18 + Number(input.cytoLymph||1)*0.2 + Number(input.lymphCyto||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_molecular_ext100':[('MolPCRadultExt','0.18 + Number(input.molPCR||1)*0.2 + Number(input.pcrTarget||1)*0.2 + Number(input.outcome||1)*0.2'),('MolNGSext','0.18 + Number(input.molNGS||1)*0.2 + Number(input.ngsPanel||1)*0.2 + Number(input.outcome||1)*0.2'),('MolMicroarrayExt','0.18 + Number(input.molMA||1)*0.2 + Number(input.maType||1)*0.2 + Number(input.outcome||1)*0.2'),('MolSequencingExt','0.18 + Number(input.molSeq||1)*0.2 + Number(input.seqType||1)*0.2 + Number(input.outcome||1)*0.2'),('MolLiquidBiopsyExt','0.18 + Number(input.molLiquid||1)*0.2 + Number(input.liquidMutation||1)*0.2 + Number(input.outcome||1)*0.2'),('MolGeneticCounselExt','0.18 + Number(input.molCounsel||1)*0.2 + Number(input.geneticRisk||1)*0.2 + Number(input.outcome||1)*0.2'),('MolPharmacogenomicExt','0.18 + Number(input.molPGx||1)*0.2 + Number(input.pgxGene||1)*0.2 + Number(input.outcome||1)*0.2'),('MolInfectPCRext','0.18 + Number(input.molInfPCR||1)*0.2 + Number(input.infectPathogen||1)*0.2 + Number(input.outcome||1)*0.2'),('MolHLAext','0.18 + Number(input.molHLA||1)*0.2 + Number(input.hlaType||1)*0.2 + Number(input.outcome||1)*0.2'),('MolOncologyExt','0.18 + Number(input.molOnc||1)*0.2 + Number(input.oncMutation||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.29.29.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.29.29.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.29.29.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.29.29.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MC v3.29.29.0 done')