import os
MODULES=['pcc_neuro_ext152','pcc_pediatric_neuro_ext141','pcc_pediatric_surg_ext141']
FUNCS={
'pcc_neuro_ext152':[('ComaConsciousnessExt','0.18 + Number(input.gcs||1)*0.04 + Number(input.coma||1)*0.2 + Number(input.outcome||1)*0.2'),('VegetativeStateExt','0.18 + Number(input.vegetative||1)*0.2 + Number(input.months||1)*0.04 + Number(input.outcome||1)*0.2'),('MinimallyConsciousExt','0.18 + Number(input.mcs||1)*0.2 + Number(input.conscious||1)*0.2 + Number(input.outcome||1)*0.2'),('LockedInSynExt','0.18 + Number(input.locked||1)*0.2 + Number(input.vertical||1)*0.2 + Number(input.outcome||1)*0.2'),('BrainDeathExt','0.18 + Number(input.brainDeath||1)*0.2 + Number(input.apnea||1)*0.2 + Number(input.outcome||1)*0.2'),('AnoxicBrainInjuryExt','0.18 + Number(input.anoxia||1)*0.2 + Number(input.cpr||1)*0.2 + Number(input.outcome||1)*0.2'),('HypoxicIschemicExt','0.18 + Number(input.hi||1)*0.2 + Number(input.noFlow||1)*0.04 + Number(input.outcome||1)*0.2'),('MetabolicEncephExt','0.18 + Number(input.metabolic||1)*0.2 + Number(input.ammonia||1)*0.2 + Number(input.outcome||1)*0.2'),('HashimotoEncephExt','0.18 + Number(input.hashimoto||1)*0.2 + Number(input.antiTPO||1)*0.2 + Number(input.outcome||1)*0.2'),('AutoimmuneEncephExt','0.18 + Number(input.ae||1)*0.2 + Number(input.autoimmune||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext141':[('PediatricComaExt','0.18 + Number(input.age||5)*0.04 + Number(input.pComa||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVSext','0.18 + Number(input.age||5)*0.04 + Number(input.pVS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMCSExt','0.18 + Number(input.age||5)*0.04 + Number(input.pMCS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLockedInExt','0.18 + Number(input.age||10)*0.04 + Number(input.pLocked||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBrainDeathExt','0.18 + Number(input.age||5)*0.04 + Number(input.pBrainDeath||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAnoxicExt','0.18 + Number(input.age||5)*0.04 + Number(input.pAnoxic||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHIBEext','0.18 + Number(input.age||1)*0.04 + Number(input.hibe||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMSUDext','0.18 + Number(input.age||1)*0.04 + Number(input.msud||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricUreaExt','0.18 + Number(input.age||1)*0.04 + Number(input.urea||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAntiNMDARExt','0.18 + Number(input.age||8)*0.04 + Number(input.nmdar||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext141':[('PediatricComaSupportExt','0.18 + Number(input.age||5)*0.04 + Number(input.supportPcoma||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVSCareExt','0.18 + Number(input.age||5)*0.04 + Number(input.vsCare||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMCSrehabExt','0.18 + Number(input.age||5)*0.04 + Number(input.mcsRehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLockedCommExt','0.18 + Number(input.age||10)*0.04 + Number(input.commDevice||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBrainDeathTestExt','0.18 + Number(input.age||5)*0.04 + Number(input.apneaTest||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTTMExt','0.18 + Number(input.age||5)*0.04 + Number(input.ttm||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHIBECoolingExt','0.18 + Number(input.age||1)*0.04 + Number(input.cooling||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMSUDdietExt','0.18 + Number(input.age||1)*0.04 + Number(input.dietMSUD||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricUreaDialysisExt','0.18 + Number(input.age||1)*0.04 + Number(input.dialysis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAntiNMDARIVIGExt','0.18 + Number(input.age||8)*0.04 + Number(input.ivigNMDAR||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.251.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.251.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.251.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.251.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KS v3.251.0 done')