import os
MODULES=['pcc_oncology_ext99','pcc_hematology_ext99','pcc_renal_ext99']
FUNCS={
'pcc_oncology_ext99':[('OncBreastExt','0.18 + Number(input.oncBreast||1)*0.2 + Number(input.her2Status||1)*0.2 + Number(input.outcome||1)*0.2'),('OncLungExt','0.18 + Number(input.oncLung||1)*0.2 + Number(input.egfrMut||1)*0.2 + Number(input.outcome||1)*0.2'),('OncColonExt','0.18 + Number(input.oncColon||1)*0.2 + Number(input.rasMut||1)*0.2 + Number(input.outcome||1)*0.2'),('OncPancreasExt','0.18 + Number(input.oncPanc||1)*0.2 + Number(input.brcaMut||1)*0.2 + Number(input.outcome||1)*0.2'),('OncProstateExt','0.18 + Number(input.oncProstate||1)*0.2 + Number(input.psaScore||1)*0.04 + Number(input.outcome||1)*0.2'),('OncRenalExt','0.18 + Number(input.oncRenal||1)*0.2 + Number(input.clearCell||1)*0.2 + Number(input.outcome||1)*0.2'),('OncMelanomaExt','0.18 + Number(input.oncMel||1)*0.2 + Number(input.brafMut||1)*0.2 + Number(input.outcome||1)*0.2'),('OncHematologicExt','0.18 + Number(input.oncHeme||1)*0.2 + Number(input.citogenRisk||1)*0.2 + Number(input.outcome||1)*0.2'),('OncImmunotherapyExt','0.18 + Number(input.oncIO||1)*0.2 + Number(input.pdl1||1)*0.04 + Number(input.outcome||1)*0.2'),('OncTargetedTxExt','0.18 + Number(input.oncTarget||1)*0.2 + Number(input.targetMutation||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_hematology_ext99':[('HemeAnemiaExt','0.18 + Number(input.hemeAnemia||1)*0.2 + Number(input.hgb||1)*0.04 + Number(input.outcome||1)*0.2'),('HemeLeukemiaExt','0.18 + Number(input.hemeLeu||1)*0.2 + Number(input.blastPct||1)*0.04 + Number(input.outcome||1)*0.2'),('HemeLymphomaExt','0.18 + Number(input.hemeLymph||1)*0.2 + Number(input.lymphStage||1)*0.04 + Number(input.outcome||1)*0.2'),('HemeMyelomaExt','0.18 + Number(input.hemeMyeloma||1)*0.2 + Number(input.mProtein||1)*0.04 + Number(input.outcome||1)*0.2'),('HemeCoagulopathyExt','0.18 + Number(input.hemeCoag||1)*0.2 + Number(input.factorLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('HemeThrombosisExt','0.18 + Number(input.hemeThromb||1)*0.2 + Number(input.dDimer||1)*0.04 + Number(input.outcome||1)*0.2'),('HemeTransfusionExt','0.18 + Number(input.hemeTrans||1)*0.2 + Number(input.transType||1)*0.2 + Number(input.outcome||1)*0.2'),('HemeStemCellExt','0.18 + Number(input.hemeSCT||1)*0.2 + Number(input.sctType||1)*0.2 + Number(input.outcome||1)*0.2'),('HemePancytopeniaExt','0.18 + Number(input.hemePancyt||1)*0.2 + Number(input.wbcCount||1)*0.04 + Number(input.outcome||1)*0.2'),('HemeSickleExt','0.18 + Number(input.hemeSickle||1)*0.2 + Number(input.hbfLevel||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_renal_ext99':[('RenalCKDExt','0.18 + Number(input.renalCKD||1)*0.2 + Number(input.gfr||1)*0.04 + Number(input.outcome||1)*0.2'),('RenalAKIext','0.18 + Number(input.renalAKI||1)*0.2 + Number(input.creat||1)*0.04 + Number(input.outcome||1)*0.2'),('RenalDialysisExt','0.18 + Number(input.renalDial||1)*0.2 + Number(input.dialysisType||1)*0.2 + Number(input.outcome||1)*0.2'),('RenalTransplantExt','0.18 + Number(input.renalTx||1)*0.2 + Number(input.txaScore||1)*0.04 + Number(input.outcome||1)*0.2'),('RenalStoneExt','0.18 + Number(input.renalStone||1)*0.2 + Number(input.stoneSize||1)*0.04 + Number(input.outcome||1)*0.2'),('RenalUTIext','0.18 + Number(input.renalUTI||1)*0.2 + Number(input.culture||1)*0.2 + Number(input.outcome||1)*0.2'),('RenalGNExt','0.18 + Number(input.renalGN||1)*0.2 + Number(input.proteinuria||1)*0.04 + Number(input.outcome||1)*0.2'),('RenalPKDExt','0.18 + Number(input.renalPKD||1)*0.2 + Number(input.pkdSize||1)*0.04 + Number(input.outcome||1)*0.2'),('RenalHTNext','0.18 + Number(input.renalHTN||1)*0.2 + Number(input.renalArtery||1)*0.2 + Number(input.outcome||1)*0.2'),('RenalElectrolyteExt','0.18 + Number(input.renalElec||1)*0.2 + Number(input.kLevel||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.18.18.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.18.18.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.18.18.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.18.18.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LR v3.18.18.0 done')