import os
MODULES=['pcc_neuro_ext150','pcc_pediatric_neuro_ext139','pcc_pediatric_surg_ext139']
FUNCS={
'pcc_neuro_ext150':[('CerebralAneurysmExt','0.18 + Number(input.aneurysm||1)*0.2 + Number(input.rupture||1)*0.2 + Number(input.outcome||1)*0.2'),('AVMExt','0.18 + Number(input.avm||1)*0.2 + Number(input.bleed||1)*0.2 + Number(input.outcome||1)*0.2'),('CavernousMalformationExt','0.18 + Number(input.cavernoma||1)*0.2 + Number(input.seizure||1)*0.2 + Number(input.outcome||1)*0.2'),('DuralAVFExt','0.18 + Number(input.davf||1)*0.2 + Number(input.pulsatile||1)*0.2 + Number(input.outcome||1)*0.2'),('MoyamoyaExt','0.18 + Number(input.moyamoya||1)*0.2 + Number(input.strokes||1)*0.2 + Number(input.outcome||1)*0.2'),('CarotidDissectionExt','0.18 + Number(input.dissect||1)*0.2 + Number(input.trauma||1)*0.2 + Number(input.outcome||1)*0.2'),('VertebralDissectionExt','0.18 + Number(input.vertDissect||1)*0.2 + Number(input.posterior||1)*0.2 + Number(input.outcome||1)*0.2'),('CerebralVenousThrombExt','0.18 + Number(input.cvt||1)*0.2 + Number(input.headache||1)*0.2 + Number(input.outcome||1)*0.2'),('RCVSext','0.18 + Number(input.rcvs||1)*0.2 + Number(input.thunderclap||1)*0.2 + Number(input.outcome||1)*0.2'),('PRESext','0.18 + Number(input.pres||1)*0.2 + Number(input.edema||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext139':[('PediatricAneurysmExt','0.18 + Number(input.age||10)*0.04 + Number(input.aneurysm||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAVMExt','0.18 + Number(input.age||8)*0.04 + Number(input.avm||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCavernomaExt','0.18 + Number(input.age||8)*0.04 + Number(input.cavernoma||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMoyamoyaExt','0.18 + Number(input.age||5)*0.04 + Number(input.moyamoya||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricArteriopathyExt','0.18 + Number(input.age||5)*0.04 + Number(input.arteriopathy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSickleStrokeExt','0.18 + Number(input.age||5)*0.04 + Number(input.sickle||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCVTExt','0.18 + Number(input.age||5)*0.04 + Number(input.cvt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeonatalStrokeExt','0.18 + Number(input.age||0)*0.04 + Number(input.neonatal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPRESExt','0.18 + Number(input.age||5)*0.04 + Number(input.pres||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRCVSExt','0.18 + Number(input.age||10)*0.04 + Number(input.rcvs||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext139':[('PediatricAneurysmClipExt','0.18 + Number(input.age||10)*0.04 + Number(input.clip||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAVMcoilExt','0.18 + Number(input.age||8)*0.04 + Number(input.coil||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCavernomaResectExt','0.18 + Number(input.age||8)*0.04 + Number(input.resect||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMoyamoyaBypassExt','0.18 + Number(input.age||5)*0.04 + Number(input.bypass||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEDASxExt','0.18 + Number(input.age||5)*0.04 + Number(input.edas||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSickleTransfuseExt','0.18 + Number(input.age||5)*0.04 + Number(input.transfuse||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCVTanticoagExt','0.18 + Number(input.age||5)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPRESMgmtExt','0.18 + Number(input.age||5)*0.04 + Number(input.presMgmt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRCVSNimodipineExt','0.18 + Number(input.age||10)*0.04 + Number(input.nimodipine||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeRehabExt','0.18 + Number(input.age||5)*0.04 + Number(input.rehab||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.249.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.249.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.249.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.249.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KQ v3.249.0 done')