import os
MODULES=['pcc_neuro_ext161','pcc_pediatric_neuro_ext150','pcc_pediatric_surg_ext150']
FUNCS={
'pcc_neuro_ext161':[('MovementDisorderTremorExt','0.18 + Number(input.tremor||1)*0.2 + Number(input.type||1)*0.2 + Number(input.outcome||1)*0.2'),('DystoniaExt','0.18 + Number(input.dystonia||1)*0.2 + Number(input.focal||1)*0.2 + Number(input.outcome||1)*0.2'),('ChoreaExt','0.18 + Number(input.chorea||1)*0.2 + Number(input.hd||1)*0.2 + Number(input.outcome||1)*0.2'),('TicDisorderExt','0.18 + Number(input.tic||1)*0.2 + Number(input.motor||1)*0.2 + Number(input.outcome||1)*0.2'),('MyoclonusExt','0.18 + Number(input.myoclonus||1)*0.2 + Number(input.cortex||1)*0.2 + Number(input.outcome||1)*0.2'),('AtaxiaCerebellarExt','0.18 + Number(input.ataxia||1)*0.2 + Number(input.cerebellar||1)*0.2 + Number(input.outcome||1)*0.2'),('SensoryAtaxiaExt','0.18 + Number(input.sensoryAtaxia||1)*0.2 + Number(input.dorsalColumn||1)*0.2 + Number(input.outcome||1)*0.2'),('VestibularAtaxiaExt','0.18 + Number(input.vestAtaxia||1)*0.2 + Number(input.vestibular||1)*0.2 + Number(input.outcome||1)*0.2'),('ParkinsonianExt','0.18 + Number(input.park||1)*0.2 + Number(input.brady||1)*0.2 + Number(input.outcome||1)*0.2'),('PSPext','0.18 + Number(input.psp||1)*0.2 + Number(input.supranuclear||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext150':[('PediatricAtaxiaExt','0.18 + Number(input.age||5)*0.04 + Number(input.pAtaxia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChoreaExt','0.18 + Number(input.age||8)*0.04 + Number(input.pChorea||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDystoniaExt','0.18 + Number(input.age||5)*0.04 + Number(input.pDystonia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTicExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTic||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMyoclonusExt','0.18 + Number(input.age||1)*0.04 + Number(input.pMyoclonus||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTremorExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTremor||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOpsoclonusExt','0.18 + Number(input.age||1)*0.04 + Number(input.opsoclonus||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSydenhamExt','0.18 + Number(input.age||8)*0.04 + Number(input.sydenham||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPANDASext','0.18 + Number(input.age||5)*0.04 + Number(input.pandas||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBenignPalsyExt','0.18 + Number(input.age||1)*0.04 + Number(input.benignPalsy||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext150':[('PediatricAtaxiaRehabExt','0.18 + Number(input.age||5)*0.04 + Number(input.ataxiaRehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChoreaRxExt','0.18 + Number(input.age||8)*0.04 + Number(input.choreaRx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDystoniaDBSext','0.18 + Number(input.age||8)*0.04 + Number(input.dystoniaDBS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTicCBText','0.18 + Number(input.age||8)*0.04 + Number(input.ticCBT||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMyoclonusRxExt','0.18 + Number(input.age||1)*0.04 + Number(input.myoRx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTremorPropranololExt','0.18 + Number(input.age||8)*0.04 + Number(input.tremorProp||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOpsoclonusIVIGext','0.18 + Number(input.age||1)*0.04 + Number(input.opsoIVIG||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSydenhamPenExt','0.18 + Number(input.age||8)*0.04 + Number(input.sydenhamPen||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPANDASabxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pandasAbx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBenignPalsyObsExt','0.18 + Number(input.age||1)*0.04 + Number(input.bpObs||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.260.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.260.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.260.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.260.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LB v3.260.0 done')