import os
MODULES=['pcc_neuro_ext156','pcc_pediatric_neuro_ext145','pcc_pediatric_surg_ext145']
FUNCS={
'pcc_neuro_ext156':[('BrainStimDBSext','0.18 + Number(input.dbs||1)*0.2 + Number(input.target||1)*0.2 + Number(input.outcome||1)*0.2'),('VagusNerveStimExt','0.18 + Number(input.vns||1)*0.2 + Number(input.epilepsy||1)*0.2 + Number(input.outcome||1)*0.2'),('ResponsiveNeuroStimExt','0.18 + Number(input.rns||1)*0.2 + Number(input.seizureDetect||1)*0.2 + Number(input.outcome||1)*0.2'),('TMSforDepressionExt','0.18 + Number(input.tms||1)*0.2 + Number(input.trd||1)*0.2 + Number(input.outcome||1)*0.2'),('TMSforStrokeRehabExt','0.18 + Number(input.tmsStroke||1)*0.2 + Number(input.motor||1)*0.2 + Number(input.outcome||1)*0.2'),('ECTdepressionExt','0.18 + Number(input.ect||1)*0.2 + Number(input.trdEct||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuroablationExt','0.18 + Number(input.mrFocus||1)*0.2 + Number(input.tremor||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalCordStimExt','0.18 + Number(input.scs||1)*0.2 + Number(input.pain||1)*0.2 + Number(input.outcome||1)*0.2'),('IntrathecalPumpExt','0.18 + Number(input.itpump||1)*0.2 + Number(input.spasticity||1)*0.2 + Number(input.outcome||1)*0.2'),('GammaKnifeExt','0.18 + Number(input.gk||1)*0.2 + Number(input.trigeminal||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext145':[('PediatricVNSext','0.18 + Number(input.age||5)*0.04 + Number(input.pVNS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDBSdystoniaExt','0.18 + Number(input.age||8)*0.04 + Number(input.pDBSdystonia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricKetogenicExt','0.18 + Number(input.age||3)*0.04 + Number(input.keto||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVNSext2','0.18 + Number(input.age||10)*0.04 + Number(input.pVNS2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHemispherotomyExt','0.18 + Number(input.age||3)*0.04 + Number(input.hemispherectomy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCallosotomyExt','0.18 + Number(input.age||5)*0.04 + Number(input.callosotomy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLesionectomyExt','0.18 + Number(input.age||8)*0.04 + Number(input.lesionectomy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRNSExt','0.18 + Number(input.age||10)*0.04 + Number(input.pRNS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGKRxExt','0.18 + Number(input.age||10)*0.04 + Number(input.pGK||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBaclofenPumpExt','0.18 + Number(input.age||5)*0.04 + Number(input.baclofen||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext145':[('PediatricVNSSurgExt','0.18 + Number(input.age||10)*0.04 + Number(input.vnsSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDBSSurgExt','0.18 + Number(input.age||8)*0.04 + Number(input.dbsSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricKetogenicDietExt','0.18 + Number(input.age||3)*0.04 + Number(input.ketoDiet||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHemispherectomySurgExt','0.18 + Number(input.age||3)*0.04 + Number(input.hemiSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCallosotomySurgExt','0.18 + Number(input.age||5)*0.04 + Number(input.callosoSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLesionectomySurgExt','0.18 + Number(input.age||8)*0.04 + Number(input.lesSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRNSSurgExt','0.18 + Number(input.age||10)*0.04 + Number(input.rnsSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGKSurgExt','0.18 + Number(input.age||10)*0.04 + Number(input.gkSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBaclofenPumpSurgExt','0.18 + Number(input.age||5)*0.04 + Number(input.bacSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTMSSurgExt','0.18 + Number(input.age||10)*0.04 + Number(input.tmsSurg||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.255.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.255.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.255.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.255.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KW v3.255.0 done')