import os
MODULES=['pcc_neuro_ext195','pcc_pediatric_neuro_ext184','pcc_pediatric_surg_ext184']
FUNCS={
'pcc_neuro_ext195':[('PeripheralNeuropathyAdultExt','0.18 + Number(input.pnpAdult||1)*0.2 + Number(input.ncs||1)*0.2 + Number(input.outcome||1)*0.2'),('DiabeticNeuropathyAdultExt','0.18 + Number(input.dnpAdult||1)*0.2 + Number(input.hba1c||1)*0.04 + Number(input.outcome||1)*0.2'),('CIDPadultExt','0.18 + Number(input.cipAdult||1)*0.2 + Number(input.progression||1)*0.2 + Number(input.outcome||1)*0.2'),('GBSadultExt','0.18 + Number(input.gbsAdult||1)*0.2 + Number(input.gbsDisability||1)*0.04 + Number(input.outcome||1)*0.2'),('MyastheniaGravisAdultExt','0.18 + Number(input.mgAdult||1)*0.2 + Number(input.achRAb||1)*0.2 + Number(input.outcome||1)*0.2'),('AMPadultExt','0.18 + Number(input.ampAdult||1)*0.2 + Number(input.ampType||1)*0.2 + Number(input.outcome||1)*0.2'),('MyopathyAdultExt','0.18 + Number(input.myopAdult||1)*0.2 + Number(input.ckLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('SmallFiberNeuropathyExt','0.18 + Number(input.sfnAdult||1)*0.2 + Number(input.sudomotor||1)*0.2 + Number(input.outcome||1)*0.2'),('CRPSadultExt','0.18 + Number(input.crpsAdult||1)*0.2 + Number(input.crpsStage||1)*0.04 + Number(input.outcome||1)*0.2'),('FacialNervePalsyAdultExt','0.18 + Number(input.fnpAdult||1)*0.2 + Number(input.houseBrack||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext184':[('PediatricPNPext','0.18 + Number(input.age||5)*0.04 + Number(input.pPNP||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCharcotExt','0.18 + Number(input.age||5)*0.04 + Number(input.pCMT||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGBSext','0.18 + Number(input.age||3)*0.04 + Number(input.pGBS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCIDPext','0.18 + Number(input.age||5)*0.04 + Number(input.pCIDP||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMGext','0.18 + Number(input.age||8)*0.04 + Number(input.pMG||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDuchenneExt','0.18 + Number(input.age||3)*0.04 + Number(input.pDMD||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMAext','0.18 + Number(input.age||0)*0.04 + Number(input.pSMA||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMyopathyExt','0.18 + Number(input.age||3)*0.04 + Number(input.pMyop||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFNPext','0.18 + Number(input.age||5)*0.04 + Number(input.pFNP||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCRPSext','0.18 + Number(input.age||8)*0.04 + Number(input.pCRPS||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext184':[('PediatricPNPTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pPNPTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCMTTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pCMTTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGBSTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pGBSTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCIDPTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pCIDPTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMGTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pMGTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDMDTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pDMDTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMATxExt','0.18 + Number(input.age||0)*0.04 + Number(input.pSMATx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMyopTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pMyopTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFNPTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pFNPTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCRPSTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pCRPSTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.24.24.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.24.24.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.24.24.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.24.24.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-HX v3.24.24.0 done')