import os
MODULES=['pcc_neuro_ext103','pcc_pediatric_neuro_ext92','pcc_pediatric_surg_ext92']
FUNCS={
'pcc_neuro_ext103':[('SpineDisorderClinicExt','0.15 + Number(input.level||3)*0.05 + Number(input.diagnosis||1)*0.2 + Number(input.complication||1)*0.2'),('CervicalStenosisEvalExt','0.18 + Number(input.myles||1)*0.2 + Number(input.degen||1)*0.2 + Number(input.risk||2)*0.1'),('CervicalMyelopathySurgExt','0.15 + Number(input.approach||1)*0.2 + Number(input.levels||2)*0.1 + Number(input.outcome||1)*0.2'),('LumbarStenosisEvalExt','0.18 + Number(input.claud||1)*0.2 + Number(input.pain||7)*0.02 + Number(input.degen||1)*0.15'),('LumbarFusionExt','0.15 + Number(input.levels||2)*0.1 + Number(input.approach||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalCordStimExt','0.15 + Number(input.trial||1)*0.2 + Number(input.coverage||80)*0.005 + Number(input.outcome||1)*0.2'),('ChordomaSurgExt','0.18 + Number(input.location||1)*0.2 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalAVMExt','0.15 + Number(input.spetzler||2)*0.15 + Number(input.embo||1)*0.2 + Number(input.outcome||1)*0.2'),('CaudaEquinaExt','0.18 + Number(input.sphincterLoss||1)*0.2 + Number(input.saddle||1)*0.2 + Number(input.decomp||1)*0.2'),('FailedBackSyndromeExt','0.15 + Number(input.previousSurg||2)*0.1 + Number(input.painScore||7)*0.05 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext92':[('PediatricTetheredCordExt','0.15 + Number(input.age||5)*0.04 + Number(input.lesion||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChiariExt','0.18 + Number(input.tonsils||3)*0.05 + Number(input.syrinx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalTumorExt','0.15 + Number(input.histology||1)*0.2 + Number(input.location||2)*0.1 + Number(input.outcome||1)*0.2'),('PediatricSpinalCordInjuryExt','0.15 + Number(input.ais||2)*0.15 + Number(input.recovery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalMuscAtrophyExt','0.15 + Number(input.smaType||1)*0.2 + Number(input.therapy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalDystrophyExt','0.15 + Number(input.kyphosis||30)*0.01 + Number(input.scoliosis||25)*0.01 + Number(input.outcome||1)*0.2'),('PediatricSkeletalDysplasiaSpineExt','0.15 + Number(input.dysplasia||1)*0.2 + Number(input.kyphosis||45)*0.005 + Number(input.outcome||1)*0.2'),('PediatricSpinalCordTumorSurgMgmExt','0.15 + Number(input.extent||1)*0.2 + Number(input.biopsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeurogenicBowelBladExt','0.15 + Number(input.lesionLevel||1)*0.2 + Number(input.training||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricToneMgmForSpineExt','0.15 + Number(input.baclofen||1)*0.2 + Number(input.rhizotomy||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext92':[('PediatricTetheredCordReleaseExt','0.15 + Number(input.age||5)*0.04 + Number(input.surgicalLevel||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChiariDecompressionExt','0.18 + Number(input.age||8)*0.03 + Number(input.syrinx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalDeformityCorrectionExt','0.15 + Number(input.age||12)*0.02 + Number(input.cobbAngle||45)*0.005 + Number(input.outcome||1)*0.2'),('PediatricGrowingRodExt','0.15 + Number(input.age||6)*0.04 + Number(input.distractions||3)*0.05 + Number(input.outcome||1)*0.2'),('PediatricMCGGExt','0.15 + Number(input.age||6)*0.04 + Number(input.conf||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVEPTRImplantExt','0.15 + Number(input.age||6)*0.04 + Number(input.ribExp||4)*0.05 + Number(input.outcome||1)*0.2'),('PediatricHaloExt','0.15 + Number(input.displacement||1)*0.2 + Number(input.traction||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOCFusionExt','0.15 + Number(input.age||10)*0.02 + Number(input.bone||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalTumorResectExt','0.15 + Number(input.level||3)*0.05 + Number(input.motor||3)*0.05 + Number(input.outcome||1)*0.2'),('PediatricScoliosisRehabPostExt','0.15 + Number(input.intensity||3)*0.1 + Number(input.weeks||12)*0.04 + Number(input.gain||10)*0.04')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\n// {m} engine (deterministic)\nmodule.exports.version=\'v3.202.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.202.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}};}};\n'
    eng+=f'\n// TS: v3.202.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'// filepath: pcc/{m}/{m}_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;else console.error(\'FAIL\',fn,r);}}console.log(\'{m} unit:\',pass,\'passed\');if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'// filepath: pcc/{m}/{m}_integration_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{value:1}},{{value:2}},{{value:3}},{{value:4}},{{value:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass,\'passed\');if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'// filepath: pcc/{m}/{m}_routes.js\nconst express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();\nrouter.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.202.0\',functions:Object.keys(F)}}));\nrouter.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});\nrouter.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});\nmodule.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- pcc/{m}/{m}_up.sql\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\')\nBEGIN\nCREATE TABLE [dbo].[{m}] (\n  [id] INT IDENTITY(1,1) PRIMARY KEY,\n  [tenant_id] NVARCHAR(64) NOT NULL,\n  [version] NVARCHAR(16) NOT NULL,\n  [module] NVARCHAR(64) NOT NULL,\n  [function] NVARCHAR(128) NOT NULL,\n  [input] NVARCHAR(MAX) NULL,\n  [score] DECIMAL(6,2) NULL,\n  [ts] DATETIME2 DEFAULT SYSUTCDATETIME()\n);\nEND\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files written')
print('P3-IV v3.202.0: 16 files written')
