import os
MODULES=['pcc_neuro_ext189','pcc_pediatric_neuro_ext178','pcc_pediatric_surg_ext178']
FUNCS={
'pcc_neuro_ext189':[('SpinalCordInjuryAdultExt','0.18 + Number(input.sciAdult||1)*0.2 + Number(input.level||1)*0.04 + Number(input.outcome||1)*0.2'),('SpinalCordInjuryCompExt','0.18 + Number(input.sciComp||1)*0.2 + Number(input.completeness||1)*0.2 + Number(input.outcome||1)*0.2'),('AutonomicDysreflexiaExt','0.18 + Number(input.ad||1)*0.2 + Number(input.bp||1)*0.04 + Number(input.outcome||1)*0.2'),('NeurogenicBladderExt','0.18 + Number(input.neuroBladder||1)*0.2 + Number(input.urodyn||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalShockExt','0.18 + Number(input.spinalShock||1)*0.2 + Number(input.acute||1)*0.2 + Number(input.outcome||1)*0.2'),('SyrinxPostTraumaExt','0.18 + Number(input.syrinxPT||1)*0.2 + Number(input.postTraumatic||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalCordRehabExt','0.18 + Number(input.sciRehab||1)*0.2 + Number(input.aisGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('CentralCordExt','0.18 + Number(input.centralCord||1)*0.2 + Number(input.central||1)*0.2 + Number(input.outcome||1)*0.2'),('CaudaEquinaAdultExt','0.18 + Number(input.caudaAdult||1)*0.2 + Number(input.saddleAdult||1)*0.2 + Number(input.outcome||1)*0.2'),('ConusMedullarisExt','0.18 + Number(input.conus||1)*0.2 + Number(input.medullaris||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext178':[('PediatricSCIext','0.18 + Number(input.age||5)*0.04 + Number(input.pSCI||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinaBifidaNeuroExt','0.18 + Number(input.age||0)*0.04 + Number(input.pSBNeuro||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeuroBladderExt','0.18 + Number(input.age||3)*0.04 + Number(input.pNeuroBladder||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeuroBowelExt','0.18 + Number(input.age||3)*0.04 + Number(input.pNeuroBowel||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSCIrehabExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSCIrehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricADpedExt','0.18 + Number(input.age||8)*0.04 + Number(input.pADped||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPressureUlcerExt','0.18 + Number(input.age||5)*0.04 + Number(input.pPU||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSCIpsyExt','0.18 + Number(input.age||10)*0.04 + Number(input.pSCIpsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSCItransExt','0.18 + Number(input.age||8)*0.04 + Number(input.pSCItrans||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSCIfollowExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSCIfollow||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext178':[('PediatricSCIsurgExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSCIsurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSBNeuroSxExt','0.18 + Number(input.age||0)*0.04 + Number(input.pSBNeuroSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeuroBladderSxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pNeuroBladderSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeuroBowelSxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pNeuroBowelSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSCIrehabTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSCIrehabTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricADpedTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pADpedTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPUTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pPUTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSCIpsyTxExt','0.18 + Number(input.age||10)*0.04 + Number(input.pSCIpsyTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSCItransTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pSCItransTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSCIfollowTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSCIfollowTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.18.18.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.18.18.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.18.18.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.18.18.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-HR v3.18.18.0 done')