import os
MODULES=['pcc_preventive_ext101','pcc_screening_ext101','pcc_wellness_ext101']
FUNCS={
'pcc_preventive_ext101':[('PrevVaccineExt','0.18 + Number(input.pvVacc||1)*0.2 + Number(input.pvVaccType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevCancerExt','0.18 + Number(input.pvCancer||1)*0.2 + Number(input.pvCancerType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevCVDExt','0.18 + Number(input.pvCVD||1)*0.2 + Number(input.pvCVDRisk||1)*0.04 + Number(input.outcome||1)*0.2'),('PrevDiabetesExt','0.18 + Number(input.pvDM||1)*0.2 + Number(input.pvDMRisk||1)*0.04 + Number(input.outcome||1)*0.2'),('PrevObesityExt','0.18 + Number(input.pvOb||1)*0.2 + Number(input.pvBMI||1)*0.04 + Number(input.outcome||1)*0.2'),('PrevSmokingExt','0.18 + Number(input.pvSmoke||1)*0.2 + Number(input.pvPackYear||1)*0.04 + Number(input.outcome||1)*0.2'),('PrevAlcoholExt','0.18 + Number(input.pvAlc||1)*0.2 + Number(input.pvAudit||1)*0.04 + Number(input.outcome||1)*0.2'),('PrevSTIScreenExt','0.18 + Number(input.pvSTI||1)*0.2 + Number(input.pvSTIType||1)*0.2 + Number(input.outcome||1)*0.2'),('PrevMentalExt','0.18 + Number(input.pvMental||1)*0.2 + Number(input.pvPHQ||1)*0.04 + Number(input.outcome||1)*0.2'),('PrevHealthLitExt','0.18 + Number(input.pvHL||1)*0.2 + Number(input.pvHLLevel||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_screening_ext101':[('ScrMammoExt','0.18 + Number(input.scMammo||1)*0.2 + Number(input.scMammoBiRads||1)*0.04 + Number(input.outcome||1)*0.2'),('ScrColonExt','0.18 + Number(input.scColon||1)*0.2 + Number(input.scColonType||1)*0.2 + Number(input.outcome||1)*0.2'),('ScrCervicalExt','0.18 + Number(input.scCervix||1)*0.2 + Number(input.scHPV||1)*0.2 + Number(input.outcome||1)*0.2'),('ScrLungExt','0.18 + Number(input.scLung||1)*0.2 + Number(input.scLungPackYr||1)*0.04 + Number(input.outcome||1)*0.2'),('ScrProstateExt','0.18 + Number(input.scProst||1)*0.2 + Number(input.scPSALevel||1)*0.04 + Number(input.outcome||1)*0.2'),('ScrOvarianExt','0.18 + Number(input.scOvar||1)*0.2 + Number(input.scOvarMarker||1)*0.04 + Number(input.outcome||1)*0.2'),('ScrAAAext','0.18 + Number(input.scAAA||1)*0.2 + Number(input.scAAAUlt||1)*0.04 + Number(input.outcome||1)*0.2'),('ScrOsteoporosisExt','0.18 + Number(input.scOsteo||1)*0.2 + Number(input.scDexaScore||1)*0.04 + Number(input.outcome||1)*0.2'),('ScrDiabetesExt','0.18 + Number(input.scDM||1)*0.2 + Number(input.scFBG||1)*0.04 + Number(input.outcome||1)*0.2'),('ScrGlaucomaExt','0.18 + Number(input.scGlaucoma||1)*0.2 + Number(input.scIOP||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_wellness_ext101':[('WellAdultExt','0.18 + Number(input.wlAdult||1)*0.2 + Number(input.wlAge||1)*0.04 + Number(input.outcome||1)*0.2'),('WellChildExt','0.18 + Number(input.wlChild||1)*0.2 + Number(input.wlChildAge||1)*0.04 + Number(input.outcome||1)*0.2'),('WellExerciseExt','0.18 + Number(input.wlExercise||1)*0.2 + Number(input.wlActMin||1)*0.04 + Number(input.outcome||1)*0.2'),('WellDietExt','0.18 + Number(input.wlDiet||1)*0.2 + Number(input.wlDietScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellSleepExt','0.18 + Number(input.wlSleep||1)*0.2 + Number(input.wlSleepHrs||1)*0.04 + Number(input.outcome||1)*0.2'),('WellStressExt','0.18 + Number(input.wlStress||1)*0.2 + Number(input.wlStressScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellSocialExt','0.18 + Number(input.wlSocial||1)*0.2 + Number(input.wlSocialConn||1)*0.04 + Number(input.outcome||1)*0.2'),('WellSexualExt','0.18 + Number(input.wlSexual||1)*0.2 + Number(input.wlSexRisk||1)*0.04 + Number(input.outcome||1)*0.2'),('WellSpiritualExt','0.18 + Number(input.wlSpirit||1)*0.2 + Number(input.wlSpiritScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WellOccupationalExt','0.18 + Number(input.wlOccup||1)*0.2 + Number(input.wlJobRisk||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.36.36.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.36.36.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.36.36.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.36.36.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MJ v3.36.36.0 done')