import os
MODULES=['pcc_neuro_ext149','pcc_pediatric_neuro_ext138','pcc_pediatric_surg_ext138']
FUNCS={
'pcc_neuro_ext149':[('NeurocutaneousTBAExt','0.18 + Number(input.tuberous||1)*0.2 + Number(input.brain||1)*0.2 + Number(input.outcome||1)*0.2'),('NeurofibromatosisExt','0.18 + Number(input.nf||1)*0.2 + Number(input.tumor||1)*0.2 + Number(input.outcome||1)*0.2'),('SturgeWeberExt','0.18 + Number(input.sturge||1)*0.2 + Number(input.brain||1)*0.2 + Number(input.outcome||1)*0.2'),('AtaxiaTelangiectasiaExt','0.18 + Number(input.at||1)*0.2 + Number(input.cerebellar||1)*0.2 + Number(input.outcome||1)*0.2'),('VonHippelLindauExt','0.18 + Number(input.vhl||1)*0.2 + Number(input.hemangioblastoma||1)*0.2 + Number(input.outcome||1)*0.2'),('CADASILExt','0.18 + Number(input.cadasil||1)*0.2 + Number(input.smallVessel||1)*0.2 + Number(input.outcome||1)*0.2'),('MELASExt','0.18 + Number(input.melas||1)*0.2 + Number(input.mito||1)*0.2 + Number(input.outcome||1)*0.2'),('MERRFExt','0.18 + Number(input.merrf||1)*0.2 + Number(input.mito||1)*0.2 + Number(input.outcome||1)*0.2'),('LeberExt','0.18 + Number(input.leber||1)*0.2 + Number(input.optical||1)*0.2 + Number(input.outcome||1)*0.2'),('HuntingtonExt','0.18 + Number(input.huntington||1)*0.2 + Number(input.cag||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext138':[('PediatricNF1Ext','0.18 + Number(input.age||5)*0.04 + Number(input.nf1||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNF2Ext','0.18 + Number(input.age||10)*0.04 + Number(input.nf2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTuberousExt','0.18 + Number(input.age||5)*0.04 + Number(input.tsc||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSturgeWeberExt','0.18 + Number(input.age||1)*0.04 + Number(input.sw||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAtaxiaTelExt','0.18 + Number(input.age||3)*0.04 + Number(input.at||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVHLchildExt','0.18 + Number(input.age||10)*0.04 + Number(input.vhl||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMitoEncephExt','0.18 + Number(input.age||3)*0.04 + Number(input.mito||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLeighExt','0.18 + Number(input.age||1)*0.04 + Number(input.leigh||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDravetExt','0.18 + Number(input.age||1)*0.04 + Number(input.dravet||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricWestSynExt','0.18 + Number(input.age||1)*0.04 + Number(input.west||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext138':[('PediatricNF1MgmtExt','0.18 + Number(input.age||5)*0.04 + Number(input.mgmt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTSCSurgeryExt','0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSturgeLaserExt','0.18 + Number(input.age||1)*0.04 + Number(input.laser||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricATMgmtExt','0.18 + Number(input.age||3)*0.04 + Number(input.atMgmt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVHLScreenExt','0.18 + Number(input.age||10)*0.04 + Number(input.vhlScreen||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMitoSuppExt','0.18 + Number(input.age||3)*0.04 + Number(input.mitoSupp||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDravetRxExt','0.18 + Number(input.age||1)*0.04 + Number(input.stiripentol||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDravetCannabExt','0.18 + Number(input.age||5)*0.04 + Number(input.cbd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricWestSteroidExt','0.18 + Number(input.age||1)*0.04 + Number(input.acth||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVigabatrinExt','0.18 + Number(input.age||1)*0.04 + Number(input.vigabatrin||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.248.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.248.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.248.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.248.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KP v3.248.0 done')