import os
MODULES=['pcc_neuro_ext166','pcc_pediatric_neuro_ext155','pcc_pediatric_surg_ext155']
FUNCS={
'pcc_neuro_ext166':[('LowBackPainRadExt','0.18 + Number(input.lbp||1)*0.2 + Number(input.radiculopathy||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalStenosisExt','0.18 + Number(input.stenosis||1)*0.2 + Number(input.neurogenicClaud||1)*0.2 + Number(input.outcome||1)*0.2'),('DiscHerniationExt','0.18 + Number(input.herniation||1)*0.2 + Number(input.dermatome||1)*0.2 + Number(input.outcome||1)*0.2'),('CaudaEquinaExt','0.18 + Number(input.caudaEquina||1)*0.2 + Number(input.saddle||1)*0.2 + Number(input.outcome||1)*0.2'),('SpondylolisthesisExt','0.18 + Number(input.spondy||1)*0.2 + Number(input.slip||1)*0.2 + Number(input.outcome||1)*0.2'),('MyelopathyExt','0.18 + Number(input.myelopathy||1)*0.2 + Number(input.longitud||1)*0.2 + Number(input.outcome||1)*0.2'),('FailedBackSurgeryExt','0.18 + Number(input.fbs||1)*0.2 + Number(input.persistentPain||1)*0.2 + Number(input.outcome||1)*0.2'),('VertebralFractureExt','0.18 + Number(input.vertFx||1)*0.2 + Number(input.osteoporosis||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalEpiduralAbscessExt','0.18 + Number(input.epiduralAbscess||1)*0.2 + Number(input.fever||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalCordInfarctionExt','0.18 + Number(input.cordInfarct||1)*0.2 + Number(input.anteriorSpinal||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext155':[('PediatricTetheredExt','0.18 + Number(input.age||5)*0.04 + Number(input.tethered||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricScoliNeuroExt','0.18 + Number(input.age||10)*0.04 + Number(input.scoliNeuro||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDiscitisExt','0.18 + Number(input.age||3)*0.04 + Number(input.discitis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpiduralAbsExt','0.18 + Number(input.age||5)*0.04 + Number(input.pEpiduralAbs||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTransverseMylExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTM||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCordTumorExt','0.18 + Number(input.age||8)*0.04 + Number(input.cordTumor||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSyringomyeliaExt','0.18 + Number(input.age||5)*0.04 + Number(input.syrinx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChiarimalExt','0.18 + Number(input.age||5)*0.04 + Number(input.chiariMal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalTraumaExt','0.18 + Number(input.age||8)*0.04 + Number(input.pSpinalTrauma||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinaBifidaExt','0.18 + Number(input.age||0)*0.04 + Number(input.spinaBifida||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext155':[('PediatricTetheredReleaseExt','0.18 + Number(input.age||5)*0.04 + Number(input.tetheredRelease||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricScoliMonitorExt','0.18 + Number(input.age||10)*0.04 + Number(input.scoliMon||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDiscitisAbxExt','0.18 + Number(input.age||3)*0.04 + Number(input.discitisAbx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpiduralDrainExt','0.18 + Number(input.age||5)*0.04 + Number(input.epiduralDrain||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTMSteroidExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTMSteroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCordTumorSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.cordTumorSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSyrinxSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.syrinxSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChiariSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.chiariSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalTraumaSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pSpinalTraumaSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinaBifidaClosureExt','0.18 + Number(input.age||0)*0.04 + Number(input.sbClosure||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.265.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.265.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.265.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.265.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LG v3.265.0 done')