import os
MODULES=['pcc_neuro_ext165','pcc_pediatric_neuro_ext154','pcc_pediatric_surg_ext154']
FUNCS={
'pcc_neuro_ext165':[('VertigoBPPVext','0.18 + Number(input.bppv||1)*0.2 + Number(input.dixHallpike||1)*0.2 + Number(input.outcome||1)*0.2'),('VestibularNeuritisExt','0.18 + Number(input.vestNeur||1)*0.2 + Number(input.acuteVertigo||1)*0.2 + Number(input.outcome||1)*0.2'),('MeniereDiseaseExt','0.18 + Number(input.meniere||1)*0.2 + Number(input.endolymph||1)*0.2 + Number(input.outcome||1)*0.2'),('LabyrinthitisExt','0.18 + Number(input.labyrinth||1)*0.2 + Number(input.hearingLoss||1)*0.2 + Number(input.outcome||1)*0.2'),('SuperiorCanalDehiscenceExt','0.18 + Number(input.scd||1)*0.2 + Number(input.bonyDefect||1)*0.2 + Number(input.outcome||1)*0.2'),('BilateralVestibulopathyExt','0.18 + Number(input.bvp||1)*0.2 + Number(input.oscillopsia||1)*0.2 + Number(input.outcome||1)*0.2'),('VestibularMigraineExt','0.18 + Number(input.vestMig||1)*0.2 + Number(input.headache||1)*0.2 + Number(input.outcome||1)*0.2'),('MalDeDebarquementExt','0.18 + Number(input.mdd||1)*0.2 + Number(input.rocking||1)*0.2 + Number(input.outcome||1)*0.2'),('PersistentPosturalExt','0.18 + Number(input.pppd||1)*0.2 + Number(input.postural||1)*0.2 + Number(input.outcome||1)*0.2'),('CervicogenicVertigoExt','0.18 + Number(input.cervVertigo||1)*0.2 + Number(input.cervical||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext154':[('PediatricBPPVext','0.18 + Number(input.age||5)*0.04 + Number(input.pBPPV||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVestNeurExt','0.18 + Number(input.age||8)*0.04 + Number(input.pVestNeur||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMeniereExt','0.18 + Number(input.age||10)*0.04 + Number(input.pMeniere||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLabyrinthExt','0.18 + Number(input.age||5)*0.04 + Number(input.pLab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMigraineVertExt','0.18 + Number(input.age||8)*0.04 + Number(input.pMigVert||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOtitisVertigoExt','0.18 + Number(input.age||3)*0.04 + Number(input.omVertigo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCholesteatomaExt','0.18 + Number(input.age||5)*0.04 + Number(input.cholesteatoma||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCPvertigoExt','0.18 + Number(input.age||5)*0.04 + Number(input.cpVertigo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTumorVertigoExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTumorVert||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVisualVertigoExt','0.18 + Number(input.age||5)*0.04 + Number(input.visualVert||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext154':[('PediatricBPPVepleyExt','0.18 + Number(input.age||5)*0.04 + Number(input.bppvEpley||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVestRehabExt','0.18 + Number(input.age||8)*0.04 + Number(input.vestRehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMeniereDiurExt','0.18 + Number(input.age||10)*0.04 + Number(input.meniereDiur||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLabyrinthSteroidExt','0.18 + Number(input.age||5)*0.04 + Number(input.labSteroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMigraineVestPrevExt','0.18 + Number(input.age||8)*0.04 + Number(input.migVestPrev||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOtitisSurgExt','0.18 + Number(input.age||3)*0.04 + Number(input.omSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCholesteatomaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.cholSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCPRehabExt','0.18 + Number(input.age||5)*0.04 + Number(input.cpRehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTumorVertSurgExt','0.18 + Number(input.age||8)*0.04 + Number(input.tumorVertSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVisualVestTrainExt','0.18 + Number(input.age||5)*0.04 + Number(input.visVestTrain||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.264.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.264.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.264.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.264.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LF v3.264.0 done')