import os
MODULES=['pcc_neuro_ext197','pcc_pediatric_neuro_ext186','pcc_pediatric_surg_ext186']
FUNCS={
'pcc_neuro_ext197':[('CerebellarAdultExt','0.18 + Number(input.cerebellarAdult||1)*0.2 + Number(input.icars||1)*0.04 + Number(input.outcome||1)*0.2'),('SpinocerebellarAdultExt','0.18 + Number(input.scaAdult||1)*0.2 + Number(input.scaType||1)*0.2 + Number(input.outcome||1)*0.2'),('FriedreichAdultExt','0.18 + Number(input.faAdult||1)*0.2 + Number(input.frataxin||1)*0.2 + Number(input.outcome||1)*0.2'),('AtaxiaTelangiectasiaAdultExt','0.18 + Number(input.atAdult||1)*0.2 + Number(input.atmGene||1)*0.2 + Number(input.outcome||1)*0.2'),('MSAadultExt','0.18 + Number(input.msaAdult||1)*0.2 + Number(input.msaType||1)*0.2 + Number(input.outcome||1)*0.2'),('PSPadultExt','0.18 + Number(input.pspAdult||1)*0.2 + Number(input.pspVariant||1)*0.2 + Number(input.outcome||1)*0.2'),('CBGDadultExt','0.18 + Number(input.cbgdAdult||1)*0.2 + Number(input.cbgdType||1)*0.2 + Number(input.outcome||1)*0.2'),('HuntingtonAdultExt','0.18 + Number(input.hdAdult||1)*0.2 + Number(input.cagRepeat||1)*0.04 + Number(input.outcome||1)*0.2'),('ChoreaSydenhamAdultExt','0.18 + Number(input.sydenhamAdult||1)*0.2 + Number(input.strepInf||1)*0.2 + Number(input.outcome||1)*0.2'),('WilsonAdultExt2','0.18 + Number(input.wilsonA||1)*0.2 + Number(input.copperLevel||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext186':[('PediatricCerebellarExt','0.18 + Number(input.age||5)*0.04 + Number(input.pCerebellar||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAText','0.18 + Number(input.age||3)*0.04 + Number(input.pAT||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFAext','0.18 + Number(input.age||8)*0.04 + Number(input.pFA||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHDExt','0.18 + Number(input.age||8)*0.04 + Number(input.pHD||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChoreaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pChoreaSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSydenhamExt','0.18 + Number(input.age||8)*0.04 + Number(input.pSydenham||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTicExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTic||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTouretteExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTourette||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDystoniaExt','0.18 + Number(input.age||3)*0.04 + Number(input.pDystonia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAtaxiaTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pAtaxiaTx||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext186':[('PediatricCerebellarSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pCerebellarSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricATSxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pATSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFASxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pFASx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHDSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pHDSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChoreaTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pChoreaTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSydenhamTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pSydenhamTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTicTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTicTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTouretteTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTouretteTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDystoniaTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pDystoniaTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAtaxiaRehabExt','0.18 + Number(input.age||5)*0.04 + Number(input.pAtaxiaRehab||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.26.26.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.26.26.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.26.26.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.26.26.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-HZ v3.26.26.0 done')