import os
MODULES=['pcc_admin_ext101','pcc_quality_ext101','pcc_compliance_ext101']
FUNCS={
'pcc_admin_ext101':[('AdmSchedulingExt','0.18 + Number(input.adSched||1)*0.2 + Number(input.adApptType||1)*0.2 + Number(input.outcome||1)*0.2'),('AdmBedManagementExt','0.18 + Number(input.adBed||1)*0.2 + Number(input.adOccupancy||1)*0.04 + Number(input.outcome||1)*0.2'),('AdmStaffingExt','0.18 + Number(input.adStaff||1)*0.2 + Number(input.adNurseRatio||1)*0.04 + Number(input.outcome||1)*0.2'),('AdmInventoryExt','0.18 + Number(input.adInv||1)*0.2 + Number(input.adStockOut||1)*0.04 + Number(input.outcome||1)*0.2'),('AdmBillingExt','0.18 + Number(input.adBill||1)*0.2 + Number(input.adClaimDenial||1)*0.04 + Number(input.outcome||1)*0.2'),('AdmInsuranceExt','0.18 + Number(input.adIns||1)*0.2 + Number(input.adAuthStatus||1)*0.2 + Number(input.outcome||1)*0.2'),('AdmReportingExt','0.18 + Number(input.adReport||1)*0.2 + Number(input.adReportFreq||1)*0.04 + Number(input.outcome||1)*0.2'),('AdmIText','0.18 + Number(input.adIT||1)*0.2 + Number(input.adUptime||1)*0.04 + Number(input.outcome||1)*0.2'),('AdmLegalExt','0.18 + Number(input.adLegal||1)*0.2 + Number(input.adComplaintType||1)*0.2 + Number(input.outcome||1)*0.2'),('AdmStrategicExt','0.18 + Number(input.adStrat||1)*0.2 + Number(input.adGoalType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_quality_ext101':[('QALeadershipExt','0.18 + Number(input.qaLead||1)*0.2 + Number(input.qaLeadScore||1)*0.04 + Number(input.outcome||1)*0.2'),('QAPatientSafetyExt','0.18 + Number(input.qaSafety||1)*0.2 + Number(input.qaIncidentRate||1)*0.04 + Number(input.outcome||1)*0.2'),('QAInfectionExt','0.18 + Number(input.qaInfection||1)*0.2 + Number(input.qaInfRate||1)*0.04 + Number(input.outcome||1)*0.2'),('QAMedicationExt','0.18 + Number(input.qaMed||1)*0.2 + Number(input.qaMedErrorRate||1)*0.04 + Number(input.outcome||1)*0.2'),('QAFallsExt','0.18 + Number(input.qaFalls||1)*0.2 + Number(input.qaFallRate||1)*0.04 + Number(input.outcome||1)*0.2'),('QAPressUlcerExt','0.18 + Number(input.qaPU||1)*0.2 + Number(input.qaPURate||1)*0.04 + Number(input.outcome||1)*0.2'),('QAReadmissionExt','0.18 + Number(input.qaReadmit||1)*0.2 + Number(input.qaReadmitRate||1)*0.04 + Number(input.outcome||1)*0.2'),('QAMortalityExt','0.18 + Number(input.qaMort||1)*0.2 + Number(input.qaMortRate||1)*0.04 + Number(input.outcome||1)*0.2'),('QAPtSatisfactionExt','0.18 + Number(input.qaPtSat||1)*0.2 + Number(input.qaPtSatScore||1)*0.04 + Number(input.outcome||1)*0.2'),('QAAccreditationExt','0.18 + Number(input.qaAccred||1)*0.2 + Number(input.qaAccredCycle||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_compliance_ext101':[('CmpZATCAExt','0.18 + Number(input.cmpZATCA||1)*0.2 + Number(input.cmpZatcaType||1)*0.2 + Number(input.outcome||1)*0.2'),('CmpNPHIESext','0.18 + Number(input.cmpNPHIES||1)*0.2 + Number(input.cmpNphiesType||1)*0.2 + Number(input.outcome||1)*0.2'),('CmpCBAHIext','0.18 + Number(input.cmpCBAHI||1)*0.2 + Number(input.cmpCbachiScore||1)*0.04 + Number(input.outcome||1)*0.2'),('CmpPDPLext','0.18 + Number(input.cmpPDPL||1)*0.2 + Number(input.cmpPdplType||1)*0.2 + Number(input.outcome||1)*0.2'),('CmpHIPAAext','0.18 + Number(input.cmpHIPAA||1)*0.2 + Number(input.cmpHipaaType||1)*0.2 + Number(input.outcome||1)*0.2'),('CmpJCIext','0.18 + Number(input.cmpJCI||1)*0.2 + Number(input.cmpJciScore||1)*0.04 + Number(input.outcome||1)*0.2'),('CmpMOHext','0.18 + Number(input.cmpMOH||1)*0.2 + Number(input.cmpMohType||1)*0.2 + Number(input.outcome||1)*0.2'),('CmpSFDAext','0.18 + Number(input.cmpSFDA||1)*0.2 + Number(input.cmpSfdaType||1)*0.2 + Number(input.outcome||1)*0.2'),('CmpSCFHSext','0.18 + Number(input.cmpSCFHS||1)*0.2 + Number(input.cmpScfhsType||1)*0.2 + Number(input.outcome||1)*0.2'),('CmpAuditExt','0.18 + Number(input.cmpAudit||1)*0.2 + Number(input.cmpAuditFinding||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.37.37.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.37.37.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.37.37.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.37.37.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MK v3.37.37.0 done')