import os
MODULES=['pcc_neuro_ext174','pcc_pediatric_neuro_ext163','pcc_pediatric_surg_ext163']
FUNCS={
'pcc_neuro_ext174':[('EpilepsyGeneticsExt','0.18 + Number(input.epiGene||1)*0.2 + Number(input.inherit||1)*0.2 + Number(input.outcome||1)*0.2'),('SCN1AepilepsyExt','0.18 + Number(input.scn1a||1)*0.2 + Number(input.dravet||1)*0.2 + Number(input.outcome||1)*0.2'),('GLUT1DeficiencyExt','0.18 + Number(input.glut1||1)*0.2 + Number(input.glucoseCSF||1)*0.2 + Number(input.outcome||1)*0.2'),('PyridoxineDepExt','0.18 + Number(input.pyridoxine||1)*0.2 + Number(input.b6Resp||1)*0.2 + Number(input.outcome||1)*0.2'),('PyridoxalPhosExt','0.18 + Number(input.plp||1)*0.2 + Number(input.plpResp||1)*0.2 + Number(input.outcome||1)*0.2'),('FolinicAcidExt','0.18 + Number(input.folinic||1)*0.2 + Number(input.folinicResp||1)*0.2 + Number(input.outcome||1)*0.2'),('KCNQ2encephalopathyExt','0.18 + Number(input.kcnq2||1)*0.2 + Number(input.neonatalSz||1)*0.2 + Number(input.outcome||1)*0.2'),('STXBP1encephalopathyExt','0.18 + Number(input.stxbp1||1)*0.2 + Number(input.eiec||1)*0.2 + Number(input.outcome||1)*0.2'),('CDKL5deficiencyExt','0.18 + Number(input.cdkl5||1)*0.2 + Number(input.earlyOnset||1)*0.2 + Number(input.outcome||1)*0.2'),('PCDH19epilepsyExt','0.18 + Number(input.pcdh19||1)*0.2 + Number(input.femaleOnly||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext163':[('PediatricEpiGeneExt','0.18 + Number(input.age||5)*0.04 + Number(input.pEpiGene||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSCN1AExt','0.18 + Number(input.age||1)*0.04 + Number(input.pSCN1A||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGLUT1Ext','0.18 + Number(input.age||3)*0.04 + Number(input.pGLUT1||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricB6DepExt','0.18 + Number(input.age||0)*0.04 + Number(input.pB6Dep||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPLPdeExt','0.18 + Number(input.age||0)*0.04 + Number(input.pPLPde||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFolinicDepExt','0.18 + Number(input.age||0)*0.04 + Number(input.pFolinicDep||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricKCNQ2Ext','0.18 + Number(input.age||0)*0.04 + Number(input.pKCNQ2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSTXBP1Ext','0.18 + Number(input.age||1)*0.04 + Number(input.pSTXBP1||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCDKL5Ext','0.18 + Number(input.age||1)*0.04 + Number(input.pCDKL5||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPCDH19Ext','0.18 + Number(input.age||3)*0.04 + Number(input.pPCDH19||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext163':[('PediatricEpiGeneTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.epiGeneTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSCN1ATxExt','0.18 + Number(input.age||1)*0.04 + Number(input.scn1aTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGLUT1ketoExt','0.18 + Number(input.age||3)*0.04 + Number(input.glut1Keto||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricB6DepRxExt','0.18 + Number(input.age||0)*0.04 + Number(input.b6DepRx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPLPdeRxExt','0.18 + Number(input.age||0)*0.04 + Number(input.plpDepRx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFolinicDepRxExt','0.18 + Number(input.age||0)*0.04 + Number(input.folinicRx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricKCNQ2RxExt','0.18 + Number(input.age||0)*0.04 + Number(input.kcnq2Rx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSTXBP1TxExt','0.18 + Number(input.age||1)*0.04 + Number(input.stxbp1Tx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCDKL5TxExt','0.18 + Number(input.age||1)*0.04 + Number(input.cdkl5Tx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPCDH19CBText','0.18 + Number(input.age||3)*0.04 + Number(input.pcdh19CBT||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.1.3.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.1.3.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.1.3.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.1.3.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-AC v3.1.3.0 done')