import os
MODULES=['pcc_neuro_ext91','pcc_pediatric_neuro_ext80','pcc_pediatric_surg_ext80']
FUNCS={
'pcc_neuro_ext91':[('EpilepsyNeuropsychExt','0.2 + Number(input.memory||80)*0.005 + Number(input.executive||75)*0.005 + Number(input.attention||70)*0.005'),('WadaLanguageExt','0.2 + Number(input.leftDom||1)*0.2 + Number(input.rightDom||0)*0.05 + Number(input.memory||7)*0.04'),('MemoryWadaExt','0.2 + Number(input.lMem||7)*0.04 + Number(input.rMem||7)*0.04 + Number(input.passFail||1)*0.15'),('PreopNeuropsychExt','0.18 + Number(input.brief||0)*0.1 + Number(input.wais||100)*0.005 + Number(input.cog||90)*0.005'),('PostopCogDeclineExt','0.2 + Number(input.followUp||12)*0.01 + Number(input.decline||5)*0.04 + Number(input.recovery||1)*0.1'),('RehabCogRestorationExt','0.15 + Number(input.intensity||3)*0.1 + Number(input.weeks||8)*0.04 + Number(input.gain||10)*0.04'),('SeizureFreeOutcomeExt','0.2 + Number(input.engelI||75)*0.005 + Number(input.followMonths||24)*0.01 + Number(input.qolie||80)*0.005'),('CognitiveRehabGoalsExt','0.18 + Number(input.goals||5)*0.05 + Number(input.weeks||12)*0.04 + Number(input.met||3)*0.08'),('MoodScreenEpilepsyExt','0.2 + Number(input.phq9||5)*0.04 + Number(input.gad7||5)*0.04 + Number(input.suicide||0)*0.1'),('NeuropsychologyReferralExt','0.15 + Number(input.urgent||1)*0.3 + Number(input.reason||1)*0.1 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext80':[('PediatricNeuropsychExt','0.2 + Number(input.kidMem||85)*0.005 + Number(input.executive||80)*0.005 + Number(input.behav||10)*0.04'),('PediatricWadaExt','0.18 + Number(input.age||10)*0.02 + Number(input.langDom||1)*0.2 + Number(input.passFail||1)*0.15'),('PediatricPreopCogExt','0.18 + Number(input.iq||100)*0.005 + Number(input.adapt||85)*0.005 + Number(input.lang||90)*0.005'),('PediatricPostopCogDeclineExt','0.2 + Number(input.followUp||12)*0.01 + Number(input.decline||5)*0.04 + Number(input.recovery||1)*0.1'),('PediatricRehabCogExt','0.15 + Number(input.intensity||3)*0.1 + Number(input.weeks||10)*0.04 + Number(input.gain||10)*0.04'),('PediatricSeizureFreeOutExt','0.2 + Number(input.engelI||75)*0.005 + Number(input.followMonths||24)*0.01 + Number(input.qolie||80)*0.005'),('PediatricSchoolReentryExt','0.18 + Number(input.schoolPlan||1)*0.3 + Number(input.weeks||4)*0.05 + Number(input.support||1)*0.2'),('PediatricMoodScreenExt','0.2 + Number(input.phq||5)*0.04 + Number(input.anxiety||5)*0.04 + Number(input.behav||1)*0.1'),('PediatricQualityOfLifeExt','0.18 + Number(input.qol||80)*0.005 + Number(input.parentStress||5)*0.04 + Number(input.support||1)*0.15'),('PediatricNeuropsychReferralExt','0.15 + Number(input.urgent||1)*0.3 + Number(input.reason||1)*0.1 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext80':[('PediatricNeuropsychPreSurgExt','0.2 + Number(input.iq||100)*0.005 + Number(input.lang||90)*0.005 + Number(input.motor||85)*0.005'),('PediatricWadaTestSurgExt','0.18 + Number(input.age||10)*0.02 + Number(input.lDom||1)*0.2 + Number(input.consent||1)*0.1'),('PediatricPostopCogCheckExt','0.2 + Number(input.day||3)*0.05 + Number(input.decline||5)*0.04 + Number(input.recovery||1)*0.1'),('PediatricPostopNeuroRehabExt','0.15 + Number(input.intensity||3)*0.1 + Number(input.weeks||8)*0.04 + Number(input.gain||10)*0.04'),('PediatricFamilyCounselSurgExt','0.18 + Number(input.sessions||3)*0.1 + Number(input.family||4)*0.05 + Number(input.stress||5)*0.05'),('PediatricOutcomeMetricsSurgExt','0.2 + Number(input.engelI||75)*0.005 + Number(input.qolie||80)*0.005 + Number(input.followMonths||24)*0.01'),('PediatricSchoolReentryPlanExt','0.18 + Number(input.plan||1)*0.3 + Number(input.weeks||4)*0.05 + Number(input.support||1)*0.2'),('PediatricMoodAssessSurgExt','0.2 + Number(input.phq||5)*0.04 + Number(input.anxiety||5)*0.04 + Number(input.behav||1)*0.1'),('PediatricQOLTrackingExt','0.18 + Number(input.qol||80)*0.005 + Number(input.parentStress||5)*0.04 + Number(input.support||1)*0.15'),('PediatricRefreralNeuropsychExt','0.15 + Number(input.urgent||1)*0.3 + Number(input.reason||1)*0.1 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\n// {m} engine (deterministic)\nmodule.exports.version=\'v3.190.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.190.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}};}};\n'
    eng+=f'\n// TS: v3.190.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'// filepath: pcc/{m}/{m}_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;else console.error(\'FAIL\',fn,r);}}console.log(\'{m} unit:\',pass,\'passed\');if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'// filepath: pcc/{m}/{m}_integration_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{value:1}},{{value:2}},{{value:3}},{{value:4}},{{value:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass,\'passed\');if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'// filepath: pcc/{m}/{m}_routes.js\nconst express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();\nrouter.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.190.0\',functions:Object.keys(F)}}));\nrouter.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});\nrouter.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});\nmodule.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- pcc/{m}/{m}_up.sql\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\')\nBEGIN\nCREATE TABLE [dbo].[{m}] (\n  [id] INT IDENTITY(1,1) PRIMARY KEY,\n  [tenant_id] NVARCHAR(64) NOT NULL,\n  [version] NVARCHAR(16) NOT NULL,\n  [module] NVARCHAR(64) NOT NULL,\n  [function] NVARCHAR(128) NOT NULL,\n  [input] NVARCHAR(MAX) NULL,\n  [score] DECIMAL(6,2) NULL,\n  [ts] DATETIME2 DEFAULT SYSUTCDATETIME()\n);\nEND\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files written')
print('P3-IJ v3.190.0: 16 files written')
