import os
MODULES=['pcc_neuro_ext183','pcc_pediatric_neuro_ext172','pcc_pediatric_surg_ext172']
FUNCS={
'pcc_neuro_ext183':[('NeuroGeriatricExt','0.18 + Number(input.geriNeuro||1)*0.2 + Number(input.frailty||1)*0.2 + Number(input.outcome||1)*0.2'),('DementiaWorkupExt','0.18 + Number(input.dementiaWorkup||1)*0.2 + Number(input.moCA||1)*0.04 + Number(input.outcome||1)*0.2'),('DeliriumExt','0.18 + Number(input.delirium||1)*0.2 + Number(input.cam||1)*0.2 + Number(input.outcome||1)*0.2'),('FallsNeuroExt','0.18 + Number(input.falls||1)*0.2 + Number(input.balance||1)*0.2 + Number(input.outcome||1)*0.2'),('PolypharmacyNeuroExt','0.18 + Number(input.polyPharm||1)*0.2 + Number(input.beers||1)*0.2 + Number(input.outcome||1)*0.2'),('BPSDext','0.18 + Number(input.bpsd||1)*0.2 + Number(input.agitation||1)*0.2 + Number(input.outcome||1)*0.2'),('CapgrasExt','0.18 + Number(input.capgras||1)*0.2 + Number(input.misidentif||1)*0.2 + Number(input.outcome||1)*0.2'),('CharlesBonnetExt','0.18 + Number(input.cbs||1)*0.2 + Number(input.visualHalluc||1)*0.2 + Number(input.outcome||1)*0.2'),('PDDext','0.18 + Number(input.pdd||1)*0.2 + Number(input.parkinsonDem||1)*0.2 + Number(input.outcome||1)*0.2'),('DLBext','0.18 + Number(input.dlb||1)*0.2 + Number(input.lewyBody||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext172':[('PediatricDemChildExt','0.18 + Number(input.age||5)*0.04 + Number(input.pDemChild||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNF1cognitiveExt','0.18 + Number(input.age||8)*0.04 + Number(input.pNF1cog||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTSCcogExt','0.18 + Number(input.age||5)*0.04 + Number(input.pTSCcog||1)*0.2 + Number(input.outcome||1)*0.2'),('Pediatric22q11Ext','0.18 + Number(input.age||3)*0.04 + Number(input.p22q11||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFragileXExt','0.18 + Number(input.age||3)*0.04 + Number(input.pFragileX||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDownCogExt','0.18 + Number(input.age||3)*0.04 + Number(input.pDownCog||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricWilliamsExt','0.18 + Number(input.age||3)*0.04 + Number(input.pWilliams||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPraderWilliExt','0.18 + Number(input.age||1)*0.04 + Number(input.pPrader||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAngelmanExt','0.18 + Number(input.age||1)*0.04 + Number(input.pAngelman||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRettExt','0.18 + Number(input.age||1)*0.04 + Number(input.pRett||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext172':[('PediatricDemChildTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pDemChildTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNF1cogTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pNF1cogTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTSCcogTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pTSCcogTx||1)*0.2 + Number(input.outcome||1)*0.2'),('Pediatric22q11TxExt','0.18 + Number(input.age||3)*0.04 + Number(input.p22q11Tx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFragileXTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pFragileXTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDownCogTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pDownCogTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricWilliamsTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pWilliamsTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPraderTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pPraderTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAngelmanTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pAngelmanTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRettTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pRettTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.1.12.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.1.12.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.1.12.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.1.12.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-AL v3.1.12.0 done')