import os
MODULES=['pcc_nephrology_ext102','pcc_urology_ext102','pcc_dialysis_ext102']
FUNCS={
'pcc_nephrology_ext102':[('NepGenExt','0.18 + Number(input.npGen||1)*0.2 + Number(input.npGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('NepAKIext','0.18 + Number(input.npAKI||1)*0.2 + Number(input.npAKIstage||1)*0.04 + Number(input.outcome||1)*0.2'),('NepCKDExt','0.18 + Number(input.npCKD||1)*0.2 + Number(input.npCKDstage||1)*0.04 + Number(input.outcome||1)*0.2'),('NepGNext','0.18 + Number(input.npGN||1)*0.2 + Number(input.npGNtype||1)*0.2 + Number(input.outcome||1)*0.2'),('NepHTnext','0.18 + Number(input.npHTN||1)*0.2 + Number(input.npHTNscore||1)*0.04 + Number(input.outcome||1)*0.2'),('NepStoneExt','0.18 + Number(input.npStone||1)*0.2 + Number(input.npStoneSize||1)*0.04 + Number(input.outcome||1)*0.2'),('NepTransplantExt','0.18 + Number(input.npTx||1)*0.2 + Number(input.npTxType||1)*0.2 + Number(input.outcome||1)*0.2'),('NepPKDExt','0.18 + Number(input.npPKD||1)*0.2 + Number(input.npPKDtype||1)*0.2 + Number(input.outcome||1)*0.2'),('NepElectrolyteExt','0.18 + Number(input.npElec||1)*0.2 + Number(input.npElecType||1)*0.2 + Number(input.outcome||1)*0.2'),('NepAcidBaseExt','0.18 + Number(input.npAB||1)*0.2 + Number(input.npABpH||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_urology_ext102':[('UroGenExt','0.18 + Number(input.urGen||1)*0.2 + Number(input.urGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('UroBPHext','0.18 + Number(input.urBPH||1)*0.2 + Number(input.urBPHscore||1)*0.04 + Number(input.outcome||1)*0.2'),('UroProstateExt','0.18 + Number(input.urPros||1)*0.2 + Number(input.urProsPSA||1)*0.04 + Number(input.outcome||1)*0.2'),('UroBladderExt','0.18 + Number(input.urBlad||1)*0.2 + Number(input.urBladType||1)*0.2 + Number(input.outcome||1)*0.2'),('UroKidneyExt','0.18 + Number(input.urKid||1)*0.2 + Number(input.urKidType||1)*0.2 + Number(input.outcome||1)*0.2'),('UroTesticExt','0.18 + Number(input.urTest||1)*0.2 + Number(input.urTestType||1)*0.2 + Number(input.outcome||1)*0.2'),('UroIncontExt','0.18 + Number(input.urIncon||1)*0.2 + Number(input.urInconType||1)*0.2 + Number(input.outcome||1)*0.2'),('UroUTIext','0.18 + Number(input.urUTI||1)*0.2 + Number(input.urUTItype||1)*0.2 + Number(input.outcome||1)*0.2'),('UroStoneExt','0.18 + Number(input.urStone||1)*0.2 + Number(input.urStoneSize||1)*0.04 + Number(input.outcome||1)*0.2'),('UroEDext','0.18 + Number(input.urED||1)*0.2 + Number(input.urEDscore||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_dialysis_ext102':[('DiaGenExt','0.18 + Number(input.diGen||1)*0.2 + Number(input.diGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('DiaHDext','0.18 + Number(input.diHD||1)*0.2 + Number(input.diHDhrs||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaPDext','0.18 + Number(input.diPD||1)*0.2 + Number(input.diPDtype||1)*0.2 + Number(input.outcome||1)*0.2'),('DiaAccessExt','0.18 + Number(input.diAcc||1)*0.2 + Number(input.diAccType||1)*0.2 + Number(input.outcome||1)*0.2'),('DiaAdequacyExt','0.18 + Number(input.diAdq||1)*0.2 + Number(input.diAdqKtV||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaAnemiaExt','0.18 + Number(input.diAn||1)*0.2 + Number(input.diAnHgb||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaMBDext','0.18 + Number(input.diMBD||1)*0.2 + Number(input.diMBDtype||1)*0.2 + Number(input.outcome||1)*0.2'),('DiaCVext','0.18 + Number(input.diCV||1)*0.2 + Number(input.diCVscore||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaInfectionExt','0.18 + Number(input.diInf||1)*0.2 + Number(input.diInfType||1)*0.2 + Number(input.outcome||1)*0.2'),('DiaTransplantExt','0.18 + Number(input.diTx||1)*0.2 + Number(input.diTxType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.53.53.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.53.53.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.53.53.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.53.53.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NA v3.53.53.0 done')