import os
MODULES=['pcc_anesthesiology_ext102','pcc_pain_mgmt_ext102','pcc_perioperative_ext102']
FUNCS={
'pcc_anesthesiology_ext102':[('AnGenExt','0.18 + Number(input.anGen||1)*0.2 + Number(input.anGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('AnGenAnesthExt','0.18 + Number(input.anGA||1)*0.2 + Number(input.anGAtype||1)*0.2 + Number(input.outcome||1)*0.2'),('AnRegAnesthExt','0.18 + Number(input.anRA||1)*0.2 + Number(input.anRAtype||1)*0.2 + Number(input.outcome||1)*0.2'),('AnLocalExt','0.18 + Number(input.anLA||1)*0.2 + Number(input.anLAtype||1)*0.2 + Number(input.outcome||1)*0.2'),('AnAirwayExt','0.18 + Number(input.anAw||1)*0.2 + Number(input.anAwScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AnMonitExt','0.18 + Number(input.anMon||1)*0.2 + Number(input.anMonType||1)*0.2 + Number(input.outcome||1)*0.2'),('AnFluidExt','0.18 + Number(input.anFl||1)*0.2 + Number(input.anFlRate||1)*0.04 + Number(input.outcome||1)*0.2'),('AnPostopExt','0.18 + Number(input.anPo||1)*0.2 + Number(input.anPoScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AnComplicExt','0.18 + Number(input.anCo||1)*0.2 + Number(input.anCoType||1)*0.2 + Number(input.outcome||1)*0.2'),('AnCriticalExt','0.18 + Number(input.anCr||1)*0.2 + Number(input.anCrType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pain_mgmt_ext102':[('PMGenExt','0.18 + Number(input.pmGen||1)*0.2 + Number(input.pmGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('PMAcuteExt','0.18 + Number(input.pmAcu||1)*0.2 + Number(input.pmAcuScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PMChronicExt','0.18 + Number(input.pmChr||1)*0.2 + Number(input.pmChrType||1)*0.2 + Number(input.outcome||1)*0.2'),('PMNeuroExt','0.18 + Number(input.pmNeu||1)*0.2 + Number(input.pmNeuScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PMCancerExt','0.18 + Number(input.pmCan||1)*0.2 + Number(input.pmCanScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PMBlockExt','0.18 + Number(input.pmBlk||1)*0.2 + Number(input.pmBlkType||1)*0.2 + Number(input.outcome||1)*0.2'),('PMInjectExt','0.18 + Number(input.pmInj||1)*0.2 + Number(input.pmInjType||1)*0.2 + Number(input.outcome||1)*0.2'),('PMPumpExt','0.18 + Number(input.pmPmp||1)*0.2 + Number(input.pmPmpType||1)*0.2 + Number(input.outcome||1)*0.2'),('PMStimExt','0.18 + Number(input.pmStm||1)*0.2 + Number(input.pmStmType||1)*0.2 + Number(input.outcome||1)*0.2'),('PMMultiExt','0.18 + Number(input.pmMlt||1)*0.2 + Number(input.pmMltScore||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_perioperative_ext102':[('POGenExt','0.18 + Number(input.poGen||1)*0.2 + Number(input.poGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('POPreopExt','0.18 + Number(input.poPre||1)*0.2 + Number(input.poPreScore||1)*0.04 + Number(input.outcome||1)*0.2'),('POIntropExt','0.18 + Number(input.poItr||1)*0.2 + Number(input.poItrType||1)*0.2 + Number(input.outcome||1)*0.2'),('POTimeOutExt','0.18 + Number(input.poTm||1)*0.2 + Number(input.poTmScore||1)*0.04 + Number(input.outcome||1)*0.2'),('POHandoffExt','0.18 + Number(input.poH||1)*0.2 + Number(input.poHScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PODischargeExt','0.18 + Number(input.poDis||1)*0.2 + Number(input.poDisType||1)*0.2 + Number(input.outcome||1)*0.2'),('POComplicExt','0.18 + Number(input.poCom||1)*0.2 + Number(input.poComType||1)*0.2 + Number(input.outcome||1)*0.2'),('POEnhancedExt','0.18 + Number(input.poERAS||1)*0.2 + Number(input.poERASScore||1)*0.04 + Number(input.outcome||1)*0.2'),('POFollowExt','0.18 + Number(input.poFol||1)*0.2 + Number(input.poFolType||1)*0.2 + Number(input.outcome||1)*0.2'),('POQualityExt','0.18 + Number(input.poQ||1)*0.2 + Number(input.poQScore||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.71.71.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.71.71.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.71.71.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.71.71.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NS v3.71.71.0 done')