import os
MODULES=['pcc_pharmacy_ext102','pcc_pharmacology_ext102','pcc_pharmacogenomics_ext102']
FUNCS={
'pcc_pharmacy_ext102':[('PharmGenExt','0.18 + Number(input.phGen||1)*0.2 + Number(input.phGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('PharmDispenExt','0.18 + Number(input.phDis||1)*0.2 + Number(input.phDisScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PharmCompExt','0.18 + Number(input.phCom||1)*0.2 + Number(input.phComType||1)*0.2 + Number(input.outcome||1)*0.2'),('PharmInteractExt','0.18 + Number(input.phInt||1)*0.2 + Number(input.phIntType||1)*0.2 + Number(input.outcome||1)*0.2'),('PharmAllergyExt','0.18 + Number(input.phAlg||1)*0.2 + Number(input.phAlgScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PharmDoseExt','0.18 + Number(input.phDose||1)*0.2 + Number(input.phDoseWeight||1)*0.04 + Number(input.outcome||1)*0.2'),('PharmIVext','0.18 + Number(input.phIV||1)*0.2 + Number(input.phIVtype||1)*0.2 + Number(input.outcome||1)*0.2'),('PharmTPNext','0.18 + Number(input.phTPN||1)*0.2 + Number(input.phTPNType||1)*0.2 + Number(input.outcome||1)*0.2'),('PharmClinicalExt','0.18 + Number(input.phCl||1)*0.2 + Number(input.phClType||1)*0.2 + Number(input.outcome||1)*0.2'),('PharmConsultExt','0.18 + Number(input.phCo||1)*0.2 + Number(input.phCoScore||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_pharmacology_ext102':[('PhcolGenExt','0.18 + Number(input.pcGen||1)*0.2 + Number(input.pcGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('PhcolPKext','0.18 + Number(input.pcPK||1)*0.2 + Number(input.pcPKType||1)*0.2 + Number(input.outcome||1)*0.2'),('PhcolPDext','0.18 + Number(input.pcPD||1)*0.2 + Number(input.pcPDType||1)*0.2 + Number(input.outcome||1)*0.2'),('PhcolMechExt','0.18 + Number(input.pcMech||1)*0.2 + Number(input.pcMechType||1)*0.2 + Number(input.outcome||1)*0.2'),('PhcolToxExt','0.18 + Number(input.pcTox||1)*0.2 + Number(input.pcToxType||1)*0.2 + Number(input.outcome||1)*0.2'),('PhcolAdvExt','0.18 + Number(input.pcAdv||1)*0.2 + Number(input.pcAdvType||1)*0.2 + Number(input.outcome||1)*0.2'),('PhcolContraExt','0.18 + Number(input.pcCon||1)*0.2 + Number(input.pcConType||1)*0.2 + Number(input.outcome||1)*0.2'),('PhcolPregExt','0.18 + Number(input.pcPreg||1)*0.2 + Number(input.pcPregType||1)*0.2 + Number(input.outcome||1)*0.2'),('PhcolPediExt','0.18 + Number(input.pcPedi||1)*0.2 + Number(input.pcPediType||1)*0.2 + Number(input.outcome||1)*0.2'),('PhcolRenalExt','0.18 + Number(input.pcRen||1)*0.2 + Number(input.pcRenCrCl||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_pharmacogenomics_ext102':[('PGxGenExt','0.18 + Number(input.pxGen||1)*0.2 + Number(input.pxGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('PGxCYPext','0.18 + Number(input.pxCYP||1)*0.2 + Number(input.pxCYPtype||1)*0.2 + Number(input.outcome||1)*0.2'),('PGxWarfarinExt','0.18 + Number(input.pxWar||1)*0.2 + Number(input.pxWarDose||1)*0.04 + Number(input.outcome||1)*0.2'),('PGxClopExt','0.18 + Number(input.pxClo||1)*0.2 + Number(input.pxCloType||1)*0.2 + Number(input.outcome||1)*0.2'),('PGxStatinExt','0.18 + Number(input.pxSta||1)*0.2 + Number(input.pxStaType||1)*0.2 + Number(input.outcome||1)*0.2'),('PGxSSRIext','0.18 + Number(input.pxSS||1)*0.2 + Number(input.pxSSType||1)*0.2 + Number(input.outcome||1)*0.2'),('PGxTPMText','0.18 + Number(input.pxTPMT||1)*0.2 + Number(input.pxTPMTtype||1)*0.2 + Number(input.outcome||1)*0.2'),('PGxDPDext','0.18 + Number(input.pxDPD||1)*0.2 + Number(input.pxDPDtype||1)*0.2 + Number(input.outcome||1)*0.2'),('PGxUGText','0.18 + Number(input.pxUGT||1)*0.2 + Number(input.pxUGTtype||1)*0.2 + Number(input.outcome||1)*0.2'),('PGxReportExt','0.18 + Number(input.pxRep||1)*0.2 + Number(input.pxRepType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.74.74.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.74.74.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.74.74.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.74.74.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NV v3.74.74.0 done')