import os
MODULES=['pcc_radiology_ext102','pcc_imaging_ext102','pcc_nuclear_med_ext102']
FUNCS={
'pcc_radiology_ext102':[('RadGenExt','0.18 + Number(input.rdGen||1)*0.2 + Number(input.rdGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('RadXrayExt','0.18 + Number(input.rdXr||1)*0.2 + Number(input.rdXrType||1)*0.2 + Number(input.outcome||1)*0.2'),('RadCText','0.18 + Number(input.rdCT||1)*0.2 + Number(input.rdCTtype||1)*0.2 + Number(input.outcome||1)*0.2'),('RadMRIext','0.18 + Number(input.rdMR||1)*0.2 + Number(input.rdMRType||1)*0.2 + Number(input.outcome||1)*0.2'),('RadUSext','0.18 + Number(input.rdUS||1)*0.2 + Number(input.rdUSType||1)*0.2 + Number(input.outcome||1)*0.2'),('RadFluoroExt','0.18 + Number(input.rdFl||1)*0.2 + Number(input.rdFlType||1)*0.2 + Number(input.outcome||1)*0.2'),('RadMammoExt','0.18 + Number(input.rdMa||1)*0.2 + Number(input.rdMaScore||1)*0.04 + Number(input.outcome||1)*0.2'),('RadAngioExt','0.18 + Number(input.rdAn||1)*0.2 + Number(input.rdAnType||1)*0.2 + Number(input.outcome||1)*0.2'),('RadIntervExt','0.18 + Number(input.rdIn||1)*0.2 + Number(input.rdInType||1)*0.2 + Number(input.outcome||1)*0.2'),('RadReportExt','0.18 + Number(input.rdRep||1)*0.2 + Number(input.rdRepScore||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_imaging_ext102':[('ImgGenExt','0.18 + Number(input.imGen||1)*0.2 + Number(input.imGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgDxExt','0.18 + Number(input.imDx||1)*0.2 + Number(input.imDxType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgIntervExt','0.18 + Number(input.imIn||1)*0.2 + Number(input.imInType||1)*0.2 + Number(input.outcome||1)*0.2'),('Img3Dext','0.18 + Number(input.im3D||1)*0.2 + Number(input.im3DType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgAIext','0.18 + Number(input.imAI||1)*0.2 + Number(input.imAIType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgContrastExt','0.18 + Number(input.imCo||1)*0.2 + Number(input.imCoType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgDoseExt','0.18 + Number(input.imDo||1)*0.2 + Number(input.imDoGy||1)*0.04 + Number(input.outcome||1)*0.2'),('ImgSafetyExt','0.18 + Number(input.imSa||1)*0.2 + Number(input.imSaScore||1)*0.04 + Number(input.outcome||1)*0.2'),('ImgArchiveExt','0.18 + Number(input.imAr||1)*0.2 + Number(input.imArScore||1)*0.04 + Number(input.outcome||1)*0.2'),('ImgTeleExt','0.18 + Number(input.imTe||1)*0.2 + Number(input.imTeType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_nuclear_med_ext102':[('NMGenExt','0.18 + Number(input.nmGen||1)*0.2 + Number(input.nmGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('NMPEText','0.18 + Number(input.nmPET||1)*0.2 + Number(input.nmPETtype||1)*0.2 + Number(input.outcome||1)*0.2'),('NMSPECText','0.18 + Number(input.nmSpec||1)*0.2 + Number(input.nmSpecType||1)*0.2 + Number(input.outcome||1)*0.2'),('NMScanExt','0.18 + Number(input.nmSc||1)*0.2 + Number(input.nmScType||1)*0.2 + Number(input.outcome||1)*0.2'),('NMThyroidExt','0.18 + Number(input.nmThy||1)*0.2 + Number(input.nmThyScore||1)*0.04 + Number(input.outcome||1)*0.2'),('NMBoneExt','0.18 + Number(input.nmBo||1)*0.2 + Number(input.nmBoType||1)*0.2 + Number(input.outcome||1)*0.2'),('NMCardiacExt','0.18 + Number(input.nmCar||1)*0.2 + Number(input.nmCarEF||1)*0.04 + Number(input.outcome||1)*0.2'),('NMRadioExt','0.18 + Number(input.nmRa||1)*0.2 + Number(input.nmRaType||1)*0.2 + Number(input.outcome||1)*0.2'),('NMDoseExt','0.18 + Number(input.nmDo||1)*0.2 + Number(input.nmDoMBq||1)*0.04 + Number(input.outcome||1)*0.2'),('NMQualityExt','0.18 + Number(input.nmQ||1)*0.2 + Number(input.nmQScore||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.76.76.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.76.76.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.76.76.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.76.76.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NX v3.76.76.0 done')