import os
MODULES=['pcc_neuro_ext144','pcc_pediatric_neuro_ext133','pcc_pediatric_surg_ext133']
FUNCS={
'pcc_neuro_ext144':[('SexualDysfunctionExt','0.18 + Number(input.libido||1)*0.2 + Number(input.erectile||1)*0.2 + Number(input.outcome||1)*0.2'),('AutonomicDysreflexiaSexExt','0.18 + Number(input.ad||1)*0.2 + Number(input.stimulus||1)*0.2 + Number(input.outcome||1)*0.2'),('MSexualExt','0.18 + Number(input.desire||1)*0.2 + Number(input.arousal||1)*0.2 + Number(input.outcome||1)*0.2'),('FSexualExt','0.18 + Number(input.lubrication||1)*0.2 + Number(input.orgasm||1)*0.2 + Number(input.outcome||1)*0.2'),('PostPartumSexualExt','0.18 + Number(input.pp||1)*0.2 + Number(input.hormone||1)*0.2 + Number(input.outcome||1)*0.2'),('CancerSexualExt','0.18 + Number(input.cancer||1)*0.2 + Number(input.treatment||1)*0.2 + Number(input.outcome||1)*0.2'),('MedicationInducedExt','0.18 + Number(input.ssri||1)*0.2 + Number(input.sexual||1)*0.2 + Number(input.outcome||1)*0.2'),('GenderDysphoriaExt','0.18 + Number(input.dysphoria||1)*0.2 + Number(input.gender||1)*0.2 + Number(input.outcome||1)*0.2'),('HypogonadismExt','0.18 + Number(input.test||1)*0.2 + Number(input.lowT||1)*0.2 + Number(input.outcome||1)*0.2'),('PrematureEjacExt','0.18 + Number(input.pe||1)*0.2 + Number(input.anxiety||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext133':[('PediatricGenderExt','0.18 + Number(input.age||10)*0.04 + Number(input.gender||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPubertyExt','0.18 + Number(input.age||10)*0.04 + Number(input.puberty||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAdrenarcheExt','0.18 + Number(input.age||5)*0.04 + Number(input.adrenarche||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGonadarcheExt','0.18 + Number(input.age||10)*0.04 + Number(input.gonadarche||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPrecociousExt','0.18 + Number(input.age||3)*0.04 + Number(input.precocious||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDelayedPubertyExt','0.18 + Number(input.age||15)*0.04 + Number(input.delayed||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTurnerExt','0.18 + Number(input.age||5)*0.04 + Number(input.turner||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricKlinefelterExt','0.18 + Number(input.age||10)*0.04 + Number(input.klinefelter||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHypogonadismExt','0.18 + Number(input.age||10)*0.04 + Number(input.hypogonadism||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSexDevExt','0.18 + Number(input.age||1)*0.04 + Number(input.dsd||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext133':[('PediatricPubertyBlockExt','0.18 + Number(input.age||10)*0.04 + Number(input.gnrh||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHormoneRxExt','0.18 + Number(input.age||10)*0.04 + Number(input.estrogen||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHypogonadismRxExt','0.18 + Number(input.age||10)*0.04 + Number(input.testosterone||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTurnerHRTtextExt','0.18 + Number(input.age||10)*0.04 + Number(input.hrt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricKlinefelterHRTextExt','0.18 + Number(input.age||10)*0.04 + Number(input.testosterone||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPrecociousBlockerExt','0.18 + Number(input.age||3)*0.04 + Number(input.gnrh||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDelayedHormonesExt','0.18 + Number(input.age||15)*0.04 + Number(input.hormones||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDSDsxExt','0.18 + Number(input.age||1)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGenderCounselingExt','0.18 + Number(input.age||10)*0.04 + Number(input.counseling||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPubertyMonitorExt','0.18 + Number(input.age||5)*0.04 + Number(input.monitor||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.243.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.243.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.243.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.243.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KK v3.243.0 done')
