import os
MODULES=['pcc_neuro_ext145','pcc_pediatric_neuro_ext134','pcc_pediatric_surg_ext134']
FUNCS={
'pcc_neuro_ext145':[('PregestationalDiabeticExt','0.18 + Number(input.diabetesType1||1)*0.2 + Number(input.control||1)*0.2 + Number(input.outcome||1)*0.2'),('GestationalDiabeticExt','0.18 + Number(input.gestational||1)*0.2 + Number(input.week||20)*0.01 + Number(input.outcome||1)*0.2'),('HypertensiveDisorderPregExt','0.18 + Number(input.preeclampsia||1)*0.2 + Number(input.severe||1)*0.2 + Number(input.outcome||1)*0.2'),('EclampsiaExt','0.18 + Number(input.seizure||1)*0.2 + Number(input.preeclampsia||1)*0.2 + Number(input.outcome||1)*0.2'),('HELLPext','0.18 + Number(input.hemolysis||1)*0.2 + Number(input.elevatedLiver||1)*0.2 + Number(input.outcome||1)*0.2'),('AcuteFattyLiverPregExt','0.18 + Number(input.afl||1)*0.2 + Number(input.week||30)*0.005 + Number(input.outcome||1)*0.2'),('HyperemesisGravidarumExt','0.18 + Number(input.hg||1)*0.2 + Number(input.week||10)*0.01 + Number(input.outcome||1)*0.2'),('CholestasisPregExt','0.18 + Number(input.cholestasis||1)*0.2 + Number(input.bileAcids||1)*0.2 + Number(input.outcome||1)*0.2'),('PlacentaAccretaExt','0.18 + Number(input.accreta||1)*0.2 + Number(input.priorCS||1)*0.2 + Number(input.outcome||1)*0.2'),('PeripartumCardiomyoExt','0.18 + Number(input.pcm||1)*0.2 + Number(input.pp||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext134':[('PediatricPregCompExt','0.18 + Number(input.age||1)*0.04 + Number(input.pregComp||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeonatalStrokeExt','0.18 + Number(input.age||0.1)*0.04 + Number(input.neonatalStroke||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHIEext','0.18 + Number(input.age||0.1)*0.04 + Number(input.hie||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIVHext','0.18 + Number(input.age||0.1)*0.04 + Number(input.ivh||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPVLext','0.18 + Number(input.age||0.1)*0.04 + Number(input.pvl||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHMDext','0.18 + Number(input.age||0.1)*0.04 + Number(input.hmd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNECext','0.18 + Number(input.age||0.5)*0.04 + Number(input.nec||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricROPext','0.18 + Number(input.age||0.5)*0.04 + Number(input.rop||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBPDext','0.18 + Number(input.age||0.5)*0.04 + Number(input.bpd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCPext','0.18 + Number(input.age||1)*0.04 + Number(input.cp||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext134':[('PediatricHypothermiaExt','0.18 + Number(input.age||0.1)*0.04 + Number(input.hypothermia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIVHsxExt','0.18 + Number(input.age||0.1)*0.04 + Number(input.drainage||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPVLsupportExt','0.18 + Number(input.age||0.1)*0.04 + Number(input.support||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHMDsupportExt','0.18 + Number(input.age||0.1)*0.04 + Number(input.surfactant||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNECsxExt','0.18 + Number(input.age||0.5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricROPlaserExt','0.18 + Number(input.age||0.5)*0.04 + Number(input.laser||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBPDsupportExt','0.18 + Number(input.age||0.5)*0.04 + Number(input.ventilator||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCPrehabExt','0.18 + Number(input.age||1)*0.04 + Number(input.rehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeonatalAntiext','0.18 + Number(input.age||0.1)*0.04 + Number(input.antiSeizure||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeonatalSteroidExt','0.18 + Number(input.age||0.1)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.244.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.244.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.244.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.244.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KL v3.244.0 done')
