import os
MODULES=['pcc_neuro_ext160','pcc_pediatric_neuro_ext149','pcc_pediatric_surg_ext149']
FUNCS={
'pcc_neuro_ext160':[('BrainTumorGliomaExt','0.18 + Number(input.glioma||1)*0.2 + Number(input.whoGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('BrainTumorMeningiomaExt','0.18 + Number(input.meningioma||1)*0.2 + Number(input.location||1)*0.2 + Number(input.outcome||1)*0.2'),('BrainTumorPituitaryExt','0.18 + Number(input.pituitary||1)*0.2 + Number(input.hormone||1)*0.2 + Number(input.outcome||1)*0.2'),('BrainMetastasisExt','0.18 + Number(input.brainMet||1)*0.2 + Number(input.primary||1)*0.2 + Number(input.outcome||1)*0.2'),('SpineTumorExt','0.18 + Number(input.spinetumor||1)*0.2 + Number(input.cordComp||1)*0.2 + Number(input.outcome||1)*0.2'),('BrainLymphomaExt','0.18 + Number(input.cnsLymphoma||1)*0.2 + Number(input.immuno||1)*0.2 + Number(input.outcome||1)*0.2'),('MedulloblastomaExt','0.18 + Number(input.medullo||1)*0.2 + Number(input.pediatricTumor||1)*0.2 + Number(input.outcome||1)*0.2'),('AcousticNeuromaExt','0.18 + Number(input.schwannoma||1)*0.2 + Number(input.hearing||1)*0.2 + Number(input.outcome||1)*0.2'),('PinealTumorExt','0.18 + Number(input.pineal||1)*0.2 + Number(input.parinaud||1)*0.2 + Number(input.outcome||1)*0.2'),('SkullBaseTumorExt','0.18 + Number(input.skullBase||1)*0.2 + Number(input.cranialNerve||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext149':[('PediatricMedulloExt','0.18 + Number(input.age||5)*0.04 + Number(input.pMedullo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPilocyticExt','0.18 + Number(input.age||8)*0.04 + Number(input.piloAstro||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpendymomaExt','0.18 + Number(input.age||5)*0.04 + Number(input.ependymomaP||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBrainstemExt','0.18 + Number(input.age||8)*0.04 + Number(input.dipg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricATRText','0.18 + Number(input.age||1)*0.04 + Number(input.atrt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCraniopharyngiomaExt','0.18 + Number(input.age||8)*0.04 + Number(input.craniophar||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPituitaryExt','0.18 + Number(input.age||12)*0.04 + Number(input.pPit||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChoroidPlexusExt','0.18 + Number(input.age||1)*0.04 + Number(input.chPlex||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalTumorExt','0.18 + Number(input.age||10)*0.04 + Number(input.pSpinal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeurofibromatosisTumorExt','0.18 + Number(input.age||8)*0.04 + Number(input.nfTumor||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext149':[('PediatricMedulloResectExt','0.18 + Number(input.age||5)*0.04 + Number(input.medResect||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPiloResectExt','0.18 + Number(input.age||8)*0.04 + Number(input.piloResect||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpendymomaResectExt','0.18 + Number(input.age||5)*0.04 + Number(input.epenResect||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDIPGBxExt','0.18 + Number(input.age||8)*0.04 + Number(input.dipgBx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricATRTSurgExt','0.18 + Number(input.age||1)*0.04 + Number(input.atrtSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCraniopharResectExt','0.18 + Number(input.age||8)*0.04 + Number(input.cranioResect||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPitTransExt','0.18 + Number(input.age||12)*0.04 + Number(input.pitTrans||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChoroidPlexSurgExt','0.18 + Number(input.age||1)*0.04 + Number(input.chPlexSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalTumorSurgExt','0.18 + Number(input.age||10)*0.04 + Number(input.pSpinalSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNFTumorSurgExt','0.18 + Number(input.age||8)*0.04 + Number(input.nfTumorSurg||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.259.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.259.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.259.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.259.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LA v3.259.0 done')