import os
MODULES=['pcc_psychiatry_ext102','pcc_mental_health_ext102','pcc_behavioral_health_ext102']
FUNCS={
'pcc_psychiatry_ext102':[('PsyGenExt','0.18 + Number(input.psGen||1)*0.2 + Number(input.psGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('PsyDepExt','0.18 + Number(input.psDep||1)*0.2 + Number(input.psDepScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PsyAnxExt','0.18 + Number(input.psAnx||1)*0.2 + Number(input.psAnxScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PsyBipolarExt','0.18 + Number(input.psBp||1)*0.2 + Number(input.psBpType||1)*0.2 + Number(input.outcome||1)*0.2'),('PsySchizoExt','0.18 + Number(input.psSch||1)*0.2 + Number(input.psSchScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PsyPTSDext','0.18 + Number(input.psPTS||1)*0.2 + Number(input.psPTSscore||1)*0.04 + Number(input.outcome||1)*0.2'),('PsyOCDext','0.18 + Number(input.psOCD||1)*0.2 + Number(input.psOCDScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PsyADHDext','0.18 + Number(input.psAD||1)*0.2 + Number(input.psADScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PsyEatingExt','0.18 + Number(input.psEat||1)*0.2 + Number(input.psEatType||1)*0.2 + Number(input.outcome||1)*0.2'),('PsyPersonalityExt','0.18 + Number(input.psPer||1)*0.2 + Number(input.psPerType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_mental_health_ext102':[('MHGenExt','0.18 + Number(input.mhGen||1)*0.2 + Number(input.mhGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('MHCounselExt','0.18 + Number(input.mhCou||1)*0.2 + Number(input.mhCouType||1)*0.2 + Number(input.outcome||1)*0.2'),('MHTherapyExt','0.18 + Number(input.mhTh||1)*0.2 + Number(input.mhThType||1)*0.2 + Number(input.outcome||1)*0.2'),('MHGroupExt','0.18 + Number(input.mhGr||1)*0.2 + Number(input.mhGrType||1)*0.2 + Number(input.outcome||1)*0.2'),('MHFamilyExt','0.18 + Number(input.mhFam||1)*0.2 + Number(input.mhFamType||1)*0.2 + Number(input.outcome||1)*0.2'),('MHCBText','0.18 + Number(input.mhCBT||1)*0.2 + Number(input.mhCBTScore||1)*0.04 + Number(input.outcome||1)*0.2'),('MHDBText','0.18 + Number(input.mhDBT||1)*0.2 + Number(input.mhDBTScore||1)*0.04 + Number(input.outcome||1)*0.2'),('MHMindfulExt','0.18 + Number(input.mhMin||1)*0.2 + Number(input.mhMinScore||1)*0.04 + Number(input.outcome||1)*0.2'),('MHCrisisExt','0.18 + Number(input.mhCri||1)*0.2 + Number(input.mhCriScore||1)*0.04 + Number(input.outcome||1)*0.2'),('MHScreenExt','0.18 + Number(input.mhScr||1)*0.2 + Number(input.mhScrScore||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_behavioral_health_ext102':[('BHGenExt','0.18 + Number(input.bhGen||1)*0.2 + Number(input.bhGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('BHAssessExt','0.18 + Number(input.bhAss||1)*0.2 + Number(input.bhAssScore||1)*0.04 + Number(input.outcome||1)*0.2'),('BHSubstanceExt','0.18 + Number(input.bhSub||1)*0.2 + Number(input.bhSubType||1)*0.2 + Number(input.outcome||1)*0.2'),('BHQuitExt','0.18 + Number(input.bhQuit||1)*0.2 + Number(input.bhQuitScore||1)*0.04 + Number(input.outcome||1)*0.2'),('BHWeightExt','0.18 + Number(input.bhWt||1)*0.2 + Number(input.bhWtScore||1)*0.04 + Number(input.outcome||1)*0.2'),('BHAdherenceExt','0.18 + Number(input.bhAdh||1)*0.2 + Number(input.bhAdhScore||1)*0.04 + Number(input.outcome||1)*0.2'),('BHSleepExt','0.18 + Number(input.bhSlp||1)*0.2 + Number(input.bhSlpScore||1)*0.04 + Number(input.outcome||1)*0.2'),('BHStressExt','0.18 + Number(input.bhStr||1)*0.2 + Number(input.bhStrScore||1)*0.04 + Number(input.outcome||1)*0.2'),('BHChronicExt','0.18 + Number(input.bhChr||1)*0.2 + Number(input.bhChrType||1)*0.2 + Number(input.outcome||1)*0.2'),('BHOutreachExt','0.18 + Number(input.bhOut||1)*0.2 + Number(input.bhOutScore||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.66.66.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.66.66.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.66.66.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.66.66.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NN v3.66.66.0 done')