import os
MODULES=['pcc_neuro_ext105','pcc_pediatric_neuro_ext94','pcc_pediatric_surg_ext94']
FUNCS={
'pcc_neuro_ext105':[('CerebralAmyloidAngioExt','0.18 + Number(input.age||75)*0.005 + Number(input.lobar||1)*0.2 + Number(input.microbleeds||1)*0.2'),('CADASILManagementExt','0.18 + Number(input.notch3||1)*0.2 + Number(input.migraine||1)*0.2 + Number(input.outcome||1)*0.2'),('RVCLSExt','0.18 + Number(input.trex1||1)*0.2 + Number(input.retinal||1)*0.2 + Number(input.outcome||1)*0.2'),('COL4A1StrokeExt','0.18 + Number(input.col4a1||1)*0.2 + Number(input.microbleeds||1)*0.2 + Number(input.outcome||1)*0.2'),('MoyamoyaAdultExt','0.18 + Number(input.bypass||1)*0.2 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2'),('SickleCellStrokeExt','0.18 + Number(input.transfusion||1)*0.2 + Number(input.tcd||1)*0.2 + Number(input.outcome||1)*0.2'),('AntiphospholipidStrokeExt','0.18 + Number(input.lupus||1)*0.2 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2'),('ThrombophiliaWorkupExt','0.15 + Number(input.factorv||1)*0.2 + Number(input.proteinC||1)*0.2 + Number(input.outcome||1)*0.2'),('HornerStrokeExt','0.18 + Number(input.dissection||1)*0.2 + Number(input.horner||1)*0.2 + Number(input.outcome||1)*0.2'),('PosteriorCircStenosisExt','0.18 + Number(input.stenosis||70)*0.005 + Number(input.symptoms||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext94':[('PediatricCerebralAmyloidExt','0.18 + Number(input.age||12)*0.02 + Number(input.family||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCADASILExt','0.18 + Number(input.notch3||1)*0.2 + Number(input.migraine||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRVCLScreeningExt','0.18 + Number(input.trex1||1)*0.2 + Number(input.eyeExam||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCOL4A1Ext','0.18 + Number(input.col4a1||1)*0.2 + Number(input.microbleeds||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMoyamoyaExt','0.18 + Number(input.bypass||1)*0.2 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSickleCellStrokeExt','0.18 + Number(input.transfusion||1)*0.2 + Number(input.tcd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAPLStrokeExt','0.18 + Number(input.lupus||1)*0.2 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricThrombophiliaExt','0.15 + Number(input.factorv||1)*0.2 + Number(input.proteinC||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeMonitoringExt','0.15 + Number(input.intensity||3)*0.1 + Number(input.weeks||12)*0.04 + Number(input.outcome||1)*0.2'),('PediatricStrokeGeneticCounselExt','0.15 + Number(input.mutations||2)*0.1 + Number(input.familyHistory||1)*0.15 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext94':[('PediatricCerebralAmyloidSxExt','0.18 + Number(input.age||12)*0.02 + Number(input.biopsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCADASILSxExt','0.18 + Number(input.notch3||1)*0.2 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRVCLSxExt','0.18 + Number(input.trex1||1)*0.2 + Number(input.procedure||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCOL4A1SxExt','0.18 + Number(input.col4a1||1)*0.2 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMoyamoyaBypassExt','0.18 + Number(input.age||7)*0.04 + Number(input.stages||2)*0.1 + Number(input.outcome||1)*0.2'),('PediatricSickleStrokeSxExt','0.18 + Number(input.transfusion||1)*0.2 + Number(input.exchange||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAPLStrokeSxExt','0.18 + Number(input.lupus||1)*0.2 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokePostOpCareExt','0.15 + Number(input.icu||3)*0.1 + Number(input.weeks||4)*0.04 + Number(input.outcome||1)*0.2'),('PediatricNeuroSxMonitoringExt','0.15 + Number(input.intensity||3)*0.1 + Number(input.days||7)*0.04 + Number(input.outcome||1)*0.2'),('PediatricNeuroSxFamilyScreenExt','0.15 + Number(input.familyHist||1)*0.15 + Number(input.testing||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\n// {m} engine (deterministic)\nmodule.exports.version=\'v3.204.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.204.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}};}};\n'
    eng+=f'\n// TS: v3.204.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'// filepath: pcc/{m}/{m}_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;else console.error(\'FAIL\',fn,r);}}console.log(\'{m} unit:\',pass,\'passed\');if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'// filepath: pcc/{m}/{m}_integration_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{value:1}},{{value:2}},{{value:3}},{{value:4}},{{value:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass,\'passed\');if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'// filepath: pcc/{m}/{m}_routes.js\nconst express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();\nrouter.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.204.0\',functions:Object.keys(F)}}));\nrouter.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});\nrouter.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});\nmodule.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- pcc/{m}/{m}_up.sql\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\')\nBEGIN\nCREATE TABLE [dbo].[{m}] (\n  [id] INT IDENTITY(1,1) PRIMARY KEY,\n  [tenant_id] NVARCHAR(64) NOT NULL,\n  [version] NVARCHAR(16) NOT NULL,\n  [module] NVARCHAR(64) NOT NULL,\n  [function] NVARCHAR(128) NOT NULL,\n  [input] NVARCHAR(MAX) NULL,\n  [score] DECIMAL(6,2) NULL,\n  [ts] DATETIME2 DEFAULT SYSUTCDATETIME()\n);\nEND\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files written')
print('P3-IX v3.204.0: 16 files written')
