import os
MODULES=['pcc_neuro_ext191','pcc_pediatric_neuro_ext180','pcc_pediatric_surg_ext180']
FUNCS={
'pcc_neuro_ext191':[('StrokeIschemicAdultExt','0.18 + Number(input.strokeAdult||1)*0.2 + Number(input.nihss||1)*0.04 + Number(input.outcome||1)*0.2'),('StrokeHemorrhagicAdultExt','0.18 + Number(input.ichAdult||1)*0.2 + Number(input.hematoma||1)*0.04 + Number(input.outcome||1)*0.2'),('TIAAadultExt','0.18 + Number(input.tiaAdult||1)*0.2 + Number(input.abcd2||1)*0.04 + Number(input.outcome||1)*0.2'),('SubarachnoidAdultExt','0.18 + Number(input.sahAdult||1)*0.2 + Number(input.huntHess||1)*0.04 + Number(input.outcome||1)*0.2'),('CVStext','0.18 + Number(input.cvstAdult||1)*0.2 + Number(input.venous||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokeYoungAdultExt','0.18 + Number(input.strokeYoung||1)*0.2 + Number(input.pfo||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokePregnancyExt','0.18 + Number(input.strokePreg||1)*0.2 + Number(input.gestAge||1)*0.04 + Number(input.outcome||1)*0.2'),('StrokePostOpExt','0.18 + Number(input.strokePostOp||1)*0.2 + Number(input.surgicalType||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokeRehabAdultExt','0.18 + Number(input.strokeRehabAdult||1)*0.2 + Number(input.fuglMeyer||1)*0.04 + Number(input.outcome||1)*0.2'),('StrokeSecondaryPrevExt','0.18 + Number(input.secondaryPrev||1)*0.2 + Number(input.etiology||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext180':[('PediatricStrokeExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStroke||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeArterialExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeArt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeSinusExt','0.18 + Number(input.age||1)*0.04 + Number(input.pStrokeSinus||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokePerinatalExt','0.18 + Number(input.age||0)*0.04 + Number(input.pStrokePeri||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeSickleExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeSickle||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeMoyaExt','0.18 + Number(input.age||8)*0.04 + Number(input.pStrokeMoya||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeCADExt','0.18 + Number(input.age||8)*0.04 + Number(input.pStrokeCAD||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeRehabExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeRehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeFollowExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeFollow||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTIAext','0.18 + Number(input.age||8)*0.04 + Number(input.pTIA||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext180':[('PediatricStrokeSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricArtSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pArtSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSinusSxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pSinusSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPeriSxExt','0.18 + Number(input.age||0)*0.04 + Number(input.pPeriSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSickleSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSickleSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMoyaSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pMoyaSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCADSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pCADSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeRehabTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeRehabTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeFollowTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeFollowTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTIATxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTIATx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.20.20.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.20.20.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.20.20.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.20.20.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-HT v3.20.20.0 done')