import os
MODULES=['pcc_rehabilitation_ext102','pcc_sports_medicine_ext102','pcc_performance_ext102']
FUNCS={
'pcc_rehabilitation_ext102':[('RehabGeneralExt','0.18 + Number(input.rhGen||1)*0.2 + Number(input.rhGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('RehabPTExt','0.18 + Number(input.rhPT||1)*0.2 + Number(input.rhPTSessions||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabOTExt','0.18 + Number(input.rhOT||1)*0.2 + Number(input.rhOTSessions||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabSTExt','0.18 + Number(input.rhST||1)*0.2 + Number(input.rhSTSessions||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabCardiacExt','0.18 + Number(input.rhCard||1)*0.2 + Number(input.rhCardMETS||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabPulmonaryExt','0.18 + Number(input.rhPulm||1)*0.2 + Number(input.rhPulmScore||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabNeuroExt','0.18 + Number(input.rhNeuro||1)*0.2 + Number(input.rhNeuroScore||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabOrthoExt','0.18 + Number(input.rhOrtho||1)*0.2 + Number(input.rhOrthoType||1)*0.2 + Number(input.outcome||1)*0.2'),('RehabProsthExt','0.18 + Number(input.rhPros||1)*0.2 + Number(input.rhProsType||1)*0.2 + Number(input.outcome||1)*0.2'),('RehabDischargeExt','0.18 + Number(input.rhDisch||1)*0.2 + Number(input.rhDischScore||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_sports_medicine_ext102':[('SportGenExt','0.18 + Number(input.smGen||1)*0.2 + Number(input.smGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('SportInjuryExt','0.18 + Number(input.smInj||1)*0.2 + Number(input.smInjType||1)*0.2 + Number(input.outcome||1)*0.2'),('SportConcussionExt','0.18 + Number(input.smConc||1)*0.2 + Number(input.smConcScore||1)*0.04 + Number(input.outcome||1)*0.2'),('SportCardioExt','0.18 + Number(input.smCard||1)*0.2 + Number(input.smCardScore||1)*0.04 + Number(input.outcome||1)*0.2'),('SportNutritionExt','0.18 + Number(input.smNut||1)*0.2 + Number(input.smNutType||1)*0.2 + Number(input.outcome||1)*0.2'),('SportHydrationExt','0.18 + Number(input.smHyd||1)*0.2 + Number(input.smHydL||1)*0.04 + Number(input.outcome||1)*0.2'),('SportDopingExt','0.18 + Number(input.smDop||1)*0.2 + Number(input.smDopType||1)*0.2 + Number(input.outcome||1)*0.2'),('SportOveruseExt','0.18 + Number(input.smOver||1)*0.2 + Number(input.smOverType||1)*0.2 + Number(input.outcome||1)*0.2'),('SportFemaleExt','0.18 + Number(input.smFem||1)*0.2 + Number(input.smFemType||1)*0.2 + Number(input.outcome||1)*0.2'),('SportReturnExt','0.18 + Number(input.smRet||1)*0.2 + Number(input.smRetScore||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_performance_ext102':[('PerfAeroExt','0.18 + Number(input.pfAero||1)*0.2 + Number(input.pfAeroVO2||1)*0.04 + Number(input.outcome||1)*0.2'),('PerfStrengthExt','0.18 + Number(input.pfStr||1)*0.2 + Number(input.pfStr1RM||1)*0.04 + Number(input.outcome||1)*0.2'),('PerfEnduranceExt','0.18 + Number(input.pfEnd||1)*0.2 + Number(input.pfEndMin||1)*0.04 + Number(input.outcome||1)*0.2'),('PerfFlexExt','0.18 + Number(input.pfFlex||1)*0.2 + Number(input.pfFlexScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PerfAgilityExt','0.18 + Number(input.pfAg||1)*0.2 + Number(input.pfAgScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PerfBalanceExt','0.18 + Number(input.pfBal||1)*0.2 + Number(input.pfBalScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PerfPowerExt','0.18 + Number(input.pfPow||1)*0.2 + Number(input.pfPowScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PerfSpeedExt','0.18 + Number(input.pfSpd||1)*0.2 + Number(input.pfSpdSec||1)*0.04 + Number(input.outcome||1)*0.2'),('PerfReactionExt','0.18 + Number(input.pfReact||1)*0.2 + Number(input.pfReactMs||1)*0.04 + Number(input.outcome||1)*0.2'),('PerfRecoveryExt','0.18 + Number(input.pfRec||1)*0.2 + Number(input.pfRecHRV||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.48.48.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.48.48.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.48.48.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.48.48.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MV v3.48.48.0 done')