import os
MODULES=['pcc_addiction_ext102','pcc_sleep_ext102','pcc_pain_ext102']
FUNCS={
'pcc_addiction_ext102':[('AddGenExt','0.18 + Number(input.adGen||1)*0.2 + Number(input.adGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('AddAlcoholExt','0.18 + Number(input.adAlc||1)*0.2 + Number(input.adAlcScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AddDrugExt','0.18 + Number(input.adDrug||1)*0.2 + Number(input.adDrugType||1)*0.2 + Number(input.outcome||1)*0.2'),('AddNicotineExt','0.18 + Number(input.adNic||1)*0.2 + Number(input.adNicScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AddGamblingExt','0.18 + Number(input.adGam||1)*0.2 + Number(input.adGamScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AddDetoxExt','0.18 + Number(input.adDetox||1)*0.2 + Number(input.adDetoxType||1)*0.2 + Number(input.outcome||1)*0.2'),('AddRehabExt','0.18 + Number(input.adReh||1)*0.2 + Number(input.adRehDays||1)*0.04 + Number(input.outcome||1)*0.2'),('AddRelapseExt','0.18 + Number(input.adRel||1)*0.2 + Number(input.adRelRate||1)*0.04 + Number(input.outcome||1)*0.2'),('AddMAText','0.18 + Number(input.adMAT||1)*0.2 + Number(input.adMATType||1)*0.2 + Number(input.outcome||1)*0.2'),('AddFamilyExt','0.18 + Number(input.adFam||1)*0.2 + Number(input.adFamScore||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_sleep_ext102':[('SleepGenExt','0.18 + Number(input.slGen||1)*0.2 + Number(input.slGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('SleepInsomniaExt','0.18 + Number(input.slIns||1)*0.2 + Number(input.slInsScore||1)*0.04 + Number(input.outcome||1)*0.2'),('SleepApneaExt','0.18 + Number(input.slApn||1)*0.2 + Number(input.slApnAHI||1)*0.04 + Number(input.outcome||1)*0.2'),('SleepRestlessExt','0.18 + Number(input.slRLS||1)*0.2 + Number(input.slRLSscore||1)*0.04 + Number(input.outcome||1)*0.2'),('SleepNarcolepsyExt','0.18 + Number(input.slNar||1)*0.2 + Number(input.slNarType||1)*0.2 + Number(input.outcome||1)*0.2'),('SleepParasomniaExt','0.18 + Number(input.slPar||1)*0.2 + Number(input.slParType||1)*0.2 + Number(input.outcome||1)*0.2'),('SleepCircadianExt','0.18 + Number(input.slCir||1)*0.2 + Number(input.slCirType||1)*0.2 + Number(input.outcome||1)*0.2'),('SleepHygieneExt','0.18 + Number(input.slHyg||1)*0.2 + Number(input.slHygScore||1)*0.04 + Number(input.outcome||1)*0.2'),('SleepCPAPext','0.18 + Number(input.slCPAP||1)*0.2 + Number(input.slCPAPhr||1)*0.04 + Number(input.outcome||1)*0.2'),('SleepStudyExt','0.18 + Number(input.slStudy||1)*0.2 + Number(input.slStudyType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pain_ext102':[('PainAcuteExt','0.18 + Number(input.pnAcu||1)*0.2 + Number(input.pnAcuScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PainChronicExt','0.18 + Number(input.pnChr||1)*0.2 + Number(input.pnChrType||1)*0.2 + Number(input.outcome||1)*0.2'),('PainNeuropathicExt','0.18 + Number(input.pnNeur||1)*0.2 + Number(input.pnNeurScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PainNociceptiveExt','0.18 + Number(input.pnNoc||1)*0.2 + Number(input.pnNocType||1)*0.2 + Number(input.outcome||1)*0.2'),('PainCancerExt','0.18 + Number(input.pnCan||1)*0.2 + Number(input.pnCanScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PainPostopExt','0.18 + Number(input.pnPO||1)*0.2 + Number(input.pnPODay||1)*0.04 + Number(input.outcome||1)*0.2'),('PainMusculoskeletalExt','0.18 + Number(input.pnMSK||1)*0.2 + Number(input.pnMSKtype||1)*0.2 + Number(input.outcome||1)*0.2'),('PainMigraineExt','0.18 + Number(input.pnMig||1)*0.2 + Number(input.pnMigScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PainOpioidExt','0.18 + Number(input.pnOp||1)*0.2 + Number(input.pnOpMME||1)*0.04 + Number(input.outcome||1)*0.2'),('PainIntervExt','0.18 + Number(input.pnInt||1)*0.2 + Number(input.pnIntType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.51.51.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.51.51.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.51.51.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.51.51.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MY v3.51.51.0 done')