import os
MODULES=['pcc_neuro_ext169','pcc_pediatric_neuro_ext158','pcc_pediatric_surg_ext158']
FUNCS={
'pcc_neuro_ext169':[('HearingLossSuddenExt','0.18 + Number(input.ssnhl||1)*0.2 + Number(input.acoustic||1)*0.2 + Number(input.outcome||1)*0.2'),('PresbycusisExt','0.18 + Number(input.presby||1)*0.2 + Number(input.highFreq||1)*0.2 + Number(input.outcome||1)*0.2'),('OtotoxicDrugExt','0.18 + Number(input.ototoxic||1)*0.2 + Number(input.aminoglyc||1)*0.2 + Number(input.outcome||1)*0.2'),('NoiseInducedExt','0.18 + Number(input.nihl||1)*0.2 + Number(input.noiseExp||1)*0.2 + Number(input.outcome||1)*0.2'),('TinnitusExt','0.18 + Number(input.tinnitus||1)*0.2 + Number(input.ringing||1)*0.2 + Number(input.outcome||1)*0.2'),('OtitisMediaChronicExt','0.18 + Number(input.com||1)*0.2 + Number(input.tympanic||1)*0.2 + Number(input.outcome||1)*0.2'),('OtosclerosisExt','0.18 + Number(input.otoscler||1)*0.2 + Number(input.conductive||1)*0.2 + Number(input.outcome||1)*0.2'),('CholesteatomaExt','0.18 + Number(input.cholest||1)*0.2 + Number(input.boneErosion||1)*0.2 + Number(input.outcome||1)*0.2'),('AcousticNeuroma2Ext','0.18 + Number(input.an2||1)*0.2 + Number(input.unilateralHL||1)*0.2 + Number(input.outcome||1)*0.2'),('AuditoryNeuropathyExt','0.18 + Number(input.anSd||1)*0.2 + Number(input.oaePresent||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext158':[('PediatricOHLExt','0.18 + Number(input.age||3)*0.04 + Number(input.pOHL||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongenitalHLext','0.18 + Number(input.age||0)*0.04 + Number(input.pCongenitalHL||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOMEext','0.18 + Number(input.age||3)*0.04 + Number(input.ome||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRecurrentOtitisExt','0.18 + Number(input.age||3)*0.04 + Number(input.recurrentOtitis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCholesteatomaExt','0.18 + Number(input.age||8)*0.04 + Number(input.pCholest||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOtosclerExt','0.18 + Number(input.age||10)*0.04 + Number(input.pOtoscler||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAuditoryNeuroExt','0.18 + Number(input.age||1)*0.04 + Number(input.pAudNeuro||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCMVhlExt','0.18 + Number(input.age||1)*0.04 + Number(input.cmvHL||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOtoxicityExt','0.18 + Number(input.age||5)*0.04 + Number(input.pOtox||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNoiseHLext','0.18 + Number(input.age||10)*0.04 + Number(input.pNoiseHL||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext158':[('PediatricOHLHearingAidExt','0.18 + Number(input.age||3)*0.04 + Number(input.ohlAid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongHLcochlearExt','0.18 + Number(input.age||0)*0.04 + Number(input.cochlear||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOMETubesExt','0.18 + Number(input.age||3)*0.04 + Number(input.tubes||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRecurrentAbxExt','0.18 + Number(input.age||3)*0.04 + Number(input.recurrentAbx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCholesteatomaSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pCholestSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOtosclerSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.pOtosclerSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAudNeuroCIExt','0.18 + Number(input.age||1)*0.04 + Number(input.audNeuroCI||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCMVvalganExt','0.18 + Number(input.age||1)*0.04 + Number(input.valgan||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOtoxMonitorExt','0.18 + Number(input.age||5)*0.04 + Number(input.otoxMonitor||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNoiseProtectExt','0.18 + Number(input.age||10)*0.04 + Number(input.noiseProtect||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.12.10.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.12.10.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.12.10.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.12.10.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LJ v3.12.10.0 done')