import os
MODULES=['pcc_neuro_ext116','pcc_pediatric_neuro_ext105','pcc_pediatric_surg_ext105']
FUNCS={
'pcc_neuro_ext116':[('SpinalCordInjuryExt','0.18 + Number(input.ais||3)*0.1 + Number(input.level||6)*0.04 + Number(input.outcome||1)*0.2'),('TetraplegiaExt','0.18 + Number(input.c1||1)*0.1 + Number(input.dvt||1)*0.2 + Number(input.outcome||1)*0.2'),('ParaplegiaExt','0.18 + Number(input.t1||1)*0.1 + Number(input.autonomic||1)*0.2 + Number(input.outcome||1)*0.2'),('BrownSequardExt','0.18 + Number(input.hemisection||1)*0.2 + Number(input.ipsilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('AnteriorCordExt','0.18 + Number(input.anterior||1)*0.2 + Number(input.motor||1)*0.2 + Number(input.outcome||1)*0.2'),('CentralCordExt','0.18 + Number(input.central||1)*0.2 + Number(input.upper||1)*0.2 + Number(input.outcome||1)*0.2'),('CaudaEquinaExt','0.18 + Number(input.lumbar||1)*0.2 + Number(input.sphincter||1)*0.2 + Number(input.outcome||1)*0.2'),('ConusMedullarisExt','0.18 + Number(input.t12||1)*0.2 + Number(input.sphincter||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalShockExt','0.18 + Number(input.areflexia||1)*0.2 + Number(input.days||3)*0.1 + Number(input.outcome||1)*0.2'),('AutonomicDysreflexiaExt','0.18 + Number(input.bp||180)*0.005 + Number(input.trigger||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext105':[('PediatricSCISext','0.18 + Number(input.age||5)*0.04 + Number(input.ais||3)*0.1 + Number(input.outcome||1)*0.2'),('PediatricTetraExt','0.18 + Number(input.age||5)*0.04 + Number(input.c1||1)*0.1 + Number(input.outcome||1)*0.2'),('PediatricParaExt','0.18 + Number(input.age||5)*0.04 + Number(input.t1||1)*0.1 + Number(input.outcome||1)*0.2'),('PediatricBSext','0.18 + Number(input.age||8)*0.04 + Number(input.hemisection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAnteriorExt','0.18 + Number(input.age||8)*0.04 + Number(input.anterior||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCentralExt','0.18 + Number(input.age||8)*0.04 + Number(input.central||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCaudaEquinaExt','0.18 + Number(input.age||8)*0.04 + Number(input.lumbar||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricConusExt','0.18 + Number(input.age||8)*0.04 + Number(input.t12||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalShockExt','0.18 + Number(input.age||5)*0.04 + Number(input.areflexia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricADRext','0.18 + Number(input.age||8)*0.04 + Number(input.bp||180)*0.005 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext105':[('PediatricSCISxExt','0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTetraSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.ventilator||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricParaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.rehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBSSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAnteriorSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.decompression||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCentralSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCaudaEquinaSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.decompression||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricConusSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalShockSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.supportive||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricADRsxExt','0.18 + Number(input.age||8)*0.04 + Number(input.sympathectomy||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.215.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.215.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.215.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.215.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-JI v3.215.0 done')
