import os
MODULES=['pcc_neuro_ext114','pcc_pediatric_neuro_ext103','pcc_pediatric_surg_ext103']
FUNCS={
'pcc_neuro_ext114':[('ALSext','0.18 + Number(input.siteOfOnset||1)*0.2 + Number(input.fvc||60)*0.005 + Number(input.outcome||1)*0.2'),('ALSbulbarExt','0.18 + Number(input.dysarthria||1)*0.2 + Number(input.dysphagia||1)*0.2 + Number(input.outcome||1)*0.2'),('ALSlimbExt','0.18 + Number(input.limb||1)*0.2 + Number(input.fasciculations||1)*0.2 + Number(input.outcome||1)*0.2'),('ALSrespiratoryExt','0.18 + Number(input.fvc||60)*0.005 + Number(input.niv||1)*0.2 + Number(input.outcome||1)*0.2'),('ProgressiveBulbarPalsyExt','0.18 + Number(input.dysarthria||1)*0.2 + Number(input.fascic||1)*0.2 + Number(input.outcome||1)*0.2'),('PrimaryLateralSclerosisExt','0.18 + Number(input.spasticity||1)*0.2 + Number(input.hyperreflexia||1)*0.2 + Number(input.outcome||1)*0.2'),('ProgressiveMuscularAtrophyExt','0.18 + Number(input.weakness||1)*0.2 + Number(input.atrophy||1)*0.2 + Number(input.outcome||1)*0.2'),('FlailArmExt','0.18 + Number(input.armWeakness||1)*0.2 + Number(input.duration||12)*0.04 + Number(input.outcome||1)*0.2'),('FlailLegExt','0.18 + Number(input.legWeakness||1)*0.2 + Number(input.duration||12)*0.04 + Number(input.outcome||1)*0.2'),('KennedyDiseaseExt','0.18 + Number(input.areflexia||1)*0.2 + Number(input.fasciculations||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext103':[('PediatricSMARtext','0.18 + Number(input.age||3)*0.04 + Number(input.smaType||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMA1Ext','0.18 + Number(input.age||0.5)*0.05 + Number(input.weakness||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMA2Ext','0.18 + Number(input.age||2)*0.04 + Number(input.sit||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMA3Ext','0.18 + Number(input.age||5)*0.04 + Number(input.walk||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDuchenneExt','0.18 + Number(input.age||5)*0.04 + Number(input.gower||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBeckerExt','0.18 + Number(input.age||8)*0.04 + Number(input.dystrophin||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMyotonicExt','0.18 + Number(input.age||10)*0.04 + Number(input.myotonia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPompeExt','0.18 + Number(input.age||1)*0.04 + Number(input.gaa||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDermatomyositisExt','0.18 + Number(input.age||5)*0.04 + Number(input.rash||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongenitalMyopathyExt','0.18 + Number(input.age||2)*0.04 + Number(input.hypotonia||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext103':[('PediatricSMANusinersenExt','0.18 + Number(input.age||3)*0.04 + Number(input.nusinersen||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMA1SxExt','0.18 + Number(input.age||0.5)*0.05 + Number(input.geneTherapy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMA2SxExt','0.18 + Number(input.age||2)*0.04 + Number(input.nusinersen||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMA3SxExt','0.18 + Number(input.age||5)*0.04 + Number(input.nusinersen||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDuchenneSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBeckerSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMyotonicSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.cardiac||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPompeSxExt','0.18 + Number(input.age||1)*0.04 + Number(input.ert||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDermatomyositisImmunoExt','0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongenitalMyoSxExt','0.18 + Number(input.age||2)*0.04 + Number(input.supportive||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.213.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.213.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.213.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.213.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-JG v3.213.0 done')
