import os
MODULES=['pcc_military_ext102','pcc_disaster_ext102','pcc_emergency_prep_ext102']
FUNCS={
'pcc_military_ext102':[('MilCombatExt','0.18 + Number(input.mcCombat||1)*0.2 + Number(input.mcInjury||1)*0.2 + Number(input.outcome||1)*0.2'),('MilTraumaExt','0.18 + Number(input.mcTrauma||1)*0.2 + Number(input.mcTraumaSev||1)*0.04 + Number(input.outcome||1)*0.2'),('MilBlastExt','0.18 + Number(input.mcBlast||1)*0.2 + Number(input.mcBlastDist||1)*0.04 + Number(input.outcome||1)*0.2'),('MilBurnExt','0.18 + Number(input.mcBurn||1)*0.2 + Number(input.mcBurnTBSA||1)*0.04 + Number(input.outcome||1)*0.2'),('MilRadiationExt','0.18 + Number(input.mcRad||1)*0.2 + Number(input.mcRadDose||1)*0.04 + Number(input.outcome||1)*0.2'),('MilChemExt','0.18 + Number(input.mcChem||1)*0.2 + Number(input.mcChemAgent||1)*0.2 + Number(input.outcome||1)*0.2'),('MilBioExt','0.18 + Number(input.mcBio||1)*0.2 + Number(input.mcBioAgent||1)*0.2 + Number(input.outcome||1)*0.2'),('MilPTSDext','0.18 + Number(input.mcPTSD||1)*0.2 + Number(input.mcPTSDScore||1)*0.04 + Number(input.outcome||1)*0.2'),('MilTBIext','0.18 + Number(input.mcTBI||1)*0.2 + Number(input.mcTBISev||1)*0.04 + Number(input.outcome||1)*0.2'),('MilEvacExt','0.18 + Number(input.mcEvac||1)*0.2 + Number(input.mcEvacTier||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_disaster_ext102':[('DisasterTriageExt','0.18 + Number(input.dzTriage||1)*0.2 + Number(input.dzTriageCount||1)*0.04 + Number(input.outcome||1)*0.2'),('DisasterMassCasExt','0.18 + Number(input.dzMassCas||1)*0.2 + Number(input.dzCasCount||1)*0.04 + Number(input.outcome||1)*0.2'),('DisasterEarthquakeExt','0.18 + Number(input.dzEQ||1)*0.2 + Number(input.dzRichter||1)*0.04 + Number(input.outcome||1)*0.2'),('DisasterFloodExt','0.18 + Number(input.dzFlood||1)*0.2 + Number(input.dzFloodDepth||1)*0.04 + Number(input.outcome||1)*0.2'),('DisasterFireExt','0.18 + Number(input.dzFire||1)*0.2 + Number(input.dzFireSize||1)*0.04 + Number(input.outcome||1)*0.2'),('DisasterChemicalExt','0.18 + Number(input.dzChem||1)*0.2 + Number(input.dzChemType||1)*0.2 + Number(input.outcome||1)*0.2'),('DisasterBiologicalExt','0.18 + Number(input.dzBio||1)*0.2 + Number(input.dzBioType||1)*0.2 + Number(input.outcome||1)*0.2'),('DisasterRadiationExt','0.18 + Number(input.dzRad||1)*0.2 + Number(input.dzRadDose||1)*0.04 + Number(input.outcome||1)*0.2'),('DisasterPandemicExt','0.18 + Number(input.dzPandemic||1)*0.2 + Number(input.dzPandR0||1)*0.04 + Number(input.outcome||1)*0.2'),('DisasterRecoveryExt','0.18 + Number(input.dzRecov||1)*0.2 + Number(input.dzRecovPhase||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_emergency_prep_ext102':[('EPPandemicPrepExt','0.18 + Number(input.epPandemic||1)*0.2 + Number(input.epPandemicPhase||1)*0.04 + Number(input.outcome||1)*0.2'),('EPBioterrorExt','0.18 + Number(input.epBio||1)*0.2 + Number(input.epBioThreat||1)*0.2 + Number(input.outcome||1)*0.2'),('EPDrillExt','0.18 + Number(input.epDrill||1)*0.2 + Number(input.epDrillType||1)*0.2 + Number(input.outcome||1)*0.2'),('EPResourceExt','0.18 + Number(input.epRes||1)*0.2 + Number(input.epResStock||1)*0.04 + Number(input.outcome||1)*0.2'),('EPCommunicationExt','0.18 + Number(input.epComm||1)*0.2 + Number(input.epCommSys||1)*0.2 + Number(input.outcome||1)*0.2'),('EPTrainingExt','0.18 + Number(input.epTrain||1)*0.2 + Number(input.epTrainType||1)*0.2 + Number(input.outcome||1)*0.2'),('EPRiskCommExt','0.18 + Number(input.epRisk||1)*0.2 + Number(input.epRiskType||1)*0.2 + Number(input.outcome||1)*0.2'),('EPLogisticsExt','0.18 + Number(input.epLog||1)*0.2 + Number(input.epLogType||1)*0.2 + Number(input.outcome||1)*0.2'),('EPLegalExt','0.18 + Number(input.epLegal||1)*0.2 + Number(input.epLegalType||1)*0.2 + Number(input.outcome||1)*0.2'),('EPEvalExt','0.18 + Number(input.epEval||1)*0.2 + Number(input.epEvalAfter||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.44.44.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.44.44.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.44.44.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.44.44.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MR v3.44.44.0 done')