import os
MODULES=['pcc_neuro_ext121','pcc_pediatric_neuro_ext110','pcc_pediatric_surg_ext110']
FUNCS={
'pcc_neuro_ext121':[('GlioblastomaExt','0.15 + Number(input.idh||1)*0.2 + Number(input.mgmt||1)*0.2 + Number(input.outcome||1)*0.2'),('AnaplasticAstrocytomaExt','0.15 + Number(input.grade||3)*0.1 + Number(input.idh||1)*0.2 + Number(input.outcome||1)*0.2'),('OligodendrogliomaExt','0.15 + Number(input.1p19q||1)*0.2 + Number(input.grade||2)*0.1 + Number(input.outcome||1)*0.2'),('GliomatosisCerebriExt','0.15 + Number(input.diffuse||1)*0.2 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('DIPGext','0.15 + Number(input.pediatric||1)*0.1 + Number(input.h3k27m||1)*0.2 + Number(input.outcome||1)*0.2'),('PilocyticAstrocytomaExt','0.15 + Number(input.braf||1)*0.2 + Number(input.ki67||1)*0.2 + Number(input.outcome||1)*0.2'),('SubependymalGiantExt','0.15 + Number(input.tsc||1)*0.2 + Number(input.seizure||1)*0.2 + Number(input.outcome||1)*0.2'),('PleomorphicXanthoExt','0.15 + Number(input.braf||1)*0.2 + Number(input.grade||2)*0.1 + Number(input.outcome||1)*0.2'),('PleomorphicAstroExt','0.15 + Number(input.grade||3)*0.1 + Number(input.mitotic||1)*0.2 + Number(input.outcome||1)*0.2'),('GliosarcomaExt','0.15 + Number(input.gbm||1)*0.2 + Number(input.sarcomatous||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext110':[('PediatricGBMext','0.15 + Number(input.age||8)*0.04 + Number(input.gbm||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAAext','0.15 + Number(input.age||5)*0.04 + Number(input.grade||3)*0.1 + Number(input.outcome||1)*0.2'),('PediatricOligoExt','0.15 + Number(input.age||10)*0.04 + Number(input.1p19q||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGliomatosisExt','0.15 + Number(input.age||5)*0.04 + Number(input.diffuse||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDIPGext','0.15 + Number(input.age||5)*0.04 + Number(input.h3k27m||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPilocyticExt','0.15 + Number(input.age||5)*0.04 + Number(input.braf||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSEGAext','0.15 + Number(input.age||5)*0.04 + Number(input.tsc||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPXAext','0.15 + Number(input.age||5)*0.04 + Number(input.braf||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPMAext','0.15 + Number(input.age||5)*0.04 + Number(input.grade||3)*0.1 + Number(input.outcome||1)*0.2'),('PediatricGliosarcomaExt','0.15 + Number(input.age||8)*0.04 + Number(input.gbm||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext110':[('PediatricGBMSxExt','0.15 + Number(input.age||8)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAASxExt','0.15 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOligoSxExt','0.15 + Number(input.age||10)*0.04 + Number(input.chemo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGliomatosisSxExt','0.15 + Number(input.age||5)*0.04 + Number(input.biopsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDIPGsxExt','0.15 + Number(input.age||5)*0.04 + Number(input.radiation||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPilocyticSxExt','0.15 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSEGASxExt','0.15 + Number(input.age||5)*0.04 + Number(input.mtor||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPXASxExt','0.15 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPMASxExt','0.15 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGliosarcomaSxExt','0.15 + Number(input.age||8)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.220.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.220.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.220.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.220.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-JN v3.220.0 done')
