import os
MODULES=['pcc_neuro_ext98','pcc_pediatric_neuro_ext87','pcc_pediatric_surg_ext87']
FUNCS={
'pcc_neuro_ext98':[('CognitionClinicExt','0.15 + Number(input.moca||26)*0.02 + Number(input.memory||80)*0.005 + Number(input.executive||75)*0.005'),('DementiaDiagnosticExt','0.2 + Number(input.mmse||24)*0.02 + Number(input.biomarker||1)*0.2 + Number(input.fdg||1)*0.15'),('MildCognitiveImpairmentExt','0.18 + Number(input.fwdRecall||5)*0.04 + Number(input.brain||1)*0.2 + Number(input.adl||85)*0.005'),('AlzheimerTreatmentExt','0.15 + Number(input.ache||1)*0.15 + Number(input.memantine||1)*0.15 + Number(input.lecanemab||1)*0.2'),('FrontotemporalDementiaExt','0.15 + Number(input.behavior||3)*0.05 + Number(input.language||3)*0.05 + Number(input.inheritance||1)*0.2'),('LewyBodyDementiaExt','0.18 + Number(input.fluctuations||1)*0.2 + Number(input.visualHall||1)*0.2 + Number(input.parkinsonism||1)*0.15'),('VascularDementiaExt','0.15 + Number(input.fazekas||2)*0.1 + Number(input.vascular||1)*0.2 + Number(input.riskFactors||3)*0.05'),('CJDiseaseEvalExt','0.2 + Number(input.mri||1)*0.2 + Number(input.rtQuIC||1)*0.2 + Number(input.rapidDementia||1)*0.15'),('NormalPressureHydroExt','0.18 + Number(input.tapTest||1)*0.2 + Number(input.walkingSpeed||0.8)*0.5 + Number(input.brainVol||1)*0.15'),('CognitiveRehabMgmExt','0.15 + Number(input.intensity||3)*0.1 + Number(input.weeks||12)*0.04 + Number(input.gain||10)*0.04')],
'pcc_pediatric_neuro_ext87':[('PediatricCognitionExt','0.15 + Number(input.iq||100)*0.005 + Number(input.memory||85)*0.005 + Number(input.executive||80)*0.005'),('PediatricNeurodegenExt','0.15 + Number(input.loss||3)*0.05 + Number(input.genetic||1)*0.2 + Number(input.age||5)*0.04'),('PediatricNCLBattenExt','0.18 + Number(input.visionLoss||1)*0.2 + Number(input.seizures||1)*0.15 + Number(input.tpp1||1)*0.2'),('PediatricLeukodystrophyExt','0.15 + Number(input.mri||1)*0.2 + Number(input.biochem||1)*0.2 + Number(input.gene||1)*0.15'),('PediatricMitochondrialExt','0.18 + Number(input.melas||1)*0.2 + Number(input.lacticAcid||2)*0.1 + Number(input.mitochondrialDNA||1)*0.2'),('PediatricPKUExt','0.15 + Number(input.pheLevels||10)*0.02 + Number(input.diet||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricWilsonExt','0.15 + Number(input.copper||100)*0.002 + Number(input.kayserFleischer||1)*0.2 + Number(input.dpen||1)*0.2'),('PediatricHuntingtonsExt','0.18 + Number(input.cag||45)*0.02 + Number(input.familyHist||1)*0.15 + Number(input.motorOnset||1)*0.2'),('PediatricNeurocutaneousExt','0.15 + Number(input.tuberous||1)*0.2 + Number(input.ashLeaf||1)*0.2 + Number(input.mriScreening||1)*0.15'),('PediatricNeurofibromatosisExt','0.15 + Number(input.opticGlioma||1)*0.2 + Number(input.plexiform||1)*0.2 + Number(input.screening||1)*0.15')],
'pcc_pediatric_surg_ext87':[('PediatricDBSNeurodegenExt','0.15 + Number(input.dystonia||1)*0.2 + Number(input.target||1)*0.15 + Number(input.outcome||1)*0.2'),('PediatricIntrathecalExt','0.15 + Number(input.baclofen||1)*0.2 + Number(input.pump||1)*0.15 + Number(input.outcome||1)*0.2'),('PediatricPallidotomyExt','0.15 + Number(input.age||7)*0.04 + Number(input.target||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricThalamotomyExt','0.15 + Number(input.age||7)*0.04 + Number(input.tremor||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCordotomyExt','0.15 + Number(input.pain||1)*0.2 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRhizotomySelectiveExt','0.15 + Number(input.age||5)*0.04 + Number(input.spasticity||3)*0.1 + Number(input.outcome||1)*0.2'),('PediatricITBTherapyExt','0.18 + Number(input.dose||300)*0.0005 + Number(input.pumpRefills||3)*0.05 + Number(input.outcome||1)*0.2'),('PediatricTrigeminalRhizExt','0.15 + Number(input.age||8)*0.04 + Number(input.trigeminal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeuroStimForMovementExt','0.15 + Number(input.target||1)*0.2 + Number(input.amplitude||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGeneTherapyDeliveryExt','0.18 + Number(input.vector||1)*0.2 + Number(input.intrathecal||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\n// {m} engine (deterministic)\nmodule.exports.version=\'v3.197.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.197.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}};}};\n'
    eng+=f'\n// TS: v3.197.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'// filepath: pcc/{m}/{m}_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;else console.error(\'FAIL\',fn,r);}}console.log(\'{m} unit:\',pass,\'passed\');if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'// filepath: pcc/{m}/{m}_integration_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{value:1}},{{value:2}},{{value:3}},{{value:4}},{{value:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass,\'passed\');if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'// filepath: pcc/{m}/{m}_routes.js\nconst express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();\nrouter.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.197.0\',functions:Object.keys(F)}}));\nrouter.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});\nrouter.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});\nmodule.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- pcc/{m}/{m}_up.sql\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\')\nBEGIN\nCREATE TABLE [dbo].[{m}] (\n  [id] INT IDENTITY(1,1) PRIMARY KEY,\n  [tenant_id] NVARCHAR(64) NOT NULL,\n  [version] NVARCHAR(16) NOT NULL,\n  [module] NVARCHAR(64) NOT NULL,\n  [function] NVARCHAR(128) NOT NULL,\n  [input] NVARCHAR(MAX) NULL,\n  [score] DECIMAL(6,2) NULL,\n  [ts] DATETIME2 DEFAULT SYSUTCDATETIME()\n);\nEND\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files written')
print('P3-IQ v3.197.0: 16 files written')
