import os
MODULES=['pcc_neuro_ext185','pcc_pediatric_neuro_ext174','pcc_pediatric_surg_ext174']
FUNCS={
'pcc_neuro_ext185':[('OphthalmoplegiaChronicExt','0.18 + Number(input.chronicOph||1)*0.2 + Number(input.eyeMuscle||1)*0.2 + Number(input.outcome||1)*0.2'),('INOExt','0.18 + Number(input.ino||1)*0.2 + Number(input.medialRectus||1)*0.2 + Number(input.outcome||1)*0.2'),('WEBINOExt','0.18 + Number(input.webino||1)*0.2 + Number(input.bilateralIno||1)*0.2 + Number(input.outcome||1)*0.2'),('OpsoclonusExt','0.18 + Number(input.opsoclonus2||1)*0.2 + Number(input.ocularShudder||1)*0.2 + Number(input.outcome||1)*0.2'),('NystagmusCongenitalExt','0.18 + Number(input.nystagmusCong||1)*0.2 + Number(input.sensoryDef||1)*0.2 + Number(input.outcome||1)*0.2'),('NystagmusAcquiredExt','0.18 + Number(input.acquiredNyst||1)*0.2 + Number(input.acuteVert||1)*0.2 + Number(input.outcome||1)*0.2'),('SaccadicPursuitExt','0.18 + Number(input.saccadic||1)*0.2 + Number(input.pursuit||1)*0.2 + Number(input.outcome||1)*0.2'),('SupranuclearPalsyExt','0.18 + Number(input.snPalsy||1)*0.2 + Number(input.verticalGaze||1)*0.2 + Number(input.outcome||1)*0.2'),('ThirdNervePalsyExt','0.18 + Number(input.iiiNerve||1)*0.2 + Number(input.ptosis||1)*0.2 + Number(input.outcome||1)*0.2'),('SixthNervePalsyExt','0.18 + Number(input.viNerve||1)*0.2 + Number(input.lateralGaze||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext174':[('PediatricINOExt','0.18 + Number(input.age||5)*0.04 + Number(input.pINO||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOpsoclonusExt','0.18 + Number(input.age||1)*0.04 + Number(input.pOpsoclonus||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongNystagmusExt','0.18 + Number(input.age||0)*0.04 + Number(input.pCongNyst||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIIIPalsyExt','0.18 + Number(input.age||5)*0.04 + Number(input.pIIIPalsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVIPalsyExt','0.18 + Number(input.age||5)*0.04 + Number(input.pVIPalsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIVPalsyExt','0.18 + Number(input.age||5)*0.04 + Number(input.pIVPalsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOphthalmoplegiaExt','0.18 + Number(input.age||3)*0.04 + Number(input.pOph||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCPEOExt','0.18 + Number(input.age||5)*0.04 + Number(input.pCPEO||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLeberHereditaryExt','0.18 + Number(input.age||1)*0.04 + Number(input.pLHON||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSupranuclearPalsyExt','0.18 + Number(input.age||8)*0.04 + Number(input.pSNP||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext174':[('PediatricINOTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pINOTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOpsoclonusTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pOpsoclonusTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongNystTxExt','0.18 + Number(input.age||0)*0.04 + Number(input.pCongNystTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIIIPalsyTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pIIIPalsyTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVIPalsyTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pVIPalsyTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIVPalsyTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pIVPalsyTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOphthalmoplegiaTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pOphTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCPEOTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pCPEOTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLeberHereditaryTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pLHONTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSupranuclearPalsyTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pSNPTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.14.14.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.14.14.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.14.14.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.14.14.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-HN v3.14.14.0 done')