import os
MODULES=['pcc_card_ext110','pcc_icu_ext99','pcc_em_ext99']
FUNCS={
'pcc_card_ext110':[('CardAdultExt','0.18 + Number(input.cardAdult||1)*0.2 + Number(input.cardStage||1)*0.04 + Number(input.outcome||1)*0.2'),('ArrhythmiaAdultExt','0.18 + Number(input.arrhAdult||1)*0.2 + Number(input.qtInterval||1)*0.04 + Number(input.outcome||1)*0.2'),('CHFAdultExt','0.18 + Number(input.chfAdult||1)*0.2 + Number(input.ef||1)*0.04 + Number(input.outcome||1)*0.2'),('CADAdultExt','0.18 + Number(input.cadAdult||1)*0.2 + Number(input.cadSeverity||1)*0.04 + Number(input.outcome||1)*0.2'),('MIAadultExt','0.18 + Number(input.miAdult||1)*0.2 + Number(input.tropPeak||1)*0.04 + Number(input.outcome||1)*0.2'),('ValveAdultExt','0.18 + Number(input.valveAdult||1)*0.2 + Number(input.valveArea||1)*0.04 + Number(input.outcome||1)*0.2'),('CardiomyopathyAdultExt','0.18 + Number(input.cmpAdult||1)*0.2 + Number(input.cmpType||1)*0.2 + Number(input.outcome||1)*0.2'),('PericardAdultExt','0.18 + Number(input.pericardAdult||1)*0.2 + Number(input.pericardEff||1)*0.2 + Number(input.outcome||1)*0.2'),('EndocardAdultExt','0.18 + Number(input.endocardAdult||1)*0.2 + Number(input.endoType||1)*0.2 + Number(input.outcome||1)*0.2'),('PulmonaryHTNAdultExt','0.18 + Number(input.phaAdult||1)*0.2 + Number(input.pap||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_icu_ext99':[('ICUSepsisExt','0.18 + Number(input.icuSepsis||1)*0.2 + Number(input.sofa||1)*0.04 + Number(input.outcome||1)*0.2'),('ICUARDSext','0.18 + Number(input.icuARDS||1)*0.2 + Number(input.pfRatio||1)*0.04 + Number(input.outcome||1)*0.2'),('ICUDKAext','0.18 + Number(input.icuDKA||1)*0.2 + Number(input.bloodSugar||1)*0.04 + Number(input.outcome||1)*0.2'),('ICUShockExt','0.18 + Number(input.icuShock||1)*0.2 + Number(input.lactate||1)*0.04 + Number(input.outcome||1)*0.2'),('ICURenalFailureExt','0.18 + Number(input.icuAKI||1)*0.2 + Number(input.creatPeak||1)*0.04 + Number(input.outcome||1)*0.2'),('ICULiverFailureExt','0.18 + Number(input.icuALF||1)*0.2 + Number(input.inrPeak||1)*0.04 + Number(input.outcome||1)*0.2'),('ICUCVVIHext','0.18 + Number(input.icuCVVH||1)*0.2 + Number(input.ufRate||1)*0.04 + Number(input.outcome||1)*0.2'),('ICUVentExt','0.18 + Number(input.icuVent||1)*0.2 + Number(input.peep||1)*0.04 + Number(input.outcome||1)*0.2'),('ICUSedationExt','0.18 + Number(input.icuSedation||1)*0.2 + Number(input.rass||1)*0.04 + Number(input.outcome||1)*0.2'),('ICUDeliriumExt','0.18 + Number(input.icuDelirium||1)*0.2 + Number(input.camIcu||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_em_ext99':[('EMChestPainExt','0.18 + Number(input.emCP||1)*0.2 + Number(input.cpScore||1)*0.04 + Number(input.outcome||1)*0.2'),('EMDyspneaExt','0.18 + Number(input.emDyspnea||1)*0.2 + Number(input.oxySat||1)*0.04 + Number(input.outcome||1)*0.2'),('EMAlteredMentalExt','0.18 + Number(input.emAMS||1)*0.2 + Number(input.gcs||1)*0.04 + Number(input.outcome||1)*0.2'),('EMTraumaExt','0.18 + Number(input.emTrauma||1)*0.2 + Number(input.issScore||1)*0.04 + Number(input.outcome||1)*0.2'),('EMPoisonExt','0.18 + Number(input.emPoison||1)*0.2 + Number(input.toxicityLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('EMStrokeAlertExt','0.18 + Number(input.emStrokeAlert||1)*0.2 + Number(input.lastKnown||1)*0.04 + Number(input.outcome||1)*0.2'),('EMSTEMIext','0.18 + Number(input.emSTEMI||1)*0.2 + Number(input.doorBalloon||1)*0.04 + Number(input.outcome||1)*0.2'),('EMAnaphylaxisExt','0.18 + Number(input.emAnaphylax||1)*0.2 + Number(input.epiDose||1)*0.04 + Number(input.outcome||1)*0.2'),('EMBurnExt','0.18 + Number(input.emBurn||1)*0.2 + Number(input.tbsaBurn||1)*0.04 + Number(input.outcome||1)*0.2'),('EMHeatStrokeExt','0.18 + Number(input.emHeat||1)*0.2 + Number(input.coreTemp||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.16.16.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.16.16.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.16.16.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.16.16.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LP v3.16.16.0 done')