import os
MODULES=['pcc_neuro_ext181','pcc_pediatric_neuro_ext170','pcc_pediatric_surg_ext170']
FUNCS={
'pcc_neuro_ext181':[('NeuroAidsExt','0.18 + Number(input.hiv||1)*0.2 + Number(input.cd4||1)*0.04 + Number(input.outcome||1)*0.2'),('NeurosyphilisExt','0.18 + Number(input.syphilis||1)*0.2 + Number(input.vdrl||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuroLymeExt','0.18 + Number(input.lyme||1)*0.2 + Number(input.titer||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuroTBext','0.18 + Number(input.tb||1)*0.2 + Number(input.tuberculoma||1)*0.2 + Number(input.outcome||1)*0.2'),('NeurocysticercosisExt','0.18 + Number(input.ncc||1)*0.2 + Number(input.cysticerci||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuroToxoplasmosisExt','0.18 + Number(input.toxo||1)*0.2 + Number(input.cd4Toxo||1)*0.04 + Number(input.outcome||1)*0.2'),('PMLext','0.18 + Number(input.pml||1)*0.2 + Number(input.jcVirus||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuroWhippleExt','0.18 + Number(input.whipple||1)*0.2 + Number(input.oms||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuroBrucellosisExt','0.18 + Number(input.brucellosis||1)*0.2 + Number(input.standard||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuroCysticercRacExt','0.18 + Number(input.nccRac||1)*0.2 + Number(input.subarach||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext170':[('PediatricNeuroAidsExt','0.18 + Number(input.age||5)*0.04 + Number(input.pNeuroAids||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeuroLymeExt','0.18 + Number(input.age||5)*0.04 + Number(input.pNeuroLyme||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongenitalCMVExt','0.18 + Number(input.age||0)*0.04 + Number(input.pCMV||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongenitalHIVExt','0.18 + Number(input.age||0)*0.04 + Number(input.pHIV||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVZVencephExt','0.18 + Number(input.age||3)*0.04 + Number(input.pVZVenceph||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHSVencephExt','0.18 + Number(input.age||1)*0.04 + Number(input.pHSVenceph||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEnterovirusExt','0.18 + Number(input.age||1)*0.04 + Number(input.pEntero||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMumpsExt','0.18 + Number(input.age||5)*0.04 + Number(input.pMumps||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMeaslesExt','0.18 + Number(input.age||1)*0.04 + Number(input.pMeasles||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRabiesExt','0.18 + Number(input.age||5)*0.04 + Number(input.pRabies||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext170':[('PediatricNeuroAidsTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pNeuroAidsTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeuroLymeTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pNeuroLymeTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCMVvalganExt','0.18 + Number(input.age||0)*0.04 + Number(input.pCMVvalgan||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHIVHAARTxExt','0.18 + Number(input.age||0)*0.04 + Number(input.pHIVHAART||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVZVencephTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pVZVencephTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHSVencephTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pHSVencephTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEnterovirusTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pEnteroTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMumpsTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pMumpsTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMeaslesTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pMeaslesTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRabiesTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pRabiesTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.1.10.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.1.10.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.1.10.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.1.10.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-AJ v3.1.10.0 done')