import os
MODULES=['pcc_neuro_ext120','pcc_pediatric_neuro_ext109','pcc_pediatric_surg_ext109']
FUNCS={
'pcc_neuro_ext120':[('PinealTumorExt','0.18 + Number(input.size||2)*0.1 + Number(input.hydrocephalus||1)*0.2 + Number(input.outcome||1)*0.2'),('PituitaryAdenomaExt','0.18 + Number(input.macroadenoma||1)*0.2 + Number(input.hormonal||1)*0.2 + Number(input.outcome||1)*0.2'),('CraniopharyngiomaExt','0.18 + Number(input.size||3)*0.1 + Number(input.calcification||1)*0.2 + Number(input.outcome||1)*0.2'),('OpticGliomaExt','0.18 + Number(input.nf1||1)*0.2 + Number(input.vision||1)*0.2 + Number(input.outcome||1)*0.2'),('BrainstemGliomaExt','0.18 + Number(input.diffuse||1)*0.2 + Number(input.pontine||1)*0.2 + Number(input.outcome||1)*0.2'),('CerebellarAstocytomaExt','0.18 + Number(input.cystic||1)*0.2 + Number(input.solid||1)*0.2 + Number(input.outcome||1)*0.2'),('MedulloblastomaExt','0.18 + Number(input.molecular||1)*0.2 + Number(input.metastasis||1)*0.2 + Number(input.outcome||1)*0.2'),('EpendymomaExt','0.18 + Number(input.location||1)*0.2 + Number(input.grade||1)*0.2 + Number(input.outcome||1)*0.2'),('ChoroidPlexusTumorExt','0.18 + Number(input.pediatric||1)*0.1 + Number(input.hydrocephalus||1)*0.2 + Number(input.outcome||1)*0.2'),('GermCellTumorExt','0.18 + Number(input.bifocal||1)*0.2 + Number(input.marker||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext109':[('PediatricPinealExt','0.18 + Number(input.age||5)*0.04 + Number(input.tumor||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPituitaryExt','0.18 + Number(input.age||10)*0.04 + Number(input.adenoma||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCraniopharyngiomaExt','0.18 + Number(input.age||5)*0.04 + Number(input.tumor||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOpticGliomaExt','0.18 + Number(input.age||5)*0.04 + Number(input.nf1||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBrainstemGliomaExt','0.18 + Number(input.age||5)*0.04 + Number(input.diffuse||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCerebellarAstrocytomaExt','0.18 + Number(input.age||5)*0.04 + Number(input.cystic||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMedulloblastomaExt','0.18 + Number(input.age||5)*0.04 + Number(input.metastasis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpendymomaExt','0.18 + Number(input.age||5)*0.04 + Number(input.grade||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCPTExt','0.18 + Number(input.age||3)*0.04 + Number(input.tumor||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGCText','0.18 + Number(input.age||10)*0.04 + Number(input.marker||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext109':[('PediatricPinealSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPituitarySxExt','0.18 + Number(input.age||10)*0.04 + Number(input.transsphenoidal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCranioSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOpticGliomaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.chemo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBrainstemGliomaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.radiation||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCerebellarAstroSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMedulloblastomaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpendymomaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCPTSxExt','0.18 + Number(input.age||3)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGCTSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.radiation||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.219.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.219.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.219.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.219.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-JM v3.219.0 done')
