import os
MODULES=['pcc_lab_ext167','pcc_path_ext178','pcc_rad_ext178']
FUNCS={
'pcc_lab_ext167':[('LabTumorMarkerAdultExt','0.18 + Number(input.tmAdult||1)*0.2 + Number(input.marker||1)*0.2 + Number(input.outcome||1)*0.2'),('LabPSAadultExt','0.18 + Number(input.psaAdult||1)*0.2 + Number(input.psaLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('LabCEAadultExt','0.18 + Number(input.ceaAdult||1)*0.2 + Number(input.ceaLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('LabCA125AdultExt','0.18 + Number(input.ca125Adult||1)*0.2 + Number(input.ca125Level||1)*0.04 + Number(input.outcome||1)*0.2'),('LabCA199AdultExt','0.18 + Number(input.ca199Adult||1)*0.2 + Number(input.ca199Level||1)*0.04 + Number(input.outcome||1)*0.2'),('LabAFPadultExt','0.18 + Number(input.afpAdult||1)*0.2 + Number(input.afpLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('LabHCGadultExt','0.18 + Number(input.hcgAdult||1)*0.2 + Number(input.hcgLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('LabTumorLiquidBxExt','0.18 + Number(input.ctdna||1)*0.2 + Number(input.mutation||1)*0.2 + Number(input.outcome||1)*0.2'),('LabThyroAdultExt','0.18 + Number(input.thyroAdult||1)*0.2 + Number(input.tsh||1)*0.04 + Number(input.outcome||1)*0.2'),('LabFerritinAdultExt','0.18 + Number(input.ferritinAdult||1)*0.2 + Number(input.ferritinLevel||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_path_ext178':[('PathTumorExt','0.18 + Number(input.pathTumor||1)*0.2 + Number(input.grade||1)*0.04 + Number(input.outcome||1)*0.2'),('PathProstateExt','0.18 + Number(input.pathProstate||1)*0.2 + Number(input.gleason||1)*0.04 + Number(input.outcome||1)*0.2'),('PathBreastExt','0.18 + Number(input.pathBreast||1)*0.2 + Number(input.nottingham||1)*0.04 + Number(input.outcome||1)*0.2'),('PathColonExt','0.18 + Number(input.pathColon||1)*0.2 + Number(input.tnmStage||1)*0.2 + Number(input.outcome||1)*0.2'),('PathLungExt','0.18 + Number(input.pathLung||1)*0.2 + Number(input.lungType||1)*0.2 + Number(input.outcome||1)*0.2'),('PathPancreasExt','0.18 + Number(input.pathPanc||1)*0.2 + Number(input.differentiation||1)*0.2 + Number(input.outcome||1)*0.2'),('PathOvaryExt','0.18 + Number(input.pathOvary||1)*0.2 + Number(input.ovaryType||1)*0.2 + Number(input.outcome||1)*0.2'),('PathRenalExt','0.18 + Number(input.pathRenal||1)*0.2 + Number(input.furhman||1)*0.04 + Number(input.outcome||1)*0.2'),('PathThyroidExt','0.18 + Number(input.pathThyroid||1)*0.2 + Number(input.thyroType||1)*0.2 + Number(input.outcome||1)*0.2'),('PathLiverExt','0.18 + Number(input.pathLiver||1)*0.2 + Number(input.liverGrade||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_rad_ext178':[('RadTumorStagingExt','0.18 + Number(input.radStaging||1)*0.2 + Number(input.tnm||1)*0.2 + Number(input.outcome||1)*0.2'),('RadPETAdultExt','0.18 + Number(input.petAdult||1)*0.2 + Number(input.suvMax||1)*0.04 + Number(input.outcome||1)*0.2'),('RadCTchestAdultExt','0.18 + Number(input.ctChest||1)*0.2 + Number(input.recist||1)*0.2 + Number(input.outcome||1)*0.2'),('RadMRIadultExt','0.18 + Number(input.mriTumor||1)*0.2 + Number(input.recistMri||1)*0.2 + Number(input.outcome||1)*0.2'),('RadBoneScanAdultExt','0.18 + Number(input.boneScan||1)*0.2 + Number(input.mets||1)*0.2 + Number(input.outcome||1)*0.2'),('RadMammoAdultExt','0.18 + Number(input.mammoAdult||1)*0.2 + Number(input.biRads||1)*0.04 + Number(input.outcome||1)*0.2'),('RadColonoscopyAdultExt','0.18 + Number(input.coloAdult||1)*0.2 + Number(input.coloFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('RadBronchoscopyAdultExt','0.18 + Number(input.bronchAdult||1)*0.2 + Number(input.bronchFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('RadEndoscopyAdultExt','0.18 + Number(input.endoAdult||1)*0.2 + Number(input.endoFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('RadRecistAdultExt','0.18 + Number(input.recistAdult||1)*0.2 + Number(input.response||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.14.14.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.14.14.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.14.14.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.14.14.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LN v3.14.14.0 done')