import os
MODULES=['pcc_neuro_ext175','pcc_pediatric_neuro_ext164','pcc_pediatric_surg_ext164']
FUNCS={
'pcc_neuro_ext175':[('StrokeInflammatoryExt','0.18 + Number(input.strokeInf||1)*0.2 + Number(input.vasculitis||1)*0.2 + Number(input.outcome||1)*0.2'),('PACNSext','0.18 + Number(input.pacns||1)*0.2 + Number(input.brainBiopsy||1)*0.2 + Number(input.outcome||1)*0.2'),('CerebralAmyloidExt','0.18 + Number(input.caa||1)*0.2 + Number(input.lobar||1)*0.2 + Number(input.outcome||1)*0.2'),('RCVS2ext','0.18 + Number(input.rcvs2||1)*0.2 + Number(input.thunderclap3||1)*0.2 + Number(input.outcome||1)*0.2'),('PRES2ext','0.18 + Number(input.pres2||1)*0.2 + Number(input.vasogenicEdema||1)*0.2 + Number(input.outcome||1)*0.2'),('CADASIL2Ext','0.18 + Number(input.cadasil2||1)*0.2 + Number(input.notch3||1)*0.2 + Number(input.outcome||1)*0.2'),('MELASstrokeExt','0.18 + Number(input.melasStroke||1)*0.2 + Number(input.mitoStroke||1)*0.2 + Number(input.outcome||1)*0.2'),('SickleCellStrokeExt','0.18 + Number(input.sickleAdult||1)*0.2 + Number(input.hbS||1)*0.2 + Number(input.outcome||1)*0.2'),('AnticoagReversalExt','0.18 + Number(input.antiCoagRev||1)*0.2 + Number(input.bleeding||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokePregnancyExt','0.18 + Number(input.strokePreg||1)*0.2 + Number(input.puerperium||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext164':[('PediatricStrokeInfExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeInf||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPACNSExt','0.18 + Number(input.age||8)*0.04 + Number(input.pPACNS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRCVS2Ext','0.18 + Number(input.age||10)*0.04 + Number(input.pRCVS2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPRES2Ext','0.18 + Number(input.age||5)*0.04 + Number(input.pPRES2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCADASILExt','0.18 + Number(input.age||10)*0.04 + Number(input.pCADASIL||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMELASstrokeExt','0.18 + Number(input.age||5)*0.04 + Number(input.pMELASstroke||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSickleStroke3Ext','0.18 + Number(input.age||5)*0.04 + Number(input.pSickleStroke3||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeHemorrhagicExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeHem||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeVasculopathyExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeVasculopathy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeThrombophiliaExt','0.18 + Number(input.age||10)*0.04 + Number(input.pStrokeThromb||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext164':[('PediatricStrokeInfTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.strokeInfTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPACNSsteroidExt','0.18 + Number(input.age||8)*0.04 + Number(input.pacnsSteroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRCVS2nimodipineExt','0.18 + Number(input.age||10)*0.04 + Number(input.rcvs2Nimo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPRES2MgmtExt','0.18 + Number(input.age||5)*0.04 + Number(input.pres2Mgmt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCADASILsupportExt','0.18 + Number(input.age||10)*0.04 + Number(input.cadasilSupport||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMELASsupportExt','0.18 + Number(input.age||5)*0.04 + Number(input.melasSupport||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSickleStroke3TxExt','0.18 + Number(input.age||5)*0.04 + Number(input.sickleStroke3Tx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeHemTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.strokeHemTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeVasculopathyTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.strokeVascTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeThrombTxExt','0.18 + Number(input.age||10)*0.04 + Number(input.strokeThrombTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.1.4.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.1.4.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.1.4.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.1.4.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-AD v3.1.4.0 done')