import os
MODULES=['pcc_dental_ext99','pcc_psych_ext99','pcc_rehab_ext99']
FUNCS={
'pcc_dental_ext99':[('DentalCariesExt','0.18 + Number(input.dentalCaries||1)*0.2 + Number(input.dmfScore||1)*0.04 + Number(input.outcome||1)*0.2'),('DentalPerioExt','0.18 + Number(input.dentalPerio||1)*0.2 + Number(input.pocketDepth||1)*0.04 + Number(input.outcome||1)*0.2'),('DentalEndoExt','0.18 + Number(input.dentalEndo||1)*0.2 + Number(input.periapical||1)*0.2 + Number(input.outcome||1)*0.2'),('DentalProsthoExt','0.18 + Number(input.dentalProsth||1)*0.2 + Number(input.missingTeeth||1)*0.04 + Number(input.outcome||1)*0.2'),('DentalOrthoExt','0.18 + Number(input.dentalOrtho||1)*0.2 + Number(input.malocclusion||1)*0.2 + Number(input.outcome||1)*0.2'),('DentalSurgeryExt','0.18 + Number(input.dentalSurg||1)*0.2 + Number(input.surgType||1)*0.2 + Number(input.outcome||1)*0.2'),('DentalPediatricExt','0.18 + Number(input.dentalPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2'),('DentalImplantExt','0.18 + Number(input.dentalImp||1)*0.2 + Number(input.boneDensity||1)*0.2 + Number(input.outcome||1)*0.2'),('DentalTraumaExt','0.18 + Number(input.dentalTrauma||1)*0.2 + Number(input.traumaClass||1)*0.04 + Number(input.outcome||1)*0.2'),('DentalOralMedExt','0.18 + Number(input.dentalOralMed||1)*0.2 + Number(input.mucosalLesion||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_psych_ext99':[('PsychDepressionExt','0.18 + Number(input.psychDep||1)*0.2 + Number(input.phq9||1)*0.04 + Number(input.outcome||1)*0.2'),('PsychAnxietyExt','0.18 + Number(input.psychAnx||1)*0.2 + Number(input.gad7||1)*0.04 + Number(input.outcome||1)*0.2'),('PsychBipolarExt','0.18 + Number(input.psychBipolar||1)*0.2 + Number(input.ymrs||1)*0.04 + Number(input.outcome||1)*0.2'),('PsychSchizoExt','0.18 + Number(input.psychSchizo||1)*0.2 + Number(input.panss||1)*0.04 + Number(input.outcome||1)*0.2'),('PsychPTSDext','0.18 + Number(input.psychPTSD||1)*0.2 + Number(input.pclScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PsychSubstanceExt','0.18 + Number(input.psychSubst||1)*0.2 + Number(input.substType||1)*0.2 + Number(input.outcome||1)*0.2'),('PsychEatingExt','0.18 + Number(input.psychEating||1)*0.2 + Number(input.bmi||1)*0.04 + Number(input.outcome||1)*0.2'),('PsychPersonalityExt','0.18 + Number(input.psychPerson||1)*0.2 + Number(input.personDisorder||1)*0.2 + Number(input.outcome||1)*0.2'),('PsychGeriatricExt','0.18 + Number(input.psychGeriatric||1)*0.2 + Number(input.mmseScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PsychCrisisExt','0.18 + Number(input.psychCrisis||1)*0.2 + Number(input.suicideRisk||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_rehab_ext99':[('RehabStrokeExt','0.18 + Number(input.rehabStroke||1)*0.2 + Number(input.barthel||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabOrthoExt','0.18 + Number(input.rehabOrtho||1)*0.2 + Number(input.orthoType||1)*0.2 + Number(input.outcome||1)*0.2'),('RehabCardiacExt','0.18 + Number(input.rehabCardiac||1)*0.2 + Number(input.metEquiv||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabPulmonaryExt','0.18 + Number(input.rehabPulm||1)*0.2 + Number(input.fev1||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabNeuroExt','0.18 + Number(input.rehabNeuro||1)*0.2 + Number(input.fuglMeyer||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabSpinalExt','0.18 + Number(input.rehabSpinal||1)*0.2 + Number(input.aisGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabBurnExt','0.18 + Number(input.rehabBurn||1)*0.2 + Number(input.tbsa||1)*0.04 + Number(input.outcome||1)*0.2'),('RehabAmputeeExt','0.18 + Number(input.rehabAmp||1)*0.2 + Number(input.ampLevel||1)*0.2 + Number(input.outcome||1)*0.2'),('RehabSportsExt','0.18 + Number(input.rehabSports||1)*0.2 + Number(input.sportsType||1)*0.2 + Number(input.outcome||1)*0.2'),('RehabPediatricExt','0.18 + Number(input.rehabPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.19.19.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.19.19.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.19.19.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.19.19.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LS v3.19.19.0 done')