import os
MODULES=['pcc_neuro_ext112','pcc_pediatric_neuro_ext101','pcc_pediatric_surg_ext101']
FUNCS={
'pcc_neuro_ext112':[('MigraineExt','0.18 + Number(input.frequency||4)*0.04 + Number(input.severity||5)*0.04 + Number(input.outcome||1)*0.2'),('MigraineAuraExt','0.18 + Number(input.aura||1)*0.2 + Number(input.frequency||4)*0.04 + Number(input.outcome||1)*0.2'),('ChronicMigraineExt','0.18 + Number(input.days||15)*0.02 + Number(input.medicationOveruse||1)*0.2 + Number(input.outcome||1)*0.2'),('ClusterHeadacheExt','0.18 + Number(input.attacks||3)*0.1 + Number(input.duration||90)*0.005 + Number(input.outcome||1)*0.2'),('TensionHeadacheExt','0.18 + Number(input.frequency||4)*0.04 + Number(input.tender||1)*0.2 + Number(input.outcome||1)*0.2'),('TrigeminalNeuralgiaExt','0.18 + Number(input.paroxysms||5)*0.04 + Number(input.trigger||1)*0.2 + Number(input.outcome||1)*0.2'),('OccipitalNeuralgiaExt','0.18 + Number(input.paroxysms||5)*0.04 + Number(input.trigger||1)*0.2 + Number(input.outcome||1)*0.2'),('IdiopathicIntracranialHTNExt','0.18 + Number(input.opening||30)*0.01 + Number(input.papilledema||1)*0.2 + Number(input.outcome||1)*0.2'),('SpontaneousICSExt','0.18 + Number(input.opening||8)*0.04 + Number(input.orthostatic||1)*0.2 + Number(input.outcome||1)*0.2'),('ReversibleCerebralVasoconstExt','0.18 + Number(input.vasoconst||1)*0.2 + Number(input.headache||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext101':[('PediatricMigraineExt','0.18 + Number(input.age||8)*0.04 + Number(input.frequency||4)*0.04 + Number(input.outcome||1)*0.2'),('PediatricMigraineAuraExt','0.18 + Number(input.age||10)*0.04 + Number(input.aura||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChronicMigraineExt','0.18 + Number(input.age||10)*0.04 + Number(input.days||15)*0.02 + Number(input.outcome||1)*0.2'),('PediatricClusterExt','0.18 + Number(input.age||12)*0.02 + Number(input.attacks||3)*0.1 + Number(input.outcome||1)*0.2'),('PediatricTensionExt','0.18 + Number(input.age||8)*0.04 + Number(input.tender||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTrigeminalExt','0.18 + Number(input.age||10)*0.04 + Number(input.paroxysms||5)*0.04 + Number(input.outcome||1)*0.2'),('PediatricOccipitalExt','0.18 + Number(input.age||10)*0.04 + Number(input.paroxysms||5)*0.04 + Number(input.outcome||1)*0.2'),('PediatricIIHExt','0.18 + Number(input.age||10)*0.04 + Number(input.papilledema||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricICSExt','0.18 + Number(input.age||12)*0.02 + Number(input.orthostatic||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRCVSExt','0.18 + Number(input.age||10)*0.04 + Number(input.vasoconst||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext101':[('PediatricMigraineImmunoExt','0.18 + Number(input.age||10)*0.04 + Number(input.cgrp||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMigraineAuraImmunoExt','0.18 + Number(input.age||10)*0.04 + Number(input.prophylaxis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChronicMigraineImmunoExt','0.18 + Number(input.age||10)*0.04 + Number(input.detox||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricClusterImmunoExt','0.18 + Number(input.age||12)*0.02 + Number(input.oxygen||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTensionImmunoExt','0.18 + Number(input.age||8)*0.04 + Number(input.relaxation||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTrigeminalSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.mvd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOccipitalSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.neurostim||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIIHSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.shunt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricICSSxExt','0.18 + Number(input.age||12)*0.02 + Number(input.patch||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRCVSSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.nimodipine||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.211.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.211.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.211.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.211.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-JE v3.211.0 done')
