import os
MODULES=['pcc_neuro_ext162','pcc_pediatric_neuro_ext151','pcc_pediatric_surg_ext151']
FUNCS={
'pcc_neuro_ext162':[('MultipleSclerosisExt','0.18 + Number(input.ms||1)*0.2 + Number(input.edss||1)*0.04 + Number(input.outcome||1)*0.2'),('MSRelapseExt','0.18 + Number(input.relapse||1)*0.2 + Number(input.gad||1)*0.2 + Number(input.outcome||1)*0.2'),('MSProgressiveExt','0.18 + Number(input.progressive||1)*0.2 + Number(input.pms||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuromyelitisOpticaExt','0.18 + Number(input.nmo||1)*0.2 + Number(input.aqp4||1)*0.2 + Number(input.outcome||1)*0.2'),('MOGantibodyExt','0.18 + Number(input.mog||1)*0.2 + Number(input.optica||1)*0.2 + Number(input.outcome||1)*0.2'),('ADEMext','0.18 + Number(input.adem||1)*0.2 + Number(input.postInfectious||1)*0.2 + Number(input.outcome||1)*0.2'),('TransverseMyelitisExt','0.18 + Number(input.tm||1)*0.2 + Number(input.longitud||1)*0.2 + Number(input.outcome||1)*0.2'),('OpticNeuritisExt','0.18 + Number(input.optNeur||1)*0.2 + Number(input.vision||1)*0.2 + Number(input.outcome||1)*0.2'),('NeurosarcoidosisExt','0.18 + Number(input.neuroSarc||1)*0.2 + Number(input.cranialNerve||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuroLupusExt','0.18 + Number(input.nLupus||1)*0.2 + Number(input.antiPhos||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext151':[('PediatricMSExt','0.18 + Number(input.age||12)*0.04 + Number(input.pMS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricADEMExt','0.18 + Number(input.age||5)*0.04 + Number(input.pADEM||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNMOExt','0.18 + Number(input.age||8)*0.04 + Number(input.pNMO||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMOGExt','0.18 + Number(input.age||5)*0.04 + Number(input.pMOG||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTMExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTM||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOptNeuritisExt','0.18 + Number(input.age||10)*0.04 + Number(input.pOptNeur||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCerebellitisExt','0.18 + Number(input.age||5)*0.04 + Number(input.cerebellitis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBrainstemExt','0.18 + Number(input.age||5)*0.04 + Number(input.brainstemEnceph||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVasculitisExt','0.18 + Number(input.age||5)*0.04 + Number(input.pVasculitis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLupusNeuroExt','0.18 + Number(input.age||10)*0.04 + Number(input.pLupusNeuro||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext151':[('PediatricMSDMTxExt','0.18 + Number(input.age||12)*0.04 + Number(input.dmtMS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricADEMsteroidExt','0.18 + Number(input.age||5)*0.04 + Number(input.ademSteroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNMOeculizExt','0.18 + Number(input.age||8)*0.04 + Number(input.nmoEcu||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMOGIVIGExt','0.18 + Number(input.age||5)*0.04 + Number(input.mogIvig||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTMsxExt','0.18 + Number(input.age||8)*0.04 + Number(input.tmSteroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOptNeurIVExt','0.18 + Number(input.age||10)*0.04 + Number(input.optIv||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCerebellitisSupportExt','0.18 + Number(input.age||5)*0.04 + Number(input.cerebSupport||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBrainstemSupportExt','0.18 + Number(input.age||5)*0.04 + Number(input.bsSupport||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVasculitisCycloExt','0.18 + Number(input.age||5)*0.04 + Number(input.pVascCyclo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLupusNeuroRxExt','0.18 + Number(input.age||10)*0.04 + Number(input.pLupusRx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.261.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.261.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.261.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.261.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LC v3.261.0 done')