import os
MODULES=['pcc_neuro_ext188','pcc_pediatric_neuro_ext177','pcc_pediatric_surg_ext177']
FUNCS={
'pcc_neuro_ext188':[('MovementDisorderDrugExt','0.18 + Number(input.mdDrug||1)*0.2 + Number(input.dopa||1)*0.2 + Number(input.outcome||1)*0.2'),('DBSprogrammingExt','0.18 + Number(input.dbsProg||1)*0.2 + Number(input.programming||1)*0.2 + Number(input.outcome||1)*0.2'),('LevodopaChallengeExt','0.18 + Number(input.levodopaChallenge||1)*0.2 + Number(input.response||1)*0.2 + Number(input.outcome||1)*0.2'),('ApomorphineExt','0.18 + Number(input.apo||1)*0.2 + Number(input.infusion||1)*0.2 + Number(input.outcome||1)*0.2'),('LCIGext','0.18 + Number(input.lcig||1)*0.2 + Number(input.dopaInfusion||1)*0.2 + Number(input.outcome||1)*0.2'),('BotulinumMovementExt','0.18 + Number(input.botoxMove||1)*0.2 + Number(input.dystoniaBotox||1)*0.2 + Number(input.outcome||1)*0.2'),('ParkFreezingExt','0.18 + Number(input.freezing||1)*0.2 + Number(input.gaitFreezing||1)*0.2 + Number(input.outcome||1)*0.2'),('ParkFallsExt','0.18 + Number(input.parkFalls||1)*0.2 + Number(input.balance||1)*0.2 + Number(input.outcome||1)*0.2'),('ParkDementiaExt','0.18 + Number(input.parkDem||1)*0.2 + Number(input.cognitive||1)*0.2 + Number(input.outcome||1)*0.2'),('ParkPsychosisExt','0.18 + Number(input.parkPsy||1)*0.2 + Number(input.hallucinations||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext177':[('PediatricMovementDrugExt','0.18 + Number(input.age||8)*0.04 + Number(input.pMDrug||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBotulinumExt','0.18 + Number(input.age||3)*0.04 + Number(input.pBotox||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDBSext','0.18 + Number(input.age||8)*0.04 + Number(input.pDBS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricITBext','0.18 + Number(input.age||5)*0.04 + Number(input.pITB||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDystoniaRxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pDystoniaRx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChoreaRxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pChoreaRx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTicRxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTicRx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAtaxiaRxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pAtaxiaRx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMyoclonusRxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pMyoRx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTremorRxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTremorRx||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext177':[('PediatricMoveDrugTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.moveDrugTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBotulinumTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.botoxTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDBSSurgExt','0.18 + Number(input.age||8)*0.04 + Number(input.pDBSSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricITBSurgExt','0.18 + Number(input.age||5)*0.04 + Number(input.pITBSurg||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDystoniaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pDystoniaSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChoreaSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pChoreaSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTicCBTExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTicCBT||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAtaxiaRehabExt','0.18 + Number(input.age||5)*0.04 + Number(input.pAtaxiaRehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMyoTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pMyoTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTremorTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTremorTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.17.17.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.17.17.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.17.17.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.17.17.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-HQ v3.17.17.0 done')