import os
MODULES=['pcc_rheumatology_ext102','pcc_allergy_ext102','pcc_immunology_ext102']
FUNCS={
'pcc_rheumatology_ext102':[('RheGenExt','0.18 + Number(input.rhGen||1)*0.2 + Number(input.rhGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('RheRAext','0.18 + Number(input.rhRA||1)*0.2 + Number(input.rhRADAS28||1)*0.04 + Number(input.outcome||1)*0.2'),('RheSLEext','0.18 + Number(input.rhSLE||1)*0.2 + Number(input.rhSLEDAI||1)*0.04 + Number(input.outcome||1)*0.2'),('RheSpAext','0.18 + Number(input.rhSpA||1)*0.2 + Number(input.rhSpAType||1)*0.2 + Number(input.outcome||1)*0.2'),('RheVasculExt','0.18 + Number(input.rhVas||1)*0.2 + Number(input.rhVasType||1)*0.2 + Number(input.outcome||1)*0.2'),('RheGoutExt','0.18 + Number(input.rhGout||1)*0.2 + Number(input.rhGoutUA||1)*0.04 + Number(input.outcome||1)*0.2'),('RheOAext','0.18 + Number(input.rhOA||1)*0.2 + Number(input.rhOAGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('RheSjogExt','0.18 + Number(input.rhSjog||1)*0.2 + Number(input.rhSjogType||1)*0.2 + Number(input.outcome||1)*0.2'),('RheScleroExt','0.18 + Number(input.rhScl||1)*0.2 + Number(input.rhSclScore||1)*0.04 + Number(input.outcome||1)*0.2'),('RheMyoExt','0.18 + Number(input.rhMyo||1)*0.2 + Number(input.rhMyoType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_allergy_ext102':[('AlgGenExt','0.18 + Number(input.alGen||1)*0.2 + Number(input.alGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('AlgRhinitisExt','0.18 + Number(input.alRhi||1)*0.2 + Number(input.alRhiScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AlgAsthmaExt','0.18 + Number(input.alAst||1)*0.2 + Number(input.alAstScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AlgFoodExt','0.18 + Number(input.alFood||1)*0.2 + Number(input.alFoodType||1)*0.2 + Number(input.outcome||1)*0.2'),('AlgDrugExt','0.18 + Number(input.alDrug||1)*0.2 + Number(input.alDrugType||1)*0.2 + Number(input.outcome||1)*0.2'),('AlgInsectExt','0.18 + Number(input.alIns||1)*0.2 + Number(input.alInsType||1)*0.2 + Number(input.outcome||1)*0.2'),('AlgLatexExt','0.18 + Number(input.alLtx||1)*0.2 + Number(input.alLtxType||1)*0.2 + Number(input.outcome||1)*0.2'),('AlgUrticariaExt','0.18 + Number(input.alUrt||1)*0.2 + Number(input.alUrtScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AlgAnaphyExt','0.18 + Number(input.alAna||1)*0.2 + Number(input.alAnaScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AlgImmunothExt','0.18 + Number(input.alImm||1)*0.2 + Number(input.alImmType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_immunology_ext102':[('ImmGenExt','0.18 + Number(input.imGen||1)*0.2 + Number(input.imGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmPrimaryExt','0.18 + Number(input.imPri||1)*0.2 + Number(input.imPriType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmSecondaryExt','0.18 + Number(input.imSec||1)*0.2 + Number(input.imSecType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmCVIDext','0.18 + Number(input.imCVID||1)*0.2 + Number(input.imCVIDscore||1)*0.04 + Number(input.outcome||1)*0.2'),('ImmHyperExt','0.18 + Number(input.imHIGM||1)*0.2 + Number(input.imHIGMtype||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmSCIDext','0.18 + Number(input.imSCID||1)*0.2 + Number(input.imSCIDtype||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmAutoExt','0.18 + Number(input.imAuto||1)*0.2 + Number(input.imAutoType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmTransplantExt','0.18 + Number(input.imTx||1)*0.2 + Number(input.imTxType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmIVIGext','0.18 + Number(input.imIVIG||1)*0.2 + Number(input.imIVIGtype||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmVaccExt','0.18 + Number(input.imVacc||1)*0.2 + Number(input.imVaccType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.60.60.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.60.60.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.60.60.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.60.60.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NH v3.60.60.0 done')