import os
MODULES=['pcc_radiology_ext100','pcc_imaging_ext100','pcc_nuclear_ext100']
FUNCS={
'pcc_radiology_ext100':[('RadXrayExt','0.18 + Number(input.rdXray||1)*0.2 + Number(input.xrayFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('RadCText','0.18 + Number(input.rdCT||1)*0.2 + Number(input.ctFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('RadMRIext','0.18 + Number(input.rdMRI||1)*0.2 + Number(input.mriFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('RadUltrasoundExt','0.18 + Number(input.rdUS||1)*0.2 + Number(input.usFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('RadFluoroExt','0.18 + Number(input.rdFluoro||1)*0.2 + Number(input.fluoroDose||1)*0.04 + Number(input.outcome||1)*0.2'),('RadAngioExt','0.18 + Number(input.rdAngio||1)*0.2 + Number(input.angioType||1)*0.2 + Number(input.outcome||1)*0.2'),('RadContrastExt','0.18 + Number(input.rdContrast||1)*0.2 + Number(input.contrastReaction||1)*0.2 + Number(input.outcome||1)*0.2'),('RadInterventionExt','0.18 + Number(input.rdInter||1)*0.2 + Number(input.interType||1)*0.2 + Number(input.outcome||1)*0.2'),('RadMammoExt','0.18 + Number(input.rdMammo||1)*0.2 + Number(input.biRadsRD||1)*0.04 + Number(input.outcome||1)*0.2'),('RadDoseExt','0.18 + Number(input.rdDose||1)*0.2 + Number(input.doseLevel||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_imaging_ext100':[('ImgPEText','0.18 + Number(input.imgPET||1)*0.2 + Number(input.suvLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('ImgSPECText','0.18 + Number(input.imgSPECT||1)*0.2 + Number(input.spectFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgDopplerExt','0.18 + Number(input.imgDoppler||1)*0.2 + Number(input.dopplerFlow||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgEchocardiographyExt','0.18 + Number(input.imgEcho||1)*0.2 + Number(input.efLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('ImgEndoscopyExt','0.18 + Number(input.imgEndo||1)*0.2 + Number(input.endoImgFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgCapsuleExt','0.18 + Number(input.imgCapsule||1)*0.2 + Number(input.capsuleFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgCBCText','0.18 + Number(input.imgCBCT||1)*0.2 + Number(input.cbctFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgFluoro3DExt','0.18 + Number(input.imgFluoro3D||1)*0.2 + Number(input.fluoro3DFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgMRAext','0.18 + Number(input.imgMRA||1)*0.2 + Number(input.mraFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('ImgCTAext','0.18 + Number(input.imgCTA||1)*0.2 + Number(input.ctaFinding||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_nuclear_ext100':[('NucThyroidExt','0.18 + Number(input.nucThyroid||1)*0.2 + Number(input.uptakeLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('NucBoneExt','0.18 + Number(input.nucBone||1)*0.2 + Number(input.boneFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('NucRenalExt','0.18 + Number(input.nucRenal||1)*0.2 + Number(input.gfrL||1)*0.04 + Number(input.outcome||1)*0.2'),('NucCardiacExt','0.18 + Number(input.nucCardiac||1)*0.2 + Number(input.perfusionDefect||1)*0.2 + Number(input.outcome||1)*0.2'),('NucLungV_QExt','0.18 + Number(input.nucVQ||1)*0.2 + Number(input.vqMatch||1)*0.2 + Number(input.outcome||1)*0.2'),('NucHIDAext','0.18 + Number(input.nucHIDA||1)*0.2 + Number(input.hidaEjection||1)*0.04 + Number(input.outcome||1)*0.2'),('NucGIbleedExt','0.18 + Number(input.nucGIb||1)*0.2 + Number(input.giBleedLoc||1)*0.2 + Number(input.outcome||1)*0.2'),('NucMIBGext','0.18 + Number(input.nucMIBG||1)*0.2 + Number(input.mibgFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('NucOctreotideExt','0.18 + Number(input.nucOct||1)*0.2 + Number(input.octreotideFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('NucPSMAext','0.18 + Number(input.nucPSMA||1)*0.2 + Number(input.psmaSUV||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.28.28.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.28.28.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.28.28.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.28.28.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MB v3.28.28.0 done')