import os
MODULES=['pcc_neuro_ext168','pcc_pediatric_neuro_ext157','pcc_pediatric_surg_ext157']
FUNCS={
'pcc_neuro_ext168':[('OpticNeuritis2Ext','0.18 + Number(input.optNeur2||1)*0.2 + Number(input.rapd||1)*0.2 + Number(input.outcome||1)*0.2'),('IschemicOpticNeuroExt','0.18 + Number(input.ion||1)*0.2 + Number(input.naion||1)*0.2 + Number(input.outcome||1)*0.2'),('PapilledemaExt','0.18 + Number(input.papilledema2||1)*0.2 + Number(input.iih2||1)*0.2 + Number(input.outcome||1)*0.2'),('MacularDegenerationExt','0.18 + Number(input.amd||1)*0.2 + Number(input.drusen||1)*0.2 + Number(input.outcome||1)*0.2'),('RetinalDetachmentExt','0.18 + Number(input.rd||1)*0.2 + Number(input.shadows||1)*0.2 + Number(input.outcome||1)*0.2'),('RetinalVeinOcclusionExt','0.18 + Number(input.rvo||1)*0.2 + Number(input.crv||1)*0.2 + Number(input.outcome||1)*0.2'),('RetinalArteryOcclusionExt','0.18 + Number(input.rac||1)*0.2 + Number(input.crao||1)*0.2 + Number(input.outcome||1)*0.2'),('DiabeticRetinopathyExt','0.18 + Number(input.dr||1)*0.2 + Number(input.hba1c||1)*0.2 + Number(input.outcome||1)*0.2'),('GlaucomaNeuroExt','0.18 + Number(input.glaucoma||1)*0.2 + Number(input.iop||1)*0.2 + Number(input.outcome||1)*0.2'),('OrbitalCellulitisExt','0.18 + Number(input.orbitalCell||1)*0.2 + Number(input.proptosis||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext157':[('PediatricOptNeurExt','0.18 + Number(input.age||8)*0.04 + Number(input.pOptNeur2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIONExt','0.18 + Number(input.age||10)*0.04 + Number(input.pION||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPapilledemaExt','0.18 + Number(input.age||5)*0.04 + Number(input.pPapilledema||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRetinoblastomaExt','0.18 + Number(input.age||1)*0.04 + Number(input.retinoblast||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricROPext','0.18 + Number(input.age||0)*0.04 + Number(input.rop||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLeberAmaurosisExt','0.18 + Number(input.age||1)*0.04 + Number(input.lca||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongCataractExt','0.18 + Number(input.age||0)*0.04 + Number(input.congCataract||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGlaucomaExt','0.18 + Number(input.age||3)*0.04 + Number(input.pGlaucoma||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOrbitalCellExt','0.18 + Number(input.age||5)*0.04 + Number(input.pOrbitalCell||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAmblyopiaExt','0.18 + Number(input.age||3)*0.04 + Number(input.amblyopia||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext157':[('PediatricOptNeurIVExt','0.18 + Number(input.age||8)*0.04 + Number(input.optIv2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIONsupportExt','0.18 + Number(input.age||10)*0.04 + Number(input.pIONSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPapilledemaTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.papTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRetinoblastomaSxExt','0.18 + Number(input.age||1)*0.04 + Number(input.retSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricROPlaserExt','0.18 + Number(input.age||0)*0.04 + Number(input.ropLaser||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLeberGeneTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.lcaGene||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongCataractSxExt','0.18 + Number(input.age||0)*0.04 + Number(input.cataractSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGlaucomaSxExt','0.18 + Number(input.age||3)*0.04 + Number(input.glaucSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOrbitalCellAbxExt','0.18 + Number(input.age||5)*0.04 + Number(input.orbitalAbx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAmblyopiaPatchExt','0.18 + Number(input.age||3)*0.04 + Number(input.patchEye||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.12.9.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.12.9.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.12.9.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.12.9.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LI v3.12.9.0 done')