import os
MODULES=['pcc_neuro_ext127','pcc_pediatric_neuro_ext116','pcc_pediatric_surg_ext116']
FUNCS={
'pcc_neuro_ext127':[('CerebralCavernousExt','0.18 + Number(input.familial||1)*0.2 + Number(input.multiple||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalCavernousExt','0.18 + Number(input.spinal||1)*0.2 + Number(input.cord||1)*0.2 + Number(input.outcome||1)*0.2'),('CerebralAVMExt2','0.18 + Number(input.spetzler||3)*0.1 + Number(input.nidus||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinalAVMExt','0.18 + Number(input.spinal||1)*0.2 + Number(input.fistula||1)*0.2 + Number(input.outcome||1)*0.2'),('DuralFistulaExt2','0.18 + Number(input.cognard||2)*0.1 + Number(input.venous||1)*0.2 + Number(input.outcome||1)*0.2'),('CarotidCavernousFistulaExt2','0.18 + Number(input.direct||1)*0.2 + Number(input.indirect||1)*0.2 + Number(input.outcome||1)*0.2'),('DevelopmentalVenousAnomExt','0.18 + Number(input.vein||1)*0.2 + Number(input.caput||1)*0.2 + Number(input.outcome||1)*0.2'),('CapillaryTelangiectasiaExt','0.18 + Number(input.brainstem||1)*0.2 + Number(input.familial||1)*0.2 + Number(input.outcome||1)*0.2'),('MixedMalformationExt','0.18 + Number(input.combined||1)*0.2 + Number(input.symptoms||1)*0.2 + Number(input.outcome||1)*0.2'),('RenduOslerWeberExt','0.18 + Number(input.hht||1)*0.2 + Number(input.avm||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext116':[('PediatricCCMext','0.18 + Number(input.age||5)*0.04 + Number(input.familial||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalCCMext','0.18 + Number(input.age||5)*0.04 + Number(input.spinal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAVMext2','0.18 + Number(input.age||5)*0.04 + Number(input.spetzler||3)*0.1 + Number(input.outcome||1)*0.2'),('PediatricSpinalAVMext','0.18 + Number(input.age||5)*0.04 + Number(input.spinal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDuralFistulaExt2','0.18 + Number(input.age||5)*0.04 + Number(input.dural||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCCFistulaExt2','0.18 + Number(input.age||5)*0.04 + Number(input.ccf||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDVAext','0.18 + Number(input.age||5)*0.04 + Number(input.dva||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCapillaryTelExt','0.18 + Number(input.age||5)*0.04 + Number(input.tel||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMixedMalExt','0.18 + Number(input.age||5)*0.04 + Number(input.combined||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHHText','0.18 + Number(input.age||5)*0.04 + Number(input.hht||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext116':[('PediatricCCMSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalCCMSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAVMSxExt2','0.18 + Number(input.age||5)*0.04 + Number(input.embolization||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinalAVMSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.embolization||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDuralFistulaSxExt2','0.18 + Number(input.age||5)*0.04 + Number(input.embolization||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCCFistulaSxExt2','0.18 + Number(input.age||5)*0.04 + Number(input.coil||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDVASxExt','0.18 + Number(input.age||5)*0.04 + Number(input.observation||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCapillaryTelSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.observation||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMixedMalSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHHTSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.embolization||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.226.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.226.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.226.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.226.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-JT v3.226.0 done')
