import os
MODULES=['pcc_neuro_ext184','pcc_pediatric_neuro_ext173','pcc_pediatric_surg_ext173']
FUNCS={
'pcc_neuro_ext184':[('NeuroEndocrineAdvancedExt','0.18 + Number(input.netAdv||1)*0.2 + Number(input.serotonin||1)*0.2 + Number(input.outcome||1)*0.2'),('PituitaryApoplexyExt','0.18 + Number(input.apoplexy||1)*0.2 + Number(input.headache||1)*0.2 + Number(input.outcome||1)*0.2'),('EmptySellaExt','0.18 + Number(input.emptySella||1)*0.2 + Number(input.herniation||1)*0.2 + Number(input.outcome||1)*0.2'),('LymphocyticHypophysitisExt','0.18 + Number(input.lymphHypo||1)*0.2 + Number(input.autoimmune||1)*0.2 + Number(input.outcome||1)*0.2'),('DiabetesInsipidusPregExt','0.18 + Number(input.diPreg||1)*0.2 + Number(input.pregnancyDI||1)*0.2 + Number(input.outcome||1)*0.2'),('HypopituitarismExt','0.18 + Number(input.hypopit||1)*0.2 + Number(input.deficiency||1)*0.2 + Number(input.outcome||1)*0.2'),('PituitaryPostopExt','0.18 + Number(input.pitPostop||1)*0.2 + Number(input.transsphen||1)*0.2 + Number(input.outcome||1)*0.2'),('SIADHCancerExt','0.18 + Number(input.siadhCancer||1)*0.2 + Number(input.smallCell||1)*0.2 + Number(input.outcome||1)*0.2'),('AdrenalInsufficiencyCritExt','0.18 + Number(input.adrenalCrit||1)*0.2 + Number(input.shock||1)*0.2 + Number(input.outcome||1)*0.2'),('PituitaryApoplexyCritExt','0.18 + Number(input.pitApoplexyCrit||1)*0.2 + Number(input.visual||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext173':[('PediatricPituitaryApoplexyExt','0.18 + Number(input.age||12)*0.04 + Number(input.pPitApoplexy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEmptySellaExt','0.18 + Number(input.age||10)*0.04 + Number(input.pEmptySella||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLymphHypoExt','0.18 + Number(input.age||8)*0.04 + Number(input.pLymphHypo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDIneonatalExt','0.18 + Number(input.age||0)*0.04 + Number(input.pDIneonatal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSIADHpostOpExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSIADHpostOp||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHypopitExt','0.18 + Number(input.age||5)*0.04 + Number(input.pHypopit||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPituitaryPostopExt','0.18 + Number(input.age||12)*0.04 + Number(input.pPitPostop||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCraniopharyngiomaExt','0.18 + Number(input.age||8)*0.04 + Number(input.pCraniopharyngioma||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHypopitTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pHypopitTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPitApoplexyCritExt','0.18 + Number(input.age||12)*0.04 + Number(input.pPitApoplexyCrit||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext173':[('PediatricPitApoplexyTxExt','0.18 + Number(input.age||12)*0.04 + Number(input.pPitApoplexyTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEmptySellaTxExt','0.18 + Number(input.age||10)*0.04 + Number(input.pEmptySellaTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLymphHypoTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pLymphHypoTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDIneonatalTxExt','0.18 + Number(input.age||0)*0.04 + Number(input.pDIneonatalTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSIADHpostOpTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSIADHpostOpTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHypopitSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pHypopitSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPituitaryPostopSxExt','0.18 + Number(input.age||12)*0.04 + Number(input.pPitPostopSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCraniopharyngiomaSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pCraniopharyngiomaSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHypopitHormoneExt','0.18 + Number(input.age||5)*0.04 + Number(input.pHypopitHormone||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPitApoplexyCritTxExt','0.18 + Number(input.age||12)*0.04 + Number(input.pPitApoplexyCritTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.13.13.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.13.13.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.13.13.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.13.13.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-HM v3.13.13.0 done')