import os
MODULES=['pcc_neuro_ext90','pcc_pediatric_neuro_ext79','pcc_pediatric_surg_ext79']
FUNCS={
'pcc_neuro_ext90':[('StereoEEGPlacementExt','0.15 + Number(input.depths||10)*0.04 + Number(input.targetAcc||95)*0.005 + Number(input.duration||5)*0.04'),('IntracranialEEGExt','0.2 + Number(input.electrodes||60)*0.006 + Number(input.days||10)*0.02 + Number(input.yield||70)*0.005'),('HighDensityEEGExt','0.18 + Number(input.channels||256)*0.002 + Number(input.seizures||3)*0.05 + Number(input.spikes||30)*0.005'),('MEGSrcLocalizationExt','0.25 + Number(input.sensors||306)*0.001 + Number(input.corr||0.9)*0.3 + Number(input.dipoles||5)*0.05'),('OpticalImagingExt','0.2 + Number(input.hbos||10)*0.02 + Number(input.fNIRS||1)*0.2 + Number(input.tasks||3)*0.05'),('TMSMappingExt','0.15 + Number(input.coils||1)*0.15 + Number(input.intensity||1.2)*0.2 + Number(input.corticalMap||80)*0.005'),('FunctionalMRIExt','0.18 + Number(input.bold||1)*0.2 + Number(input.dyn||1)*0.15 + Number(input.taskFMRI||1)*0.15'),('DiffusionTensorExt','0.2 + Number(input.tracts||10)*0.04 + Number(input.fa||0.5)*0.5 + Number(input.fibers||1)*0.1'),('MRISpectroscopyExt','0.18 + Number(input.metabolites||5)*0.06 + Number(input.voxels||10)*0.02 + Number(input.NAA||1)*0.2'),('PETAmyloidExt','0.2 + Number(input.suvr||1.5)*0.3 + Number(input.drift||1)*0.1 + Number(input.centiloids||50)*0.008')],
'pcc_pediatric_neuro_ext79':[('PediatricStereoEEGSurgExt','0.15 + Number(input.pediatricDepths||8)*0.04 + Number(input.accuracy||94)*0.005 + Number(input.duration||4)*0.05'),('PediatricIntracranialExt','0.2 + Number(input.grid||60)*0.006 + Number(input.days||7)*0.02 + Number(input.localization||75)*0.005'),('PediatricHighDensityEEGExt','0.18 + Number(input.chan||128)*0.003 + Number(input.evt||2)*0.05 + Number(input.spikes||40)*0.005'),('PediatricMEGSrcExt','0.25 + Number(input.sens||306)*0.001 + Number(input.corr||0.9)*0.3 + Number(input.kidDipoles||3)*0.05'),('PediatricOpticalExt','0.2 + Number(input.hbos||5)*0.04 + Number(input.tasks||2)*0.1 + Number(input.duration||30)*0.01'),('PediatricTMSMappingExt','0.15 + Number(input.age||8)*0.02 + Number(input.intensity||0.9)*0.2 + Number(input.corticalMap||75)*0.005'),('PediatricFMRIExt','0.18 + Number(input.bold||1)*0.2 + Number(input.dyn||1)*0.15 + Number(input.taskFMRI||1)*0.15'),('PediatricDTIExt','0.2 + Number(input.tracts||8)*0.04 + Number(input.fa||0.5)*0.5 + Number(input.fibers||1)*0.1'),('PediatricSpectroscopyExt','0.18 + Number(input.metabolites||4)*0.06 + Number(input.voxels||8)*0.02 + Number(input.NAA||1)*0.2'),('PediatricAmyloidPETExt','0.2 + Number(input.suvr||1.3)*0.3 + Number(input.drift||1)*0.1 + Number(input.centiloids||40)*0.008')],
'pcc_pediatric_surg_ext79':[('PediatricSEEGPlacementSurgExt','0.15 + Number(input.targets||8)*0.04 + Number(input.acc||95)*0.005 + Number(input.duration||4)*0.05'),('PediatricIntracranialGridSurgExt','0.2 + Number(input.grid||60)*0.006 + Number(input.duration||6)*0.04 + Number(input.complications||2)*0.05'),('PediatricDepthElecSurgExt','0.18 + Number(input.depths||10)*0.03 + Number(input.acc||95)*0.005 + Number(input.duration||3)*0.05'),('PediatricCraniotomyICEEGExt','0.2 + Number(input.approach||1)*0.2 + Number(input.bloodLoss||100)*0.001 + Number(input.icu||2)*0.05'),('PediatricBurrHoleSurgExt','0.15 + Number(input.holes||3)*0.05 + Number(input.acc||95)*0.005 + Number(input.complications||1)*0.1'),('PediatricVagalSurgLeadExt','0.18 + Number(input.age||10)*0.02 + Number(input.weight||25)*0.01 + Number(input.leadType||1)*0.1'),('PediatricRNSBurrHoleExt','0.2 + Number(input.leads||2)*0.15 + Number(input.burrHoles||2)*0.1 + Number(input.acc||96)*0.005'),('PediatricLaserProbeSurgExt','0.15 + Number(input.probes||2)*0.1 + Number(input.duration||2)*0.1 + Number(input.target||3)*0.05'),('PediatricHippocampalLaserExt','0.18 + Number(input.surgVol||3)*0.1 + Number(input.duration||2.5)*0.08 + Number(input.tiss||3)*0.05'),('PediatricStereoEEGExplSurgExt','0.18 + Number(input.electrodes||12)*0.03 + Number(input.acc||95)*0.005 + Number(input.duration||4)*0.05')]}

for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\n// {m} engine (deterministic)\nmodule.exports.version=\'v3.189.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.189.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}};}};\n'
    eng+=f'\n// TS: v3.189.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'// filepath: pcc/{m}/{m}_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;else console.error(\'FAIL\',fn,r);}}console.log(\'{m} unit:\',pass,\'passed\');if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'// filepath: pcc/{m}/{m}_integration_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{value:1}},{{value:2}},{{value:3}},{{value:4}},{{value:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass,\'passed\');if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'// filepath: pcc/{m}/{m}_routes.js\nconst express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();\nrouter.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.189.0\',functions:Object.keys(F)}}));\nrouter.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});\nrouter.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});\nmodule.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- pcc/{m}/{m}_up.sql\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\')\nBEGIN\nCREATE TABLE [dbo].[{m}] (\n  [id] INT IDENTITY(1,1) PRIMARY KEY,\n  [tenant_id] NVARCHAR(64) NOT NULL,\n  [version] NVARCHAR(16) NOT NULL,\n  [module] NVARCHAR(64) NOT NULL,\n  [function] NVARCHAR(128) NOT NULL,\n  [input] NVARCHAR(MAX) NULL,\n  [score] DECIMAL(6,2) NULL,\n  [ts] DATETIME2 DEFAULT SYSUTCDATETIME()\n);\nEND\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files written')
print('P3-II v3.189.0: 16 files written')
