import os
MODULES=['pcc_neurosurg_ext101','pcc_spinesurg_ext101','pcc_ctsurg_ext101']
FUNCS={
'pcc_neurosurg_ext101':[('NSCraniotomyExt','0.18 + Number(input.nsCraniotomy||1)*0.2 + Number(input.cranioInd||1)*0.2 + Number(input.outcome||1)*0.2'),('NSShuntExt','0.18 + Number(input.nsShunt||1)*0.2 + Number(input.shuntType||1)*0.2 + Number(input.outcome||1)*0.2'),('NSTumorResectExt','0.18 + Number(input.nsTumorRes||1)*0.2 + Number(input.tumorResExtent||1)*0.2 + Number(input.outcome||1)*0.2'),('NSVascularExt','0.18 + Number(input.nsVasc||1)*0.2 + Number(input.vascLesion||1)*0.2 + Number(input.outcome||1)*0.2'),('NSAneurysmExt','0.18 + Number(input.nsAneurysm||1)*0.2 + Number(input.aneurysmSize||1)*0.04 + Number(input.outcome||1)*0.2'),('NSAVMext','0.18 + Number(input.nsAVM||1)*0.2 + Number(input.avmGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('NSDBSext','0.18 + Number(input.nsDBS||1)*0.2 + Number(input.dbsTarget||1)*0.2 + Number(input.outcome||1)*0.2'),('NSVNSext','0.18 + Number(input.nsVNS||1)*0.2 + Number(input.vnsBattery||1)*0.04 + Number(input.outcome||1)*0.2'),('NSResectionEpilepsyExt','0.18 + Number(input.nsEpilepsySx||1)*0.2 + Number(input.epilepsyFocus||1)*0.2 + Number(input.outcome||1)*0.2'),('NSPedSurgeryExt','0.18 + Number(input.nsPedSx||1)*0.2 + Number(input.nsPedType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_spinesurg_ext101':[('SpineFusionExt','0.18 + Number(input.spFusion||1)*0.2 + Number(input.fusionLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('SpineDiscExt','0.18 + Number(input.spDisc||1)*0.2 + Number(input.discLevel||1)*0.2 + Number(input.outcome||1)*0.2'),('SpineLaminExt','0.18 + Number(input.spLamin||1)*0.2 + Number(input.laminLevels||1)*0.04 + Number(input.outcome||1)*0.2'),('SpineForaminExt','0.18 + Number(input.spForamin||1)*0.2 + Number(input.foraminSide||1)*0.2 + Number(input.outcome||1)*0.2'),('SpineScoliosisExt','0.18 + Number(input.spScoliosis||1)*0.2 + Number(input.cobbAngle||1)*0.04 + Number(input.outcome||1)*0.2'),('SpineFractureExt','0.18 + Number(input.spFracture||1)*0.2 + Number(input.fractureType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpineTumorExt','0.18 + Number(input.spTumor||1)*0.2 + Number(input.spineTumorType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpineInfectionExt','0.18 + Number(input.spInfection||1)*0.2 + Number(input.spineInfType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpineCordExt','0.18 + Number(input.spCord||1)*0.2 + Number(input.cordCompress||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinePedExt','0.18 + Number(input.spPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_ctsurg_ext101':[('CTThoracicExt','0.18 + Number(input.ctThoracic||1)*0.2 + Number(input.thoracicProc||1)*0.2 + Number(input.outcome||1)*0.2'),('CTLobectomyExt','0.18 + Number(input.ctLobectomy||1)*0.2 + Number(input.lobeResected||1)*0.2 + Number(input.outcome||1)*0.2'),('CTPneumonectomyExt','0.18 + Number(input.ctPneumon||1)*0.2 + Number(input.pneumonType||1)*0.2 + Number(input.outcome||1)*0.2'),('CTMediastinoscopyExt','0.18 + Number(input.ctMediast||1)*0.2 + Number(input.mediastFinding||1)*0.2 + Number(input.outcome||1)*0.2'),('CTEsophagectomyExt','0.18 + Number(input.ctEsoph||1)*0.2 + Number(input.esophApproach||1)*0.2 + Number(input.outcome||1)*0.2'),('CTTrachealExt','0.18 + Number(input.ctTracheal||1)*0.2 + Number(input.trachealProc||1)*0.2 + Number(input.outcome||1)*0.2'),('CTChestWallExt','0.18 + Number(input.ctChestWall||1)*0.2 + Number(input.chestWallProc||1)*0.2 + Number(input.outcome||1)*0.2'),('CTDiaphragmExt','0.18 + Number(input.ctDiaphragm||1)*0.2 + Number(input.diaphragmProc||1)*0.2 + Number(input.outcome||1)*0.2'),('CTTraumaExt','0.18 + Number(input.ctTrauma||1)*0.2 + Number(input.chestTraumaSev||1)*0.04 + Number(input.outcome||1)*0.2'),('CTPediatricExt','0.18 + Number(input.ctPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.32.32.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.32.32.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.32.32.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.32.32.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MF v3.32.32.0 done')