import os
MODULES=['pcc_nutrition_ext102','pcc_dietary_ext102','pcc_culinary_medicine_ext102']
FUNCS={
'pcc_nutrition_ext102':[('NutrGeneralExt','0.18 + Number(input.nuGen||1)*0.2 + Number(input.nuGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('NutrAssessmentExt','0.18 + Number(input.nuAss||1)*0.2 + Number(input.nuAssScore||1)*0.04 + Number(input.outcome||1)*0.2'),('NutrDeficiencyExt','0.18 + Number(input.nuDef||1)*0.2 + Number(input.nuDefType||1)*0.2 + Number(input.outcome||1)*0.2'),('NutrMacroExt','0.18 + Number(input.nuMac||1)*0.2 + Number(input.nuMacRatio||1)*0.04 + Number(input.outcome||1)*0.2'),('NutrMicroExt','0.18 + Number(input.nuMic||1)*0.2 + Number(input.nuMicType||1)*0.2 + Number(input.outcome||1)*0.2'),('NutrAllergyExt','0.18 + Number(input.nuAlg||1)*0.2 + Number(input.nuAlgType||1)*0.2 + Number(input.outcome||1)*0.2'),('NutrPediatricExt','0.18 + Number(input.nuPeds||1)*0.2 + Number(input.nuPedsType||1)*0.2 + Number(input.outcome||1)*0.2'),('NutrGeriatricExt','0.18 + Number(input.nuGeri||1)*0.2 + Number(input.nuGeriType||1)*0.2 + Number(input.outcome||1)*0.2'),('NutrEnteralExt','0.18 + Number(input.nuEnt||1)*0.2 + Number(input.nuEntType||1)*0.2 + Number(input.outcome||1)*0.2'),('NutrParenteralExt','0.18 + Number(input.nuPar||1)*0.2 + Number(input.nuParType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_dietary_ext102':[('DietPlanningExt','0.18 + Number(input.diPlan||1)*0.2 + Number(input.diPlanType||1)*0.2 + Number(input.outcome||1)*0.2'),('DietTherapeuticExt','0.18 + Number(input.diTher||1)*0.2 + Number(input.diTherType||1)*0.2 + Number(input.outcome||1)*0.2'),('DietDiabeticExt','0.18 + Number(input.diab||1)*0.2 + Number(input.diabCarbs||1)*0.04 + Number(input.outcome||1)*0.2'),('DietRenalExt','0.18 + Number(input.diRen||1)*0.2 + Number(input.diRenStage||1)*0.04 + Number(input.outcome||1)*0.2'),('DietCardiacExt','0.18 + Number(input.diCar||1)*0.2 + Number(input.diCarScore||1)*0.04 + Number(input.outcome||1)*0.2'),('DietCancerExt','0.18 + Number(input.diCanc||1)*0.2 + Number(input.diCancType||1)*0.2 + Number(input.outcome||1)*0.2'),('DietAllergyExt','0.18 + Number(input.diAlg||1)*0.2 + Number(input.diAlgType||1)*0.2 + Number(input.outcome||1)*0.2'),('DietPregnancyExt','0.18 + Number(input.diPreg||1)*0.2 + Number(input.diPregType||1)*0.2 + Number(input.outcome||1)*0.2'),('DietWeightExt','0.18 + Number(input.diWt||1)*0.2 + Number(input.diWtKg||1)*0.04 + Number(input.outcome||1)*0.2'),('DietSuppExt','0.18 + Number(input.diSup||1)*0.2 + Number(input.diSupType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_culinary_medicine_ext102':[('CulBasicExt','0.18 + Number(input.cuBas||1)*0.2 + Number(input.cuBasType||1)*0.2 + Number(input.outcome||1)*0.2'),('CulMediterraneanExt','0.18 + Number(input.cuMed||1)*0.2 + Number(input.cuMedScore||1)*0.04 + Number(input.outcome||1)*0.2'),('CulPlantExt','0.18 + Number(input.cuPl||1)*0.2 + Number(input.cuPlType||1)*0.2 + Number(input.outcome||1)*0.2'),('CulKetoExt','0.18 + Number(input.cuKeto||1)*0.2 + Number(input.cuKetoRatio||1)*0.04 + Number(input.outcome||1)*0.2'),('CulPaleoExt','0.18 + Number(input.cuPal||1)*0.2 + Number(input.cuPalType||1)*0.2 + Number(input.outcome||1)*0.2'),('CulDASHext','0.18 + Number(input.cuDash||1)*0.2 + Number(input.cuDashScore||1)*0.04 + Number(input.outcome||1)*0.2'),('CulFunctionalExt','0.18 + Number(input.cuFunc||1)*0.2 + Number(input.cuFuncType||1)*0.2 + Number(input.outcome||1)*0.2'),('CulCookingExt','0.18 + Number(input.cuCook||1)*0.2 + Number(input.cuCookType||1)*0.2 + Number(input.outcome||1)*0.2'),('CulHerbExt','0.18 + Number(input.cuHerb||1)*0.2 + Number(input.cuHerbType||1)*0.2 + Number(input.outcome||1)*0.2'),('CulSeasonalExt','0.18 + Number(input.cuSea||1)*0.2 + Number(input.cuSeaType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.49.49.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.49.49.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.49.49.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.49.49.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MW v3.49.49.0 done')