import os
MODULES=['pcc_neuro_ext106','pcc_pediatric_neuro_ext95','pcc_pediatric_surg_ext95']
FUNCS={
'pcc_neuro_ext106':[('VertebralArteryDissectExt','0.18 + Number(input.trauma||1)*0.2 + Number(input.dissection||1)*0.2 + Number(input.outcome||1)*0.2'),('CarotidArteryDissectExt','0.18 + Number(input.trauma||1)*0.2 + Number(input.dissection||1)*0.2 + Number(input.outcome||1)*0.2'),('IntracranialStentingExt','0.18 + Number(input.stenosis||70)*0.005 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('CerebralVenousStentingExt','0.18 + Number(input.stenosis||50)*0.005 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('CarotidBodyTumorExt','0.18 + Number(input.size||3)*0.1 + Number(input.vesselInvolve||1)*0.2 + Number(input.outcome||1)*0.2'),('MoyaMoyaPregnancyExt','0.18 + Number(input.week||20)*0.01 + Number(input.bypass||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokePregnancyExt','0.18 + Number(input.trimester||1)*0.1 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2'),('PostpartumStrokeExt','0.18 + Number(input.days||7)*0.04 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokePregnancyExt','0.18 + Number(input.age||15)*0.04 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2'),('NeonatalStrokeExt','0.18 + Number(input.days||3)*0.1 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext95':[('PediatricVertebralDissectExt','0.18 + Number(input.trauma||1)*0.2 + Number(input.dissection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCarotidDissectExt','0.18 + Number(input.trauma||1)*0.2 + Number(input.dissection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIntracranialStentExt','0.18 + Number(input.stenosis||70)*0.005 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVenousStentExt','0.18 + Number(input.stenosis||50)*0.005 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCarotidBodyTumorExt','0.18 + Number(input.size||3)*0.1 + Number(input.vessels||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMoyamoyaPregExt','0.18 + Number(input.age||15)*0.04 + Number(input.week||20)*0.01 + Number(input.outcome||1)*0.2'),('PediatricStrokePregExt','0.18 + Number(input.age||15)*0.04 + Number(input.trimester||1)*0.1 + Number(input.outcome||1)*0.2'),('PediatricPostpartumStrokeExt','0.18 + Number(input.days||7)*0.04 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2'),('NeonatalArterialStrokeExt','0.18 + Number(input.days||3)*0.1 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2'),('NeonatalCerebralVenousExt','0.18 + Number(input.days||5)*0.04 + Number(input.thrombosis||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext95':[('PediatricVertebralRepairExt','0.18 + Number(input.age||10)*0.04 + Number(input.repair||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCarotidRepairExt','0.18 + Number(input.age||10)*0.04 + Number(input.repair||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIntracranialStentSxExt','0.18 + Number(input.stenosis||70)*0.005 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVenousStentSxExt','0.18 + Number(input.stenosis||50)*0.005 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCarotidBodyTumorSxExt','0.18 + Number(input.size||3)*0.1 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMoyamoyaPregSxExt','0.18 + Number(input.age||15)*0.04 + Number(input.delivery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokePregSxExt','0.18 + Number(input.age||15)*0.04 + Number(input.cSection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPostpartumSxExt','0.18 + Number(input.days||7)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('NeonatalArterialRepairExt','0.18 + Number(input.days||3)*0.1 + Number(input.repair||1)*0.2 + Number(input.outcome||1)*0.2'),('NeonatalVenousRepairExt','0.18 + Number(input.days||5)*0.04 + Number(input.repair||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\n// {m} engine (deterministic)\nmodule.exports.version=\'v3.205.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.205.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}};}};\n'
    eng+=f'\n// TS: v3.205.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'// filepath: pcc/{m}/{m}_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;else console.error(\'FAIL\',fn,r);}}console.log(\'{m} unit:\',pass,\'passed\');if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'// filepath: pcc/{m}/{m}_integration_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{value:1}},{{value:2}},{{value:3}},{{value:4}},{{value:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass,\'passed\');if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'// filepath: pcc/{m}/{m}_routes.js\nconst express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();\nrouter.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.205.0\',functions:Object.keys(F)}}));\nrouter.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});\nrouter.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});\nmodule.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- pcc/{m}/{m}_up.sql\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\')\nBEGIN\nCREATE TABLE [dbo].[{m}] (\n  [id] INT IDENTITY(1,1) PRIMARY KEY,\n  [tenant_id] NVARCHAR(64) NOT NULL,\n  [version] NVARCHAR(16) NOT NULL,\n  [module] NVARCHAR(64) NOT NULL,\n  [function] NVARCHAR(128) NOT NULL,\n  [input] NVARCHAR(MAX) NULL,\n  [score] DECIMAL(6,2) NULL,\n  [ts] DATETIME2 DEFAULT SYSUTCDATETIME()\n);\nEND\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files written')
print('P3-IY v3.205.0: 15 files written')
