import os
MODULES=['pcc_derm_ext100','pcc_allergy_ext100','pcc_immunology_ext100']
FUNCS={
'pcc_derm_ext100':[('DermEczemaExt','0.18 + Number(input.dermEczema||1)*0.2 + Number(input.easiScore||1)*0.04 + Number(input.outcome||1)*0.2'),('DermPsoriasisExt','0.18 + Number(input.dermPsor||1)*0.2 + Number(input.pasiScore||1)*0.04 + Number(input.outcome||1)*0.2'),('DermAcneExt','0.18 + Number(input.dermAcne||1)*0.2 + Number(input.acneGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('DermMelanomaExt','0.18 + Number(input.dermMelanoma||1)*0.2 + Number(input.breslow||1)*0.04 + Number(input.outcome||1)*0.2'),('DermBCCext','0.18 + Number(input.dermBCC||1)*0.2 + Number(input.bccType||1)*0.2 + Number(input.outcome||1)*0.2'),('DermSCCext','0.18 + Number(input.dermSCC||1)*0.2 + Number(input.sccGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('DermDrugExt','0.18 + Number(input.dermDrug||1)*0.2 + Number(input.drugType||1)*0.2 + Number(input.outcome||1)*0.2'),('DermAutoimmuneExt','0.18 + Number(input.dermAuto||1)*0.2 + Number(input.autoSkinAb||1)*0.2 + Number(input.outcome||1)*0.2'),('DermInfectionExt','0.18 + Number(input.dermInf||1)*0.2 + Number(input.dermPathogen||1)*0.2 + Number(input.outcome||1)*0.2'),('DermBurnExt','0.18 + Number(input.dermBurn||1)*0.2 + Number(input.tbsaDerm||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_allergy_ext100':[('AllergicRhinitisExt','0.18 + Number(input.allRhinitis||1)*0.2 + Number(input.igeTotal||1)*0.04 + Number(input.outcome||1)*0.2'),('AllergicAsthmaExt','0.18 + Number(input.allAsthma||1)*0.2 + Number(input.fev1All||1)*0.04 + Number(input.outcome||1)*0.2'),('AllergicFoodExt','0.18 + Number(input.allFood||1)*0.2 + Number(input.foodIgE||1)*0.04 + Number(input.outcome||1)*0.2'),('AllergicDrugExt','0.18 + Number(input.allDrug||1)*0.2 + Number(input.drugAllergy||1)*0.2 + Number(input.outcome||1)*0.2'),('AllergicUrticariaExt','0.18 + Number(input.allUrticaria||1)*0.2 + Number(input.uasScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AllergicAnaphylaxisExt','0.18 + Number(input.allAnaphyl||1)*0.2 + Number(input.trypLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('AllergicContactExt','0.18 + Number(input.allContact||1)*0.2 + Number(input.patchResult||1)*0.2 + Number(input.outcome||1)*0.2'),('AllergicVenomExt','0.18 + Number(input.allVenom||1)*0.2 + Number(input.venomIgE||1)*0.04 + Number(input.outcome||1)*0.2'),('AllergicLatexExt','0.18 + Number(input.allLatex||1)*0.2 + Number(input.latexIgE||1)*0.04 + Number(input.outcome||1)*0.2'),('AllergicImmunotherapyExt','0.18 + Number(input.allImmuno||1)*0.2 + Number(input.immunoType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_immunology_ext100':[('ImmunoPIDext','0.18 + Number(input.immPID||1)*0.2 + Number(input.pidType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmunoIgADefExt','0.18 + Number(input.immIgA||1)*0.2 + Number(input.igaLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('ImmunoCVIDExt','0.18 + Number(input.immCVID||1)*0.2 + Number(input.iggLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('ImmunoSCIDext','0.18 + Number(input.immSCID||1)*0.2 + Number(input.tcellCount||1)*0.04 + Number(input.outcome||1)*0.2'),('ImmunoComplementExt','0.18 + Number(input.immCompl||1)*0.2 + Number(input.c3Level||1)*0.04 + Number(input.outcome||1)*0.2'),('ImmunoAutoImmuneExt','0.18 + Number(input.immAuto||1)*0.2 + Number(input.autoAbType||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmunoTransplantRejExt','0.18 + Number(input.immTxRej||1)*0.2 + Number(input.rejGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('ImmunoGVHDeXt','0.18 + Number(input.immGVHD||1)*0.2 + Number(input.gvhdGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('ImmunoBiologicExt','0.18 + Number(input.immBiologic||1)*0.2 + Number(input.biolAgent||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmunoVaccineRespExt','0.18 + Number(input.immVaccResp||1)*0.2 + Number(input.vaccAbTiter||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.22.22.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.22.22.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.22.22.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.22.22.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LV v3.22.22.0 done')