import os
MODULES=['pcc_neuro_ext179','pcc_pediatric_neuro_ext168','pcc_pediatric_surg_ext168']
FUNCS={
'pcc_neuro_ext179':[('NeuroRehabStrokeExt','0.18 + Number(input.strokeRehabNeuro||1)*0.2 + Number(input.fuglmeyer||1)*0.04 + Number(input.outcome||1)*0.2'),('ConstraintInducedExt','0.18 + Number(input.cit||1)*0.2 + Number(input.motorDeficit||1)*0.2 + Number(input.outcome||1)*0.2'),('RobotRehabExt','0.18 + Number(input.robotRehab||1)*0.2 + Number(input.gait||1)*0.2 + Number(input.outcome||1)*0.2'),('BWSTText','0.18 + Number(input.bwstt||1)*0.2 + Number(input.spinalInjury||1)*0.2 + Number(input.outcome||1)*0.2'),('FESext','0.18 + Number(input.fes||1)*0.2 + Number(input.dropFoot||1)*0.2 + Number(input.outcome||1)*0.2'),('VRrehabExt','0.18 + Number(input.vr||1)*0.2 + Number(input.strokeVR||1)*0.2 + Number(input.outcome||1)*0.2'),('TelerehabExt','0.18 + Number(input.telerehab||1)*0.2 + Number(input.remoteRx||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuroplasticityExt','0.18 + Number(input.neuroplastic||1)*0.2 + Number(input.intensity||1)*0.2 + Number(input.outcome||1)*0.2'),('SpasticityMgtExt','0.18 + Number(input.spasticityMgt||1)*0.2 + Number(input.masScore||1)*0.04 + Number(input.outcome||1)*0.2'),('DysphagiaMgtExt','0.18 + Number(input.dysphagiaMgt||1)*0.2 + Number(input.foIS||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext168':[('PediatricCIMText','0.18 + Number(input.age||5)*0.04 + Number(input.pCIMT||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCPRehabExt','0.18 + Number(input.age||3)*0.04 + Number(input.pCPRehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeurorehabExt','0.18 + Number(input.age||5)*0.04 + Number(input.pNeurorehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRobotRehabExt','0.18 + Number(input.age||5)*0.04 + Number(input.pRobotRehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVRrehabExt','0.18 + Number(input.age||8)*0.04 + Number(input.pVR||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTelerehabExt','0.18 + Number(input.age||8)*0.04 + Number(input.pTelerehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpasticityMgtExt','0.18 + Number(input.age||3)*0.04 + Number(input.pSpast||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDysphagiaMgtExt','0.18 + Number(input.age||1)*0.04 + Number(input.pDysph||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricConstraintExt','0.18 + Number(input.age||3)*0.04 + Number(input.pConstraint||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHandTherapyExt','0.18 + Number(input.age||5)*0.04 + Number(input.pHandTx||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext168':[('PediatricCIMTTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.cimtTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCPRehabTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.cpRehabTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeurorehabTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.neurorehabTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRobotRehabTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.robotRehabTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVRrehabTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.vrRehabTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTelerehabTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.telerehabTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpasticityTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.spastTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDysphagiaTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.dysphTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricConstraintTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.constraintTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHandTherapyTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.handTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.1.8.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.1.8.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.1.8.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.1.8.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-AH v3.1.8.0 done')