import os
MODULES=['pcc_obstetrics_ext102','pcc_gynecology_ext102','pcc_midwifery_ext102']
FUNCS={
'pcc_obstetrics_ext102':[('ObsGenExt','0.18 + Number(input.obGen||1)*0.2 + Number(input.obGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('ObsAntenatalExt','0.18 + Number(input.obAnt||1)*0.2 + Number(input.obAntWeek||1)*0.04 + Number(input.outcome||1)*0.2'),('ObsLaborExt','0.18 + Number(input.obLab||1)*0.2 + Number(input.obLabStage||1)*0.04 + Number(input.outcome||1)*0.2'),('ObsDeliveryExt','0.18 + Number(input.obDel||1)*0.2 + Number(input.obDelType||1)*0.2 + Number(input.outcome||1)*0.2'),('ObsPostpartumExt','0.18 + Number(input.obPP||1)*0.2 + Number(input.obPPDay||1)*0.04 + Number(input.outcome||1)*0.2'),('ObsHighRiskExt','0.18 + Number(input.obHR||1)*0.2 + Number(input.obHRScore||1)*0.04 + Number(input.outcome||1)*0.2'),('ObsGDMext','0.18 + Number(input.obGDM||1)*0.2 + Number(input.obGDMScore||1)*0.04 + Number(input.outcome||1)*0.2'),('ObsPreeclExt','0.18 + Number(input.obPE||1)*0.2 + Number(input.obPEScore||1)*0.04 + Number(input.outcome||1)*0.2'),('ObsFetalExt','0.18 + Number(input.obFM||1)*0.2 + Number(input.obFMType||1)*0.2 + Number(input.outcome||1)*0.2'),('ObsInfertilityExt','0.18 + Number(input.obIF||1)*0.2 + Number(input.obIFType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_gynecology_ext102':[('GynGenExt','0.18 + Number(input.gyGen||1)*0.2 + Number(input.gyGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('GynMensExt','0.18 + Number(input.gyMen||1)*0.2 + Number(input.gyMenScore||1)*0.04 + Number(input.outcome||1)*0.2'),('GynEndoExt','0.18 + Number(input.gyEnd||1)*0.2 + Number(input.gyEndStage||1)*0.04 + Number(input.outcome||1)*0.2'),('GynPCOSext','0.18 + Number(input.gyPCOS||1)*0.2 + Number(input.gyPCOSscore||1)*0.04 + Number(input.outcome||1)*0.2'),('GynFibExt','0.18 + Number(input.gyFib||1)*0.2 + Number(input.gyFibSize||1)*0.04 + Number(input.outcome||1)*0.2'),('GynOvarExt','0.18 + Number(input.gyOv||1)*0.2 + Number(input.gyOvType||1)*0.2 + Number(input.outcome||1)*0.2'),('GynCerExt','0.18 + Number(input.gyCer||1)*0.2 + Number(input.gyCerScore||1)*0.04 + Number(input.outcome||1)*0.2'),('GynHPVext','0.18 + Number(input.gyHPV||1)*0.2 + Number(input.gyHPVType||1)*0.2 + Number(input.outcome||1)*0.2'),('GynIncontExt','0.18 + Number(input.gyIncon||1)*0.2 + Number(input.gyInconType||1)*0.2 + Number(input.outcome||1)*0.2'),('GynProlapseExt','0.18 + Number(input.gyProl||1)*0.2 + Number(input.gyProlStage||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_midwifery_ext102':[('MidGenExt','0.18 + Number(input.mwGen||1)*0.2 + Number(input.mwGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('MidPrenatalExt','0.18 + Number(input.mwPre||1)*0.2 + Number(input.mwPreWeek||1)*0.04 + Number(input.outcome||1)*0.2'),('MidBirthExt','0.18 + Number(input.mwBir||1)*0.2 + Number(input.mwBirType||1)*0.2 + Number(input.outcome||1)*0.2'),('MidPostnatalExt','0.18 + Number(input.mwPost||1)*0.2 + Number(input.mwPostDay||1)*0.04 + Number(input.outcome||1)*0.2'),('MidLactationExt','0.18 + Number(input.mwLac||1)*0.2 + Number(input.mwLacScore||1)*0.04 + Number(input.outcome||1)*0.2'),('MidNewbornExt','0.18 + Number(input.mwNB||1)*0.2 + Number(input.mwNBDay||1)*0.04 + Number(input.outcome||1)*0.2'),('MidHomeExt','0.18 + Number(input.mwHome||1)*0.2 + Number(input.mwHomeType||1)*0.2 + Number(input.outcome||1)*0.2'),('MidWaterExt','0.18 + Number(input.mwWat||1)*0.2 + Number(input.mwWatScore||1)*0.04 + Number(input.outcome||1)*0.2'),('MidVBACext','0.18 + Number(input.mwVBAC||1)*0.2 + Number(input.mwVBACtype||1)*0.2 + Number(input.outcome||1)*0.2'),('MidEmergencyExt','0.18 + Number(input.mwEm||1)*0.2 + Number(input.mwEmType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.67.67.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.67.67.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.67.67.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.67.67.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NO v3.67.67.0 done')