import os
MODULES=['pcc_neuro_ext151','pcc_pediatric_neuro_ext140','pcc_pediatric_surg_ext140']
FUNCS={
'pcc_neuro_ext151':[('MyastheniaCrisisExt','0.18 + Number(input.mg||1)*0.2 + Number(input.crisis||1)*0.2 + Number(input.outcome||1)*0.2'),('LambertEatonExt','0.18 + Number(input.lems||1)*0.2 + Number(input.weakness||1)*0.2 + Number(input.outcome||1)*0.2'),('CIDPext','0.18 + Number(input.cidp||1)*0.2 + Number(input.demyelinating||1)*0.2 + Number(input.outcome||1)*0.2'),('GuillainBarreExt','0.18 + Number(input.gbs||1)*0.2 + Number(input.ascending||1)*0.2 + Number(input.outcome||1)*0.2'),('MillerFisherExt','0.18 + Number(input.mfs||1)*0.2 + Number(input.opthalmoplegia||1)*0.2 + Number(input.outcome||1)*0.2'),('BotulismExt','0.18 + Number(input.botulism||1)*0.2 + Number(input.descending||1)*0.2 + Number(input.outcome||1)*0.2'),('PolymyositisExt','0.18 + Number(input.pm||1)*0.2 + Number(input.proximal||1)*0.2 + Number(input.outcome||1)*0.2'),('DermatomyositisExt','0.18 + Number(input.dm||1)*0.2 + Number(input.heliotrope||1)*0.2 + Number(input.outcome||1)*0.2'),('InclusionBodyExt','0.18 + Number(input.ibm||1)*0.2 + Number(input.inclusion||1)*0.2 + Number(input.outcome||1)*0.2'),('MyotonicDystrophyExt','0.18 + Number(input.dm1||1)*0.2 + Number(input.myotonia||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext140':[('PediatricMGcrisisExt','0.18 + Number(input.age||8)*0.04 + Number(input.mgCrisis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGBSchildExt','0.18 + Number(input.age||5)*0.04 + Number(input.gbs||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBotulismExt','0.18 + Number(input.age||1)*0.04 + Number(input.infantBot||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDermatomyositisExt','0.18 + Number(input.age||8)*0.04 + Number(input.jdm||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDuchenneExt','0.18 + Number(input.age||5)*0.04 + Number(input.dmd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBeckersExt','0.18 + Number(input.age||5)*0.04 + Number(input.bmd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMAtype1Ext','0.18 + Number(input.age||0)*0.04 + Number(input.sma1||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMAtype2Ext','0.18 + Number(input.age||1)*0.04 + Number(input.sma2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCMText','0.18 + Number(input.age||1)*0.04 + Number(input.cmt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMyastheniaExt','0.18 + Number(input.age||3)*0.04 + Number(input.mg||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext140':[('PediatricMGCriSupportExt','0.18 + Number(input.age||8)*0.04 + Number(input.support||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGBSTherapyExt','0.18 + Number(input.age||5)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBotulismSupportExt','0.18 + Number(input.age||1)*0.04 + Number(input.supportBot||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricJDMsteroidExt','0.18 + Number(input.age||8)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDMDsteroidExt','0.18 + Number(input.age||5)*0.04 + Number(input.prednisone||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBMDSteroidExt','0.18 + Number(input.age||5)*0.04 + Number(input.bmdSteroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMA1geneTxExt','0.18 + Number(input.age||0)*0.04 + Number(input.zolgensma||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSMA2nusinersenExt','0.18 + Number(input.age||1)*0.04 + Number(input.nusinersen||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCMTPTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMGPsupportExt','0.18 + Number(input.age||3)*0.04 + Number(input.pyridostigmine||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.250.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.250.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.250.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.250.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KR v3.250.0 done')