import os
MODULES=['pcc_nursing_ext102','pcc_midwifery_nurse_ext102','pcc_nurse_practitioner_ext102']
FUNCS={
'pcc_nursing_ext102':[('NurGenExt','0.18 + Number(input.nrGen||1)*0.2 + Number(input.nrGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('NurAssessExt','0.18 + Number(input.nrAs||1)*0.2 + Number(input.nrAsScore||1)*0.04 + Number(input.outcome||1)*0.2'),('NurPlanExt','0.18 + Number(input.nrPl||1)*0.2 + Number(input.nrPlType||1)*0.2 + Number(input.outcome||1)*0.2'),('NurImplementExt','0.18 + Number(input.nrImp||1)*0.2 + Number(input.nrImpType||1)*0.2 + Number(input.outcome||1)*0.2'),('NurEvalExt','0.18 + Number(input.nrEv||1)*0.2 + Number(input.nrEvScore||1)*0.04 + Number(input.outcome||1)*0.2'),('NurMedExt','0.18 + Number(input.nrMed||1)*0.2 + Number(input.nrMedScore||1)*0.04 + Number(input.outcome||1)*0.2'),('NurWoundExt','0.18 + Number(input.nrWou||1)*0.2 + Number(input.nrWouType||1)*0.2 + Number(input.outcome||1)*0.2'),('NurIVext','0.18 + Number(input.nrIV||1)*0.2 + Number(input.nrIVtype||1)*0.2 + Number(input.outcome||1)*0.2'),('NurHandoffExt','0.18 + Number(input.nrHo||1)*0.2 + Number(input.nrHoScore||1)*0.04 + Number(input.outcome||1)*0.2'),('NurEducExt','0.18 + Number(input.nrEd||1)*0.2 + Number(input.nrEdType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_midwifery_nurse_ext102':[('MWNurseGenExt','0.18 + Number(input.mnGen||1)*0.2 + Number(input.mnGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('MWNurseAntenExt','0.18 + Number(input.mnAnt||1)*0.2 + Number(input.mnAntWeek||1)*0.04 + Number(input.outcome||1)*0.2'),('MWNurseIntrapartExt','0.18 + Number(input.mnIntra||1)*0.2 + Number(input.mnIntraStage||1)*0.04 + Number(input.outcome||1)*0.2'),('MWNursePostExt','0.18 + Number(input.mnPost||1)*0.2 + Number(input.mnPostDay||1)*0.04 + Number(input.outcome||1)*0.2'),('MWNurseNewbornExt','0.18 + Number(input.mnNB||1)*0.2 + Number(input.mnNBDay||1)*0.04 + Number(input.outcome||1)*0.2'),('MWNurseBFext','0.18 + Number(input.mnBF||1)*0.2 + Number(input.mnBFscore||1)*0.04 + Number(input.outcome||1)*0.2'),('MWNurseGYNExt','0.18 + Number(input.mnGyn||1)*0.2 + Number(input.mnGynType||1)*0.2 + Number(input.outcome||1)*0.2'),('MWNurseScreenExt','0.18 + Number(input.mnScr||1)*0.2 + Number(input.mnScrType||1)*0.2 + Number(input.outcome||1)*0.2'),('MWNurseCommExt','0.18 + Number(input.mnCom||1)*0.2 + Number(input.mnComType||1)*0.2 + Number(input.outcome||1)*0.2'),('MWNurseOutreachExt','0.18 + Number(input.mnOut||1)*0.2 + Number(input.mnOutType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_nurse_practitioner_ext102':[('NPGenExt','0.18 + Number(input.npGen||1)*0.2 + Number(input.npGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('NPAssessExt','0.18 + Number(input.npAs||1)*0.2 + Number(input.npAsScore||1)*0.04 + Number(input.outcome||1)*0.2'),('NPDiagnosisExt','0.18 + Number(input.npDx||1)*0.2 + Number(input.npDxScore||1)*0.04 + Number(input.outcome||1)*0.2'),('NPTreatExt','0.18 + Number(input.npTx||1)*0.2 + Number(input.npTxType||1)*0.2 + Number(input.outcome||1)*0.2'),('NPRxExt','0.18 + Number(input.npRx||1)*0.2 + Number(input.npRxType||1)*0.2 + Number(input.outcome||1)*0.2'),('NPFollowExt','0.18 + Number(input.npFo||1)*0.2 + Number(input.npFoScore||1)*0.04 + Number(input.outcome||1)*0.2'),('NPEduExt','0.18 + Number(input.npEd||1)*0.2 + Number(input.npEdType||1)*0.2 + Number(input.outcome||1)*0.2'),('NPConsultExt','0.18 + Number(input.npCo||1)*0.2 + Number(input.npCoType||1)*0.2 + Number(input.outcome||1)*0.2'),('NPSpecialtyExt','0.18 + Number(input.npSp||1)*0.2 + Number(input.npSpType||1)*0.2 + Number(input.outcome||1)*0.2'),('NPQualityExt','0.18 + Number(input.npQ||1)*0.2 + Number(input.npQScore||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.73.73.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.73.73.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.73.73.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.73.73.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NU v3.73.73.0 done')