import os
MODULES=['pcc_neuro_ext176','pcc_pediatric_neuro_ext165','pcc_pediatric_surg_ext165']
FUNCS={
'pcc_neuro_ext176':[('NeuroPsychSurgeryExt','0.18 + Number(input.psSurg||1)*0.2 + Number(input.target||1)*0.2 + Number(input.outcome||1)*0.2'),('CapsulotomyExt','0.18 + Number(input.capsulotomy||1)*0.2 + Number(input.ocdTarget||1)*0.2 + Number(input.outcome||1)*0.2'),('CingulotomyExt','0.18 + Number(input.cingulotomy||1)*0.2 + Number(input.depressionTarget||1)*0.2 + Number(input.outcome||1)*0.2'),('SubthalamotomyExt','0.18 + Number(input.subthalamotomy||1)*0.2 + Number(input.parkTarget||1)*0.2 + Number(input.outcome||1)*0.2'),('PallidotomyExt','0.18 + Number(input.pallidotomy||1)*0.2 + Number(input.dystoniaTarget||1)*0.2 + Number(input.outcome||1)*0.2'),('ThalamotomyExt','0.18 + Number(input.thalamotomy||1)*0.2 + Number(input.tremorTarget||1)*0.2 + Number(input.outcome||1)*0.2'),('LobotomyExt','0.18 + Number(input.lobotomy||1)*0.2 + Number(input.historical||1)*0.2 + Number(input.outcome||1)*0.2'),('CordotomyExt','0.18 + Number(input.cordotomy||1)*0.2 + Number(input.cancerPain||1)*0.2 + Number(input.outcome||1)*0.2'),('CommissurotomyExt','0.18 + Number(input.commissurotomy||1)*0.2 + Number(input.epilepsyTarget||1)*0.2 + Number(input.outcome||1)*0.2'),('DREZprocedureExt','0.18 + Number(input.drez||1)*0.2 + Number(input.painTarget||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext165':[('PediatricHemispherExt','0.18 + Number(input.age||3)*0.04 + Number(input.pHemispher||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVNSpedExt','0.18 + Number(input.age||5)*0.04 + Number(input.pVNSped||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDBSpedExt','0.18 + Number(input.age||8)*0.04 + Number(input.pDBSped||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCallosotomyExt','0.18 + Number(input.age||5)*0.04 + Number(input.pCalloso||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLesionectomyExt','0.18 + Number(input.age||8)*0.04 + Number(input.pLesion||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLaserAblationExt','0.18 + Number(input.age||3)*0.04 + Number(input.pLaserAbl||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRFablationExt','0.18 + Number(input.age||5)*0.04 + Number(input.pRFablation||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLITTepilepsyExt','0.18 + Number(input.age||5)*0.04 + Number(input.pLITT||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStereotacticExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStereo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricECOGguidedExt','0.18 + Number(input.age||5)*0.04 + Number(input.pECOG||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext165':[('PediatricHemispherSxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pHemispherSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVNSpedSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pVNSpedSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDBSpedSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pDBSpedSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCallosoSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pCallosoSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLesionSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pLesionSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLaserAblSxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pLaserAblSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRFablationSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pRFablSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLITTSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pLITTSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStereoSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStereoSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricECOGguidedSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pECOGSx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.1.5.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.1.5.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.1.5.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.1.5.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-AE v3.1.5.0 done')