import os
MODULES=['pcc_neuro_ext142','pcc_pediatric_neuro_ext131','pcc_pediatric_surg_ext131']
FUNCS={
'pcc_neuro_ext142':[('VitaminB12DeficiencyExt','0.18 + Number(input.macrocytic||1)*0.2 + Number(input.neuropathy||1)*0.2 + Number(input.outcome||1)*0.2'),('FolicAcidDeficiencyExt','0.18 + Number(input.folate||1)*0.2 + Number(input.macrocytic||1)*0.2 + Number(input.outcome||1)*0.2'),('ThiamineDeficiencyExt','0.18 + Number(input.thiamine||1)*0.2 + Number(input.beriberi||1)*0.2 + Number(input.outcome||1)*0.2'),('NiacinDeficiencyExt','0.18 + Number(input.niacin||1)*0.2 + Number(input.pellagra||1)*0.2 + Number(input.outcome||1)*0.2'),('PyridoxineDeficiencyExt','0.18 + Number(input.b6||1)*0.2 + Number(input.neuropathy||1)*0.2 + Number(input.outcome||1)*0.2'),('VitaminDExt','0.18 + Number(input.vitD||1)*0.2 + Number(input.osteomalacia||1)*0.2 + Number(input.outcome||1)*0.2'),('VitaminEExt','0.18 + Number(input.vitE||1)*0.2 + Number(input.neuropathy||1)*0.2 + Number(input.outcome||1)*0.2'),('CopperDeficiencyExt','0.18 + Number(input.copper||1)*0.2 + Number(input.myeloneuropathy||1)*0.2 + Number(input.outcome||1)*0.2'),('ZincDeficiencyExt','0.18 + Number(input.zinc||1)*0.2 + Number(input.skin||1)*0.2 + Number(input.outcome||1)*0.2'),('SeleniumDeficiencyExt','0.18 + Number(input.selenium||1)*0.2 + Number(input.keshan||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext131':[('PediatricB12DeficiencyExt','0.18 + Number(input.age||5)*0.04 + Number(input.b12||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFolateDeficiencyExt','0.18 + Number(input.age||5)*0.04 + Number(input.folate||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricThiamineDeficiencyExt','0.18 + Number(input.age||5)*0.04 + Number(input.thiamine||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNiacinDeficiencyExt','0.18 + Number(input.age||5)*0.04 + Number(input.niacin||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricB6DeficiencyExt','0.18 + Number(input.age||5)*0.04 + Number(input.b6||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVitDDeficiencyExt','0.18 + Number(input.age||5)*0.04 + Number(input.vitD||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVitEDeficiencyExt','0.18 + Number(input.age||5)*0.04 + Number(input.vitE||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCopperDeficiencyExt','0.18 + Number(input.age||5)*0.04 + Number(input.copper||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricZincDeficiencyExt','0.18 + Number(input.age||5)*0.04 + Number(input.zinc||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSeleniumDeficiencyExt','0.18 + Number(input.age||5)*0.04 + Number(input.selenium||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext131':[('PediatricB12ReplExt','0.18 + Number(input.age||5)*0.04 + Number(input.b12Replace||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFolateReplExt','0.18 + Number(input.age||5)*0.04 + Number(input.folateReplace||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricThiamineReplExt','0.18 + Number(input.age||5)*0.04 + Number(input.thiamineReplace||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNiacinReplExt','0.18 + Number(input.age||5)*0.04 + Number(input.niacinReplace||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricB6ReplExt','0.18 + Number(input.age||5)*0.04 + Number(input.b6Replace||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVitDReplExt','0.18 + Number(input.age||5)*0.04 + Number(input.vitDReplace||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVitEReplExt','0.18 + Number(input.age||5)*0.04 + Number(input.vitEReplace||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCopperReplExt','0.18 + Number(input.age||5)*0.04 + Number(input.copperReplace||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricZincReplExt','0.18 + Number(input.age||5)*0.04 + Number(input.zincReplace||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSeleniumReplExt','0.18 + Number(input.age||5)*0.04 + Number(input.seleniumReplace||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.241.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.241.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.241.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.241.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KI v3.241.0 done')
