import os
MODULES=['pcc_pulmonology_ext102','pcc_thoracic_surgery_ext102','pcc_respiratory_ext102']
FUNCS={
'pcc_pulmonology_ext102':[('PulmGenExt','0.18 + Number(input.plGen||1)*0.2 + Number(input.plGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('PulmAsthmaExt','0.18 + Number(input.plAst||1)*0.2 + Number(input.plAstScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PulmCOPDext','0.18 + Number(input.plCOPD||1)*0.2 + Number(input.plCOPDFEV1||1)*0.04 + Number(input.outcome||1)*0.2'),('PulmPneumExt','0.18 + Number(input.plPneu||1)*0.2 + Number(input.plPneuType||1)*0.2 + Number(input.outcome||1)*0.2'),('PulmTBext','0.18 + Number(input.plTB||1)*0.2 + Number(input.plTBType||1)*0.2 + Number(input.outcome||1)*0.2'),('PulmCancerExt','0.18 + Number(input.plCan||1)*0.2 + Number(input.plCanStage||1)*0.04 + Number(input.outcome||1)*0.2'),('PulmILDext','0.18 + Number(input.plILD||1)*0.2 + Number(input.plILDType||1)*0.2 + Number(input.outcome||1)*0.2'),('PulmPHTnext','0.18 + Number(input.plPH||1)*0.2 + Number(input.plPHscore||1)*0.04 + Number(input.outcome||1)*0.2'),('PulmPleuralExt','0.18 + Number(input.plPleu||1)*0.2 + Number(input.plPleuType||1)*0.2 + Number(input.outcome||1)*0.2'),('PulmSleepExt','0.18 + Number(input.plSleep||1)*0.2 + Number(input.plSleepAHI||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_thoracic_surgery_ext102':[('TSxGenExt','0.18 + Number(input.tsGen||1)*0.2 + Number(input.tsGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('TSxLobExt','0.18 + Number(input.tsLob||1)*0.2 + Number(input.tsLobType||1)*0.2 + Number(input.outcome||1)*0.2'),('TSxPneumExt','0.18 + Number(input.tsPneu||1)*0.2 + Number(input.tsPneuType||1)*0.2 + Number(input.outcome||1)*0.2'),('TSxEsophExt','0.18 + Number(input.tsEso||1)*0.2 + Number(input.tsEsoType||1)*0.2 + Number(input.outcome||1)*0.2'),('TSxMediastExt','0.18 + Number(input.tsMed||1)*0.2 + Number(input.tsMedType||1)*0.2 + Number(input.outcome||1)*0.2'),('TSxChestWallExt','0.18 + Number(input.tsCW||1)*0.2 + Number(input.tsCWType||1)*0.2 + Number(input.outcome||1)*0.2'),('TSxVATSext','0.18 + Number(input.tsVATS||1)*0.2 + Number(input.tsVATSscore||1)*0.04 + Number(input.outcome||1)*0.2'),('TSxTrachExt','0.18 + Number(input.tsTra||1)*0.2 + Number(input.tsTraType||1)*0.2 + Number(input.outcome||1)*0.2'),('TSxDiaphExt','0.18 + Number(input.tsDia||1)*0.2 + Number(input.tsDiaType||1)*0.2 + Number(input.outcome||1)*0.2'),('TSxPostExt','0.18 + Number(input.tsPost||1)*0.2 + Number(input.tsPostDay||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_respiratory_ext102':[('RespGenExt','0.18 + Number(input.rsGen||1)*0.2 + Number(input.rsGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('RespVentExt','0.18 + Number(input.rsVent||1)*0.2 + Number(input.rsVentMode||1)*0.2 + Number(input.outcome||1)*0.2'),('RespOxygenExt','0.18 + Number(input.rsO2||1)*0.2 + Number(input.rsO2FiO2||1)*0.04 + Number(input.outcome||1)*0.2'),('RespWeaningExt','0.18 + Number(input.rsWean||1)*0.2 + Number(input.rsWeanScore||1)*0.04 + Number(input.outcome||1)*0.2'),('RespTrachExt','0.18 + Number(input.rsTrach||1)*0.2 + Number(input.rsTrachType||1)*0.2 + Number(input.outcome||1)*0.2'),('RespPFText','0.18 + Number(input.rsPFT||1)*0.2 + Number(input.rsPFTScore||1)*0.04 + Number(input.outcome||1)*0.2'),('RespABGext','0.18 + Number(input.rsABG||1)*0.2 + Number(input.rsABGtype||1)*0.2 + Number(input.outcome||1)*0.2'),('RespRehabExt','0.18 + Number(input.rsReh||1)*0.2 + Number(input.rsRehScore||1)*0.04 + Number(input.outcome||1)*0.2'),('RespHomeExt','0.18 + Number(input.rsHome||1)*0.2 + Number(input.rsHomeType||1)*0.2 + Number(input.outcome||1)*0.2'),('RespFailureExt','0.18 + Number(input.rsFail||1)*0.2 + Number(input.rsFailScore||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.55.55.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.55.55.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.55.55.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.55.55.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NC v3.55.55.0 done')