import os
MODULES=['pcc_neuro_ext104','pcc_pediatric_neuro_ext93','pcc_pediatric_surg_ext93']
FUNCS={
'pcc_neuro_ext104':[('TelestrokeDripAndShipExt','0.15 + Number(input.distance||50)*0.005 + Number(input.lkw||3)*0.05 + Number(input.ship||1)*0.2'),('StrokeMimicExt','0.15 + Number(input.headache||1)*0.15 + Number(input.seizure||1)*0.15 + Number(input.toxicology||1)*0.2'),('StrokeCenterLevelEvalExt','0.15 + Number(input.csc||1)*0.2 + Number(input.tsc||1)*0.15 + Number(input.asc||1)*0.1'),('AcuteStrokeRehabExt','0.15 + Number(input.days||7)*0.04 + Number(input.intensity||3)*0.1 + Number(input.gain||10)*0.04'),('StrokeSecondaryPreventionExt','0.15 + Number(input.cause||1)*0.2 + Number(input.antiplatelet||1)*0.15 + Number(input.statins||1)*0.15'),('CarotidEndarterectomyEvalExt','0.18 + Number(input.stenosis||80)*0.005 + Number(input.symptom||1)*0.2 + Number(input.risk||2)*0.1'),('CryptogenicStrokeWorkupExt','0.15 + Number(input.pfo||1)*0.2 + Number(input.hypercoag||1)*0.2 + Number(input.afibBurst||1)*0.2'),('CerebralVenousThrombExt','0.18 + Number(input.location||2)*0.1 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokeInYoungExt','0.18 + Number(input.age||40)*0.005 + Number(input.workup||3)*0.05 + Number(input.outcome||1)*0.2'),('StrokeRecoveryLongTermExt','0.15 + Number(input.months||24)*0.005 + Number(input.therapy||3)*0.05 + Number(input.gain||10)*0.04')],
'pcc_pediatric_neuro_ext93':[('PediatricStrokeRehabExt','0.15 + Number(input.age||5)*0.04 + Number(input.intensity||3)*0.1 + Number(input.outcome||1)*0.2'),('PediatricStrokeSecondaryPreventionExt','0.15 + Number(input.cause||1)*0.2 + Number(input.antiplatelet||1)*0.15 + Number(input.outcome||1)*0.2'),('PediatricCryptogenicStrokeExt','0.18 + Number(input.pfo||1)*0.2 + Number(input.hypercoag||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCSVTWorkupExt','0.18 + Number(input.clotSite||2)*0.1 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSickleCellStrokeExt','0.18 + Number(input.transfusion||1)*0.2 + Number(input.transcranialDoppler||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeInYoungExt','0.18 + Number(input.age||10)*0.04 + Number(input.moya||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricArtDiseaseStrokeExt','0.18 + Number(input.arteriopathy||1)*0.2 + Number(input.recur||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeLateEffectsExt','0.15 + Number(input.intensity||3)*0.1 + Number(input.weeks||12)*0.04 + Number(input.outcome||1)*0.2'),('PediatricStrokeGeneticExt','0.15 + Number(input.mutations||2)*0.1 + Number(input.syndromic||1)*0.15 + Number(input.outcome||1)*0.2'),('PediatricStrokeFamilyScreenExt','0.15 + Number(input.familyHist||1)*0.15 + Number(input.testing||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext93':[('PediatricCarotidReimplantExt','0.15 + Number(input.age||10)*0.04 + Number(input.stenosis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricECICExt','0.15 + Number(input.age||6)*0.04 + Number(input.bypass||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMoyaMoyaBypassExt','0.15 + Number(input.age||7)*0.04 + Number(input.stages||2)*0.1 + Number(input.outcome||1)*0.2'),('PediatricPosteriorFossaRevascExt','0.15 + Number(input.age||5)*0.04 + Number(input.vessel||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricArteriopathyAnticoagSurgExt','0.15 + Number(input.age||7)*0.04 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCVSTThrombolysisExt','0.15 + Number(input.age||6)*0.04 + Number(input.thrombolysis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDecompressiveStrokeSurgExt','0.15 + Number(input.age||7)*0.04 + Number(input.diam||10)*0.04 + Number(input.outcome||1)*0.2'),('PediatricStentingICAExt','0.15 + Number(input.age||12)*0.02 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCollateralAugmentationExt','0.15 + Number(input.age||6)*0.04 + Number(input.collat||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRevascPostOpCareExt','0.15 + Number(input.age||6)*0.04 + Number(input.icu||3)*0.1 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\n// {m} engine (deterministic)\nmodule.exports.version=\'v3.203.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.203.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}};}};\n'
    eng+=f'\n// TS: v3.203.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'// filepath: pcc/{m}/{m}_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;else console.error(\'FAIL\',fn,r);}}console.log(\'{m} unit:\',pass,\'passed\');if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'// filepath: pcc/{m}/{m}_integration_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{value:1}},{{value:2}},{{value:3}},{{value:4}},{{value:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass,\'passed\');if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'// filepath: pcc/{m}/{m}_routes.js\nconst express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();\nrouter.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.203.0\',functions:Object.keys(F)}}));\nrouter.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});\nrouter.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});\nmodule.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- pcc/{m}/{m}_up.sql\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\')\nBEGIN\nCREATE TABLE [dbo].[{m}] (\n  [id] INT IDENTITY(1,1) PRIMARY KEY,\n  [tenant_id] NVARCHAR(64) NOT NULL,\n  [version] NVARCHAR(16) NOT NULL,\n  [module] NVARCHAR(64) NOT NULL,\n  [function] NVARCHAR(128) NOT NULL,\n  [input] NVARCHAR(MAX) NULL,\n  [score] DECIMAL(6,2) NULL,\n  [ts] DATETIME2 DEFAULT SYSUTCDATETIME()\n);\nEND\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files written')
print('P3-IW v3.203.0: 16 files written')
