import os
MODULES=['pcc_neuro_ext135','pcc_pediatric_neuro_ext124','pcc_pediatric_surg_ext124']
FUNCS={
'pcc_neuro_ext135':[('CarotidStenosisExt','0.18 + Number(input.stenosis||70)*0.005 + Number(input.symptom||1)*0.2 + Number(input.outcome||1)*0.2'),('AsymptomaticCarotidStenExt','0.18 + Number(input.stenosis||60)*0.005 + Number(input.asymptom||1)*0.2 + Number(input.outcome||1)*0.2'),('VertebralStenosisExt','0.18 + Number(input.vertebral||1)*0.2 + Number(input.stenosis||1)*0.2 + Number(input.outcome||1)*0.2'),('IntracranialStenosisExt','0.18 + Number(input.ica||1)*0.2 + Number(input.mca||1)*0.2 + Number(input.outcome||1)*0.2'),('SubclavianStealExt','0.18 + Number(input.subclavian||1)*0.2 + Number(input.steal||1)*0.2 + Number(input.outcome||1)*0.2'),('BowHuntersExt','0.18 + Number(input.rotation||1)*0.2 + Number(input.vertebral||1)*0.2 + Number(input.outcome||1)*0.2'),('ECSText','0.18 + Number(input.carotid||1)*0.2 + Number(input.plaque||1)*0.2 + Number(input.outcome||1)*0.2'),('ICADExt','0.18 + Number(input.intracranial||1)*0.2 + Number(input.stenosis||1)*0.2 + Number(input.outcome||1)*0.2'),('MoyamoyaDiseaseExt','0.18 + Number(input.moyamoya||1)*0.2 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('FMDext','0.18 + Number(input.beading||1)*0.2 + Number(input.female||1)*0.1 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext124':[('PediatricCarotidStenExt','0.18 + Number(input.age||10)*0.04 + Number(input.stenosis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAsymptomCarotidExt','0.18 + Number(input.age||10)*0.04 + Number(input.asymptom||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVertebralStenExt','0.18 + Number(input.age||10)*0.04 + Number(input.vertebral||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIntracranialStenExt','0.18 + Number(input.age||8)*0.04 + Number(input.intracranial||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSubclavianStealExt','0.18 + Number(input.age||10)*0.04 + Number(input.subclavian||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBowHunterExt','0.18 + Number(input.age||10)*0.04 + Number(input.bowHunter||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricECSText','0.18 + Number(input.age||10)*0.04 + Number(input.ecs||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricICADext','0.18 + Number(input.age||8)*0.04 + Number(input.icad||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMoyamoyaExt','0.18 + Number(input.age||5)*0.04 + Number(input.moyamoya||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFMDext','0.18 + Number(input.age||10)*0.04 + Number(input.fmd||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext124':[('PediatricCarotidStentExt','0.18 + Number(input.age||10)*0.04 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAsymptomStentExt','0.18 + Number(input.age||10)*0.04 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVertebralStentExt','0.18 + Number(input.age||10)*0.04 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIntracranialStentExt','0.18 + Number(input.age||8)*0.04 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSubclavianStentExt','0.18 + Number(input.age||10)*0.04 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBowHunterSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.fusion||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricECSAxSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.cea||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricICADsxExt','0.18 + Number(input.age||8)*0.04 + Number(input.angioplasty||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMoyamoyaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.bypass||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFMDsxExt','0.18 + Number(input.age||10)*0.04 + Number(input.angioplasty||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.234.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.234.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.234.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.234.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KB v3.234.0 done')
