import os
MODULES=['pcc_neuro_ext173','pcc_pediatric_neuro_ext162','pcc_pediatric_surg_ext162']
FUNCS={
'pcc_neuro_ext173':[('StrokeHemorrhagicExt','0.18 + Number(input.hemStroke||1)*0.2 + Number(input.hematomaVol||1)*0.2 + Number(input.outcome||1)*0.2'),('Subarachnoid2Ext','0.18 + Number(input.sah2||1)*0.2 + Number(input.huntHess2||1)*0.04 + Number(input.outcome||1)*0.2'),('CerebralVenous2Ext','0.18 + Number(input.cvt2||1)*0.2 + Number(input.dDimers||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokeCryptoExt','0.18 + Number(input.cryptoStroke||1)*0.2 + Number(input.pfo2||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokeEmbolicExt','0.18 + Number(input.embolicStroke||1)*0.2 + Number(input.afib||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokeSmallVesselExt','0.18 + Number(input.smallVess||1)*0.2 + Number(input.lacune||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokeWatershedExt','0.18 + Number(input.watershed||1)*0.2 + Number(input.hypotension||1)*0.2 + Number(input.outcome||1)*0.2'),('StrokeRecoveryExt','0.18 + Number(input.strokeRecov||1)*0.2 + Number(input.northernRankin||1)*0.04 + Number(input.outcome||1)*0.2'),('PostStrokeSeizureExt','0.18 + Number(input.postStrokeSz||1)*0.2 + Number(input.lateOnset||1)*0.2 + Number(input.outcome||1)*0.2'),('PostStrokeHeadacheExt','0.18 + Number(input.postStrokeH||1)*0.2 + Number(input.thunderclap2||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext162':[('PediatricStroke2Ext','0.18 + Number(input.age||5)*0.04 + Number(input.pStroke2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSAH2Ext','0.18 + Number(input.age||10)*0.04 + Number(input.pSAH2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricICH2Ext','0.18 + Number(input.age||5)*0.04 + Number(input.pICH2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeonatalStroke2Ext','0.18 + Number(input.age||0)*0.04 + Number(input.pNeoStroke2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPFOstrokeExt','0.18 + Number(input.age||5)*0.04 + Number(input.pPFO||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSickleStroke2Ext','0.18 + Number(input.age||5)*0.04 + Number(input.sickleStroke2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSinusThromb2Ext','0.18 + Number(input.age||5)*0.04 + Number(input.pSinus2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeRecoveryExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeRecov||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPostStrokeEpilepsyExt','0.18 + Number(input.age||5)*0.04 + Number(input.pPostSzEpi||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVasculitisStrokeExt','0.18 + Number(input.age||8)*0.04 + Number(input.pVasculitisStroke||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext162':[('PediatricStroke2TxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pStroke2Tx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSAH2clipExt','0.18 + Number(input.age||10)*0.04 + Number(input.pSAH2clip||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricICH2evacExt','0.18 + Number(input.age||5)*0.04 + Number(input.pICH2evac||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeonatalStroke2TxExt','0.18 + Number(input.age||0)*0.04 + Number(input.pNeoStroke2Tx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPFOcloseExt','0.18 + Number(input.age||5)*0.04 + Number(input.pPFOclose||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSickleTrans2Ext','0.18 + Number(input.age||5)*0.04 + Number(input.sickleTrans2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSinusAnticoag2Ext','0.18 + Number(input.age||5)*0.04 + Number(input.sinusAnticoag2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStrokeRecovTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.strokeRecovTx2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPostStrokeAEDExt','0.18 + Number(input.age||5)*0.04 + Number(input.postStrokeAED||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVasculitisStrokeTxExt','0.18 + Number(input.age||8)*0.04 + Number(input.vasculitisStrokeTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.1.2.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.1.2.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.1.2.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.1.2.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-AB v3.1.2.0 done')