import os
MODULES=['pcc_palliative_ext102','pcc_hospice_ext102','pcc_end_of_life_ext102']
FUNCS={
'pcc_palliative_ext102':[('PalGenExt','0.18 + Number(input.plGen||1)*0.2 + Number(input.plGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('PalSymptomExt','0.18 + Number(input.plSym||1)*0.2 + Number(input.plSymScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PalPainExt','0.18 + Number(input.plPain||1)*0.2 + Number(input.plPainScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PalDyspneaExt','0.18 + Number(input.plDys||1)*0.2 + Number(input.plDysScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PalNauseaExt','0.18 + Number(input.plNau||1)*0.2 + Number(input.plNauScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PalConstipationExt','0.18 + Number(input.plCon||1)*0.2 + Number(input.plConScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PalDeliriumExt','0.18 + Number(input.plDel||1)*0.2 + Number(input.plDelScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PalAnorexiaExt','0.18 + Number(input.plAno||1)*0.2 + Number(input.plAnoScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PalPsychExt','0.18 + Number(input.plPsy||1)*0.2 + Number(input.plPsyScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PalFamilyExt','0.18 + Number(input.plFam||1)*0.2 + Number(input.plFamScore||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_hospice_ext102':[('HosGenExt','0.18 + Number(input.hsGen||1)*0.2 + Number(input.hsGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('HosEligibilityExt','0.18 + Number(input.hsElig||1)*0.2 + Number(input.hsEligScore||1)*0.04 + Number(input.outcome||1)*0.2'),('HosAdmitExt','0.18 + Number(input.hsAdm||1)*0.2 + Number(input.hsAdmType||1)*0.2 + Number(input.outcome||1)*0.2'),('HosPlanExt','0.18 + Number(input.hsPlan||1)*0.2 + Number(input.hsPlanType||1)*0.2 + Number(input.outcome||1)*0.2'),('HosSymptomExt','0.18 + Number(input.hsSym||1)*0.2 + Number(input.hsSymScore||1)*0.04 + Number(input.outcome||1)*0.2'),('HosCaregiverExt','0.18 + Number(input.hsCare||1)*0.2 + Number(input.hsCareScore||1)*0.04 + Number(input.outcome||1)*0.2'),('HosBereavementExt','0.18 + Number(input.hsBer||1)*0.2 + Number(input.hsBerScore||1)*0.04 + Number(input.outcome||1)*0.2'),('HosSpiritualExt','0.18 + Number(input.hsSpi||1)*0.2 + Number(input.hsSpiScore||1)*0.04 + Number(input.outcome||1)*0.2'),('HosVolunteerExt','0.18 + Number(input.hsVol||1)*0.2 + Number(input.hsVolScore||1)*0.04 + Number(input.outcome||1)*0.2'),('HosDischargeExt','0.18 + Number(input.hsDis||1)*0.2 + Number(input.hsDisType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_end_of_life_ext102':[('EOLCareExt','0.18 + Number(input.elCar||1)*0.2 + Number(input.elCarType||1)*0.2 + Number(input.outcome||1)*0.2'),('EOLDNRExt','0.18 + Number(input.elDNR||1)*0.2 + Number(input.elDNRtype||1)*0.2 + Number(input.outcome||1)*0.2'),('EOLAdvanceExt','0.18 + Number(input.elAdv||1)*0.2 + Number(input.elAdvType||1)*0.2 + Number(input.outcome||1)*0.2'),('EOLGoalsExt','0.18 + Number(input.elGoal||1)*0.2 + Number(input.elGoalType||1)*0.2 + Number(input.outcome||1)*0.2'),('EOLComfortExt','0.18 + Number(input.elCom||1)*0.2 + Number(input.elComScore||1)*0.04 + Number(input.outcome||1)*0.2'),('EOLWithdrawalExt','0.18 + Number(input.elWdr||1)*0.2 + Number(input.elWdrType||1)*0.2 + Number(input.outcome||1)*0.2'),('EOLFamilyMeetExt','0.18 + Number(input.elFam||1)*0.2 + Number(input.elFamScore||1)*0.04 + Number(input.outcome||1)*0.2'),('EOLSpiritualExt','0.18 + Number(input.elSpi||1)*0.2 + Number(input.elSpiScore||1)*0.04 + Number(input.outcome||1)*0.2'),('EOLGriefExt','0.18 + Number(input.elGrief||1)*0.2 + Number(input.elGriefScore||1)*0.04 + Number(input.outcome||1)*0.2'),('EOLDeathExt','0.18 + Number(input.elDeath||1)*0.2 + Number(input.elDeathType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.52.52.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.52.52.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.52.52.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.52.52.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MZ v3.52.52.0 done')