import os
MODULES=['pcc_neuro_ext186','pcc_pediatric_neuro_ext175','pcc_pediatric_surg_ext175']
FUNCS={
'pcc_neuro_ext186':[('CSFdisorderExt','0.18 + Number(input.csfDisorder||1)*0.2 + Number(input.pressure||1)*0.2 + Number(input.outcome||1)*0.2'),('CSFleakSpontaneousExt','0.18 + Number(input.csfLeak||1)*0.2 + Number(input.orthostatic||1)*0.2 + Number(input.outcome||1)*0.2'),('CSFleakSpinalExt','0.18 + Number(input.csfSpinalLeak||1)*0.2 + Number(input.epidural||1)*0.2 + Number(input.outcome||1)*0.2'),('ChiariMalformationExt','0.18 + Number(input.chiariMal||1)*0.2 + Number(input.tonsillar||1)*0.2 + Number(input.outcome||1)*0.2'),('SyringomyeliaExt','0.18 + Number(input.syringo||1)*0.2 + Number(input.cordCyst||1)*0.2 + Number(input.outcome||1)*0.2'),('TetheredCordExt','0.18 + Number(input.tethered||1)*0.2 + Number(input.filum||1)*0.2 + Number(input.outcome||1)*0.2'),('ChiariDecompressionExt','0.18 + Number(input.chiariDecomp||1)*0.2 + Number(input.decompression||1)*0.2 + Number(input.outcome||1)*0.2'),('SpinaBifidaOccultaExt','0.18 + Number(input.sbOcculta||1)*0.2 + Number(input.spinaBifida||1)*0.2 + Number(input.outcome||1)*0.2'),('HydrocephalusExt','0.18 + Number(input.hydro||1)*0.2 + Number(input.evans||1)*0.04 + Number(input.outcome||1)*0.2'),('PseudotumorExt','0.18 + Number(input.pseudotumor||1)*0.2 + Number(input.iih||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext175':[('PediatricCSFleakExt','0.18 + Number(input.age||8)*0.04 + Number(input.pCSFleak||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChiariExt','0.18 + Number(input.age||8)*0.04 + Number(input.pChiari||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSyringoExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSyringo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTetheredExt','0.18 + Number(input.age||3)*0.04 + Number(input.pTethered||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinaBifidaExt','0.18 + Number(input.age||0)*0.04 + Number(input.pSpinaBifida||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHydroExt','0.18 + Number(input.age||1)*0.04 + Number(input.pHydro||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIIHext','0.18 + Number(input.age||10)*0.04 + Number(input.pIIH||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDandyWalkerExt','0.18 + Number(input.age||3)*0.04 + Number(input.pDandy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAqueductStenExt','0.18 + Number(input.age||5)*0.04 + Number(input.pAqueduct||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricArachnoidCystExt','0.18 + Number(input.age||5)*0.04 + Number(input.pArachnoid||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext175':[('PediatricCSFleakSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pCSFleakSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChiariSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.pChiariSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSyringoSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSyringoSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTetheredSxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pTetheredSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSpinaBifidaSxExt','0.18 + Number(input.age||0)*0.04 + Number(input.pSpinaBifidaSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHydroSxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pHydroSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIIHacetazolExt','0.18 + Number(input.age||10)*0.04 + Number(input.pIIHacetazol||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDandyWalkerSxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pDandySx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAqueductSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pAqueductSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricArachnoidSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pArachnoidSx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.15.15.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.15.15.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.15.15.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.15.15.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-HO v3.15.15.0 done')