import os
MODULES=['pcc_neuro_ext154','pcc_pediatric_neuro_ext143','pcc_pediatric_surg_ext143']
FUNCS={
'pcc_neuro_ext154':[('CavernousSinusExt','0.18 + Number(input.cs||1)*0.2 + Number(input.opthalmoplegia||1)*0.2 + Number(input.outcome||1)*0.2'),('SuperiorOrbitalFissureExt','0.18 + Number(input.sof||1)*0.2 + Number(input.orbital||1)*0.2 + Number(input.outcome||1)*0.2'),('OrbitalApexExt','0.18 + Number(input.apex||1)*0.2 + Number(input.vision||1)*0.2 + Number(input.outcome||1)*0.2'),('GradenigoExt','0.18 + Number(input.gradenigo||1)*0.2 + Number(input.petrous||1)*0.2 + Number(input.outcome||1)*0.2'),('TrigeminalNeuralgiaExt','0.18 + Number(input.tic||1)*0.2 + Number(input.v2||1)*0.2 + Number(input.outcome||1)*0.2'),('HemifacialSpasmExt','0.18 + Number(input.hfs||1)*0.2 + Number(input.microvasc||1)*0.2 + Number(input.outcome||1)*0.2'),('GlossopharyngealExt','0.18 + Number(input.glossophar||1)*0.2 + Number(input.throat||1)*0.2 + Number(input.outcome||1)*0.2'),('BellPalsyExt','0.18 + Number(input.bell||1)*0.2 + Number(input.houseBrack||1)*0.04 + Number(input.outcome||1)*0.2'),('RamsayHuntExt','0.18 + Number(input.ramsay||1)*0.2 + Number(input.vzv||1)*0.2 + Number(input.outcome||1)*0.2'),('MelkerssonExt','0.18 + Number(input.melkersson||1)*0.2 + Number(input.facialEdema||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext143':[('PediatricBellPalsyExt','0.18 + Number(input.age||5)*0.04 + Number(input.pBell||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRamsayExt','0.18 + Number(input.age||5)*0.04 + Number(input.pRamsay||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFacialPalsyExt','0.18 + Number(input.age||1)*0.04 + Number(input.facialPalsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMobiusExt','0.18 + Number(input.age||0)*0.04 + Number(input.mobius||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTrigeminalExt','0.18 + Number(input.age||5)*0.04 + Number(input.pTrigeminal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHFSext','0.18 + Number(input.age||8)*0.04 + Number(input.pHFS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongenitalFacialExt','0.18 + Number(input.age||0)*0.04 + Number(input.congFacial||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFacialDiplegiaExt','0.18 + Number(input.age||5)*0.04 + Number(input.facialDiplegia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGBSfacialExt','0.18 + Number(input.age||5)*0.04 + Number(input.gbsFacial||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLymeFacialExt','0.18 + Number(input.age||5)*0.04 + Number(input.lymeFacial||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext143':[('PediatricBellSteroidExt','0.18 + Number(input.age||5)*0.04 + Number(input.bellSteroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRamsayAntivExt','0.18 + Number(input.age||5)*0.04 + Number(input.ramsayAntiv||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFacialRehabExt','0.18 + Number(input.age||1)*0.04 + Number(input.facialRehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMobiusSupportExt','0.18 + Number(input.age||0)*0.04 + Number(input.mobiusSupport||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTrigeminalCarbamExt','0.18 + Number(input.age||5)*0.04 + Number(input.carbamazepine||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHFSbotoxExt','0.18 + Number(input.age||8)*0.04 + Number(input.botoxHFS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFacialProtectExt','0.18 + Number(input.age||0)*0.04 + Number(input.eyeProtect||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFacialSurgeryExt','0.18 + Number(input.age||5)*0.04 + Number(input.facialSurgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFacialEMGExt','0.18 + Number(input.age||5)*0.04 + Number(input.emgFacial||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLymeDoxyExt','0.18 + Number(input.age||5)*0.04 + Number(input.doxycycline||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.253.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.253.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.253.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.253.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KU v3.253.0 done')