import os
MODULES=['pcc_neuro_ext139','pcc_pediatric_neuro_ext128','pcc_pediatric_surg_ext128']
FUNCS={
'pcc_neuro_ext139':[('HemophiliaExt','0.18 + Number(input.factorVIII||1)*0.2 + Number(input.bleed||1)*0.2 + Number(input.outcome||1)*0.2'),('VonWillebrandExt','0.18 + Number(input.vwf||1)*0.2 + Number(input.bleed||1)*0.2 + Number(input.outcome||1)*0.2'),('ImmuneThrombocytopeniaExt','0.18 + Number(input.platelet||20)*0.01 + Number(input.bleed||1)*0.2 + Number(input.outcome||1)*0.2'),('AcquiredHemophiliaExt','0.18 + Number(input.acquired||1)*0.2 + Number(input.factorVIII||1)*0.2 + Number(input.outcome||1)*0.2'),('DICSecondaryExt','0.18 + Number(input.dic||1)*0.2 + Number(input.cause||1)*0.2 + Number(input.outcome||1)*0.2'),('ThromboticMicroangiopathyExt','0.18 + Number(input.tma||1)*0.2 + Number(input.pltLow||1)*0.2 + Number(input.outcome||1)*0.2'),('HypercoagulableStateExt','0.18 + Number(input.thrombophilia||1)*0.2 + Number(input.dvt||1)*0.2 + Number(input.outcome||1)*0.2'),('AntiphospholipidSynExt','0.18 + Number(input.lupus||1)*0.2 + Number(input.anticardiolipin||1)*0.2 + Number(input.outcome||1)*0.2'),('ThrombophiliaInheritedExt','0.18 + Number(input.factorVleiden||1)*0.2 + Number(input.prothrombin||1)*0.2 + Number(input.outcome||1)*0.2'),('AnticoagulationReversalExt','0.18 + Number(input.warfarin||1)*0.2 + Number(input.bleed||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext128':[('PediatricHemophiliaExt','0.18 + Number(input.age||5)*0.04 + Number(input.hemophilia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVWDExt','0.18 + Number(input.age||5)*0.04 + Number(input.vwd||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricITPExt','0.18 + Number(input.age||5)*0.04 + Number(input.itp||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAcquiredHemoExt','0.18 + Number(input.age||10)*0.04 + Number(input.acquiredHemo||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDICExt','0.18 + Number(input.age||1)*0.04 + Number(input.dic||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTMAext','0.18 + Number(input.age||5)*0.04 + Number(input.tma||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHypercoagExt','0.18 + Number(input.age||5)*0.04 + Number(input.hypercoag||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAPASext','0.18 + Number(input.age||10)*0.04 + Number(input.aps||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricThrombophiliaExt','0.18 + Number(input.age||10)*0.04 + Number(input.thrombophilia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAnticoagulationExt','0.18 + Number(input.age||5)*0.04 + Number(input.anticoagulation||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext128':[('PediatricHemophiliaFactorExt','0.18 + Number(input.age||5)*0.04 + Number(input.factor||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVWDDDAVPext','0.18 + Number(input.age||5)*0.04 + Number(input.ddavp||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricITPSteroidExt','0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAcquiredHemoBypassExt','0.18 + Number(input.age||10)*0.04 + Number(input.bypass||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDICtransfusionExt','0.18 + Number(input.age||1)*0.04 + Number(input.transfusion||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTMAplasmaExt','0.18 + Number(input.age||5)*0.04 + Number(input.plasmaExchange||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHypercoagAntiExt','0.18 + Number(input.age||5)*0.04 + Number(input.antiCoag||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAPASantiExt','0.18 + Number(input.age||10)*0.04 + Number(input.antiCoag||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricThrombophiliaAntiExt','0.18 + Number(input.age||10)*0.04 + Number(input.antiCoag||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAnticoagulationReversalExt','0.18 + Number(input.age||5)*0.04 + Number(input.vitaminK||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.238.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.238.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.238.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.238.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KF v3.238.0 done')
