import os
MODULES=['pcc_obgyn_ext99','pcc_ped_ext99','pcc_surg_ext99']
FUNCS={
'pcc_obgyn_ext99':[('OBAntenatalExt','0.18 + Number(input.obAntenatal||1)*0.2 + Number(input.ga||1)*0.04 + Number(input.outcome||1)*0.2'),('OBIntrapartumExt','0.18 + Number(input.obIP||1)*0.2 + Number(input.cervixDil||1)*0.04 + Number(input.outcome||1)*0.2'),('OBPostpartumExt','0.18 + Number(input.obPP||1)*0.2 + Number(input.ppDay||1)*0.04 + Number(input.outcome||1)*0.2'),('OBHighRiskExt','0.18 + Number(input.obHR||1)*0.2 + Number(input.riskScore||1)*0.04 + Number(input.outcome||1)*0.2'),('GynGeneralExt','0.18 + Number(input.gynGeneral||1)*0.2 + Number(input.gynAge||1)*0.04 + Number(input.outcome||1)*0.2'),('GynOncologyExt','0.18 + Number(input.gynOnc||1)*0.2 + Number(input.gynStage||1)*0.04 + Number(input.outcome||1)*0.2'),('GynInfertilityExt','0.18 + Number(input.gynIF||1)*0.2 + Number(input.amh||1)*0.04 + Number(input.outcome||1)*0.2'),('OBDiabetesExt','0.18 + Number(input.obDM||1)*0.2 + Number(input.gdm||1)*0.2 + Number(input.outcome||1)*0.2'),('OBPreeclampsiaExt','0.18 + Number(input.obPE||1)*0.2 + Number(input.bpHigh||1)*0.04 + Number(input.outcome||1)*0.2'),('OBFetalMonitoringExt','0.18 + Number(input.obFHR||1)*0.2 + Number(input.fhrCategory||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_ped_ext99':[('PedGeneralExt','0.18 + Number(input.pedGen||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2'),('PedNeonateExt','0.18 + Number(input.pedNeo||1)*0.2 + Number(input.gaWeeks||1)*0.04 + Number(input.outcome||1)*0.2'),('PedInfantExt','0.18 + Number(input.pedInfant||1)*0.2 + Number(input.pedAge||1)*0.04 + Number(input.outcome||1)*0.2'),('PedChildExt','0.18 + Number(input.pedChild||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2'),('PedAdolescentExt','0.18 + Number(input.pedAdol||1)*0.2 + Number(input.pedAge||12)*0.04 + Number(input.outcome||1)*0.2'),('PedRespiratoryExt','0.18 + Number(input.pedResp||1)*0.2 + Number(input.oxySat||1)*0.04 + Number(input.outcome||1)*0.2'),('PedGastroExt','0.18 + Number(input.pedGI||1)*0.2 + Number(input.dehyd||1)*0.2 + Number(input.outcome||1)*0.2'),('PedFeverExt','0.18 + Number(input.pedFever||1)*0.2 + Number(input.temp||1)*0.04 + Number(input.outcome||1)*0.2'),('PedVaccineExt','0.18 + Number(input.pedVacc||1)*0.2 + Number(input.vaccAge||1)*0.04 + Number(input.outcome||1)*0.2'),('PedGrowthExt','0.18 + Number(input.pedGrowth||1)*0.2 + Number(input.percentile||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_surg_ext99':[('SurgPreopExt','0.18 + Number(input.preOp||1)*0.2 + Number(input.asaClass||1)*0.04 + Number(input.outcome||1)*0.2'),('SurgIntraopExt','0.18 + Number(input.intraOp||1)*0.2 + Number(input.opDuration||1)*0.04 + Number(input.outcome||1)*0.2'),('SurgPostopExt','0.18 + Number(input.postOp||1)*0.2 + Number(input.pod||1)*0.04 + Number(input.outcome||1)*0.2'),('SurgCardiacExt','0.18 + Number(input.surgCardiac||1)*0.2 + Number(input.bypassTime||1)*0.04 + Number(input.outcome||1)*0.2'),('SurgNeuroExt','0.18 + Number(input.surgNeuro||1)*0.2 + Number(input.craniotomyType||1)*0.2 + Number(input.outcome||1)*0.2'),('SurgOrthoExt','0.18 + Number(input.surgOrtho||1)*0.2 + Number(input.orthoType||1)*0.2 + Number(input.outcome||1)*0.2'),('SurgGIext','0.18 + Number(input.surgGI||1)*0.2 + Number(input.giProcedure||1)*0.2 + Number(input.outcome||1)*0.2'),('SurgVascularExt','0.18 + Number(input.surgVasc||1)*0.2 + Number(input.vascType||1)*0.2 + Number(input.outcome||1)*0.2'),('SurgTransplantExt','0.18 + Number(input.surgTx||1)*0.2 + Number(input.txType||1)*0.2 + Number(input.outcome||1)*0.2'),('SurgOncologyExt','0.18 + Number(input.surgOnc||1)*0.2 + Number(input.oncStage||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.17.17.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.17.17.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.17.17.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.17.17.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LQ v3.17.17.0 done')