import os
MODULES=['pcc_neuro_ext155','pcc_pediatric_neuro_ext144','pcc_pediatric_surg_ext144']
FUNCS={
'pcc_neuro_ext155':[('SleepApneaNeuroExt','0.18 + Number(input.osa||1)*0.2 + Number(input.aHI||1)*0.04 + Number(input.outcome||1)*0.2'),('NarcolepsyExt','0.18 + Number(input.narcolepsy||1)*0.2 + Number(input.cataplexy||1)*0.2 + Number(input.outcome||1)*0.2'),('IdiopathicHypersomniaExt','0.18 + Number(input.ih||1)*0.2 + Number(input.daytime||1)*0.2 + Number(input.outcome||1)*0.2'),('KleineLevinExt','0.18 + Number(input.kl||1)*0.2 + Number(input.hypersomnia||1)*0.2 + Number(input.outcome||1)*0.2'),('REMBehaviorExt','0.18 + Number(input.rbd||1)*0.2 + Number(input.actigraphy||1)*0.2 + Number(input.outcome||1)*0.2'),('RestlessLegsExt','0.18 + Number(input.rls||1)*0.2 + Number(input.ferritin||1)*0.2 + Number(input.outcome||1)*0.2'),('PeriodicLimbExt','0.18 + Number(input.plmd||1)*0.2 + Number(input.plms||1)*0.04 + Number(input.outcome||1)*0.2'),('SleepParalysisExt','0.18 + Number(input.paralysis||1)*0.2 + Number(input.atonia||1)*0.2 + Number(input.outcome||1)*0.2'),('ExplodingHeadExt','0.18 + Number(input.exploding||1)*0.2 + Number(input.head||1)*0.2 + Number(input.outcome||1)*0.2'),('FatalFamilialInsomniaExt','0.18 + Number(input.ffi||1)*0.2 + Number(input.prion||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext144':[('PediatricOSAExt','0.18 + Number(input.age||5)*0.04 + Number(input.pOSA||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNarcolepsyExt','0.18 + Number(input.age||10)*0.04 + Number(input.pNarcolepsy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNightTerrorsExt','0.18 + Number(input.age||3)*0.04 + Number(input.nightTerror||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSleepWalkingExt','0.18 + Number(input.age||8)*0.04 + Number(input.sleepwalk||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRLSext','0.18 + Number(input.age||5)*0.04 + Number(input.pRLS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEnuresisExt','0.18 + Number(input.age||5)*0.04 + Number(input.enuresis||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDelayedSleepExt','0.18 + Number(input.age||10)*0.04 + Number(input.dsps||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSleepApneaSyndromeExt','0.18 + Number(input.age||5)*0.04 + Number(input.pSAS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCongenitalHypoventExt','0.18 + Number(input.age||0)*0.04 + Number(input.cihs||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricKleineLevinExt','0.18 + Number(input.age||10)*0.04 + Number(input.pKL||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext144':[('PediatricOSAtonsilExt','0.18 + Number(input.age||5)*0.04 + Number(input.tonsillectomy||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOSACPAPExt','0.18 + Number(input.age||5)*0.04 + Number(input.cpap||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNarcolepsyModafinilExt','0.18 + Number(input.age||10)*0.04 + Number(input.modafinil||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSleepHygieneExt','0.18 + Number(input.age||3)*0.04 + Number(input.sleepHygiene||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEnuresisAlarmExt','0.18 + Number(input.age||5)*0.04 + Number(input.alarm||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDSPSmelatoninExt','0.18 + Number(input.age||10)*0.04 + Number(input.melatonin||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSleepStudyExt','0.18 + Number(input.age||5)*0.04 + Number(input.polysom||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVentSupportExt','0.18 + Number(input.age||0)*0.04 + Number(input.ventSupport||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricRLSIronExt','0.18 + Number(input.age||5)*0.04 + Number(input.ironRLS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricKLsupportExt','0.18 + Number(input.age||10)*0.04 + Number(input.klSupport||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.254.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.254.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.254.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.254.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KV v3.254.0 done')