import os
MODULES=['pcc_pharmacovigilance_ext102','pcc_orphan_drugs_ext102','pcc_rare_diseases_ext102']
FUNCS={
'pcc_pharmacovigilance_ext102':[('PVReportingExt','0.18 + Number(input.pvReport||1)*0.2 + Number(input.pvReportType||1)*0.2 + Number(input.outcome||1)*0.2'),('PVSignalExt','0.18 + Number(input.pvSignal||1)*0.2 + Number(input.pvSignalStrength||1)*0.04 + Number(input.outcome||1)*0.2'),('PVADRadultExt','0.18 + Number(input.pvADR||1)*0.2 + Number(input.pvAdrType||1)*0.2 + Number(input.outcome||1)*0.2'),('PVPeriodicExt','0.18 + Number(input.pvPSUR||1)*0.2 + Number(input.pvPsurType||1)*0.2 + Number(input.outcome||1)*0.2'),('PVRiskMgmtExt','0.18 + Number(input.pvRMP||1)*0.2 + Number(input.pvRmpType||1)*0.2 + Number(input.outcome||1)*0.2'),('PVVaccineExt','0.18 + Number(input.pvVacc||1)*0.2 + Number(input.pvVaccType||1)*0.2 + Number(input.outcome||1)*0.2'),('PVDeviceExt','0.18 + Number(input.pvDevice||1)*0.2 + Number(input.pvDeviceType||1)*0.2 + Number(input.outcome||1)*0.2'),('PVMedErrorExt','0.18 + Number(input.pvError||1)*0.2 + Number(input.pvErrorType||1)*0.2 + Number(input.outcome||1)*0.2'),('PVLackEfficacyExt','0.18 + Number(input.pvLoE||1)*0.2 + Number(input.pvLoeDrug||1)*0.2 + Number(input.outcome||1)*0.2'),('PVPregnancyExt','0.18 + Number(input.pvPreg||1)*0.2 + Number(input.pvPregTrimest||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_orphan_drugs_ext102':[('OrphanDesignationExt','0.18 + Number(input.orDesig||1)*0.2 + Number(input.orDesigStatus||1)*0.2 + Number(input.outcome||1)*0.2'),('OrphanAccessExt','0.18 + Number(input.orAccess||1)*0.2 + Number(input.orAccessType||1)*0.2 + Number(input.outcome||1)*0.2'),('OrphanCostExt','0.18 + Number(input.orCost||1)*0.2 + Number(input.orCostCover||1)*0.2 + Number(input.outcome||1)*0.2'),('OrphanTrialExt','0.18 + Number(input.orTrial||1)*0.2 + Number(input.orTrialPhase||1)*0.04 + Number(input.outcome||1)*0.2'),('OrphanSurrogateExt','0.18 + Number(input.orSurrogate||1)*0.2 + Number(input.orSurrogateType||1)*0.2 + Number(input.outcome||1)*0.2'),('OrphanCompassionateExt','0.18 + Number(input.orComp||1)*0.2 + Number(input.orCompType||1)*0.2 + Number(input.outcome||1)*0.2'),('OrphanRegistryExt','0.18 + Number(input.orReg||1)*0.2 + Number(input.orRegSize||1)*0.04 + Number(input.outcome||1)*0.2'),('OrphanPediatricExt','0.18 + Number(input.orPed||1)*0.2 + Number(input.orPedAge||5)*0.04 + Number(input.outcome||1)*0.2'),('OrphanGeneticExt','0.18 + Number(input.orGen||1)*0.2 + Number(input.orGenDisorder||1)*0.2 + Number(input.outcome||1)*0.2'),('OrphanApprovalExt','0.18 + Number(input.orAppr||1)*0.2 + Number(input.orApprPath||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_rare_diseases_ext102':[('RareDxExt','0.18 + Number(input.rdDx||1)*0.2 + Number(input.rdDxType||1)*0.2 + Number(input.outcome||1)*0.2'),('RarePrevalenceExt','0.18 + Number(input.rdPrev||1)*0.2 + Number(input.rdPrevRate||1)*0.04 + Number(input.outcome||1)*0.2'),('RareRegistryExt','0.18 + Number(input.rdReg||1)*0.2 + Number(input.rdRegSize||1)*0.04 + Number(input.outcome||1)*0.2'),('RareCenterExt','0.18 + Number(input.rdCenter||1)*0.2 + Number(input.rdCenterType||1)*0.2 + Number(input.outcome||1)*0.2'),('RarePediatricExt','0.18 + Number(input.rdPed||1)*0.2 + Number(input.rdPedAge||5)*0.04 + Number(input.outcome||1)*0.2'),('RareNewbornExt','0.18 + Number(input.rdNBS||1)*0.2 + Number(input.rdNbsCond||1)*0.2 + Number(input.outcome||1)*0.2'),('RareGeneticExt','0.18 + Number(input.rdGen||1)*0.2 + Number(input.rdGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('RareMetabolicExt','0.18 + Number(input.rdMet||1)*0.2 + Number(input.rdMetType||1)*0.2 + Number(input.outcome||1)*0.2'),('RareAdultExt','0.18 + Number(input.rdAdult||1)*0.2 + Number(input.rdAdultType||1)*0.2 + Number(input.outcome||1)*0.2'),('RareSupportExt','0.18 + Number(input.rdSupport||1)*0.2 + Number(input.rdSupportType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.40.40.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.40.40.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.40.40.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.40.40.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MN v3.40.40.0 done')