import os
MODULES=['pcc_uro_ext101','pcc_urogyn_ext101','pcc_reprod_ext101']
FUNCS={
'pcc_uro_ext101':[('UroGeneralExt','0.18 + Number(input.uroGen||1)*0.2 + Number(input.uroGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('UroBPHext','0.18 + Number(input.uroBPH||1)*0.2 + Number(input.ippsScore||1)*0.04 + Number(input.outcome||1)*0.2'),('UroProstateCancerExt','0.18 + Number(input.uroPCa||1)*0.2 + Number(input.psaPSA||1)*0.04 + Number(input.outcome||1)*0.2'),('UroBladderCancerExt','0.18 + Number(input.uroBladCa||1)*0.2 + Number(input.bladderCaStage||1)*0.04 + Number(input.outcome||1)*0.2'),('UroKidneyCancerExt','0.18 + Number(input.uroKCa||1)*0.2 + Number(input.kcaStage||1)*0.04 + Number(input.outcome||1)*0.2'),('UroTesticularExt','0.18 + Number(input.uroTestis||1)*0.2 + Number(input.tcStage||1)*0.04 + Number(input.outcome||1)*0.2'),('UroStoneExt','0.18 + Number(input.uroStone||1)*0.2 + Number(input.stoneSizeU||1)*0.04 + Number(input.outcome||1)*0.2'),('UroStrictureExt','0.18 + Number(input.uroStric||1)*0.2 + Number(input.strictureLoc||1)*0.2 + Number(input.outcome||1)*0.2'),('UroIncontinenceExt','0.18 + Number(input.uroIncont||1)*0.2 + Number(input.incontType||1)*0.2 + Number(input.outcome||1)*0.2'),('UroPediatricExt','0.18 + Number(input.uroPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_urogyn_ext101':[('UGProlapseExt','0.18 + Number(input.ugProlapse||1)*0.2 + Number(input.prolapseStage||1)*0.04 + Number(input.outcome||1)*0.2'),('UGIncontinenceExt','0.18 + Number(input.ugIncont||1)*0.2 + Number(input.ugIncontType||1)*0.2 + Number(input.outcome||1)*0.2'),('UGOveractiveExt','0.18 + Number(input.ugOAB||1)*0.2 + Number(input.oabScore||1)*0.04 + Number(input.outcome||1)*0.2'),('UGRecurrentUTIext','0.18 + Number(input.ugUTI||1)*0.2 + Number(input.utiFreqUG||1)*0.04 + Number(input.outcome||1)*0.2'),('UGMeshComplicationExt','0.18 + Number(input.ugMesh||1)*0.2 + Number(input.meshCompType||1)*0.2 + Number(input.outcome||1)*0.2'),('UGPFMText','0.18 + Number(input.ugPFM||1)*0.2 + Number(input.pfmType||1)*0.2 + Number(input.outcome||1)*0.2'),('UGInterstitialExt','0.18 + Number(input.ugIC||1)*0.2 + Number(input.icPainScore||1)*0.04 + Number(input.outcome||1)*0.2'),('UGEndometriosisExt','0.18 + Number(input.ugEndo||1)*0.2 + Number(input.endoStage||1)*0.04 + Number(input.outcome||1)*0.2'),('UGBirthTraumaExt','0.18 + Number(input.ugBirth||1)*0.2 + Number(input.birthTraumaType||1)*0.2 + Number(input.outcome||1)*0.2'),('UGMenopauseExt','0.18 + Number(input.ugMenopause||1)*0.2 + Number(input.menoStage||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_reprod_ext101':[('ReproIFMExt','0.18 + Number(input.rpIFM||1)*0.2 + Number(input.fshLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('ReproIVFExt','0.18 + Number(input.rpIVF||1)*0.2 + Number(input.ivfCycle||1)*0.04 + Number(input.outcome||1)*0.2'),('ReproMaleExt','0.18 + Number(input.rpMale||1)*0.2 + Number(input.spermCount||1)*0.04 + Number(input.outcome||1)*0.2'),('ReproPCOSext','0.18 + Number(input.rpPCOS||1)*0.2 + Number(input.amhRP||1)*0.04 + Number(input.outcome||1)*0.2'),('ReproEndometriosisExt','0.18 + Number(input.rpEndo||1)*0.2 + Number(input.endoStageRP||1)*0.04 + Number(input.outcome||1)*0.2'),('ReproGeneticExt','0.18 + Number(input.rpGen||1)*0.2 + Number(input.karyotype||1)*0.2 + Number(input.outcome||1)*0.2'),('ReproMiscarriageExt','0.18 + Number(input.rpMiscar||1)*0.2 + Number(input.miscarRecur||1)*0.04 + Number(input.outcome||1)*0.2'),('ReproContraceptionExt','0.18 + Number(input.rpContra||1)*0.2 + Number(input.contraType||1)*0.2 + Number(input.outcome||1)*0.2'),('ReproMenstrualExt','0.18 + Number(input.rpMens||1)*0.2 + Number(input.mensCycle||1)*0.04 + Number(input.outcome||1)*0.2'),('ReproSexualExt','0.18 + Number(input.rpSex||1)*0.2 + Number(input.sexualDysfn||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.34.34.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.34.34.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.34.34.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.34.34.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MH v3.34.34.0 done')