import os
MODULES=['pcc_neuro_ext123','pcc_pediatric_neuro_ext112','pcc_pediatric_surg_ext112']
FUNCS={
'pcc_neuro_ext123':[('SchwannomaExt','0.18 + Number(input.size||3)*0.1 + Number(input.location||1)*0.2 + Number(input.outcome||1)*0.2'),('VestibularSchwannomaExt','0.18 + Number(input.koos||3)*0.1 + Number(input.hearing||1)*0.2 + Number(input.outcome||1)*0.2'),('TrigeminalSchwannomaExt','0.18 + Number(input.v||3)*0.1 + Number(input.face||1)*0.2 + Number(input.outcome||1)*0.2'),('NF2ext','0.18 + Number(input.bilateral||1)*0.2 + Number(input.family||1)*0.2 + Number(input.outcome||1)*0.2'),('NF2vestibularExt','0.18 + Number(input.bilateral||1)*0.2 + Number(input.merlin||1)*0.2 + Number(input.outcome||1)*0.2'),('NeurofibromaExt','0.18 + Number(input.nf1||1)*0.2 + Number(input.plexiform||1)*0.2 + Number(input.outcome||1)*0.2'),('MalignantPeripheralExt','0.18 + Number(input.mpnst||1)*0.2 + Number(input.nf1||1)*0.2 + Number(input.outcome||1)*0.2'),('GlomusTumorExt','0.18 + Number(input.jugulare||1)*0.2 + Number(input.tympanicum||1)*0.2 + Number(input.outcome||1)*0.2'),('HemangioblastomaExt','0.18 + Number(input.vhl||1)*0.2 + Number(input.cyst||1)*0.2 + Number(input.outcome||1)*0.2'),('ChordomaExt','0.18 + Number(input.clivus||1)*0.2 + Number(input.brainstem||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext112':[('PediatricSchwannomaExt','0.18 + Number(input.age||10)*0.04 + Number(input.schwannoma||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVestibularSchwannomaExt','0.18 + Number(input.age||10)*0.04 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTrigeminalSchwannomaExt','0.18 + Number(input.age||10)*0.04 + Number(input.face||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNF2ext','0.18 + Number(input.age||8)*0.04 + Number(input.nf2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNF2vestibularExt','0.18 + Number(input.age||8)*0.04 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeurofibromaExt','0.18 + Number(input.age||5)*0.04 + Number(input.nf1||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMPNSText','0.18 + Number(input.age||10)*0.04 + Number(input.mpnst||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGlomusExt','0.18 + Number(input.age||10)*0.04 + Number(input.glomus||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHemangioblastomaExt','0.18 + Number(input.age||8)*0.04 + Number(input.vhl||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChordomaExt','0.18 + Number(input.age||5)*0.04 + Number(input.clivus||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext112':[('PediatricSchwannomaSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVestibularSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTrigeminalSchwannomaSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNF2SxExt','0.18 + Number(input.age||8)*0.04 + Number(input.bevacizumab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNF2vestibularSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.hearingPreserve||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNeurofibromaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.surgery||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMPNSTSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGlomusSxExt','0.18 + Number(input.age||10)*0.04 + Number(input.preopEmbol||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHemangioblastomaSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChordomaSxExt','0.18 + Number(input.age||5)*0.04 + Number(input.proton||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.222.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.222.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.222.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.222.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-JP v3.222.0 done')
