import os
MODULES=['pcc_genetics_ext102','pcc_genomics_ext102','pcc_proteomics_ext102']
FUNCS={
'pcc_genetics_ext102':[('GenDnaSeqExt','0.18 + Number(input.gnSeq||1)*0.2 + Number(input.gnSeqType||1)*0.2 + Number(input.outcome||1)*0.2'),('GenVariantExt','0.18 + Number(input.gnVar||1)*0.2 + Number(input.gnVarType||1)*0.2 + Number(input.outcome||1)*0.2'),('GenCarrierExt','0.18 + Number(input.gnCarr||1)*0.2 + Number(input.gnCarrTrait||1)*0.2 + Number(input.outcome||1)*0.2'),('GenPrenatalExt','0.18 + Number(input.gnPrenatal||1)*0.2 + Number(input.gnFetalAge||1)*0.04 + Number(input.outcome||1)*0.2'),('GenNewbornExt','0.18 + Number(input.gnNewborn||1)*0.2 + Number(input.gnNbsCondition||1)*0.2 + Number(input.outcome||1)*0.2'),('GenCancerSyndromeExt','0.18 + Number(input.gnCancerSyn||1)*0.2 + Number(input.gnCsGene||1)*0.2 + Number(input.outcome||1)*0.2'),('GenCardiacExt','0.18 + Number(input.gnCardiac||1)*0.2 + Number(input.gnCardiacGene||1)*0.2 + Number(input.outcome||1)*0.2'),('GenNeuroExt','0.18 + Number(input.gnNeuro||1)*0.2 + Number(input.gnNeuroGene||1)*0.2 + Number(input.outcome||1)*0.2'),('GenMetabolicExt','0.18 + Number(input.gnMet||1)*0.2 + Number(input.gnMetGene||1)*0.2 + Number(input.outcome||1)*0.2'),('GenCounselingExt','0.18 + Number(input.gnCounsel||1)*0.2 + Number(input.gnCounselRisk||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_genomics_ext102':[('GenWholeGenomeExt','0.18 + Number(input.gnWGS||1)*0.2 + Number(input.gnWgsCov||1)*0.04 + Number(input.outcome||1)*0.2'),('GenExomeExt','0.18 + Number(input.gnExome||1)*0.2 + Number(input.gnExomCov||1)*0.04 + Number(input.outcome||1)*0.2'),('GenRNASeqExt','0.18 + Number(input.gnRNA||1)*0.2 + Number(input.gnRnaTissue||1)*0.2 + Number(input.outcome||1)*0.2'),('GenMethylationExt','0.18 + Number(input.gnMeth||1)*0.2 + Number(input.gnMethSite||1)*0.04 + Number(input.outcome||1)*0.2'),('GenMicrobiomeExt','0.18 + Number(input.gnMicro||1)*0.2 + Number(input.gnMicroSite||1)*0.2 + Number(input.outcome||1)*0.2'),('GenPharmacogenomicExt','0.18 + Number(input.gnPGx||1)*0.2 + Number(input.gnPgxDrug||1)*0.2 + Number(input.outcome||1)*0.2'),('GenEpigenomicExt','0.18 + Number(input.gnEpig||1)*0.2 + Number(input.gnEpigMarker||1)*0.04 + Number(input.outcome||1)*0.2'),('GenSingleCellExt','0.18 + Number(input.gnSC||1)*0.2 + Number(input.gnScType||1)*0.2 + Number(input.outcome||1)*0.2'),('GenSpatialExt','0.18 + Number(input.gnSpatial||1)*0.2 + Number(input.gnSpatialTissue||1)*0.2 + Number(input.outcome||1)*0.2'),('GenMultiOmicsExt','0.18 + Number(input.gnMulti||1)*0.2 + Number(input.gnMultiLayer||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_proteomics_ext102':[('ProMassSpecExt','0.18 + Number(input.prMS||1)*0.2 + Number(input.prMsType||1)*0.2 + Number(input.outcome||1)*0.2'),('ProELISAExt','0.18 + Number(input.prELISA||1)*0.2 + Number(input.prElisaTarget||1)*0.2 + Number(input.outcome||1)*0.2'),('ProWBext','0.18 + Number(input.prWB||1)*0.2 + Number(input.prWbAb||1)*0.04 + Number(input.outcome||1)*0.2'),('ProFlowExt','0.18 + Number(input.prFlow||1)*0.2 + Number(input.prFlowMarker||1)*0.2 + Number(input.outcome||1)*0.2'),('ProIHCext','0.18 + Number(input.prIHC||1)*0.2 + Number(input.prIhcMarker||1)*0.2 + Number(input.outcome||1)*0.2'),('ProBiomarkerExt','0.18 + Number(input.prBiomarker||1)*0.2 + Number(input.prBiomarkerLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('ProPhosphoExt','0.18 + Number(input.prPhos||1)*0.2 + Number(input.prPhosSite||1)*0.2 + Number(input.outcome||1)*0.2'),('ProInteractomeExt','0.18 + Number(input.prInt||1)*0.2 + Number(input.prIntType||1)*0.2 + Number(input.outcome||1)*0.2'),('ProStructExt','0.18 + Number(input.prStruct||1)*0.2 + Number(input.prStructType||1)*0.2 + Number(input.outcome||1)*0.2'),('ProClinExt','0.18 + Number(input.prClin||1)*0.2 + Number(input.prClinInd||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.38.38.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.38.38.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.38.38.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.38.38.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-ML v3.38.38.0 done')