import os
MODULES=['pcc_neuro_ext134','pcc_pediatric_neuro_ext123','pcc_pediatric_surg_ext123']
FUNCS={
'pcc_neuro_ext134':[('AbuliaExt','0.18 + Number(input.motivation||1)*0.2 + Number(input.frontal||1)*0.2 + Number(input.outcome||1)*0.2'),('CatatoniaExt','0.18 + Number(input.stupor||1)*0.2 + Number(input.mutism||1)*0.2 + Number(input.outcome||1)*0.2'),('AkineticMutismExt','0.18 + Number(input.mutism||1)*0.2 + Number(input.akinesia||1)*0.2 + Number(input.outcome||1)*0.2'),('LockedInSyndromeExt','0.18 + Number(input.pontine||1)*0.2 + Number(input.aware||1)*0.2 + Number(input.outcome||1)*0.2'),('VegetativeStateExt','0.18 + Number(input.unresponsive||1)*0.2 + Number(input.cycle||1)*0.2 + Number(input.outcome||1)*0.2'),('MinimallyConsciousStateExt','0.18 + Number(input.command||1)*0.2 + Number(input.inconsistent||1)*0.2 + Number(input.outcome||1)*0.2'),('BrainDeathExt','0.18 + Number(input.coma||1)*0.2 + Number(input.apnea||1)*0.2 + Number(input.outcome||1)*0.2'),('PersistentVegetativeStateExt','0.18 + Number(input.months||6)*0.04 + Number(input.unresponsive||1)*0.2 + Number(input.outcome||1)*0.2'),('ConsciousnessDisordersExt','0.18 + Number(input.disorder||1)*0.2 + Number(input.awareness||1)*0.2 + Number(input.outcome||1)*0.2'),('StuporExt','0.18 + Number(input.stupor||1)*0.2 + Number(input.unresponsive||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext123':[('PediatricAbuliaExt','0.18 + Number(input.age||5)*0.04 + Number(input.abulia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCatatoniaExt','0.18 + Number(input.age||10)*0.04 + Number(input.catatonia||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAkineticMutismExt','0.18 + Number(input.age||5)*0.04 + Number(input.mutism||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLockedInExt','0.18 + Number(input.age||5)*0.04 + Number(input.lockedIn||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVSext','0.18 + Number(input.age||1)*0.04 + Number(input.unresponsive||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMCSExt','0.18 + Number(input.age||3)*0.04 + Number(input.command||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBrainDeathExt','0.18 + Number(input.age||3)*0.04 + Number(input.brainDead||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPVSExt','0.18 + Number(input.age||3)*0.04 + Number(input.pvs||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricConsciousnessExt','0.18 + Number(input.age||5)*0.04 + Number(input.consciousness||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStuporExt','0.18 + Number(input.age||5)*0.04 + Number(input.stupor||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext123':[('PediatricAbuliaSupportExt','0.18 + Number(input.age||5)*0.04 + Number(input.dopamine||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCatatoniaLorazepamExt','0.18 + Number(input.age||10)*0.04 + Number(input.lorazepam||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAkineticMutismSupportExt','0.18 + Number(input.age||5)*0.04 + Number(input.stimulant||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLockedInSupportExt','0.18 + Number(input.age||5)*0.04 + Number(input.communication||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricVSSupportExt','0.18 + Number(input.age||1)*0.04 + Number(input.support||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMCSrehabExt','0.18 + Number(input.age||3)*0.04 + Number(input.rehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBrainDeathConfirmExt','0.18 + Number(input.age||3)*0.04 + Number(input.apneaTest||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPVSrehabExt','0.18 + Number(input.age||3)*0.04 + Number(input.rehab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricConsciousnessStimExt','0.18 + Number(input.age||5)*0.04 + Number(input.zolpidem||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStuporSupportExt','0.18 + Number(input.age||5)*0.04 + Number(input.support||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.233.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.233.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.233.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.233.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KA v3.233.0 done')
