import os
MODULES=['pcc_orthopedics_ext102','pcc_sports_ortho_ext102','pcc_joint_replacement_ext102']
FUNCS={
'pcc_orthopedics_ext102':[('OrtGenExt','0.18 + Number(input.orGen||1)*0.2 + Number(input.orGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('OrtFracExt','0.18 + Number(input.orFrac||1)*0.2 + Number(input.orFracType||1)*0.2 + Number(input.outcome||1)*0.2'),('OrtDislocExt','0.18 + Number(input.orDis||1)*0.2 + Number(input.orDisType||1)*0.2 + Number(input.outcome||1)*0.2'),('OrtSprainExt','0.18 + Number(input.orSpr||1)*0.2 + Number(input.orSprGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('OrtArthritisExt','0.18 + Number(input.orArt||1)*0.2 + Number(input.orArtGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('OrtBackExt','0.18 + Number(input.orBack||1)*0.2 + Number(input.orBackScore||1)*0.04 + Number(input.outcome||1)*0.2'),('OrtPediatricExt','0.18 + Number(input.orPed||1)*0.2 + Number(input.orPedType||1)*0.2 + Number(input.outcome||1)*0.2'),('OrtTumorExt','0.18 + Number(input.orTum||1)*0.2 + Number(input.orTumType||1)*0.2 + Number(input.outcome||1)*0.2'),('OrtInfectionExt','0.18 + Number(input.orInf||1)*0.2 + Number(input.orInfType||1)*0.2 + Number(input.outcome||1)*0.2'),('OrtSportsExt','0.18 + Number(input.orSpo||1)*0.2 + Number(input.orSpoType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_sports_ortho_ext102':[('SpOGenExt','0.18 + Number(input.sgGen||1)*0.2 + Number(input.sgGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpOKneeExt','0.18 + Number(input.sgKnee||1)*0.2 + Number(input.sgKneeType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpOShoulderExt','0.18 + Number(input.sgSh||1)*0.2 + Number(input.sgShType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpOHipExt','0.18 + Number(input.sgHip||1)*0.2 + Number(input.sgHipType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpOAnkleExt','0.18 + Number(input.sgAnk||1)*0.2 + Number(input.sgAnkType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpOElbowExt','0.18 + Number(input.sgElb||1)*0.2 + Number(input.sgElbType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpOWristExt','0.18 + Number(input.sgWri||1)*0.2 + Number(input.sgWriType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpOACLext','0.18 + Number(input.sgACL||1)*0.2 + Number(input.sgACLtype||1)*0.2 + Number(input.outcome||1)*0.2'),('SpOMeniscusExt','0.18 + Number(input.sgMen||1)*0.2 + Number(input.sgMenType||1)*0.2 + Number(input.outcome||1)*0.2'),('SpORotatorExt','0.18 + Number(input.sgRot||1)*0.2 + Number(input.sgRotType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_joint_replacement_ext102':[('JRGenExt','0.18 + Number(input.jrGen||1)*0.2 + Number(input.jrGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('JRHipExt','0.18 + Number(input.jrHip||1)*0.2 + Number(input.jrHipType||1)*0.2 + Number(input.outcome||1)*0.2'),('JRKneeExt','0.18 + Number(input.jrKnee||1)*0.2 + Number(input.jrKneeType||1)*0.2 + Number(input.outcome||1)*0.2'),('JRShoulderExt','0.18 + Number(input.jrSh||1)*0.2 + Number(input.jrShType||1)*0.2 + Number(input.outcome||1)*0.2'),('JRElbowExt','0.18 + Number(input.jrElb||1)*0.2 + Number(input.jrElbType||1)*0.2 + Number(input.outcome||1)*0.2'),('JRAnkleExt','0.18 + Number(input.jrAnk||1)*0.2 + Number(input.jrAnkType||1)*0.2 + Number(input.outcome||1)*0.2'),('JRWristExt','0.18 + Number(input.jrWri||1)*0.2 + Number(input.jrWriType||1)*0.2 + Number(input.outcome||1)*0.2'),('JRRevisionExt','0.18 + Number(input.jrRev||1)*0.2 + Number(input.jrRevType||1)*0.2 + Number(input.outcome||1)*0.2'),('JRRoboticExt','0.18 + Number(input.jrRob||1)*0.2 + Number(input.jrRobScore||1)*0.04 + Number(input.outcome||1)*0.2'),('JRRehabExt','0.18 + Number(input.jrReh||1)*0.2 + Number(input.jrRehScore||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.62.62.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.62.62.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.62.62.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.62.62.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NJ v3.62.62.0 done')