import os
MODULES=['pcc_neuro_ext163','pcc_pediatric_neuro_ext152','pcc_pediatric_surg_ext152']
FUNCS={
'pcc_neuro_ext163':[('DementiaAlzExt','0.18 + Number(input.alz||1)*0.2 + Number(input.mmse||1)*0.04 + Number(input.outcome||1)*0.2'),('DementiaVascularExt','0.18 + Number(input.vascDem||1)*0.2 + Number(input.hachinski||1)*0.04 + Number(input.outcome||1)*0.2'),('DementiaLewyExt','0.18 + Number(input.dlb||1)*0.2 + Number(input.visualHalluc||1)*0.2 + Number(input.outcome||1)*0.2'),('DementiaFrontotemporalExt','0.18 + Number(input.ftd||1)*0.2 + Number(input.behavioral||1)*0.2 + Number(input.outcome||1)*0.2'),('ParkinsonDementiaExt','0.18 + Number(input.pdD||1)*0.2 + Number(input.cognition||1)*0.2 + Number(input.outcome||1)*0.2'),('NormalPressureHydroExt','0.18 + Number(input.nph||1)*0.2 + Number(input.gait||1)*0.2 + Number(input.outcome||1)*0.2'),('WernickeExt','0.18 + Number(input.wernicke||1)*0.2 + Number(input.thiamine||1)*0.2 + Number(input.outcome||1)*0.2'),('CreutzfeldtJakobExt','0.18 + Number(input.cjd||1)*0.2 + Number(input.rapidDem||1)*0.2 + Number(input.outcome||1)*0.2'),('HIVAssociatedExt','0.18 + Number(input.had||1)*0.2 + Number(input.cd4||1)*0.04 + Number(input.outcome||1)*0.2'),('MildCognitiveExt','0.18 + Number(input.mci||1)*0.2 + Number(input.memory||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext152':[('PediatricDementiaExt','0.18 + Number(input.age||5)*0.04 + Number(input.pDem||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNCLext','0.18 + Number(input.age||3)*0.04 + Number(input.ncl||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTaySachsExt','0.18 + Number(input.age||1)*0.04 + Number(input.taysachs||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNiemannPickExt','0.18 + Number(input.age||1)*0.04 + Number(input.niemann||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGaucherExt','0.18 + Number(input.age||3)*0.04 + Number(input.gaucher||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPKUExt','0.18 + Number(input.age||1)*0.04 + Number(input.pku||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricWilsonExt','0.18 + Number(input.age||8)*0.04 + Number(input.wilson||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMenkesExt','0.18 + Number(input.age||0)*0.04 + Number(input.menkes||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHurlerExt','0.18 + Number(input.age||1)*0.04 + Number(input.hurler||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSanfilippoExt','0.18 + Number(input.age||3)*0.04 + Number(input.sanfilippo||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext152':[('PediatricDemSupportExt','0.18 + Number(input.age||5)*0.04 + Number(input.demSupport||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNCLsupportExt','0.18 + Number(input.age||3)*0.04 + Number(input.nclSupport||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTaySachsSupportExt','0.18 + Number(input.age||1)*0.04 + Number(input.taySupport||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNiemannSupportExt','0.18 + Number(input.age||1)*0.04 + Number(input.niemannSupport||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricGaucherERTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.gaucherERT||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPKUdietExt','0.18 + Number(input.age||1)*0.04 + Number(input.pkuDiet||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricWilsonChelationExt','0.18 + Number(input.age||8)*0.04 + Number(input.wilsonChelate||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMenkesCuExt','0.18 + Number(input.age||0)*0.04 + Number(input.cuHist||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHurlerERTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.hurlerERT||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSanfilippoSupportExt','0.18 + Number(input.age||3)*0.04 + Number(input.sanSupport||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.262.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.262.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.262.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.262.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LD v3.262.0 done')