import os
MODULES=['pcc_neuro_ext119','pcc_pediatric_neuro_ext108','pcc_pediatric_surg_ext108']
FUNCS={
'pcc_neuro_ext119':[('OpticNeuritisExt','0.18 + Number(input.eye||1)*0.2 + Number(input.pain||1)*0.2 + Number(input.outcome||1)*0.2'),('NeuromyelitisOpticaExt','0.18 + Number(input.aq4||1)*0.2 + Number(input.longitudinal||1)*0.2 + Number(input.outcome||1)*0.2'),('MOGassociatedExt','0.18 + Number(input.mog||1)*0.2 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('IschemicOpticExt','0.18 + Number(input.arteritic||1)*0.2 + Number(input.vision||1)*0.2 + Number(input.outcome||1)*0.2'),('PapilledemaExt','0.18 + Number(input.pressure||30)*0.01 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('PseudotumorCerebriExt','0.18 + Number(input.ophth||1)*0.2 + Number(input.female||1)*0.1 + Number(input.outcome||1)*0.2'),('LeberOpticExt','0.18 + Number(input.maternal||1)*0.2 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('ToxicOpticExt','0.18 + Number(input.toxin||1)*0.2 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('NutritionalOpticExt','0.18 + Number(input.b12||1)*0.2 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2'),('HereditaryOpticExt','0.18 + Number(input.family||1)*0.2 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext108':[('PediatricOpticNeuritisExt','0.18 + Number(input.age||8)*0.04 + Number(input.eye||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNMOExt','0.18 + Number(input.age||10)*0.04 + Number(input.aq4||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMOGExt','0.18 + Number(input.age||6)*0.04 + Number(input.mog||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIONExt','0.18 + Number(input.age||5)*0.04 + Number(input.arteritic||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPapilledemaExt','0.18 + Number(input.age||8)*0.04 + Number(input.pressure||30)*0.01 + Number(input.outcome||1)*0.2'),('PediatricIIHExt','0.18 + Number(input.age||10)*0.04 + Number(input.ophth||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLHONExt','0.18 + Number(input.age||12)*0.02 + Number(input.maternal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricToxicOpticExt','0.18 + Number(input.age||5)*0.04 + Number(input.toxin||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNutritionalOpticExt','0.18 + Number(input.age||5)*0.04 + Number(input.b12||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHereditaryOpticExt','0.18 + Number(input.age||5)*0.04 + Number(input.family||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext108':[('PediatricONsteroidExt','0.18 + Number(input.age||8)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNMOimmunoExt','0.18 + Number(input.age||10)*0.04 + Number(input.rituximab||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMOGsteroidExt','0.18 + Number(input.age||6)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIONsteroidExt','0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPapilledemaSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.shunt||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIIHsxExt','0.18 + Number(input.age||10)*0.04 + Number(input.opticsheath||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLHONidebenoneExt','0.18 + Number(input.age||12)*0.02 + Number(input.idebenone||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricToxicOpticExtExt','0.18 + Number(input.age||5)*0.04 + Number(input.stopToxin||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricNutritionalOpticSuppExt','0.18 + Number(input.age||5)*0.04 + Number(input.supplement||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricHereditaryOpticSuppExt','0.18 + Number(input.age||5)*0.04 + Number(input.supportive||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.218.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.218.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.218.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.218.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-JL v3.218.0 done')
