import os
MODULES=['pcc_dermatology_ext102','pcc_plastic_surgery_ext102','pcc_wound_care_ext102']
FUNCS={
'pcc_dermatology_ext102':[('DerGenExt','0.18 + Number(input.deGen||1)*0.2 + Number(input.deGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('DerEczemaExt','0.18 + Number(input.deEcz||1)*0.2 + Number(input.deEczScore||1)*0.04 + Number(input.outcome||1)*0.2'),('DerPsorExt','0.18 + Number(input.dePso||1)*0.2 + Number(input.dePsoPASI||1)*0.04 + Number(input.outcome||1)*0.2'),('DerAcneExt','0.18 + Number(input.deAcn||1)*0.2 + Number(input.deAcnGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('DerSkinCancerExt','0.18 + Number(input.deSCC||1)*0.2 + Number(input.deSCCtype||1)*0.2 + Number(input.outcome||1)*0.2'),('DerMelanomaExt','0.18 + Number(input.deMel||1)*0.2 + Number(input.deMelBreslow||1)*0.04 + Number(input.outcome||1)*0.2'),('DerInfectionExt','0.18 + Number(input.deInf||1)*0.2 + Number(input.deInfType||1)*0.2 + Number(input.outcome||1)*0.2'),('DerAutoimmuneExt','0.18 + Number(input.deAI||1)*0.2 + Number(input.deAIType||1)*0.2 + Number(input.outcome||1)*0.2'),('DerHairExt','0.18 + Number(input.deHai||1)*0.2 + Number(input.deHaiScore||1)*0.04 + Number(input.outcome||1)*0.2'),('DerNailExt','0.18 + Number(input.deNai||1)*0.2 + Number(input.deNaiType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_plastic_surgery_ext102':[('PSxGenExt','0.18 + Number(input.psGen||1)*0.2 + Number(input.psGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('PSxReconExt','0.18 + Number(input.psRec||1)*0.2 + Number(input.psRecType||1)*0.2 + Number(input.outcome||1)*0.2'),('PSxCosmetExt','0.18 + Number(input.psCos||1)*0.2 + Number(input.psCosType||1)*0.2 + Number(input.outcome||1)*0.2'),('PSxBurnExt','0.18 + Number(input.psBur||1)*0.2 + Number(input.psBurTBSA||1)*0.04 + Number(input.outcome||1)*0.2'),('PSxHandExt','0.18 + Number(input.psHnd||1)*0.2 + Number(input.psHndType||1)*0.2 + Number(input.outcome||1)*0.2'),('PSxCranioExt','0.18 + Number(input.psCrn||1)*0.2 + Number(input.psCrnType||1)*0.2 + Number(input.outcome||1)*0.2'),('PSxMicroExt','0.18 + Number(input.psMic||1)*0.2 + Number(input.psMicType||1)*0.2 + Number(input.outcome||1)*0.2'),('PSxScarExt','0.18 + Number(input.psScr||1)*0.2 + Number(input.psScrType||1)*0.2 + Number(input.outcome||1)*0.2'),('PSxFlapExt','0.18 + Number(input.psFlp||1)*0.2 + Number(input.psFlpType||1)*0.2 + Number(input.outcome||1)*0.2'),('PSxPostExt','0.18 + Number(input.psPst||1)*0.2 + Number(input.psPstDay||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_wound_care_ext102':[('WCGenExt','0.18 + Number(input.wcGen||1)*0.2 + Number(input.wcGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('WCAcuteExt','0.18 + Number(input.wcAcu||1)*0.2 + Number(input.wcAcuType||1)*0.2 + Number(input.outcome||1)*0.2'),('WCChronicExt','0.18 + Number(input.wcChr||1)*0.2 + Number(input.wcChrScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WCDiabeticExt','0.18 + Number(input.wcDia||1)*0.2 + Number(input.wcDiaGrade||1)*0.04 + Number(input.outcome||1)*0.2'),('WCPressureExt','0.18 + Number(input.wcPrs||1)*0.2 + Number(input.wcPrsStage||1)*0.04 + Number(input.outcome||1)*0.2'),('WCVascularExt','0.18 + Number(input.wcVas||1)*0.2 + Number(input.wcVasType||1)*0.2 + Number(input.outcome||1)*0.2'),('WCSurgicalExt','0.18 + Number(input.wcSur||1)*0.2 + Number(input.wcSurType||1)*0.2 + Number(input.outcome||1)*0.2'),('WCBurnExt','0.18 + Number(input.wcBur||1)*0.2 + Number(input.wcBurDepth||1)*0.04 + Number(input.outcome||1)*0.2'),('WCTraumaExt','0.18 + Number(input.wcTrv||1)*0.2 + Number(input.wcTrvScore||1)*0.04 + Number(input.outcome||1)*0.2'),('WCDressingExt','0.18 + Number(input.wcDrs||1)*0.2 + Number(input.wcDrsType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.64.64.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.64.64.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.64.64.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.64.64.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NL v3.64.64.0 done')