import os
MODULES=['pcc_neuro_ext96','pcc_pediatric_neuro_ext85','pcc_pediatric_surg_ext85']
FUNCS={
'pcc_neuro_ext96':[('SleepMedPolysomExt','0.15 + Number(input.aHI||20)*0.01 + Number(input.spo2||85)*0.005 + Number(input.central||1)*0.1'),('CPAPComplianceExt','0.2 + Number(input.usageHours||4)*0.05 + Number(input.mask||1)*0.1 + Number(input.adherence||80)*0.005'),('NarcolepsyManageExt','0.18 + Number(input.cataplexy||1)*0.2 + Number(input.modafinil||1)*0.15 + Number(input.sodiumOxybate||1)*0.15'),('RestlessLegsMgmExt','0.15 + Number(input.ferritin||50)*0.002 + Number(input.dopamine||1)*0.2 + Number(input.severity||20)*0.01'),('ParasomniasEvalExt','0.15 + Number(input.episodes||3)*0.05 + Number(input.rem||1)*0.15 + Number(input.triggers||2)*0.05'),('InsomniaCBTIExt','0.15 + Number(input.sleepOnsetLatency||30)*0.005 + Number(input.wakeAfter||3)*0.05 + Number(input.treatments||5)*0.05'),('PeriodicLimbMovementExt','0.18 + Number(input.plmsIndex||15)*0.01 + Number(input.arousals||10)*0.02 + Number(input.ferritin||50)*0.002'),('CircadianRhythmDisorderExt','0.15 + Number(input.dsps||1)*0.2 + Number(input.melatonin||1)*0.15 + Number(input.chronotherapy||1)*0.15'),('ShiftWorkDisorderExt','0.15 + Number(input.shifts||3)*0.05 + Number(input.melatonin||1)*0.15 + Number(input.modafinil||1)*0.15'),('SleepApneaSurgeryEvalExt','0.18 + Number(input.aiHI||20)*0.01 + Number(input.uyap||1)*0.2 + Number(input.bmi||30)*0.01')],
'pcc_pediatric_neuro_ext85':[('PediatricSleepStudyExt','0.15 + Number(input.ahi||5)*0.05 + Number(input.spo2||90)*0.005 + Number(input.apnea||1)*0.2'),('PediatricObstructiveSleepExt','0.18 + Number(input.adenoids||2)*0.15 + Number(input.tonsils||2)*0.15 + Number(input.bmi||20)*0.01'),('PediatricInsomniaExt','0.15 + Number(input.sleepLatency||30)*0.005 + Number(input.awakenings||3)*0.05 + Number(input.intervention||1)*0.2'),('PediatricParasomniaExt','0.15 + Number(input.episodes||3)*0.05 + Number(input.rem||1)*0.15 + Number(input.triggers||2)*0.05'),('PediatricNarcolepsyExt','0.18 + Number(input.cataplexy||1)*0.2 + Number(input.modafinil||1)*0.15 + Number(input.sodiumOxybate||1)*0.15'),('PediatricRLSExt','0.15 + Number(input.ferritin||30)*0.005 + Number(input.dopamine||1)*0.2 + Number(input.severity||20)*0.01'),('PediatricCPAPAdherenceExt','0.18 + Number(input.usage||4)*0.05 + Number(input.mask||1)*0.1 + Number(input.adherence||80)*0.005'),('PediatricSleepApneaSurgExt','0.18 + Number(input.tonsils||2)*0.15 + Number(input.age||5)*0.04 + Number(input.outcome||1)*0.2'),('PediatricCircadianEvalExt','0.15 + Number(input.dsps||1)*0.2 + Number(input.melatonin||1)*0.15 + Number(input.hygiene||1)*0.15'),('PediatricNightTerrorsExt','0.15 + Number(input.episodes||3)*0.05 + Number(input.sleepStage||1)*0.2 + Number(input.familyHist||1)*0.15')],
'pcc_pediatric_surg_ext85':[('PediatricTonsillectomySleepExt','0.18 + Number(input.age||5)*0.04 + Number(input.size||3)*0.05 + Number(input.complications||2)*0.05'),('PediatricAdenoidectomyExt','0.15 + Number(input.size||3)*0.05 + Number(input.ahi||10)*0.04 + Number(input.outcome||1)*0.2'),('PediatricTAndACombinedExt','0.18 + Number(input.age||5)*0.04 + Number(input.tonsils||3)*0.05 + Number(input.outcome||1)*0.2'),('PediatricUvulopalatopharyngoplastyExt','0.15 + Number(input.age||8)*0.03 + Number(input.size||3)*0.05 + Number(input.outcome||1)*0.2'),('PediatricCraniofacialSleepExt','0.18 + Number(input.syndrome||1)*0.2 + Number(input.midface||1)*0.15 + Number(input.outcome||1)*0.2'),('PediatricTracheostomySleepExt','0.18 + Number(input.indic||1)*0.2 + Number(input.success||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMandibleDistractionExt','0.18 + Number(input.age||5)*0.04 + Number(input.distance||15)*0.005 + Number(input.outcome||1)*0.2'),('PediatricBariatricSleepExt','0.18 + Number(input.bmi||35)*0.01 + Number(input.ahi||30)*0.01 + Number(input.outcome||1)*0.2'),('PediatricHypoglossalStimExt','0.15 + Number(input.age||10)*0.03 + Number(input.ahi||20)*0.01 + Number(input.outcome||1)*0.2'),('PediatricNasalReconstructExt','0.15 + Number(input.choanae||1)*0.2 + Number(input.stenosis||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\n// {m} engine (deterministic)\nmodule.exports.version=\'v3.195.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.195.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}};}};\n'
    eng+=f'\n// TS: v3.195.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'// filepath: pcc/{m}/{m}_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;else console.error(\'FAIL\',fn,r);}}console.log(\'{m} unit:\',pass,\'passed\');if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'// filepath: pcc/{m}/{m}_integration_test.js\nconst {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{value:1}},{{value:2}},{{value:3}},{{value:4}},{{value:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass,\'passed\');if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'// filepath: pcc/{m}/{m}_routes.js\nconst express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();\nrouter.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.195.0\',functions:Object.keys(F)}}));\nrouter.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});\nrouter.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});\nmodule.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- pcc/{m}/{m}_up.sql\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\')\nBEGIN\nCREATE TABLE [dbo].[{m}] (\n  [id] INT IDENTITY(1,1) PRIMARY KEY,\n  [tenant_id] NVARCHAR(64) NOT NULL,\n  [version] NVARCHAR(16) NOT NULL,\n  [module] NVARCHAR(64) NOT NULL,\n  [function] NVARCHAR(128) NOT NULL,\n  [input] NVARCHAR(MAX) NULL,\n  [score] DECIMAL(6,2) NULL,\n  [ts] DATETIME2 DEFAULT SYSUTCDATETIME()\n);\nEND\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files written')
print('P3-IO v3.195.0: 16 files written')
