import os
MODULES=['pcc_endocrine_ext100','pcc_metabolic_ext100','pcc_nutrition_ext100']
FUNCS={
'pcc_endocrine_ext100':[('EndoDiabetesExt','0.18 + Number(input.endoDM||1)*0.2 + Number(input.hba1c||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoThyroidExt','0.18 + Number(input.endoThyroid||1)*0.2 + Number(input.tsh||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoAdrenalExt','0.18 + Number(input.endoAdrenal||1)*0.2 + Number(input.cortisol||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoPituitaryExt','0.18 + Number(input.endoPit||1)*0.2 + Number(input.igf1||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoParathyroidExt','0.18 + Number(input.endoPTH||1)*0.2 + Number(input.calcium||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoGonadExt','0.18 + Number(input.endoGonad||1)*0.2 + Number(input.testosterone||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoPCOSext','0.18 + Number(input.endoPCOS||1)*0.2 + Number(input.amhPCOS||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoObesityExt','0.18 + Number(input.endoObesity||1)*0.2 + Number(input.bmiOb||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoLipidExt','0.18 + Number(input.endoLipid||1)*0.2 + Number(input.ldlEndo||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoBoneExt','0.18 + Number(input.endoBone||1)*0.2 + Number(input.boneDex||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_metabolic_ext100':[('MetabolicDKAext','0.18 + Number(input.metDKA||1)*0.2 + Number(input.bicarb||1)*0.04 + Number(input.outcome||1)*0.2'),('MetabolicHHSext','0.18 + Number(input.metHHS||1)*0.2 + Number(input.osm||1)*0.04 + Number(input.outcome||1)*0.2'),('MetabolicHypoExt','0.18 + Number(input.metHypo||1)*0.2 + Number(input.glucose||1)*0.04 + Number(input.outcome||1)*0.2'),('MetabolicThyroidStormExt','0.18 + Number(input.metThySt||1)*0.2 + Number(input.freeT4||1)*0.04 + Number(input.outcome||1)*0.2'),('MetabolicMyxedemaExt','0.18 + Number(input.metMyx||1)*0.2 + Number(input.tshMyx||1)*0.04 + Number(input.outcome||1)*0.2'),('MetabolicAdrenalExt','0.18 + Number(input.metAdrenal||1)*0.2 + Number(input.acth||1)*0.04 + Number(input.outcome||1)*0.2'),('MetabolicPheoExt','0.18 + Number(input.metPheo||1)*0.2 + Number(input.metanephr||1)*0.04 + Number(input.outcome||1)*0.2'),('MetabolicCarcExt','0.18 + Number(input.metCarc||1)*0.2 + Number(input.hiaa5||1)*0.04 + Number(input.outcome||1)*0.2'),('MetabolicSIADHext','0.18 + Number(input.metSIADH||1)*0.2 + Number(input.serumOsm||1)*0.04 + Number(input.outcome||1)*0.2'),('MetabolicDIext','0.18 + Number(input.metDI||1)*0.2 + Number(input.urineOsm||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_nutrition_ext100':[('NutrAssessmentExt','0.18 + Number(input.nutrAssess||1)*0.2 + Number(input.alb||1)*0.04 + Number(input.outcome||1)*0.2'),('NutrMalnutritionExt','0.18 + Number(input.nutrMaln||1)*0.2 + Number(input.weightLoss||1)*0.04 + Number(input.outcome||1)*0.2'),('NutrObesityExt','0.18 + Number(input.nutrOb||1)*0.2 + Number(input.bmiNutr||1)*0.04 + Number(input.outcome||1)*0.2'),('NutrTPNext','0.18 + Number(input.nutrTPN||1)*0.2 + Number(input.tpnDuration||1)*0.04 + Number(input.outcome||1)*0.2'),('NutrEnteralExt','0.18 + Number(input.nutrEnt||1)*0.2 + Number(input.feedingType||1)*0.2 + Number(input.outcome||1)*0.2'),('NutrDiabeticExt','0.18 + Number(input.nutrDM||1)*0.2 + Number(input.carbs||1)*0.04 + Number(input.outcome||1)*0.2'),('NutrRenalExt','0.18 + Number(input.nutrRenal||1)*0.2 + Number(input.renalDiet||1)*0.2 + Number(input.outcome||1)*0.2'),('NutrCardiacExt','0.18 + Number(input.nutrCard||1)*0.2 + Number(input.sodium||1)*0.04 + Number(input.outcome||1)*0.2'),('NutrPediatricExt','0.18 + Number(input.nutrPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2'),('NutrGeriatricExt','0.18 + Number(input.nutrGer||1)*0.2 + Number(input.gerAge||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.20.20.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.20.20.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.20.20.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.20.20.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LT v3.20.20.0 done')