import os
MODULES=['pcc_endocrinology_ext102','pcc_diabetes_ext102','pcc_thyroid_ext102']
FUNCS={
'pcc_endocrinology_ext102':[('EndoGenExt','0.18 + Number(input.enGen||1)*0.2 + Number(input.enGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('EndoPitExt','0.18 + Number(input.enPit||1)*0.2 + Number(input.enPitType||1)*0.2 + Number(input.outcome||1)*0.2'),('EndoAdrenalExt','0.18 + Number(input.enAdr||1)*0.2 + Number(input.enAdrType||1)*0.2 + Number(input.outcome||1)*0.2'),('EndoParathExt','0.18 + Number(input.enPT||1)*0.2 + Number(input.enPTlevel||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoBoneExt','0.18 + Number(input.enBone||1)*0.2 + Number(input.enBoneT||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoObesityExt','0.18 + Number(input.enOb||1)*0.2 + Number(input.enObBMI||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoLipidExt','0.18 + Number(input.enLip||1)*0.2 + Number(input.enLipScore||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoGonadExt','0.18 + Number(input.enGon||1)*0.2 + Number(input.enGonLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('EndoGrowthExt','0.18 + Number(input.enGr||1)*0.2 + Number(input.enGrType||1)*0.2 + Number(input.outcome||1)*0.2'),('EndoMENext','0.18 + Number(input.enMEN||1)*0.2 + Number(input.enMENtype||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_diabetes_ext102':[('DiaT1Ext','0.18 + Number(input.dbT1||1)*0.2 + Number(input.dbT1A1c||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaT2Ext','0.18 + Number(input.dbT2||1)*0.2 + Number(input.dbT2A1c||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaGDMext','0.18 + Number(input.dbGDM||1)*0.2 + Number(input.dbGDMScore||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaInsulinExt','0.18 + Number(input.dbIns||1)*0.2 + Number(input.dbInsTDD||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaPumpExt','0.18 + Number(input.dbPump||1)*0.2 + Number(input.dbPumpType||1)*0.2 + Number(input.outcome||1)*0.2'),('DiaCGMext','0.18 + Number(input.dbCGM||1)*0.2 + Number(input.dbCGMTime||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaDKAext','0.18 + Number(input.dbDKA||1)*0.2 + Number(input.dbDKApH||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaHHSext','0.18 + Number(input.dbHHS||1)*0.2 + Number(input.dbHHSOSM||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaHypoExt','0.18 + Number(input.dbHypo||1)*0.2 + Number(input.dbHypoScore||1)*0.04 + Number(input.outcome||1)*0.2'),('DiaCompExt','0.18 + Number(input.dbComp||1)*0.2 + Number(input.dbCompType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_thyroid_ext102':[('ThyGenExt','0.18 + Number(input.thGen||1)*0.2 + Number(input.thGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('ThyHypoExt','0.18 + Number(input.thHypo||1)*0.2 + Number(input.thHypoTSH||1)*0.04 + Number(input.outcome||1)*0.2'),('ThyHyperExt','0.18 + Number(input.thHyper||1)*0.2 + Number(input.thHyperTSH||1)*0.04 + Number(input.outcome||1)*0.2'),('ThyHashiExt','0.18 + Number(input.thHash||1)*0.2 + Number(input.thHashTPO||1)*0.04 + Number(input.outcome||1)*0.2'),('ThyGraveExt','0.18 + Number(input.thGrav||1)*0.2 + Number(input.thGravScore||1)*0.04 + Number(input.outcome||1)*0.2'),('ThyNoduleExt','0.18 + Number(input.thNod||1)*0.2 + Number(input.thNodSize||1)*0.04 + Number(input.outcome||1)*0.2'),('ThyCancerExt','0.18 + Number(input.thCan||1)*0.2 + Number(input.thCanStage||1)*0.04 + Number(input.outcome||1)*0.2'),('ThyPregExt','0.18 + Number(input.thPreg||1)*0.2 + Number(input.thPregType||1)*0.2 + Number(input.outcome||1)*0.2'),('ThyPedExt','0.18 + Number(input.thPeds||1)*0.2 + Number(input.thPedsType||1)*0.2 + Number(input.outcome||1)*0.2'),('ThySurgExt','0.18 + Number(input.thSurg||1)*0.2 + Number(input.thSurgType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.57.57.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.57.57.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.57.57.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.57.57.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NE v3.57.57.0 done')