import os
MODULES=['pcc_occupational_ext102','pcc_environmental_ext102','pcc_public_health_ext102']
FUNCS={
'pcc_occupational_ext102':[('OccGeneralExt','0.18 + Number(input.ocGen||1)*0.2 + Number(input.ocGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('OccPneumoconiosisExt','0.18 + Number(input.ocPneum||1)*0.2 + Number(input.ocPneumType||1)*0.2 + Number(input.outcome||1)*0.2'),('OccAsbestosExt','0.18 + Number(input.ocAsb||1)*0.2 + Number(input.ocAsbExp||1)*0.04 + Number(input.outcome||1)*0.2'),('OccLeadExt','0.18 + Number(input.ocLead||1)*0.2 + Number(input.ocLeadLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('OccSolventExt','0.18 + Number(input.ocSolv||1)*0.2 + Number(input.ocSolvType||1)*0.2 + Number(input.outcome||1)*0.2'),('OccNoiseExt','0.18 + Number(input.ocNoise||1)*0.2 + Number(input.ocNoiseDb||1)*0.04 + Number(input.outcome||1)*0.2'),('OccRadiationExt','0.18 + Number(input.ocRad||1)*0.2 + Number(input.ocRadDose||1)*0.04 + Number(input.outcome||1)*0.2'),('OccRepetitiveExt','0.18 + Number(input.ocRep||1)*0.2 + Number(input.ocRepType||1)*0.2 + Number(input.outcome||1)*0.2'),('OccShiftWorkExt','0.18 + Number(input.ocShift||1)*0.2 + Number(input.ocShiftType||1)*0.2 + Number(input.outcome||1)*0.2'),('OccReturnExt','0.18 + Number(input.ocReturn||1)*0.2 + Number(input.ocReturnDays||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_environmental_ext102':[('EnvAirExt','0.18 + Number(input.enAir||1)*0.2 + Number(input.enAirAqi||1)*0.04 + Number(input.outcome||1)*0.2'),('EnvWaterExt','0.18 + Number(input.enWater||1)*0.2 + Number(input.enWaterType||1)*0.2 + Number(input.outcome||1)*0.2'),('EnvSoilExt','0.18 + Number(input.enSoil||1)*0.2 + Number(input.enSoilCont||1)*0.2 + Number(input.outcome||1)*0.2'),('EnvHeatExt','0.18 + Number(input.enHeat||1)*0.2 + Number(input.enHeatTemp||1)*0.04 + Number(input.outcome||1)*0.2'),('EnvColdExt','0.18 + Number(input.enCold||1)*0.2 + Number(input.enColdTemp||1)*0.04 + Number(input.outcome||1)*0.2'),('EnvRadiationExt','0.18 + Number(input.enRad||1)*0.2 + Number(input.enRadDose||1)*0.04 + Number(input.outcome||1)*0.2'),('EnvClimateChangeExt','0.18 + Number(input.enClimate||1)*0.2 + Number(input.enClimateImpact||1)*0.2 + Number(input.outcome||1)*0.2'),('EnvVectorExt','0.18 + Number(input.enVector||1)*0.2 + Number(input.enVectorType||1)*0.2 + Number(input.outcome||1)*0.2'),('EnvFoodExt','0.18 + Number(input.enFood||1)*0.2 + Number(input.enFoodCont||1)*0.2 + Number(input.outcome||1)*0.2'),('EnvSurveillanceExt','0.18 + Number(input.enSurv||1)*0.2 + Number(input.enSurvType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_public_health_ext102':[('PHImmunizationExt','0.18 + Number(input.phImm||1)*0.2 + Number(input.phImmCoverage||1)*0.04 + Number(input.outcome||1)*0.2'),('PHSurveillanceExt','0.18 + Number(input.phSurv||1)*0.2 + Number(input.phSurvType||1)*0.2 + Number(input.outcome||1)*0.2'),('PHOutbreakExt','0.18 + Number(input.phOut||1)*0.2 + Number(input.phOutSize||1)*0.04 + Number(input.outcome||1)*0.2'),('PHHealthEdExt','0.18 + Number(input.phEd||1)*0.2 + Number(input.phEdType||1)*0.2 + Number(input.outcome||1)*0.2'),('PHPolicyExt','0.18 + Number(input.phPol||1)*0.2 + Number(input.phPolType||1)*0.2 + Number(input.outcome||1)*0.2'),('PHScreeningExt','0.18 + Number(input.phScr||1)*0.2 + Number(input.phScrType||1)*0.2 + Number(input.outcome||1)*0.2'),('PHEpidemicExt','0.18 + Number(input.phEpid||1)*0.2 + Number(input.phEpidType||1)*0.2 + Number(input.outcome||1)*0.2'),('PHCommunityExt','0.18 + Number(input.phComm||1)*0.2 + Number(input.phCommType||1)*0.2 + Number(input.outcome||1)*0.2'),('PHGlobalHealthExt','0.18 + Number(input.phGlobal||1)*0.2 + Number(input.phGlobalRegion||1)*0.2 + Number(input.outcome||1)*0.2'),('PHEvalExt','0.18 + Number(input.phEval||1)*0.2 + Number(input.phEvalType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.45.45.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.45.45.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.45.45.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.45.45.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MS v3.45.45.0 done')