import os
MODULES=['pcc_neuro_ext148','pcc_pediatric_neuro_ext137','pcc_pediatric_surg_ext137']
FUNCS={
'pcc_neuro_ext148':[('ToxicEncephalopathyExt','0.18 + Number(input.toxin||1)*0.2 + Number(input.encephalopathy||1)*0.2 + Number(input.outcome||1)*0.2'),('WernickeEncephalopathyExt','0.18 + Number(input.thiamine||1)*0.2 + Number(input.wehicke||1)*0.2 + Number(input.outcome||1)*0.2'),('KorsakoffExt','0.18 + Number(input.alcohol||1)*0.2 + Number(input.memory||1)*0.2 + Number(input.outcome||1)*0.2'),('AlcoholWithdrawalExt','0.18 + Number(input.alcohol||1)*0.2 + Number(input.withdrawal||1)*0.2 + Number(input.outcome||1)*0.2'),('AlcoholSeizureExt','0.18 + Number(input.alcohol||1)*0.2 + Number(input.seizure||1)*0.2 + Number(input.outcome||1)*0.2'),('OpioidOverdoseExt','0.18 + Number(input.opioid||1)*0.2 + Number(input.overdose||1)*0.2 + Number(input.outcome||1)*0.2'),('OpioidWithdrawalExt','0.18 + Number(input.opioid||1)*0.2 + Number(input.withdrawal||1)*0.2 + Number(input.outcome||1)*0.2'),('BenzodiazepineSedationExt','0.18 + Number(input.benzo||1)*0.2 + Number(input.sedation||1)*0.2 + Number(input.outcome||1)*0.2'),('StimulantToxicExt','0.18 + Number(input.stimulant||1)*0.2 + Number(input.toxicity||1)*0.2 + Number(input.outcome||1)*0.2'),('CocaineCerebroExt','0.18 + Number(input.cocaine||1)*0.2 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext137':[('PediatricToxicEncephExt','0.18 + Number(input.age||5)*0.04 + Number(input.toxin||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAccidentalODExt','0.18 + Number(input.age||3)*0.04 + Number(input.od||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAlcoholExt','0.18 + Number(input.age||12)*0.04 + Number(input.alcohol||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricInhalantExt','0.18 + Number(input.age||10)*0.04 + Number(input.inhalant||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCOpoisoningExt','0.18 + Number(input.age||5)*0.04 + Number(input.co||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLeadExt','0.18 + Number(input.age||3)*0.04 + Number(input.lead||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMercuryExt','0.18 + Number(input.age||5)*0.04 + Number(input.mercury||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOrganophosExt','0.18 + Number(input.age||5)*0.04 + Number(input.op||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMethemoglobinExt','0.18 + Number(input.age||1)*0.04 + Number(input.methb||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricETOHsyncopeExt','0.18 + Number(input.age||12)*0.04 + Number(input.etohSyncope||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext137':[('PediatricToxinDecontamExt','0.18 + Number(input.age||5)*0.04 + Number(input.decontam||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricAntidoteExt','0.18 + Number(input.age||5)*0.04 + Number(input.antidote||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricThiamineExt','0.18 + Number(input.age||10)*0.04 + Number(input.thiamine||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBenzoWithdrawalExt','0.18 + Number(input.age||10)*0.04 + Number(input.benzoW||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMethadoneExt','0.18 + Number(input.age||10)*0.04 + Number(input.methadone||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCOoxygenExt','0.18 + Number(input.age||5)*0.04 + Number(input.co||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLeadChelationExt','0.18 + Number(input.age||3)*0.04 + Number(input.chelation||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMercuryChelationExt','0.18 + Number(input.age||5)*0.04 + Number(input.chelation||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricOPAtropineExt','0.18 + Number(input.age||5)*0.04 + Number(input.atropine||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMethbMethyleneExt','0.18 + Number(input.age||1)*0.04 + Number(input.methylene||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.247.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.247.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.247.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.247.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-KO v3.247.0 done')