import os
MODULES=['pcc_anesth_ext100','pcc_pain_ext100','pcc_palliative_ext100']
FUNCS={
'pcc_anesth_ext100':[('AnesthGeneralExt','0.18 + Number(input.anGeneral||1)*0.2 + Number(input.asaClassAN||1)*0.04 + Number(input.outcome||1)*0.2'),('AnesthRegionalExt','0.18 + Number(input.anRegional||1)*0.2 + Number(input.blockType||1)*0.2 + Number(input.outcome||1)*0.2'),('AnesthLocalExt','0.18 + Number(input.anLocal||1)*0.2 + Number(input.localType||1)*0.2 + Number(input.outcome||1)*0.2'),('AnesthSpinalExt','0.18 + Number(input.anSpinal||1)*0.2 + Number(input.spinalLevel||1)*0.2 + Number(input.outcome||1)*0.2'),('AnesthEpiduralExt','0.18 + Number(input.anEpidural||1)*0.2 + Number(input.epidLevel||1)*0.2 + Number(input.outcome||1)*0.2'),('AnesthSedationExt','0.18 + Number(input.anSedation||1)*0.2 + Number(input.ramsayScore||1)*0.04 + Number(input.outcome||1)*0.2'),('AnesthPediatricExt','0.18 + Number(input.anPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2'),('AnesthObstetricExt','0.18 + Number(input.anObstetric||1)*0.2 + Number(input.gestAge||1)*0.04 + Number(input.outcome||1)*0.2'),('AnesthCardiacExt','0.18 + Number(input.anCardiac||1)*0.2 + Number(input.anCardiacType||1)*0.2 + Number(input.outcome||1)*0.2'),('AnesthTraumaExt','0.18 + Number(input.anTrauma||1)*0.2 + Number(input.traumaSev||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_pain_ext100':[('PainAcuteExt','0.18 + Number(input.pnAcute||1)*0.2 + Number(input.nrsScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PainChronicExt','0.18 + Number(input.pnChronic||1)*0.2 + Number(input.painDuration||1)*0.04 + Number(input.outcome||1)*0.2'),('PainNeuropathicExt','0.18 + Number(input.pnNeuro||1)*0.2 + Number(input.dn4Score||1)*0.04 + Number(input.outcome||1)*0.2'),('PainCancerExt','0.18 + Number(input.pnCancer||1)*0.2 + Number(input.cancerStage||1)*0.04 + Number(input.outcome||1)*0.2'),('PainBackExt','0.18 + Number(input.pnBack||1)*0.2 + Number(input.oswestryScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PainHeadacheExt','0.18 + Number(input.pnHead||1)*0.2 + Number(input.headFreq||1)*0.04 + Number(input.outcome||1)*0.2'),('PainOpioidExt','0.18 + Number(input.pnOpioid||1)*0.2 + Number(input.morphineDose||1)*0.04 + Number(input.outcome||1)*0.2'),('PainInterventionExt','0.18 + Number(input.pnInter||1)*0.2 + Number(input.interventionType||1)*0.2 + Number(input.outcome||1)*0.2'),('PainPediatricExt','0.18 + Number(input.pnPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2'),('PainGeriatricExt','0.18 + Number(input.pnGer||1)*0.2 + Number(input.gerAge||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_palliative_ext100':[('PallPainExt','0.18 + Number(input.plPain||1)*0.2 + Number(input.esasScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PallDyspneaExt','0.18 + Number(input.plDyspnea||1)*0.2 + Number(input.dyspneaSev||1)*0.04 + Number(input.outcome||1)*0.2'),('PallNauseaExt','0.18 + Number(input.plNausea||1)*0.2 + Number(input.nauseaFreq||1)*0.04 + Number(input.outcome||1)*0.2'),('PallConstipationExt','0.18 + Number(input.plConstip||1)*0.2 + Number(input.bristolScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PallDeliriumExt','0.18 + Number(input.plDelirium||1)*0.2 + Number(input.camScore||1)*0.2 + Number(input.outcome||1)*0.2'),('PallAnorexiaExt','0.18 + Number(input.plAnorexia||1)*0.2 + Number(input.appetiteScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PallFatigueExt','0.18 + Number(input.plFatigue||1)*0.2 + Number(input.fatigueScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PallAnxietyExt','0.18 + Number(input.plAnxiety||1)*0.2 + Number(input.hadsScore||1)*0.04 + Number(input.outcome||1)*0.2'),('PallEndOfLifeExt','0.18 + Number(input.plEOL||1)*0.2 + Number(input.eolPhase||1)*0.2 + Number(input.outcome||1)*0.2'),('PallHospiceExt','0.18 + Number(input.plHospice||1)*0.2 + Number(input.hospiceDays||1)*0.04 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.27.27.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.27.27.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.27.27.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.27.27.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MA v3.27.27.0 done')