import os
MODULES=['pcc_forensic_ext102','pcc_toxicology_ext102','pcc_legal_ext102']
FUNCS={
'pcc_forensic_ext102':[('ForensicAutopsyExt','0.18 + Number(input.frAut||1)*0.2 + Number(input.frAutType||1)*0.2 + Number(input.outcome||1)*0.2'),('ForensicToxScreenExt','0.18 + Number(input.frTox||1)*0.2 + Number(input.frToxScreen||1)*0.2 + Number(input.outcome||1)*0.2'),('ForensicDnaExt','0.18 + Number(input.frDna||1)*0.2 + Number(input.frDnaType||1)*0.2 + Number(input.outcome||1)*0.2'),('ForensicTraceExt','0.18 + Number(input.frTrace||1)*0.2 + Number(input.frTraceType||1)*0.2 + Number(input.outcome||1)*0.2'),('ForensicSerologyExt','0.18 + Number(input.frSer||1)*0.2 + Number(input.frSerType||1)*0.2 + Number(input.outcome||1)*0.2'),('ForensicAnthroExt','0.18 + Number(input.frAnth||1)*0.2 + Number(input.frAnthType||1)*0.2 + Number(input.outcome||1)*0.2'),('ForensicOdontologyExt','0.18 + Number(input.frOdonto||1)*0.2 + Number(input.frOdontoType||1)*0.2 + Number(input.outcome||1)*0.2'),('ForensicRadiologyExt','0.18 + Number(input.frRad||1)*0.2 + Number(input.frRadType||1)*0.2 + Number(input.outcome||1)*0.2'),('ForensicDigitalExt','0.18 + Number(input.frDig||1)*0.2 + Number(input.frDigType||1)*0.2 + Number(input.outcome||1)*0.2'),('ForensicReportExt','0.18 + Number(input.frReport||1)*0.2 + Number(input.frReportType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_toxicology_ext102':[('ToxDrugScreenExt','0.18 + Number(input.txDrug||1)*0.2 + Number(input.txDrugType||1)*0.2 + Number(input.outcome||1)*0.2'),('ToxAlcoholExt','0.18 + Number(input.txAlc||1)*0.2 + Number(input.txAlcLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('ToxHeavyMetalExt','0.18 + Number(input.txMetal||1)*0.2 + Number(input.txMetalType||1)*0.2 + Number(input.outcome||1)*0.2'),('ToxPesticideExt','0.18 + Number(input.txPest||1)*0.2 + Number(input.txPestType||1)*0.2 + Number(input.outcome||1)*0.2'),('ToxCOext','0.18 + Number(input.txCO||1)*0.2 + Number(input.txCOLevel||1)*0.04 + Number(input.outcome||1)*0.2'),('ToxPlantExt','0.18 + Number(input.txPlant||1)*0.2 + Number(input.txPlantType||1)*0.2 + Number(input.outcome||1)*0.2'),('ToxMushroomExt','0.18 + Number(input.txMush||1)*0.2 + Number(input.txMushType||1)*0.2 + Number(input.outcome||1)*0.2'),('ToxAnimalExt','0.18 + Number(input.txAnim||1)*0.2 + Number(input.txAnimType||1)*0.2 + Number(input.outcome||1)*0.2'),('ToxIndustrialExt','0.18 + Number(input.txInd||1)*0.2 + Number(input.txIndType||1)*0.2 + Number(input.outcome||1)*0.2'),('ToxChelationExt','0.18 + Number(input.txChel||1)*0.2 + Number(input.txChelDrug||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_legal_ext102':[('LegalMalpracticeExt','0.18 + Number(input.lgMal||1)*0.2 + Number(input.lgMalType||1)*0.2 + Number(input.outcome||1)*0.2'),('LegalConsentExt','0.18 + Number(input.lgConsent||1)*0.2 + Number(input.lgConsentType||1)*0.2 + Number(input.outcome||1)*0.2'),('LegalCapacityExt','0.18 + Number(input.lgCap||1)*0.2 + Number(input.lgCapType||1)*0.2 + Number(input.outcome||1)*0.2'),('LegalConfidentialityExt','0.18 + Number(input.lgConf||1)*0.2 + Number(input.lgConfType||1)*0.2 + Number(input.outcome||1)*0.2'),('LegalReportingExt','0.18 + Number(input.lgReport||1)*0.2 + Number(input.lgReportType||1)*0.2 + Number(input.outcome||1)*0.2'),('LegalEndOfLifeExt','0.18 + Number(input.lgEOL||1)*0.2 + Number(input.lgEolType||1)*0.2 + Number(input.outcome||1)*0.2'),('LegalReproductiveExt','0.18 + Number(input.lgRepro||1)*0.2 + Number(input.lgReproType||1)*0.2 + Number(input.outcome||1)*0.2'),('LegalResearchExt','0.18 + Number(input.lgRes||1)*0.2 + Number(input.lgResType||1)*0.2 + Number(input.outcome||1)*0.2'),('LegalResourceAllocationExt','0.18 + Number(input.lgRA||1)*0.2 + Number(input.lgRaType||1)*0.2 + Number(input.outcome||1)*0.2'),('LegalDisputeExt','0.18 + Number(input.lgDispute||1)*0.2 + Number(input.lgDisputeType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.43.43.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.43.43.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.43.43.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.43.43.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-MQ v3.43.43.0 done')