import os
MODULES=['pcc_hematology_ext102','pcc_oncology_ext102','pcc_transfusion_ext102']
FUNCS={
'pcc_hematology_ext102':[('HemGenExt','0.18 + Number(input.heGen||1)*0.2 + Number(input.heGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('HemAnemiaExt','0.18 + Number(input.heAn||1)*0.2 + Number(input.heAnHgb||1)*0.04 + Number(input.outcome||1)*0.2'),('HemSickleExt','0.18 + Number(input.heSic||1)*0.2 + Number(input.heSicType||1)*0.2 + Number(input.outcome||1)*0.2'),('HemThalExt','0.18 + Number(input.heThal||1)*0.2 + Number(input.heThalType||1)*0.2 + Number(input.outcome||1)*0.2'),('HemLeukExt','0.18 + Number(input.heLeuk||1)*0.2 + Number(input.heLeukType||1)*0.2 + Number(input.outcome||1)*0.2'),('HemLymphExt','0.18 + Number(input.heLym||1)*0.2 + Number(input.heLymType||1)*0.2 + Number(input.outcome||1)*0.2'),('HemMDSext','0.18 + Number(input.heMDS||1)*0.2 + Number(input.heMDSscore||1)*0.04 + Number(input.outcome||1)*0.2'),('HemClotExt','0.18 + Number(input.heClot||1)*0.2 + Number(input.heClotType||1)*0.2 + Number(input.outcome||1)*0.2'),('HemBleedExt','0.18 + Number(input.heBleed||1)*0.2 + Number(input.heBleedScore||1)*0.04 + Number(input.outcome||1)*0.2'),('HemTransExt','0.18 + Number(input.heTrans||1)*0.2 + Number(input.heTransType||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_oncology_ext102':[('OncGenExt','0.18 + Number(input.onGen||1)*0.2 + Number(input.onGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('OncStageExt','0.18 + Number(input.onStg||1)*0.2 + Number(input.onStgTNM||1)*0.04 + Number(input.outcome||1)*0.2'),('OncChemoExt','0.18 + Number(input.onChemo||1)*0.2 + Number(input.onChemoType||1)*0.2 + Number(input.outcome||1)*0.2'),('OncRadioExt','0.18 + Number(input.onRad||1)*0.2 + Number(input.onRadGy||1)*0.04 + Number(input.outcome||1)*0.2'),('OncImmuneExt','0.18 + Number(input.onImm||1)*0.2 + Number(input.onImmType||1)*0.2 + Number(input.outcome||1)*0.2'),('OncTargetExt','0.18 + Number(input.onTar||1)*0.2 + Number(input.onTarType||1)*0.2 + Number(input.outcome||1)*0.2'),('OncHormoneExt','0.18 + Number(input.onHor||1)*0.2 + Number(input.onHorType||1)*0.2 + Number(input.outcome||1)*0.2'),('OncSurgExt','0.18 + Number(input.onSurg||1)*0.2 + Number(input.onSurgType||1)*0.2 + Number(input.outcome||1)*0.2'),('OncSurvExt','0.18 + Number(input.onSurv||1)*0.2 + Number(input.onSurvScore||1)*0.04 + Number(input.outcome||1)*0.2'),('OncPallExt','0.18 + Number(input.onPal||1)*0.2 + Number(input.onPalScore||1)*0.04 + Number(input.outcome||1)*0.2')],
'pcc_transfusion_ext102':[('TxGenExt','0.18 + Number(input.trGen||1)*0.2 + Number(input.trGenType||1)*0.2 + Number(input.outcome||1)*0.2'),('TxRBCext','0.18 + Number(input.trRBC||1)*0.2 + Number(input.trRBCunit||1)*0.04 + Number(input.outcome||1)*0.2'),('TxPLText','0.18 + Number(input.trPLT||1)*0.2 + Number(input.trPLTcount||1)*0.04 + Number(input.outcome||1)*0.2'),('TxFFPext','0.18 + Number(input.trFFP||1)*0.2 + Number(input.trFFPtype||1)*0.2 + Number(input.outcome||1)*0.2'),('TxCryoExt','0.18 + Number(input.trCryo||1)*0.2 + Number(input.trCryoType||1)*0.2 + Number(input.outcome||1)*0.2'),('TxTypeCrossExt','0.18 + Number(input.trTC||1)*0.2 + Number(input.trTCtype||1)*0.2 + Number(input.outcome||1)*0.2'),('TxMassiveExt','0.18 + Number(input.trMass||1)*0.2 + Number(input.trMassScore||1)*0.04 + Number(input.outcome||1)*0.2'),('TxReactionExt','0.18 + Number(input.trRx||1)*0.2 + Number(input.trRxType||1)*0.2 + Number(input.outcome||1)*0.2'),('TxIrradiatedExt','0.18 + Number(input.trIrr||1)*0.2 + Number(input.trIrrType||1)*0.2 + Number(input.outcome||1)*0.2'),('TxConsentExt','0.18 + Number(input.trCon||1)*0.2 + Number(input.trConType||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.58.58.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.58.58.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.58.58.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.58.58.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-NF v3.58.58.0 done')