import os
MODULES=['pcc_neuro_ext193','pcc_pediatric_neuro_ext182','pcc_pediatric_surg_ext182']
FUNCS={
'pcc_neuro_ext193':[('EpilepsyAdultFocalExt','0.18 + Number(input.epAdultFocal||1)*0.2 + Number(input.focalOnset||1)*0.04 + Number(input.outcome||1)*0.2'),('EpilepsyAdultGeneralizedExt','0.18 + Number(input.epAdultGen||1)*0.2 + Number(input.genOnset||1)*0.04 + Number(input.outcome||1)*0.2'),('StatusEpilepticusAdultExt','0.18 + Number(input.seAdult||1)*0.2 + Number(input.duration||1)*0.04 + Number(input.outcome||1)*0.2'),('EpilepsyPregnancyExt','0.18 + Number(input.epPreg||1)*0.2 + Number(input.gestAge||1)*0.04 + Number(input.outcome||1)*0.2'),('EpilepsyElderlyExt','0.18 + Number(input.epElderly||1)*0.2 + Number(input.ageElderly||1)*0.04 + Number(input.outcome||1)*0.2'),('EpilepsySurgeryAdultExt','0.18 + Number(input.epSxAdult||1)*0.2 + Number(input.candidate||1)*0.2 + Number(input.outcome||1)*0.2'),('VNSadultExt','0.18 + Number(input.vnsAdult||1)*0.2 + Number(input.vnsSettings||1)*0.2 + Number(input.outcome||1)*0.2'),('RNSadultExt','0.18 + Number(input.rnsAdult||1)*0.2 + Number(input.rnsDetect||1)*0.2 + Number(input.outcome||1)*0.2'),('EpilepsyDietAdultExt','0.18 + Number(input.epDietAdult||1)*0.2 + Number(input.keto||1)*0.2 + Number(input.outcome||1)*0.2'),('SUDEPadultExt','0.18 + Number(input.sudepAdult||1)*0.2 + Number(input.risk||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext182':[('PediatricEpilepsyExt','0.18 + Number(input.age||5)*0.04 + Number(input.pEp||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpilepsyFocalExt','0.18 + Number(input.age||5)*0.04 + Number(input.pEpFocal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpilepsyGeneralizedExt','0.18 + Number(input.age||5)*0.04 + Number(input.pEpGen||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricStatusEpilepticusExt','0.18 + Number(input.age||3)*0.04 + Number(input.pSE||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFebrileSeizureExt','0.18 + Number(input.age||2)*0.04 + Number(input.pFebSz||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricInfantileSpasmExt','0.18 + Number(input.age||0)*0.04 + Number(input.pIS||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLennoxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pLennox||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpilepsySurgeryExt','0.18 + Number(input.age||5)*0.04 + Number(input.pEpSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDietEpilepsyExt','0.18 + Number(input.age||3)*0.04 + Number(input.pDietEp||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpilepsyVaccineExt','0.18 + Number(input.age||1)*0.04 + Number(input.pEpVacc||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext182':[('PediatricEpilepsySxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pEpSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpSxFocalExt','0.18 + Number(input.age||5)*0.04 + Number(input.pEpSxFocal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpSxGenExt','0.18 + Number(input.age||5)*0.04 + Number(input.pEpSxGen||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricSETxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pSETx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricFebSzTxExt','0.18 + Number(input.age||2)*0.04 + Number(input.pFebSzTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricISTxExt','0.18 + Number(input.age||0)*0.04 + Number(input.pISTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricLennoxTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pLennoxTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpSxTxExt','0.18 + Number(input.age||5)*0.04 + Number(input.pEpSxTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricDietEpTxExt','0.18 + Number(input.age||3)*0.04 + Number(input.pDietEpTx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricEpVaccTxExt','0.18 + Number(input.age||1)*0.04 + Number(input.pEpVaccTx||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.22.22.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.22.22.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.22.22.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.22.22.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-HV v3.22.22.0 done')