import os
MODULES=['pcc_neuro_ext164','pcc_pediatric_neuro_ext153','pcc_pediatric_surg_ext153']
FUNCS={
'pcc_neuro_ext164':[('HeadacheMigraineExt','0.18 + Number(input.migraine||1)*0.2 + Number(input.frequency||1)*0.04 + Number(input.outcome||1)*0.2'),('TensionHeadacheExt','0.18 + Number(input.tth||1)*0.2 + Number(input.pericranial||1)*0.2 + Number(input.outcome||1)*0.2'),('ClusterHeadacheExt','0.18 + Number(input.cluster||1)*0.2 + Number(input.horner||1)*0.2 + Number(input.outcome||1)*0.2'),('MedicationOveruseExt','0.18 + Number(input.moh||1)*0.2 + Number(input.analgesic||1)*0.2 + Number(input.outcome||1)*0.2'),('TrigeminalAutonomicExt','0.18 + Number(input.tac||1)*0.2 + Number(input.autonomic||1)*0.2 + Number(input.outcome||1)*0.2'),('ThunderclapHeadacheExt','0.18 + Number(input.thunderclap||1)*0.2 + Number(input.worst||1)*0.2 + Number(input.outcome||1)*0.2'),('SexualHeadacheExt','0.18 + Number(input.orgasmHeadache||1)*0.2 + Number(input.exertional||1)*0.2 + Number(input.outcome||1)*0.2'),('CoughHeadacheExt','0.18 + Number(input.coughHeadache||1)*0.2 + Number(input.valsalva||1)*0.2 + Number(input.outcome||1)*0.2'),('HypnicHeadacheExt','0.18 + Number(input.hypnic||1)*0.2 + Number(input.nightly||1)*0.2 + Number(input.outcome||1)*0.2'),('IdiopathicIntracranialExt','0.18 + Number(input.iih||1)*0.2 + Number(input.papilledema||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_neuro_ext153':[('PediatricMigraineExt','0.18 + Number(input.age||8)*0.04 + Number(input.pMigraine||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTTHext','0.18 + Number(input.age||8)*0.04 + Number(input.pTTH||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricClusterExt','0.18 + Number(input.age||10)*0.04 + Number(input.pCluster||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMOHext','0.18 + Number(input.age||12)*0.04 + Number(input.pMOH||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChronicDailyExt','0.18 + Number(input.age||10)*0.04 + Number(input.pCDH||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIIHext','0.18 + Number(input.age||10)*0.04 + Number(input.pIIH||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCSFleakExt','0.18 + Number(input.age||10)*0.04 + Number(input.pCSFleak||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPostTraumaticExt','0.18 + Number(input.age||5)*0.04 + Number(input.pPostTraumaHead||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChiariExt','0.18 + Number(input.age||8)*0.04 + Number(input.pChiari||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricBrainTumorHeadExt','0.18 + Number(input.age||5)*0.04 + Number(input.pTumorHead||1)*0.2 + Number(input.outcome||1)*0.2')],
'pcc_pediatric_surg_ext153':[('PediatricMigraineAbortExt','0.18 + Number(input.age||8)*0.04 + Number(input.migAbort||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMigrainePrevExt','0.18 + Number(input.age||8)*0.04 + Number(input.migPrev||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTTHanalgesicExt','0.18 + Number(input.age||8)*0.04 + Number(input.tthAnal||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricClusterO2Ext','0.18 + Number(input.age||10)*0.04 + Number(input.clusterO2||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricMOHdetoxExt','0.18 + Number(input.age||12)*0.04 + Number(input.mohDetox||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricIIHacetazolExt','0.18 + Number(input.age||10)*0.04 + Number(input.iihAcet||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricCSFpatchExt','0.18 + Number(input.age||10)*0.04 + Number(input.csfPatch||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricPostTraumaRestExt','0.18 + Number(input.age||5)*0.04 + Number(input.postTraumaRest||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricChiariSxExt','0.18 + Number(input.age||8)*0.04 + Number(input.chiariSx||1)*0.2 + Number(input.outcome||1)*0.2'),('PediatricTumorOncoExt','0.18 + Number(input.age||5)*0.04 + Number(input.tumorOnco||1)*0.2 + Number(input.outcome||1)*0.2')]}
for m in MODULES:
    d=f'./{m}'
    os.makedirs(d, exist_ok=True)
    eng=f'// filepath: pcc/{m}/{m}_engine.js\nmodule.exports.version=\'v3.263.0\';\nmodule.exports.module=\'{m}\';\nmodule.exports.functions={{}};\n'
    for fn,body in FUNCS[m]:
        eng+=f'module.exports.functions[\'{fn}\']=function(input){{const score=Math.round(({body})*100)/100;return{{version:\'v3.263.0\',module:\'{m}\',function:\'{fn}\',input,score,ts:new Date().toISOString()}}}};\n'
    eng+=f'\n// TS: v3.263.0\n'
    open(f'{d}/{m}_engine.js','w',encoding='utf-8').write(eng)
    test=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;for(const fn of Object.keys(F)){{const r=F[fn]({{}});if(typeof r.score===\'number\'&&r.score>=0&&r.score<=1.5)pass++;}}console.log(\'{m} unit:\',pass);if(pass!==10)process.exit(1);\n'
    open(f'{d}/{m}_test.js','w',encoding='utf-8').write(test)
    itest=f'const {{functions:F}}=require(\'./{m}_engine\');let pass=0;const samples=[{{v:1}},{{v:2}},{{v:3}},{{v:4}},{{v:5}}];for(const fn of Object.keys(F)){{for(const s of samples){{const r=F[fn](s);if(r&&typeof r.score===\'number\')pass++;}}}}console.log(\'{m} integration:\',pass);if(pass!==50)process.exit(1);\n'
    open(f'{d}/{m}_integration_test.js','w',encoding='utf-8').write(itest)
    routes=f'const express=require(\'express\');const {{functions:F}}=require(\'./{m}_engine\');const {{authenticate}}=require(\'../middleware\');const router=express.Router();router.get(\'/list\',(_req,res)=>res.json({{module:\'{m}\',version:\'v3.263.0\',functions:Object.keys(F)}}));router.post(\'/call/:fn\',(req,res)=>{{const fn=req.params.fn;if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](req.body||{{}});res.json(r);}});router.post(\'/record\',(req,res)=>{{const {{fn,payload,decisionId}}=req.body||{{}};if(!F[fn])return res.status(404).json({{error:\'not found\'}});const r=F[fn](payload||{{}});res.json({{decisionId,...r}});}});module.exports=router;\n'
    open(f'{d}/{m}_routes.js','w',encoding='utf-8').write(routes)
    sql=f'-- {m} up\nIF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[dbo].[{m}]\') AND type = \'U\') BEGIN CREATE TABLE [dbo].[{m}] ([id] INT IDENTITY(1,1) PRIMARY KEY,[tenant_id] NVARCHAR(64) NOT NULL,[version] NVARCHAR(16) NOT NULL,[module] NVARCHAR(64) NOT NULL,[function] NVARCHAR(128) NOT NULL,[input] NVARCHAR(MAX) NULL,[score] DECIMAL(6,2) NULL,[ts] DATETIME2 DEFAULT SYSUTCDATETIME()); END\n'
    open(f'{d}/{m}_up.sql','w',encoding='utf-8').write(sql)
    print(f'{m}: 5 files')
print('P3-LE v3.263.0 done')