// filepath: pcc/pcc_pediatric_neuro_ext161/pcc_pediatric_neuro_ext161_engine.js
module.exports.version='v3.1.1.0';
module.exports.module='pcc_pediatric_neuro_ext161';
module.exports.functions={};
module.exports.functions['PediatricBrainTumor2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pBrainT2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_pediatric_neuro_ext161',function:'PediatricBrainTumor2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeuroblastomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.neuroblastoma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_pediatric_neuro_ext161',function:'PediatricNeuroblastomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOpticPathwayExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.opg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_pediatric_neuro_ext161',function:'PediatricOpticPathwayExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinalTumor2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pSpinalT2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_pediatric_neuro_ext161',function:'PediatricSpinalTumor2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricATRT2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pATRT2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_pediatric_neuro_ext161',function:'PediatricATRT2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLCHneuroExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.lchNeuro||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_pediatric_neuro_ext161',function:'PediatricLCHneuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGCText']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pGCT||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_pediatric_neuro_ext161',function:'PediatricGCText',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPNEText']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pPNET||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_pediatric_neuro_ext161',function:'PediatricPNEText',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricParaneoExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pParaneo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_pediatric_neuro_ext161',function:'PediatricParaneoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOpsomyocExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pOpsomyoc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.1.0',module:'pcc_pediatric_neuro_ext161',function:'PediatricOpsomyocExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.1.0
