// Auto_generated by gen_p3ib.py -- PCC v3.182.0
"use strict";
const TS = '2026-07-28T14:30:00Z';

function AtaxiaTelangiectasiaExt(input) { const score = Math.round((0.4+Number(input.atm||0)*0.2)*100)/100; return { version:'3.182.0', module:'pcc_neuro_ext83', function:"AtaxiaTelangiectasiaExt", input, score, ts: TS }; }

function FriedreichAtaxiaExt(input) { const score = Math.round((0.4+Number(input.repeats||500)*0.0006)*100)/100; return { version:'3.182.0', module:'pcc_neuro_ext83', function:"FriedreichAtaxiaExt", input, score, ts: TS }; }

function SpinocerebellarAtaxiaExt(input) { const score = Math.round((0.4+Number(input.repeats||40)*0.005)*100)/100; return { version:'3.182.0', module:'pcc_neuro_ext83', function:"SpinocerebellarAtaxiaExt", input, score, ts: TS }; }

function MSAExt(input) { const score = Math.round((0.4+Number(input.autonomic_severity||3)*0.1)*100)/100; return { version:'3.182.0', module:'pcc_neuro_ext83', function:"MSAExt", input, score, ts: TS }; }

function CerebellarAtaxiaExt(input) { const score = Math.round((0.35+Number(input.cerebellar_score||3)*0.1)*100)/100; return { version:'3.182.0', module:'pcc_neuro_ext83', function:"CerebellarAtaxiaExt", input, score, ts: TS }; }

function SensoryAtaxiaExt(input) { const score = Math.round((0.35+Number(input.sensory_loss||3)*0.1)*100)/100; return { version:'3.182.0', module:'pcc_neuro_ext83', function:"SensoryAtaxiaExt", input, score, ts: TS }; }

function VestibularAtaxiaExt(input) { const score = Math.round((0.35+Number(input.vestibular_loss||30)*0.012)*100)/100; return { version:'3.182.0', module:'pcc_neuro_ext83', function:"VestibularAtaxiaExt", input, score, ts: TS }; }

function AtaxiaGeneticExt(input) { const score = Math.round((0.4+Number(input.gene||0)*0.15)*100)/100; return { version:'3.182.0', module:'pcc_neuro_ext83', function:"AtaxiaGeneticExt", input, score, ts: TS }; }

function AtaxiaRehabExt(input) { const score = Math.round((0.3+Number(input.balance_score||30)*0.02)*100)/100; return { version:'3.182.0', module:'pcc_neuro_ext83', function:"AtaxiaRehabExt", input, score, ts: TS }; }

function AtaxiaMetabolicExt(input) { const score = Math.round((0.35+Number(input.csf_lactate||2)*0.15)*100)/100; return { version:'3.182.0', module:'pcc_neuro_ext83', function:"AtaxiaMetabolicExt", input, score, ts: TS }; }

module.exports = {
  AtaxiaTelangiectasiaExt,
  FriedreichAtaxiaExt,
  SpinocerebellarAtaxiaExt,
  MSAExt,
  CerebellarAtaxiaExt,
  SensoryAtaxiaExt,
  VestibularAtaxiaExt,
  AtaxiaGeneticExt,
  AtaxiaRehabExt,
  AtaxiaMetabolicExt,
};