-- coe_105 reverse
BEGIN;
DROP TABLE IF EXISTS coe_105_results CASCADE;
DROP TABLE IF EXISTS coe_105_orders  CASCADE;
DROP TABLE IF EXISTS coe_105_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_COE_105_up';
COMMIT;
