// filepath: pcc/pcc_pediatric_surg_ext121/pcc_pediatric_surg_ext121_engine.js
module.exports.version='v3.231.0';
module.exports.module='pcc_pediatric_surg_ext121';
module.exports.functions={};
module.exports.functions['PediatricToxicChelationExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.chelation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.231.0',module:'pcc_pediatric_surg_ext121',function:'PediatricToxicChelationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHeavyMetalChelationExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.chelation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.231.0',module:'pcc_pediatric_surg_ext121',function:'PediatricHeavyMetalChelationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricManganeseEDTAExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.edta||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.231.0',module:'pcc_pediatric_surg_ext121',function:'PediatricManganeseEDTAExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSolventSupportExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.support||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.231.0',module:'pcc_pediatric_surg_ext121',function:'PediatricSolventSupportExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAlcoholThiamineExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.thiamine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.231.0',module:'pcc_pediatric_surg_ext121',function:'PediatricAlcoholThiamineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWernickeThiamineExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.thiamine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.231.0',module:'pcc_pediatric_surg_ext121',function:'PediatricWernickeThiamineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricKorsakoffThiamineExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.thiamine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.231.0',module:'pcc_pediatric_surg_ext121',function:'PediatricKorsakoffThiamineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCerebellarThiamineExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.thiamine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.231.0',module:'pcc_pediatric_surg_ext121',function:'PediatricCerebellarThiamineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMarchiafavaThiamineExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.thiamine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.231.0',module:'pcc_pediatric_surg_ext121',function:'PediatricMarchiafavaThiamineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAlcoholWithdrawalBZDext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.benzodiazepine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.231.0',module:'pcc_pediatric_surg_ext121',function:'PediatricAlcoholWithdrawalBZDext',input,score,ts:new Date().toISOString()}};

// TS: v3.231.0
