// filepath: pcc/pcc_pediatric_neuro_ext102/pcc_pediatric_neuro_ext102_engine.js
module.exports.version='v3.212.0';
module.exports.module='pcc_pediatric_neuro_ext102';
module.exports.functions={};
module.exports.functions['PediatricDementiaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.develop||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_neuro_ext102',function:'PediatricDementiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNCLext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.lipofuscin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_neuro_ext102',function:'PediatricNCLext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTaySachsExt']=function(input){const score=Math.round((0.18 + Number(input.age||2)*0.04 + Number(input.hexa||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_neuro_ext102',function:'PediatricTaySachsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNiemannPickExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.smpd1||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_neuro_ext102',function:'PediatricNiemannPickExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGauchersExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.gba||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_neuro_ext102',function:'PediatricGauchersExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricKrabbeExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.galc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_neuro_ext102',function:'PediatricKrabbeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMLDext']=function(input){const score=Math.round((0.18 + Number(input.age||2)*0.04 + Number(input.arsa||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_neuro_ext102',function:'PediatricMLDext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricALDext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.abcd1||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_neuro_ext102',function:'PediatricALDext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPKUExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pah||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_neuro_ext102',function:'PediatricPKUExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHomocystinuriaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cbs||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.212.0',module:'pcc_pediatric_neuro_ext102',function:'PediatricHomocystinuriaExt',input,score,ts:new Date().toISOString()}};

// TS: v3.212.0
