// filepath: pcc/pcc_neuro_ext197/pcc_neuro_ext197_engine.js
module.exports.version='v3.26.26.0';
module.exports.module='pcc_neuro_ext197';
module.exports.functions={};
module.exports.functions['CerebellarAdultExt']=function(input){const score=Math.round((0.18 + Number(input.cerebellarAdult||1)*0.2 + Number(input.icars||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_neuro_ext197',function:'CerebellarAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SpinocerebellarAdultExt']=function(input){const score=Math.round((0.18 + Number(input.scaAdult||1)*0.2 + Number(input.scaType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_neuro_ext197',function:'SpinocerebellarAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['FriedreichAdultExt']=function(input){const score=Math.round((0.18 + Number(input.faAdult||1)*0.2 + Number(input.frataxin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_neuro_ext197',function:'FriedreichAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AtaxiaTelangiectasiaAdultExt']=function(input){const score=Math.round((0.18 + Number(input.atAdult||1)*0.2 + Number(input.atmGene||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_neuro_ext197',function:'AtaxiaTelangiectasiaAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MSAadultExt']=function(input){const score=Math.round((0.18 + Number(input.msaAdult||1)*0.2 + Number(input.msaType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_neuro_ext197',function:'MSAadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PSPadultExt']=function(input){const score=Math.round((0.18 + Number(input.pspAdult||1)*0.2 + Number(input.pspVariant||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_neuro_ext197',function:'PSPadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CBGDadultExt']=function(input){const score=Math.round((0.18 + Number(input.cbgdAdult||1)*0.2 + Number(input.cbgdType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_neuro_ext197',function:'CBGDadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HuntingtonAdultExt']=function(input){const score=Math.round((0.18 + Number(input.hdAdult||1)*0.2 + Number(input.cagRepeat||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_neuro_ext197',function:'HuntingtonAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ChoreaSydenhamAdultExt']=function(input){const score=Math.round((0.18 + Number(input.sydenhamAdult||1)*0.2 + Number(input.strepInf||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_neuro_ext197',function:'ChoreaSydenhamAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['WilsonAdultExt2']=function(input){const score=Math.round((0.18 + Number(input.wilsonA||1)*0.2 + Number(input.copperLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.26.26.0',module:'pcc_neuro_ext197',function:'WilsonAdultExt2',input,score,ts:new Date().toISOString()}};

// TS: v3.26.26.0
