// filepath: pcc/pcc_lab_ext167/pcc_lab_ext167_engine.js
module.exports.version='v3.14.14.0';
module.exports.module='pcc_lab_ext167';
module.exports.functions={};
module.exports.functions['LabTumorMarkerAdultExt']=function(input){const score=Math.round((0.18 + Number(input.tmAdult||1)*0.2 + Number(input.marker||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_lab_ext167',function:'LabTumorMarkerAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LabPSAadultExt']=function(input){const score=Math.round((0.18 + Number(input.psaAdult||1)*0.2 + Number(input.psaLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_lab_ext167',function:'LabPSAadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LabCEAadultExt']=function(input){const score=Math.round((0.18 + Number(input.ceaAdult||1)*0.2 + Number(input.ceaLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_lab_ext167',function:'LabCEAadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LabCA125AdultExt']=function(input){const score=Math.round((0.18 + Number(input.ca125Adult||1)*0.2 + Number(input.ca125Level||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_lab_ext167',function:'LabCA125AdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LabCA199AdultExt']=function(input){const score=Math.round((0.18 + Number(input.ca199Adult||1)*0.2 + Number(input.ca199Level||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_lab_ext167',function:'LabCA199AdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LabAFPadultExt']=function(input){const score=Math.round((0.18 + Number(input.afpAdult||1)*0.2 + Number(input.afpLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_lab_ext167',function:'LabAFPadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LabHCGadultExt']=function(input){const score=Math.round((0.18 + Number(input.hcgAdult||1)*0.2 + Number(input.hcgLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_lab_ext167',function:'LabHCGadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LabTumorLiquidBxExt']=function(input){const score=Math.round((0.18 + Number(input.ctdna||1)*0.2 + Number(input.mutation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_lab_ext167',function:'LabTumorLiquidBxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LabThyroAdultExt']=function(input){const score=Math.round((0.18 + Number(input.thyroAdult||1)*0.2 + Number(input.tsh||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_lab_ext167',function:'LabThyroAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LabFerritinAdultExt']=function(input){const score=Math.round((0.18 + Number(input.ferritinAdult||1)*0.2 + Number(input.ferritinLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_lab_ext167',function:'LabFerritinAdultExt',input,score,ts:new Date().toISOString()}};

// TS: v3.14.14.0
