// filepath: pcc/pcc_nurse_practitioner_ext102/pcc_nurse_practitioner_ext102_engine.js
module.exports.version='v3.73.73.0';
module.exports.module='pcc_nurse_practitioner_ext102';
module.exports.functions={};
module.exports.functions['NPGenExt']=function(input){const score=Math.round((0.18 + Number(input.npGen||1)*0.2 + Number(input.npGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_nurse_practitioner_ext102',function:'NPGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NPAssessExt']=function(input){const score=Math.round((0.18 + Number(input.npAs||1)*0.2 + Number(input.npAsScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_nurse_practitioner_ext102',function:'NPAssessExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NPDiagnosisExt']=function(input){const score=Math.round((0.18 + Number(input.npDx||1)*0.2 + Number(input.npDxScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_nurse_practitioner_ext102',function:'NPDiagnosisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NPTreatExt']=function(input){const score=Math.round((0.18 + Number(input.npTx||1)*0.2 + Number(input.npTxType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_nurse_practitioner_ext102',function:'NPTreatExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NPRxExt']=function(input){const score=Math.round((0.18 + Number(input.npRx||1)*0.2 + Number(input.npRxType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_nurse_practitioner_ext102',function:'NPRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NPFollowExt']=function(input){const score=Math.round((0.18 + Number(input.npFo||1)*0.2 + Number(input.npFoScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_nurse_practitioner_ext102',function:'NPFollowExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NPEduExt']=function(input){const score=Math.round((0.18 + Number(input.npEd||1)*0.2 + Number(input.npEdType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_nurse_practitioner_ext102',function:'NPEduExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NPConsultExt']=function(input){const score=Math.round((0.18 + Number(input.npCo||1)*0.2 + Number(input.npCoType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_nurse_practitioner_ext102',function:'NPConsultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NPSpecialtyExt']=function(input){const score=Math.round((0.18 + Number(input.npSp||1)*0.2 + Number(input.npSpType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_nurse_practitioner_ext102',function:'NPSpecialtyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NPQualityExt']=function(input){const score=Math.round((0.18 + Number(input.npQ||1)*0.2 + Number(input.npQScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.73.73.0',module:'pcc_nurse_practitioner_ext102',function:'NPQualityExt',input,score,ts:new Date().toISOString()}};

// TS: v3.73.73.0
