// filepath: pcc/pcc_pediatric_neuro_ext95/pcc_pediatric_neuro_ext95_engine.js
// pcc_pediatric_neuro_ext95 engine (deterministic)
module.exports.version='v3.205.0';
module.exports.module='pcc_pediatric_neuro_ext95';
module.exports.functions={};
module.exports.functions['PediatricVertebralDissectExt']=function(input){const score=Math.round((0.18 + Number(input.trauma||1)*0.2 + Number(input.dissection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.205.0',module:'pcc_pediatric_neuro_ext95',function:'PediatricVertebralDissectExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCarotidDissectExt']=function(input){const score=Math.round((0.18 + Number(input.trauma||1)*0.2 + Number(input.dissection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.205.0',module:'pcc_pediatric_neuro_ext95',function:'PediatricCarotidDissectExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricIntracranialStentExt']=function(input){const score=Math.round((0.18 + Number(input.stenosis||70)*0.005 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.205.0',module:'pcc_pediatric_neuro_ext95',function:'PediatricIntracranialStentExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricVenousStentExt']=function(input){const score=Math.round((0.18 + Number(input.stenosis||50)*0.005 + Number(input.stent||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.205.0',module:'pcc_pediatric_neuro_ext95',function:'PediatricVenousStentExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCarotidBodyTumorExt']=function(input){const score=Math.round((0.18 + Number(input.size||3)*0.1 + Number(input.vessels||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.205.0',module:'pcc_pediatric_neuro_ext95',function:'PediatricCarotidBodyTumorExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricMoyamoyaPregExt']=function(input){const score=Math.round((0.18 + Number(input.age||15)*0.04 + Number(input.week||20)*0.01 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.205.0',module:'pcc_pediatric_neuro_ext95',function:'PediatricMoyamoyaPregExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStrokePregExt']=function(input){const score=Math.round((0.18 + Number(input.age||15)*0.04 + Number(input.trimester||1)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.205.0',module:'pcc_pediatric_neuro_ext95',function:'PediatricStrokePregExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricPostpartumStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.days||7)*0.04 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.205.0',module:'pcc_pediatric_neuro_ext95',function:'PediatricPostpartumStrokeExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['NeonatalArterialStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.days||3)*0.1 + Number(input.stroke||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.205.0',module:'pcc_pediatric_neuro_ext95',function:'NeonatalArterialStrokeExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['NeonatalCerebralVenousExt']=function(input){const score=Math.round((0.18 + Number(input.days||5)*0.04 + Number(input.thrombosis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.205.0',module:'pcc_pediatric_neuro_ext95',function:'NeonatalCerebralVenousExt',input,score,ts:new Date().toISOString()};};

// TS: v3.205.0
