// filepath: pcc/pcc_neuro_ext193/pcc_neuro_ext193_engine.js
module.exports.version='v3.22.22.0';
module.exports.module='pcc_neuro_ext193';
module.exports.functions={};
module.exports.functions['EpilepsyAdultFocalExt']=function(input){const score=Math.round((0.18 + Number(input.epAdultFocal||1)*0.2 + Number(input.focalOnset||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.22.22.0',module:'pcc_neuro_ext193',function:'EpilepsyAdultFocalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EpilepsyAdultGeneralizedExt']=function(input){const score=Math.round((0.18 + Number(input.epAdultGen||1)*0.2 + Number(input.genOnset||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.22.22.0',module:'pcc_neuro_ext193',function:'EpilepsyAdultGeneralizedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['StatusEpilepticusAdultExt']=function(input){const score=Math.round((0.18 + Number(input.seAdult||1)*0.2 + Number(input.duration||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.22.22.0',module:'pcc_neuro_ext193',function:'StatusEpilepticusAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EpilepsyPregnancyExt']=function(input){const score=Math.round((0.18 + Number(input.epPreg||1)*0.2 + Number(input.gestAge||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.22.22.0',module:'pcc_neuro_ext193',function:'EpilepsyPregnancyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EpilepsyElderlyExt']=function(input){const score=Math.round((0.18 + Number(input.epElderly||1)*0.2 + Number(input.ageElderly||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.22.22.0',module:'pcc_neuro_ext193',function:'EpilepsyElderlyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EpilepsySurgeryAdultExt']=function(input){const score=Math.round((0.18 + Number(input.epSxAdult||1)*0.2 + Number(input.candidate||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.22.22.0',module:'pcc_neuro_ext193',function:'EpilepsySurgeryAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VNSadultExt']=function(input){const score=Math.round((0.18 + Number(input.vnsAdult||1)*0.2 + Number(input.vnsSettings||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.22.22.0',module:'pcc_neuro_ext193',function:'VNSadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RNSadultExt']=function(input){const score=Math.round((0.18 + Number(input.rnsAdult||1)*0.2 + Number(input.rnsDetect||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.22.22.0',module:'pcc_neuro_ext193',function:'RNSadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EpilepsyDietAdultExt']=function(input){const score=Math.round((0.18 + Number(input.epDietAdult||1)*0.2 + Number(input.keto||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.22.22.0',module:'pcc_neuro_ext193',function:'EpilepsyDietAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SUDEPadultExt']=function(input){const score=Math.round((0.18 + Number(input.sudepAdult||1)*0.2 + Number(input.risk||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.22.22.0',module:'pcc_neuro_ext193',function:'SUDEPadultExt',input,score,ts:new Date().toISOString()}};

// TS: v3.22.22.0
