// filepath: pcc/pcc_pediatric_neuro_ext167/pcc_pediatric_neuro_ext167_engine.js
module.exports.version='v3.1.7.0';
module.exports.module='pcc_pediatric_neuro_ext167';
module.exports.functions={};
module.exports.functions['PediatricChronicPainExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pChronicPain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_neuro_ext167',function:'PediatricChronicPainExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCRPSext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pCRPS||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_neuro_ext167',function:'PediatricCRPSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMigraineChronicExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMigChronic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_neuro_ext167',function:'PediatricMigraineChronicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFibromyalgiaExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pFibro||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_neuro_ext167',function:'PediatricFibromyalgiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAbdominalPainExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pAbdPain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_neuro_ext167',function:'PediatricAbdominalPainExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHeadacheChronicExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pHeadChronic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_neuro_ext167',function:'PediatricHeadacheChronicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricComplexPainExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pComplexPain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_neuro_ext167',function:'PediatricComplexPainExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeuropathicExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pNeuropathic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_neuro_ext167',function:'PediatricNeuropathicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSicklePainExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSicklePain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_neuro_ext167',function:'PediatricSicklePainExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCancerPainExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pCancerPain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_pediatric_neuro_ext167',function:'PediatricCancerPainExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.7.0
