// filepath: pcc/pcc_pharmacogenomics_ext102/pcc_pharmacogenomics_ext102_engine.js
module.exports.version='v3.74.74.0';
module.exports.module='pcc_pharmacogenomics_ext102';
module.exports.functions={};
module.exports.functions['PGxGenExt']=function(input){const score=Math.round((0.18 + Number(input.pxGen||1)*0.2 + Number(input.pxGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.74.74.0',module:'pcc_pharmacogenomics_ext102',function:'PGxGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PGxCYPext']=function(input){const score=Math.round((0.18 + Number(input.pxCYP||1)*0.2 + Number(input.pxCYPtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.74.74.0',module:'pcc_pharmacogenomics_ext102',function:'PGxCYPext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PGxWarfarinExt']=function(input){const score=Math.round((0.18 + Number(input.pxWar||1)*0.2 + Number(input.pxWarDose||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.74.74.0',module:'pcc_pharmacogenomics_ext102',function:'PGxWarfarinExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PGxClopExt']=function(input){const score=Math.round((0.18 + Number(input.pxClo||1)*0.2 + Number(input.pxCloType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.74.74.0',module:'pcc_pharmacogenomics_ext102',function:'PGxClopExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PGxStatinExt']=function(input){const score=Math.round((0.18 + Number(input.pxSta||1)*0.2 + Number(input.pxStaType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.74.74.0',module:'pcc_pharmacogenomics_ext102',function:'PGxStatinExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PGxSSRIext']=function(input){const score=Math.round((0.18 + Number(input.pxSS||1)*0.2 + Number(input.pxSSType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.74.74.0',module:'pcc_pharmacogenomics_ext102',function:'PGxSSRIext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PGxTPMText']=function(input){const score=Math.round((0.18 + Number(input.pxTPMT||1)*0.2 + Number(input.pxTPMTtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.74.74.0',module:'pcc_pharmacogenomics_ext102',function:'PGxTPMText',input,score,ts:new Date().toISOString()}};
module.exports.functions['PGxDPDext']=function(input){const score=Math.round((0.18 + Number(input.pxDPD||1)*0.2 + Number(input.pxDPDtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.74.74.0',module:'pcc_pharmacogenomics_ext102',function:'PGxDPDext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PGxUGText']=function(input){const score=Math.round((0.18 + Number(input.pxUGT||1)*0.2 + Number(input.pxUGTtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.74.74.0',module:'pcc_pharmacogenomics_ext102',function:'PGxUGText',input,score,ts:new Date().toISOString()}};
module.exports.functions['PGxReportExt']=function(input){const score=Math.round((0.18 + Number(input.pxRep||1)*0.2 + Number(input.pxRepType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.74.74.0',module:'pcc_pharmacogenomics_ext102',function:'PGxReportExt',input,score,ts:new Date().toISOString()}};

// TS: v3.74.74.0
