// filepath: pcc/pcc_card_ext110/pcc_card_ext110_engine.js
module.exports.version='v3.16.16.0';
module.exports.module='pcc_card_ext110';
module.exports.functions={};
module.exports.functions['CardAdultExt']=function(input){const score=Math.round((0.18 + Number(input.cardAdult||1)*0.2 + Number(input.cardStage||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_card_ext110',function:'CardAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ArrhythmiaAdultExt']=function(input){const score=Math.round((0.18 + Number(input.arrhAdult||1)*0.2 + Number(input.qtInterval||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_card_ext110',function:'ArrhythmiaAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CHFAdultExt']=function(input){const score=Math.round((0.18 + Number(input.chfAdult||1)*0.2 + Number(input.ef||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_card_ext110',function:'CHFAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CADAdultExt']=function(input){const score=Math.round((0.18 + Number(input.cadAdult||1)*0.2 + Number(input.cadSeverity||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_card_ext110',function:'CADAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MIAadultExt']=function(input){const score=Math.round((0.18 + Number(input.miAdult||1)*0.2 + Number(input.tropPeak||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_card_ext110',function:'MIAadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ValveAdultExt']=function(input){const score=Math.round((0.18 + Number(input.valveAdult||1)*0.2 + Number(input.valveArea||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_card_ext110',function:'ValveAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CardiomyopathyAdultExt']=function(input){const score=Math.round((0.18 + Number(input.cmpAdult||1)*0.2 + Number(input.cmpType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_card_ext110',function:'CardiomyopathyAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PericardAdultExt']=function(input){const score=Math.round((0.18 + Number(input.pericardAdult||1)*0.2 + Number(input.pericardEff||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_card_ext110',function:'PericardAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EndocardAdultExt']=function(input){const score=Math.round((0.18 + Number(input.endocardAdult||1)*0.2 + Number(input.endoType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_card_ext110',function:'EndocardAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PulmonaryHTNAdultExt']=function(input){const score=Math.round((0.18 + Number(input.phaAdult||1)*0.2 + Number(input.pap||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_card_ext110',function:'PulmonaryHTNAdultExt',input,score,ts:new Date().toISOString()}};

// TS: v3.16.16.0
