// filepath: pcc/pcc_pediatric_surg_ext175/pcc_pediatric_surg_ext175_engine.js
module.exports.version='v3.15.15.0';
module.exports.module='pcc_pediatric_surg_ext175';
module.exports.functions={};
module.exports.functions['PediatricCSFleakSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pCSFleakSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_surg_ext175',function:'PediatricCSFleakSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChiariSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pChiariSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_surg_ext175',function:'PediatricChiariSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSyringoSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSyringoSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_surg_ext175',function:'PediatricSyringoSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTetheredSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pTetheredSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_surg_ext175',function:'PediatricTetheredSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinaBifidaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pSpinaBifidaSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_surg_ext175',function:'PediatricSpinaBifidaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHydroSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pHydroSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_surg_ext175',function:'PediatricHydroSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIIHacetazolExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pIIHacetazol||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_surg_ext175',function:'PediatricIIHacetazolExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDandyWalkerSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pDandySx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_surg_ext175',function:'PediatricDandyWalkerSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAqueductSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAqueductSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_surg_ext175',function:'PediatricAqueductSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricArachnoidSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pArachnoidSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_surg_ext175',function:'PediatricArachnoidSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.15.15.0
