// Auto-generated by gen_p3ic.py -- PCC v3.183.0
"use strict";
const TS = '2026-07-28T14:40:00Z';

function PediatricKetogenicDietExt(input) { const score = Math.round((0.4+Number(input.ketone||3)*0.1)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_surg_ext73', function:'PediatricKetogenicDietExt', input, score, ts: TS }; }

function PediatricVagusNerveSurgExt(input) { const score = Math.round((0.35+Number(input.output||1)*0.1)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_surg_ext73', function:'PediatricVagusNerveSurgExt', input, score, ts: TS }; }

function PediatricCallosotomyExt(input) { const score = Math.round((0.5+Number(input.drop_seizures||2)*0.1)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_surg_ext73', function:'PediatricCallosotomyExt', input, score, ts: TS }; }

function PediatricHemispherectomyExt(input) { const score = Math.round((0.5+Number(input.daily_seizures||3)*0.1)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_surg_ext73', function:'PediatricHemispherectomyExt', input, score, ts: TS }; }

function PediatricLesionectomyExt(input) { const score = Math.round((0.4+Number(input.lesion_size||2)*0.1)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_surg_ext73', function:'PediatricLesionectomyExt', input, score, ts: TS }; }

function PediatricLaserAblationExt(input) { const score = Math.round((0.4+Number(input.laser_fibers||1)*0.1)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_surg_ext73', function:'PediatricLaserAblationExt', input, score, ts: TS }; }

function PediatricRNSSurgExt(input) { const score = Math.round((0.4+Number(input.detections||10)*0.02)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_surg_ext73', function:'PediatricRNSSurgExt', input, score, ts: TS }; }

function PediatricCordotomyExt(input) { const score = Math.round((0.5+Number(input.pain_score||7)*0.05)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_surg_ext73', function:'PediatricCordotomyExt', input, score, ts: TS }; }

function PediatricITBSurgExt(input) { const score = Math.round((0.4+Number(input.dose_mg||30)*0.012)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_surg_ext73', function:'PediatricITBSurgExt', input, score, ts: TS }; }

function PediatricNeurostimExt(input) { const score = Math.round((0.35+Number(input.elegibility||1)*0.15)*100)/100; return { version:'3.183.0', module:'pcc_pediatric_surg_ext73', function:'PediatricNeurostimExt', input, score, ts: TS }; }

module.exports = {
  PediatricKetogenicDietExt,
  PediatricVagusNerveSurgExt,
  PediatricCallosotomyExt,
  PediatricHemispherectomyExt,
  PediatricLesionectomyExt,
  PediatricLaserAblationExt,
  PediatricRNSSurgExt,
  PediatricCordotomyExt,
  PediatricITBSurgExt,
  PediatricNeurostimExt,
};