-- rare_106 reverse
BEGIN;
DROP TABLE IF EXISTS rare_106_results CASCADE;
DROP TABLE IF EXISTS rare_106_orders  CASCADE;
DROP TABLE IF EXISTS rare_106_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_RARE_106_up';
COMMIT;
