// filepath: pcc/pcc_pediatric_neuro_ext173/pcc_pediatric_neuro_ext173_engine.js
module.exports.version='v3.13.13.0';
module.exports.module='pcc_pediatric_neuro_ext173';
module.exports.functions={};
module.exports.functions['PediatricPituitaryApoplexyExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pPitApoplexy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_neuro_ext173',function:'PediatricPituitaryApoplexyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEmptySellaExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pEmptySella||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_neuro_ext173',function:'PediatricEmptySellaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLymphHypoExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pLymphHypo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_neuro_ext173',function:'PediatricLymphHypoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDIneonatalExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pDIneonatal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_neuro_ext173',function:'PediatricDIneonatalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSIADHpostOpExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSIADHpostOp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_neuro_ext173',function:'PediatricSIADHpostOpExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHypopitExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pHypopit||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_neuro_ext173',function:'PediatricHypopitExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPituitaryPostopExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pPitPostop||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_neuro_ext173',function:'PediatricPituitaryPostopExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCraniopharyngiomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pCraniopharyngioma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_neuro_ext173',function:'PediatricCraniopharyngiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHypopitTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pHypopitTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_neuro_ext173',function:'PediatricHypopitTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPitApoplexyCritExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pPitApoplexyCrit||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.13.13.0',module:'pcc_pediatric_neuro_ext173',function:'PediatricPitApoplexyCritExt',input,score,ts:new Date().toISOString()}};

// TS: v3.13.13.0
