-- ent_101 reverse
BEGIN;
DROP TABLE IF EXISTS ent_101_results CASCADE;
DROP TABLE IF EXISTS ent_101_orders  CASCADE;
DROP TABLE IF EXISTS ent_101_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ENT_101_up';
COMMIT;
