// filepath: pcc/pcc_thoracic_surgery_ext102/pcc_thoracic_surgery_ext102_engine.js
module.exports.version='v3.55.55.0';
module.exports.module='pcc_thoracic_surgery_ext102';
module.exports.functions={};
module.exports.functions['TSxGenExt']=function(input){const score=Math.round((0.18 + Number(input.tsGen||1)*0.2 + Number(input.tsGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_thoracic_surgery_ext102',function:'TSxGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TSxLobExt']=function(input){const score=Math.round((0.18 + Number(input.tsLob||1)*0.2 + Number(input.tsLobType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_thoracic_surgery_ext102',function:'TSxLobExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TSxPneumExt']=function(input){const score=Math.round((0.18 + Number(input.tsPneu||1)*0.2 + Number(input.tsPneuType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_thoracic_surgery_ext102',function:'TSxPneumExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TSxEsophExt']=function(input){const score=Math.round((0.18 + Number(input.tsEso||1)*0.2 + Number(input.tsEsoType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_thoracic_surgery_ext102',function:'TSxEsophExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TSxMediastExt']=function(input){const score=Math.round((0.18 + Number(input.tsMed||1)*0.2 + Number(input.tsMedType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_thoracic_surgery_ext102',function:'TSxMediastExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TSxChestWallExt']=function(input){const score=Math.round((0.18 + Number(input.tsCW||1)*0.2 + Number(input.tsCWType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_thoracic_surgery_ext102',function:'TSxChestWallExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TSxVATSext']=function(input){const score=Math.round((0.18 + Number(input.tsVATS||1)*0.2 + Number(input.tsVATSscore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_thoracic_surgery_ext102',function:'TSxVATSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['TSxTrachExt']=function(input){const score=Math.round((0.18 + Number(input.tsTra||1)*0.2 + Number(input.tsTraType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_thoracic_surgery_ext102',function:'TSxTrachExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TSxDiaphExt']=function(input){const score=Math.round((0.18 + Number(input.tsDia||1)*0.2 + Number(input.tsDiaType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_thoracic_surgery_ext102',function:'TSxDiaphExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TSxPostExt']=function(input){const score=Math.round((0.18 + Number(input.tsPost||1)*0.2 + Number(input.tsPostDay||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.55.55.0',module:'pcc_thoracic_surgery_ext102',function:'TSxPostExt',input,score,ts:new Date().toISOString()}};

// TS: v3.55.55.0
