// filepath: pcc/pcc_pediatric_neuro_ext130/pcc_pediatric_neuro_ext130_engine.js
module.exports.version='v3.240.0';
module.exports.module='pcc_pediatric_neuro_ext130';
module.exports.functions={};
module.exports.functions['PediatricCryptoExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.crypto||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.240.0',module:'pcc_pediatric_neuro_ext130',function:'PediatricCryptoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTBmeningExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.tb||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.240.0',module:'pcc_pediatric_neuro_ext130',function:'PediatricTBmeningExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHIVExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.hiv||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.240.0',module:'pcc_pediatric_neuro_ext130',function:'PediatricHIVExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricToxoplasmosisExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.toxo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.240.0',module:'pcc_pediatric_neuro_ext130',function:'PediatricToxoplasmosisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPMLExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pml||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.240.0',module:'pcc_pediatric_neuro_ext130',function:'PediatricPMLExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAIDSDemExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.aids||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.240.0',module:'pcc_pediatric_neuro_ext130',function:'PediatricAIDSDemExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricToxoplasmosiExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.toxoplasmosis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.240.0',module:'pcc_pediatric_neuro_ext130',function:'PediatricToxoplasmosiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCysticercosisExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cysticercosis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.240.0',module:'pcc_pediatric_neuro_ext130',function:'PediatricCysticercosisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEchinococcusExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.echino||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.240.0',module:'pcc_pediatric_neuro_ext130',function:'PediatricEchinococcusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAmebicExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.amebic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.240.0',module:'pcc_pediatric_neuro_ext130',function:'PediatricAmebicExt',input,score,ts:new Date().toISOString()}};

// TS: v3.240.0
