-- rare_101 reverse
BEGIN;
DROP TABLE IF EXISTS rare_101_results CASCADE;
DROP TABLE IF EXISTS rare_101_orders  CASCADE;
DROP TABLE IF EXISTS rare_101_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_RARE_101_up';
COMMIT;
