-- obg_105 reverse
BEGIN;
DROP TABLE IF EXISTS obg_105_results CASCADE;
DROP TABLE IF EXISTS obg_105_orders  CASCADE;
DROP TABLE IF EXISTS obg_105_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_OBG_105_up';
COMMIT;
