// Auto-generated by gen_p3master.py -- PCC 3.189.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.189.0';

function CABGAssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.cabg) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_cabg_ext', function: 'CABGAssessmentExt', input, score, ts: TS };
}

function CABGScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.cabg) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_cabg_ext', function: 'CABGScoreExt', input, score, ts: TS };
}

function CABGStageExt(input) {
  const score = Math.round((0.3 + (Number(input.cabg) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_cabg_ext', function: 'CABGStageExt', input, score, ts: TS };
}

function CABGPlanExt(input) {
  const score = Math.round((0.3 + (Number(input.cabg) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_cabg_ext', function: 'CABGPlanExt', input, score, ts: TS };
}

function CABGRiskExt(input) {
  const score = Math.round((0.3 + (Number(input.cabg) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_cabg_ext', function: 'CABGRiskExt', input, score, ts: TS };
}

function CABGDoseExt(input) {
  const score = Math.round((0.3 + (Number(input.cabg) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_cabg_ext', function: 'CABGDoseExt', input, score, ts: TS };
}

function CABGFrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.cabg) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_cabg_ext', function: 'CABGFrequencyExt', input, score, ts: TS };
}

function CABGDurationExt(input) {
  const score = Math.round((0.3 + (Number(input.cabg) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_cabg_ext', function: 'CABGDurationExt', input, score, ts: TS };
}

function CABGFollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.cabg) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_cabg_ext', function: 'CABGFollowupExt', input, score, ts: TS };
}

function CABGOutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.cabg) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_cabg_ext', function: 'CABGOutcomeExt', input, score, ts: TS };
}

module.exports = {
  CABGAssessmentExt,
  CABGScoreExt,
  CABGStageExt,
  CABGPlanExt,
  CABGRiskExt,
  CABGDoseExt,
  CABGFrequencyExt,
  CABGDurationExt,
  CABGFollowupExt,
  CABGOutcomeExt,
};