// filepath: pcc/pcc_pediatric_neuro_ext174/pcc_pediatric_neuro_ext174_engine.js
module.exports.version='v3.14.14.0';
module.exports.module='pcc_pediatric_neuro_ext174';
module.exports.functions={};
module.exports.functions['PediatricINOExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pINO||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_pediatric_neuro_ext174',function:'PediatricINOExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOpsoclonusExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pOpsoclonus||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_pediatric_neuro_ext174',function:'PediatricOpsoclonusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCongNystagmusExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pCongNyst||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_pediatric_neuro_ext174',function:'PediatricCongNystagmusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIIIPalsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pIIIPalsy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_pediatric_neuro_ext174',function:'PediatricIIIPalsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVIPalsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pVIPalsy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_pediatric_neuro_ext174',function:'PediatricVIPalsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIVPalsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pIVPalsy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_pediatric_neuro_ext174',function:'PediatricIVPalsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOphthalmoplegiaExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pOph||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_pediatric_neuro_ext174',function:'PediatricOphthalmoplegiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCPEOExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pCPEO||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_pediatric_neuro_ext174',function:'PediatricCPEOExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLeberHereditaryExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pLHON||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_pediatric_neuro_ext174',function:'PediatricLeberHereditaryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSupranuclearPalsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pSNP||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.14.14.0',module:'pcc_pediatric_neuro_ext174',function:'PediatricSupranuclearPalsyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.14.14.0
