// filepath: pcc/pcc_neuro_ext169/pcc_neuro_ext169_engine.js
module.exports.version='v3.12.10.0';
module.exports.module='pcc_neuro_ext169';
module.exports.functions={};
module.exports.functions['HearingLossSuddenExt']=function(input){const score=Math.round((0.18 + Number(input.ssnhl||1)*0.2 + Number(input.acoustic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.10.0',module:'pcc_neuro_ext169',function:'HearingLossSuddenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PresbycusisExt']=function(input){const score=Math.round((0.18 + Number(input.presby||1)*0.2 + Number(input.highFreq||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.10.0',module:'pcc_neuro_ext169',function:'PresbycusisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OtotoxicDrugExt']=function(input){const score=Math.round((0.18 + Number(input.ototoxic||1)*0.2 + Number(input.aminoglyc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.10.0',module:'pcc_neuro_ext169',function:'OtotoxicDrugExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NoiseInducedExt']=function(input){const score=Math.round((0.18 + Number(input.nihl||1)*0.2 + Number(input.noiseExp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.10.0',module:'pcc_neuro_ext169',function:'NoiseInducedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TinnitusExt']=function(input){const score=Math.round((0.18 + Number(input.tinnitus||1)*0.2 + Number(input.ringing||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.10.0',module:'pcc_neuro_ext169',function:'TinnitusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OtitisMediaChronicExt']=function(input){const score=Math.round((0.18 + Number(input.com||1)*0.2 + Number(input.tympanic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.10.0',module:'pcc_neuro_ext169',function:'OtitisMediaChronicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OtosclerosisExt']=function(input){const score=Math.round((0.18 + Number(input.otoscler||1)*0.2 + Number(input.conductive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.10.0',module:'pcc_neuro_ext169',function:'OtosclerosisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CholesteatomaExt']=function(input){const score=Math.round((0.18 + Number(input.cholest||1)*0.2 + Number(input.boneErosion||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.10.0',module:'pcc_neuro_ext169',function:'CholesteatomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AcousticNeuroma2Ext']=function(input){const score=Math.round((0.18 + Number(input.an2||1)*0.2 + Number(input.unilateralHL||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.10.0',module:'pcc_neuro_ext169',function:'AcousticNeuroma2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['AuditoryNeuropathyExt']=function(input){const score=Math.round((0.18 + Number(input.anSd||1)*0.2 + Number(input.oaePresent||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.10.0',module:'pcc_neuro_ext169',function:'AuditoryNeuropathyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.12.10.0
