// filepath: pcc/pcc_nutrition_ext102/pcc_nutrition_ext102_engine.js
module.exports.version='v3.49.49.0';
module.exports.module='pcc_nutrition_ext102';
module.exports.functions={};
module.exports.functions['NutrGeneralExt']=function(input){const score=Math.round((0.18 + Number(input.nuGen||1)*0.2 + Number(input.nuGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.49.49.0',module:'pcc_nutrition_ext102',function:'NutrGeneralExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrAssessmentExt']=function(input){const score=Math.round((0.18 + Number(input.nuAss||1)*0.2 + Number(input.nuAssScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.49.49.0',module:'pcc_nutrition_ext102',function:'NutrAssessmentExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.nuDef||1)*0.2 + Number(input.nuDefType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.49.49.0',module:'pcc_nutrition_ext102',function:'NutrDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrMacroExt']=function(input){const score=Math.round((0.18 + Number(input.nuMac||1)*0.2 + Number(input.nuMacRatio||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.49.49.0',module:'pcc_nutrition_ext102',function:'NutrMacroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrMicroExt']=function(input){const score=Math.round((0.18 + Number(input.nuMic||1)*0.2 + Number(input.nuMicType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.49.49.0',module:'pcc_nutrition_ext102',function:'NutrMicroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrAllergyExt']=function(input){const score=Math.round((0.18 + Number(input.nuAlg||1)*0.2 + Number(input.nuAlgType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.49.49.0',module:'pcc_nutrition_ext102',function:'NutrAllergyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrPediatricExt']=function(input){const score=Math.round((0.18 + Number(input.nuPeds||1)*0.2 + Number(input.nuPedsType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.49.49.0',module:'pcc_nutrition_ext102',function:'NutrPediatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrGeriatricExt']=function(input){const score=Math.round((0.18 + Number(input.nuGeri||1)*0.2 + Number(input.nuGeriType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.49.49.0',module:'pcc_nutrition_ext102',function:'NutrGeriatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrEnteralExt']=function(input){const score=Math.round((0.18 + Number(input.nuEnt||1)*0.2 + Number(input.nuEntType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.49.49.0',module:'pcc_nutrition_ext102',function:'NutrEnteralExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NutrParenteralExt']=function(input){const score=Math.round((0.18 + Number(input.nuPar||1)*0.2 + Number(input.nuParType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.49.49.0',module:'pcc_nutrition_ext102',function:'NutrParenteralExt',input,score,ts:new Date().toISOString()}};

// TS: v3.49.49.0
