// Auto-generated by gen_p3master.py -- PCC 3.298.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.298.0';

function X317AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x317) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_317', function: 'X317AssessmentExt', input, score, ts: TS };
}

function X317ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x317) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_317', function: 'X317ScoreExt', input, score, ts: TS };
}

function X317StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x317) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_317', function: 'X317StageExt', input, score, ts: TS };
}

function X317PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x317) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_317', function: 'X317PlanExt', input, score, ts: TS };
}

function X317RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x317) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_317', function: 'X317RiskExt', input, score, ts: TS };
}

function X317DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x317) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_317', function: 'X317DoseExt', input, score, ts: TS };
}

function X317FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x317) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_317', function: 'X317FrequencyExt', input, score, ts: TS };
}

function X317DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x317) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_317', function: 'X317DurationExt', input, score, ts: TS };
}

function X317FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x317) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_317', function: 'X317FollowupExt', input, score, ts: TS };
}

function X317OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x317) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_317', function: 'X317OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X317AssessmentExt,
  X317ScoreExt,
  X317StageExt,
  X317PlanExt,
  X317RiskExt,
  X317DoseExt,
  X317FrequencyExt,
  X317DurationExt,
  X317FollowupExt,
  X317OutcomeExt,
};