// Auto-generated by gen_p3gx.py -- PCC v3.166.0
"use strict";
const TS = '2026-07-28T11:50:00Z';

function PediatricSelectiveDorsalRhizotomyExt(input) { const score = Math.round((0.4+Number(input.rootlets||5)*0.05)*100)/100; return { version:'3.166.0', module:'pcc_pediatric_surg_ext56', function:'PediatricSelectiveDorsalRhizotomyExt', input, score, ts: TS }; }

function PediatricIntrathecalBaclofenSurgeryExt(input) { const score = Math.round((0.4+Number(input.catheter_level||2)*0.08)*100)/100; return { version:'3.166.0', module:'pcc_pediatric_surg_ext56', function:'PediatricIntrathecalBaclofenSurgeryExt', input, score, ts: TS }; }

function PediatricTendonLengtheningExt(input) { const score = Math.round((0.3+Number(input.tendons||3)*0.05)*100)/100; return { version:'3.166.0', module:'pcc_pediatric_surg_ext56', function:'PediatricTendonLengtheningExt', input, score, ts: TS }; }

function PediatricBotulinumInjectionSurgeryExt(input) { const score = Math.round((0.3+Number(input.muscles||4)*0.05)*100)/100; return { version:'3.166.0', module:'pcc_pediatric_surg_ext56', function:'PediatricBotulinumInjectionSurgeryExt', input, score, ts: TS }; }

function PediatricOrthopedicSpineSurgeryExt(input) { const score = Math.round((0.5+Number(input.cobb_angle||40)*0.01)*100)/100; return { version:'3.166.0', module:'pcc_pediatric_surg_ext56', function:'PediatricOrthopedicSpineSurgeryExt', input, score, ts: TS }; }

function PediatricHipReconstructionExt(input) { const score = Math.round((0.45+Number(input.reimers||30)*0.01)*100)/100; return { version:'3.166.0', module:'pcc_pediatric_surg_ext56', function:'PediatricHipReconstructionExt', input, score, ts: TS }; }

function PediatricGaitSurgeryExt(input) { const score = Math.round((0.35+Number(input.levels||3)*0.05)*100)/100; return { version:'3.166.0', module:'pcc_pediatric_surg_ext56', function:'PediatricGaitSurgeryExt', input, score, ts: TS }; }

function PediatricUpperLimbSurgeryExt(input) { const score = Math.round((0.3+Number(input.muscles||4)*0.05)*100)/100; return { version:'3.166.0', module:'pcc_pediatric_surg_ext56', function:'PediatricUpperLimbSurgeryExt', input, score, ts: TS }; }

function PediatricSpasticitySurgeryExt(input) { const score = Math.round((0.4+Number(input.spasm_score||2)*0.1)*100)/100; return { version:'3.166.0', module:'pcc_pediatric_surg_ext56', function:'PediatricSpasticitySurgeryExt', input, score, ts: TS }; }

function PediatricCerebralPalsySurgeryExt(input) { const score = Math.round((0.4+Number(input.gmfcs||2)*0.1)*100)/100; return { version:'3.166.0', module:'pcc_pediatric_surg_ext56', function:'PediatricCerebralPalsySurgeryExt', input, score, ts: TS }; }

module.exports = {
  PediatricSelectiveDorsalRhizotomyExt,
  PediatricIntrathecalBaclofenSurgeryExt,
  PediatricTendonLengtheningExt,
  PediatricBotulinumInjectionSurgeryExt,
  PediatricOrthopedicSpineSurgeryExt,
  PediatricHipReconstructionExt,
  PediatricGaitSurgeryExt,
  PediatricUpperLimbSurgeryExt,
  PediatricSpasticitySurgeryExt,
  PediatricCerebralPalsySurgeryExt,
};