// filepath: pcc/pcc_pediatric_surg_ext128/pcc_pediatric_surg_ext128_engine.js
module.exports.version='v3.238.0';
module.exports.module='pcc_pediatric_surg_ext128';
module.exports.functions={};
module.exports.functions['PediatricHemophiliaFactorExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.factor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_surg_ext128',function:'PediatricHemophiliaFactorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVWDDDAVPext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ddavp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_surg_ext128',function:'PediatricVWDDDAVPext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricITPSteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.steroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_surg_ext128',function:'PediatricITPSteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAcquiredHemoBypassExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.bypass||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_surg_ext128',function:'PediatricAcquiredHemoBypassExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDICtransfusionExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.transfusion||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_surg_ext128',function:'PediatricDICtransfusionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTMAplasmaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.plasmaExchange||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_surg_ext128',function:'PediatricTMAplasmaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHypercoagAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.antiCoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_surg_ext128',function:'PediatricHypercoagAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAPASantiExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.antiCoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_surg_ext128',function:'PediatricAPASantiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricThrombophiliaAntiExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.antiCoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_surg_ext128',function:'PediatricThrombophiliaAntiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAnticoagulationReversalExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.vitaminK||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_pediatric_surg_ext128',function:'PediatricAnticoagulationReversalExt',input,score,ts:new Date().toISOString()}};

// TS: v3.238.0
