// Auto_generated by gen_p3gy.py -- PCC v3.167.0
"use strict";
const TS = '2026-07-28T12:00:00Z';

function PediatricEpilepsyClassificationExt(input) { const score = Math.round((0.3+Number(input.seizure_freq||2)*0.05)*100)/100; return { version:'3.167.0', module:'pcc_pediatric_neuro_ext57', function:"PediatricEpilepsyClassificationExt", input, score, ts: TS }; }

function PediatricStatusEpilepticusExt(input) { const score = Math.round((0.5+Number(input.duration_min||5)*0.01)*100)/100; return { version:'3.167.0', module:'pcc_pediatric_neuro_ext57', function:"PediatricStatusEpilepticusExt", input, score, ts: TS }; }

function PediatricRefractoryEpilepsyExt(input) { const score = Math.round((0.4+Number(input.failed_drugs||2)*0.08)*100)/100; return { version:'3.167.0', module:'pcc_pediatric_neuro_ext57', function:"PediatricRefractoryEpilepsyExt", input, score, ts: TS }; }

function PediatricEpilepsySurgeryEvalExt(input) { const score = Math.round((0.35+Number(input.eeg_focus_score||3)*0.06)*100)/100; return { version:'3.167.0', module:'pcc_pediatric_neuro_ext57', function:"PediatricEpilepsySurgeryEvalExt", input, score, ts: TS }; }

function PediatricVagalNerveStimExt(input) { const score = Math.round((0.3+Number(input.output_mA||1)*0.1)*100)/100; return { version:'3.167.0', module:'pcc_pediatric_neuro_ext57', function:"PediatricVagalNerveStimExt", input, score, ts: TS }; }

function PediatricRNSPlacementExt(input) { const score = Math.round((0.3+Number(input.detections||10)*0.02)*100)/100; return { version:'3.167.0', module:'pcc_pediatric_neuro_ext57', function:"PediatricRNSPlacementExt", input, score, ts: TS }; }

function PediatricDBSForEpilepsyExt(input) { const score = Math.round((0.35+Number(input.frequency||130)*0.003)*100)/100; return { version:'3.167.0', module:'pcc_pediatric_neuro_ext57', function:"PediatricDBSForEpilepsyExt", input, score, ts: TS }; }

function PediatricKetogenicDietExt(input) { const score = Math.round((0.3+Number(input.ketone_level||3)*0.1)*100)/100; return { version:'3.167.0', module:'pcc_pediatric_neuro_ext57', function:"PediatricKetogenicDietExt", input, score, ts: TS }; }

function PediatricASMLevelExt(input) { const score = Math.round((0.3+Number(input.drug_count||1)*0.06)*100)/100; return { version:'3.167.0', module:'pcc_pediatric_neuro_ext57', function:"PediatricASMLevelExt", input, score, ts: TS }; }

function PediatricEpilepsyGeneticsExt(input) { const score = Math.round((0.4+Number(input.variants||1)*0.15)*100)/100; return { version:'3.167.0', module:'pcc_pediatric_neuro_ext57', function:"PediatricEpilepsyGeneticsExt", input, score, ts: TS }; }

module.exports = {
  PediatricEpilepsyClassificationExt,
  PediatricStatusEpilepticusExt,
  PediatricRefractoryEpilepsyExt,
  PediatricEpilepsySurgeryEvalExt,
  PediatricVagalNerveStimExt,
  PediatricRNSPlacementExt,
  PediatricDBSForEpilepsyExt,
  PediatricKetogenicDietExt,
  PediatricASMLevelExt,
  PediatricEpilepsyGeneticsExt,
};