// Auto-generated by gen_p3master.py -- PCC 3.295.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.295.0';

function X309AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x309) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_309', function: 'X309AssessmentExt', input, score, ts: TS };
}

function X309ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x309) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_309', function: 'X309ScoreExt', input, score, ts: TS };
}

function X309StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x309) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_309', function: 'X309StageExt', input, score, ts: TS };
}

function X309PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x309) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_309', function: 'X309PlanExt', input, score, ts: TS };
}

function X309RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x309) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_309', function: 'X309RiskExt', input, score, ts: TS };
}

function X309DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x309) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_309', function: 'X309DoseExt', input, score, ts: TS };
}

function X309FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x309) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_309', function: 'X309FrequencyExt', input, score, ts: TS };
}

function X309DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x309) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_309', function: 'X309DurationExt', input, score, ts: TS };
}

function X309FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x309) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_309', function: 'X309FollowupExt', input, score, ts: TS };
}

function X309OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x309) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_309', function: 'X309OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X309AssessmentExt,
  X309ScoreExt,
  X309StageExt,
  X309PlanExt,
  X309RiskExt,
  X309DoseExt,
  X309FrequencyExt,
  X309DurationExt,
  X309FollowupExt,
  X309OutcomeExt,
};