// filepath: pcc/pcc_anesthesiology_ext102/pcc_anesthesiology_ext102_engine.js
module.exports.version='v3.71.71.0';
module.exports.module='pcc_anesthesiology_ext102';
module.exports.functions={};
module.exports.functions['AnGenExt']=function(input){const score=Math.round((0.18 + Number(input.anGen||1)*0.2 + Number(input.anGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_anesthesiology_ext102',function:'AnGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnGenAnesthExt']=function(input){const score=Math.round((0.18 + Number(input.anGA||1)*0.2 + Number(input.anGAtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_anesthesiology_ext102',function:'AnGenAnesthExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnRegAnesthExt']=function(input){const score=Math.round((0.18 + Number(input.anRA||1)*0.2 + Number(input.anRAtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_anesthesiology_ext102',function:'AnRegAnesthExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnLocalExt']=function(input){const score=Math.round((0.18 + Number(input.anLA||1)*0.2 + Number(input.anLAtype||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_anesthesiology_ext102',function:'AnLocalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnAirwayExt']=function(input){const score=Math.round((0.18 + Number(input.anAw||1)*0.2 + Number(input.anAwScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_anesthesiology_ext102',function:'AnAirwayExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnMonitExt']=function(input){const score=Math.round((0.18 + Number(input.anMon||1)*0.2 + Number(input.anMonType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_anesthesiology_ext102',function:'AnMonitExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnFluidExt']=function(input){const score=Math.round((0.18 + Number(input.anFl||1)*0.2 + Number(input.anFlRate||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_anesthesiology_ext102',function:'AnFluidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnPostopExt']=function(input){const score=Math.round((0.18 + Number(input.anPo||1)*0.2 + Number(input.anPoScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_anesthesiology_ext102',function:'AnPostopExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnComplicExt']=function(input){const score=Math.round((0.18 + Number(input.anCo||1)*0.2 + Number(input.anCoType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_anesthesiology_ext102',function:'AnComplicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnCriticalExt']=function(input){const score=Math.round((0.18 + Number(input.anCr||1)*0.2 + Number(input.anCrType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.71.71.0',module:'pcc_anesthesiology_ext102',function:'AnCriticalExt',input,score,ts:new Date().toISOString()}};

// TS: v3.71.71.0
