// filepath: pcc/pcc_neuro_ext139/pcc_neuro_ext139_engine.js
module.exports.version='v3.238.0';
module.exports.module='pcc_neuro_ext139';
module.exports.functions={};
module.exports.functions['HemophiliaExt']=function(input){const score=Math.round((0.18 + Number(input.factorVIII||1)*0.2 + Number(input.bleed||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_neuro_ext139',function:'HemophiliaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VonWillebrandExt']=function(input){const score=Math.round((0.18 + Number(input.vwf||1)*0.2 + Number(input.bleed||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_neuro_ext139',function:'VonWillebrandExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ImmuneThrombocytopeniaExt']=function(input){const score=Math.round((0.18 + Number(input.platelet||20)*0.01 + Number(input.bleed||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_neuro_ext139',function:'ImmuneThrombocytopeniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AcquiredHemophiliaExt']=function(input){const score=Math.round((0.18 + Number(input.acquired||1)*0.2 + Number(input.factorVIII||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_neuro_ext139',function:'AcquiredHemophiliaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['DICSecondaryExt']=function(input){const score=Math.round((0.18 + Number(input.dic||1)*0.2 + Number(input.cause||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_neuro_ext139',function:'DICSecondaryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ThromboticMicroangiopathyExt']=function(input){const score=Math.round((0.18 + Number(input.tma||1)*0.2 + Number(input.pltLow||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_neuro_ext139',function:'ThromboticMicroangiopathyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HypercoagulableStateExt']=function(input){const score=Math.round((0.18 + Number(input.thrombophilia||1)*0.2 + Number(input.dvt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_neuro_ext139',function:'HypercoagulableStateExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AntiphospholipidSynExt']=function(input){const score=Math.round((0.18 + Number(input.lupus||1)*0.2 + Number(input.anticardiolipin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_neuro_ext139',function:'AntiphospholipidSynExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ThrombophiliaInheritedExt']=function(input){const score=Math.round((0.18 + Number(input.factorVleiden||1)*0.2 + Number(input.prothrombin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_neuro_ext139',function:'ThrombophiliaInheritedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnticoagulationReversalExt']=function(input){const score=Math.round((0.18 + Number(input.warfarin||1)*0.2 + Number(input.bleed||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.238.0',module:'pcc_neuro_ext139',function:'AnticoagulationReversalExt',input,score,ts:new Date().toISOString()}};

// TS: v3.238.0
