// filepath: pcc/pcc_pediatric_surg_ext172/pcc_pediatric_surg_ext172_engine.js
module.exports.version='v3.1.12.0';
module.exports.module='pcc_pediatric_surg_ext172';
module.exports.functions={};
module.exports.functions['PediatricDemChildTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pDemChildTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.12.0',module:'pcc_pediatric_surg_ext172',function:'PediatricDemChildTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNF1cogTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pNF1cogTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.12.0',module:'pcc_pediatric_surg_ext172',function:'PediatricNF1cogTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTSCcogTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pTSCcogTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.12.0',module:'pcc_pediatric_surg_ext172',function:'PediatricTSCcogTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['Pediatric22q11TxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.p22q11Tx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.12.0',module:'pcc_pediatric_surg_ext172',function:'Pediatric22q11TxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFragileXTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pFragileXTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.12.0',module:'pcc_pediatric_surg_ext172',function:'PediatricFragileXTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDownCogTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pDownCogTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.12.0',module:'pcc_pediatric_surg_ext172',function:'PediatricDownCogTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWilliamsTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pWilliamsTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.12.0',module:'pcc_pediatric_surg_ext172',function:'PediatricWilliamsTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPraderTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pPraderTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.12.0',module:'pcc_pediatric_surg_ext172',function:'PediatricPraderTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAngelmanTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pAngelmanTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.12.0',module:'pcc_pediatric_surg_ext172',function:'PediatricAngelmanTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRettTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pRettTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.12.0',module:'pcc_pediatric_surg_ext172',function:'PediatricRettTxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.12.0
