// filepath: pcc/pcc_pediatric_surg_ext156/pcc_pediatric_surg_ext156_engine.js
module.exports.version='v3.12.8.0';
module.exports.module='pcc_pediatric_surg_ext156';
module.exports.functions={};
module.exports.functions['PediatricPituitaryTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pPitTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_surg_ext156',function:'PediatricPituitaryTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAcromegalyTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pAcroTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_surg_ext156',function:'PediatricAcromegalyTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCushingTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pCushingTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_surg_ext156',function:'PediatricCushingTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDIdDAVPExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pDIdDAVP||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_surg_ext156',function:'PediatricDIdDAVPExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSIADHFluidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSIADHFluid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_surg_ext156',function:'PediatricSIADHFluidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHypothyroidLevExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pHypoLev||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_surg_ext156',function:'PediatricHypothyroidLevExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCongHypothyroidRxExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pCongHypoRx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_surg_ext156',function:'PediatricCongHypothyroidRxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHyperthyroidTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pHyperTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_surg_ext156',function:'PediatricHyperthyroidTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAdrenalSteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAdrenSteroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_surg_ext156',function:'PediatricAdrenalSteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPheochromSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pPheoSx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.8.0',module:'pcc_pediatric_surg_ext156',function:'PediatricPheochromSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.12.8.0
