// filepath: pcc/pcc_pediatric_neuro_ext99/pcc_pediatric_neuro_ext99_engine.js
// pcc_pediatric_neuro_ext99 engine (deterministic)
module.exports.version='v3.209.0';
module.exports.module='pcc_pediatric_neuro_ext99';
module.exports.functions={};
module.exports.functions['PediatricParkinsonExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.parkinson||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.209.0',module:'pcc_pediatric_neuro_ext99',function:'PediatricParkinsonExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricHuntingtonExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.cag||45)*0.01 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.209.0',module:'pcc_pediatric_neuro_ext99',function:'PediatricHuntingtonExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricDystoniaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.dystonia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.209.0',module:'pcc_pediatric_neuro_ext99',function:'PediatricDystoniaExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricTouretteExt']=function(input){const score=Math.round((0.18 + Number(input.age||6)*0.04 + Number(input.tics||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.209.0',module:'pcc_pediatric_neuro_ext99',function:'PediatricTouretteExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricEssentialTremorExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.tremor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.209.0',module:'pcc_pediatric_neuro_ext99',function:'PediatricEssentialTremorExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCerebellarExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ataxia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.209.0',module:'pcc_pediatric_neuro_ext99',function:'PediatricCerebellarExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricFriedreichExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.frda||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.209.0',module:'pcc_pediatric_neuro_ext99',function:'PediatricFriedreichExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSCAext']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.sca||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.209.0',module:'pcc_pediatric_neuro_ext99',function:'PediatricSCAext',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricWilsonExt']=function(input){const score=Math.round((0.18 + Number(input.age||6)*0.04 + Number(input.copper||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.209.0',module:'pcc_pediatric_neuro_ext99',function:'PediatricWilsonExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricChoreaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.chorea||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.209.0',module:'pcc_pediatric_neuro_ext99',function:'PediatricChoreaExt',input,score,ts:new Date().toISOString()};};

// TS: v3.209.0
