[package]
name = "pcc-sdk"
version = "3.316.6"
edition = "2021"
description = "Rust SDK for NamaMedical PCC Sandbox"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[lib]
name = "pcc_sdk"
path = "src/lib.rs"
