// Auto-generated by gen_p3ig.py -- PCC v3.187.0
"use strict";
const TS = '2026-07-28T15:20:00Z';

function PediatricMedicalRefractoryExt(input) { const score = Math.round((0.45+Number(input.failed_drugs||2)*0.1)*100)/100; return { version:'3.187.0', module:'pcc_pediatric_neuro_ext77', function:'PediatricMedicalRefractoryExt', input, score, ts: TS }; }

function PediatricSurgicalEpilepsyExt(input) { const score = Math.round((0.4+Number(input.localization||1)*0.15)*100)/100; return { version:'3.187.0', module:'pcc_pediatric_neuro_ext77', function:'PediatricSurgicalEpilepsyExt', input, score, ts: TS }; }

function PediatricLaserAblationExt(input) { const score = Math.round((0.4+Number(input.depth_mm||8)*0.03)*100)/100; return { version:'3.187.0', module:'pcc_pediatric_neuro_ext77', function:'PediatricLaserAblationExt', input, score, ts: TS }; }

function PediatricRNSExt(input) { const score = Math.round((0.4+Number(input.detections||3)*0.06)*100)/100; return { version:'3.187.0', module:'pcc_pediatric_neuro_ext77', function:'PediatricRNSExt', input, score, ts: TS }; }

function PediatricDBSForEpilepsyExt(input) { const score = Math.round((0.45+Number(input.seizure_freq||3)*0.06)*100)/100; return { version:'3.187.0', module:'pcc_pediatric_neuro_ext77', function:'PediatricDBSForEpilepsyExt', input, score, ts: TS }; }

function PediatricVNSTuneExt(input) { const score = Math.round((0.3+Number(input.output||0.5)*0.1)*100)/100; return { version:'3.187.0', module:'pcc_pediatric_neuro_ext77', function:'PediatricVNSTuneExt', input, score, ts: TS }; }

function PediatricKetogenicExt(input) { const score = Math.round((0.3+Number(input.ketone||3)*0.1)*100)/100; return { version:'3.187.0', module:'pcc_pediatric_neuro_ext77', function:'PediatricKetogenicExt', input, score, ts: TS }; }

function PediatricACTHExt(input) { const score = Math.round((0.3+Number(input.dose_mg||40)*0.01)*100)/100; return { version:'3.187.0', module:'pcc_pediatric_neuro_ext77', function:'PediatricACTHExt', input, score, ts: TS }; }

function PediatricEpilepsyGeneticExt(input) { const score = Math.round((0.4+Number(input.variant||1)*0.15)*100)/100; return { version:'3.187.0', module:'pcc_pediatric_neuro_ext77', function:'PediatricEpilepsyGeneticExt', input, score, ts: TS }; }

function PediatricSUDEPExt(input) { const score = Math.round((0.4+Number(input.seizure_type||2)*0.1)*100)/100; return { version:'3.187.0', module:'pcc_pediatric_neuro_ext77', function:'PediatricSUDEPExt', input, score, ts: TS }; }

module.exports = {
  PediatricMedicalRefractoryExt,
  PediatricSurgicalEpilepsyExt,
  PediatricLaserAblationExt,
  PediatricRNSExt,
  PediatricDBSForEpilepsyExt,
  PediatricVNSTuneExt,
  PediatricKetogenicExt,
  PediatricACTHExt,
  PediatricEpilepsyGeneticExt,
  PediatricSUDEPExt,
};