// filepath: pcc/pcc_sleep_ext100/pcc_sleep_ext100_engine.js
module.exports.version='v3.25.25.0';
module.exports.module='pcc_sleep_ext100';
module.exports.functions={};
module.exports.functions['SleepApneaExt']=function(input){const score=Math.round((0.18 + Number(input.slApnea||1)*0.2 + Number(input.ahiSL||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_sleep_ext100',function:'SleepApneaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SleepInsomniaExt']=function(input){const score=Math.round((0.18 + Number(input.slInsom||1)*0.2 + Number(input.isiScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_sleep_ext100',function:'SleepInsomniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SleepNarcolepsyExt']=function(input){const score=Math.round((0.18 + Number(input.slNarc||1)*0.2 + Number(input.essScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_sleep_ext100',function:'SleepNarcolepsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SleepRestlessLegExt']=function(input){const score=Math.round((0.18 + Number(input.slRLS||1)*0.2 + Number(input.rlsSeverity||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_sleep_ext100',function:'SleepRestlessLegExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SleepParasomniaExt']=function(input){const score=Math.round((0.18 + Number(input.slPara||1)*0.2 + Number(input.paraType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_sleep_ext100',function:'SleepParasomniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SleepCircadianExt']=function(input){const score=Math.round((0.18 + Number(input.slCirc||1)*0.2 + Number(input.circType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_sleep_ext100',function:'SleepCircadianExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SleepPediatricExt']=function(input){const score=Math.round((0.18 + Number(input.slPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_sleep_ext100',function:'SleepPediatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SleepCPAPext']=function(input){const score=Math.round((0.18 + Number(input.slCPAP||1)*0.2 + Number(input.cpapHours||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_sleep_ext100',function:'SleepCPAPext',input,score,ts:new Date().toISOString()}};
module.exports.functions['SleepShiftWorkExt']=function(input){const score=Math.round((0.18 + Number(input.slShift||1)*0.2 + Number(input.shiftType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_sleep_ext100',function:'SleepShiftWorkExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SleepHygieneExt']=function(input){const score=Math.round((0.18 + Number(input.slHygiene||1)*0.2 + Number(input.sleepQuality||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.25.25.0',module:'pcc_sleep_ext100',function:'SleepHygieneExt',input,score,ts:new Date().toISOString()}};

// TS: v3.25.25.0
