// filepath: pcc/pcc_pediatric_neuro_ext183/pcc_pediatric_neuro_ext183_engine.js
module.exports.version='v3.23.23.0';
module.exports.module='pcc_pediatric_neuro_ext183';
module.exports.functions={};
module.exports.functions['PediatricMigraineExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pMigraine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_pediatric_neuro_ext183',function:'PediatricMigraineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricClusterExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pCluster||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_pediatric_neuro_ext183',function:'PediatricClusterExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTTHext']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTTH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_pediatric_neuro_ext183',function:'PediatricTTHext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMOHext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMOH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_pediatric_neuro_ext183',function:'PediatricMOHext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIIHext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pIIH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_pediatric_neuro_ext183',function:'PediatricIIHext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLowCSFext']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pLowCSF||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_pediatric_neuro_ext183',function:'PediatricLowCSFext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTGNext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pTGN||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_pediatric_neuro_ext183',function:'PediatricTGNext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHemicraniaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pHemicrania||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_pediatric_neuro_ext183',function:'PediatricHemicraniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDailyPersistentExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pNDPH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_pediatric_neuro_ext183',function:'PediatricDailyPersistentExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHAltSexhExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pHASH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.23.23.0',module:'pcc_pediatric_neuro_ext183',function:'PediatricHAltSexhExt',input,score,ts:new Date().toISOString()}};

// TS: v3.23.23.0
