// Auto-generated by gen_p3ic.py -- PCC v3.183.0
"use strict";
const TS = '2026-07-28T14:40:00Z';

function DementiaScreeningExt(input) { const score = Math.round((0.3+Number(input.mmse||25)*0.025)*100)/100; return { version:'3.183.0', module:'pcc_neuro_ext84', function:'DementiaScreeningExt', input, score, ts: TS }; }

function AlzheimersDementiaExt(input) { const score = Math.round((0.4+Number(input.atrophy||2)*0.1)*100)/100; return { version:'3.183.0', module:'pcc_neuro_ext84', function:'AlzheimersDementiaExt', input, score, ts: TS }; }

function LewyBodyDementiaExt(input) { const score = Math.round((0.4+Number(input.visual_hallucination||0)*0.2)*100)/100; return { version:'3.183.0', module:'pcc_neuro_ext84', function:'LewyBodyDementiaExt', input, score, ts: TS }; }

function VascularDementiaExt(input) { const score = Math.round((0.4+Number(input.fazekas||1)*0.15)*100)/100; return { version:'3.183.0', module:'pcc_neuro_ext84', function:'VascularDementiaExt', input, score, ts: TS }; }

function FTDBehavioralExt(input) { const score = Math.round((0.4+Number(input.disinhibition||2)*0.15)*100)/100; return { version:'3.183.0', module:'pcc_neuro_ext84', function:'FTDBehavioralExt', input, score, ts: TS }; }

function FTDLanguageExt(input) { const score = Math.round((0.4+Number(input.language_score||2)*0.15)*100)/100; return { version:'3.183.0', module:'pcc_neuro_ext84', function:'FTDLanguageExt', input, score, ts: TS }; }

function PosteriorCorticalAtrophyExt(input) { const score = Math.round((0.4+Number(input.visual_field||2)*0.15)*100)/100; return { version:'3.183.0', module:'pcc_neuro_ext84', function:'PosteriorCorticalAtrophyExt', input, score, ts: TS }; }

function DLBvsADDExt(input) { const score = Math.round((0.4+Number(input.caregiver_ih||0)*0.2)*100)/100; return { version:'3.183.0', module:'pcc_neuro_ext84', function:'DLBvsADDExt', input, score, ts: TS }; }

function DementiaTreatmentExt(input) { const score = Math.round((0.3+Number(input.drug_count||1)*0.15)*100)/100; return { version:'3.183.0', module:'pcc_neuro_ext84', function:'DementiaTreatmentExt', input, score, ts: TS }; }

function DementiaBehavioralExt(input) { const score = Math.round((0.3+Number(input.behavioral_score||2)*0.15)*100)/100; return { version:'3.183.0', module:'pcc_neuro_ext84', function:'DementiaBehavioralExt', input, score, ts: TS }; }

module.exports = {
  DementiaScreeningExt,
  AlzheimersDementiaExt,
  LewyBodyDementiaExt,
  VascularDementiaExt,
  FTDBehavioralExt,
  FTDLanguageExt,
  PosteriorCorticalAtrophyExt,
  DLBvsADDExt,
  DementiaTreatmentExt,
  DementiaBehavioralExt,
};