// Auto-generated by gen_p3hc.py -- PCC v3.171.0
"use strict";
const TS = '2026-07-28T12:40:00Z';

function PediatricVPShuntInfectionRevExt(input) { const score = Math.round((0.4+Number(input.shunt_age_months||12)*0.02)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_surg_ext61', function:'PediatricVPShuntInfectionRevExt', input, score, ts: TS }; }

function PediatricEVDPlacementExt(input) { const score = Math.round((0.35+Number(input.pressure||15)*0.02)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_surg_ext61', function:'PediatricEVDPlacementExt', input, score, ts: TS }; }

function PediatricCraniotomyForAbscessExt(input) { const score = Math.round((0.4+Number(input.location_depth||10)*0.02)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_surg_ext61', function:'PediatricCraniotomyForAbscessExt', input, score, ts: TS }; }

function PediatricSepticEmpyemaExt(input) { const score = Math.round((0.45+Number(input.thickness||5)*0.05)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_surg_ext61', function:'PediatricSepticEmpyemaExt', input, score, ts: TS }; }

function PediatricSpinalDrainExt(input) { const score = Math.round((0.35+Number(input.drain_level||3)*0.05)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_surg_ext61', function:'PediatricSpinalDrainExt', input, score, ts: TS }; }

function PediatricLPForMeningitisExt(input) { const score = Math.round((0.3+Number(input.csf_opening||30)*0.01)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_surg_ext61', function:'PediatricLPForMeningitisExt', input, score, ts: TS }; }

function PediatricVPShuntExternalizationExt(input) { const score = Math.round((0.4+Number(input.days_external||7)*0.04)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_surg_ext61', function:'PediatricVPShuntExternalizationExt', input, score, ts: TS }; }

function PediatricVentriculitisTreatmentExt(input) { const score = Math.round((0.45+Number(input.antibiotic_days||10)*0.02)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_surg_ext61', function:'PediatricVentriculitisTreatmentExt', input, score, ts: TS }; }

function PediatricSubduralEmpyemaExt(input) { const score = Math.round((0.5+Number(input.csf_pressure||25)*0.01)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_surg_ext61', function:'PediatricSubduralEmpyemaExt', input, score, ts: TS }; }

function PediatricCNSInfectionRecoverSurgExt(input) { const score = Math.round((0.3+Number(input.recovery_days||14)*0.02)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_surg_ext61', function:'PediatricCNSInfectionRecoverSurgExt', input, score, ts: TS }; }

module.exports = {
  PediatricVPShuntInfectionRevExt,
  PediatricEVDPlacementExt,
  PediatricCraniotomyForAbscessExt,
  PediatricSepticEmpyemaExt,
  PediatricSpinalDrainExt,
  PediatricLPForMeningitisExt,
  PediatricVPShuntExternalizationExt,
  PediatricVentriculitisTreatmentExt,
  PediatricSubduralEmpyemaExt,
  PediatricCNSInfectionRecoverSurgExt,
};