// filepath: pcc/pcc_clinical_trials_ext102/pcc_clinical_trials_ext102_engine.js
module.exports.version='v3.39.39.0';
module.exports.module='pcc_clinical_trials_ext102';
module.exports.functions={};
module.exports.functions['CTPhase1Ext']=function(input){const score=Math.round((0.18 + Number(input.ctP1||1)*0.2 + Number(input.ctP1Dose||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_clinical_trials_ext102',function:'CTPhase1Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTPhase2Ext']=function(input){const score=Math.round((0.18 + Number(input.ctP2||1)*0.2 + Number(input.ctP2Eff||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_clinical_trials_ext102',function:'CTPhase2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTPhase3Ext']=function(input){const score=Math.round((0.18 + Number(input.ctP3||1)*0.2 + Number(input.ctP3Outcome||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_clinical_trials_ext102',function:'CTPhase3Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTPhase4Ext']=function(input){const score=Math.round((0.18 + Number(input.ctP4||1)*0.2 + Number(input.ctP4Safety||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_clinical_trials_ext102',function:'CTPhase4Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTRandomizedExt']=function(input){const score=Math.round((0.18 + Number(input.ctRCT||1)*0.2 + Number(input.ctRctDesign||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_clinical_trials_ext102',function:'CTRandomizedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTObservationalExt']=function(input){const score=Math.round((0.18 + Number(input.ctObs||1)*0.2 + Number(input.ctObsDesign||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_clinical_trials_ext102',function:'CTObservationalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTAdaptiveExt']=function(input){const score=Math.round((0.18 + Number(input.ctAdapt||1)*0.2 + Number(input.ctAdaptRule||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_clinical_trials_ext102',function:'CTAdaptiveExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTBioequivalenceExt']=function(input){const score=Math.round((0.18 + Number(input.ctBE||1)*0.2 + Number(input.ctBeCmax||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_clinical_trials_ext102',function:'CTBioequivalenceExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTFirstInHumanExt']=function(input){const score=Math.round((0.18 + Number(input.ctFIH||1)*0.2 + Number(input.ctFihDose||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_clinical_trials_ext102',function:'CTFirstInHumanExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTExpandedAccessExt']=function(input){const score=Math.round((0.18 + Number(input.ctEA||1)*0.2 + Number(input.ctEaType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.39.39.0',module:'pcc_clinical_trials_ext102',function:'CTExpandedAccessExt',input,score,ts:new Date().toISOString()}};

// TS: v3.39.39.0
