// filepath: pcc/pcc_pediatric_neuro_ext142/pcc_pediatric_neuro_ext142_engine.js
module.exports.version='v3.252.0';
module.exports.module='pcc_pediatric_neuro_ext142';
module.exports.functions={};
module.exports.functions['PediatricNeuroSarcExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pSarc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_neuro_ext142',function:'PediatricNeuroSarcExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBehcetExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pBehcet||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_neuro_ext142',function:'PediatricBehcetExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeuroLupusExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pSLE||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_neuro_ext142',function:'PediatricNeuroLupusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVasculitisExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pVasculitis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_neuro_ext142',function:'PediatricVasculitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricADEMext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.adem||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_neuro_ext142',function:'PediatricADEMext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMSChildExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMS||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_neuro_ext142',function:'PediatricMSChildExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNMOExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.nmo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_neuro_ext142',function:'PediatricNMOExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMOGExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.mog||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_neuro_ext142',function:'PediatricMOGExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAutoimmuneEncephExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAE||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_neuro_ext142',function:'PediatricAutoimmuneEncephExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFIRESext']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.fires||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.252.0',module:'pcc_pediatric_neuro_ext142',function:'PediatricFIRESext',input,score,ts:new Date().toISOString()}};

// TS: v3.252.0
