// filepath: pcc/pcc_pediatric_neuro_ext137/pcc_pediatric_neuro_ext137_engine.js
module.exports.version='v3.247.0';
module.exports.module='pcc_pediatric_neuro_ext137';
module.exports.functions={};
module.exports.functions['PediatricToxicEncephExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.toxin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_pediatric_neuro_ext137',function:'PediatricToxicEncephExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAccidentalODExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.od||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_pediatric_neuro_ext137',function:'PediatricAccidentalODExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAlcoholExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.alcohol||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_pediatric_neuro_ext137',function:'PediatricAlcoholExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricInhalantExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.inhalant||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_pediatric_neuro_ext137',function:'PediatricInhalantExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCOpoisoningExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.co||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_pediatric_neuro_ext137',function:'PediatricCOpoisoningExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLeadExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.lead||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_pediatric_neuro_ext137',function:'PediatricLeadExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMercuryExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.mercury||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_pediatric_neuro_ext137',function:'PediatricMercuryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOrganophosExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.op||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_pediatric_neuro_ext137',function:'PediatricOrganophosExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMethemoglobinExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.methb||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_pediatric_neuro_ext137',function:'PediatricMethemoglobinExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricETOHsyncopeExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.etohSyncope||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.247.0',module:'pcc_pediatric_neuro_ext137',function:'PediatricETOHsyncopeExt',input,score,ts:new Date().toISOString()}};

// TS: v3.247.0
