// filepath: pcc/pcc_pediatric_surg_ext113/pcc_pediatric_surg_ext113_engine.js
module.exports.version='v3.223.0';
module.exports.module='pcc_pediatric_surg_ext113';
module.exports.functions={};
module.exports.functions['PediatricCNSLymphomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.methotrexate||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_surg_ext113',function:'PediatricCNSLymphomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSecondaryCNSLymphomaSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.chemo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_surg_ext113',function:'PediatricSecondaryCNSLymphomaSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDLBCLSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.rituximab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_surg_ext113',function:'PediatricDLBCLSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBurkittSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.intrathecal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_surg_ext113',function:'PediatricBurkittSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIntravascularSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.chemo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_surg_ext113',function:'PediatricIntravascularSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLymphomatoidSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.rituximab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_surg_ext113',function:'PediatricLymphomatoidSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeurolymphomatosisSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.chemo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_surg_ext113',function:'PediatricNeurolymphomatosisSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLeptomeningealCarcSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.intrathecal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_surg_ext113',function:'PediatricLeptomeningealCarcSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainMetastasesSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.radiation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_surg_ext113',function:'PediatricBrainMetastasesSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricParaneoplasticSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.ivig||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_pediatric_surg_ext113',function:'PediatricParaneoplasticSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.223.0
