// filepath: pcc/pcc_pediatric_neuro_ext125/pcc_pediatric_neuro_ext125_engine.js
module.exports.version='v3.235.0';
module.exports.module='pcc_pediatric_neuro_ext125';
module.exports.functions={};
module.exports.functions['PediatricCVSText']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.sinus||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_neuro_ext125',function:'PediatricCVSText',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSagittalThrombExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.sagittal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_neuro_ext125',function:'PediatricSagittalThrombExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTransverseThrombExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.transverse||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_neuro_ext125',function:'PediatricTransverseThrombExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSigmoidThrombExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.sigmoid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_neuro_ext125',function:'PediatricSigmoidThrombExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCavernousThrombExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cavernous||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_neuro_ext125',function:'PediatricCavernousThrombExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDeepVenousThrombExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.deep||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_neuro_ext125',function:'PediatricDeepVenousThrombExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCorticalVeinExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cortical||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_neuro_ext125',function:'PediatricCorticalVeinExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSepticThrombExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.sepsis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_neuro_ext125',function:'PediatricSepticThrombExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAsepticThrombExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.aseptic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_neuro_ext125',function:'PediatricAsepticThrombExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPregnancyThrombExt']=function(input){const score=Math.round((0.18 + Number(input.age||15)*0.04 + Number(input.pregnancy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.235.0',module:'pcc_pediatric_neuro_ext125',function:'PediatricPregnancyThrombExt',input,score,ts:new Date().toISOString()}};

// TS: v3.235.0
