// Auto-generated by gen_p3master.py -- PCC 3.305.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.305.0';

function X339AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x339) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_339', function: 'X339AssessmentExt', input, score, ts: TS };
}

function X339ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x339) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_339', function: 'X339ScoreExt', input, score, ts: TS };
}

function X339StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x339) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_339', function: 'X339StageExt', input, score, ts: TS };
}

function X339PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x339) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_339', function: 'X339PlanExt', input, score, ts: TS };
}

function X339RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x339) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_339', function: 'X339RiskExt', input, score, ts: TS };
}

function X339DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x339) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_339', function: 'X339DoseExt', input, score, ts: TS };
}

function X339FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x339) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_339', function: 'X339FrequencyExt', input, score, ts: TS };
}

function X339DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x339) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_339', function: 'X339DurationExt', input, score, ts: TS };
}

function X339FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x339) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_339', function: 'X339FollowupExt', input, score, ts: TS };
}

function X339OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x339) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_339', function: 'X339OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X339AssessmentExt,
  X339ScoreExt,
  X339StageExt,
  X339PlanExt,
  X339RiskExt,
  X339DoseExt,
  X339FrequencyExt,
  X339DurationExt,
  X339FollowupExt,
  X339OutcomeExt,
};