// filepath: pcc/pcc_pediatric_neuro_ext139/pcc_pediatric_neuro_ext139_engine.js
module.exports.version='v3.249.0';
module.exports.module='pcc_pediatric_neuro_ext139';
module.exports.functions={};
module.exports.functions['PediatricAneurysmExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.aneurysm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.249.0',module:'pcc_pediatric_neuro_ext139',function:'PediatricAneurysmExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAVMExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.avm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.249.0',module:'pcc_pediatric_neuro_ext139',function:'PediatricAVMExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCavernomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.cavernoma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.249.0',module:'pcc_pediatric_neuro_ext139',function:'PediatricCavernomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMoyamoyaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.moyamoya||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.249.0',module:'pcc_pediatric_neuro_ext139',function:'PediatricMoyamoyaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricArteriopathyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.arteriopathy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.249.0',module:'pcc_pediatric_neuro_ext139',function:'PediatricArteriopathyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSickleStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.sickle||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.249.0',module:'pcc_pediatric_neuro_ext139',function:'PediatricSickleStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCVTExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cvt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.249.0',module:'pcc_pediatric_neuro_ext139',function:'PediatricCVTExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeonatalStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.neonatal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.249.0',module:'pcc_pediatric_neuro_ext139',function:'PediatricNeonatalStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPRESExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pres||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.249.0',module:'pcc_pediatric_neuro_ext139',function:'PediatricPRESExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRCVSExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.rcvs||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.249.0',module:'pcc_pediatric_neuro_ext139',function:'PediatricRCVSExt',input,score,ts:new Date().toISOString()}};

// TS: v3.249.0
