// filepath: pcc/pcc_preventive_medicine_ext102/pcc_preventive_medicine_ext102_engine.js
module.exports.version='v3.47.47.0';
module.exports.module='pcc_preventive_medicine_ext102';
module.exports.functions={};
module.exports.functions['PrevPrimExt']=function(input){const score=Math.round((0.18 + Number(input.pmPrim||1)*0.2 + Number(input.pmPrimType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.47.47.0',module:'pcc_preventive_medicine_ext102',function:'PrevPrimExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PrevSecExt']=function(input){const score=Math.round((0.18 + Number(input.pmSec||1)*0.2 + Number(input.pmSecType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.47.47.0',module:'pcc_preventive_medicine_ext102',function:'PrevSecExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PrevTertExt']=function(input){const score=Math.round((0.18 + Number(input.pmTert||1)*0.2 + Number(input.pmTertType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.47.47.0',module:'pcc_preventive_medicine_ext102',function:'PrevTertExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PrevVaccExt']=function(input){const score=Math.round((0.18 + Number(input.pmVacc||1)*0.2 + Number(input.pmVaccType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.47.47.0',module:'pcc_preventive_medicine_ext102',function:'PrevVaccExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PrevScreenExt']=function(input){const score=Math.round((0.18 + Number(input.pmScreen||1)*0.2 + Number(input.pmScreenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.47.47.0',module:'pcc_preventive_medicine_ext102',function:'PrevScreenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PrevCounselExt']=function(input){const score=Math.round((0.18 + Number(input.pmCounsel||1)*0.2 + Number(input.pmCounselType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.47.47.0',module:'pcc_preventive_medicine_ext102',function:'PrevCounselExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PrevRiskRedExt']=function(input){const score=Math.round((0.18 + Number(input.pmRisk||1)*0.2 + Number(input.pmRiskLevel||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.47.47.0',module:'pcc_preventive_medicine_ext102',function:'PrevRiskRedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PrevChemoprophExt']=function(input){const score=Math.round((0.18 + Number(input.pmChem||1)*0.2 + Number(input.pmChemType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.47.47.0',module:'pcc_preventive_medicine_ext102',function:'PrevChemoprophExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PrevHealthPromExt']=function(input){const score=Math.round((0.18 + Number(input.pmPromo||1)*0.2 + Number(input.pmPromoType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.47.47.0',module:'pcc_preventive_medicine_ext102',function:'PrevHealthPromExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PrevAdherenceExt']=function(input){const score=Math.round((0.18 + Number(input.pmAdh||1)*0.2 + Number(input.pmAdhRate||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.47.47.0',module:'pcc_preventive_medicine_ext102',function:'PrevAdherenceExt',input,score,ts:new Date().toISOString()}};

// TS: v3.47.47.0
