// filepath: pcc/pcc_pediatric_neuro_ext176/pcc_pediatric_neuro_ext176_engine.js
module.exports.version='v3.16.16.0';
module.exports.module='pcc_pediatric_neuro_ext176';
module.exports.functions={};
module.exports.functions['PediatricMetabolicBrainExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pMetabBrain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_pediatric_neuro_ext176',function:'PediatricMetabolicBrainExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricUreaCycleExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pUreaCycle||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_pediatric_neuro_ext176',function:'PediatricUreaCycleExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWilsonExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pWilson||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_pediatric_neuro_ext176',function:'PediatricWilsonExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMitoEncephExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pMitoEnceph||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_pediatric_neuro_ext176',function:'PediatricMitoEncephExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMELASExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pMELAS||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_pediatric_neuro_ext176',function:'PediatricMELASExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMERRFExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pMERRF||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_pediatric_neuro_ext176',function:'PediatricMERRFExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNARPExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pNARP||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_pediatric_neuro_ext176',function:'PediatricNARPExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLHONExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pLHON||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_pediatric_neuro_ext176',function:'PediatricLHONExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLeighExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pLeigh||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_pediatric_neuro_ext176',function:'PediatricLeighExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPDHCExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pPDHC||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.16.16.0',module:'pcc_pediatric_neuro_ext176',function:'PediatricPDHCExt',input,score,ts:new Date().toISOString()}};

// TS: v3.16.16.0
