// filepath: pcc/pcc_pediatric_neuro_ext138/pcc_pediatric_neuro_ext138_engine.js
module.exports.version='v3.248.0';
module.exports.module='pcc_pediatric_neuro_ext138';
module.exports.functions={};
module.exports.functions['PediatricNF1Ext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.nf1||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_neuro_ext138',function:'PediatricNF1Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNF2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.nf2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_neuro_ext138',function:'PediatricNF2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTuberousExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.tsc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_neuro_ext138',function:'PediatricTuberousExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSturgeWeberExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.sw||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_neuro_ext138',function:'PediatricSturgeWeberExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAtaxiaTelExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.at||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_neuro_ext138',function:'PediatricAtaxiaTelExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVHLchildExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.vhl||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_neuro_ext138',function:'PediatricVHLchildExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMitoEncephExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.mito||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_neuro_ext138',function:'PediatricMitoEncephExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLeighExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.leigh||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_neuro_ext138',function:'PediatricLeighExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDravetExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.dravet||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_neuro_ext138',function:'PediatricDravetExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWestSynExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.west||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.248.0',module:'pcc_pediatric_neuro_ext138',function:'PediatricWestSynExt',input,score,ts:new Date().toISOString()}};

// TS: v3.248.0
