-- rare_103 reverse
BEGIN;
DROP TABLE IF EXISTS rare_103_results CASCADE;
DROP TABLE IF EXISTS rare_103_orders  CASCADE;
DROP TABLE IF EXISTS rare_103_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_RARE_103_up';
COMMIT;
