// filepath: pcc/pcc_pediatric_neuro_ext93/pcc_pediatric_neuro_ext93_engine.js
// pcc_pediatric_neuro_ext93 engine (deterministic)
module.exports.version='v3.203.0';
module.exports.module='pcc_pediatric_neuro_ext93';
module.exports.functions={};
module.exports.functions['PediatricStrokeRehabExt']=function(input){const score=Math.round((0.15 + Number(input.age||5)*0.04 + Number(input.intensity||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_neuro_ext93',function:'PediatricStrokeRehabExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStrokeSecondaryPreventionExt']=function(input){const score=Math.round((0.15 + Number(input.cause||1)*0.2 + Number(input.antiplatelet||1)*0.15 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_neuro_ext93',function:'PediatricStrokeSecondaryPreventionExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCryptogenicStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.pfo||1)*0.2 + Number(input.hypercoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_neuro_ext93',function:'PediatricCryptogenicStrokeExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricCSVTWorkupExt']=function(input){const score=Math.round((0.18 + Number(input.clotSite||2)*0.1 + Number(input.anticoag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_neuro_ext93',function:'PediatricCSVTWorkupExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSickleCellStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.transfusion||1)*0.2 + Number(input.transcranialDoppler||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_neuro_ext93',function:'PediatricSickleCellStrokeExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStrokeInYoungExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.moya||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_neuro_ext93',function:'PediatricStrokeInYoungExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricArtDiseaseStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.arteriopathy||1)*0.2 + Number(input.recur||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_neuro_ext93',function:'PediatricArtDiseaseStrokeExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStrokeLateEffectsExt']=function(input){const score=Math.round((0.15 + Number(input.intensity||3)*0.1 + Number(input.weeks||12)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_neuro_ext93',function:'PediatricStrokeLateEffectsExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStrokeGeneticExt']=function(input){const score=Math.round((0.15 + Number(input.mutations||2)*0.1 + Number(input.syndromic||1)*0.15 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_neuro_ext93',function:'PediatricStrokeGeneticExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStrokeFamilyScreenExt']=function(input){const score=Math.round((0.15 + Number(input.familyHist||1)*0.15 + Number(input.testing||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.203.0',module:'pcc_pediatric_neuro_ext93',function:'PediatricStrokeFamilyScreenExt',input,score,ts:new Date().toISOString()};};

// TS: v3.203.0
