// Auto-generated by gen_p3master.py -- PCC 3.191.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.191.0';

function PRXAssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.prxa) || 0) * 0.2) * 100) / 100;
  return { version: VER, module: 'pcc_pulmonary_rehab', function: 'PRXAssessmentExt', input, score, ts: TS };
}

function PRXScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.prxs) || 0) * 0.31) * 100) / 100;
  return { version: VER, module: 'pcc_pulmonary_rehab', function: 'PRXScoreExt', input, score, ts: TS };
}

function PRXStageExt(input) {
  const score = Math.round((0.3 + (Number(input.prxs) || 0) * 0.32) * 100) / 100;
  return { version: VER, module: 'pcc_pulmonary_rehab', function: 'PRXStageExt', input, score, ts: TS };
}

function PRXPlanExt(input) {
  const score = Math.round((0.3 + (Number(input.prxp) || 0) * 0.28) * 100) / 100;
  return { version: VER, module: 'pcc_pulmonary_rehab', function: 'PRXPlanExt', input, score, ts: TS };
}

function PRXRiskExt(input) {
  const score = Math.round((0.3 + (Number(input.prxr) || 0) * 0.29) * 100) / 100;
  return { version: VER, module: 'pcc_pulmonary_rehab', function: 'PRXRiskExt', input, score, ts: TS };
}

function PRXDoseExt(input) {
  const score = Math.round((0.3 + (Number(input.prxd) || 0) * 0.3) * 100) / 100;
  return { version: VER, module: 'pcc_pulmonary_rehab', function: 'PRXDoseExt', input, score, ts: TS };
}

function PRXFrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.prxf) || 0) * 0.21) * 100) / 100;
  return { version: VER, module: 'pcc_pulmonary_rehab', function: 'PRXFrequencyExt', input, score, ts: TS };
}

function PRXDurationExt(input) {
  const score = Math.round((0.3 + (Number(input.prxd) || 0) * 0.17) * 100) / 100;
  return { version: VER, module: 'pcc_pulmonary_rehab', function: 'PRXDurationExt', input, score, ts: TS };
}

function PRXFollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.prxf) || 0) * 0.18) * 100) / 100;
  return { version: VER, module: 'pcc_pulmonary_rehab', function: 'PRXFollowupExt', input, score, ts: TS };
}

function PRXOutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.prxo) || 0) * 0.49) * 100) / 100;
  return { version: VER, module: 'pcc_pulmonary_rehab', function: 'PRXOutcomeExt', input, score, ts: TS };
}

module.exports = {
  PRXAssessmentExt,
  PRXScoreExt,
  PRXStageExt,
  PRXPlanExt,
  PRXRiskExt,
  PRXDoseExt,
  PRXFrequencyExt,
  PRXDurationExt,
  PRXFollowupExt,
  PRXOutcomeExt,
};