// Auto-generated by gen_p3master.py -- PCC 3.297.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.297.0';

function X313AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x313) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_313', function: 'X313AssessmentExt', input, score, ts: TS };
}

function X313ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x313) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_313', function: 'X313ScoreExt', input, score, ts: TS };
}

function X313StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x313) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_313', function: 'X313StageExt', input, score, ts: TS };
}

function X313PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x313) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_313', function: 'X313PlanExt', input, score, ts: TS };
}

function X313RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x313) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_313', function: 'X313RiskExt', input, score, ts: TS };
}

function X313DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x313) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_313', function: 'X313DoseExt', input, score, ts: TS };
}

function X313FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x313) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_313', function: 'X313FrequencyExt', input, score, ts: TS };
}

function X313DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x313) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_313', function: 'X313DurationExt', input, score, ts: TS };
}

function X313FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x313) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_313', function: 'X313FollowupExt', input, score, ts: TS };
}

function X313OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x313) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_313', function: 'X313OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X313AssessmentExt,
  X313ScoreExt,
  X313StageExt,
  X313PlanExt,
  X313RiskExt,
  X313DoseExt,
  X313FrequencyExt,
  X313DurationExt,
  X313FollowupExt,
  X313OutcomeExt,
};