// filepath: pcc/pcc_pediatric_neuro_ext175/pcc_pediatric_neuro_ext175_engine.js
module.exports.version='v3.15.15.0';
module.exports.module='pcc_pediatric_neuro_ext175';
module.exports.functions={};
module.exports.functions['PediatricCSFleakExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pCSFleak||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_neuro_ext175',function:'PediatricCSFleakExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChiariExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pChiari||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_neuro_ext175',function:'PediatricChiariExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSyringoExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pSyringo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_neuro_ext175',function:'PediatricSyringoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTetheredExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pTethered||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_neuro_ext175',function:'PediatricTetheredExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSpinaBifidaExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pSpinaBifida||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_neuro_ext175',function:'PediatricSpinaBifidaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHydroExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pHydro||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_neuro_ext175',function:'PediatricHydroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIIHext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pIIH||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_neuro_ext175',function:'PediatricIIHext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDandyWalkerExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pDandy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_neuro_ext175',function:'PediatricDandyWalkerExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAqueductStenExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAqueduct||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_neuro_ext175',function:'PediatricAqueductStenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricArachnoidCystExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pArachnoid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_pediatric_neuro_ext175',function:'PediatricArachnoidCystExt',input,score,ts:new Date().toISOString()}};

// TS: v3.15.15.0
