// Auto_generated by gen_p3ig.py -- PCC v3.187.0
"use strict";
const TS = '2026-07-28T15:20:00Z';

function MedicalRefractoryEpilepsyExt(input) { const score = Math.round((0.45+Number(input.failed_drugs||3)*0.1)*100)/100; return { version:'3.187.0', module:'pcc_neuro_ext88', function:"MedicalRefractoryEpilepsyExt", input, score, ts: TS }; }

function SurgicalEpilepsyEvalExt(input) { const score = Math.round((0.4+Number(input.localization||1)*0.15)*100)/100; return { version:'3.187.0', module:'pcc_neuro_ext88', function:"SurgicalEpilepsyEvalExt", input, score, ts: TS }; }

function LaserAblationExt(input) { const score = Math.round((0.4+Number(input.depth_mm||10)*0.025)*100)/100; return { version:'3.187.0', module:'pcc_neuro_ext88', function:"LaserAblationExt", input, score, ts: TS }; }

function RNSExt(input) { const score = Math.round((0.4+Number(input.detections||5)*0.04)*100)/100; return { version:'3.187.0', module:'pcc_neuro_ext88', function:"RNSExt", input, score, ts: TS }; }

function DBSForEpilepsyExt(input) { const score = Math.round((0.45+Number(input.seizure_freq||5)*0.05)*100)/100; return { version:'3.187.0', module:'pcc_neuro_ext88', function:"DBSForEpilepsyExt", input, score, ts: TS }; }

function VagusNerveTuneExt(input) { const score = Math.round((0.3+Number(input.output||1)*0.05)*100)/100; return { version:'3.187.0', module:'pcc_neuro_ext88', function:"VagusNerveTuneExt", input, score, ts: TS }; }

function KetogenicDietNeuroExt(input) { const score = Math.round((0.3+Number(input.ketone||3)*0.1)*100)/100; return { version:'3.187.0', module:'pcc_neuro_ext88', function:"KetogenicDietNeuroExt", input, score, ts: TS }; }

function ACTHExt(input) { const score = Math.round((0.3+Number(input.dose_mg||80)*0.005)*100)/100; return { version:'3.187.0', module:'pcc_neuro_ext88', function:"ACTHExt", input, score, ts: TS }; }

function EpilepsyGeneticExt(input) { const score = Math.round((0.4+Number(input.variant||1)*0.15)*100)/100; return { version:'3.187.0', module:'pcc_neuro_ext88', function:"EpilepsyGeneticExt", input, score, ts: TS }; }

function SuddenUnexpectedDeathEpilepsyRiskExt(input) { const score = Math.round((0.4+Number(input.seizure_type||2)*0.1)*100)/100; return { version:'3.187.0', module:'pcc_neuro_ext88', function:"SuddenUnexpectedDeathEpilepsyRiskExt", input, score, ts: TS }; }

module.exports = {
  MedicalRefractoryEpilepsyExt,
  SurgicalEpilepsyEvalExt,
  LaserAblationExt,
  RNSExt,
  DBSForEpilepsyExt,
  VagusNerveTuneExt,
  KetogenicDietNeuroExt,
  ACTHExt,
  EpilepsyGeneticExt,
  SuddenUnexpectedDeathEpilepsyRiskExt,
};