// filepath: pcc/pcc_pediatric_neuro_ext148/pcc_pediatric_neuro_ext148_engine.js
module.exports.version='v3.258.0';
module.exports.module='pcc_pediatric_neuro_ext148';
module.exports.functions={};
module.exports.functions['PediatricFebrileSzExt']=function(input){const score=Math.round((0.18 + Number(input.age||2)*0.04 + Number(input.pFebSz||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.258.0',module:'pcc_pediatric_neuro_ext148',function:'PediatricFebrileSzExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEpilepsyNewExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pEpNew||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.258.0',module:'pcc_pediatric_neuro_ext148',function:'PediatricEpilepsyNewExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRefractoryExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pRefract||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.258.0',module:'pcc_pediatric_neuro_ext148',function:'PediatricRefractoryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStatusEpiExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pSE||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.258.0',module:'pcc_pediatric_neuro_ext148',function:'PediatricStatusEpiExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNCSEext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pNCSE||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.258.0',module:'pcc_pediatric_neuro_ext148',function:'PediatricNCSEext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAbsenceExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAbsence||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.258.0',module:'pcc_pediatric_neuro_ext148',function:'PediatricAbsenceExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMyoclonicExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pMyoclon||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.258.0',module:'pcc_pediatric_neuro_ext148',function:'PediatricMyoclonicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTonicExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pTonic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.258.0',module:'pcc_pediatric_neuro_ext148',function:'PediatricTonicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAtonicExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pAtonic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.258.0',module:'pcc_pediatric_neuro_ext148',function:'PediatricAtonicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBenignExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pBenign||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.258.0',module:'pcc_pediatric_neuro_ext148',function:'PediatricBenignExt',input,score,ts:new Date().toISOString()}};

// TS: v3.258.0
