// filepath: pcc/pcc_pediatric_surg_ext169/pcc_pediatric_surg_ext169_engine.js
module.exports.version='v3.1.9.0';
module.exports.module='pcc_pediatric_surg_ext169';
module.exports.functions={};
module.exports.functions['PediatricNeuroICUTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pNeuroICUTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_surg_ext169',function:'PediatricNeuroICUTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHerniationTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pHerniationTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_surg_ext169',function:'PediatricHerniationTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricICPTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pICPTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_surg_ext169',function:'PediatricICPTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStatusEpiICUTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pSEicuTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_surg_ext169',function:'PediatricStatusEpiICUTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMeningitisTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pMeningitisTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_surg_ext169',function:'PediatricMeningitisTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEncephTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pEncephTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_surg_ext169',function:'PediatricEncephTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainAbscessTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAbscessTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_surg_ext169',function:'PediatricBrainAbscessTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVentNeuroTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pVentNeuroTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_surg_ext169',function:'PediatricVentNeuroTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVasospasmTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pVasospasmTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_surg_ext169',function:'PediatricVasospasmTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainDeathTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pBrainDeathTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.9.0',module:'pcc_pediatric_surg_ext169',function:'PediatricBrainDeathTxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.9.0
