// filepath: pcc/pcc_neuro_ext122/pcc_neuro_ext122_engine.js
module.exports.version='v3.221.0';
module.exports.module='pcc_neuro_ext122';
module.exports.functions={};
module.exports.functions['MeningiomaWHO1Ext']=function(input){const score=Math.round((0.18 + Number(input.size||3)*0.1 + Number(input.location||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_neuro_ext122',function:'MeningiomaWHO1Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['MeningiomaWHO2Ext']=function(input){const score=Math.round((0.18 + Number(input.size||3)*0.1 + Number(input.atypical||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_neuro_ext122',function:'MeningiomaWHO2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['MeningiomaWHO3Ext']=function(input){const score=Math.round((0.18 + Number(input.anaplastic||1)*0.2 + Number(input.brainInvasion||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_neuro_ext122',function:'MeningiomaWHO3Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['CavernousSinusMeningiomaExt']=function(input){const score=Math.round((0.18 + Number(input.cavernous||1)*0.2 + Number(input.cranial||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_neuro_ext122',function:'CavernousSinusMeningiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OlfactoryGrooveMeningiomaExt']=function(input){const score=Math.round((0.18 + Number(input.anosmia||1)*0.2 + Number(input.bilateral||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_neuro_ext122',function:'OlfactoryGrooveMeningiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ParasagittalMeningiomaExt']=function(input){const score=Math.round((0.18 + Number(input.sagittal||1)*0.2 + Number(input.invasionSinus||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_neuro_ext122',function:'ParasagittalMeningiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ConvexityMeningiomaExt']=function(input){const score=Math.round((0.18 + Number(input.convexity||1)*0.2 + Number(input.grossTotal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_neuro_ext122',function:'ConvexityMeningiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SphenoidWingMeningiomaExt']=function(input){const score=Math.round((0.18 + Number(input.sphenoid||1)*0.2 + Number(input.optico||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_neuro_ext122',function:'SphenoidWingMeningiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PosteriorFossaMeningiomaExt']=function(input){const score=Math.round((0.18 + Number(input.posteriorFossa||1)*0.2 + Number(input.brainstem||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_neuro_ext122',function:'PosteriorFossaMeningiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SpinalMeningiomaExt']=function(input){const score=Math.round((0.18 + Number(input.spinal||1)*0.2 + Number(input.cordCompression||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_neuro_ext122',function:'SpinalMeningiomaExt',input,score,ts:new Date().toISOString()}};

// TS: v3.221.0
