// filepath: pcc/pcc_pediatric_surg_ext104/pcc_pediatric_surg_ext104_engine.js
module.exports.version='v3.214.0';
module.exports.module='pcc_pediatric_surg_ext104';
module.exports.functions={};
module.exports.functions['PediatricTBIsxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ICPmonitor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_pediatric_surg_ext104',function:'PediatricTBIsxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricConcussionSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.rest||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_pediatric_surg_ext104',function:'PediatricConcussionSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPostConcussionSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.vestibular||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_pediatric_surg_ext104',function:'PediatricPostConcussionSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSDHsxExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.burrHole||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_pediatric_surg_ext104',function:'PediatricSDHsxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEDHsxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.craniectomy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_pediatric_surg_ext104',function:'PediatricEDHsxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSAHTraumaticSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.observation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_pediatric_surg_ext104',function:'PediatricSAHTraumaticSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDAEsxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ICPcontrol||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_pediatric_surg_ext104',function:'PediatricDAEsxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPenetratingSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.debridement||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_pediatric_surg_ext104',function:'PediatricPenetratingSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSkullBaseSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.repair||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_pediatric_surg_ext104',function:'PediatricSkullBaseSxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCSFleakSxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.lumbarDrain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_pediatric_surg_ext104',function:'PediatricCSFleakSxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.214.0
