// Auto-generated by gen_p3gu.py -- PCC v3.163.0
"use strict";
const TS = '2026-07-28T11:20:00Z';

function PediatricVenousSinusStentSurgeryExt(input) { const score = Math.round((0.4+Number(input.stent_diameter_mm||6)/20)*100)/100; return { version:'3.163.0', module:'pcc_pediatric_surg_ext53', function:'PediatricVenousSinusStentSurgeryExt', input, score, ts: TS }; }

function PediatricVPShuntTapTestExt(input) { const score = Math.round((0.2+Number(input.tap_response||1)*0.08)*100)/100; return { version:'3.163.0', module:'pcc_pediatric_surg_ext53', function:'PediatricVPShuntTapTestExt', input, score, ts: TS }; }

function PediatricChiariDecompressionExt(input) { const score = Math.round((0.4+Number(input.bone_removal_mm||10)*0.03)*100)/100; return { version:'3.163.0', module:'pcc_pediatric_surg_ext53', function:'PediatricChiariDecompressionExt', input, score, ts: TS }; }

function PediatricSyrinxShuntExt(input) { const score = Math.round((0.35+Number(input.syrinx_size_mm||8)*0.04)*100)/100; return { version:'3.163.0', module:'pcc_pediatric_surg_ext53', function:'PediatricSyrinxShuntExt', input, score, ts: TS }; }

function PediatricBasilarInvaginationSurgeryExt(input) { const score = Math.round((0.5+Number(input.reduction_mm||5)*0.05)*100)/100; return { version:'3.163.0', module:'pcc_pediatric_surg_ext53', function:'PediatricBasilarInvaginationSurgeryExt', input, score, ts: TS }; }

function PediatricOccipitalCervicalFusionExt(input) { const score = Math.round((0.45+Number(input.levels_fused||3)*0.05)*100)/100; return { version:'3.163.0', module:'pcc_pediatric_surg_ext53', function:'PediatricOccipitalCervicalFusionExt', input, score, ts: TS }; }

function PediatricVPShuntPlacementExt(input) { const score = Math.round((0.3+Number(input.catheter_length||30)*0.01)*100)/100; return { version:'3.163.0', module:'pcc_pediatric_surg_ext53', function:'PediatricVPShuntPlacementExt', input, score, ts: TS }; }

function PediatricEndoscopicThirdVentriculostomyExt(input) { const score = Math.round((0.4+Number(input.ostomy_size||5)*0.05)*100)/100; return { version:'3.163.0', module:'pcc_pediatric_surg_ext53', function:'PediatricEndoscopicThirdVentriculostomyExt', input, score, ts: TS }; }

function PediatricCSFDiversionExt(input) { const score = Math.round((0.35+Number(input.drain_Level||1)*0.04)*100)/100; return { version:'3.163.0', module:'pcc_pediatric_surg_ext53', function:'PediatricCSFDiversionExt', input, score, ts: TS }; }

function PediatricEndoscopicFenestrationExt(input) { const score = Math.round((0.4+Number(input.fenestrations||2)*0.06)*100)/100; return { version:'3.163.0', module:'pcc_pediatric_surg_ext53', function:'PediatricEndoscopicFenestrationExt', input, score, ts: TS }; }

module.exports = {
  PediatricVenousSinusStentSurgeryExt,
  PediatricVPShuntTapTestExt,
  PediatricChiariDecompressionExt,
  PediatricSyrinxShuntExt,
  PediatricBasilarInvaginationSurgeryExt,
  PediatricOccipitalCervicalFusionExt,
  PediatricVPShuntPlacementExt,
  PediatricEndoscopicThirdVentriculostomyExt,
  PediatricCSFDiversionExt,
  PediatricEndoscopicFenestrationExt,
};