-- card_105 reverse
BEGIN;
DROP TABLE IF EXISTS card_105_results CASCADE;
DROP TABLE IF EXISTS card_105_orders  CASCADE;
DROP TABLE IF EXISTS card_105_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_CARD_105_up';
COMMIT;
