// filepath: pcc/pcc_ctsurg_ext101/pcc_ctsurg_ext101_engine.js
module.exports.version='v3.32.32.0';
module.exports.module='pcc_ctsurg_ext101';
module.exports.functions={};
module.exports.functions['CTThoracicExt']=function(input){const score=Math.round((0.18 + Number(input.ctThoracic||1)*0.2 + Number(input.thoracicProc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.32.32.0',module:'pcc_ctsurg_ext101',function:'CTThoracicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTLobectomyExt']=function(input){const score=Math.round((0.18 + Number(input.ctLobectomy||1)*0.2 + Number(input.lobeResected||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.32.32.0',module:'pcc_ctsurg_ext101',function:'CTLobectomyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTPneumonectomyExt']=function(input){const score=Math.round((0.18 + Number(input.ctPneumon||1)*0.2 + Number(input.pneumonType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.32.32.0',module:'pcc_ctsurg_ext101',function:'CTPneumonectomyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTMediastinoscopyExt']=function(input){const score=Math.round((0.18 + Number(input.ctMediast||1)*0.2 + Number(input.mediastFinding||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.32.32.0',module:'pcc_ctsurg_ext101',function:'CTMediastinoscopyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTEsophagectomyExt']=function(input){const score=Math.round((0.18 + Number(input.ctEsoph||1)*0.2 + Number(input.esophApproach||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.32.32.0',module:'pcc_ctsurg_ext101',function:'CTEsophagectomyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTTrachealExt']=function(input){const score=Math.round((0.18 + Number(input.ctTracheal||1)*0.2 + Number(input.trachealProc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.32.32.0',module:'pcc_ctsurg_ext101',function:'CTTrachealExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTChestWallExt']=function(input){const score=Math.round((0.18 + Number(input.ctChestWall||1)*0.2 + Number(input.chestWallProc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.32.32.0',module:'pcc_ctsurg_ext101',function:'CTChestWallExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTDiaphragmExt']=function(input){const score=Math.round((0.18 + Number(input.ctDiaphragm||1)*0.2 + Number(input.diaphragmProc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.32.32.0',module:'pcc_ctsurg_ext101',function:'CTDiaphragmExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTTraumaExt']=function(input){const score=Math.round((0.18 + Number(input.ctTrauma||1)*0.2 + Number(input.chestTraumaSev||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.32.32.0',module:'pcc_ctsurg_ext101',function:'CTTraumaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CTPediatricExt']=function(input){const score=Math.round((0.18 + Number(input.ctPed||1)*0.2 + Number(input.pedAge||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.32.32.0',module:'pcc_ctsurg_ext101',function:'CTPediatricExt',input,score,ts:new Date().toISOString()}};

// TS: v3.32.32.0
