// filepath: pcc/pcc_path_ext179/pcc_path_ext179_engine.js
module.exports.version='v3.15.15.0';
module.exports.module='pcc_path_ext179';
module.exports.functions={};
module.exports.functions['PathDiabetesExt']=function(input){const score=Math.round((0.18 + Number(input.pathDM||1)*0.2 + Number(input.pathType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_path_ext179',function:'PathDiabetesExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PathRenalBiopsyExt']=function(input){const score=Math.round((0.18 + Number(input.pathRenalBx||1)*0.2 + Number(input.igaStain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_path_ext179',function:'PathRenalBiopsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PathLiverBiopsyExt']=function(input){const score=Math.round((0.18 + Number(input.pathLiverBx||1)*0.2 + Number(input.fibrosisStage||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_path_ext179',function:'PathLiverBiopsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PathCardiacBiopsyExt']=function(input){const score=Math.round((0.18 + Number(input.pathCardiacBx||1)*0.2 + Number(input.amyloidCardiac||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_path_ext179',function:'PathCardiacBiopsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PathSkinBiopsyExt']=function(input){const score=Math.round((0.18 + Number(input.pathSkinBx||1)*0.2 + Number(input.skinFinding||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_path_ext179',function:'PathSkinBiopsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PathLymphNodeExt']=function(input){const score=Math.round((0.18 + Number(input.pathLN||1)*0.2 + Number(input.lymphStage||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_path_ext179',function:'PathLymphNodeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PathBoneMarrowExt']=function(input){const score=Math.round((0.18 + Number(input.pathBM||1)*0.2 + Number(input.cellularity||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_path_ext179',function:'PathBoneMarrowExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PathGIbiopsyExt']=function(input){const score=Math.round((0.18 + Number(input.pathGIbx||1)*1*0.2 + Number(input.giFinding||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_path_ext179',function:'PathGIbiopsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PathLiquidBxExt']=function(input){const score=Math.round((0.18 + Number(input.pathLiquidBx||1)*0.2 + Number(input.liquidType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_path_ext179',function:'PathLiquidBxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PathMolecularExt']=function(input){const score=Math.round((0.18 + Number(input.pathMol||1)*0.2 + Number(input.molMarker||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.15.15.0',module:'pcc_path_ext179',function:'PathMolecularExt',input,score,ts:new Date().toISOString()}};

// TS: v3.15.15.0
