// Auto-generated by gen_p3master.py -- PCC 3.280.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.280.0';

function X263AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x263) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_263', function: 'X263AssessmentExt', input, score, ts: TS };
}

function X263ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x263) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_263', function: 'X263ScoreExt', input, score, ts: TS };
}

function X263StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x263) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_263', function: 'X263StageExt', input, score, ts: TS };
}

function X263PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x263) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_263', function: 'X263PlanExt', input, score, ts: TS };
}

function X263RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x263) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_263', function: 'X263RiskExt', input, score, ts: TS };
}

function X263DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x263) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_263', function: 'X263DoseExt', input, score, ts: TS };
}

function X263FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x263) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_263', function: 'X263FrequencyExt', input, score, ts: TS };
}

function X263DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x263) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_263', function: 'X263DurationExt', input, score, ts: TS };
}

function X263FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x263) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_263', function: 'X263FollowupExt', input, score, ts: TS };
}

function X263OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x263) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_263', function: 'X263OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X263AssessmentExt,
  X263ScoreExt,
  X263StageExt,
  X263PlanExt,
  X263RiskExt,
  X263DoseExt,
  X263FrequencyExt,
  X263DurationExt,
  X263FollowupExt,
  X263OutcomeExt,
};