// filepath: pcc/pcc_rare_diseases_ext102/pcc_rare_diseases_ext102_engine.js
module.exports.version='v3.40.40.0';
module.exports.module='pcc_rare_diseases_ext102';
module.exports.functions={};
module.exports.functions['RareDxExt']=function(input){const score=Math.round((0.18 + Number(input.rdDx||1)*0.2 + Number(input.rdDxType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_rare_diseases_ext102',function:'RareDxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RarePrevalenceExt']=function(input){const score=Math.round((0.18 + Number(input.rdPrev||1)*0.2 + Number(input.rdPrevRate||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_rare_diseases_ext102',function:'RarePrevalenceExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RareRegistryExt']=function(input){const score=Math.round((0.18 + Number(input.rdReg||1)*0.2 + Number(input.rdRegSize||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_rare_diseases_ext102',function:'RareRegistryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RareCenterExt']=function(input){const score=Math.round((0.18 + Number(input.rdCenter||1)*0.2 + Number(input.rdCenterType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_rare_diseases_ext102',function:'RareCenterExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RarePediatricExt']=function(input){const score=Math.round((0.18 + Number(input.rdPed||1)*0.2 + Number(input.rdPedAge||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_rare_diseases_ext102',function:'RarePediatricExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RareNewbornExt']=function(input){const score=Math.round((0.18 + Number(input.rdNBS||1)*0.2 + Number(input.rdNbsCond||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_rare_diseases_ext102',function:'RareNewbornExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RareGeneticExt']=function(input){const score=Math.round((0.18 + Number(input.rdGen||1)*0.2 + Number(input.rdGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_rare_diseases_ext102',function:'RareGeneticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RareMetabolicExt']=function(input){const score=Math.round((0.18 + Number(input.rdMet||1)*0.2 + Number(input.rdMetType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_rare_diseases_ext102',function:'RareMetabolicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RareAdultExt']=function(input){const score=Math.round((0.18 + Number(input.rdAdult||1)*0.2 + Number(input.rdAdultType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_rare_diseases_ext102',function:'RareAdultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RareSupportExt']=function(input){const score=Math.round((0.18 + Number(input.rdSupport||1)*0.2 + Number(input.rdSupportType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_rare_diseases_ext102',function:'RareSupportExt',input,score,ts:new Date().toISOString()}};

// TS: v3.40.40.0
