// filepath: pcc/pcc_performance_ext102/pcc_performance_ext102_engine.js
module.exports.version='v3.48.48.0';
module.exports.module='pcc_performance_ext102';
module.exports.functions={};
module.exports.functions['PerfAeroExt']=function(input){const score=Math.round((0.18 + Number(input.pfAero||1)*0.2 + Number(input.pfAeroVO2||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_performance_ext102',function:'PerfAeroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PerfStrengthExt']=function(input){const score=Math.round((0.18 + Number(input.pfStr||1)*0.2 + Number(input.pfStr1RM||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_performance_ext102',function:'PerfStrengthExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PerfEnduranceExt']=function(input){const score=Math.round((0.18 + Number(input.pfEnd||1)*0.2 + Number(input.pfEndMin||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_performance_ext102',function:'PerfEnduranceExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PerfFlexExt']=function(input){const score=Math.round((0.18 + Number(input.pfFlex||1)*0.2 + Number(input.pfFlexScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_performance_ext102',function:'PerfFlexExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PerfAgilityExt']=function(input){const score=Math.round((0.18 + Number(input.pfAg||1)*0.2 + Number(input.pfAgScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_performance_ext102',function:'PerfAgilityExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PerfBalanceExt']=function(input){const score=Math.round((0.18 + Number(input.pfBal||1)*0.2 + Number(input.pfBalScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_performance_ext102',function:'PerfBalanceExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PerfPowerExt']=function(input){const score=Math.round((0.18 + Number(input.pfPow||1)*0.2 + Number(input.pfPowScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_performance_ext102',function:'PerfPowerExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PerfSpeedExt']=function(input){const score=Math.round((0.18 + Number(input.pfSpd||1)*0.2 + Number(input.pfSpdSec||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_performance_ext102',function:'PerfSpeedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PerfReactionExt']=function(input){const score=Math.round((0.18 + Number(input.pfReact||1)*0.2 + Number(input.pfReactMs||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_performance_ext102',function:'PerfReactionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PerfRecoveryExt']=function(input){const score=Math.round((0.18 + Number(input.pfRec||1)*0.2 + Number(input.pfRecHRV||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_performance_ext102',function:'PerfRecoveryExt',input,score,ts:new Date().toISOString()}};

// TS: v3.48.48.0
