// filepath: pcc/pcc_pediatric_surg_ext141/pcc_pediatric_surg_ext141_engine.js
module.exports.version='v3.251.0';
module.exports.module='pcc_pediatric_surg_ext141';
module.exports.functions={};
module.exports.functions['PediatricComaSupportExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.supportPcoma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.251.0',module:'pcc_pediatric_surg_ext141',function:'PediatricComaSupportExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVSCareExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.vsCare||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.251.0',module:'pcc_pediatric_surg_ext141',function:'PediatricVSCareExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMCSrehabExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.mcsRehab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.251.0',module:'pcc_pediatric_surg_ext141',function:'PediatricMCSrehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLockedCommExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.commDevice||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.251.0',module:'pcc_pediatric_surg_ext141',function:'PediatricLockedCommExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainDeathTestExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.apneaTest||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.251.0',module:'pcc_pediatric_surg_ext141',function:'PediatricBrainDeathTestExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTTMExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.ttm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.251.0',module:'pcc_pediatric_surg_ext141',function:'PediatricTTMExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHIBECoolingExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.cooling||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.251.0',module:'pcc_pediatric_surg_ext141',function:'PediatricHIBECoolingExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMSUDdietExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.dietMSUD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.251.0',module:'pcc_pediatric_surg_ext141',function:'PediatricMSUDdietExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricUreaDialysisExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.dialysis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.251.0',module:'pcc_pediatric_surg_ext141',function:'PediatricUreaDialysisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAntiNMDARIVIGExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.ivigNMDAR||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.251.0',module:'pcc_pediatric_surg_ext141',function:'PediatricAntiNMDARIVIGExt',input,score,ts:new Date().toISOString()}};

// TS: v3.251.0
