// filepath: pcc/pcc_neuro_ext171/pcc_neuro_ext171_engine.js
module.exports.version='v3.12.12.0';
module.exports.module='pcc_neuro_ext171';
module.exports.functions={};
module.exports.functions['MuscularDystrophyBMDExt']=function(input){const score=Math.round((0.18 + Number(input.bmdGenetic||1)*0.2 + Number(input.dystrophin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_neuro_ext171',function:'MuscularDystrophyBMDExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LimbGirdleExt']=function(input){const score=Math.round((0.18 + Number(input.lgmd||1)*0.2 + Number(input.sarcoglycan||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_neuro_ext171',function:'LimbGirdleExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['FacioscapHumeralExt']=function(input){const score=Math.round((0.18 + Number(input.fshd||1)*0.2 + Number(input.d4z4||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_neuro_ext171',function:'FacioscapHumeralExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['OculopharyngealExt']=function(input){const score=Math.round((0.18 + Number(input.opmd||1)*0.2 + Number(input.pabpn1||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_neuro_ext171',function:'OculopharyngealExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EmeryDreifussExt']=function(input){const score=Math.round((0.18 + Number(input.edmd||1)*0.2 + Number(input.emerin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_neuro_ext171',function:'EmeryDreifussExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MyotonicDM1Ext']=function(input){const score=Math.round((0.18 + Number(input.dm1Genetic||1)*0.2 + Number(input.ctgRepeat||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_neuro_ext171',function:'MyotonicDM1Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['MyotonicDM2Ext']=function(input){const score=Math.round((0.18 + Number(input.dm2||1)*0.2 + Number(input.cctgRepeat||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_neuro_ext171',function:'MyotonicDM2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['CongenitalMyopathyExt']=function(input){const score=Math.round((0.18 + Number(input.congenMyop||1)*0.2 + Number(input.centralCore||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_neuro_ext171',function:'CongenitalMyopathyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MitochondrialMyopExt']=function(input){const score=Math.round((0.18 + Number(input.mitoMyop||1)*0.2 + Number(input.mtdna||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_neuro_ext171',function:'MitochondrialMyopExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PompeDiseaseExt']=function(input){const score=Math.round((0.18 + Number(input.pompe||1)*0.2 + Number(input.gaa||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_neuro_ext171',function:'PompeDiseaseExt',input,score,ts:new Date().toISOString()}};

// TS: v3.12.12.0
