-- anes_102 reverse
BEGIN;
DROP TABLE IF EXISTS anes_102_results CASCADE;
DROP TABLE IF EXISTS anes_102_orders  CASCADE;
DROP TABLE IF EXISTS anes_102_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ANES_102_up';
COMMIT;
