// Auto-generated by gen_p3master.py -- PCC 3.285.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.285.0';

function X278AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x278) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_278', function: 'X278AssessmentExt', input, score, ts: TS };
}

function X278ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x278) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_278', function: 'X278ScoreExt', input, score, ts: TS };
}

function X278StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x278) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_278', function: 'X278StageExt', input, score, ts: TS };
}

function X278PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x278) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_278', function: 'X278PlanExt', input, score, ts: TS };
}

function X278RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x278) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_278', function: 'X278RiskExt', input, score, ts: TS };
}

function X278DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x278) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_278', function: 'X278DoseExt', input, score, ts: TS };
}

function X278FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x278) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_278', function: 'X278FrequencyExt', input, score, ts: TS };
}

function X278DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x278) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_278', function: 'X278DurationExt', input, score, ts: TS };
}

function X278FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x278) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_278', function: 'X278FollowupExt', input, score, ts: TS };
}

function X278OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x278) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_278', function: 'X278OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X278AssessmentExt,
  X278ScoreExt,
  X278StageExt,
  X278PlanExt,
  X278RiskExt,
  X278DoseExt,
  X278FrequencyExt,
  X278DurationExt,
  X278FollowupExt,
  X278OutcomeExt,
};