// Auto-generated by gen_p3master.py -- PCC 3.287.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.287.0';

function X283AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x283) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_283', function: 'X283AssessmentExt', input, score, ts: TS };
}

function X283ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x283) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_283', function: 'X283ScoreExt', input, score, ts: TS };
}

function X283StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x283) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_283', function: 'X283StageExt', input, score, ts: TS };
}

function X283PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x283) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_283', function: 'X283PlanExt', input, score, ts: TS };
}

function X283RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x283) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_283', function: 'X283RiskExt', input, score, ts: TS };
}

function X283DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x283) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_283', function: 'X283DoseExt', input, score, ts: TS };
}

function X283FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x283) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_283', function: 'X283FrequencyExt', input, score, ts: TS };
}

function X283DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x283) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_283', function: 'X283DurationExt', input, score, ts: TS };
}

function X283FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x283) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_283', function: 'X283FollowupExt', input, score, ts: TS };
}

function X283OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x283) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_283', function: 'X283OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X283AssessmentExt,
  X283ScoreExt,
  X283StageExt,
  X283PlanExt,
  X283RiskExt,
  X283DoseExt,
  X283FrequencyExt,
  X283DurationExt,
  X283FollowupExt,
  X283OutcomeExt,
};