// filepath: pcc/pcc_biostatistics_ext102/pcc_biostatistics_ext102_engine.js
module.exports.version='v3.46.46.0';
module.exports.module='pcc_biostatistics_ext102';
module.exports.functions={};
module.exports.functions['BioDescExt']=function(input){const score=Math.round((0.18 + Number(input.bsDesc||1)*0.2 + Number(input.bsDescType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.46.46.0',module:'pcc_biostatistics_ext102',function:'BioDescExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BioInferExt']=function(input){const score=Math.round((0.18 + Number(input.bsInf||1)*0.2 + Number(input.bsInfType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.46.46.0',module:'pcc_biostatistics_ext102',function:'BioInferExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BioRegressionExt']=function(input){const score=Math.round((0.18 + Number(input.bsReg||1)*0.2 + Number(input.bsRegType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.46.46.0',module:'pcc_biostatistics_ext102',function:'BioRegressionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BioSurvivalExt']=function(input){const score=Math.round((0.18 + Number(input.bsSurv||1)*0.2 + Number(input.bsSurvType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.46.46.0',module:'pcc_biostatistics_ext102',function:'BioSurvivalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BioBayesExt']=function(input){const score=Math.round((0.18 + Number(input.bsBayes||1)*0.2 + Number(input.bsBayesPrior||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.46.46.0',module:'pcc_biostatistics_ext102',function:'BioBayesExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BioSampleSizeExt']=function(input){const score=Math.round((0.18 + Number(input.bsSample||1)*0.2 + Number(input.bsSampleSize||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.46.46.0',module:'pcc_biostatistics_ext102',function:'BioSampleSizeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BioPowerExt']=function(input){const score=Math.round((0.18 + Number(input.bsPower||1)*0.2 + Number(input.bsPowerVal||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.46.46.0',module:'pcc_biostatistics_ext102',function:'BioPowerExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BioMissingDataExt']=function(input){const score=Math.round((0.18 + Number(input.bsMiss||1)*0.2 + Number(input.bsMissType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.46.46.0',module:'pcc_biostatistics_ext102',function:'BioMissingDataExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BioMetaExt']=function(input){const score=Math.round((0.18 + Number(input.bsMeta||1)*0.2 + Number(input.bsMetaType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.46.46.0',module:'pcc_biostatistics_ext102',function:'BioMetaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BioClinicalTrialExt']=function(input){const score=Math.round((0.18 + Number(input.bsCT||1)*0.2 + Number(input.bsCTPhase||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.46.46.0',module:'pcc_biostatistics_ext102',function:'BioClinicalTrialExt',input,score,ts:new Date().toISOString()}};

// TS: v3.46.46.0
