// filepath: pcc/pcc_pediatric_neuro_ext100/pcc_pediatric_neuro_ext100_engine.js
// pcc_pediatric_neuro_ext100 engine (deterministic)
module.exports.version='v3.210.0';
module.exports.module='pcc_pediatric_neuro_ext100';
module.exports.functions={};
module.exports.functions['PediatricEpilepsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.seizure||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_neuro_ext100',function:'PediatricEpilepsyExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricFocalExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.mri||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_neuro_ext100',function:'PediatricFocalExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricGeneralizedExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.eeg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_neuro_ext100',function:'PediatricGeneralizedExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricStatusExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.duration||10)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_neuro_ext100',function:'PediatricStatusExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricRefractoryExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.drugs||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_neuro_ext100',function:'PediatricRefractoryExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricEpilepsySxExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.resection||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_neuro_ext100',function:'PediatricEpilepsySxExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricTemporalExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.mri||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_neuro_ext100',function:'PediatricTemporalExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricFrontalExt']=function(input){const score=Math.round((0.18 + Number(input.age||7)*0.04 + Number(input.eeg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_neuro_ext100',function:'PediatricFrontalExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricMyoclonicExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.myoclonic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_neuro_ext100',function:'PediatricMyoclonicExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricAbsenceExt']=function(input){const score=Math.round((0.18 + Number(input.age||6)*0.04 + Number(input.eeg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.210.0',module:'pcc_pediatric_neuro_ext100',function:'PediatricAbsenceExt',input,score,ts:new Date().toISOString()};};

// TS: v3.210.0
