// Auto-generated by gen_p3master.py -- PCC 3.300.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.300.0';

function X323AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x323) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_323', function: 'X323AssessmentExt', input, score, ts: TS };
}

function X323ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x323) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_323', function: 'X323ScoreExt', input, score, ts: TS };
}

function X323StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x323) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_323', function: 'X323StageExt', input, score, ts: TS };
}

function X323PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x323) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_323', function: 'X323PlanExt', input, score, ts: TS };
}

function X323RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x323) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_323', function: 'X323RiskExt', input, score, ts: TS };
}

function X323DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x323) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_323', function: 'X323DoseExt', input, score, ts: TS };
}

function X323FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x323) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_323', function: 'X323FrequencyExt', input, score, ts: TS };
}

function X323DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x323) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_323', function: 'X323DurationExt', input, score, ts: TS };
}

function X323FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x323) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_323', function: 'X323FollowupExt', input, score, ts: TS };
}

function X323OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x323) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_323', function: 'X323OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X323AssessmentExt,
  X323ScoreExt,
  X323StageExt,
  X323PlanExt,
  X323RiskExt,
  X323DoseExt,
  X323FrequencyExt,
  X323DurationExt,
  X323FollowupExt,
  X323OutcomeExt,
};