-- onc_103 reverse
BEGIN;
DROP TABLE IF EXISTS onc_103_results CASCADE;
DROP TABLE IF EXISTS onc_103_orders  CASCADE;
DROP TABLE IF EXISTS onc_103_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ONC_103_up';
COMMIT;
