// filepath: pcc/pcc_pediatric_surg_ext160/pcc_pediatric_surg_ext160_engine.js
module.exports.version='v3.12.12.0';
module.exports.module='pcc_pediatric_surg_ext160';
module.exports.functions={};
module.exports.functions['PediatricDMDsteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.dmdSteroid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_surg_ext160',function:'PediatricDMDsteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBMDsteroidExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.bmdSteroid2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_surg_ext160',function:'PediatricBMDsteroidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLGMDsupportExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.lgmdSupport||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_surg_ext160',function:'PediatricLGMDsupportExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFSHDtxExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.fshdTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_surg_ext160',function:'PediatricFSHDtxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOPMDdysphagiaExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.opmdDysph||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_surg_ext160',function:'PediatricOPMDdysphagiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEDMDcardiacExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.edmdCardiac||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_surg_ext160',function:'PediatricEDMDcardiacExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDM1monitorExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.dm1Monitor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_surg_ext160',function:'PediatricDM1monitorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCongMyopTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.congMyopTx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_surg_ext160',function:'PediatricCongMyopTxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMitoMyopSuppExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.mitoSupp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_surg_ext160',function:'PediatricMitoMyopSuppExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPompeERTxExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pompeERT||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.12.12.0',module:'pcc_pediatric_surg_ext160',function:'PediatricPompeERTxExt',input,score,ts:new Date().toISOString()}};

// TS: v3.12.12.0
