// filepath: pcc/pcc_pediatric_neuro_ext131/pcc_pediatric_neuro_ext131_engine.js
module.exports.version='v3.241.0';
module.exports.module='pcc_pediatric_neuro_ext131';
module.exports.functions={};
module.exports.functions['PediatricB12DeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.b12||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_neuro_ext131',function:'PediatricB12DeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricFolateDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.folate||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_neuro_ext131',function:'PediatricFolateDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricThiamineDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.thiamine||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_neuro_ext131',function:'PediatricThiamineDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNiacinDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.niacin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_neuro_ext131',function:'PediatricNiacinDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricB6DeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.b6||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_neuro_ext131',function:'PediatricB6DeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVitDDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.vitD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_neuro_ext131',function:'PediatricVitDDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVitEDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.vitE||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_neuro_ext131',function:'PediatricVitEDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCopperDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.copper||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_neuro_ext131',function:'PediatricCopperDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricZincDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.zinc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_neuro_ext131',function:'PediatricZincDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSeleniumDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.selenium||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_pediatric_neuro_ext131',function:'PediatricSeleniumDeficiencyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.241.0
