-- adm_107 reverse
BEGIN;
DROP TABLE IF EXISTS adm_107_results CASCADE;
DROP TABLE IF EXISTS adm_107_orders  CASCADE;
DROP TABLE IF EXISTS adm_107_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ADM_107_up';
COMMIT;
