-- icu_102 reverse
BEGIN;
DROP TABLE IF EXISTS icu_102_results CASCADE;
DROP TABLE IF EXISTS icu_102_orders  CASCADE;
DROP TABLE IF EXISTS icu_102_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ICU_102_up';
COMMIT;
