// filepath: pcc/pcc_pediatric_neuro_ext129/pcc_pediatric_neuro_ext129_engine.js
module.exports.version='v3.239.0';
module.exports.module='pcc_pediatric_neuro_ext129';
module.exports.functions={};
module.exports.functions['PediatricPostOpStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.postOp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_pediatric_neuro_ext129',function:'PediatricPostOpStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCardiacSxStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.cardiac||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_pediatric_neuro_ext129',function:'PediatricCardiacSxStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCEAstrokeExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cea||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_pediatric_neuro_ext129',function:'PediatricCEAstrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDeliriumExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.delirium||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_pediatric_neuro_ext129',function:'PediatricDeliriumExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCogDysExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cogDys||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_pediatric_neuro_ext129',function:'PediatricCogDysExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAnesthToxExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.anesthTox||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_pediatric_neuro_ext129',function:'PediatricAnesthToxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPropofolExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.propofol||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_pediatric_neuro_ext129',function:'PediatricPropofolExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLocalAnesthExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.localAnesth||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_pediatric_neuro_ext129',function:'PediatricLocalAnesthExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMalignHypExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.malignHyp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_pediatric_neuro_ext129',function:'PediatricMalignHypExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSerotoninExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.serotonin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_pediatric_neuro_ext129',function:'PediatricSerotoninExt',input,score,ts:new Date().toISOString()}};

// TS: v3.239.0
