// filepath: pcc/pcc_critical_care_ext102/pcc_critical_care_ext102_engine.js
module.exports.version='v3.72.72.0';
module.exports.module='pcc_critical_care_ext102';
module.exports.functions={};
module.exports.functions['CCGenExt']=function(input){const score=Math.round((0.18 + Number(input.ccGen||1)*0.2 + Number(input.ccGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.72.72.0',module:'pcc_critical_care_ext102',function:'CCGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CCMonitorExt']=function(input){const score=Math.round((0.18 + Number(input.ccMon||1)*0.2 + Number(input.ccMonScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.72.72.0',module:'pcc_critical_care_ext102',function:'CCMonitorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CCShockExt']=function(input){const score=Math.round((0.18 + Number(input.ccShk||1)*0.2 + Number(input.ccShkType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.72.72.0',module:'pcc_critical_care_ext102',function:'CCShockExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CCAirwayExt']=function(input){const score=Math.round((0.18 + Number(input.ccAw||1)*0.2 + Number(input.ccAwScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.72.72.0',module:'pcc_critical_care_ext102',function:'CCAirwayExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CCBreathExt']=function(input){const score=Math.round((0.18 + Number(input.ccBr||1)*0.2 + Number(input.ccBrScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.72.72.0',module:'pcc_critical_care_ext102',function:'CCBreathExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CCCirculExt']=function(input){const score=Math.round((0.18 + Number(input.ccCir||1)*0.2 + Number(input.ccCirScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.72.72.0',module:'pcc_critical_care_ext102',function:'CCCirculExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CCDisabilityExt']=function(input){const score=Math.round((0.18 + Number(input.ccDis||1)*0.2 + Number(input.ccDisScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.72.72.0',module:'pcc_critical_care_ext102',function:'CCDisabilityExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CCExposureExt']=function(input){const score=Math.round((0.18 + Number(input.ccExp||1)*0.2 + Number(input.ccExpScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.72.72.0',module:'pcc_critical_care_ext102',function:'CCExposureExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CCFamilyExt']=function(input){const score=Math.round((0.18 + Number(input.ccFam||1)*0.2 + Number(input.ccFamScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.72.72.0',module:'pcc_critical_care_ext102',function:'CCFamilyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CCTriageExt']=function(input){const score=Math.round((0.18 + Number(input.ccTr||1)*0.2 + Number(input.ccTrScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.72.72.0',module:'pcc_critical_care_ext102',function:'CCTriageExt',input,score,ts:new Date().toISOString()}};

// TS: v3.72.72.0
