// filepath: pcc/pcc_tropical_ext100/pcc_tropical_ext100_engine.js
module.exports.version='v3.21.21.0';
module.exports.module='pcc_tropical_ext100';
module.exports.functions={};
module.exports.functions['TropMalariaExt']=function(input){const score=Math.round((0.18 + Number(input.tropMalaria||1)*0.2 + Number(input.parasitemia||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_tropical_ext100',function:'TropMalariaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TropDengueExt']=function(input){const score=Math.round((0.18 + Number(input.tropDengue||1)*0.2 + Number(input.dengueAg||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_tropical_ext100',function:'TropDengueExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TropTyphoidExt']=function(input){const score=Math.round((0.18 + Number(input.tropTyphoid||1)*0.2 + Number(input.bloodCulture||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_tropical_ext100',function:'TropTyphoidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TropCholeraExt']=function(input){const score=Math.round((0.18 + Number(input.tropCholera||1)*0.2 + Number(input.stoolRdt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_tropical_ext100',function:'TropCholeraExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TropSchistoExt']=function(input){const score=Math.round((0.18 + Number(input.tropSchisto||1)*0.2 + Number(input.eggCount||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_tropical_ext100',function:'TropSchistoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TropLeishmaniaExt']=function(input){const score=Math.round((0.18 + Number(input.tropLeish||1)*0.2 + Number(input.amastigote||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_tropical_ext100',function:'TropLeishmaniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TropFilariaExt']=function(input){const score=Math.round((0.18 + Number(input.tropFilaria||1)*0.2 + Number(input.mfCount||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_tropical_ext100',function:'TropFilariaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TropAmoebiasisExt']=function(input){const score=Math.round((0.18 + Number(input.tropAmeb||1)*0.2 + Number(input.amoebaSer||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_tropical_ext100',function:'TropAmoebiasisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TropRabiesExt']=function(input){const score=Math.round((0.18 + Number(input.tropRabies||1)*0.2 + Number(input.rabiesAb||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_tropical_ext100',function:'TropRabiesExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TropBrucellosisExt']=function(input){const score=Math.round((0.18 + Number(input.tropBruc||1)*0.2 + Number(input.brucellaTiter||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.21.21.0',module:'pcc_tropical_ext100',function:'TropBrucellosisExt',input,score,ts:new Date().toISOString()}};

// TS: v3.21.21.0
