// Auto-generated by gen_p3hf.py -- PCC v3.174.0
"use strict";
const TS = '2026-07-28T13:10:00Z';

function PediatricMyastheniaGravisExt(input) { const score = Math.round((0.3+Number(input.adl_score||4)*0.07)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_neuro_ext64', function:'PediatricMyastheniaGravisExt', input, score, ts: TS }; }

function PediatricLambertEatonExt(input) { const score = Math.round((0.4+Number(input.cmamp||1)*0.15)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_neuro_ext64', function:'PediatricLambertEatonExt', input, score, ts: TS }; }

function PediatricMyasthenicCrisisExt(input) { const score = Math.round((0.5+Number(input.vital||20)*0.015)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_neuro_ext64', function:'PediatricMyasthenicCrisisExt', input, score, ts: TS }; }

function PediatricCholinergicCrisisExt(input) { const score = Math.round((0.5+Number(input.symptoms||2)*0.1)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_neuro_ext64', function:'PediatricCholinergicCrisisExt', input, score, ts: TS }; }

function PediatricOcularMGExt(input) { const score = Math.round((0.3+Number(input.ocular_score||2)*0.1)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_neuro_ext64', function:'PediatricOcularMGExt', input, score, ts: TS }; }

function PediatricThymomaExt(input) { const score = Math.round((0.4+Number(input.thymus_size||2)*0.1)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_neuro_ext64', function:'PediatricThymomaExt', input, score, ts: TS }; }

function PediatricMUSKAntibodyExt(input) { const score = Math.round((0.4+Number(input.musk_titer||0)*0.001)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_neuro_ext64', function:'PediatricMUSKAntibodyExt', input, score, ts: TS }; }

function PediatricLRP4Ext(input) { const score = Math.round((0.4+Number(input.lrp4_titer||0)*0.001)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_neuro_ext64', function:'PediatricLRP4Ext', input, score, ts: TS }; }

function PediatricSeronegativeMGExt(input) { const score = Math.round((0.4+Number(input.achr_pct||0)*0.01)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_neuro_ext64', function:'PediatricSeronegativeMGExt', input, score, ts: TS }; }

function PediatricMGQOLExt(input) { const score = Math.round((0.3+Number(input.qol_score||10)*0.05)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_neuro_ext64', function:'PediatricMGQOLExt', input, score, ts: TS }; }

module.exports = {
  PediatricMyastheniaGravisExt,
  PediatricLambertEatonExt,
  PediatricMyasthenicCrisisExt,
  PediatricCholinergicCrisisExt,
  PediatricOcularMGExt,
  PediatricThymomaExt,
  PediatricMUSKAntibodyExt,
  PediatricLRP4Ext,
  PediatricSeronegativeMGExt,
  PediatricMGQOLExt,
};