// filepath: pcc/pcc_pediatric_neuro_ext180/pcc_pediatric_neuro_ext180_engine.js
module.exports.version='v3.20.20.0';
module.exports.module='pcc_pediatric_neuro_ext180';
module.exports.functions={};
module.exports.functions['PediatricStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStroke||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_neuro_ext180',function:'PediatricStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeArterialExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeArt||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_neuro_ext180',function:'PediatricStrokeArterialExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeSinusExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pStrokeSinus||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_neuro_ext180',function:'PediatricStrokeSinusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokePerinatalExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pStrokePeri||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_neuro_ext180',function:'PediatricStrokePerinatalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeSickleExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeSickle||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_neuro_ext180',function:'PediatricStrokeSickleExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeMoyaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pStrokeMoya||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_neuro_ext180',function:'PediatricStrokeMoyaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeCADExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pStrokeCAD||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_neuro_ext180',function:'PediatricStrokeCADExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeRehabExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeRehab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_neuro_ext180',function:'PediatricStrokeRehabExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStrokeFollowExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pStrokeFollow||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_neuro_ext180',function:'PediatricStrokeFollowExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTIAext']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTIA||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.20.20.0',module:'pcc_pediatric_neuro_ext180',function:'PediatricTIAext',input,score,ts:new Date().toISOString()}};

// TS: v3.20.20.0
