// filepath: pcc/pcc_pediatric_neuro_ext111/pcc_pediatric_neuro_ext111_engine.js
module.exports.version='v3.221.0';
module.exports.module='pcc_pediatric_neuro_ext111';
module.exports.functions={};
module.exports.functions['PediatricMeningiomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.meningioma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_neuro_ext111',function:'PediatricMeningiomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWHO1Ext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.size||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_neuro_ext111',function:'PediatricWHO1Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWHO2Ext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.atypical||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_neuro_ext111',function:'PediatricWHO2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWHO3Ext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.anaplastic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_neuro_ext111',function:'PediatricWHO3Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCavernousSinusExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.cavernous||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_neuro_ext111',function:'PediatricCavernousSinusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOlfactoryExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.anosmia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_neuro_ext111',function:'PediatricOlfactoryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricParasagittalExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.sagittal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_neuro_ext111',function:'PediatricParasagittalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricConvexityExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.convexity||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_neuro_ext111',function:'PediatricConvexityExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSphenoidExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.sphenoid||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_neuro_ext111',function:'PediatricSphenoidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPosteriorFossaExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.posteriorFossa||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.221.0',module:'pcc_pediatric_neuro_ext111',function:'PediatricPosteriorFossaExt',input,score,ts:new Date().toISOString()}};

// TS: v3.221.0
