// filepath: pcc/pcc_rehabilitation_ext102/pcc_rehabilitation_ext102_engine.js
module.exports.version='v3.48.48.0';
module.exports.module='pcc_rehabilitation_ext102';
module.exports.functions={};
module.exports.functions['RehabGeneralExt']=function(input){const score=Math.round((0.18 + Number(input.rhGen||1)*0.2 + Number(input.rhGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_rehabilitation_ext102',function:'RehabGeneralExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RehabPTExt']=function(input){const score=Math.round((0.18 + Number(input.rhPT||1)*0.2 + Number(input.rhPTSessions||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_rehabilitation_ext102',function:'RehabPTExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RehabOTExt']=function(input){const score=Math.round((0.18 + Number(input.rhOT||1)*0.2 + Number(input.rhOTSessions||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_rehabilitation_ext102',function:'RehabOTExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RehabSTExt']=function(input){const score=Math.round((0.18 + Number(input.rhST||1)*0.2 + Number(input.rhSTSessions||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_rehabilitation_ext102',function:'RehabSTExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RehabCardiacExt']=function(input){const score=Math.round((0.18 + Number(input.rhCard||1)*0.2 + Number(input.rhCardMETS||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_rehabilitation_ext102',function:'RehabCardiacExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RehabPulmonaryExt']=function(input){const score=Math.round((0.18 + Number(input.rhPulm||1)*0.2 + Number(input.rhPulmScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_rehabilitation_ext102',function:'RehabPulmonaryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RehabNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.rhNeuro||1)*0.2 + Number(input.rhNeuroScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_rehabilitation_ext102',function:'RehabNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RehabOrthoExt']=function(input){const score=Math.round((0.18 + Number(input.rhOrtho||1)*0.2 + Number(input.rhOrthoType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_rehabilitation_ext102',function:'RehabOrthoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RehabProsthExt']=function(input){const score=Math.round((0.18 + Number(input.rhPros||1)*0.2 + Number(input.rhProsType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_rehabilitation_ext102',function:'RehabProsthExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RehabDischargeExt']=function(input){const score=Math.round((0.18 + Number(input.rhDisch||1)*0.2 + Number(input.rhDischScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.48.48.0',module:'pcc_rehabilitation_ext102',function:'RehabDischargeExt',input,score,ts:new Date().toISOString()}};

// TS: v3.48.48.0
