// Auto-generated by gen_p3master.py -- PCC 3.279.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.279.0';

function X261AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x261) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_261', function: 'X261AssessmentExt', input, score, ts: TS };
}

function X261ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x261) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_261', function: 'X261ScoreExt', input, score, ts: TS };
}

function X261StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x261) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_261', function: 'X261StageExt', input, score, ts: TS };
}

function X261PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x261) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_261', function: 'X261PlanExt', input, score, ts: TS };
}

function X261RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x261) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_261', function: 'X261RiskExt', input, score, ts: TS };
}

function X261DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x261) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_261', function: 'X261DoseExt', input, score, ts: TS };
}

function X261FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x261) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_261', function: 'X261FrequencyExt', input, score, ts: TS };
}

function X261DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x261) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_261', function: 'X261DurationExt', input, score, ts: TS };
}

function X261FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x261) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_261', function: 'X261FollowupExt', input, score, ts: TS };
}

function X261OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x261) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_261', function: 'X261OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X261AssessmentExt,
  X261ScoreExt,
  X261StageExt,
  X261PlanExt,
  X261RiskExt,
  X261DoseExt,
  X261FrequencyExt,
  X261DurationExt,
  X261FollowupExt,
  X261OutcomeExt,
};