// filepath: pcc/pcc_pediatric_neuro_ext152/pcc_pediatric_neuro_ext152_engine.js
module.exports.version='v3.262.0';
module.exports.module='pcc_pediatric_neuro_ext152';
module.exports.functions={};
module.exports.functions['PediatricDementiaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pDem||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.262.0',module:'pcc_pediatric_neuro_ext152',function:'PediatricDementiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNCLext']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.ncl||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.262.0',module:'pcc_pediatric_neuro_ext152',function:'PediatricNCLext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTaySachsExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.taysachs||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.262.0',module:'pcc_pediatric_neuro_ext152',function:'PediatricTaySachsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNiemannPickExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.niemann||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.262.0',module:'pcc_pediatric_neuro_ext152',function:'PediatricNiemannPickExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGaucherExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.gaucher||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.262.0',module:'pcc_pediatric_neuro_ext152',function:'PediatricGaucherExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPKUExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pku||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.262.0',module:'pcc_pediatric_neuro_ext152',function:'PediatricPKUExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricWilsonExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.wilson||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.262.0',module:'pcc_pediatric_neuro_ext152',function:'PediatricWilsonExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMenkesExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.menkes||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.262.0',module:'pcc_pediatric_neuro_ext152',function:'PediatricMenkesExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHurlerExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.hurler||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.262.0',module:'pcc_pediatric_neuro_ext152',function:'PediatricHurlerExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSanfilippoExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.sanfilippo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.262.0',module:'pcc_pediatric_neuro_ext152',function:'PediatricSanfilippoExt',input,score,ts:new Date().toISOString()}};

// TS: v3.262.0
