-- fct_101 reverse
BEGIN;
DROP TABLE IF EXISTS fct_101_results CASCADE;
DROP TABLE IF EXISTS fct_101_orders  CASCADE;
DROP TABLE IF EXISTS fct_101_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_FCT_101_up';
COMMIT;
