// Auto-generated by gen_p3master.py -- PCC 3.189.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.189.0';

function VSAssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.vsas) || 0) * 0.15) * 100) / 100;
  return { version: VER, module: 'pcc_valve_surgery', function: 'VSAssessmentExt', input, score, ts: TS };
}

function VSScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.vssc) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_valve_surgery', function: 'VSScoreExt', input, score, ts: TS };
}

function VSStageExt(input) {
  const score = Math.round((0.3 + (Number(input.vsst) || 0) * 0.27) * 100) / 100;
  return { version: VER, module: 'pcc_valve_surgery', function: 'VSStageExt', input, score, ts: TS };
}

function VSPlanExt(input) {
  const score = Math.round((0.3 + (Number(input.vspl) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_valve_surgery', function: 'VSPlanExt', input, score, ts: TS };
}

function VSRiskExt(input) {
  const score = Math.round((0.3 + (Number(input.vsri) || 0) * 0.24) * 100) / 100;
  return { version: VER, module: 'pcc_valve_surgery', function: 'VSRiskExt', input, score, ts: TS };
}

function VSDoseExt(input) {
  const score = Math.round((0.3 + (Number(input.vsdo) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_valve_surgery', function: 'VSDoseExt', input, score, ts: TS };
}

function VSFrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.vsfr) || 0) * 0.16) * 100) / 100;
  return { version: VER, module: 'pcc_valve_surgery', function: 'VSFrequencyExt', input, score, ts: TS };
}

function VSDurationExt(input) {
  const score = Math.round((0.3 + (Number(input.vsdu) || 0) * 0.47) * 100) / 100;
  return { version: VER, module: 'pcc_valve_surgery', function: 'VSDurationExt', input, score, ts: TS };
}

function VSFollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.vsfo) || 0) * 0.48) * 100) / 100;
  return { version: VER, module: 'pcc_valve_surgery', function: 'VSFollowupExt', input, score, ts: TS };
}

function VSOutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.vsou) || 0) * 0.44) * 100) / 100;
  return { version: VER, module: 'pcc_valve_surgery', function: 'VSOutcomeExt', input, score, ts: TS };
}

module.exports = {
  VSAssessmentExt,
  VSScoreExt,
  VSStageExt,
  VSPlanExt,
  VSRiskExt,
  VSDoseExt,
  VSFrequencyExt,
  VSDurationExt,
  VSFollowupExt,
  VSOutcomeExt,
};