// Auto-generated by gen_p3master.py -- PCC 3.302.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.302.0';

function X330AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x330) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_330', function: 'X330AssessmentExt', input, score, ts: TS };
}

function X330ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x330) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_330', function: 'X330ScoreExt', input, score, ts: TS };
}

function X330StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x330) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_330', function: 'X330StageExt', input, score, ts: TS };
}

function X330PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x330) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_330', function: 'X330PlanExt', input, score, ts: TS };
}

function X330RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x330) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_330', function: 'X330RiskExt', input, score, ts: TS };
}

function X330DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x330) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_330', function: 'X330DoseExt', input, score, ts: TS };
}

function X330FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x330) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_330', function: 'X330FrequencyExt', input, score, ts: TS };
}

function X330DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x330) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_330', function: 'X330DurationExt', input, score, ts: TS };
}

function X330FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x330) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_330', function: 'X330FollowupExt', input, score, ts: TS };
}

function X330OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x330) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_330', function: 'X330OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X330AssessmentExt,
  X330ScoreExt,
  X330StageExt,
  X330PlanExt,
  X330RiskExt,
  X330DoseExt,
  X330FrequencyExt,
  X330DurationExt,
  X330FollowupExt,
  X330OutcomeExt,
};