// Auto-generated by gen_p3master.py -- PCC 3.290.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.290.0';

function X294AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x294) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_294', function: 'X294AssessmentExt', input, score, ts: TS };
}

function X294ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x294) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_294', function: 'X294ScoreExt', input, score, ts: TS };
}

function X294StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x294) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_294', function: 'X294StageExt', input, score, ts: TS };
}

function X294PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x294) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_294', function: 'X294PlanExt', input, score, ts: TS };
}

function X294RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x294) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_294', function: 'X294RiskExt', input, score, ts: TS };
}

function X294DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x294) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_294', function: 'X294DoseExt', input, score, ts: TS };
}

function X294FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x294) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_294', function: 'X294FrequencyExt', input, score, ts: TS };
}

function X294DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x294) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_294', function: 'X294DurationExt', input, score, ts: TS };
}

function X294FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x294) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_294', function: 'X294FollowupExt', input, score, ts: TS };
}

function X294OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x294) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_294', function: 'X294OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X294AssessmentExt,
  X294ScoreExt,
  X294StageExt,
  X294PlanExt,
  X294RiskExt,
  X294DoseExt,
  X294FrequencyExt,
  X294DurationExt,
  X294FollowupExt,
  X294OutcomeExt,
};