// Auto-generated by gen_p3master.py -- PCC 3.187.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.187.0';

function PCPAssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.pcpa) || 0) * 0.2) * 100) / 100;
  return { version: VER, module: 'pcc_preventive_cardio', function: 'PCPAssessmentExt', input, score, ts: TS };
}

function PCPScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.pcps) || 0) * 0.31) * 100) / 100;
  return { version: VER, module: 'pcc_preventive_cardio', function: 'PCPScoreExt', input, score, ts: TS };
}

function PCPStageExt(input) {
  const score = Math.round((0.3 + (Number(input.pcps) || 0) * 0.32) * 100) / 100;
  return { version: VER, module: 'pcc_preventive_cardio', function: 'PCPStageExt', input, score, ts: TS };
}

function PCPPlanExt(input) {
  const score = Math.round((0.3 + (Number(input.pcpp) || 0) * 0.28) * 100) / 100;
  return { version: VER, module: 'pcc_preventive_cardio', function: 'PCPPlanExt', input, score, ts: TS };
}

function PCPRiskExt(input) {
  const score = Math.round((0.3 + (Number(input.pcpr) || 0) * 0.29) * 100) / 100;
  return { version: VER, module: 'pcc_preventive_cardio', function: 'PCPRiskExt', input, score, ts: TS };
}

function PCPDoseExt(input) {
  const score = Math.round((0.3 + (Number(input.pcpd) || 0) * 0.3) * 100) / 100;
  return { version: VER, module: 'pcc_preventive_cardio', function: 'PCPDoseExt', input, score, ts: TS };
}

function PCPFrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.pcpf) || 0) * 0.21) * 100) / 100;
  return { version: VER, module: 'pcc_preventive_cardio', function: 'PCPFrequencyExt', input, score, ts: TS };
}

function PCPDurationExt(input) {
  const score = Math.round((0.3 + (Number(input.pcpd) || 0) * 0.17) * 100) / 100;
  return { version: VER, module: 'pcc_preventive_cardio', function: 'PCPDurationExt', input, score, ts: TS };
}

function PCPFollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.pcpf) || 0) * 0.18) * 100) / 100;
  return { version: VER, module: 'pcc_preventive_cardio', function: 'PCPFollowupExt', input, score, ts: TS };
}

function PCPOutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.pcpo) || 0) * 0.49) * 100) / 100;
  return { version: VER, module: 'pcc_preventive_cardio', function: 'PCPOutcomeExt', input, score, ts: TS };
}

module.exports = {
  PCPAssessmentExt,
  PCPScoreExt,
  PCPStageExt,
  PCPPlanExt,
  PCPRiskExt,
  PCPDoseExt,
  PCPFrequencyExt,
  PCPDurationExt,
  PCPFollowupExt,
  PCPOutcomeExt,
};