// filepath: pcc/pcc_neuro_ext143/pcc_neuro_ext143_engine.js
module.exports.version='v3.242.0';
module.exports.module='pcc_neuro_ext143';
module.exports.functions={};
module.exports.functions['SleepWakeDisordersExt']=function(input){const score=Math.round((0.18 + Number(input.sleep||1)*0.2 + Number(input.circadian||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_neuro_ext143',function:'SleepWakeDisordersExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['InsomniaExt']=function(input){const score=Math.round((0.18 + Number(input.onset||3)*0.05 + Number(input.maintenance||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_neuro_ext143',function:'InsomniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HypersomniaExt']=function(input){const score=Math.round((0.18 + Number(input.daytimeSleep||1)*0.2 + Number(input.narcolepsy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_neuro_ext143',function:'HypersomniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NarcolepsyExt']=function(input){const score=Math.round((0.18 + Number(input.cataplexy||1)*0.2 + Number(input.sleepAttack||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_neuro_ext143',function:'NarcolepsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['RestlessLegsExt']=function(input){const score=Math.round((0.18 + Number(input.urge||1)*0.2 + Number(input.evening||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_neuro_ext143',function:'RestlessLegsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SleepApneaExt']=function(input){const score=Math.round((0.18 + Number(input.apnea||1)*0.2 + Number(input.hypopnea||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_neuro_ext143',function:'SleepApneaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PeriodicLegMovementsExt']=function(input){const score=Math.round((0.18 + Number(input.plms||1)*0.2 + Number(input.arousal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_neuro_ext143',function:'PeriodicLegMovementsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['REMBehaviorDisorderExt']=function(input){const score=Math.round((0.18 + Number(input.rem||1)*0.2 + Number(input.behavior||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_neuro_ext143',function:'REMBehaviorDisorderExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CircadianDisordersExt']=function(input){const score=Math.round((0.18 + Number(input.shift||1)*0.2 + Number(input.jetLag||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_neuro_ext143',function:'CircadianDisordersExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ParasomniasExt']=function(input){const score=Math.round((0.18 + Number(input.nightmare||1)*0.2 + Number(input.sleepTerror||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_neuro_ext143',function:'ParasomniasExt',input,score,ts:new Date().toISOString()}};

// TS: v3.242.0
