// Auto-generated by gen_p3gz.py -- PCC v3.168.0
"use strict";
const TS = '2026-07-28T12:10:00Z';

function HeadacheClassificationExt(input) { const score = Math.round((0.3+Number(input.frequency||3)*0.04)*100)/100; return { version:'3.168.0', module:'pcc_neuro_ext69', function:'HeadacheClassificationExt', input, score, ts: TS }; }

function MigraineProphylaxisExt(input) { const score = Math.round((0.4+Number(input.headache_days||10)*0.02)*100)/100; return { version:'3.168.0', module:'pcc_neuro_ext69', function:'MigraineProphylaxisExt', input, score, ts: TS }; }

function ClusterHeadacheExt(input) { const score = Math.round((0.5+Number(input.attacks_per_day||3)*0.08)*100)/100; return { version:'3.168.0', module:'pcc_neuro_ext69', function:'ClusterHeadacheExt', input, score, ts: TS }; }

function TensionHeadacheExt(input) { const score = Math.round((0.25+Number(input.tenderness_score||3)*0.05)*100)/100; return { version:'3.168.0', module:'pcc_neuro_ext69', function:'TensionHeadacheExt', input, score, ts: TS }; }

function TrigeminalNeuralgiaExt(input) { const score = Math.round((0.4+Number(input.paroxysms||10)*0.03)*100)/100; return { version:'3.168.0', module:'pcc_neuro_ext69', function:'TrigeminalNeuralgiaExt', input, score, ts: TS }; }

function MedicationOveruseHeadacheExt(input) { const score = Math.round((0.45+Number(input.days_per_month||15)*0.02)*100)/100; return { version:'3.168.0', module:'pcc_neuro_ext69', function:'MedicationOveruseHeadacheExt', input, score, ts: TS }; }

function ThunderclapHeadacheExt(input) { const score = Math.round((0.5+Number(input.severity_peak||10)*0.04)*100)/100; return { version:'3.168.0', module:'pcc_neuro_ext69', function:'ThunderclapHeadacheExt', input, score, ts: TS }; }

function CervicogenicHeadacheExt(input) { const score = Math.round((0.3+Number(input.cervical_tender||2)*0.08)*100)/100; return { version:'3.168.0', module:'pcc_neuro_ext69', function:'CervicogenicHeadacheExt', input, score, ts: TS }; }

function PostConcussionHeadacheExt(input) { const score = Math.round((0.35+Number(input.pcss_score||20)*0.02)*100)/100; return { version:'3.168.0', module:'pcc_neuro_ext69', function:'PostConcussionHeadacheExt', input, score, ts: TS }; }

function IdiopathicIntracranialHypertensionHeadacheExt(input) { const score = Math.round((0.4+Number(input.opening_pressure||25)*0.012)*100)/100; return { version:'3.168.0', module:'pcc_neuro_ext69', function:'IdiopathicIntracranialHypertensionHeadacheExt', input, score, ts: TS }; }

module.exports = {
  HeadacheClassificationExt,
  MigraineProphylaxisExt,
  ClusterHeadacheExt,
  TensionHeadacheExt,
  TrigeminalNeuralgiaExt,
  MedicationOveruseHeadacheExt,
  ThunderclapHeadacheExt,
  CervicogenicHeadacheExt,
  PostConcussionHeadacheExt,
  IdiopathicIntracranialHypertensionHeadacheExt,
};