// Auto-generated by gen_p3ie.py -- PCC v3.185.0
"use strict";
const TS = '2026-07-28T15:00:00Z';

function SialorrheaManagementExt(input) { const score = Math.round((0.3+Number(input.drool_severity||3)*0.1)*100)/100; return { version:'3.185.0', module:'pcc_neuro_ext86', function:'SialorrheaManagementExt', input, score, ts: TS }; }

function SpasticityOralExt(input) { const score = Math.round((0.3+Number(input.tone_score||3)*0.1)*100)/100; return { version:'3.185.0', module:'pcc_neuro_ext86', function:'SpasticityOralExt', input, score, ts: TS }; }

function DysarthriaAssessmentExt(input) { const score = Math.round((0.3+Number(input.intelligibility||50)*0.01)*100)/100; return { version:'3.185.0', module:'pcc_neuro_ext86', function:'DysarthriaAssessmentExt', input, score, ts: TS }; }

function DysphagiaScreeningExt(input) { const score = Math.round((0.3+Number(input.aspiration_risk||30)*0.012)*100)/100; return { version:'3.185.0', module:'pcc_neuro_ext86', function:'DysphagiaScreeningExt', input, score, ts: TS }; }

function PEGPlacementExt(input) { const score = Math.round((0.35+Number(input.weight_loss_pct||10)*0.03)*100)/100; return { version:'3.185.0', module:'pcc_neuro_ext86', function:'PEGPlacementExt', input, score, ts: TS }; }

function TracheostomyDecannulationExt(input) { const score = Math.round((0.4+Number(input.vent_days||30)*0.005)*100)/100; return { version:'3.185.0', module:'pcc_neuro_ext86', function:'TracheostomyDecannulationExt', input, score, ts: TS }; }

function RespiratoryAssessmentExt(input) { const score = Math.round((0.3+Number(input.fev1_pct||50)*0.01)*100)/100; return { version:'3.185.0', module:'pcc_neuro_ext86', function:'RespiratoryAssessmentExt', input, score, ts: TS }; }

function VentManagementExt(input) { const score = Math.round((0.4+Number(input.vent_hours||12)*0.025)*100)/100; return { version:'3.185.0', module:'pcc_neuro_ext86', function:'VentManagementExt', input, score, ts: TS }; }

function SleepApneaStrokeExt(input) { const score = Math.round((0.4+Number(input.ahi||15)*0.025)*100)/100; return { version:'3.185.0', module:'pcc_neuro_ext86', function:'SleepApneaStrokeExt', input, score, ts: TS }; }

function GIAssessmentNeuroExt(input) { const score = Math.round((0.3+Number(input.feeding_score||30)*0.02)*100)/100; return { version:'3.185.0', module:'pcc_neuro_ext86', function:'GIAssessmentNeuroExt', input, score, ts: TS }; }

module.exports = {
  SialorrheaManagementExt,
  SpasticityOralExt,
  DysarthriaAssessmentExt,
  DysphagiaScreeningExt,
  PEGPlacementExt,
  TracheostomyDecannulationExt,
  RespiratoryAssessmentExt,
  VentManagementExt,
  SleepApneaStrokeExt,
  GIAssessmentNeuroExt,
};