// filepath: pcc/pcc_neuro_ext173/pcc_neuro_ext173_engine.js
module.exports.version='v3.1.2.0';
module.exports.module='pcc_neuro_ext173';
module.exports.functions={};
module.exports.functions['StrokeHemorrhagicExt']=function(input){const score=Math.round((0.18 + Number(input.hemStroke||1)*0.2 + Number(input.hematomaVol||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_neuro_ext173',function:'StrokeHemorrhagicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['Subarachnoid2Ext']=function(input){const score=Math.round((0.18 + Number(input.sah2||1)*0.2 + Number(input.huntHess2||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_neuro_ext173',function:'Subarachnoid2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['CerebralVenous2Ext']=function(input){const score=Math.round((0.18 + Number(input.cvt2||1)*0.2 + Number(input.dDimers||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_neuro_ext173',function:'CerebralVenous2Ext',input,score,ts:new Date().toISOString()}};
module.exports.functions['StrokeCryptoExt']=function(input){const score=Math.round((0.18 + Number(input.cryptoStroke||1)*0.2 + Number(input.pfo2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_neuro_ext173',function:'StrokeCryptoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['StrokeEmbolicExt']=function(input){const score=Math.round((0.18 + Number(input.embolicStroke||1)*0.2 + Number(input.afib||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_neuro_ext173',function:'StrokeEmbolicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['StrokeSmallVesselExt']=function(input){const score=Math.round((0.18 + Number(input.smallVess||1)*0.2 + Number(input.lacune||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_neuro_ext173',function:'StrokeSmallVesselExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['StrokeWatershedExt']=function(input){const score=Math.round((0.18 + Number(input.watershed||1)*0.2 + Number(input.hypotension||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_neuro_ext173',function:'StrokeWatershedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['StrokeRecoveryExt']=function(input){const score=Math.round((0.18 + Number(input.strokeRecov||1)*0.2 + Number(input.northernRankin||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_neuro_ext173',function:'StrokeRecoveryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PostStrokeSeizureExt']=function(input){const score=Math.round((0.18 + Number(input.postStrokeSz||1)*0.2 + Number(input.lateOnset||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_neuro_ext173',function:'PostStrokeSeizureExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PostStrokeHeadacheExt']=function(input){const score=Math.round((0.18 + Number(input.postStrokeH||1)*0.2 + Number(input.thunderclap2||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.2.0',module:'pcc_neuro_ext173',function:'PostStrokeHeadacheExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.2.0
