// Auto_generated by gen_p3gu.py -- PCC v3.163.0
"use strict";
const TS = '2026-07-28T11:20:00Z';

function IdiopathicIntracranialHypertensionExt3(input) { const score = Math.round((0.3+Number(input.opening_pressure||25)/50)*100)/100; return { version:'3.163.0', module:'pcc_neuro_ext64', function:'IdiopathicIntracranialHypertensionExt3', input, score, ts: TS }; }

function VenousSinusStenosisStentingExt(input) { const score = Math.round((0.4+Number(input.gradient_mmHg||8)/30)*100)/100; return { version:'3.163.0', module:'pcc_neuro_ext64', function:"VenousSinusStenosisStentingExt", input, score, ts: TS }; }

function CSFLeakSiteLocalizationExt(input) { const score = Math.round((0.2+Number(input.beta2transferrin||0)*0.6)*100)/100; return { version:'3.163.0', module:'pcc_neuro_ext64', function:"CSFLeakSiteLocalizationExt", input, score, ts: TS }; }

function SpontaneousIntracranialHypotensionExt(input) { const score = Math.round((0.3+Number(input.ortho_headache||1)*0.05)*100)/100; return { version:'3.163.0', module:'pcc_neuro_ext64', function:"SpontaneousIntracranialHypotensionExt", input, score, ts: TS }; }

function ChiariMalformationComplexExt(input) { const score = Math.round((0.4+Number(input.tonsil_mm||6)*0.04)*100)/100; return { version:'3.163.0', module:'pcc_neuro_ext64', function:"ChiariMalformationComplexExt", input, score, ts: TS }; }

function SyringomyeliaMonitoringExt(input) { const score = Math.round((0.3+Number(input.cyst_length_mm||10)*0.02)*100)/100; return { version:'3.163.0', module:'pcc_neuro_ext64', function:"SyringomyeliaMonitoringExt", input, score, ts: TS }; }

function BasilarInvaginationExt(input) { const score = Math.round((0.45+Number(input.basion_mm||5)*0.04)*100)/100; return { version:'3.163.0', module:'pcc_neuro_ext64', function:"BasilarInvaginationExt", input, score, ts: TS }; }

function CraniovertebralJunctionAnomalyExt(input) { const score = Math.round((0.4+Number(input.cvj_angle_deg||140)*0.003)*100)/100; return { version:'3.163.0', module:'pcc_neuro_ext64', function:"CraniovertebralJunctionAnomalyExt", input, score, ts: TS }; }

function CSFFlowDynamicsExt(input) { const score = Math.round((0.35+Number(input.flow_velocity||10)*0.04)*100)/100; return { version:'3.163.0', module:'pcc_neuro_ext64', function:"CSFFlowDynamicsExt", input, score, ts: TS }; }

function EmptySellaSyndromeMonitorExt(input) { const score = Math.round((0.3+Number(input.pituitary_height||2)*0.15)*100)/100; return { version:'3.163.0', module:'pcc_neuro_ext64', function:"EmptySellaSyndromeMonitorExt", input, score, ts: TS }; }

module.exports = {
  IdiopathicIntracranialHypertensionExt3,
  VenousSinusStenosisStentingExt,
  CSFLeakSiteLocalizationExt,
  SpontaneousIntracranialHypotensionExt,
  ChiariMalformationComplexExt,
  SyringomyeliaMonitoringExt,
  BasilarInvaginationExt,
  CraniovertebralJunctionAnomalyExt,
  CSFFlowDynamicsExt,
  EmptySellaSyndromeMonitorExt,
};