// Auto-generated by gen_p3master.py -- PCC 3.294.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.294.0';

function X304AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x304) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_304', function: 'X304AssessmentExt', input, score, ts: TS };
}

function X304ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x304) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_304', function: 'X304ScoreExt', input, score, ts: TS };
}

function X304StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x304) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_304', function: 'X304StageExt', input, score, ts: TS };
}

function X304PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x304) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_304', function: 'X304PlanExt', input, score, ts: TS };
}

function X304RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x304) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_304', function: 'X304RiskExt', input, score, ts: TS };
}

function X304DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x304) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_304', function: 'X304DoseExt', input, score, ts: TS };
}

function X304FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x304) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_304', function: 'X304FrequencyExt', input, score, ts: TS };
}

function X304DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x304) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_304', function: 'X304DurationExt', input, score, ts: TS };
}

function X304FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x304) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_304', function: 'X304FollowupExt', input, score, ts: TS };
}

function X304OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x304) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_304', function: 'X304OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X304AssessmentExt,
  X304ScoreExt,
  X304StageExt,
  X304PlanExt,
  X304RiskExt,
  X304DoseExt,
  X304FrequencyExt,
  X304DurationExt,
  X304FollowupExt,
  X304OutcomeExt,
};