-- int_106 reverse
BEGIN;
DROP TABLE IF EXISTS int_106_results CASCADE;
DROP TABLE IF EXISTS int_106_orders  CASCADE;
DROP TABLE IF EXISTS int_106_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_INT_106_up';
COMMIT;
