// filepath: pcc/pcc_vascularsurg_ext101/pcc_vascularsurg_ext101_engine.js
module.exports.version='v3.33.33.0';
module.exports.module='pcc_vascularsurg_ext101';
module.exports.functions={};
module.exports.functions['VSCarotidExt']=function(input){const score=Math.round((0.18 + Number(input.vsCarotid||1)*0.2 + Number(input.carotidStenVS||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.33.33.0',module:'pcc_vascularsurg_ext101',function:'VSCarotidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VSAorticAneurysmExt']=function(input){const score=Math.round((0.18 + Number(input.vsAAA||1)*0.2 + Number(input.aaaSize||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.33.33.0',module:'pcc_vascularsurg_ext101',function:'VSAorticAneurysmExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VSAorticDissectionExt']=function(input){const score=Math.round((0.18 + Number(input.vsAAD||1)*0.2 + Number(input.aadType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.33.33.0',module:'pcc_vascularsurg_ext101',function:'VSAorticDissectionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VSPADext']=function(input){const score=Math.round((0.18 + Number(input.vsPAD||1)*0.2 + Number(input.padABI||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.33.33.0',module:'pcc_vascularsurg_ext101',function:'VSPADext',input,score,ts:new Date().toISOString()}};
module.exports.functions['VSCLIext']=function(input){const score=Math.round((0.18 + Number(input.vsCLI||1)*0.2 + Number(input.cliStage||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.33.33.0',module:'pcc_vascularsurg_ext101',function:'VSCLIext',input,score,ts:new Date().toISOString()}};
module.exports.functions['VSDVText']=function(input){const score=Math.round((0.18 + Number(input.vsDVT||1)*0.2 + Number(input.dvtLoc||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.33.33.0',module:'pcc_vascularsurg_ext101',function:'VSDVText',input,score,ts:new Date().toISOString()}};
module.exports.functions['VSVaricoseExt']=function(input){const score=Math.round((0.18 + Number(input.vsVaricose||1)*0.2 + Number(input.venousStage||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.33.33.0',module:'pcc_vascularsurg_ext101',function:'VSVaricoseExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VSThrombolysisExt']=function(input){const score=Math.round((0.18 + Number(input.vsThrombo||1)*0.2 + Number(input.thromboType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.33.33.0',module:'pcc_vascularsurg_ext101',function:'VSThrombolysisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VSDialysisAccessExt']=function(input){const score=Math.round((0.18 + Number(input.vsAccess||1)*0.2 + Number(input.accessType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.33.33.0',module:'pcc_vascularsurg_ext101',function:'VSDialysisAccessExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VSTraumaExt']=function(input){const score=Math.round((0.18 + Number(input.vsTrauma||1)*0.2 + Number(input.vascularTrauma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.33.33.0',module:'pcc_vascularsurg_ext101',function:'VSTraumaExt',input,score,ts:new Date().toISOString()}};

// TS: v3.33.33.0
