-- sup_103 reverse
BEGIN;
DROP TABLE IF EXISTS sup_103_results CASCADE;
DROP TABLE IF EXISTS sup_103_orders  CASCADE;
DROP TABLE IF EXISTS sup_103_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_SUP_103_up';
COMMIT;
