// filepath: pcc/pcc_pediatric_neuro_ext101/pcc_pediatric_neuro_ext101_engine.js
module.exports.version='v3.211.0';
module.exports.module='pcc_pediatric_neuro_ext101';
module.exports.functions={};
module.exports.functions['PediatricMigraineExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.frequency||4)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.211.0',module:'pcc_pediatric_neuro_ext101',function:'PediatricMigraineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMigraineAuraExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.aura||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.211.0',module:'pcc_pediatric_neuro_ext101',function:'PediatricMigraineAuraExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChronicMigraineExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.days||15)*0.02 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.211.0',module:'pcc_pediatric_neuro_ext101',function:'PediatricChronicMigraineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricClusterExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.02 + Number(input.attacks||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.211.0',module:'pcc_pediatric_neuro_ext101',function:'PediatricClusterExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTensionExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.tender||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.211.0',module:'pcc_pediatric_neuro_ext101',function:'PediatricTensionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTrigeminalExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.paroxysms||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.211.0',module:'pcc_pediatric_neuro_ext101',function:'PediatricTrigeminalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOccipitalExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.paroxysms||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.211.0',module:'pcc_pediatric_neuro_ext101',function:'PediatricOccipitalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricIIHExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.papilledema||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.211.0',module:'pcc_pediatric_neuro_ext101',function:'PediatricIIHExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricICSExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.02 + Number(input.orthostatic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.211.0',module:'pcc_pediatric_neuro_ext101',function:'PediatricICSExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRCVSExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.vasoconst||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.211.0',module:'pcc_pediatric_neuro_ext101',function:'PediatricRCVSExt',input,score,ts:new Date().toISOString()}};

// TS: v3.211.0
