// filepath: pcc/pcc_pediatric_neuro_ext132/pcc_pediatric_neuro_ext132_engine.js
module.exports.version='v3.242.0';
module.exports.module='pcc_pediatric_neuro_ext132';
module.exports.functions={};
module.exports.functions['PediatricSleepExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.sleep||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_pediatric_neuro_ext132',function:'PediatricSleepExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricInsomniaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.insomnia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_pediatric_neuro_ext132',function:'PediatricInsomniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHypersomniaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.hypersomnia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_pediatric_neuro_ext132',function:'PediatricHypersomniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNarcolepsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.narcolepsy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_pediatric_neuro_ext132',function:'PediatricNarcolepsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRLSExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.rls||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_pediatric_neuro_ext132',function:'PediatricRLSExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSleepApneaExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.sleepApnea||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_pediatric_neuro_ext132',function:'PediatricSleepApneaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPLMSExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.plms||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_pediatric_neuro_ext132',function:'PediatricPLMSExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRBDExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.rbd||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_pediatric_neuro_ext132',function:'PediatricRBDExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCircadianExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.circadian||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_pediatric_neuro_ext132',function:'PediatricCircadianExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricParasomniaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.parasomnia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.242.0',module:'pcc_pediatric_neuro_ext132',function:'PediatricParasomniaExt',input,score,ts:new Date().toISOString()}};

// TS: v3.242.0
