// Auto-generated by gen_p3master.py -- PCC 3.293.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.293.0';

function X302AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x302) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_302', function: 'X302AssessmentExt', input, score, ts: TS };
}

function X302ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x302) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_302', function: 'X302ScoreExt', input, score, ts: TS };
}

function X302StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x302) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_302', function: 'X302StageExt', input, score, ts: TS };
}

function X302PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x302) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_302', function: 'X302PlanExt', input, score, ts: TS };
}

function X302RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x302) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_302', function: 'X302RiskExt', input, score, ts: TS };
}

function X302DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x302) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_302', function: 'X302DoseExt', input, score, ts: TS };
}

function X302FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x302) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_302', function: 'X302FrequencyExt', input, score, ts: TS };
}

function X302DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x302) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_302', function: 'X302DurationExt', input, score, ts: TS };
}

function X302FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x302) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_302', function: 'X302FollowupExt', input, score, ts: TS };
}

function X302OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x302) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_302', function: 'X302OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X302AssessmentExt,
  X302ScoreExt,
  X302StageExt,
  X302PlanExt,
  X302RiskExt,
  X302DoseExt,
  X302FrequencyExt,
  X302DurationExt,
  X302FollowupExt,
  X302OutcomeExt,
};