// filepath: pcc/pcc_pediatric_neuro_ext123/pcc_pediatric_neuro_ext123_engine.js
module.exports.version='v3.233.0';
module.exports.module='pcc_pediatric_neuro_ext123';
module.exports.functions={};
module.exports.functions['PediatricAbuliaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.abulia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_pediatric_neuro_ext123',function:'PediatricAbuliaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCatatoniaExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.catatonia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_pediatric_neuro_ext123',function:'PediatricCatatoniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAkineticMutismExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.mutism||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_pediatric_neuro_ext123',function:'PediatricAkineticMutismExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLockedInExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.lockedIn||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_pediatric_neuro_ext123',function:'PediatricLockedInExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVSext']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.unresponsive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_pediatric_neuro_ext123',function:'PediatricVSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMCSExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.command||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_pediatric_neuro_ext123',function:'PediatricMCSExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainDeathExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.brainDead||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_pediatric_neuro_ext123',function:'PediatricBrainDeathExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPVSExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pvs||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_pediatric_neuro_ext123',function:'PediatricPVSExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricConsciousnessExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.consciousness||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_pediatric_neuro_ext123',function:'PediatricConsciousnessExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStuporExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.stupor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.233.0',module:'pcc_pediatric_neuro_ext123',function:'PediatricStuporExt',input,score,ts:new Date().toISOString()}};

// TS: v3.233.0
