// Auto-generated by gen_p3master.py -- PCC 3.276.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.276.0';

function X251AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x251) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_251', function: 'X251AssessmentExt', input, score, ts: TS };
}

function X251ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x251) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_251', function: 'X251ScoreExt', input, score, ts: TS };
}

function X251StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x251) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_251', function: 'X251StageExt', input, score, ts: TS };
}

function X251PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x251) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_251', function: 'X251PlanExt', input, score, ts: TS };
}

function X251RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x251) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_251', function: 'X251RiskExt', input, score, ts: TS };
}

function X251DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x251) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_251', function: 'X251DoseExt', input, score, ts: TS };
}

function X251FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x251) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_251', function: 'X251FrequencyExt', input, score, ts: TS };
}

function X251DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x251) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_251', function: 'X251DurationExt', input, score, ts: TS };
}

function X251FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x251) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_251', function: 'X251FollowupExt', input, score, ts: TS };
}

function X251OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x251) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_251', function: 'X251OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X251AssessmentExt,
  X251ScoreExt,
  X251StageExt,
  X251PlanExt,
  X251RiskExt,
  X251DoseExt,
  X251FrequencyExt,
  X251DurationExt,
  X251FollowupExt,
  X251OutcomeExt,
};