-- surg_101 reverse
BEGIN;
DROP TABLE IF EXISTS surg_101_results CASCADE;
DROP TABLE IF EXISTS surg_101_orders  CASCADE;
DROP TABLE IF EXISTS surg_101_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_SURG_101_up';
COMMIT;
