// filepath: pcc/pcc_pediatric_neuro_ext150/pcc_pediatric_neuro_ext150_engine.js
module.exports.version='v3.260.0';
module.exports.module='pcc_pediatric_neuro_ext150';
module.exports.functions={};
module.exports.functions['PediatricAtaxiaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pAtaxia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_neuro_ext150',function:'PediatricAtaxiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricChoreaExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pChorea||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_neuro_ext150',function:'PediatricChoreaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDystoniaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pDystonia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_neuro_ext150',function:'PediatricDystoniaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTicExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_neuro_ext150',function:'PediatricTicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMyoclonusExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pMyoclonus||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_neuro_ext150',function:'PediatricMyoclonusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTremorExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTremor||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_neuro_ext150',function:'PediatricTremorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOpsoclonusExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.opsoclonus||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_neuro_ext150',function:'PediatricOpsoclonusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSydenhamExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.sydenham||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_neuro_ext150',function:'PediatricSydenhamExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPANDASext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pandas||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_neuro_ext150',function:'PediatricPANDASext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBenignPalsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.benignPalsy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.260.0',module:'pcc_pediatric_neuro_ext150',function:'PediatricBenignPalsyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.260.0
