// Auto-generated by gen_p3master.py -- PCC 3.188.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.188.0';

function ECMOAssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.ecmo) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_ecmo_advanced', function: 'ECMOAssessmentExt', input, score, ts: TS };
}

function ECMOScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.ecmo) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_ecmo_advanced', function: 'ECMOScoreExt', input, score, ts: TS };
}

function ECMOStageExt(input) {
  const score = Math.round((0.3 + (Number(input.ecmo) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_ecmo_advanced', function: 'ECMOStageExt', input, score, ts: TS };
}

function ECMOPlanExt(input) {
  const score = Math.round((0.3 + (Number(input.ecmo) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_ecmo_advanced', function: 'ECMOPlanExt', input, score, ts: TS };
}

function ECMORiskExt(input) {
  const score = Math.round((0.3 + (Number(input.ecmo) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_ecmo_advanced', function: 'ECMORiskExt', input, score, ts: TS };
}

function ECMODoseExt(input) {
  const score = Math.round((0.3 + (Number(input.ecmo) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_ecmo_advanced', function: 'ECMODoseExt', input, score, ts: TS };
}

function ECMOFrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.ecmo) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_ecmo_advanced', function: 'ECMOFrequencyExt', input, score, ts: TS };
}

function ECMODurationExt(input) {
  const score = Math.round((0.3 + (Number(input.ecmo) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_ecmo_advanced', function: 'ECMODurationExt', input, score, ts: TS };
}

function ECMOFollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.ecmo) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_ecmo_advanced', function: 'ECMOFollowupExt', input, score, ts: TS };
}

function ECMOOutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.ecmo) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_ecmo_advanced', function: 'ECMOOutcomeExt', input, score, ts: TS };
}

module.exports = {
  ECMOAssessmentExt,
  ECMOScoreExt,
  ECMOStageExt,
  ECMOPlanExt,
  ECMORiskExt,
  ECMODoseExt,
  ECMOFrequencyExt,
  ECMODurationExt,
  ECMOFollowupExt,
  ECMOOutcomeExt,
};