// filepath: pcc/pcc_pediatric_neuro_ext151/pcc_pediatric_neuro_ext151_engine.js
module.exports.version='v3.261.0';
module.exports.module='pcc_pediatric_neuro_ext151';
module.exports.functions={};
module.exports.functions['PediatricMSExt']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.04 + Number(input.pMS||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.261.0',module:'pcc_pediatric_neuro_ext151',function:'PediatricMSExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricADEMExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pADEM||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.261.0',module:'pcc_pediatric_neuro_ext151',function:'PediatricADEMExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNMOExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pNMO||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.261.0',module:'pcc_pediatric_neuro_ext151',function:'PediatricNMOExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMOGExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pMOG||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.261.0',module:'pcc_pediatric_neuro_ext151',function:'PediatricMOGExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTMExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTM||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.261.0',module:'pcc_pediatric_neuro_ext151',function:'PediatricTMExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOptNeuritisExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pOptNeur||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.261.0',module:'pcc_pediatric_neuro_ext151',function:'PediatricOptNeuritisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCerebellitisExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cerebellitis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.261.0',module:'pcc_pediatric_neuro_ext151',function:'PediatricCerebellitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricBrainstemExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.brainstemEnceph||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.261.0',module:'pcc_pediatric_neuro_ext151',function:'PediatricBrainstemExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVasculitisExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pVasculitis||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.261.0',module:'pcc_pediatric_neuro_ext151',function:'PediatricVasculitisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLupusNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pLupusNeuro||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.261.0',module:'pcc_pediatric_neuro_ext151',function:'PediatricLupusNeuroExt',input,score,ts:new Date().toISOString()}};

// TS: v3.261.0
