-- rare_104 reverse
BEGIN;
DROP TABLE IF EXISTS rare_104_results CASCADE;
DROP TABLE IF EXISTS rare_104_orders  CASCADE;
DROP TABLE IF EXISTS rare_104_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_RARE_104_up';
COMMIT;
