// filepath: pcc/pcc_general_medicine_ext102/pcc_general_medicine_ext102_engine.js
module.exports.version='v3.77.77.0';
module.exports.module='pcc_general_medicine_ext102';
module.exports.functions={};
module.exports.functions['GMGenExt']=function(input){const score=Math.round((0.18 + Number(input.gmGen||1)*0.2 + Number(input.gmGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.77.77.0',module:'pcc_general_medicine_ext102',function:'GMGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GMVisitExt']=function(input){const score=Math.round((0.18 + Number(input.gmVs||1)*0.2 + Number(input.gmVsType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.77.77.0',module:'pcc_general_medicine_ext102',function:'GMVisitExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GMConsultExt']=function(input){const score=Math.round((0.18 + Number(input.gmCo||1)*0.2 + Number(input.gmCoType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.77.77.0',module:'pcc_general_medicine_ext102',function:'GMConsultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GMScreenExt']=function(input){const score=Math.round((0.18 + Number(input.gmSr||1)*0.2 + Number(input.gmSrType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.77.77.0',module:'pcc_general_medicine_ext102',function:'GMScreenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GMDxExt']=function(input){const score=Math.round((0.18 + Number(input.gmDx||1)*0.2 + Number(input.gmDxScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.77.77.0',module:'pcc_general_medicine_ext102',function:'GMDxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GMTreatExt']=function(input){const score=Math.round((0.18 + Number(input.gmTr||1)*0.2 + Number(input.gmTrType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.77.77.0',module:'pcc_general_medicine_ext102',function:'GMTreatExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GMPreventExt']=function(input){const score=Math.round((0.18 + Number(input.gmPr||1)*0.2 + Number(input.gmPrType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.77.77.0',module:'pcc_general_medicine_ext102',function:'GMPreventExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GMChronicExt']=function(input){const score=Math.round((0.18 + Number(input.gmCh||1)*0.2 + Number(input.gmChScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.77.77.0',module:'pcc_general_medicine_ext102',function:'GMChronicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GMEduExt']=function(input){const score=Math.round((0.18 + Number(input.gmEd||1)*0.2 + Number(input.gmEdType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.77.77.0',module:'pcc_general_medicine_ext102',function:'GMEduExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['GMReferExt']=function(input){const score=Math.round((0.18 + Number(input.gmRf||1)*0.2 + Number(input.gmRfType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.77.77.0',module:'pcc_general_medicine_ext102',function:'GMReferExt',input,score,ts:new Date().toISOString()}};

// TS: v3.77.77.0
