// filepath: pcc/pcc_pediatric_neuro_ext136/pcc_pediatric_neuro_ext136_engine.js
module.exports.version='v3.246.0';
module.exports.module='pcc_pediatric_neuro_ext136';
module.exports.functions={};
module.exports.functions['PediatricTardiveExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.tardive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.246.0',module:'pcc_pediatric_neuro_ext136',function:'PediatricTardiveExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAkathisiaExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.akathisia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.246.0',module:'pcc_pediatric_neuro_ext136',function:'PediatricAkathisiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNMSExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.nms||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.246.0',module:'pcc_pediatric_neuro_ext136',function:'PediatricNMSExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricDrugParkExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.drugPark||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.246.0',module:'pcc_pediatric_neuro_ext136',function:'PediatricDrugParkExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAcuteDystExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.acuteDyst||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.246.0',module:'pcc_pediatric_neuro_ext136',function:'PediatricAcuteDystExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSSRIDysExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.ssriDys||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.246.0',module:'pcc_pediatric_neuro_ext136',function:'PediatricSSRIDysExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSSRINaExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.ssriNa||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.246.0',module:'pcc_pediatric_neuro_ext136',function:'PediatricSSRINaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSSRISynExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.ssriSyn||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.246.0',module:'pcc_pediatric_neuro_ext136',function:'PediatricSSRISynExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAtypAntipsychExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.atyp||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.246.0',module:'pcc_pediatric_neuro_ext136',function:'PediatricAtypAntipsychExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricStimSideExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.stim||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.246.0',module:'pcc_pediatric_neuro_ext136',function:'PediatricStimSideExt',input,score,ts:new Date().toISOString()}};

// TS: v3.246.0
