// filepath: pcc/pcc_pediatric_neuro_ext170/pcc_pediatric_neuro_ext170_engine.js
module.exports.version='v3.1.10.0';
module.exports.module='pcc_pediatric_neuro_ext170';
module.exports.functions={};
module.exports.functions['PediatricNeuroAidsExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pNeuroAids||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.10.0',module:'pcc_pediatric_neuro_ext170',function:'PediatricNeuroAidsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNeuroLymeExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pNeuroLyme||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.10.0',module:'pcc_pediatric_neuro_ext170',function:'PediatricNeuroLymeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCongenitalCMVExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pCMV||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.10.0',module:'pcc_pediatric_neuro_ext170',function:'PediatricCongenitalCMVExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCongenitalHIVExt']=function(input){const score=Math.round((0.18 + Number(input.age||0)*0.04 + Number(input.pHIV||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.10.0',module:'pcc_pediatric_neuro_ext170',function:'PediatricCongenitalHIVExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVZVencephExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.pVZVenceph||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.10.0',module:'pcc_pediatric_neuro_ext170',function:'PediatricVZVencephExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricHSVencephExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pHSVenceph||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.10.0',module:'pcc_pediatric_neuro_ext170',function:'PediatricHSVencephExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricEnterovirusExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pEntero||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.10.0',module:'pcc_pediatric_neuro_ext170',function:'PediatricEnterovirusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMumpsExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pMumps||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.10.0',module:'pcc_pediatric_neuro_ext170',function:'PediatricMumpsExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMeaslesExt']=function(input){const score=Math.round((0.18 + Number(input.age||1)*0.04 + Number(input.pMeasles||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.10.0',module:'pcc_pediatric_neuro_ext170',function:'PediatricMeaslesExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRabiesExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pRabies||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.10.0',module:'pcc_pediatric_neuro_ext170',function:'PediatricRabiesExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.10.0
