// filepath: pcc/pcc_neuro_ext142/pcc_neuro_ext142_engine.js
module.exports.version='v3.241.0';
module.exports.module='pcc_neuro_ext142';
module.exports.functions={};
module.exports.functions['VitaminB12DeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.macrocytic||1)*0.2 + Number(input.neuropathy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_neuro_ext142',function:'VitaminB12DeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['FolicAcidDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.folate||1)*0.2 + Number(input.macrocytic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_neuro_ext142',function:'FolicAcidDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ThiamineDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.thiamine||1)*0.2 + Number(input.beriberi||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_neuro_ext142',function:'ThiamineDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NiacinDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.niacin||1)*0.2 + Number(input.pellagra||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_neuro_ext142',function:'NiacinDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PyridoxineDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.b6||1)*0.2 + Number(input.neuropathy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_neuro_ext142',function:'PyridoxineDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VitaminDExt']=function(input){const score=Math.round((0.18 + Number(input.vitD||1)*0.2 + Number(input.osteomalacia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_neuro_ext142',function:'VitaminDExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['VitaminEExt']=function(input){const score=Math.round((0.18 + Number(input.vitE||1)*0.2 + Number(input.neuropathy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_neuro_ext142',function:'VitaminEExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CopperDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.copper||1)*0.2 + Number(input.myeloneuropathy||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_neuro_ext142',function:'CopperDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ZincDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.zinc||1)*0.2 + Number(input.skin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_neuro_ext142',function:'ZincDeficiencyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SeleniumDeficiencyExt']=function(input){const score=Math.round((0.18 + Number(input.selenium||1)*0.2 + Number(input.keshan||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.241.0',module:'pcc_neuro_ext142',function:'SeleniumDeficiencyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.241.0
