// filepath: pcc/pcc_joint_replacement_ext102/pcc_joint_replacement_ext102_engine.js
module.exports.version='v3.62.62.0';
module.exports.module='pcc_joint_replacement_ext102';
module.exports.functions={};
module.exports.functions['JRGenExt']=function(input){const score=Math.round((0.18 + Number(input.jrGen||1)*0.2 + Number(input.jrGenType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.62.62.0',module:'pcc_joint_replacement_ext102',function:'JRGenExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['JRHipExt']=function(input){const score=Math.round((0.18 + Number(input.jrHip||1)*0.2 + Number(input.jrHipType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.62.62.0',module:'pcc_joint_replacement_ext102',function:'JRHipExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['JRKneeExt']=function(input){const score=Math.round((0.18 + Number(input.jrKnee||1)*0.2 + Number(input.jrKneeType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.62.62.0',module:'pcc_joint_replacement_ext102',function:'JRKneeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['JRShoulderExt']=function(input){const score=Math.round((0.18 + Number(input.jrSh||1)*0.2 + Number(input.jrShType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.62.62.0',module:'pcc_joint_replacement_ext102',function:'JRShoulderExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['JRElbowExt']=function(input){const score=Math.round((0.18 + Number(input.jrElb||1)*0.2 + Number(input.jrElbType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.62.62.0',module:'pcc_joint_replacement_ext102',function:'JRElbowExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['JRAnkleExt']=function(input){const score=Math.round((0.18 + Number(input.jrAnk||1)*0.2 + Number(input.jrAnkType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.62.62.0',module:'pcc_joint_replacement_ext102',function:'JRAnkleExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['JRWristExt']=function(input){const score=Math.round((0.18 + Number(input.jrWri||1)*0.2 + Number(input.jrWriType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.62.62.0',module:'pcc_joint_replacement_ext102',function:'JRWristExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['JRRevisionExt']=function(input){const score=Math.round((0.18 + Number(input.jrRev||1)*0.2 + Number(input.jrRevType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.62.62.0',module:'pcc_joint_replacement_ext102',function:'JRRevisionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['JRRoboticExt']=function(input){const score=Math.round((0.18 + Number(input.jrRob||1)*0.2 + Number(input.jrRobScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.62.62.0',module:'pcc_joint_replacement_ext102',function:'JRRoboticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['JRRehabExt']=function(input){const score=Math.round((0.18 + Number(input.jrReh||1)*0.2 + Number(input.jrRehScore||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.62.62.0',module:'pcc_joint_replacement_ext102',function:'JRRehabExt',input,score,ts:new Date().toISOString()}};

// TS: v3.62.62.0
