// filepath: pcc/pcc_neuro_ext124/pcc_neuro_ext124_engine.js
module.exports.version='v3.223.0';
module.exports.module='pcc_neuro_ext124';
module.exports.functions={};
module.exports.functions['PrimaryCNSLymphomaExt']=function(input){const score=Math.round((0.18 + Number(input.immunocomp||1)*0.2 + Number(input.deep||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_neuro_ext124',function:'PrimaryCNSLymphomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SecondaryCNSLymphomaExt']=function(input){const score=Math.round((0.18 + Number(input.systemic||1)*0.2 + Number(input.brain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_neuro_ext124',function:'SecondaryCNSLymphomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['DLBCLExt']=function(input){const score=Math.round((0.18 + Number(input.dlbcl||1)*0.2 + Number(input.brain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_neuro_ext124',function:'DLBCLExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BurkittCNSext']=function(input){const score=Math.round((0.18 + Number(input.burkitt||1)*0.2 + Number(input.leptomeningeal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_neuro_ext124',function:'BurkittCNSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntravascularLymphomaExt']=function(input){const score=Math.round((0.18 + Number(input.intravascular||1)*0.2 + Number(input.skin||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_neuro_ext124',function:'IntravascularLymphomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LymphomatoidGranulomatosisExt']=function(input){const score=Math.round((0.18 + Number(input.ebv||1)*0.2 + Number(input.lung||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_neuro_ext124',function:'LymphomatoidGranulomatosisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['NeurolymphomatosisExt']=function(input){const score=Math.round((0.18 + Number(input.nerve||1)*0.2 + Number(input.pain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_neuro_ext124',function:'NeurolymphomatosisExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LeptomeningealCarcExt']=function(input){const score=Math.round((0.18 + Number(input.lung||1)*0.2 + Number(input.breast||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_neuro_ext124',function:'LeptomeningealCarcExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['BrainMetastasesExt']=function(input){const score=Math.round((0.18 + Number(input.number||3)*0.1 + Number(input.size||2)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_neuro_ext124',function:'BrainMetastasesExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ParaneoplasticExt']=function(input){const score=Math.round((0.18 + Number(input.antiHu||1)*0.2 + Number(input.cancer||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.223.0',module:'pcc_neuro_ext124',function:'ParaneoplasticExt',input,score,ts:new Date().toISOString()}};

// TS: v3.223.0
