// Auto-generated by gen_p3ie.py -- PCC v3.185.0
"use strict";
const TS = '2026-07-28T15:00:00Z';

function PediatricTonsillectomyOSASurgExt(input) { const score = Math.round((0.4+Number(input.ahi_pre||20)*0.02)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_surg_ext75', function:'PediatricTonsillectomyOSASurgExt', input, score, ts: TS }; }

function PediatricSupraglottoplastyExt(input) { const score = Math.round((0.4+Number(input.laryngomalacia||2)*0.1)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_surg_ext75', function:'PediatricSupraglottoplastyExt', input, score, ts: TS }; }

function PediatricLaryngotrachealSurgExt(input) { const score = Math.round((0.5+Number(input.subglottic||2)*0.1)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_surg_ext75', function:'PediatricLaryngotrachealSurgExt', input, score, ts: TS }; }

function PediatricBronchoscopyExt(input) { const score = Math.round((0.4+Number(input.fb_count||2)*0.08)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_surg_ext75', function:'PediatricBronchoscopyExt', input, score, ts: TS }; }

function PediatricTrachealReconstructionExt(input) { const score = Math.round((0.5+Number(input.stenosis_cm||1)*0.15)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_surg_ext75', function:'PediatricTrachealReconstructionExt', input, score, ts: TS }; }

function PediatricPEGInsertionExt(input) { const score = Math.round((0.35+Number(input.weight_loss_pct||5)*0.06)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_surg_ext75', function:'PediatricPEGInsertionExt', input, score, ts: TS }; }

function PediatricGJTubesExt(input) { const score = Math.round((0.35+Number(input.feeding_score||3)*0.1)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_surg_ext75', function:'PediatricGJTubesExt', input, score, ts: TS }; }

function PediatricFundoplicationExt(input) { const score = Math.round((0.35+Number(input.reflux_score||3)*0.1)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_surg_ext75', function:'PediatricFundoplicationExt', input, score, ts: TS }; }

function PediatricTracheostomyPlastyExt(input) { const score = Math.round((0.5+Number(input.granulation||1)*0.15)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_surg_ext75', function:'PediatricTracheostomyPlastyExt', input, score, ts: TS }; }

function PediatricChestWallReconstructionExt(input) { const score = Math.round((0.4+Number(input.defect||3)*0.1)*100)/100; return { version:'3.185.0', module:'pcc_pediatric_surg_ext75', function:'PediatricChestWallReconstructionExt', input, score, ts: TS }; }

module.exports = {
  PediatricTonsillectomyOSASurgExt,
  PediatricSupraglottoplastyExt,
  PediatricLaryngotrachealSurgExt,
  PediatricBronchoscopyExt,
  PediatricTrachealReconstructionExt,
  PediatricPEGInsertionExt,
  PediatricGJTubesExt,
  PediatricFundoplicationExt,
  PediatricTracheostomyPlastyExt,
  PediatricChestWallReconstructionExt,
};