// filepath: pcc/pcc_interv_ext101/pcc_interv_ext101_engine.js
module.exports.version='v3.31.31.0';
module.exports.module='pcc_interv_ext101';
module.exports.functions={};
module.exports.functions['IntervPCIext']=function(input){const score=Math.round((0.18 + Number(input.inPCI||1)*0.2 + Number(input.pciVessels||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_interv_ext101',function:'IntervPCIext',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntervTAVIext']=function(input){const score=Math.round((0.18 + Number(input.inTAVI||1)*0.2 + Number(input.taviType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_interv_ext101',function:'IntervTAVIext',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntervMitraClipExt']=function(input){const score=Math.round((0.18 + Number(input.inMitra||1)*0.2 + Number(input.mitraClip||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_interv_ext101',function:'IntervMitraClipExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntervWatchmanExt']=function(input){const score=Math.round((0.18 + Number(input.inWatch||1)*0.2 + Number(input.watchmanSize||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_interv_ext101',function:'IntervWatchmanExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntervAblationExt']=function(input){const score=Math.round((0.18 + Number(input.inAblation||1)*0.2 + Number(input.ablationType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_interv_ext101',function:'IntervAblationExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntervPFOext']=function(input){const score=Math.round((0.18 + Number(input.inPFO||1)*0.2 + Number(input.pfoClosure||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_interv_ext101',function:'IntervPFOext',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntervEVARext']=function(input){const score=Math.round((0.18 + Number(input.inEVAR||1)*0.2 + Number(input.evarType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_interv_ext101',function:'IntervEVARext',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntervTEVARext']=function(input){const score=Math.round((0.18 + Number(input.inTEVAR||1)*0.2 + Number(input.tevarType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_interv_ext101',function:'IntervTEVARext',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntervCarotidExt']=function(input){const score=Math.round((0.18 + Number(input.inCarotid||1)*0.2 + Number(input.carotidSten||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_interv_ext101',function:'IntervCarotidExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['IntervPeripheralExt']=function(input){const score=Math.round((0.18 + Number(input.inPeriph||1)*0.2 + Number(input.periphVessel||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_interv_ext101',function:'IntervPeripheralExt',input,score,ts:new Date().toISOString()}};

// TS: v3.31.31.0
