// Auto-generated by gen_p3master.py -- PCC 3.267.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.267.0';

function EXT1AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.ext1) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_id_ext10', function: 'EXT1AssessmentExt', input, score, ts: TS };
}

function EXT1ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.ext1) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_id_ext10', function: 'EXT1ScoreExt', input, score, ts: TS };
}

function EXT1StageExt(input) {
  const score = Math.round((0.3 + (Number(input.ext1) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_id_ext10', function: 'EXT1StageExt', input, score, ts: TS };
}

function EXT1PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.ext1) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_id_ext10', function: 'EXT1PlanExt', input, score, ts: TS };
}

function EXT1RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.ext1) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_id_ext10', function: 'EXT1RiskExt', input, score, ts: TS };
}

function EXT1DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.ext1) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_id_ext10', function: 'EXT1DoseExt', input, score, ts: TS };
}

function EXT1FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.ext1) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_id_ext10', function: 'EXT1FrequencyExt', input, score, ts: TS };
}

function EXT1DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.ext1) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_id_ext10', function: 'EXT1DurationExt', input, score, ts: TS };
}

function EXT1FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.ext1) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_id_ext10', function: 'EXT1FollowupExt', input, score, ts: TS };
}

function EXT1OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.ext1) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_id_ext10', function: 'EXT1OutcomeExt', input, score, ts: TS };
}

module.exports = {
  EXT1AssessmentExt,
  EXT1ScoreExt,
  EXT1StageExt,
  EXT1PlanExt,
  EXT1RiskExt,
  EXT1DoseExt,
  EXT1FrequencyExt,
  EXT1DurationExt,
  EXT1FollowupExt,
  EXT1OutcomeExt,
};