// filepath: pcc/pcc_cardiosurg_ext101/pcc_cardiosurg_ext101_engine.js
module.exports.version='v3.31.31.0';
module.exports.module='pcc_cardiosurg_ext101';
module.exports.functions={};
module.exports.functions['CABGext']=function(input){const score=Math.round((0.18 + Number(input.csCABG||1)*0.2 + Number(input.cabgGrafts||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_cardiosurg_ext101',function:'CABGext',input,score,ts:new Date().toISOString()}};
module.exports.functions['ValveSurgeryExt']=function(input){const score=Math.round((0.18 + Number(input.csValve||1)*0.2 + Number(input.valveSurgType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_cardiosurg_ext101',function:'ValveSurgeryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AorticSurgeryExt']=function(input){const score=Math.round((0.18 + Number(input.csAortic||1)*0.2 + Number(input.aorticType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_cardiosurg_ext101',function:'AorticSurgeryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AorticDissectExt']=function(input){const score=Math.round((0.18 + Number(input.csDissect||1)*0.2 + Number(input.dissectType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_cardiosurg_ext101',function:'AorticDissectExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['HeartTransplantExt']=function(input){const score=Math.round((0.18 + Number(input.csHTx||1)*0.2 + Number(input.htxStatus||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_cardiosurg_ext101',function:'HeartTransplantExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LVADext']=function(input){const score=Math.round((0.18 + Number(input.csLVAD||1)*0.2 + Number(input.lvadType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_cardiosurg_ext101',function:'LVADext',input,score,ts:new Date().toISOString()}};
module.exports.functions['CongenitalSurgeryExt']=function(input){const score=Math.round((0.18 + Number(input.csCongenital||1)*0.2 + Number(input.congenitalType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_cardiosurg_ext101',function:'CongenitalSurgeryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PericardialSurgeryExt']=function(input){const score=Math.round((0.18 + Number(input.csPericard||1)*0.2 + Number(input.pericardialSurgType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_cardiosurg_ext101',function:'PericardialSurgeryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CardiacTraumaExt']=function(input){const score=Math.round((0.18 + Number(input.csTrauma||1)*0.2 + Number(input.cardiacTraumaType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_cardiosurg_ext101',function:'CardiacTraumaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CardiacTumorExt']=function(input){const score=Math.round((0.18 + Number(input.csTumor||1)*0.2 + Number(input.cardiacTumorType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.31.31.0',module:'pcc_cardiosurg_ext101',function:'CardiacTumorExt',input,score,ts:new Date().toISOString()}};

// TS: v3.31.31.0
