// Auto-generated by gen_p3master.py -- PCC 3.304.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.304.0';

function X336AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x336) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_336', function: 'X336AssessmentExt', input, score, ts: TS };
}

function X336ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x336) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_336', function: 'X336ScoreExt', input, score, ts: TS };
}

function X336StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x336) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_336', function: 'X336StageExt', input, score, ts: TS };
}

function X336PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x336) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_336', function: 'X336PlanExt', input, score, ts: TS };
}

function X336RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x336) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_336', function: 'X336RiskExt', input, score, ts: TS };
}

function X336DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x336) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_336', function: 'X336DoseExt', input, score, ts: TS };
}

function X336FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x336) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_336', function: 'X336FrequencyExt', input, score, ts: TS };
}

function X336DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x336) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_336', function: 'X336DurationExt', input, score, ts: TS };
}

function X336FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x336) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_336', function: 'X336FollowupExt', input, score, ts: TS };
}

function X336OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x336) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_336', function: 'X336OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X336AssessmentExt,
  X336ScoreExt,
  X336StageExt,
  X336PlanExt,
  X336RiskExt,
  X336DoseExt,
  X336FrequencyExt,
  X336DurationExt,
  X336FollowupExt,
  X336OutcomeExt,
};