// Auto-generated by gen_p3master.py -- PCC 3.196.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.196.0';

function EXT8AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.ext8) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_pulm_ext8', function: 'EXT8AssessmentExt', input, score, ts: TS };
}

function EXT8ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.ext8) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_pulm_ext8', function: 'EXT8ScoreExt', input, score, ts: TS };
}

function EXT8StageExt(input) {
  const score = Math.round((0.3 + (Number(input.ext8) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_pulm_ext8', function: 'EXT8StageExt', input, score, ts: TS };
}

function EXT8PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.ext8) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_pulm_ext8', function: 'EXT8PlanExt', input, score, ts: TS };
}

function EXT8RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.ext8) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_pulm_ext8', function: 'EXT8RiskExt', input, score, ts: TS };
}

function EXT8DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.ext8) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_pulm_ext8', function: 'EXT8DoseExt', input, score, ts: TS };
}

function EXT8FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.ext8) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_pulm_ext8', function: 'EXT8FrequencyExt', input, score, ts: TS };
}

function EXT8DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.ext8) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_pulm_ext8', function: 'EXT8DurationExt', input, score, ts: TS };
}

function EXT8FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.ext8) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_pulm_ext8', function: 'EXT8FollowupExt', input, score, ts: TS };
}

function EXT8OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.ext8) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_pulm_ext8', function: 'EXT8OutcomeExt', input, score, ts: TS };
}

module.exports = {
  EXT8AssessmentExt,
  EXT8ScoreExt,
  EXT8StageExt,
  EXT8PlanExt,
  EXT8RiskExt,
  EXT8DoseExt,
  EXT8FrequencyExt,
  EXT8DurationExt,
  EXT8FollowupExt,
  EXT8OutcomeExt,
};