// Auto_generated by gen_p3hd.py -- PCC v3.172.0
"use strict";
const TS = '2026-07-28T12:50:00Z';

function PediatricTBIExt(input) { const score = Math.round((0.4+Number(input.gcs_pedi||6)*0.05)*100)/100; return { version:'3.172.0', module:'pcc_pediatric_neuro_ext62', function:"PediatricTBIExt", input, score, ts: TS }; }

function PediatricConcussionExt(input) { const score = Math.round((0.3+Number(input.symptom_count||3)*0.08)*100)/100; return { version:'3.172.0', module:'pcc_pediatric_neuro_ext62', function:"PediatricConcussionExt", input, score, ts: TS }; }

function PediatricPostConcussionExt(input) { const score = Math.round((0.35+Number(input.days_since||14)*0.012)*100)/100; return { version:'3.172.0', module:'pcc_pediatric_neuro_ext62', function:"PediatricPostConcussionExt", input, score, ts: TS }; }

function PediatricChronicTBIExt(input) { const score = Math.round((0.4+Number(input.tep_count||2)*0.07)*100)/100; return { version:'3.172.0', module:'pcc_pediatric_neuro_ext62', function:"PediatricChronicTBIExt", input, score, ts: TS }; }

function PediatricSkullFractureExt(input) { const score = Math.round((0.4+Number(input.depression||2)*0.1)*100)/100; return { version:'3.172.0', module:'pcc_pediatric_neuro_ext62', function:"PediatricSkullFractureExt", input, score, ts: TS }; }

function PediatricEpiduralHematomaExt(input) { const score = Math.round((0.45+Number(input.thickness||8)*0.03)*100)/100; return { version:'3.172.0', module:'pcc_pediatric_neuro_ext62', function:"PediatricEpiduralHematomaExt", input, score, ts: TS }; }

function PediatricSubduralHematomaExt(input) { const score = Math.round((0.45+Number(input.thickness||8)*0.03)*100)/100; return { version:'3.172.0', module:'pcc_pediatric_neuro_ext62', function:"PediatricSubduralHematomaExt", input, score, ts: TS }; }

function PediatricTraumaticSAHExt(input) { const score = Math.round((0.5+Number(input.fisher||2)*0.08)*100)/100; return { version:'3.172.0', module:'pcc_pediatric_neuro_ext62', function:"PediatricTraumaticSAHExt", input, score, ts: TS }; }

function PediatricDiffuseAxonalInjuryExt(input) { const score = Math.round((0.5+Number(input.lesions||3)*0.08)*100)/100; return { version:'3.172.0', module:'pcc_pediatric_neuro_ext62', function:"PediatricDiffuseAxonalInjuryExt", input, score, ts: TS }; }

function PediatricCerebralEdemaExt(input) { const score = Math.round((0.45+Number(input.midline_shift||3)*0.07)*100)/100; return { version:'3.172.0', module:'pcc_pediatric_neuro_ext62', function:"PediatricCerebralEdemaExt", input, score, ts: TS }; }

module.exports = {
  PediatricTBIExt,
  PediatricConcussionExt,
  PediatricPostConcussionExt,
  PediatricChronicTBIExt,
  PediatricSkullFractureExt,
  PediatricEpiduralHematomaExt,
  PediatricSubduralHematomaExt,
  PediatricTraumaticSAHExt,
  PediatricDiffuseAxonalInjuryExt,
  PediatricCerebralEdemaExt,
};