-- CARD-006 Migration UP

BEGIN;

CREATE TABLE CARD-006 (id UUID PK, tenant_id UUID FK, patient_id BIGINT, ...);
ALTER TABLE CARD-006 ENABLE ROW LEVEL SECURITY;
ALTER TABLE CARD-006 FORCE ROW LEVEL SECURITY;
CREATE POLICY CARD-006_tenant ON CARD-006 USING (tenant_id = current_setting('app.tenant_id')::UUID);

-- +6 tables

COMMIT;
