// filepath: pcc/pcc_pediatric_neuro_ext154/pcc_pediatric_neuro_ext154_engine.js
module.exports.version='v3.264.0';
module.exports.module='pcc_pediatric_neuro_ext154';
module.exports.functions={};
module.exports.functions['PediatricBPPVext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pBPPV||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_pediatric_neuro_ext154',function:'PediatricBPPVext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVestNeurExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pVestNeur||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_pediatric_neuro_ext154',function:'PediatricVestNeurExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMeniereExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pMeniere||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_pediatric_neuro_ext154',function:'PediatricMeniereExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLabyrinthExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.pLab||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_pediatric_neuro_ext154',function:'PediatricLabyrinthExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricMigraineVertExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pMigVert||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_pediatric_neuro_ext154',function:'PediatricMigraineVertExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricOtitisVertigoExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.omVertigo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_pediatric_neuro_ext154',function:'PediatricOtitisVertigoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCholesteatomaExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cholesteatoma||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_pediatric_neuro_ext154',function:'PediatricCholesteatomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricCPvertigoExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.cpVertigo||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_pediatric_neuro_ext154',function:'PediatricCPvertigoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTumorVertigoExt']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.pTumorVert||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_pediatric_neuro_ext154',function:'PediatricTumorVertigoExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVisualVertigoExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.visualVert||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.264.0',module:'pcc_pediatric_neuro_ext154',function:'PediatricVisualVertigoExt',input,score,ts:new Date().toISOString()}};

// TS: v3.264.0
