// filepath: pcc/pcc_pediatric_surg_ext83/pcc_pediatric_surg_ext83_engine.js
// pcc_pediatric_surg_ext83 engine (deterministic)
module.exports.version='v3.193.0';
module.exports.module='pcc_pediatric_surg_ext83';
module.exports.functions={};
module.exports.functions['PediatricBrainTumorResectExt']=function(input){const score=Math.round((0.18 + Number(input.extent||1)*0.2 + Number(input.complications||2)*0.1 + Number(input.location||2)*0.1)*100)/100;return{version:'v3.193.0',module:'pcc_pediatric_surg_ext83',function:'PediatricBrainTumorResectExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricPosteriorFossaExt']=function(input){const score=Math.round((0.18 + Number(input.approach||1)*0.2 + Number(input.syndrome||1)*0.15 + Number(input.csf||1)*0.15)*100)/100;return{version:'v3.193.0',module:'pcc_pediatric_surg_ext83',function:'PediatricPosteriorFossaExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSupratentorialExt']=function(input){const score=Math.round((0.18 + Number(input.approach||1)*0.2 + Number(input.motor||1)*0.15 + Number(input.outcome||1)*0.15)*100)/100;return{version:'v3.193.0',module:'pcc_pediatric_surg_ext83',function:'PediatricSupratentorialExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricBrainstemBiopsyExt']=function(input){const score=Math.round((0.18 + Number(input.approach||1)*0.2 + Number(input.target||3)*0.1 + Number(input.outcome||1)*0.15)*100)/100;return{version:'v3.193.0',module:'pcc_pediatric_surg_ext83',function:'PediatricBrainstemBiopsyExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricEndoscopicThirdVentriculostomyExt']=function(input){const score=Math.round((0.15 + Number(input.age||6)*0.04 + Number(input.etvss||70)*0.005 + Number(input.outcome||1)*0.15)*100)/100;return{version:'v3.193.0',module:'pcc_pediatric_surg_ext83',function:'PediatricEndoscopicThirdVentriculostomyExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricTumorShuntExt']=function(input){const score=Math.round((0.15 + Number(input.approach||1)*0.15 + Number(input.age||5)*0.04 + Number(input.outcome||1)*0.15)*100)/100;return{version:'v3.193.0',module:'pcc_pediatric_surg_ext83',function:'PediatricTumorShuntExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricSpinalTumorResectExt']=function(input){const score=Math.round((0.18 + Number(input.levels||2)*0.1 + Number(input.compression||1)*0.2 + Number(input.motor||3)*0.05)*100)/100;return{version:'v3.193.0',module:'pcc_pediatric_surg_ext83',function:'PediatricSpinalTumorResectExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricIntraopNeuroMonitorExt']=function(input){const score=Math.round((0.15 + Number(input.modalities||4)*0.05 + Number(input.alerts||3)*0.05 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.193.0',module:'pcc_pediatric_surg_ext83',function:'PediatricIntraopNeuroMonitorExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricAwakeCraniotomyExt']=function(input){const score=Math.round((0.15 + Number(input.age||14)*0.02 + Number(input.cooperation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.193.0',module:'pcc_pediatric_surg_ext83',function:'PediatricAwakeCraniotomyExt',input,score,ts:new Date().toISOString()};};
module.exports.functions['PediatricRadioOncSurgExt']=function(input){const score=Math.round((0.15 + Number(input.doseGy||54)*0.005 + Number(input.field||2)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.193.0',module:'pcc_pediatric_surg_ext83',function:'PediatricRadioOncSurgExt',input,score,ts:new Date().toISOString()};};

// TS: v3.193.0
