-- adm_105 reverse
BEGIN;
DROP TABLE IF EXISTS adm_105_results CASCADE;
DROP TABLE IF EXISTS adm_105_orders  CASCADE;
DROP TABLE IF EXISTS adm_105_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_ADM_105_up';
COMMIT;
