// filepath: pcc/pcc_pharmacovigilance_ext102/pcc_pharmacovigilance_ext102_engine.js
module.exports.version='v3.40.40.0';
module.exports.module='pcc_pharmacovigilance_ext102';
module.exports.functions={};
module.exports.functions['PVReportingExt']=function(input){const score=Math.round((0.18 + Number(input.pvReport||1)*0.2 + Number(input.pvReportType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_pharmacovigilance_ext102',function:'PVReportingExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PVSignalExt']=function(input){const score=Math.round((0.18 + Number(input.pvSignal||1)*0.2 + Number(input.pvSignalStrength||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_pharmacovigilance_ext102',function:'PVSignalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PVADRadultExt']=function(input){const score=Math.round((0.18 + Number(input.pvADR||1)*0.2 + Number(input.pvAdrType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_pharmacovigilance_ext102',function:'PVADRadultExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PVPeriodicExt']=function(input){const score=Math.round((0.18 + Number(input.pvPSUR||1)*0.2 + Number(input.pvPsurType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_pharmacovigilance_ext102',function:'PVPeriodicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PVRiskMgmtExt']=function(input){const score=Math.round((0.18 + Number(input.pvRMP||1)*0.2 + Number(input.pvRmpType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_pharmacovigilance_ext102',function:'PVRiskMgmtExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PVVaccineExt']=function(input){const score=Math.round((0.18 + Number(input.pvVacc||1)*0.2 + Number(input.pvVaccType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_pharmacovigilance_ext102',function:'PVVaccineExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PVDeviceExt']=function(input){const score=Math.round((0.18 + Number(input.pvDevice||1)*0.2 + Number(input.pvDeviceType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_pharmacovigilance_ext102',function:'PVDeviceExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PVMedErrorExt']=function(input){const score=Math.round((0.18 + Number(input.pvError||1)*0.2 + Number(input.pvErrorType||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_pharmacovigilance_ext102',function:'PVMedErrorExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PVLackEfficacyExt']=function(input){const score=Math.round((0.18 + Number(input.pvLoE||1)*0.2 + Number(input.pvLoeDrug||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_pharmacovigilance_ext102',function:'PVLackEfficacyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PVPregnancyExt']=function(input){const score=Math.round((0.18 + Number(input.pvPreg||1)*0.2 + Number(input.pvPregTrimest||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.40.40.0',module:'pcc_pharmacovigilance_ext102',function:'PVPregnancyExt',input,score,ts:new Date().toISOString()}};

// TS: v3.40.40.0
