// Auto-generated by gen_p3hf.py -- PCC v3.174.0
"use strict";
const TS = '2026-07-28T13:10:00Z';

function PediatricThymectomyExt(input) { const score = Math.round((0.4+Number(input.thymus_size||3)*0.08)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_surg_ext64', function:'PediatricThymectomyExt', input, score, ts: TS }; }

function PediatricPlasmapheresisExt(input) { const score = Math.round((0.35+Number(input.exchanges||5)*0.06)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_surg_ext64', function:'PediatricPlasmapheresisExt', input, score, ts: TS }; }

function PediatricIVIGExt(input) { const score = Math.round((0.3+Number(input.dose_gkg||1)*0.15)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_surg_ext64', function:'PediatricIVIGExt', input, score, ts: TS }; }

function PediatricImmunoablativeTherapyExt(input) { const score = Math.round((0.45+Number(input.cycle_count||2)*0.1)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_surg_ext64', function:'PediatricImmunoablativeTherapyExt', input, score, ts: TS }; }

function PediatricRituximabNMJExt(input) { const score = Math.round((0.4+Number(input.dose_mg||375)*0.0006)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_surg_ext64', function:'PediatricRituximabNMJExt', input, score, ts: TS }; }

function PediatricECulizumabExt(input) { const score = Math.round((0.5+Number(input.dose_mg||600)*0.0005)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_surg_ext64', function:'PediatricECulizumabExt', input, score, ts: TS }; }

function PediatricFcRNTreatmentExt(input) { const score = Math.round((0.5+Number(input.dose_mg||340)*0.0008)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_surg_ext64', function:'PediatricFcRNTreatmentExt', input, score, ts: TS }; }

function PediatricPlasmapheresisCathExt(input) { const score = Math.round((0.35+Number(input.catheter||1)*0.1)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_surg_ext64', function:'PediatricPlasmapheresisCathExt', input, score, ts: TS }; }

function PediatricNMJDietExt(input) { const score = Math.round((0.3+Number(input.calories||1500)*0.0002)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_surg_ext64', function:'PediatricNMJDietExt', input, score, ts: TS }; }

function PediatricSwallowingAssessExt(input) { const score = Math.round((0.3+Number(input.aspiration_score||2)*0.1)*100)/100; return { version:'3.174.0', module:'pcc_pediatric_surg_ext64', function:'PediatricSwallowingAssessExt', input, score, ts: TS }; }

module.exports = {
  PediatricThymectomyExt,
  PediatricPlasmapheresisExt,
  PediatricIVIGExt,
  PediatricImmunoablativeTherapyExt,
  PediatricRituximabNMJExt,
  PediatricECulizumabExt,
  PediatricFcRNTreatmentExt,
  PediatricPlasmapheresisCathExt,
  PediatricNMJDietExt,
  PediatricSwallowingAssessExt,
};