// filepath: pcc/pcc_neuro_ext140/pcc_neuro_ext140_engine.js
module.exports.version='v3.239.0';
module.exports.module='pcc_neuro_ext140';
module.exports.functions={};
module.exports.functions['PostoperativeStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.surgeryType||1)*0.2 + Number(input.embolic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_neuro_ext140',function:'PostoperativeStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CardiacSurgeryStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.cabg||1)*0.2 + Number(input.afib||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_neuro_ext140',function:'CardiacSurgeryStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CEAStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.cea||1)*0.2 + Number(input.embolism||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_neuro_ext140',function:'CEAStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PostOpDeliriumExt']=function(input){const score=Math.round((0.18 + Number(input.age||70)*0.005 + Number(input.delirium||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_neuro_ext140',function:'PostOpDeliriumExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PostOpCognitiveDysfunctionExt']=function(input){const score=Math.round((0.18 + Number(input.surgery||1)*0.2 + Number(input.cognitive||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_neuro_ext140',function:'PostOpCognitiveDysfunctionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['AnesthesiaRelatedExt']=function(input){const score=Math.round((0.18 + Number(input.anesthesia||1)*0.2 + Number(input.toxicity||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_neuro_ext140',function:'AnesthesiaRelatedExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PropofolInfusionExt']=function(input){const score=Math.round((0.18 + Number(input.propofol||1)*0.2 + Number(input.dose||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_neuro_ext140',function:'PropofolInfusionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LocalAnesthesiaToxExt']=function(input){const score=Math.round((0.18 + Number(input.localAnesth||1)*0.2 + Number(input.toxicity||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_neuro_ext140',function:'LocalAnesthesiaToxExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MalignantHyperthermiaExt']=function(input){const score=Math.round((0.18 + Number(input.succinylcholine||1)*0.2 + Number(input.fever||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_neuro_ext140',function:'MalignantHyperthermiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SerotoninSyndromeExt']=function(input){const score=Math.round((0.18 + Number(input.ssri||1)*0.2 + Number(input.mental||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.239.0',module:'pcc_neuro_ext140',function:'SerotoninSyndromeExt',input,score,ts:new Date().toISOString()}};

// TS: v3.239.0
