// filepath: pcc/pcc_neuro_ext178/pcc_neuro_ext178_engine.js
module.exports.version='v3.1.7.0';
module.exports.module='pcc_neuro_ext178';
module.exports.functions={};
module.exports.functions['NeuroPainChronicExt']=function(input){const score=Math.round((0.18 + Number(input.chronicPain||1)*0.2 + Number(input.neuropathic||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_neuro_ext178',function:'NeuroPainChronicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CRPSext']=function(input){const score=Math.round((0.18 + Number(input.crps||1)*0.2 + Number(input.allodynia||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_neuro_ext178',function:'CRPSext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PostHerpeticNeuralgiaExt']=function(input){const score=Math.round((0.18 + Number(input.phn||1)*0.2 + Number(input.shingles||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_neuro_ext178',function:'PostHerpeticNeuralgiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['TrigeminalNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.tgn||1)*0.2 + Number(input.trigeminal||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_neuro_ext178',function:'TrigeminalNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['DiabeticNeuropathicExt']=function(input){const score=Math.round((0.18 + Number(input.dpn||1)*0.2 + Number(input.dmNeuro||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_neuro_ext178',function:'DiabeticNeuropathicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['FibromyalgiaExt']=function(input){const score=Math.round((0.18 + Number(input.fibromyalgia||1)*0.2 + Number(input.tender||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_neuro_ext178',function:'FibromyalgiaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CentralPostStrokeExt']=function(input){const score=Math.round((0.18 + Number(input.cpsp||1)*0.2 + Number(input.postStrokePain||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_neuro_ext178',function:'CentralPostStrokeExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PhantomLimbExt']=function(input){const score=Math.round((0.18 + Number(input.phantom||1)*0.2 + Number(input.amputation||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_neuro_ext178',function:'PhantomLimbExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['LowBackNeuroExt']=function(input){const score=Math.round((0.18 + Number(input.lbpNeuro||1)*0.2 + Number(input.radicular||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_neuro_ext178',function:'LowBackNeuroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['MigraineChronicExt']=function(input){const score=Math.round((0.18 + Number(input.cm||1)*0.2 + Number(input.headacheDays||1)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.1.7.0',module:'pcc_neuro_ext178',function:'MigraineChronicExt',input,score,ts:new Date().toISOString()}};

// TS: v3.1.7.0
