// filepath: pcc/pcc_neuro_ext115/pcc_neuro_ext115_engine.js
module.exports.version='v3.214.0';
module.exports.module='pcc_neuro_ext115';
module.exports.functions={};
module.exports.functions['TraumaticBrainInjuryExt']=function(input){const score=Math.round((0.18 + Number(input.gcs||8)*0.04 + Number(input.ct||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_neuro_ext115',function:'TraumaticBrainInjuryExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['ConcussionExt']=function(input){const score=Math.round((0.18 + Number(input.sport||1)*0.2 + Number(input.symptoms||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_neuro_ext115',function:'ConcussionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PostConcussionExt']=function(input){const score=Math.round((0.18 + Number(input.days||30)*0.01 + Number(input.symptoms||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_neuro_ext115',function:'PostConcussionExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SubduralHematomaExt']=function(input){const score=Math.round((0.18 + Number(input.thickness||10)*0.04 + Number(input.midline||5)*0.04 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_neuro_ext115',function:'SubduralHematomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['EpiduralHematomaExt']=function(input){const score=Math.round((0.18 + Number(input.thickness||10)*0.04 + Number(input.skullFracture||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_neuro_ext115',function:'EpiduralHematomaExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SubarachnoidTraumaticExt']=function(input){const score=Math.round((0.18 + Number(input.fisher||2)*0.1 + Number(input.huntHess||2)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_neuro_ext115',function:'SubarachnoidTraumaticExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['DiffuseAxonalExt']=function(input){const score=Math.round((0.18 + Number(input.gcs||6)*0.04 + Number(input.mri||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_neuro_ext115',function:'DiffuseAxonalExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PenetratingBrainExt']=function(input){const score=Math.round((0.18 + Number(input.gcs||8)*0.04 + Number(input.vasospasm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_neuro_ext115',function:'PenetratingBrainExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['SkullBaseFractureExt']=function(input){const score=Math.round((0.18 + Number(input.csfLeak||1)*0.2 + Number(input.cranialNerve||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_neuro_ext115',function:'SkullBaseFractureExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['CSFleakExt']=function(input){const score=Math.round((0.18 + Number(input.location||1)*0.2 + Number(input.pressure||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.214.0',module:'pcc_neuro_ext115',function:'CSFleakExt',input,score,ts:new Date().toISOString()}};

// TS: v3.214.0
