// Auto-generated by gen_p3if.py -- PCC v3.186.0
"use strict";
const TS = '2026-07-28T15:10:00Z';

function CognitiveDisorderExt(input) { const score = Math.round((0.3+Number(input.moca_score||22)*0.03)*100)/100; return { version:'3.186.0', module:'pcc_neuro_ext87', function:'CognitiveDisorderExt', input, score, ts: TS }; }

function AnosognosiaExt(input) { const score = Math.round((0.4+Number(input.awareness_score||2)*0.15)*100)/100; return { version:'3.186.0', module:'pcc_neuro_ext87', function:'AnosognosiaExt', input, score, ts: TS }; }

function ApraxiaExt(input) { const score = Math.round((0.35+Number(input.apraxia_score||3)*0.1)*100)/100; return { version:'3.186.0', module:'pcc_neuro_ext87', function:'ApraxiaExt', input, score, ts: TS }; }

function AgnosiaExt(input) { const score = Math.round((0.35+Number(input.agnosia_score||3)*0.1)*100)/100; return { version:'3.186.0', module:'pcc_neuro_ext87', function:'AgnosiaExt', input, score, ts: TS }; }

function ExecutiveDysfunctionExt(input) { const score = Math.round((0.35+Number(input.tmt_b_seconds||90)*0.005)*100)/100; return { version:'3.186.0', module:'pcc_neuro_ext87', function:'ExecutiveDysfunctionExt', input, score, ts: TS }; }

function MemoryDisorderExt(input) { const score = Math.round((0.3+Number(input.memory_score||40)*0.012)*100)/100; return { version:'3.186.0', module:'pcc_neuro_ext87', function:'MemoryDisorderExt', input, score, ts: TS }; }

function VisuospatialExt(input) { const score = Math.round((0.35+Number(input.vsp_score||30)*0.015)*100)/100; return { version:'3.186.0', module:'pcc_neuro_ext87', function:'VisuospatialExt', input, score, ts: TS }; }

function LanguageDisorderExt(input) { const score = Math.round((0.35+Number(input.naming_score||40)*0.012)*100)/100; return { version:'3.186.0', module:'pcc_neuro_ext87', function:'LanguageDisorderExt', input, score, ts: TS }; }

function BehavioralDysexecutiveExt(input) { const score = Math.round((0.4+Number(input.disinhibition||2)*0.15)*100)/100; return { version:'3.186.0', module:'pcc_neuro_ext87', function:'BehavioralDysexecutiveExt', input, score, ts: TS }; }

function SocialCognitionExt(input) { const score = Math.round((0.4+Number(input.social_score||3)*0.08)*100)/100; return { version:'3.186.0', module:'pcc_neuro_ext87', function:'SocialCognitionExt', input, score, ts: TS }; }

module.exports = {
  CognitiveDisorderExt,
  AnosognosiaExt,
  ApraxiaExt,
  AgnosiaExt,
  ExecutiveDysfunctionExt,
  MemoryDisorderExt,
  VisuospatialExt,
  LanguageDisorderExt,
  BehavioralDysexecutiveExt,
  SocialCognitionExt,
};