// filepath: pcc/pcc_pediatric_neuro_ext107/pcc_pediatric_neuro_ext107_engine.js
module.exports.version='v3.217.0';
module.exports.module='pcc_pediatric_neuro_ext107';
module.exports.functions={};
module.exports.functions['PediatricBellPalsyExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.houseBrack||3)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_neuro_ext107',function:'PediatricBellPalsyExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRHExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.vesicle||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_neuro_ext107',function:'PediatricRHExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricTNExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.v1||1)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_neuro_ext107',function:'PediatricTNExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGPNExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.throat||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_neuro_ext107',function:'PediatricGPNExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricVagusExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.hoarseness||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_neuro_ext107',function:'PediatricVagusExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricRLNext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.unilateral||1)*0.1 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_neuro_ext107',function:'PediatricRLNext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSLNext']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.sensory||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_neuro_ext107',function:'PediatricSLNext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPhrenicExt']=function(input){const score=Math.round((0.18 + Number(input.age||3)*0.04 + Number(input.hemidiaphragm||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_neuro_ext107',function:'PediatricPhrenicExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricLTExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.winging||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_neuro_ext107',function:'PediatricLTExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSANExt']=function(input){const score=Math.round((0.18 + Number(input.age||5)*0.04 + Number(input.trapezius||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.217.0',module:'pcc_pediatric_neuro_ext107',function:'PediatricSANExt',input,score,ts:new Date().toISOString()}};

// TS: v3.217.0
