// Auto_generated by gen_p3hc.py -- PCC v3.171.0
"use strict";
const TS = '2026-07-28T12:40:00Z';

function PediatricCNSInfectionExt(input) { const score = Math.round((0.4+Number(input.csf_cells||100)*0.001)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_neuro_ext61', function:"PediatricCNSInfectionExt", input, score, ts: TS }; }

function PediatricEncephalitisExt(input) { const score = Math.round((0.4+Number(input.acid||0)*0.15)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_neuro_ext61', function:"PediatricEncephalitisExt", input, score, ts: TS }; }

function PediatricMeningitisExt(input) { const score = Math.round((0.35+Number(input.csf_wbc||500)*0.0004)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_neuro_ext61', function:"PediatricMeningitisExt", input, score, ts: TS }; }

function PediatricBrainAbscessExt(input) { const score = Math.round((0.4+Number(input.abscess_volume||3)*0.05)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_neuro_ext61', function:"PediatricBrainAbscessExt", input, score, ts: TS }; }

function PediatricSpinalEpiduralAbscessExt(input) { const score = Math.round((0.45+Number(input.abscess_length||3)*0.05)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_neuro_ext61', function:"PediatricSpinalEpiduralAbscessExt", input, score, ts: TS }; }

function PediatricCerebritisExt(input) { const score = Math.round((0.4+Number(input.fever||1)*0.08)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_neuro_ext61', function:"PediatricCerebritisExt", input, score, ts: TS }; }

function PediatricPostInfectiousExt(input) { const score = Math.round((0.45+Number(input.antibody||0)*0.1)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_neuro_ext61', function:"PediatricPostInfectiousExt", input, score, ts: TS }; }

function PediatricRASMeningitisExt(input) { const score = Math.round((0.45+Number(input.csf_pressure||30)*0.01)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_neuro_ext61', function:"PediatricRASMeningitisExt", input, score, ts: TS }; }

function PediatricTBMExt(input) { const score = Math.round((0.45+Number(input.csf_glucose||40)*0.005)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_neuro_ext61', function:"PediatricTBMExt", input, score, ts: TS }; }

function PediatricFungalMeningitisExt(input) { const score = Math.round((0.45+Number(input.csf_protein||100)*0.002)*100)/100; return { version:'3.171.0', module:'pcc_pediatric_neuro_ext61', function:"PediatricFungalMeningitisExt", input, score, ts: TS }; }

module.exports = {
  PediatricCNSInfectionExt,
  PediatricEncephalitisExt,
  PediatricMeningitisExt,
  PediatricBrainAbscessExt,
  PediatricSpinalEpiduralAbscessExt,
  PediatricCerebritisExt,
  PediatricPostInfectiousExt,
  PediatricRASMeningitisExt,
  PediatricTBMExt,
  PediatricFungalMeningitisExt,
};