// Auto-generated by gen_p3hi.py -- PCC v3.177.0
"use strict";
const TS = '2026-07-28T13:40:00Z';

function PediatricTBIRehabExt(input) { const score = Math.round((0.3+Number(input.disability_score||2)*0.1)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_neuro_ext67', function:'PediatricTBIRehabExt', input, score, ts: TS }; }

function PediatricSCIRecoveryExt(input) { const score = Math.round((0.4+Number(input.ais_level||1)*0.15)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_neuro_ext67', function:'PediatricSCIRecoveryExt', input, score, ts: TS }; }

function PediatricStrokeRehabExt(input) { const score = Math.round((0.35+Number(input.pediatric_outcome||3)*0.08)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_neuro_ext67', function:'PediatricStrokeRehabExt', input, score, ts: TS }; }

function PediatricBotoxExt(input) { const score = Math.round((0.3+Number(input.muscles||3)*0.07)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_neuro_ext67', function:'PediatricBotoxExt', input, score, ts: TS }; }

function PediatricFESExt(input) { const score = Math.round((0.3+Number(input.channels||2)*0.08)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_neuro_ext67', function:'PediatricFESExt', input, score, ts: TS }; }

function PediatricPressureUlcerExt(input) { const score = Math.round((0.4+Number(input.braden_score||16)*0.02)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_neuro_ext67', function:'PediatricPressureUlcerExt', input, score, ts: TS }; }

function PediatricNeuroBladderMgmtExt(input) { const score = Math.round((0.35+Number(input.catheter_type||1)*0.15)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_neuro_ext67', function:'PediatricNeuroBladderMgmtExt', input, score, ts: TS }; }

function PediatricWheelchairExt(input) { const score = Math.round((0.3+Number(input.chair_score||3)*0.08)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_neuro_ext67', function:'PediatricWheelchairExt', input, score, ts: TS }; }

function PediatricNeuroAssistExt(input) { const score = Math.round((0.3+Number(input.devices||2)*0.1)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_neuro_ext67', function:'PediatricNeuroAssistExt', input, score, ts: TS }; }

function PediatricOPRehabExt(input) { const score = Math.round((0.3+Number(input.sessions||8)*0.03)*100)/100; return { version:'3.177.0', module:'pcc_pediatric_neuro_ext67', function:'PediatricOPRehabExt', input, score, ts: TS }; }

module.exports = {
  PediatricTBIRehabExt,
  PediatricSCIRecoveryExt,
  PediatricStrokeRehabExt,
  PediatricBotoxExt,
  PediatricFESExt,
  PediatricPressureUlcerExt,
  PediatricNeuroBladderMgmtExt,
  PediatricWheelchairExt,
  PediatricNeuroAssistExt,
  PediatricOPRehabExt,
};