// Auto_generated by gen_p3gz.py -- PCC v3.168.0
"use strict";
const TS = '2026-07-28T12:10:00Z';

function PediatricHeadacheExt(input) { const score = Math.round((0.3+Number(input.frequency||2)*0.04)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_neuro_ext58', function:"PediatricHeadacheExt", input, score, ts: TS }; }

function PediatricMigraineExt(input) { const score = Math.round((0.4+Number(input.headache_days||5)*0.03)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_neuro_ext58', function:"PediatricMigraineExt", input, score, ts: TS }; }

function PediatricClusterHeadacheExt(input) { const score = Math.round((0.45+Number(input.attacks||1)*0.1)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_neuro_ext58', function:"PediatricClusterHeadacheExt", input, score, ts: TS }; }

function PediatricTensionHeadacheExt(input) { const score = Math.round((0.25+Number(input.stress_score||3)*0.05)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_neuro_ext58', function:"PediatricTensionHeadacheExt", input, score, ts: TS }; }

function PediatricTrigeminalExt(input) { const score = Math.round((0.4+Number(input.paroxysms||5)*0.04)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_neuro_ext58', function:"PediatricTrigeminalExt", input, score, ts: TS }; }

function PediatricMOHExt(input) { const score = Math.round((0.4+Number(input.days_per_month||10)*0.03)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_neuro_ext58', function:"PediatricMOHExt", input, score, ts: TS }; }

function PediatricThunderclapHeadacheExt(input) { const score = Math.round((0.5+Number(input.severity_peak||10)*0.04)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_neuro_ext58', function:"PediatricThunderclapHeadacheExt", input, score, ts: TS }; }

function PediatricCervicogenicExt(input) { const score = Math.round((0.3+Number(input.tender_points||2)*0.08)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_neuro_ext58', function:"PediatricCervicogenicExt", input, score, ts: TS }; }

function PediatricPostConcussionExt(input) { const score = Math.round((0.35+Number(input.pcss_score||15)*0.025)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_neuro_ext58', function:"PediatricPostConcussionExt", input, score, ts: TS }; }

function PediatricIIHHeadacheExt(input) { const score = Math.round((0.4+Number(input.opening_pressure||20)*0.014)*100)/100; return { version:'3.168.0', module:'pcc_pediatric_neuro_ext58', function:"PediatricIIHHeadacheExt", input, score, ts: TS }; }

module.exports = {
  PediatricHeadacheExt,
  PediatricMigraineExt,
  PediatricClusterHeadacheExt,
  PediatricTensionHeadacheExt,
  PediatricTrigeminalExt,
  PediatricMOHExt,
  PediatricThunderclapHeadacheExt,
  PediatricCervicogenicExt,
  PediatricPostConcussionExt,
  PediatricIIHHeadacheExt,
};