-- Migration DOWN: P0-2_COMMAND_CENTER

DROP POLICY IF EXISTS cc_eq_tenant_isolation ON cc_equipment;
ALTER TABLE cc_equipment NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cc_equipment DISABLE ROW LEVEL SECURITY;
DROP TABLE IF EXISTS cc_equipment CASCADE;

DROP POLICY IF EXISTS cc_mci_tenant_isolation ON cc_mci_events;
ALTER TABLE cc_mci_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cc_mci_events DISABLE ROW LEVEL SECURITY;
DROP TABLE IF EXISTS cc_mci_events CASCADE;

DROP POLICY IF EXISTS cc_or_tenant_isolation ON cc_or_schedule;
ALTER TABLE cc_or_schedule NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cc_or_schedule DISABLE ROW LEVEL SECURITY;
DROP TABLE IF EXISTS cc_or_schedule CASCADE;

DROP POLICY IF EXISTS cc_ed_tenant_isolation ON cc_ed_visits;
ALTER TABLE cc_ed_visits NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cc_ed_visits DISABLE ROW LEVEL SECURITY;
DROP TABLE IF EXISTS cc_ed_visits CASCADE;

DROP POLICY IF EXISTS cc_beds_tenant_isolation ON cc_beds;
ALTER TABLE cc_beds NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cc_beds DISABLE ROW LEVEL SECURITY;
DROP TABLE IF EXISTS cc_beds CASCADE;
