// Auto-generated by gen_p3master.py -- PCC 3.274.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.274.0';

function EXT5AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.ext5) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_path_ext5', function: 'EXT5AssessmentExt', input, score, ts: TS };
}

function EXT5ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.ext5) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_path_ext5', function: 'EXT5ScoreExt', input, score, ts: TS };
}

function EXT5StageExt(input) {
  const score = Math.round((0.3 + (Number(input.ext5) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_path_ext5', function: 'EXT5StageExt', input, score, ts: TS };
}

function EXT5PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.ext5) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_path_ext5', function: 'EXT5PlanExt', input, score, ts: TS };
}

function EXT5RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.ext5) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_path_ext5', function: 'EXT5RiskExt', input, score, ts: TS };
}

function EXT5DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.ext5) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_path_ext5', function: 'EXT5DoseExt', input, score, ts: TS };
}

function EXT5FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.ext5) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_path_ext5', function: 'EXT5FrequencyExt', input, score, ts: TS };
}

function EXT5DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.ext5) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_path_ext5', function: 'EXT5DurationExt', input, score, ts: TS };
}

function EXT5FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.ext5) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_path_ext5', function: 'EXT5FollowupExt', input, score, ts: TS };
}

function EXT5OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.ext5) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_path_ext5', function: 'EXT5OutcomeExt', input, score, ts: TS };
}

module.exports = {
  EXT5AssessmentExt,
  EXT5ScoreExt,
  EXT5StageExt,
  EXT5PlanExt,
  EXT5RiskExt,
  EXT5DoseExt,
  EXT5FrequencyExt,
  EXT5DurationExt,
  EXT5FollowupExt,
  EXT5OutcomeExt,
};