// Auto-generated by gen_p3master.py -- PCC 3.312.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.312.0';

function X360AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x360) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_360', function: 'X360AssessmentExt', input, score, ts: TS };
}

function X360ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x360) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_360', function: 'X360ScoreExt', input, score, ts: TS };
}

function X360StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x360) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_360', function: 'X360StageExt', input, score, ts: TS };
}

function X360PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x360) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_360', function: 'X360PlanExt', input, score, ts: TS };
}

function X360RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x360) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_360', function: 'X360RiskExt', input, score, ts: TS };
}

function X360DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x360) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_360', function: 'X360DoseExt', input, score, ts: TS };
}

function X360FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x360) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_360', function: 'X360FrequencyExt', input, score, ts: TS };
}

function X360DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x360) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_360', function: 'X360DurationExt', input, score, ts: TS };
}

function X360FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x360) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_360', function: 'X360FollowupExt', input, score, ts: TS };
}

function X360OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x360) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_gen_360', function: 'X360OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X360AssessmentExt,
  X360ScoreExt,
  X360StageExt,
  X360PlanExt,
  X360RiskExt,
  X360DoseExt,
  X360FrequencyExt,
  X360DurationExt,
  X360FollowupExt,
  X360OutcomeExt,
};