-- obg_102 reverse
BEGIN;
DROP TABLE IF EXISTS obg_102_results CASCADE;
DROP TABLE IF EXISTS obg_102_orders  CASCADE;
DROP TABLE IF EXISTS obg_102_visits  CASCADE;
DELETE FROM schema_migrations WHERE id = 'p3_OBG_102_up';
COMMIT;
