// filepath: pcc/pcc_pediatric_neuro_ext114/pcc_pediatric_neuro_ext114_engine.js
module.exports.version='v3.224.0';
module.exports.module='pcc_pediatric_neuro_ext114';
module.exports.functions={};
module.exports.functions['PediatricTNExt2']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.tn||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_pediatric_neuro_ext114',function:'PediatricTNExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricAnesthesiaDoloroExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.v1||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_pediatric_neuro_ext114',function:'PediatricAnesthesiaDoloroExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPHNext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.hzv||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_pediatric_neuro_ext114',function:'PediatricPHNext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricONext2']=function(input){const score=Math.round((0.18 + Number(input.age||8)*0.04 + Number(input.occipital||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_pediatric_neuro_ext114',function:'PediatricONext2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricGPNExt2']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.pharynx||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_pediatric_neuro_ext114',function:'PediatricGPNExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricNIext']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.ear||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_pediatric_neuro_ext114',function:'PediatricNIext',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricClusterExt2']=function(input){const score=Math.round((0.18 + Number(input.age||12)*0.02 + Number(input.attack||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_pediatric_neuro_ext114',function:'PediatricClusterExt2',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSUNCExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.short||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_pediatric_neuro_ext114',function:'PediatricSUNCExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricSUNAExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.face||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_pediatric_neuro_ext114',function:'PediatricSUNAExt',input,score,ts:new Date().toISOString()}};
module.exports.functions['PediatricPHExt']=function(input){const score=Math.round((0.18 + Number(input.age||10)*0.04 + Number(input.abs||1)*0.2 + Number(input.outcome||1)*0.2)*100)/100;return{version:'v3.224.0',module:'pcc_pediatric_neuro_ext114',function:'PediatricPHExt',input,score,ts:new Date().toISOString()}};

// TS: v3.224.0
