// Auto-generated by gen_p3master.py -- PCC 3.286.0
"use strict";
const TS = '2026-07-29T14:00:00Z';
const VER = '3.286.0';

function X280AssessmentExt(input) {
  const score = Math.round((0.3 + (Number(input.x280) || 0) * 0.25) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_280', function: 'X280AssessmentExt', input, score, ts: TS };
}

function X280ScoreExt(input) {
  const score = Math.round((0.3 + (Number(input.x280) || 0) * 0.36) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_280', function: 'X280ScoreExt', input, score, ts: TS };
}

function X280StageExt(input) {
  const score = Math.round((0.3 + (Number(input.x280) || 0) * 0.37) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_280', function: 'X280StageExt', input, score, ts: TS };
}

function X280PlanExt(input) {
  const score = Math.round((0.3 + (Number(input.x280) || 0) * 0.33) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_280', function: 'X280PlanExt', input, score, ts: TS };
}

function X280RiskExt(input) {
  const score = Math.round((0.3 + (Number(input.x280) || 0) * 0.34) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_280', function: 'X280RiskExt', input, score, ts: TS };
}

function X280DoseExt(input) {
  const score = Math.round((0.3 + (Number(input.x280) || 0) * 0.35) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_280', function: 'X280DoseExt', input, score, ts: TS };
}

function X280FrequencyExt(input) {
  const score = Math.round((0.3 + (Number(input.x280) || 0) * 0.26) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_280', function: 'X280FrequencyExt', input, score, ts: TS };
}

function X280DurationExt(input) {
  const score = Math.round((0.3 + (Number(input.x280) || 0) * 0.22) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_280', function: 'X280DurationExt', input, score, ts: TS };
}

function X280FollowupExt(input) {
  const score = Math.round((0.3 + (Number(input.x280) || 0) * 0.23) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_280', function: 'X280FollowupExt', input, score, ts: TS };
}

function X280OutcomeExt(input) {
  const score = Math.round((0.3 + (Number(input.x280) || 0) * 0.19) * 100) / 100;
  return { version: VER, module: 'pcc_auto_ext_280', function: 'X280OutcomeExt', input, score, ts: TS };
}

module.exports = {
  X280AssessmentExt,
  X280ScoreExt,
  X280StageExt,
  X280PlanExt,
  X280RiskExt,
  X280DoseExt,
  X280FrequencyExt,
  X280DurationExt,
  X280FollowupExt,
  X280OutcomeExt,
};